### ISSUE TITLE
Consider making categories based on tags for England, Wales, Scotland and Northern Ireland

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1001]
This would have the effect of stressing which part of the UK a body is based in, or applies to. This might reduce the occurrence of misdirected requests arising as a result of similarly named bodies in different parts of the UK. 

Arguments against is that 

* so-far we've not used categories in this way, so this use might be surprising. 
* we don't have a big problem with misdirected requests arising as a result of similarly named bodies in different parts of the UK. 

See also:

* Flags for nations of the UK on pages for bodies, and requests to bodies, where the body has a tag for that nation #824 
* Regionalise the front page for visitors from nations and regions of the UK #825

**Comment by garethrees** [comment]
I like this idea. Could also create one for United Kingdom for national authorities.
