### ISSUE TITLE
Rename this repository WhatDoTheyKnow

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1002]
This would reflect the wider use being made of the issue tracker to cover site policy, promotion and activism and might help with operating clearly in-public and engaging a wider group of people in discussions about running the service. 

I have no idea of the consequences of such a change and if it is practical.

**Comment by garethrees** [comment]
Couple of off the cuff thoughts:

* Would need to update site deploy scripts.
* Would issue URLs referenced elsewhere break? I think GitHub handles rename redirects, but would want to check.
* I don't think there's any requirement for a theme repo to be named `*theme`
