### ISSUE TITLE
Review coverage of Welsh schools

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1010]
Compare [Wales's list of schools](https://gov.wales/address-list-schools) with [GIaS](https://get-information-schools.service.gov.uk/).  If there are differences, it could be used as a starting-point for improving the coverage of schools in Wales.

I'd note that Wales's list of schools doesn't contain email addresses, but then nor does the public GIaS.

(I'm splitting this from the email discussion, which is now mainly about Scottish schools.)

**Comment by WilliamWDTK** [comment]
The file is [address-list-schools-wales.ods](https://github.com/mysociety/whatdotheyknow-theme/files/8136685/address-list-schools-wales.ods).

**Tabs**
1. T1: can be ignored (count of schools)
1. T2: can be ignored (count of schools)
1. T3: can be ignored (count of schools)
1. T4: can be ignored (count of schools)
1. T5: can be ignored (count of schools)
1. A gynhelir: Welsh, probably matches up with 9
1. Annibynnol: Welsh, probably matches up with 10
3. UCD: Welsh, probably matches up with 11
4. Maintained: List: Maintained Schools (Nursery/Primary/Middle/Secondary/Special)
5. Independent: List: Independent Schools
6. PRU: List: Pupil Referral Units
7. N1: Notes: These will probably be useful
8. N2: Licence details (OGL v3)

**Fields available**
Maintained: School Number | School Name | LA Code | Local Authority | Sector | Governance - see notes | WM Code | Welsh Medium Type - see notes | School Type | Religious Character | Address 1 | Address 2 | Address 3 | Address 4 | Postcode | Phone Number | Pupils - see notes

E.G. 6772277 | Beaufort Hill Primary | 677 | Blaenau Gwent | Primary | Community | EM | English medium | Nursery, Infants & Juniors | --- | Beaufort Hill | Ebbw Vale | Blaenau Gwent |   | NP23 5QD | 01495 302624 | 253
matches [`urn:401407`](https://get-information-schools.service.gov.uk/Establishments/Establishment/Details/401407).  The School Number matches the DfE number field (minus the slash).  In the GIAS download, it is in two fields: LA (code) and EstablishmentNumber, so combining these two will give the Welsh list's School Number.

**Comment by WilliamWDTK** [comment]
Total Welsh schools on GIAS: 1588
Total in Welsh Government's sheet: 1472 maintained + 83 independent + 21 PRUs = 1576
1588≠1576

**Comment by RichardTaylor** [comment]
Linking to #808

**Comment by WilliamWDTK** [comment]
I've created a cross-language conflated list of Maintained schools from the Welsh Gov's list (an updated version I just downloaded, I'm not sure if there were any changes.  I will next try to compare it with a GIaS extract, and then with WDTK.  I think we don't want to list independent schools, and there's only a handful of PRUs.

[conflated-maintained.csv](https://github.com/mysociety/whatdotheyknow-theme/files/8599939/conflated-maintained.csv)

The column headers are explained below:

  | From EN | From CY
-- | -- | --
lac | LA Code | Cod ALl
schn | School Number | Rhif yr ysgol
snmEN | School Name | -
snmCY | - | Enw’r ysgol
laEN | Local Authority | -
laCY | - | Awdurdod Lleol
sctEN | Sector | -
sctCY | - | Sector
wmEN | WM Code | -
wmCY | - | Cod CC
ad1EN | Address 1 | -
ad2EN | Address 2 | -
ad3EN | Address 3 | -
ad4EN | Address 4 | -
ad1CY | - | Cyfeiriad 1
ad2CY | - | Cyfeiriad 2
ad3CY | - | Cyfeiriad 3
ad4CY | - | Cyfeiriad 4
pc | Postcode | Cod post
note |   |  


</body>

</html>

**Comment by WilliamWDTK** [comment]
I've not included all of the available fields here, but hopefully that's not a problem.

**Comment by WilliamWDTK** [comment]
I think it might be worth closing this (unless anyone objects/wants to take it on themself), since the total numbers of schools in each database are so similar, the differences are likely to be small.
