### ISSUE TITLE
Error in refusal advice for section 12 for aggregated requests

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1011]
A single character change is required at

https://github.com/mysociety/whatdotheyknow-theme/blob/87ae3cda57763b453d552ff2c54061f165203776/config/refusal_advice/section_12_actions.yml.erb#L40

>"up to 20 days ‘backwards’ 

needs changing to 

>"up to 60 days ‘backwards’

to bring it in-line with paragraph 50 of the linked reference from the ICO. 

This error was reported by a WhatDoTheyKnow user.

**Comment by mdeuk** [comment]
I've raised a pull request for this - a nice easy change.
