### ISSUE TITLE
Consider listing Returning Officers and Electoral Registration Offices / Officers

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1014]
Returning Officers and Electoral Registration Offices / Officers are not subject to FOI, but we might want to list them anyway given their public, state, functions. 

In practice we'd probably want to list the elections team contact addresses from lower tier councils 

One reason for not listing them is that requests made to councils generally get forwarded to the elections team anyway so a separate listing wouldn't achieve much, and give us an extra maintenance overhead. 

An argument for listing is that it would collect requests, and refusals, together, helping make the case for making these organisations subject to FOI, or making them proactively operate more transparently.   

This is a long standing point of discussion but not one we've added to the public repository before as far as I can see. 

Example refusal letter:

https://www.whatdotheyknow.com/request/818482/response/1948411/attach/2/Response%20not%20held.pdf?cookie_passthrough=1

**Comment by RichardTaylor** [comment]
Linking:

* https://github.com/mysociety/whatdotheyknow-theme/issues/1558

**Comment by RichardTaylor** [comment]
Consider if we're listing the actual returning officer who often is only ceremonial, or the "acting returning officer" who actually does the work.  We probably want the "acting returning officers".

**Comment by confirmordeny** [comment]
Now listed here: https://wdtkwiki.mysociety.org/wiki/Authority_suggestions
