### ISSUE TITLE
NHS : CCG aboliton and move to ICB / ICP model from 1 July 2022

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1022]
As described at:

https://digital.nhs.uk/services/organisation-data-service/integrated-care-boards

**Comment by RichardTaylor** [comment]
Integrated Care Boards have been added comprehensively as forthcoming bodies:

https://www.whatdotheyknow.com/body/list/icb


Internal spreadsheet:
https://docs.google.com/spreadsheets/d/1ycnubdKksGwGsUnKT_SaNRCq8UakIgs46oQOJ6iduXs/edit#gid=0

**Comment by RichardTaylor** [comment]
STPs 

https://www.whatdotheyknow.com/body/list/stp

will also cease to exist when ICB / ICPs come into being.

**Comment by mdeuk** [comment]
> Integrated Care Boards have been added comprehensively as forthcoming bodies:
> 
> https://www.whatdotheyknow.com/body/list/icb

For mass changes such as this in the past, we've often asked the public body themselves if they have the relevant contact details - I wonder if this is a solution that would work here?

We can do this via mass email and perhaps collate updates via a Google form to allow us to then have the bodies 'go live' at the right time.

**Comment by mdeuk** [comment]
This ticket is an another example of where #818 and https://github.com/mysociety/alaveteli/issues/235 would make a difference - having geographic information could allow for better targetting of requests, particularly where 'fringe' areas are of interest.

**Comment by RichardTaylor** [comment]
Plan:
* List ICPs comprehensively en-masse as forthcoming bodies ASAP 
* At end of 30 June 
  *  Tag CCGs and STPs defunct
  * Remove forthcoming tag from ICBs and ICPs which have it
 * On 1 July
   * Check each of the 42 new area's websites and update contact details, websites etc. Track this work with a shared spreadsheet. 
   * Tweet when we're in a good position, maybe ask for help pointing to "ask us to update FOI email" links. 
   * Possible tweet noting greater openness arising from the changes, STPs have denied being subject to the act [as recently has an ICS (perhaps with more justification than STPs?)](https://www.whatdotheyknow.com/request/committee_meeting_minutes_at_our#incoming-2055371). 
   

>We can do this via mass email 

Because there are many more CCGs than new ICB/P/Ss I don't think it would be appropriate to email all CCGs and ask for email contacts for their successor bodies. We could. It might be best just to work from the web though and that's what I propose.

**Comment by FOIMonkey** [comment]
List of which CCGs are going to be replaced by which ICBs: https://nhssbs.support.tradeshift.com/knowledgebase/article/360012631220

**Comment by RichardTaylor** [comment]
Note the City of London Integrated Care Partnership Board and Integrated Commissioning Board 
 https://democracy.cityoflondon.gov.uk/ieListMeetings.aspx?CommitteeId=1247 

At the time of writing it is a "committee-in-common" of  is a Committee in-
Common meeting of the: The London Borough of Hackney Integrated Commissioning Sub-Committee, The City of London Corporation Integrated Commissioning Sub-Committee and North East London CCG City and Hackney ICP Area Committee. 

When North East London CCG is replaced by the NHS North East London Integrated Care Board presumably it will take the CCGs place on this committee. 

Listed at 

https://www.whatdotheyknow.com/body/city_of_london_integrated_care_partnership_board

**Comment by RichardTaylor** [comment]
>List ICPs comprehensively en-masse as forthcoming bodies ASAP

Done:
https://www.whatdotheyknow.com/body/list/icp

Removed bodies called Integrated Care Partnerships which aren't ICPs under [the new definition](https://www.legislation.gov.uk/ukpga/2022/31/part/1/crossheading/integrated-care-partnerships/enacted) from that tag. 


It's looking like we might want to list some Integrated Care Systems where they have names, contact addresses, websites, members etc. which make them appear to be public bodies in their own rights, not just a descriptive term for the ICB + ICP.

**Comment by RichardTaylor** [comment]
Outstanding issues here:

* Some ICB email addresses are not yet working. 
* Almost all ICPs are yet to be set up by the looks of it

All the body changes other than getting all the email addresses up-to-date have been completed though. Getting the emails up-to-date is now routine work which should be prompted by users/bodies getting in touch I think, so we can close the ticket. 

We could do a bulk review of ICPs say three months in. We can set a scheduled message to prompt that in the WDTK mailbox - I'll set one up.
