### ISSUE TITLE
Pitch to Information Commissioner for collaboration on access to information

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1024]
Make the case to the Information Commissioner that it would be great if they would collaborate with WhatDoTheyKnow on:

* [Enabling FOI referrals to the ICO to be made within WhatDoTheyKnow](https://github.com/mysociety/alaveteli/issues/2819).
* Using WhatDoTheyKnow to detect bodies with poor FOI performance.
* Reducing the frequency of data breaches associated with FOI responses. 
* Informing people of their rights under access to information legislation and helping them exercise those rights. 

Both WhatDoTheyKnow and the Information Commissioner are seeking to make access to information legislation effective.

**Comment by FOIMonkey** [comment]
For want of a better place to note this, a user said that they rang the ICO and "The person I spoke to had heard of WDTK, but was not really familiar with how it works."

Better collaboration would help us to change that.

**Comment by HelenWDTK** [comment]
Closing as complete
