### ISSUE TITLE
Improve help page text related to calculating deadlines

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1027]
A user has noted the text:

>if the day the request email was delivered was a non-working day, we count the next working day as “day one”. Delivery is delivery, even if it happened on the weekend. Some authorities [disagree with this](http://www.whatdotheyknow.com/request/policy_regarding_body_scans#incoming-1100), our lawyer disagrees with them. 

https://www.whatdotheyknow.com/help/officers#days

isn't great as it doesn't explain why our lawyer disagrees with them. 

The text in question is probably very old text, and the key thing which matters now is the ICO guidance on the subject. Presumably there is now a consistent interpretation of the law taken by us, the ICO, most public bodies, and the courts?

The relevant ICO guidance is 

https://ico.org.uk/media/for-organisations/documents/1165/time-for-compliance-foia-guidance.pdf

>If the request is received on a non-working day, the clock will still start on the following working day

Proposed new text:

>if the day the request email was delivered was a non-working day, the next working day is counted as “day one”.

  
We already state:

>If you’d like to know more, read the [detailed ICO guidance](https://ico.org.uk/media/for-organisations/documents/1165/time-for-compliance-foia-guidance.pdf).

That could become

>If you’d like to know more, see the [detailed ICO guidance](https://ico.org.uk/media/for-organisations/documents/1165/time-for-compliance-foia-guidance.pdf) which is in-line with the approach we take.

I also don't think it is obvious this section is best under "officers", this is information which both users and officers may want. (Related:  #883 )

**Comment by mdeuk** [comment]
> A user has noted the text:
> 
> The text in question is probably very old text, and the key thing which matters now is the ICO guidance on the subject. Presumably there is now a consistent interpretation of the law taken by us, the ICO, most public bodies, and the courts?
> 
> The relevant ICO guidance is
> 
> https://ico.org.uk/media/for-organisations/documents/1165/time-for-compliance-foia-guidance.pdf
> 
> > If the request is received on a non-working day, the clock will still start on the following working day

It's important that we note the technical definition from FoIA 2000:

  _"[s10(6)](https://www.legislation.gov.uk/ukpga/2000/36/section/10#section-10-6): …     “the date of receipt” means—
    (a) the day on which the public authority receives the request for information, or
    (b) if later, the day on which it receives the information referred to in section 1(3);
  
  “working day” means any day other than a Saturday, a Sunday, Christmas Day, Good Friday or a day which is a bank holiday under the [Banking and Financial Dealings Act 1971](https://www.legislation.gov.uk/ukpga/1971/80/contents) in any part of the United Kingdom. "_

FoISA 2002 has a _slightly_ different definition: 

_"[s73](https://www.legislation.gov.uk/asp/2002/13/section/73): “working day” means any day other than a Saturday, a Sunday, Christmas Day or a day which, under the Banking and Financial Dealings Act 1971 (c.80), is a bank holiday in Scotland. "_

We already deal with bank holidays generally, are we giving weekends the same regard?

**Comment by RichardTaylor** [comment]
>It's important that we note the technical definition from FoIA 2000

The linked guidance quotes from and links to the act, so I think on that basis just linking to the guidance is OK. I usually prefer the most direct reference, but here I was actually wanting to point to how the law is being interpreted. 

>FoISA 2002 has a slightly different definition:

The ICO guidance doesn't cover that, and [the guidance from the Scottish Information Commissioner on the subject of timescales ](https://www.itspublicknowledge.info/FAQ/PublicAuthorityFAQ/TimescalesFAQ.aspx)doesn't cover the issue of which day is the first day. 

Does WhatDoTheyKnow generally use the correct definition of a working day when dealing with timescales for requests to Scottish bodies? I can see we had a [Scotland specific change during covid](https://github.com/mysociety/whatdotheyknow-theme/issues/672), but are there generally Scottish specific calculations?

New proposal for the second piece of proposed new text:

>If you’d like to know more, see the [detailed ICO guidance](https://ico.org.uk/media/for-organisations/documents/1165/time-for-compliance-foia-guidance.pdf) which is in-line with the approach we take. Note [the definition of a working day is slightly different in Scotland than in the rest of the UK](https://www.itspublicknowledge.info/FAQ/PublicAuthorityFAQ/TimescalesFAQ.aspx#workingDay). 


Also while we're on this text there's a space needed at:
> differently.Since 

>We already deal with bank holidays generally, are we giving weekends the same regard?

The system treats weekends as non-working days.
