### ISSUE TITLE
Check if the whatdotheyknow-only category on the mySociety blog still has its intended effect

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1031]
https://www.mysociety.org/category/archived/whatdotheyknow-only/

The function of this category was to enable blogs relating to WhatDoTheyKnow to be published without them appearing on the mySociety blog front page.  The reason was so we don't have to reduce the rate of WhatDoTheyKnow blogs to prevent overwhelming the mySociety blog with too many of them, compared with other content.

**Comment by garethrees** [comment]
Doesn't answer the question, but to add some info here, we currently set this [config value](https://alaveteli.org/docs/customising/config/#blog_feed) for WDTK:

```yaml
BLOG_FEED: https://www.mysociety.org/category/projects/whatdotheyknow/feed/
```
