### ISSUE TITLE
Help page section on requests for material from datasets

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1032]
The "dataset" provisions of FOI are powerful.

If anyone requests an element of a dataset that prompts a requirement for a public body to publish that dataset, and keep the published dataset up to date.

>Under [Section 19(2A) of the Freedom of Information Act](https://www.legislation.gov.uk/ukpga/2000/36/section/19) public bodies are required to publish:
>* (i)any dataset held by the authority in relation to which a person makes a request for information to the authority, and
>* (ii)any up-dated version held by the authority of such a dataset

This is excellent as a FOI request can prompt ongoing proactive publication covering far more information than might have been initially requested.

**Comment by garethrees** [comment]
There's potentially some light "research" we could do here, using WDTK itself, to identify requests where this provision ought to have been enacted, as a means to flesh out a blog post to promote this fact.
