### ISSUE TITLE
Comprehensively list Safeguarding Adults Boards on WhatDoTheyKnow 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1033]
Legislation requiring these boards:

https://www.legislation.gov.uk/ukpga/2014/23/section/43/enacted

We have a few listed already 

https://www.whatdotheyknow.com/body/list/lsab

Some areas have combined Adult and Children safeguarding organisations, we can tag them both lcsp and lsab

Possible list of boards:

https://www.anncrafttrust.org/resources/find-your-nearest-safeguarding-adults-board/

**Comment by confirmordeny** [comment]
We might want to add these as signposts.

**Comment by HelenWDTK** [comment]
https://wdtkwiki.mysociety.org/wiki/Authority_suggestions
