### ISSUE TITLE
Confusing phrasing of Legal basis for processing

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1035]
Our section on [Legal basis for processing](https://www.whatdotheyknow.com/help/privacy#legal_basis) states:

> In most cases our legal basis for processing personal information is "legitimate interest"…

It then goes on to say (em mine)…

> We believe that our processing of our users’ data is as they would expect when they use our service. If you use WhatDoTheyKnow to make a FOI request, you are **consenting** to your data being processed as described on this page.

I don't think this is accurate, since we process all GDPR RTE requests under the legal basis of Legitimate Interests.

**Comment by RichardTaylor** [comment]
I agree. 

We could just delete:

>, you are consenting to your data being processed as described on this page.
