### ISSUE TITLE
Creating legitimate interest factors library

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1040]
To assist when we are conducting legitimate interest balance tests and writing the responses.

We already have guidance on how to conduct these here: https://wiki.mysociety.org/wiki/WhatDoTheyKnow_GDPR_legitimate_interests_test

This library would contain the statements that we use within the tests when drafting a using the basic response template:https://docs.google.com/document/d/1tCdtJyYKJIgrRq-DC8PeCPPdz6txkDIff109GltAF4M/edit#

This will help to save time having to type up the statements again and also ensure consistency.

The library could be stored be in the wiki, or be linked from the wiki to an easy to look up to a relevant document.  This would need to be indexed in a way that it can be easily searched.
>These could be grouped by the type of information “Name Removal”, “Address Removal”
>Or they could be group by type of individual making the request "FOI Officer, HMO Landlords, Public Body Officers,  member of the public, (I'm sure that there are more to add here'

The library would then be used to look up and use the statements relevant to that particular case, and can be added to over time.

During the canned response review, I made a start on this in relation to HMO Landlords, but it needs more work https://docs.google.com/document/d/1FQPiwlUKT2CVLvhtACESg0RG3rPUm_NSskxI0pF1ysM/edit#

The statements that we have previously used can be found in the responses stored in the GDPR and Information rights folder and could be used to start the library https://drive.google.com/drive/folders/13Ao0HiF3zoabj4YebUovBXuvHP2Mr0Wl

**Comment by mdeuk** [comment]
+1, an idea I had some time back was to start a "phrase bank" - no two cases are the same and, quite rightly, each warrants a decision based on its own individual merits - but that doesn't mean doing everything from scratch. If we put together our 'best' answers we can then have some tools which help us to make the right decision first time - and hopefully then reduce second/third stage.

A helpful way of looking at this might be to look at the refusal advice tool - a more 'rough and ready' solution is as simple as a flowchart with some copy/paste.

**Comment by MyfanwyNixon** [comment]
I'm just looking at this now. 
How functional do we want it to be? It feels like the sort of thing that someone with more technical expertise than me could make into a database that allowed you to filter by conditions such as the type of correspondent and the type of information. Unfortunately, I don't have those skills myself so it'd be a very clunky Google doc or spreadsheet. Might be worth collaring a couple of hours of a developers' time before bringing me in to wrangle the copy?

**Comment by mdeuk** [comment]
> I'm just looking at this now.
> How functional do we want it to be? It feels like the sort of thing that someone with more technical expertise than me could make into a database that allowed you to filter by conditions such as the type of correspondent and the type of information. Unfortunately, I don't have those skills myself so it'd be a very clunky Google doc or spreadsheet. Might be worth collaring a couple of hours of a developers' time before bringing me in to wrangle the copy?

A clunky Google doc would give us the basis for anything more technical down the line - we can possibly do what we need in GSuite itself, but if I’m honest I haven’t looked into this ticket at all yet.

**Comment by garethrees** [comment]
> it'd be a very clunky Google doc or spreadsheet

+1 to @mdeuk's note. The first step in this is actually just documenting what we've used in the past, so that's fine (I _think_ preferably a doc, but whatever ends up working best).

We definitely don't have time to build and maintain a software app for this. We could consider something off the shelf like Airtable, but equally would be good to use something we already use rather than another new tool.

The main thing here is just understanding what the scale of our "library" might look like. It may be small enough that  we ca fit all the ones we've used in our standard template to delete as applicable – or it may be 100s of points that might warrant a cleverer solution. No idea right now.

**Comment by RichardTaylor** [comment]
>The statements that we have previously used can be found in the responses stored in the GDPR and Information rights folder

and also in the inbox, in the review and wdtk-legal mailboxes and on the wiki.

**Comment by sallytay** [comment]
This is a great start thank you.

I'll review it properly next week and then when we are all happy we can get it moved over into the WDTK shared drive. I'm sure it will evolve as we use it with more additions.

Sally

**Comment by garethrees** [comment]
Amazing! Such a level-up!

**Comment by sallytay** [comment]
I've added the document to the WDTK shared drive https://docs.google.com/document/d/1IWyNP_RxXJZwyZ41ANBgNtZ-9eWP_-p876EgIwYDmHQ/edit#heading=h.gjdgxs

I'm sure that we will continue to add to this as we use it.

I've updated the WDTK Wiki pages for canned responses and WhatDoTheyKnow GDPR legitimate interests test with a link to help with being able to find it easily.

**Comment by RichardTaylor** [comment]
* A section on information relating to regulated professionals would be a good addition. 

* We should also link to this new document from the relevant place in the GDPR Legitimate Interest Response template where these snippets are to be used.

**Comment by sallytay** [comment]
>We should also link to this new document from the relevant place in the GDPR Legitimate Interest Response template where these snippets are to be used.

I've done this.

>A section on information relating to regulated professionals would be a good addition.

As I'm doing a response related this, once we this is completed I can add these elements in

**Comment by RichardTaylor** [comment]
>We already have guidance on how to conduct these here: https://wiki.mysociety.org/wiki/WhatDoTheyKnow_GDPR_legitimate_interests_test

That's a link to the mySociety wiki, which for some reason has an old copy of the WDTK policy on it, the current WDTK policy is at:

https://wdtkwiki.mysociety.org/wiki/WhatDoTheyKnow_GDPR_legitimate_interests_test

**Comment by garethrees** [comment]
I think the main crux of this issue has been completed, so new improvements should be new issues.
