### ISSUE TITLE
Create default text for GDPR complaint reviews when we agree with original decision

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1041]
To help with complaint responses.

Have a default text for the statement when we agree with the original decision.

I've put together some recent examples here: that could be worked into default text https://docs.google.com/document/d/1JZzPV07VO4kApI1NJK6od_ZRrLR9Zz3wWRbaJFOhQjU/edit

**Comment by mdeuk** [comment]
+1

This sounds like something we should be doing via templates (which can be customised by the tracker). There is some pre-existing code which could be enhanced to do this.

**Comment by MyfanwyNixon** [comment]
I've drafted a response here: https://docs.google.com/document/d/1pqM-wNKPSoMYuKsthXHH3jMhsiaNOmbxvZXuw1L1w2s/edit
You may have to request access if you're outside the mySoc staff team.

**Comment by sallytay** [comment]
Thank you @MyfanwyNixon 

I've added the WDTK Support inbox to the access list, so hopefully people will be able to access the document when using this log in

**Comment by HelenWDTK** [comment]
Closing as complete via template
