### ISSUE TITLE
Consider commercial use policy for WhatDoTheyKnow

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1043]
WhatDoTheyKnow currently permits unlimited commercial use of its free public service. 

Often commercial users make heavy use of the service, resulting in significant work for staff and volunteers. 

Our position to-date has been that we're happy to support this use on the grounds we're largely getting prompted to keep our bodies database up-to-date which is something we want to do anyway, and published FOI responses are of use to all. 

We also support commercial use of FOI and WDTK as being something which we think can lead to public benefit. 

We do see examples of poor commercial use, and sometimes commercial use which breaches our house rules and has led to bans/suspensions. Often commercial users will use multiple accounts, perhaps to spread work between individual staff, but also perhaps to evade rate caps. 

Often, but not always, commercial users aren't very helpful when it comes to researching what has gone wrong and eg. finding out if a body still exists or proposing a new email address for a body. 

Elsewhere at mySociety on the TheyWorkForYou and MapIt APIs a free tier of service requiring registration is only made available to "registered charities, or individuals pursuing a non-profit project on an unpaid basis", and those eligible for that free tier are given 50% off higher level access.  The public websites are freely available to all. 

A commercial user with a £10 WhatDoTheyKnow Pro account can easily make use of the service costing many tens of times what they are paying to support. 

Linked closely to:  https://github.com/mysociety/alaveteli/issues/6806

Noting commercial users are often seeking public sector contact details so https://github.com/mysociety/alaveteli/issues/10 is related. 

We do want to promote the service to commercial users: https://github.com/mysociety/whatdotheyknow-theme/issues/941

There are many potential features which might attract / be of use to commercial users including https://github.com/mysociety/whatdotheyknow-theme/issues/985 and https://github.com/mysociety/alaveteli/issues/2500

**Comment by FOIMonkey** [comment]
> Often commercial users will use multiple accounts, perhaps to spread work between individual staff, but also perhaps to evade rate caps.
I have noticed this happening quite often. It's easy to spot as the questions are identical.

I wanted to add a few observations from classifying:

- The majority of unclassified requests seem to come from Pro/Commercial users. As they tend to request in bulk, the burden of them not classifying is greater.
- Commercial users/pro users seem much more likely to "abandon" requests by ignoring requests for clarification/delivery errors.
- Commercial users are often much less careful that they are asking the right body for information

I think all of the above is because commercial users/journalists often do not care too much about the success of any one response in particular, as long as enough responses are received before a set deadline. 

Current commercial users often ask for the same types of information repeatedly, despite the datasets being published and regularly updated eg NNDR, Empty Commercial Property, Structure Charts, Fleet Management, Public Health Funerals, contact details. There is limited value to the responses received to these requests as they are usually just a link to the information.

Commercial Users also frequently include their company information and a mini sales pitch in the body of the request, meaning that we are effectively giving them free advertising by hosting these.

**Comment by FOIMonkey** [comment]
Some public authorities are now refusing to answer requests that they consider to be commercial eg https://www.whatdotheyknow.com/request/finance_procurement_systems_2#incoming-1772027

**Comment by RichardTaylor** [comment]
Anecdotally around a third of FOI use is commercial. I don't know if that includes commercial journalistic use. 

Some bodies record and report FOI statistics broken down by category of requester. 

Breakdown of FOI requests by type of applicant by Swansea Council in 2017-18

<img width="672" alt="Screenshot 2022-03-16 at 02 14 03" src="https://user-images.githubusercontent.com/547695/158503187-2e84d265-4763-4106-9989-9f7df6cf0a36.png">

https://democracy.swansea.gov.uk/documents/s53003/09%205%20of%206%20-%20FOI%20Annual%20Report%202017-18%20Appendix%204.pdf?LLL=0

Breakdown of who FOI requests to Thurrock Council were made by in 2020/21:
<img width="830" alt="Screenshot 2022-03-16 at 02 16 46" src="https://user-images.githubusercontent.com/547695/158503501-2f448b12-7add-4dd5-bb01-53af08ed1225.png">

https://democracy.thurrock.gov.uk/documents/s30774/Annual%20Information%20Governance%20Report.pdf

Another body, a health body, reports 20% commercial requests:

https://www.inverclyde.gov.uk/meetings/documents/8738/10%20FOI%20%20Annual%20Report.pdf

**Comment by FOIMonkey** [comment]
Some more s14 mentions re: commercial requests
University of Leicester: https://www.whatdotheyknow.com/request/procurement_framework_5 and https://www.whatdotheyknow.com/request/foi_request_confidential_waste_2

Manchester Met https://www.whatdotheyknow.com/request/estates_director_contact_details_61 and https://www.whatdotheyknow.com/request/insurance_services#incoming-1694728

**Comment by sallytay** [comment]
Note from Community and Activism Meeting (2022-03-29) 

We may want to consider as part of this, a fair usage policy.

**Comment by FOIMonkey** [comment]
Some feedback on this topic via the contact form:

> I work as a Freedom of Information Officer and have seen a massive upturn over the last few months of people using whatdotheyknow.com to raise requests that are clearly commercial with the intention to obtain information that they then sell on.  I have seen 2 applicants in particular who have each raised over 2000 requests in the last year.  I think the Freedom of Information legislation is essential when used for the intended use of openness and transparency, however, when it is being misused  by companies to obtain information to sell on something is wrong.  If each of these applicants requests takes half the allowed time to complete that still amounts to £450,000 of public funds spent to answer these requests alone.  I understand that legally these companies are operating within the law but wanted to raise the issue with yourselves as this seems contrary to your mission statement of being open and transparent and does not seem in line with the intended use of the site. I hope you will  consider taking action to limit the number of people using your site for clearly commercial purposes.

**Comment by RichardTaylor** [comment]
>people using whatdotheyknow.com to raise requests that are clearly commercial with the intention to obtain information that they then sell on. 

See also discussion at 

https://github.com/mysociety/alaveteli/issues/10#issuecomment-11492105

In many cases commercial requests on our service highlight issues with the transparency and accessibility of public procurement systems. Getting into lobbying for improvements there might be a little out of scope for us, but perhaps not too far if we can link it to usage of our service.

**Comment by garethrees** [comment]
> We have had a case where we didn't offer access to a feature to a user on the grounds they were a commercial user, a marketing company

My decision was more that I wasn't confident the particular user was going to make good use of it. Their email domain was a factor, but not the only one.

**Comment by RichardTaylor** [comment]
From slack:

>Imagine a world where all the commercial users are on pro, paying a commercial fee.

I'd agree with that for bulk requesters. 

Maybe not just commercial, but all organisational users.

**Comment by WilliamWDTK** [comment]
I think something along these lines has come up recently, although I'm not sure of the details

**Comment by HelenWDTK** [comment]
It has in relation to pro. AIUI the thinking was that commercial use could be channelled to pro rather than the regular service. I don't think any concrete decisions have been made in that regard yet though.

**Comment by garethrees** [comment]
Some concrete actions are tracked in https://github.com/mysociety/whatdotheyknow-private/milestone/6 – aiming to schedule them in our next 6 week planning cycle (Oct 07 - Nov 17).

**Comment by HelenWDTK** [comment]
As above - this is happening as part of pro changes ticketed elsewhere
