### ISSUE TITLE
Improvement in House Rules about requesting information relating to other people

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1050]
In some recent cases we have seen that users have been misinterpreting our house on requesting information on named people.

One such case: https://mail.google.com/mail/u/0/?tab=rm&ogbl#search/kb/FMfcgzGmvLRrCWWPlgwJDJDgNQVWGMxC

Our house rules state:
Do not use our service to request other people’s personal information and do not include such information in requests, annotations or follow-ups, unless it is fair to do so.

It has been noted on that thread that the house rules do read as though we don't allow any requests for information about named people, which I don't think is accurate.

It may help to add some explanation of 'fair to do so'. This appears to be encouraging people to report requests that contain names without considering 'fair to do so'

**Comment by RichardTaylor** [comment]
>Do not use our service to request other people’s personal information and do not include such information in requests, annotations or follow-ups, unless it is fair to do so.

There is ambiguity there as to if the "unless it is fair to do so" clause applies to the whole sentence. The intent is it does apply to the whole sentence. 

Proposed replacement ideas:

>Unless it is fair to do so you must not: i/ use our service to request other people’s personal information or ii/ include others' personal information in requests, annotations or follow-ups.

>Unless it is fair to do so you must not use our service to request other people’s personal information or include others' personal information in requests, annotations or follow-ups.

As for expanding on "fair to do so" ideally we'd have a help page section to link to. We don't currently have anything ideal, and while there is relevant material at https://www.whatdotheyknow.com/help/how and https://www.whatdotheyknow.com/help/privacy#legal_basis it's not specific to this issue. 

We have 
>Can I request information about a deceased person? [#](https://www.whatdotheyknow.com/help/requesting#data_protection_deceased_persons)

Perhaps above it we could have 

>Can I request information which relates to another person? 

**Further instance**

We have a worse instance of this issue at

https://www.whatdotheyknow.com/help/requesting#data_protection

>If you see that somebody has included personal information, perhaps unwittingly, in a request, please contact us immediately so we can remove it. 

That could become :

>If you see that somebody has unreasonably included personal information in a request, please contact us immediately so we can remove it.

**Comment by HelenWDTK** [comment]
We've updated the house rules since this was raised.
