### ISSUE TITLE
Agree and publish a media engagement policy

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1055]
Possibly inspired by 

https://www.camcycle.org.uk/about/mediapolicy/

Links to "Improve help pages so we have content on them we can point those making media inquiries to" #946  

See support inbox thread <CAEu8bMnOq2GfG_UeLViXo5pvf7DGtATWdaWQ3io=B3V8_h4b5w@mail.gmail.com> for more.

**Comment by garethrees** [comment]
We have https://www.mysociety.org/press so perhaps we should link to that. I'm not sure we need/want service-specific policies.

**Comment by RichardTaylor** [comment]
I support having a mySociety wide policy on this which we can link to. 

At the moment there isn't a mySociety wide policy at https://www.mysociety.org/press

**Comment by HelenWDTK** [comment]
Closing in favour of https://github.com/mysociety/orgsites/issues/1241 as this is something that gets decided at an organisational level

**Comment by WilliamWDTK** [comment]
That repo is not accessible to volunteers

**Comment by HelenWDTK** [comment]
Ticket just links to this and says to do it at a mySociety level, as suggested above.
