### ISSUE TITLE
Help page section on Outlook "Recall" messages

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1059]
This comes up often enough that we ought to have some pre-existing wording around handling these.

**Comment by mdeuk** [comment]
> This comes up often enough that we ought to have some pre-existing wording around handling these.

We have a form of words in the mailbox that we’ve used before - were you thinking of /help/officers as the right place?

**Comment by mdeuk** [comment]
Here's a possible draft, based on a recent complaint reply:

>###  I tried recalling a message - why hasn't it worked?
>
>The recall function provided in Microsoft Outlook generally only works if both the sender and recipient are on the same email system.
>
>This functionality is unlikely to work on other platforms; and it is not a function that is supported on WhatDoTheyKnow. Further information about this function, and its limitations, may be found on the [Microsoft website](https://support.microsoft.com/en-us/office/recall-or-replace-an-email-message-that-you-sent-35027f88-d655-4554-b4f8-6c0729a723a0?ui=en-us&rs=en-us&ad=us).
>
>If you've spotted an issue with a request, please [contact us](https://www.whatdotheyknow.com/help/contact), giving as much detail as possible, and we'll help.

**Comment by mdeuk** [comment]
Thinking about this, I've logged a feature request upstream (https://github.com/mysociety/alaveteli/issues/6884).

This is by no means an isolated issue, as the [crudest of searches](https://www.whatdotheyknow.com/search/%22would%20like%20to%20recall%20the%20message%22/all?page=1&query=%22would+like+to+recall+the+message%22) indicates that we've thousands of these recall messages. Whilst most of them are probably innocuous, we don't know that, and without _proactive moderation_ we would only find out if either the public body or a user brought it to our attention.

Fortunately, there does appear to be some commonality which can be used to identify them, so we _might_ be able to identify them via automated means and return a suitable message to the sender.

### Proposal:
- [ ] Agree draft wording for text on /help/officers
- [ ] HTMLify and add to [officers.html.erb](https://github.com/mysociety/whatdotheyknow-theme/blob/master/lib/views/help/officers.html.erb) with appropriate anchor
- [ ] At a later date, consider if automatic detection can be implemented

**Comment by RichardTaylor** [comment]
The proposed text is fine. I considered something punchier but it's unnecessary and may well be inaccurate and outdated:

>The recall function provided in Microsoft Outlook generally only works when the recipient also uses Microsoft Outlook and [reportedly](https://www.codetwo.com/kb/outlook-message-recall/) doesn't even work when the recipient uses "Outlook on the web" or a mobile Outlook client.

**Comment by garethrees** [comment]
+1 on @mdeuk's proposed text

**Comment by mdeuk** [comment]
> +1 on @mdeuk's proposed text

Lovely, pull request duly raised 😀

**Comment by WilliamWDTK** [comment]
It's fairly inconsequential, and possibly too late now, but I would have changed/expanded the last line a bit, it seems a little abrupt to me:

> > If you've spotted an issue with a request, please [contact us](https://www.whatdotheyknow.com/help/contact), giving as much detail as possible, and we'll help.

▼

> > If you've spotted an issue with a request, please [contact us](https://www.whatdotheyknow.com/help/contact), giving as much detail as possible, and we'll look into it.

or 

> > …and we'll help resolve the problem.

or similar…

**Comment by mdeuk** [comment]
> It's fairly inconsequential, and possibly too late now, but I would have changed/expanded the last line a bit, it seems a little abrupt to me:
> 
> > > If you've spotted an issue with a request, please [contact us](https://www.whatdotheyknow.com/help/contact), giving as much detail as possible, and we'll help.
> 
> ▼
> 
> > > If you've spotted an issue with a request, please [contact us](https://www.whatdotheyknow.com/help/contact), giving as much detail as possible, and we'll look into it.
 
I think "look into it" works - it's not too late to add a commit, so I'll go ahead and do so now. Thanks for the review 👍
