### ISSUE TITLE
Improve naming of canned responses

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1060]
The [list of canned responses](https://wdtkwiki.mysociety.org/wiki/Canned_responses) is a major improvement in helping to find a potentially useful response for any given case.

However, they still feel quite disorganised and difficult to navigate.

For example, we have "GDPR-RtE Confirm Anon" vs "GDPR Response to ErasureS" vs "GDPR FOI Officer Continue to Publish". I'd expect:

* GDPR-RtE Confirm Anon
* GDPR-RtE Default Reject Single Request
* GDPR-RtE Default Reject Multiple Requests
* GDPR-RtE FOI Officer Reject

i.e. "`GDPR`-`RIGHT` `SUMMARY`".

I also think this would help with the sort order of the wiki page, which doesn't appear to be sorted in any particular order.

We should also be cognisant of the limited area that we have to view the titles.

* "Data Breach Notification Authority" → BR-notify-body
* "Data Breach Notification Complex" → BR-notify-body+ico

I'm sure we'll never get these _perfect_, but I feel like there's an iteration we could make from where we are now that would be a big improvement.

**Comment by RichardTaylor** [comment]
This was actively considered as part of 

https://github.com/mysociety/whatdotheyknow-theme/issues/777

It's very difficult given the restriction on the amount of the title which can be viewed. 

We want the canned responses/snippets to make it easier and quicker to respond to mail, and ideally to enable a wider group of people to help out, and to make it easier for new admins to get started. Cryptic titles for canned responses, are hard to avoid, but they don't help with these aims. 

Another challenge is different people have different ways of working. Different admins have set up different types of canned response, with different styles of naming. The recent review did normalise some of the variation. 

Having to go to the wiki to look up which canned response to use feels like a convoluted workflow to me. If you have to look it up on the wiki the template may as well just be on the wiki.

**Comment by garethrees** [comment]
I still think there's _some_ improvements we can make here.

```
BEFORE
xxxxxxxxxxxxxxxxxxxxxxxxxx  <-- 26 chars
New GDPR case
GDPR-RtE ack request
GDPR Response to ErasureS
GDPR Response to ErasureR
GDRR-RtR ack request
GDPR-RtO ack request(no RtE)
GDPR-RoA ack request
GDPR FOI Officer Continue to Publish
GDPR-Reply with PDF attachment
GDPR-RtE Confirm Anon
Subject-access-advise

AFTER
xxxxxxxxxxxxxxxxxxxxxxxxxx
GDPR-New case
GDPR-RtE ack request
GDPR-RtE Refuse Single Request
GDPR-RtE Refuse Multiple Requests
GDRR-RtR ack request
GDPR-RtO ack request(no RtE)
GDPR-RoA ack request
GDPR-RtE FOI Officer Refuse
GDPR-Reply with PDF attachment
GDPR-RtE Confirm Anon
GDPR-RoA SAR Advice
```

> Having to go to the wiki to look up which canned response to use feels like a convoluted workflow to me…

I've _really_ appreciated the wiki index to get a better sense of what's available to me. Prior to this I'd spend ages searching through the cryptic-to-me template chooser getting frustrated that each time I pick one its not right and then need to go and delete it from the draft.

> …. If you have to look it up on the wiki the template may as well just be on the wiki.

I disagree. To me there's a benefit to having a lower-resolution index of templates with one liner descriptions, with the actual contents easily addable to the mail. I do agree that it would be better for all this to be better handled by GMail though.

> The maximum character limit (including spaces) is 26…

I've just had a play with the CSS in the web inspector and Gmail does actually render the full template name to the page. I wonder if we can add some easily-installable user styles?

<img width="660" alt="Screenshot 2022-03-22 at 09 42 11" src="https://user-images.githubusercontent.com/282788/159452298-2b2c1f8f-9f38-4115-a668-6c8785c118b3.png">

**Comment by garethrees** [comment]
Looks like the css is consistent across reloads:

![Screenshot 2022-04-11 at 16 39 16](https://user-images.githubusercontent.com/282788/162778169-f4ec5e23-6dec-400f-b869-81303427eee5.png)

Need to remove the `max-width` on the `.BA.J-N-Jz` class.

**Comment by RichardTaylor** [comment]
Minor issue 

>Snippet - Updated-thanks-resent

may be short but it's actually a full response once combined with the recipient's name and a footer. 

I didn't expect it to be filed under "Snippet -"

**Comment by sallytay** [comment]
> Minor issue
> 
> > Snippet - Updated-thanks-resent
> 
> may be short but it's actually a full response once combined with the recipient's name and a footer.
> 
> I didn't expect it to be filed under "Snippet -"

I've updated this so it is no longer a snippet

**Comment by sallytay** [comment]
I propose to update the names of the following canned responses:

>Subject-access-advise change to Advice - Subject Access (How) (to note this is to advice people how they can make subject access requests not a GDPR related response to user making a subject access request to us)

>Advice on ICO referral change to Advice - ICO referral

>Explain Two Factor Authentication change to Advice - Two Factor Authentication

>GDPR Response to ErasureS change to GDPR-RtE_refuse_multiple_requests

>GDPR Response to ErasureR change to GDPR-RtE_refuse_single_request

>Data Breach Notification Complex change to GDPR-BR_ICO+Authority

>Data Breach Notification Authority change to GDPR-BR_authority only

>GDPR RtE document templates change to GDPR-RtE_document_templates

>New GDPR case change to	GDPR-new_case

>Warning for misuse of What change to Warning _for _misuse

>Thread reopening for old requests change to Thread_reopen_rejected

>Out of date email - encourage to change change to Out_of_date_email_updated

**Comment by HelenWDTK** [comment]
Closing as largely complete, and the inbox monster makes this a bit outdated.
