### ISSUE TITLE
Public policy on Pro discounts

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1062]
If Pro discounts are to be given to certain individuals / organisations on request that should be promoted, along with the assessment criteria, otherwise it's not  fair on those who don't have the chutzpah to ask.

The same approach to encouraging responsible use of FOI should be applied to those being offered a Pro free trial as is applied to rate cap removal for free users. 

As I understand it:

* Free trial discount codes were promoted as the Pro system was launched, via blogs, and at in-person events. 

* WhatDoTheyKnow volunteers are offered free Pro accounts. 

* mySociety has provided a Pro free trial on other occasions. 

See also: https://github.com/mysociety/whatdotheyknow-theme/issues/719

**Comment by HelenWDTK** [comment]
To the best of my knowledge, we're not running any pro specific promotions at this time.

**Comment by WilliamWDTK** [comment]
I believe a discount was offered for prepayment for a year in advance, or something similar. I'm not sure whether that's no longer available, but I think it was what prompted this ticket.
