### ISSUE TITLE
Remove footer from all canned responses

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1064]
`Misaddressed-not-wdtk` includes a footer, so has to be manually removed so that we don't send a message containing 2 footers.

We should standardise on no footers in message templates so that we don't have to update lots of canned messages each time we change the footer (and avoids the duplication problem)

**Comment by mdeuk** [comment]
> We should standardise on no footers in message templates so that we don't have to update lots of canned messages each time we change the footer (and avoids the duplication problem)

+1, I thought we had done this already - but it could be that something has been missed.

**Comment by sallytay** [comment]
Yes this was done when I did the canned responses review.

That particular response was updated recently to correct a typo so I imagine the footer was left on by mistake.
