### ISSUE TITLE
Persistant WhatDoTheyKnow.com link for WhatDoTheyKnow blog posts

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1066]
An anchor for each article was added via

https://github.com/mysociety/alaveteli/issues/189

however any such links won't persist forever as only a certain number of articles are shown on https://www.whatdotheyknow.com/blog 

Caution: Google might not like duplicate content on WhatDoTheyKnow and the mySociety blog. An article page on both sites might not be the way to go.

**Comment by garethrees** [comment]
The canonical URL is the mysociety.org/blog URL
