### ISSUE TITLE
Reward great uses of the service

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1067]
1.  Identify users who have made great use of the service
2. Reward them

We are already doing this to some extent with the free month of Pro for articles based on requests (#719) and depending on if you see it as a reward, membership of the site admin team. 

Increased prominence of good requests is one form of award, as are blogs featuring requests and their use of the service. 

Should we be sending out medals, t-shirts, hoodies, cash etc. ?

**Comment by HelenWDTK** [comment]
We ran a citation promo for a while. Work on badges is likely coming soon, so closing in favour of that.
