### ISSUE TITLE
Present users with the statistics on the success rate of internal reviews at the appropriate time to encourage internal review requests

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1069]
When users classify a request as rejected or partially successful encourage them to request an internal review, noting the encouraging statistics on success rates of internal reviews. 
 
Statistics presented at 

https://www.whatdotheyknow.com/help/unhappy#internal_review

Related ticket to update those stats: #1068

Getting @ajparsons's work in-front of users' eyes at the right moment,

**Comment by mdeuk** [comment]
It strikes me that some illustration might help make this content more visually engaging.

Linking to https://github.com/mysociety/alaveteli/issues/6586

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
