### ISSUE TITLE
Add a tag (and note) to bodies who often respond off-site

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1070]
Prompted by @FOIMonkey's suggestion on Slack:

> I've noticed that we have a note on the Southampton Uni page about the fact that they always reply off-site. Is this worth adding to the other bodies that consistently do so? (eg Knowsley Council and ONS). It might be worth making a list as we find them in case we want to scrape the responses at some point.

I responded to say:

> [W]e could add a tag to bodies that respond off-site, with the aim of automatically adding a note in the future, but doing so manually for now…

Proposed tag:

`responds_offsite` (or perhaps `responds_off-site`)

See also: mysociety/alaveteli#387, #826, mysociety/alaveteli#6305

**Comment by FOIMonkey** [comment]
This could also be helpful for bodies that regularly respond offsite such as Waltham Forest, Brighton and Hove, Adur and Worthing councils or bodies who regularly upload large files offsite on a time limited basis eg University of Oxford

**Comment by WilliamWDTK** [comment]
One could also put a tag on individual requests, e.g. https://www.whatdotheyknow.com/request/announcements_29.

**Comment by FOIMonkey** [comment]
Further example from Devon County Council https://www.whatdotheyknow.com/request/knives_in_schools_42#incoming-1342852

**Comment by garethrees** [comment]
I think we're doing this now via https://wdtkwiki.mysociety.org/wiki/Authority_Performance_Tags
