### ISSUE TITLE
Blog Post - A week in the life of WDTK Service Manager

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1072]
A series of short internal blog posts to show the varied work of the Service Manager alongside the rest of the admin team to show the rest of the organisation the variety of tasks that we carry out.

An initial draft is being completed and will be shared for comment once completed/

**Comment by sallytay** [comment]
Initial draft of this blog is here - not yet completed or ready for publishing
https://docs.google.com/document/d/169V04hRw9ECNCTzjBy8Fo3GWf-yr-iysDYuux7JD45s/edit#heading=h.nq7pf2pglp0p

**Comment by WilliamWDTK** [comment]
Presumably, if this is to be done, it would now have to be @HelenWDTK's perspective, though perhaps based off @sallytay's draft, and there might be some comparisons that could be drawn.

I think it's definitely an interesting idea.

**Comment by HelenWDTK** [comment]
I'll reopen this if there is ever an average week!
