### ISSUE TITLE
Blog Post - Northern Ireland's schools comprehensively listed

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1074]
Suggestion to blog, externally when completed. This has now been completed

More detailed information on the import can be found https://wdtkwiki.mysociety.org/wiki/NI_School_and_Educational_Institution_Import_Winter_2021/22

Inbox thread: https://mail.google.com/mail/u/0/?tab=rm&ogbl#label/Blog%2Fpublicity+ideas/FMfcgzGllVnXGjvNDwFCqTfQsGcknlrP

**Comment by WilliamWDTK** [comment]
The boat has sailed on this, I think. It can probably be closed, so I'll do so.
