### ISSUE TITLE
Blog Post - Listing more Charter Trustees 

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1075]
Suggestion for a blog post but maybe we just keep this in mind for something to mention when we're generally talking about how confusing local government can be.

Inbox thread:
https://mail.google.com/mail/u/0/?tab=rm&ogbl#label/Blog%2Fpublicity+ideas/KtbxLthVfQrWQrxThdwDvLKcKVrPsnpKPg 

Information:
>We've now got some more "Charter Trustees" listed: https://www.whatdotheyknow.com/body/list/charter_trustees
>It looks like they're small groups of district councillors for a town given the power to elect a mayor and deputy mayor for the town, and to raise taxes for the purpose of the upkeep of the Civic Insignia or 'Silver' and the mayoralty. 
>Another level of obscure complexity to UK local government.
>Suggestion by Richard

**Comment by RichardTaylor** [comment]
Now we list even more charter trustees, and appear to have a longer list of charter trustees than anyone else, we can write an even better blog post. 

* #1247

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
