### ISSUE TITLE
Blog post - How public bodies themselves use FOI

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1076]
Suggestion as made on inbox thread:
https://mail.google.com/mail/u/0/?tab=rm&ogbl#label/Blog%2Fpublicity+ideas/FMfcgzGllCmcNpxmlcnjgFhzjsCRZSWL 

Needs further research and should not be case specific, we’d need to base it on public information.

Suggestion by @RichardTaylor   

Edit: Removing quoting RT

**Comment by garethrees** [comment]
There's a reddit thread about an authority employee wanting to use FOI to make internal improvements https://www.reddit.com/r/TheCivilService/comments/153tza3/any_comeback_for_making_a_foi_request/

**Comment by MyfanwyNixon** [comment]
>This might need a bit of a mindset change.

Makes me wonder (again) whether Reddit might be a good place for an official mySoc account (or WDTK for that matter) that could act as a kind of brand advocate. 

Capacity, though, as ever.

**Comment by garethrees** [comment]
Yeah. I think it's more about spotting these things in the wild, writing about them on our own platforms, and then hopefully those who are pointing to WDTK will point to the more specific advice we've written.

**Comment by HelenWDTK** [comment]
> This might need a bit of a mindset change. All information is available to the public by default, unless exempt.

In theory. They mean without them needing to ask for it. Whilst this is kinda  true, without a knowing what info an authority has, you might not even know to ask for it in the first place.

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
