### ISSUE TITLE
Blog Post - How we process requests for user data

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1077]
To note work has already been started on this by @RichardTaylor 

As detailed in this email thread.
https://mail.google.com/mail/u/0/?tab=rm&ogbl#search/label%3A+label%3ABlog-publicity-ideas/KtbxLwGzcRWTKvLhZfnSbtTHLghzvPTklB

Also mentioned  on thread https://mail.google.com/mail/u/0/?tab=rm&ogbl#inbox/FMfcgzGlksGwTStszvsKTSzqVNhsCgzn in relations to our experience of receiving Police production orders to reveal user data

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
