### ISSUE TITLE
Blog Post - Post Office Scandal

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1078]
We have two related items which could, together, make a blog:
https://www.whatdotheyknow.com/request/submissions_to_law_commission_re_2 
https://twitter.com/WhatDoTheyKnow/status/1460667459674030082

To note this maybe better holding off until later in the year when the public inquiry has been completed. Updates can be found here; https://www.postofficescandal.uk/blog

**Comment by confirmordeny** [comment]
There was a blog post: https://www.mysociety.org/2023/10/16/whatdotheyknow-and-the-post-office-horizon-scandal/
