### ISSUE TITLE
Blog Post - Public information that reveals how disorganised public bodies can be

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1079]
Suggestion from grant wrap up call - Lost in Europe discussion . 

>They can’t respond because they’ve not got good record keeping themselves. 
>We could write about these as a follow up to the “not held” can be actionable blog post. 

Suggestion from @RichardTaylor 

Examples:
PPE contracts mentioned elsewhere is an example. 

Edit: Quote formatting improvement. RT

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
