### ISSUE TITLE
Blog post- Example trade offs between data protection and transparency

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1080]
Suggestion for a blog to describe how we balance data protection and transparency. 
As mention in a High Risk Case and Policy call

Example can be found here: review case https://groups.google.com/a/mysociety.org/g/wdtk-review/c/wGpFPhV2TNI/m/v_gAiK75AQAJ

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
