### ISSUE TITLE
Blog post - When an authority does not provide a contact email address

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1081]
Suggestion to explain what we we do when an authority does not provide a contact email address

Previous examples
Reading Borough Council and Barnsley as examples

This should also include ICO decision notes on this

**Comment by RichardTaylor** [comment]
Example case

https://www.whatdotheyknow.com/request/number_of_licenses_to_exhibit_an_312#comment-106211

Relates to, and follows up on, previous blog:

https://www.mysociety.org/2021/05/06/dont-let-the-auto-responses-worry-you/

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
