### ISSUE TITLE
Blog post Harms vs Benefits of running WDTK

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1082]
A draft of this has previously been started at
https://docs.google.com/document/d/1e6U7Ys2HjVd5rQmNBmewpKlv7WRB-1wSxsA_391_Dck/edit?disco=AAAANXOvSNc&usp_dm=false)

Suggestion from @RichardTaylor 
>Elements could be spun out of this into shorter blog posts now we don’t need the whole thing
>Blog on harms vs benefits specifically of publishing HMO landlord / manager licence information.

**Comment by WilliamWDTK** [comment]
This is a duplicate of #830
