### ISSUE TITLE
System data request for all public bodies with no email addresses

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1084]
Would it be possible to get a list of all public bodies that currently have no email address. 

Helen has offered to have a look through these for us, and it's something that we could use in the future for giving new volunteers projects to work on

It would be useful for it to include the public body name and a link to their admin page.

**Comment by RichardTaylor** [comment]
Related:
* https://github.com/mysociety/alaveteli/issues/3477
* https://github.com/mysociety/alaveteli/issues/6424
* https://github.com/mysociety/alaveteli/issues/6831

**Comment by garethrees** [comment]
Generated an export [today](https://groups.google.com/a/mysociety.org/g/alaveteli-dev-private/c/nIcUbmY7fuA/m/LMlYmJuTAAAJ) with the following:

```ruby
csv_string = CSV.generate do |csv|
  csv << %w[
    public_url
    admin_url
    body_name
    home_page
    tags
  ]

  PublicBody.without_request_email.each do |body|
    csv << [
      "https://www.whatdotheyknow.com/body/#{body.url_name}",
      "https://www.whatdotheyknow.com/admin/bodies/#{body.id}",
      body.name,
      body.calculated_home_page,
      body.tag_string
    ]
  end

  csv
end

File.write("tmp/#{Date.today.iso8601}-missing-body-emails.csv", csv_string)
```
