### ISSUE TITLE
Create a list of topics of active misinformation 

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1086]
Suggestion from the High Risk and Policy meeting.

The list would assist with potential mass problematic requests on certain high profile areas of misinformation.  

A recent example of this would be COVID.

I suggest the list would added to the Wiki

**Comment by garethrees** [comment]
LSE

**Comment by RichardTaylor** [comment]
The notes from the High Risk and Policy call agenda [state](https://docs.google.com/document/d/1TwkIS1dFjrum5TysIFAGJgrgRB17E3A5eWzMuU5H91o/edit?skip_itp2_check=true#bookmark=id.yu4ou0mgw2dr):

>Create list of “topics of active misinformation” where we may move to more active measures.

In the "LSE" case requests were identified as vexatious and moderation took place accordingly as described at https://www.mysociety.org/2022/03/09/freedom-of-information-requests-around-the-academic-status-of-dr-tsai-ing-wen/ 

I think we need to be really careful not to prevent requests on certain subjects, or we will lose our position as a neutral service provider. Forbidding requests on certain subjects would prevent use of the service to investigate, or disprove, conspiracy theories. Sometimes FOI requests which appear not to have a serious purpose result in the release of surprising information, [eg. requests on exorcisms, UFOs, ghosts and homeopathy](https://www.mysociety.org/2012/02/21/whatdotheyknow-justice-ctte/). 

Is the aim to create a list of subject areas on which requests should be reviewed for consideration if they are [generally] vexatious?

>A recent example of this would be COVID.

I think we can be more specific, COVID, is a very broad subject.  

>I suggest the list would added to the Wiki

Presumably what we need is a review of the use of the service on each subject, with a special moderation approach to be proposed if that appears to be a sensible outcome of the review.

**Comment by FOIMonkey** [comment]
Clear responses from public authorities can sometimes be helpful in tackling misinformation: https://www.whatdotheyknow.com/request/667086/response/1586389/attach/3/FOI2020%2016613%20response.pdf

I also think we'd need to be aware of the legal consequences of more proactive moderation.

**Comment by RichardTaylor** [comment]
Following a new case today I've started the inbox label `Misuse: Misinformation` nested under Misuse. 

We could also use a misinformation request tag. I've noted that at https://wdtkwiki.mysociety.org/wiki/Request_tags

**Comment by RichardTaylor** [comment]
We try to be transparent about why we've removed material. Where appropriate we could replace removed material with 

>`[extraneous misinformation removed]`

just as we do with eg. `[extraneous potentially defamatory material removed]` / `[potentially defamatory material removed]`

**Comment by HelenWDTK** [comment]
closing as complete via wiki page.
