### ISSUE TITLE
Blog post on public bodies responding to FOI requests via password protected online systems

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1088]
Note section 11 of the Freedom of Information Act requires public bodies to follow any reasonable request as to a means of correspondence 

https://www.legislation.gov.uk/ukpga/2000/36/section/11

Those making a request via WhatDoTheyKnow clearly request a response via the @whatdotheyknow.com email provided as an address for correspondence.

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
