### ISSUE TITLE
Indentify internal reviews which took more than i/ 20, or ii/ 40, working days

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1091]
Some statistics, and links the actual request threads where internal reviews took the longest, would be of interest. 

This research / data extract could be used:

* To support lobbying for a legal time limit on internal review responses
* Identify notable and potentially newsworthy request threads

This could be done as a live page on the site

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
