### ISSUE TITLE
Blog post - Good use of FOI, past exam papers

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1094]
Suggestion from support inbox:

Inbox thread with suggested content.
https://mail.google.com/mail/u/0/?tab=rm&ogbl#label/Blog%2Fpublicity+ideas/FMfcgzGmvTstgskfvvLDtjpcSljPtSWL

We've started to build up a pretty large collection of past exam papers on the site. I think this is a good use of FOI, as there is a clear benefit to having this information available to the wider public, so I've started to put together a list of them here:
https://docs.google.com/spreadsheets/d/1InmGJEY3gs9ifsGw9SdMLyk-ZtfXUTu-CRxCEMJAzrs/edit?usp=sharing

A blog on exam papers could be a nice follow-up to that to a proposed blog https://github.com/mysociety/whatdotheyknow-theme/issues/989.

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
