### ISSUE TITLE
Blog post - FOI myths busted

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1095]
Suggestion from WDTK Support Inbox from @RichardTaylor 

Inbox thread:
https://mail.google.com/mail/u/0/?tab=rm&ogbl#search/Blog%2C+or+even+Youtube+idea.+FOI+myths+busted/FFNDWMkvDdGRXdGHDnkkqTSXfPgHLGCS

Could also be a YouTube Video

Content suggestions: Some myths we could bust:
* Companies are not subject to FOI or similar access to information legislation.
* Receiving public money makes a body subject to FOI
* Charities are subject to FOI
* Personal information cannot be requested, or obtained, under FOI
* All public bodies are subject to FOI

Rough draft already started 
https://docs.google.com/document/d/1UOm7kW_ciXRqjcbrnph0BYpzxwYsHoNaEosvSwRgWuo/edit

**Comment by HelenWDTK** [comment]
Closing as complete: https://www.youtube.com/shorts/15XskWaWPgA
