### ISSUE TITLE
New canned response - point to other routes than FOI

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1097]
Action from High risk and policy meeting on 2022-03-24

New canned response - similar to home office responses to help users who are trying to get information  where FOI isn't appropriate.

Example in the meeting was for Housing Association contact but it could apply to other types of authority too.

We could add line to warning email pointing to routes other than FOI eg. complaints /writing to  elected reps.   FOI isn’t the route for solving all issues. Or create an alternate warning email that includes this for when it is needed

**Comment by RichardTaylor** [comment]
Very closely related:
https://github.com/mysociety/whatdotheyknow-theme/issues/632#issuecomment-1075322930

**Comment by HelenWDTK** [comment]
Closing as stale.
