### ISSUE TITLE
Improve tagging suggestions/hints for admins adding new bodies

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1098]
Ideas:
* List commonly used non-category tags on add authority page.
* Autocomplete / selection for common tags
* Link from body addition page to the guidance on the wiki
* When a tag is entered show how commonly used it is (this would help an admin see if it's a currently used tag or not). 

Tags such as cic, company, limited etc. are not categories so are not listed at 

https://www.whatdotheyknow.com/admin/bodies/new

There is more information on our body tagging policy and practice at 

https://wdtkwiki.mysociety.org/wiki/Policies#Tagging

**Comment by WilliamWDTK** [comment]
We could perhaps use any data from [this spreadsheet of tags and their frequencies](https://docs.google.com/spreadsheets/d/1UmBuTkxv7324YYGwpCaxQzj3El6IYwlLDsEs7MgS6VE/) to inform this.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
