### ISSUE TITLE
Improve notes on London Legacy Development Corporation

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1100]
> https://www.whatdotheyknow.com/body/lldc
>
> A news article today suggests it’s a planning authority which surprised me
>
> https://www.bbc.co.uk/news/uk-england-london-60848732
>
> Its role could be explained in notes. 
>
> Related: We could tag planning authorities, we might want to tag principle planning authorities differently from other types of planning authority.
>
> – via @RichardTaylor 

Let's see what comes out of the notes here before deciding on whether there's a worthwhile distinction between principle planning authorities and the other types.

**Comment by RichardTaylor** [comment]
New text for:

https://www.whatdotheyknow.com/body/lldc

>The London Legacy Development Corporation acts as the planning authority for the area around and including Queen Elizabeth Olympic Park.[*](https://www.queenelizabetholympicpark.co.uk/planning-authority)


Also closely related new text for

https://www.whatdotheyknow.com/body/old_oak_and_park_royal_development_corporation

> This body is the local planning authority Old Oak and Park Royal. The 650 hectare area in which the development corporation has planning responsibilities includes Park Royal industrial estate, the Old Oak development area around the new High Speed 2 Old Oak Common Station, and the protected land at Wormwood Scrubs.[*](https://www.london.gov.uk/about-us/organisations-we-work/old-oak-and-park-royal-development-corporation-opdc/about-us/introduction-old-oak-and-park-royal-development-corporation)



=====

>principle planning authorities and the other types

Wikipedia summarises the situation in England at:

https://en.wikipedia.org/wiki/Local_planning_authority#England

I suspect there are further complexities such as delegation of planning powers to joint committees ([example](https://democracy.cambridge.gov.uk/ieListMeetings.aspx?CId=497&Year=0)) and city deal organisations. 

It notes 2 mayoral development corporations (the [London Legacy Development Corporation](https://en.wikipedia.org/wiki/London_Legacy_Development_Corporation) and the [Old Oak and Park Royal Development Corporation](https://en.wikipedia.org/wiki/Old_Oak_and_Park_Royal_Development_Corporation)) act as local planning authorities. 

I'll spin out a separate ticket for the tagging issue.

**Comment by RichardTaylor** [comment]
Notes updated. Closing.
