### ISSUE TITLE
Agree and implement policy on tagging planning authorities

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1101]
Wikipedia summarises the situation in England at:

https://en.wikipedia.org/wiki/Local_planning_authority#England

I propose using the tag [local_planning_authority](https://www.whatdotheyknow.com/body?tag=local_planning_authority) for primary, lowest tier, planning authorities in an area. 

We need to add principle councils, national parks, the broads authority etc. to that tag. 

The situation in Scotland, Wales and Northern Ireland requires some research. 

[](https://en.wikipedia.org/wiki/Local_planning_authority#England)I suspect there are further complexities beyond those noted on Wikipedia such as delegation of planning powers to joint committees ([example](https://democracy.cambridge.gov.uk/ieListMeetings.aspx?CId=497&Year=0)) and city deal organisations.

There are other types of planning authority to consider planning beyond local planning authorities, eg. as noted in Wikipedia:

>The [non-metropolitan county](https://en.wikipedia.org/wiki/Non-metropolitan_county) councils (where they exist) are the planning authorities for their own developments, such as most schools, care homes, fire stations and highways.

What tag might make sense for those?

We already list, and tag, Neighbourhood Planning Forum

https://www.whatdotheyknow.com/body/list/neighbourhoodforum

We might want to distinguish between plan making bodies, and planning regulatory bodies. 

We may want to make some tags mentioned into categories. 

Some work which will make dealing with this ticket easier has already been carried out as noted at 

https://github.com/mysociety/whatdotheyknow-theme/issues/579#issuecomment-731754163

**Comment by HelenWDTK** [comment]
https://wdtkwiki.mysociety.org/wiki/Tagging_suggestions
