### ISSUE TITLE
Improve and simplify handling of delivery errors

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1103]
To consider:

What do we do when we can't find an email address for an authority following a reported delivery error?
>Should we make the email address blank to push finding one back to the user community
>Should we ask the user who made the request to see if they are willing to try and find an address
>Should we try to contact the authority ourselves to ask for an address

How do we link the email alerts received into the WDTK Support inbox with Pro user reports sent to the pro support email address?

Once agreed this should be added to the Wiki

**Comment by RichardTaylor** [comment]
Should we make a FOI request seeking a contact address? Is this [a kind of request we could make from [name] on behalf of WhatDoTheyKnow?](https://docs.google.com/document/d/1E4-O6j2HP42yBVjRGGuTcu8GsAdy8fL1Jog1gShqI4E/edit#bookmark=id.xp7swb9ztz0u) [internal discussion link].  

>Should we make the email address blank to push finding one back to the user community

We could more actively push the challenge of finding an address to the wider community eg. by tweeting, using the banner etc, or using a community mailing list. There's also an existing ticket mentioning "something like the request categorisation game but for missing email addresses." https://github.com/mysociety/alaveteli/issues/3477

**Comment by WilliamWDTK** [comment]
I'd said on #1196:

> [W]e could perhaps change the processing of identified delivery errors to marking those which come in the alerts in the inbox as error_message, archiving the inbox thread and dealing with it through Alavateli.

**Comment by HelenWDTK** [comment]
Things have moved on since this was opened, with authorities with no email address being highlighted, and all support being handled in one place.
