### ISSUE TITLE
Review coverage of harbour/port authorities

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1108]
A list of "competent harbour authorities" has been released at:
 
https://www.whatdotheyknow.com/request/competent_harbour_authorities

We have an existing category which may or may not directly correspond to that list of bodies at

https://www.whatdotheyknow.com/body/list/port_authority

We should document how we use the port_authority tag - that's something we could do publicly but I don't think there's an obvious place for such documentation at the moment.

**Comment by confirmordeny** [comment]
I have added the list to FOIWiki: https://foiwiki.com/foiwiki/index.php/Competent_harbour_authorities

**Comment by confirmordeny** [comment]
From memory, we originally added trust ports because they are publicly owned. (It is a bit odd because they say they are not owned by the Government but by by themselves. I think they might be owned by the Crown.) Some of the CHAs are not trust ports and some might be local authorities.

**Comment by HelenWDTK** [comment]
closing as complete
