### ISSUE TITLE
Consider standardisation/improvement of tagging

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1109]
Using [this spreadsheet](https://docs.google.com/spreadsheets/d/1UmBuTkxv7324YYGwpCaxQzj3El6IYwlLDsEs7MgS6VE/) as a starting point for further analysis, consider how tags can be standardised.

# To consider
- Capitalisation
- Place name formats (e.g. [`Kingston_upon_Hull,_City_of`](https://www.whatdotheyknow.com/body?tag=Kingston_upon_Hull%2C_City_of) is particularly ugly, and presumably came from a school import.
- Tags that have probably been imported improperly (e.g. in schools the string `Not applicable` turns into the two tags `Not` and `applicable`, same with `Middle Deemed Secondary`/`Middle Deemed Primary`)
- Other oddities/idiosyncracies
- Improvement of [documentation on wiki](https://wdtkwiki.mysociety.org/wiki/Category:Tagging)

# Things already noted
(on the sheet)

Tag | Count (Total: 189098) | Length of tag | Is k:v tag? | Is lowercase? | Notes
-- | -- | -- | -- | -- | --
Brent | 85 | 5 | FALSE | FALSE | Not sure what this tag is referring to, it seems oddly allocated: https://www.whatdotheyknow.com/body?tag=Brent
CH: | 58 | 2 | TRUE | FALSE | Probably wants changing
  | 39 | 0 | FALSE | TRUE | The tag probably needs removing, see https://www.whatdotheyknow.com/admin/bodies?utf8=%E2%9C%93&query=%27&commit=Search
St._Helens | 34 | 10 | FALSE | FALSE | Do we want to remove the dot here?
applicable | 27 | 10 | FALSE | TRUE | I think this matches "Not"
Not | 27 | 3 | FALSE | FALSE | I think this matches the tag "applicable" (also 27)
academies, | 4 | 10 | FALSE | TRUE | We might want to remove the comma
nhs, | 2 | 4 | FALSE | TRUE | We might want to remove the comma
academies;Schools;academy_trust | 1 | 31 | FALSE | FALSE | fixed body 64586
association, | 1 | 12 | FALSE | TRUE | We might want to remove the comma
companies_owned_ | 1 | 16 | FALSE | TRUE | This looks like a mistake
CroydonFree_schoolsschoolschool_new_nov2020SecondaryURN: | 1 | 55 | TRUE | FALSE | This is  on body 90255, and I've fixed it (W)
curmbia | 1 | 7 | FALSE | TRUE | My typo for cumbria - fixed (H)
engla | 1 | 5 | FALSE | TRUE | Is this a mistake?
executive_agency, | 1 | 17 | FALSE | TRUE | We might want to remove the comma
fei, | 1 | 4 | FALSE | TRUE | We might want to remove the comma
NHSChoicesC88627 | 1 | 16 | FALSE | FALSE | This looks like a mistake
richmond_upon_thames. | 1 | 21 | FALSE | TRUE | Do we want to remove the dot here?
Tags | 1 | 4 | FALSE | FALSE | Do we still want body 111687?
ucas;W81 | 1 | 8 | FALSE | FALSE | changed semicolon to colon in body 7052
utc, | 1 | 4 | FALSE | TRUE | We might want to remove the comma
Z5247837 | 1 | 8 | FALSE | FALSE | This looks like a DPR
zoo, | 1 | 4 | FALSE | TRUE | We might want to remove the comma

# See also
- #1098
- https://github.com/mysociety/alaveteli/issues/5307
- #1101
- #982
- #963

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
