### ISSUE TITLE
/help/unhappy/ workflow has broken URL to ICO

### ISSUE THREAD

**Issue by mvl22** [mysociety/whatdotheyknow-theme#1110]
The link in:

Has the authority sought the views of the third party whose commercial interests they are citing? [ICO guidance](https://ico.org.uk/media/for-organisations/documents/1178/commercial-interests-section-43-foia-guidance.pdf) says: "When a public authority wants to withhold information on the basis that to disclose the information would or would be likely to prejudice the commercial interests of a third party, it must have evidence that this does in fact represent the concerns of that third party. It is not sufficient for the public authority to speculate on the prejudice which may be caused to the third party by the disclosure."

Looks like this should possibly now be

https://ico.org.uk/for-organisations/guidance-index/freedom-of-information-and-environmental-information-regulations/section-43-commercial-interests/

**Comment by garethrees** [comment]
Thanks for reporting. Got that fixed, and should be rolled out over the next few days or so.
