### ISSUE TITLE
Consider adding the Catapult Network to WDTK

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1113]
As agreed at Community and Activism meeting on 2002-03-29

Adding the catapult network [[catapult.org.uk](http://catapult.org.uk/)] of companies to the database

>They would meet our criteria for listing if we consider that they do distribute substantial public funds then that is a criteria we've used for listing 
>Action: Needs research as to how their funding is received / distributed

**Comment by sallytay** [comment]
Further information has been provided by the user who requested for these to be added.

>They receive in excess of £100m of taxpayers' funds every year, much of which is then distributed to research projects. Certainly ought to be in scope of FOI requests.
>https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/975595/catapult-
network-review-april-2021.pdf

It appears that for most listed projects the core funding that is provided by the government makes up over 50% of the total funding

**Comment by RichardTaylor** [comment]
>     It appears that for most listed projects 

It's not clear what this refers to. Perhaps it refers to the list of Catapults listed in the appendix of the linked document. 

There is an example in the document of one catapult distributing public money:

>Connected Places Catapult delivers the Transport Technology Research Innovation Grants
(T-TRIG) programme for the UK’s Department for Transport (DfT), shaping innovation
challenges and allocating grant funding to accelerate commercialisation projects across
transport technology. Organisations are awarded £30k to undertake six-month R&D
projects to prove technological concepts.

We could list the Connected Places Catapult on the basis of that under the https://wdtkwiki.mysociety.org/wiki/Listing_bodies_not_subject_to_FOI

**Comment by RichardTaylor** [comment]
>Connected Places Catapult is a company limited by guarantee, registered in England under company number 11837978
Source: https://cp.catapult.org.uk/

Companies House listing:
https://find-and-update.company-information.service.gov.uk/company/11837978

The latest accounts state: "The company is a private company limited by guarantee and consequently does not have share capital".

It does have members.  The articles of association state "Membership is solely open to Directors of the Company". A resolution has been signed by two members who appear to be individuals and not public bodies. 

The latest accounts suggest there are five wholly owned subsidiaries:

* Connected Places Catapult Services Ltd
* Future Cities Catapult Ltd
* Future Cities Catapult Services Ltd
* Transport Systems Catapult Ltd
* Transport Systems Catapult Services Ltd

These companies do not appear to be subject to FOI via [Section 6 of the Freedom of Information Act (Publicly-owned companies)](https://www.legislation.gov.uk/ukpga/2000/36/section/6), though they may be if the members are "acting on behalf of a relevant public authority".

**Comment by RichardTaylor** [comment]
What best serves our users? 

Do we have examples of requests made to public bodies such as Innovate UK and Government Departments which provide funding to the Catapults where they say they don't hold the information sought?

**Comment by HelenWDTK** [comment]
https://wdtkwiki.mysociety.org/wiki/Authority_suggestions
