### ISSUE TITLE
Reduce length of outgoing message footer

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1115]
[Current](https://github.com/mysociety/whatdotheyknow-theme/blob/master/lib/views/outgoing_mailer/_followup_footer.text.erb):

```
Disclaimer: This message and any reply that you make will be
published on the internet. Our privacy and copyright policies:
https://www.whatdotheyknow.com/help/officers

For more detailed guidance on safely disclosing information, read the
latest advice from the ICO:
https://www.whatdotheyknow.com/help/ico-guidance-for-authorities
https://www.whatdotheyknow.com/help/ico-anonymisation-code

Please note that in some cases publication of requests and
responses will be delayed.

If you find this service useful as an FOI officer, please ask your
web manager to link to us from your organisation's FOI page.
```

It's getting a bit close to wall-of-text IMO.

**Comment by garethrees** [comment]
Proposed:

```
Disclaimer: This message and any reply that you make will be published on the internet.

Please see our help page for FOI officers for details about our privacy and copyright
policies and detailed guidance on safely disclosing information.

https://www.whatdotheyknow.com/help/officers
```

I think this would then result in a need to update the intro to `/help/officers`, with the long-form FAQ-style content beneath it.

**Comment by garethrees** [comment]
> > guidance on safely disclosing information
> There isn't advice on that subject at

Yeah, the intention was to move those links from the footer to the help page.

**Comment by garethrees** [comment]
https://github.com/mysociety/whatdotheyknow-theme/issues/867#issuecomment-895108202 proposes:

> This message and any reply that you make will be published on the internet.
> Please use request-[xxxxx-xxxxxx]@whatdotheyknow.com for all correspondence about this request.
> Read more about replying to information requests made through WhatDoTheyKnow: https://www.whatdotheyknow.com/help/officers

**Comment by WilliamWDTK** [comment]
I'd propose adding "automatically published on the internet, normally (but not always) immediately"

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
