### ISSUE TITLE
Add advice on avoiding data breaches to officer help page

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1118]
New section for 

https://www.whatdotheyknow.com/help/officers

incorporating advice including that at

https://www.mysociety.org/2013/06/13/whatdotheyknow-team-urge-caution-when-using-excel-to-depersonalise-data/

**Comment by RichardTaylor** [comment]
Links to https://github.com/mysociety/whatdotheyknow-theme/issues/1115

**Comment by RichardTaylor** [comment]
The advice should include links to:

https://ico.org.uk/media/for-organisations/documents/how-to-disclose-information-safely-removing-personal-data-from-information-requests-and-datasets/2013958/how-to-disclose-information-safely.pdf

and

 
https://ico.org.uk/media/1061/anonymisation-code.pdf

**Comment by garethrees** [comment]
Just noting some specifics and search terms:

* Cached data
* Hidden sheets
* Filters don't remove data

Excel, Spreadsheets, XLS, XLSX.

Also marking as blog-idea as it may be that we publish a post and link to it from this page.

**Comment by garethrees** [comment]
Incorporate https://github.com/mysociety/whatdotheyknow-theme/issues/1745

**Comment by HelenWDTK** [comment]
My current plan is to spin this off by itself and add a link from the officer page

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
