### ISSUE TITLE
Respond to consultation on Strategic Lawsuits Against Public Participation

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1120]
The consultation includes consideration of changes to defamation law which, if made, could assist with the running of WhatDoTheyKnow.com

https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1061468/slapps-call-for-evidence-web.pdf

**Comment by garethrees** [comment]
FYI @ajparsons

**Comment by RichardTaylor** [comment]
I've started an internal notes document 

https://docs.google.com/document/d/1GuJuBWIfFNh8drBmApSHuGV9QxR-RSsTKr_gHCHxGD8/edit?usp=sharing

**Comment by ajparsons** [comment]
Here is my go at draft 1 based on Richard's notes. 

https://docs.google.com/document/d/1hjWG6lD1i9Q4L3ZBelWfcI8hbqPVOA3adlFF6HEXiOo/edit#

I've made up bits, please re-edit where that makes sense.

I think it needs a bit more on the examples in a few places (this is really what they're after), but understand that's not always simple.

I've fleshed out the general argument around universities, but it really needs a concrete example of our experience that shows why its a slapp issue to ground it. 

I'll be back on the 18th, so can tidy for final submission and can try to keep an eye on any questions for me (if any come up) before then. 

@RichardTaylor : Can you have a look through for yourself and flag for any other volunteers bits they might have input/opinions? If there's bits of the notes I've dropped you thought were important, please drop back in.

**Comment by garethrees** [comment]
This go published at: https://research.mysociety.org/html/slapp-response
