### ISSUE TITLE
Something strange with a handful of bodies having a blank name on Welsh version of site

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1123]
I accidentally ended up on the /cy/ version of the body admin page

https://www.whatdotheyknow.com/cy/admin/bodies

The first ~20 bodies there are currently shown with blank names. 

One entry relates to 

https://www.whatdotheyknow.com/body/whippingham_parish_council

the Welsh link

https://www.whatdotheyknow.com/cy/body/whippingham_parish_council

redirects to

https://www.whatdotheyknow.com/cy/body/body 

Something's wrong here but I'm not quite sure what.

**Comment by garethrees** [comment]
As of right now:

```ruby
PublicBody::Translation.where(name: '', locale: 'cy').count
# => 18
```

**Comment by FOIMonkey** [comment]
I raised this again due to my continued inability to find anything on GitHub: https://github.com/mysociety/alaveteli/issues/7132

I suspect there will be more places where this is visible if we looked, such as on the category pages.

**Comment by garethrees** [comment]
Going to close in favour of https://github.com/mysociety/alaveteli/issues/7132 as they're likely the same underlying cause.
