### ISSUE TITLE
Find missing email addresses for Business Improvement Districts

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1124]
Many Business Improvement Districts have been listed without email addresses 

https://www.whatdotheyknow.com/body/list/bid

The London BIDs are being reviewed via the following spreadsheet:

https://docs.google.com/spreadsheets/d/1tejPY6BltJw6_k8Qg9zQj-UEC0UluqnrvAiiqV1-wew/edit#gid=0

This ticket is for the outstanding action following the closure of: Add business improvement districts #726 

We hope users may find and propose missing addresses, and this may become more likely in the future if features for making, and encouraging, such submissions are added (https://github.com/mysociety/alaveteli/issues/3477).

**Comment by RichardTaylor** [comment]
>The London BIDs are being reviewed via the following spreadsheet:

>https://docs.google.com/spreadsheets/d/1tejPY6BltJw6_k8Qg9zQj-UEC0UluqnrvAiiqV1-wew/edit#gid=0

Review complete.

**Comment by RichardTaylor** [comment]
Related: 

* System data request for all public bodies with no email addresses #1084 

Easy access to the list of bodies in this category with missing email addresses would make this task easier.

**Comment by garethrees** [comment]
https://www.whatdotheyknow.com/search/tag:missing_email%20AND%20tag:bid/bodies
