### ISSUE TITLE
Blog on listing of  Business Improvement Districts 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1125]
https://www.whatdotheyknow.com/body/list/bid

* Explain role of BIDs and why we think they should be subject to FOI (they raise and spend taxes, and have significant influence on the public realm). 
* Note our policy of listing bodies which are not subject to FOI but we think should be, as part of our activist approach to seeking to extend public sector transparency. 
* Note while we've got many email addresses we don't have them all; those seeking to make requests to BIDs we don't hold email addresses for will be prompted to find them.

**Comment by RichardTaylor** [comment]
Blog draft

https://docs.google.com/document/d/1D1ff5I-6zbclsOGQW3yGgBMLYqq8ZOZDJBpqwPwyN2g/edit?usp=sharing

@MyfanwyNixon

**Comment by garethrees** [comment]
Published at https://www.mysociety.org/2022/04/27/business-improvement-districts-on-whatdotheyknow/
