### ISSUE TITLE
Improve coverage of bodies serving those most in need of improved public services

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1126]
Possible approaches:

* Identify areas of poverty, poor health outcomes, or poor educational outcomes and make a focused attempt to improve our coverage of bodies in those areas
* Check we're listing the poorest performing schools, surgeries, etc.

**Comment by RichardTaylor** [comment]
As well as ensuring we list such bodies, we could also focus efforts to improve public body notes on such bodies.

**Comment by confirmordeny** [comment]
now listed here: https://wdtkwiki.mysociety.org/wiki/Authority_suggestions
