### ISSUE TITLE
Improve London Fire Brigade listing

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1127]
https://www.whatdotheyknow.com/body/lfb

Consider renaming body from 

>London Fire Commissioner (London Fire Brigade) 

to

>London Fire Brigade

The notes should explain what the body subject to FOI actually is, and focus on what FOI requesters using our service need to know. References to other public bodies should link to their pages on WhatDoTheyKnow. 

Statements made in notes should be referenced.

**Comment by confirmordeny** [comment]
I have renamed it to the London Fire Brigade.
