### ISSUE TITLE
Public body update form is currently slow and timing out

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1132]
>504 Gateway Time-out
>nginx

Rest of the site is working fine

**Comment by RichardTaylor** [comment]
The issue is only on submitting a change, it's taking lots of retries to get a change made.

**Comment by RichardTaylor** [comment]
Now a different error:

>Sorry, there was a problem processing this page
>You have found a bug. Please [contact us](https://www.whatdotheyknow.com/help/contact) to tell us about the problem

**Comment by garethrees** [comment]
Quick update – there's a backlog of indexing jobs to process (currently 35k) - see `#whatdotheyknow` slack channel. Will investigate more on Monday, but a few more hours and it should be back to normal.

**Comment by garethrees** [comment]
Should now be resolved by https://github.com/mysociety/alaveteli/issues/1240
