### ISSUE TITLE
2022 Annual inbox analysis

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1135]
The 2022 annual inbox audit is currently in progress:

Data has been collect from the inbox and the analysis of this has started. Details can be found here
https://docs.google.com/spreadsheets/d/1hglHy_fDoIzGNElfz1wUbM1P8ANlhzH_5gr_iUC5OMQ/edit#gid=1734648625

Next steps: 
>write up an initial findings from the figures (proposed as an internal blog)
>further analysis of findings to help give a rounded picture of where we need more resources (both in terms of people and site improvements)

It has also been added to the Wiki page https://wdtkwiki.mysociety.org/wiki/Annual_Inbox_Analysis

Sally

**Comment by sallytay** [comment]
Internal blog posted at https://mail.google.com/mail/u/0/?tab=rm&ogbl#trash/FMfcgzGpFWTLRJrtsJplwqlDPBXdndfj

**Comment by RichardTaylor** [comment]
>Internal blog posted at https://mail.google.com/mail/u/0/?tab=rm&ogbl#trash/FMfcgzGpFWTLRJrtsJplwqlDPBXdndfj

That link doesn't work for me, it's to a deleted email thread in the support inbox I think. 

The blog is at 

https://blogs.mysociety.org/internal/2022/04/21/insight-into-whatdotheyknow-support/
