### ISSUE TITLE
Consider finding/adding associations of BIDs

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1137]
We should consider adding BID associations.  

Extracting from a thread:

@WilliamWDTK:
> Would we want to list associations of BIDs?  One example (I don't know whether there are others) is the [Northern BIDs Group](http://www.northernbidsgroup.com/).

@RichardTaylor:
> Yes. 
>
> If we list BIDs we should list bodies made up of BIDs, just as we list other bodies made up of other public bodies. (We do the latter because bodies made up of other public bodies are subject to FOI).

Would we want any tags aside from `association`?

Possible candidates identified so far (could put in a spreadsheet):

- [British BIDs](https://britishbids.info/) (national)
- [Northern BIDs Group](http://www.northernbidsgroup.com/) (North of England: Bradford, Chester, Durham, Leeds, Liverpool, Manchester, Newcastle, Sheffield, Sunderland & York)

**Comment by RichardTaylor** [comment]
We need to look to see if organisations really are owned by / made up of other public bodies. 

If all the shareholders / members of an organisation are other public bodies then the organisation is a public body for FOI purposes. 

Often the governing documents available on Companies House, or records of shareholdings, again on Companies House, can help. 

* [British BIDs](https://britishbids.info/) (national)
The company behind this appears to be https://find-and-update.company-information.service.gov.uk/company/07473073 which has one share owned by Central Management Solutions Limited which appears to be the company now called Savills Place-Shaping & Marketing Ltd https://find-and-update.company-information.service.gov.uk/company/07595573 That company's accounts notes is ultimate parent is Savills PLC.  I suspect that one does not have the character of a public body. I propose we don't list it. 

* [Northern BIDs Group](http://www.northernbidsgroup.com/)
There is no company mentioned on this organisation's website, it does appear to just be what it says, an association of BIDS, on that basis **we should list it.**  The co-chairs have contact details at the respective BIDS they are from. It looks to be perhaps like an unincorporated association.

**Comment by RichardTaylor** [comment]
*The South West BIDs Group
https://www.southwestbids.co.uk/sw-bids
We should list this one, it appears to be just what it says, a group of BIDs.
It has a chairman, and a website, it appears to exist as a body independent of its constituent parts.
(We could also check we're already listing its members) 

* The West Cheshire BID group  
We should list this one too. 
https://visitnorthwich.co.uk/collective-bids-group-announced-to-champion-west-cheshire/
It appears to have a logo. I can't find a website, or any references to it after the announcement of its establishment!

**Comment by RichardTaylor** [comment]
* Scottish City BIDs Group - Recent news article https://www.agcc.co.uk/news-article/scottish-city-bids-call-for-safe-and-full-return-to-office 

Probably not to list:
* The BID Foundation - https://www.placemanagement.org/the-bid-foundation/
* Industrial BIDS Group - https://britishbids.info/industrial-bids-group

**Comment by confirmordeny** [comment]
I have added what I can here: https://www.whatdotheyknow.com/body/list/group_of_bids
