### ISSUE TITLE
Accessibility issues

### ISSUE THREAD

**Issue by lucascumsille** [mysociety/whatdotheyknow-theme#1138]
Hi @garethrees last sprint we talked about me, checking the WhatDoTheyKnow theme. These are some of the issues I have found. Let me know if you want me apply some fixes to them.

#### Blue Button
<img width="330" alt="Screenshot 2022-04-14 at 08 58 50" src="https://user-images.githubusercontent.com/13790153/163359830-5be08c82-de54-4423-b252-1cda465509f4.png">

#### Navigation bar
<img width="855" alt="Screenshot 2022-04-14 at 09 00 55" src="https://user-images.githubusercontent.com/13790153/163359963-6142da69-8f94-4f3f-aba9-56a2bab837c1.png">

### Homepage
<img width="916" alt="Screenshot 2022-04-14 at 08 57 12" src="https://user-images.githubusercontent.com/13790153/163360066-552d0341-ddf4-4d55-81ac-168bd7316356.png">

### Dashboard (en/alaveteli_pro/)
<img width="855" alt="Screenshot 2022-04-14 at 09 02 25" src="https://user-images.githubusercontent.com/13790153/163360534-06de4e66-b0fb-4823-ab29-6cee48a7f061.png">

### en/alaveteli_pro/info_requests/new
I would also give the warning a yellow or red colour, so it pops out more. Plus some vertical alignment so the the lock and text are at the same height.

<img width="497" alt="Screenshot 2022-04-14 at 10 52 17" src="https://user-images.githubusercontent.com/13790153/163360894-473ceabc-0d1e-433a-93e9-97b611dd4095.png">
<img width="497" alt="Screenshot 2022-04-14 at 10 53 04" src="https://user-images.githubusercontent.com/13790153/163361038-4c6f741c-6eb0-4039-a45b-683067277567.png">

### en/request/the_cost_of_boring_two#incoming-3
Not a major thing

"Help" button 
Possible solution
<img width="1029" alt="Screenshot 2022-04-14 at 11 11 36" src="https://user-images.githubusercontent.com/13790153/163364533-7a127f35-062b-4b54-b1b9-3b040397fab9.png">
`
    font-size: 10px;
    text-transform: uppercase;
    font-weight: 700;
`

Current state
<img width="1029" alt="Screenshot 2022-04-14 at 11 12 00" src="https://user-images.githubusercontent.com/13790153/163364515-a2cf36c4-f29a-42af-b711-488ac1b5dcb0.png">

#### Links on the request link sections

<img width="340" alt="Screenshot 2022-04-14 at 11 16 23" src="https://user-images.githubusercontent.com/13790153/163365149-c905989f-c38b-4cbd-a539-8c4c1d7442dc.png">

**Comment by lucascumsille** [comment]
### en/help/about

Not major, but the list items could use some more vertical padding, so they don't look so tight and also help users to have a better clickable area.

<img width="343" alt="Screenshot 2022-04-14 at 11 22 24" src="https://user-images.githubusercontent.com/13790153/163366005-c1dee0d6-b6dd-42b3-b75e-256262be66a0.png">

**Comment by lucascumsille** [comment]
### Styling issue

#### Secondary button mixin
The background colour makes the element too subtle, it could benefit of some colour, that still make it look like a secondary element without being too subtle.

Possible solution
<img width="1028" alt="Screenshot 2022-04-14 at 11 01 10" src="https://user-images.githubusercontent.com/13790153/163362634-7d8dcc79-44ac-4d30-831e-1d2dd59cda7f.png">

Current state
<img width="1028" alt="Screenshot 2022-04-14 at 11 01 25" src="https://user-images.githubusercontent.com/13790153/163362765-fa2c49c2-6fbb-4996-8e67-5df2c97db259.png">

**Comment by garethrees** [comment]
I think all of these look sensible improvements, other than the "[Secondary button mixin](https://github.com/mysociety/whatdotheyknow-theme/issues/1138#issuecomment-1099064678)". To me the light blue in the proposed solution looks a bit jarring. Perhaps we could make the brown background a bit darker instead?

**Comment by garethrees** [comment]
Also note that much of this styling _may_ come from Alaveteli core, so we should fix them there if possible, and only fix in whatdotheyknow-theme if that's the place that has introduced a problem.
