### ISSUE TITLE
Add a help-page sidebar to the advanced search page

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1141]
The [advanced search page](https://www.whatdotheyknow.com/advancedsearch) is linked in the help-page sidebar:

![Help page sidebar](https://user-images.githubusercontent.com/99501342/163729736-8f1a2416-ae01-41ab-9013-284a1aee9a3a.png)

However, the page itself does not have the sidebar, meaning it is slightly inconsistent, and marginally more inconvenient to navigate.

**Comment by garethrees** [comment]
Linking to https://github.com/mysociety/alaveteli/pull/3037#issuecomment-187203464 – not sure of the history for this page, but assume it's similar.

**Comment by HelenWDTK** [comment]
AIUI this is intentional, and down to the ways that you interact with that page via the site (eg via a link from the search and not other help pages as such).
