### ISSUE TITLE
Improve wording on "Contact us" page

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1142]
The section of the ["Contact us" page](https://www.whatdotheyknow.com/help/contact) about contacting "a public authority, like my **local council, hospital, or school**." has a slightly odd text introducing the [WriteToThem](https://www.writetothem.com/) link (incidentally: *WriteToThem* or *WriteToThem.com*?):

![](https://user-images.githubusercontent.com/99501342/163729954-32f8e784-8823-4321-9a6b-108df746640e.png)

> If you want to write to your MP, local councillor, or other representative, you can [write to your MP on WriteToThem.com.](https://www.writetothem.com/)

The first part refers to three (types of) people that one might want to write to, but the link refers only to MPs. 

Also: the "Of" in "Freedom Of Information" might be better as lowercase.

**Comment by garethrees** [comment]
> If you want to write to your MP, local councillor, or other representative, you can [WriteToThem.com](https://www.writetothem.com/).

😁? 

I think we have 3 todos:

- [ ] Decide on updated phrasing for the WTT bullet
- [ ] Make the text update to the WTT bullet
- [ ] Make the text update to Of → of in the first bullet

**Comment by WilliamWDTK** [comment]
> > If you want to write to your MP, local councillor, or other representative, you can [WriteToThem.com](https://www.writetothem.com/).
> 
> grin?

I'd probably not go with that wording, but I suppose we could.

> I think we have 3 todos:
> 
>     * [ ]  Decide on updated phrasing for the WTT bullet

In the "Snippet - Where to find help" canned response in the support inbox, we say:

> You could try writing to your local Member of Parliament (MP) or councillors. You can find and write to your elected representatives via: http://www.writetothem.com/

So, we call them more generally "elected representatives".

**Comment by garethrees** [comment]
How about:

> If you want to write to your MP, local councillor, or other elected representative, you can do so using [WriteToThem.com](https://www.writetothem.com/) service.

**Comment by sallytay** [comment]
I think that would work

**Comment by mdeuk** [comment]
> How about:
> 
> > If you want to write to your MP, local councillor, or other elected representative, you can do so using our [WriteToThem.com](https://www.writetothem.com/) service.

Could also be something like "You can find, and contact, your local elected members using [WriteToThem](https://www.writetothem.com/)."

As a side question - from a branding perspective, WTT doesn't include the '.com' in its branding - what's the best way to refer to it in this context?

**Comment by WilliamWDTK** [comment]
> * [ ]  Make the text update to Of → of in the first bullet

Just to note, this particular point also applies to the first section ("I want to contact a **government department** – for example, Visas and Immigration, the Home Office, HMRC, or the Department for Work and Pensions."):
![image](https://user-images.githubusercontent.com/99501342/164443620-e08f7d4b-6b1a-484e-80b7-f9990abeb0a5.png)

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
