### ISSUE TITLE
Create new volunteer job descriptions

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1145]
This is one of the tasks detailed in the Volunteer recruitment plan from ticket https://github.com/mysociety/whatdotheyknow-theme/issues/1038

Create volunteer job descriptions for initial recruitment phase: 
>Bodies Database admin
https://docs.google.com/document/d/1hx3RHsfP6hYvB_gIJ6RW94khnYnFHSRO0F4c2mYoIlY/edit
>Classifier plus (needs new name) 
https://docs.google.com/document/d/1lXYXeMQ10FbWPYCNskbBOysoSmazXUHkdcU8atCmb3k/edit
>User Advisor (needs a new name)
https://docs.google.com/document/d/1991FO9WQ6RcPekHW-bp_-7U93NEp0c1nw5jMEw1AD3s/edit

I've started work on these, the format and some of the content is based on the mySociety staff roles that have been recently posted. I've also used some of the text from the Reach volunteering ads that we posted last year.

If anyone has comments or suggestion on the content of these I'd appreciate your input. I would like to have them finalised from our side by 2nd May.

**Comment by sallytay** [comment]
Thank you for the comments that have been made on these. 

If anyone else has anything to add could you let me know by 2nd May

**Comment by sallytay** [comment]
Just to update the status of these. I've sent them on to Yolanda (mySociety HR and Wellbeing Manager), who isn't a GitHub user and @MyfanwyNixon for further review.

**Comment by sallytay** [comment]
Update: These have now been reviewed by everyone.

The final job titles are
FOI content researcher (previously categoriser plus)
FOI help desk administrator (previously user advisor)
FOI database administrator (previously Bodies database administrator)

There is one outstanding suggestion is to improve this line to make it stronger, I don't think we want to add a time limit ie daily or weekly as that would depend on what the volunteer was working on, although I realise that could come across as being a little vague

>We just ask that you keep in touch and let us know how you are getting on with your tasks.

**Comment by MyfanwyNixon** [comment]
'keep in regular touch' might work!

**Comment by sallytay** [comment]
These have now been finalised.

I've created a new WDTK wiki page for the admin team to be able to access them easily
https://wdtkwiki.mysociety.org/wiki/Volunteer_Job_Descriptions

To note the page isn't quite finished yet, which is noted on the there

**Comment by sallytay** [comment]
All actions on this ticket have been completed.
