### ISSUE TITLE
Add full blank agenda template to WhatDoTheyKnow High Risk Cases & Policy call rolling agenda document

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1147]
Currently we have a template for 

>Key standing context questions :

but not for the rest of the meeting structure. 

Having a template for items on individual cases would be useful. 

I also suggest a new agenda item, which usually wouldn't need any discussion:

>**Review threads not selected for the agenda:**
>* A single sentence on each of these might aid assurance they’ve been considered and don't need discussing.

**Comment by RichardTaylor** [comment]
On a related point arising from the last call. Where a proposal involves a Legitimate Interests Test include, or link to, a copy of the factors taken into account conclusion, as they would be presented to the individual concerned.  

Perhaps that's the kind of practice which could be noted on an agenda template?

**Comment by sallytay** [comment]
>Having a template for items on individual cases would be useful.

I've created a template for the individual cases and other agenda items - I've done this in a separate document and linked that to the agenda to avoid the main agenda document containing too much text.

>I also suggest a new agenda item, which usually wouldn't need any discussion: Review threads not selected for the agenda:
A single sentence on each of these might aid assurance they’ve been considered and don't need discussing.

I've added this to the next agenda, we can see how this works in the next meeting

**Comment by garethrees** [comment]
Thanks! Looks like this is resolved so can be closed?
