### ISSUE TITLE
Combine, or emphasise difference between, canned responses "Upload-response-obtained-privately" and "Post-response-to-offsite-address"

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1148]
These two canned responses seem to serve the same purpose, or very similar if not exactly the same.  Could they be combined?

**Upload-response-obtained-privately**
>We don't allow people to upload responses to requests they have made directly to public bodies.
>
>One reason for this is that currently our service gives some assurance responses are genuine and really did come from the public body in question.
>
>Hosting any material users wanted to upload might well cause us quite a challenge in terms of moderation and confirming the authenticity of the material.
>
>In the future, if you use our service, WhatDoTheyKnow.com to make your requests, we'll automatically publish the requests and responses for you.
>
>A repeated request from the same person may well, legitimately, be rejected so you probably shouldn't make your requests again via our service to attempt to get the responses published.
>
>You might though want to consider making a request via our service under a pseudonym for eg. "the responses to FOI requests references xxxx and xxxx".
>
>https://www.whatdotheyknow.com/help/privacy#public_names 
>
>Regards,
>

**Post-response-to-offsite-address**
>We don't publish FOI responses to requests made outside of our site.
>
>You could make the request(s) again via our service, perhaps simply of the form "Please release a copy of your response to request reference XXXX".
>
>A repeated request can be rejected, so consider our advice at:
https://www.whatdotheyknow.com/help/privacy#real_name
>
>Regards,
>

**Comment by WilliamWDTK** [comment]
I would suggest perhaps combining them to:

>We don't publish FOI responses to requests made outside of our site, nor do we allow people to upload responses to requests they have made directly to public bodies.
>
>One reason for this is that currently our service gives some assurance responses are genuine and really did come from the public body in question.
>
>Hosting any material users wanted to upload might well cause us quite a challenge in terms of moderation and confirming the authenticity of the material.
>
>In the future, if you use our service, WhatDoTheyKnow, to make your requests, we'll automatically publish the requests and responses for you.
>
>A repeated request from the same person may well be, legitimitely, rejected, so you probably shouldn't make your requests again via our service to attempt to get the responses published.
>
>You might though want to consider making a request via our service under a pseudonym for eg. "the responses to FOI requests references xxxx and xxxx".
>
>https://www.whatdotheyknow.com/help/privacy#Names
>
>Regards,

**Comment by garethrees** [comment]
Related to #1060

**Comment by RichardTaylor** [comment]
>Post-response-to-offsite-address

I think this one is intended for when someone writes to us asking why they can't find a FOI request/response they've seen mentioned somewhere like Parliament, a news article, or in a research paper isn't available on WhatDoTheyKnow

The heading/title here could perhaps usefully better reflect its purpose.

**Comment by sallytay** [comment]
I've updated the canned response for "Upload-response-obtained-privately" using the text suggested by William

I've renamed "Post-response-to-offsite-address" with "Request_not_made_on_WDTK"

I've also updated the text to say

>The FOI request that you have mentioned was not made on the  WhatDoTheyKnow site.
We only publish requests that are made on our site and not those made directly to authorities
You may be able to find the original FOI request by looking at the public disclosure log of the authority who provided the response

I've updated the templates in the inbox, on the back up document and on the Wiki

Happy to further tweak the wording if others think more should be included

**Comment by RichardTaylor** [comment]
>Happy to further tweak the wording if others think more should be included

It could be made clearer that our advice on making a concise request under a pseudonym is intended for those seeking to evade [the provision enabling bodies not to respond to a repeated request](https://www.legislation.gov.uk/ukpga/2000/36/section/14). 

>A repeated request from the same person may well be, legitimately, rejected. If you want to get the response to your request published on WhatDoTheyKnow you could make a concise request via our service under a pseudonym for eg. "the responses to FOI requests references xxxx and xxxx". See our advice on using pseudonyms at https://www.whatdotheyknow.com/help/privacy#Names

**Comment by sallytay** [comment]
Thank you for the suggestion, I've updated the canned response to include that text.
