### ISSUE TITLE
Adopt policy of summarising and presenting cases escalated to review, including all relevant emails and keeping review threads up-to-date

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1149]
Under previous arrangements we used to summarise and present cases when they were escalated, we had one thread per case, we included all relevant material in the thread, and we kept threads up-to-date. 

Our current process doesn't include providing summaries, keeping review threads up-to-date, having one review thread per case or including all relevant emails in review threads. 

Advantages of reverting something more like the previous arrangements :

* It makes it easier for those contributing at the review level, and saves them time. 
* Summaries would be available for using as a basis for the High Risk etc. call agenda. 
* The High Risk etc. call agenda could be compiled using only information from the review group. 

Disadvantages of the previous arrangements:

* [Claimed]Creates a divide between admins and review
* Makes escalation to review more time consuming (we could have an exception for cases being escalated when the person doesn't have the time to summarise the case/issues). 
* Possible data protection issues depending on who is on the review group and how they access it. 

Current policy [WDTK Review Process Changes | February 2021] document notes:

>There’s no way of automatically forwarding any subsequent correspondence on a thread in the support mailbox to review ... , so whoever is handling the case on the staff side is going to need to check the support mailbox too for relevant information. 

This has been discussed on catchup calls, I have noted

>What I am in favour of though is all case details being on the review group when I get there, and not having to also go into the inbox - not only for myself but because I want to enable others to volunteer "at the review level" - and perhaps to recruit into that role - though actually if we want more advisory input we probably need to go above the individual case level - and work on the basis of summaries of issues eg. landlord registers, and general stats such as those proposed in the transparency report

While this has been discussed before, including when devising the current system, we don't currently have an issue for it.

**Comment by RichardTaylor** [comment]
Related to this we could re-adopt a policy of explaining the reason for escalation. Examples of past practice:

>This is being sent to wdtk-legal as its a legally and reputationally risky area, and a lot of people's data is involved.

>This is being sent to WDTK-legal due to defamation concerns having been raised, and we judge defamation cases as risky. 

>Reasons for escalation to wdtk-legal: Involvement of a court order (even though it doesn't appear to bind us), potential defamation, and the general policy/practice issues raised by this case.

**Comment by mdeuk** [comment]
What problem are we seeking to solve with this?

There are probably some ways we could _**improve**_ the current process - but I don’t necessarily think that switching back to the original process will work. We simply don’t have the resource for that.

If we are seeking to make the process simpler - I would be tempted to look at drafting a proforma which we can use to evaluate the cases and generate a summary that way. 

Looking toward a process driven method would have the advantage of not merely moving correspondence from one mailbox to another (with a wider audience), but enabling a more standard evaluation process which allows for improved decision making / assignment to the ‘right’ place based on risk / circumstances.

You could, perhaps, also envision this being used as a method of automatically generating the relevant referral on agendas where applicable.

**Comment by RichardTaylor** [comment]
>switching back to the original process will work. We simply don’t have the resource for that.

I think overall better quality escalation reports are more resource efficient, especially if you assign greater value to the time/effort of those acting at the review level than those acting below that level. 

>look at drafting a proforma 

This is something we've done in the long distant past. We used to complete "Takedown Assessment" forms" which included a summary of issues and a recommendation.   We hold copies on the wiki. https://wdtkwiki.mysociety.org/mediawiki/index.php?search=takedown+assessment 

We could develop that kind of approach again. The key things I think to include are 

* Issue summary
* Proposed action
* Any relevant deadlines
* Reason for escalation
* Background information: Details of considerations, copies of correspondence, links to materials / guidance / policy etc.

Two further comments:

* Currently we have a divergence between policy and practice. We are generally keeping review threads up-to-date although this is not required by the escalation policy. The policy is actively designed not to require it, review duty holders are expected to find and review all relevant material. The escalation is merely an alerting system. This is a problem because
  * It is confusing for new admins
  * It can surprise review duty holders (and has surprised them) if they've been used to finding all the material they need on a review thread, but in a rare case the policy has been followed, and the review thread not kept up-to-date. 

* The review group archives are kept indefinitely. If we don't keep review threads up-to-date we lose copies of material it might have been useful to keep.

**Comment by HelenWDTK** [comment]
The current practice seems to be sufficient (speaking as someone who escalates cases, and reviews others). If individuals wish to provide more information that is asked for, that's up to them, but I will always check the relevant inbox threads when looking at a case to ensure that I haven't missed any material. I've reviewed the documentation on the wiki, as part of a wider tidy up, and I think the current documentation on escalation is clear about what is and is not expected of admins.
