### ISSUE TITLE
Respond to ICO consultation: "Call for views: data security incident trends"

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1150]
>Please send us your responses by 5pm on 30 April 2022 when the call for views will close.

https://ico.org.uk/about-the-ico/ico-and-stakeholder-consultations/call-for-views-data-security-incident-trends/

We want to Improve outcomes arising from our reporting of of data breaches by public bodies to the ICO #1128 

cc @ajparsons 

Existence of consultation noted by Louise on Slack.

**Comment by RichardTaylor** [comment]
We do want feedback showing our reports have been acted on. 

Would we want the ICO to publish how many reports we've made and/or how many data breaches have been made by public bodies via WhatDoTheyKnow? There is a reputational risk if it isn't clear that the breach is by the public body.

**Comment by ajparsons** [comment]
It's ok just to reply to a few. These seem like the ones there *might* be an opinion on? I'm also happy to do nothing if there isn't. 

> C11	Is there any other information you would like us to publish about data breaches that are reported to us?
> 
> Yes												☐
> 
> No												☐
> 
> If yes, please provide details about the additional information you would like and why
> 
> Click or tap here to enter text.
> 
> 
> C12 Do you have any concerns about the publication of breach reporting data?
> 
> Yes												☐
> 
> No												☐
> 
> If yes, please explain what these concerns are
> Click or tap here to enter text.
> 
> 
> C13	Do you have any additional comments about our breach reporting data?
> 
> Click or tap here to enter text.
>

**Comment by RichardTaylor** [comment]
I'm erring towards not responding on the grounds we don't have much, if anything, to say about how they publish their statistics. 

Do we have a comment on their classification of incident types? 

15% of issues covered in the latest Q2 2021/2 report come under "Other non-cyber incident", does that suggest that category is too broad?

Their classifications are below. The most serious issues we see arise from misunderstanding Excel's hidden sheets and pivot table functions. Is it clear where they would be classified? Does it matter?

The data could allow us to determine what fraction of the "failure to react" data breaches by central or local government in a certain time period were reported by us. I don't think we really want to do that though. 

Non-cyber security incidents | Alteration of personal data
-- | --
  | Data emailed to incorrect recipient
  | Data of wrong data subject shown in client portal
  | Data posted or faxed to incorrect recipient
  | Failure to redact
  | Failure to use bcc
  | Incorrect disposal of hardware
  | Incorrect disposal of paperwork
  | Loss/theft of device containing personal data
  | Loss/theft of paperwork or data left in insecure location
  | Not Provided
  | Other non-cyber incident
  | Unauthorised access (non-cyber)
  | Verbal disclosure of personal data
  |  
Cyber security incidents | Brute Force
  | Cryptographic flaw
  | Denial of service
  | Hardware/software misconfiguration
  | Malware
  | Other cyber incident
  | Phishing
  | Ransomware
  | Unauthorised access (cyber)

[Source](https://ico.org.uk/media/action-weve-taken/csvs/4018947/data-security-incident-trends-q2-202122.csv)

**Comment by ajparsons** [comment]
Let's leave this one then, if we have more direct asks we can do that another way.
