### ISSUE TITLE
Consider policy and technical approach to hiding very old material

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1152]
Generally if we hide a correspondence thread from public view because it is not a request for information, vexatious, or personal correspondence we notify the user that we have done so and provide them with a link they can use to access the correspondence when they are logged in. 

Sometimes our attention is drawn to material which has been published for a very long time, for five, or ten years. 

Writing to people about a vexatious request they made many years ago can surprise them. 

Ideas:

* Warn admins who are about to send a message to someone in respect of correspondence which is more than say 2 years old and offer an option to silently hide the material [without writing to them].

* Adopt a policy of not informing users when we hide material as vexatious/personal correspondence/not FOI if the correspondence was sent over 2 years ago. 

We should consider the justification for continuing to hold such material once it has been removed from public view. Requesters may still have access to it, if they've kept the direct link and can still log into the site though.

**Comment by RichardTaylor** [comment]
>Writing to people about a vexatious request they made many years ago can surprise them.

It can also remind people of their behaviour and risk re-starting it, it can also ignite unnecessary correspondence.

**Comment by sallytay** [comment]
To note, after hiding a request that was considered personal correspondence from 2018, this did result in some unnecessary correspondence as a result of us notifying the user.

If we were to reconsider our policy we'd need to agree the timescale and the implications of whether we are still acting transparently in our actions.

The original timescale suggested, seems reasonable, however we do need to also consider whether this could be perceived as us not being transparent in our actions though.

>Adopt a policy of not informing users when we hide material as vexatious/personal correspondence/not FOI if the correspondence was sent over 2 years ago.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
