### ISSUE TITLE
Consider approach to moderating use of the citations / "in the news" feature

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1153]
Currently new citations are being noted, but not actively reviewed, via the "Alaveteli Professional Weekly Review" document and the fortnightly "Transparency programme sprint planning" call. 

If we had a public list of new citations (https://github.com/mysociety/alaveteli/issues/6701) that might enable, and prompt. us to moderate them and/or prompt people to report issues with them. 

There is some level of misuse of the feature, some of which may have arisen from a misunderstanding of its intent.

Do we want to proactively or reactively moderate citations?
Do we need tools ("report this" links) to encourage reports? 

As this is a new feature and we're intending to give prominence to cited requests some degree of proactive moderation (but still retrospective moderation) might be appropriate.

**Comment by HelenWDTK** [comment]
These get pulled out of the system and looked at on a fortnightly basis as part of sprint planning, so any misuse is likely to be noticed in that way.
