### ISSUE TITLE
FOI Life Hacks Blog Post

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1155]
Title suggested by Juliet. 

This could be a University related FOI hacks post. 

Use FOI to:

* Find out what qualifications those who get into the course you want have. (FOI makes access to universities more egalitarian as information previously shared by those in the know can now be obtained by anyone). 
* Get help while at university - use FOI to obtain past papers, mark schemes, examiners' reports etc. 
* Get a rent refund if the landlord/manager of your shared house wasn't registered when they should be. (Checking registration databases released via WDTK).

**Comment by RichardTaylor** [comment]
>A user has got Southeastern to publish a customer service email address - they usually force customers to use a webform: https://www.whatdotheyknow.com/request/email_address_for_your_customer

This could be a FOI life hack ... is a public service making it difficult for you to contact them .. use FOI to obtain the email address you need. 

Issue: WDTK redacts email addresses from responses so this might not be the type of request we want to promote!

**Comment by WilliamWDTK** [comment]
> > A user has got Southeastern to publish a customer service email address - they usually force customers to use a webform: https://www.whatdotheyknow.com/request/email_address_for_your_customer
> 
> This could be a FOI life hack ... is a public service making it difficult for you to contact them .. use FOI to obtain the email address you need.
> 
> Issue: WDTK redacts email addresses from responses so this might not be the type of request we want to promote!

People could request other forms of contact, perhaps (addresses to write to, phone numbers etc), so it could still be useful.

**Comment by confirmordeny** [comment]
See also #1425

**Comment by RichardTaylor** [comment]
>University related 

We list regulators of higher education accommodation:

* https://www.whatdotheyknow.com/body/uuk
* https://www.whatdotheyknow.com/body/unipol

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
