### ISSUE TITLE
Advise users referring cases to the ICO that if the action is slow they might need to contact us and ask us to re-open a thread to correspondence 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1156]
We provide advice on making a referral to the ICO at

https://www.whatdotheyknow.com/help/unhappy#refer-to-ico

We say:

>WhatDoTheyKnow does not currently have any special facilities for handling a referral to the Information Commissioner. We encourage users to leave annotations on requests keeping people informed of progress. Decisions by the Information Commissioner are published online and you can link to a decision via an annotation on the request.

>A warning. Although the Information Commissioner has worked hard to reduce their backlog of casework, it can still take several months to get resolution from them in many cases. One area where they have sped up things considerably is that they are able to prompt non-responsive authorities to reply within a few weeks of receiving a complaint. 

after that we could add

>[WhatDoTheyKnow closes old requests to new correspondence](https://www.whatdotheyknow.com/help/officers#allowed_responses). Where this happens a note appears on the request thread. You can contact us if we have closed a request on which a very late response is expected following an ICO, or similar, decision. 

Ticket aimed at preventing the need for this advice:

* https://github.com/mysociety/alaveteli/issues/5946

**Comment by RichardTaylor** [comment]
Related:  Improve help page advice on threads closed to new correspondence #1157

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
