### ISSUE TITLE
Improve help page advice on threads closed to new correspondence

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1157]
We have a section on this at

https://www.whatdotheyknow.com/help/officers#allowed_responses

We could usefully additionally note:

>Any responses sent to closed threads receive an auto-response letting the sender know what has happened and inviting them to get in-touch with us, asking us to re-open the thread. 

This advice is not just relevant to FOI officers, requesters may find it useful to. Perhaps it is currently in the wrong place on the help pages?

**Comment by confirmordeny** [comment]
Addressed as above.
