### ISSUE TITLE
Develop policy on access to the category based body selector for creating batch requests

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1160]
As I understand it:

* This is a beta feature which is not generally available to all pro users. 
* This feature has the potential to add great value to Pro users, saving lots of work identifying which bodies are responsible for what.
* This feature has the potential to improve accessibility to information, by reducing the amount of knowledge of how government is organised needed to properly target requests. 
* The feature has the potential to help people make better targeted batch requests (reducing work for both requesters and public bodies). 
* There is concern that the feature may make it too easy to inappropriately make requests to large numbers of bodies.

Clearly the latter two points there are in conflict. 

Proposed approach: 

* Make the category based selection tool available to all Pro users. 
* Act to reduce the misuse of the batch request service in other ways eg. 
  * Pre-approval of pro accounts
  * Lower initial cap on the size of a batch which can be removed on admin approval
  * Act robustly in response to misuse of the Pro service, warning and banning users where appropriate. 
  * Prevent continued use of Pro if responses remain uncategorised

**Comment by RichardTaylor** [comment]
Related: 

https://github.com/mysociety/whatdotheyknow-theme/issues/1043#issuecomment-1111112814

**Comment by garethrees** [comment]
Will send a more detailed update on this when we get a bit further, but we're aiming to do some collaborative work with [Sweden](https://handlingar.se/) during May to iron out some of the bugs and get this into a state that we're happy to enable for all Pros by default (or at least via the admin interface in an analogous way to removal of request cap for normal users).

**Comment by garethrees** [comment]
The main way we'll get this shipped initially, I think, is https://github.com/mysociety/alaveteli/issues/6862.

**Comment by garethrees** [comment]
> Pre-approval of pro accounts

We don't have capacity to do this.

> Prevent continued use of Pro if responses remain uncategorised

I disagree with this. I think its a much better situation to have high-impact users make their requests in a way that gets them eventually published and fed into the classification game. It's almost a _feature_ of the pro service. We get _much_ more information released this way.

> Act robustly in response to misuse of the Pro service, warning and banning users where appropriate.

I agree for "serious" misuse – obviously vexatious or non-foi use. Did you have other situations in mind?

**Comment by garethrees** [comment]
The current plan is to ship this without the "add all" button (https://github.com/mysociety/alaveteli/issues/6862), and then make "Add all" an on-request feature (https://github.com/mysociety/alaveteli/issues/7021) much like how users can request rate cap removal.

**Comment by garethrees** [comment]
This is now general availability to pro users.
