### ISSUE TITLE
Include standard legitimate interests in GDPR Legitimate Interest Response template

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1162]
Include standard factors setting out legitimate interest, and the public's legitimate interest, in us running our service in the table for balancing factors for and against publication. 

These can be taken from https://www.whatdotheyknow.com/help/privacy#legal_basis 
 
Note:

>The legitimate interests can be your own interests or the interests of third parties. They can include commercial interests, individual interests or broader societal benefits.

https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/lawful-basis-for-processing/legitimate-interests/

The aim could be achieved  by tweaking the text above the table to stress that items in the table are only additional case specific matters, and our starting point is that there are strong legitimate interests generally in providing our service.

**Comment by RichardTaylor** [comment]
This arises from my concern that our current process focuses too much on case-specific factors and does not give enough weight to the strong legitimate interests which generally apply to providing our service.

**Comment by sallytay** [comment]
We already say within the response that:

>We consider the legal basis for our processing of personal information to be that we have a legitimate interest as laid out  in Article 6(1)(f) of the GDPR). As set out at: https://www.whatdotheyknow.com/help/privacy#legal_basis. 

We could add this that text to help make it clearer.

>The legitimate interests can be your own interests or the interests of third parties. They can include commercial interests, individual interests or broader societal benefits.

The table should include all factors for and against publication within the table. From previous response feedback the feeling seemed to be to make them more case specific rather than general, however these should be based around our standard factors.

We need to be careful not overload people with information if it isn't relevant to their case.

I can draft up a new template that we can then review and agreed on, and also make sure that all the factors mentioned in the legal basis page are also in the legitimate interest library.

**Comment by garethrees** [comment]
>  From previous response feedback the feeling seemed to be to make them more case specific rather than general

I don't think this needs to be an either-or.

> We need to be careful not overload people with information if it isn't relevant to their case.

I agree, we should give prominence to the most important interests in the given case contexts. Our phrasing could be something like "In addition to our [general legitimate interests](https://www.whatdotheyknow.com/help/privacy#legal_basis), we have also assessed case-specific points…"

> make sure that all the factors mentioned in the legal basis page are also in the legitimate interest library.

I'm not sure we need to duplicate this. If we're not clear enough on the help pages about what we think are "standard factors" –  that we need to keep explaining – then we should do the work to elaborate on them there.

**Comment by RichardTaylor** [comment]
>We need to be careful not overload people with information if it isn't relevant to their case.

In almost all cases our general legitimate interests in running our service are relevant factors.

**Comment by RichardTaylor** [comment]
If we're re-drafting this we can deal with #996 at the same time.

**Comment by RichardTaylor** [comment]
I've suggested adding the following to the legitimate interest library:

>The information in question may well be used (or may already have been used) in connection with lobbying, journalism or academic research. Removal of material from our service could undermine those activities. WhatDoTheyKnow provides a public archive of FOI requests and responses, and so holding copies of FOI related correspondence is necessary for us to provide our service.

I'd expect that to be used in many cases and it reflects, but doesn't entirely duplicate, what we already say in public at https://www.whatdotheyknow.com/help/privacy#legal_basis

I'd make it part of the template but putting it in the snippet library may well suffice, the important thing is that it ends up being given appropriate weight in our considerations / responses.

**Comment by sallytay** [comment]
I've added this to the  legitimate interest library as suggested
