### ISSUE TITLE
Issue with WhatDoTheyKnow request 676701

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1163]
Currently the request page gives non-logged in users, and non-proadmins a

>Sorry, we couldn't find that page

error, but links to the attachments still work. 

The request was publicly accessible as of last night.

**Comment by garethrees** [comment]
```
Event 11140775: Expire embargo 2022-02-17 13:45:42 +0000
…
Event 11749715: Response 2022-04-27 13:56:52 +0100
Event 11759086: Set embargo 2022-04-28 09:28:01 +0100
```

**Comment by garethrees** [comment]
A case of https://github.com/mysociety/alaveteli-professional/issues/578

**Comment by garethrees** [comment]
> error, but links to the attachments still work.

These should have been reindexed by now 🤔

**Comment by gbp** [comment]
Are the links to the attachments visible on the site or is the issue that someone might know the direct links to the attachment and they are still retrievable?

**Comment by RichardTaylor** [comment]
>Are the links to the attachments visible on the site

Not that I'm aware of. 

>someone might know the direct links

Some people do know the direct links, and more were findable via Googling. 

(There's a related WhatDoTheyKnow Slack thread started last night)

**Comment by FOIMonkey** [comment]
I have the links to the attachments, because I downloaded most of the files last night. I can access these directly and links to the html previews of the attachments also still work.

**Comment by garethrees** [comment]
> > but links to the attachments still work.
> 
> These should have been reindexed by now 🤔

I think the fix for this is

```diff
diff --git a/app/models/alaveteli_pro/embargo.rb b/app/models/alaveteli_pro/embargo.rb
index 1f1dd715b..aa955e231 100644
--- a/app/models/alaveteli_pro/embargo.rb
+++ b/app/models/alaveteli_pro/embargo.rb
@@ -171,7 +171,7 @@ def notify_expiration
     end
 
     def reindex_request
-      info_request.reindex_request_events
+      info_request.expire
     end
   end
 end
```

**Comment by RichardTaylor** [comment]
>admin links to the individual responses

I think this might need explaining further in a separate Alaveteli ticket. I've started one at:

https://github.com/mysociety/alaveteli/issues/6999
