### ISSUE TITLE
Link to more external resources for challenging refusals on /help/unhappy

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1164]
Spotted on [this video](https://www.medact.org/2020/resources/videos/making-effective-freedom-of-information-requests/) @ ~18:00:00 https://youtu.be/6_1C_tICS98?t=1085.

![Screenshot 2022-04-29 at 12 37 28](https://user-images.githubusercontent.com/282788/165937369-8ea8c98f-fd81-4783-8c97-6476fa335333.png)

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
