### ISSUE TITLE
Place login as /user/whatdotheyknow button on the admin toolbar

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1165]
I find myself going to /user/whatdotheyknow -> clicking the user admin link there > clicking the "Login as" button. 

The `Log in as WhatDoTheyKnow...` button could usefully be placed on the admin toolbar.  

The recent new feature "Button for admins to revert to their own account after logging in as a user https://github.com/mysociety/alaveteli/issues/1785 has made it easier to switch to/from the whatdotheyknow account however this tweak, which I think is a simple tweak would improve things further.

**Comment by mdeuk** [comment]
> The recent new feature "Button for admins to revert to their own account after logging in as a user #1785 has made it easier to switch to/from the whatdotheyknow account however this tweak, which I think is a simple tweak would improve things further.

Longer term, I think I'd prefer a solution such as the one described in https://github.com/mysociety/alaveteli/issues/6270#issuecomment-849046509 - but, I don't see a reason why we can't make the **current process** a bit simpler, if possible, now that we are using this account as a more 'regular' way of working.

**Comment by RichardTaylor** [comment]
> If you were to login/logout as WhatDoTheyKnow user from the nav bar, then I guess you would want to remain on the current page instead of being redirect to the public/admin user page?

Yes, I've just raised that as an issue too https://github.com/mysociety/alaveteli/issues/6998 :-)

**Comment by RichardTaylor** [comment]
> Longer term, I think I'd prefer a solution such as the one described in [mysociety/alaveteli#6270 (comment)](https://github.com/mysociety/alaveteli/issues/6270#issuecomment-849046509)

I agree. There would still be some role for a /user/whatdotheyknow user too though I suspect. (Related https://github.com/mysociety/alaveteli/issues/6997 on recognising an "official user account" in the system) 

We should probably discuss our policy on how we use the features on a different ticket.

**Comment by mdeuk** [comment]
> > Longer term, I think I'd prefer a solution such as the one described in [mysociety/alaveteli#6270 (comment)](https://github.com/mysociety/alaveteli/issues/6270#issuecomment-849046509)
> 
> I agree. There would still be some role for a /user/whatdotheyknow user too though I suspect. (Related [mysociety/alaveteli#6997](https://github.com/mysociety/alaveteli/issues/6997) on recognising an "official user account" in the system)

If I'm remembering my envisioned intent - the account would still exist, just, we wouldn't have to _manually_ login to it - with a suitably enabled admin account you'd tick a box and your annotation would post using the nominated 'site' account.

I think we're perhaps a bit away from that yet, so the proposal described here seems to be something worthy of consideration - it'll make something that is a bit of an irritant a good bit easier to use.

**Comment by HelenWDTK** [comment]
I get a sense that we've switched to using notes more, rather than annotations on the support account, so that this is less of an issue as it was. Closing as stale, but we can bring it back if needed,
