### ISSUE TITLE
Blog Post - When FOI Goes Wrong

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1167]
From myself on email:

>Could we do a blog highlighting a series of requests which either got no response at all (or no substantive response), or took a very long time (over a year) to get a response?
>
>We'd want to select substantive requests.
>
>I have one strange response of my own to offer:
>
>https://www.whatdotheyknow.com/request/nhs_england_midlands_and_east_re
>
>and recent site admin has drawn my attention to a very slow response at:
>
>https://www.whatdotheyknow.com/request/communication_with_consular_serv

The latter has become more astonishing 

>After 20 Public Interest Test extensions and close to 2 years of delay, the FCO closed this request down because the requester didn't respond to one email within 10 days. 

https://twitter.com/FOIMonkey/status/1520072529834094594

**Comment by FOIMonkey** [comment]
Noting some more bad FCDO examples (there are more):

https://www.whatdotheyknow.com/request/ico_decision_notices_challenges_12
https://www.whatdotheyknow.com/request/progress_of_uk_ais_commercial_de

Suggested title from @mdeuk on slack: "It's the PITs"

**Comment by FOIMonkey** [comment]
Another: https://www.whatdotheyknow.com/request/sporting_hospitalitysports_washi

**Comment by RichardTaylor** [comment]
Another long public interest test delay 

https://www.whatdotheyknow.com/request/liz_truss_visit_to_brazil_april

tagged pit and pit_delay and noted those tags at https://wdtkwiki.mysociety.org/wiki/Request_tags

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
