### ISSUE TITLE
Blog post on when a minister steps in to block a FOI response

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1169]
* Note where the law enables/requires ministers to take decisions in relation to the handling of FOI requests. 

* List some examples of ministerial decisions in respect of specific FOI requests on WhatDoTheyKnow.  

* Let's use the request tag `minister` for where a minister has intervened in, or taken a decision in relation to, a specific request. 

* We can search WhatDoTheyKnow for other examples. Focusing on more recent examples might be good. 

* Are there published statistics on the use of the relevant exemptions? Can we identify the departments where ministers are using their FOI request blocking powers more than others?

Example cases:

* There is a surprising refusal at:
https://www.whatdotheyknow.com/request/cif_grant_funding_bids#incoming-1742497
A minister made the decision not to release information about a school seeking funding for a fence and pavilion!

* There is a ministerial refusal at 
 https://www.whatdotheyknow.com/request/no_outsiders_6#incoming-1356600

Policy ideas:

* Should the specific minister be identified in these cases? 
* Should a copy of the signed ministerial decision be published? 
* Should the recommendation to the minister be published?

Material relating to case handling could be obtained via a "meta" FOI request.

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
