### ISSUE TITLE
Blog on using tags to track poor public body performance

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1173]
https://wdtkwiki.mysociety.org/wiki/Authority_Performance_Tags

**Comment by garethrees** [comment]
Might want to do https://github.com/mysociety/whatdotheyknow-theme/issues/1172 first as a place to link to from this.

**Comment by garethrees** [comment]
Now even more of an incentive to do so https://github.com/mysociety/whatdotheyknow-theme/issues/1172.
