### ISSUE TITLE
Blog post about the bat release

### ISSUE THREAD

**Issue by FOIMonkey** [mysociety/whatdotheyknow-theme#1174]
Recently National Highways released a massive amount of bat survey data in response to this request:

https://www.whatdotheyknow.com/request/2021_bat_surveys_for_the_arundel

All in all it is 1.23TB, consisting of just over 110,000 files, including lots of video and audio. The data still needs a permanent home.

I think this is WDTK's largest ever data release.

It shows the power of EIR in giving you access to large amounts of data. With this raw data, it would be possible to independently verify/dispute the conclusions of the authority's experts.

The requester is linked to a campaign group who are trying to stop a bypass being built west of Arundel, and has made a number of high quality requests related to this issue.

**Comment by RichardTaylor** [comment]
>The requester is linked to a campaign group who are trying to stop a bypass being built west of Arundel, and has made a number of high quality requests related to this issue.

We could ~"interview" them by email and seek a quote from them for this article and/or a case study. 

@MyfanwyNixon

**Comment by MyfanwyNixon** [comment]
Yes, that sounds like a thoroughly enjoyable topic for a post. 
But @FOIMonkey this is very much your finding, so you have first dibs on writing it up if that's something you'd like to do! OTOH if you're not so keen, Arundel isn't very far away from me, and while email would be more efficient, I could even do a face to face.

**Comment by FOIMonkey** [comment]
I'd be happy to have a go at putting something together.

**Comment by MyfanwyNixon** [comment]
@FOIMonkey might be worth you having a quick scan of the mySociety style guide [not that there is anything bat specific in there ;) ] https://docs.google.com/document/d/12RER4ToOQfzBrsc_X1JXNGTUi7vOS-1okB_VCE9sum8/edit#

**Comment by FOIMonkey** [comment]
https://www.mysociety.org/2022/05/26/thats-bats/
