### ISSUE TITLE
Blog on misuse of the service to send personal correspondence to Government departments 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1175]
* Note the problem and explain we hide such material when it has been brought to our attention. 
* Note the DVLA and Home Office are the key problems, and we suspect part of the issue is the difficulty people have getting through to these organisations directly.  
* Note our public notes and interstitial questions on the Home Office page.
* Point out how FOI and our service could be part of the solution. Information on these bodies' performance responding to contact from the public is accessible under FOI, enabling informed lobbying for improvements. 
* Perhaps note there appears to be an issue correlating people's reported experiences with those performance statistics which are available.

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
