### ISSUE TITLE
Volunteer plan - Create new volunteering specific contact form

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1179]
Linked from ticket #1038 and https://github.com/mysociety/whatdotheyknow-theme/issues/1178

Create a new contact form specifically for volunteer enquiries 

The form is based on some questions that we already ask potential new volunteers when they contact us.  This new form would allow is to have this information straight away to enable faster processing of new volunteers.

Proposed new form is can be viewed here, please add any suggestions or comment to the document
https://docs.google.com/document/d/16gDuunLfKl9f7dc3a6GvmvyG7Muq5eDoa9KMySVgDbA/edit

cc @MyfanwyNixon

**Comment by garethrees** [comment]
Also cc @gbp – need to have a bit of a think about how we'd implement this without too much theme-based custom code. Can we submit the new form to the existing controller, or do we need a whole new controller endpoint?

**Comment by sallytay** [comment]
Thank you to everyone in the team for reviewing this document.

i've now acted on the suggestions made

I
