### ISSUE TITLE
Volunteer plan - Update text for 'Membership of the Admin team'

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1180]
Linked to ticket #1038

Text needs to be updated: Membership of the admin team https://www.whatdotheyknow.com/help/how#admin_team to be consistent with the update text https://www.whatdotheyknow.com/help/volunteers.

To note ticket  #1178  will need to be completed before the text for this can be drafted

**Comment by sallytay** [comment]
Updated text proposed at: https://docs.google.com/document/d/1GY0A09Cm3ruUoABAVr85-zpefC-rOdOkOGG9MpoAdoA/edit 

Please add any comments or suggestions that you have

**Comment by sallytay** [comment]
Thank you for the suggestions and comments on this, I've now updated the draft.

If anyone has any further thoughts please let me know, if not we can get this updated.

**Comment by sallytay** [comment]
No further suggestions or comment have been made on the proposed new text.

Could we get this updated on site now

**Comment by mdeuk** [comment]
> Could we get this updated on site now

PR #1374 raised for commit b7cd7c52d1b566b1209c0fb5895558cc49d088be, awaiting review. 😃
