### ISSUE TITLE
Agree replacement for the word "extraneous" for use when we remove extraneous material from the site

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1181]
To make our service more accessible we want to use a simpler word, or phrase, than extraneous to describe material removed on the grounds it isn't a necessary part of the FOI request or subsequent correspondence. 

Ideas:

* Irrelevant
* Unnecessary (preferred as probably less pejorative than irrelevant )

If we went with "unnecessary" we'd replace material with:

[unnecessary material removed]

Subsequent actions once agreed:

* Replace references to extraneous in the help pages 
* Replace references to extraneous in the admin system - template censor rule replacements 
* Update relevant wiki pages eg. https://wdtkwiki.mysociety.org/wiki/Defamation_or_Libel_Threats

**Comment by FOIMonkey** [comment]
We should make sure that all of the language we use can be easily understood by users with lower literacy levels and by second language speakers. 

It would be good to change the existing redactions if this is technically possible. 

The CEFR level of extraneous is C2. 

Unnecessary, material and removed are all B1 words, which I think should be our maximum level.

**Comment by RichardTaylor** [comment]
>It would be good to change the existing redactions if this is technically possible.

Existing censor rule replacements could probably be safely changed, I'd be more wary about trying to find and replace text in outgoing messages which have been edited.

**Comment by garethrees** [comment]
> > It would be good to change the existing redactions if this is technically possible
>
> Existing censor rule replacements could probably be safely changed

It's technically possible but less so from a resourcing point of view. My default would be for this to be a change going forward unless someone can make an _extremely_ compelling case for spending the time on changing existing replacements. I'm sure there'll be edge cases that make this a bit trickier than a one-liner.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
