### ISSUE TITLE
Consider listing the (Welsh?) Education Consortia

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1182]
I've found these Welsh educational consortia while looking at #1010, I'm not sure whether they also exist in other areas, but we might want to consider whether we want to list them.

Consortia Addysg - Education consortia |  
-- | --
Ceir pedwar consortia Addysg ffurfiol yng Nghymru sy'n cwmpasu'r canlynol: |
Gogledd Cymru (Sir y Fflint, Conwy, Wrecsam, Gwynedd, Ynys Môn, Sir Ddinbych) | https://www.gwegogledd.cymru/
De-orllewin a Chanolbarth Cymru ( (Abertawe, Castell-nedd Port Talbot, Sir Gaerfyrddin, Sir Benfro, Powys, Ceredigion) |  
Canol De Cymru (Pen-y-bont ar Ogwr, Caerdydd, Merthyr Tudful, Rhondda Cynon Taf, Bro Morgannwg) | https://www.cscjes.org.uk/culture/cy?redirectUrl=https%3A%2F%2Fwww.cscjes.org.uk%2F
De-ddwyrain Cymru (Caerffili, Sir Fynwy, Casnewydd, Blaenau Gwent, Tor-faen) | https://sewaleseas.org.uk/cymraeg/
There are four formal Education consortia in Wales covering: |  
North Wales (Flintshire, Conwy, Wrexham, Gwynedd, Isle of Anglesey, Denbighshire) | https://www.gwegogledd.cymru/?lang=en
South West and Mid Wales (Swansea, Neath Port Talbot, Carmarthenshire, Pembrokeshire, Powys, Ceredigion) | *Not sure if this exists, Powys seems to have left it.*
Central South Wales (Bridgend, Cardiff, Merthyr Tydfil, Rhondda Cynon Taf, Vale of Glamorgan) | https://www.cscjes.org.uk/culture/en?redirectUrl=https%3A%2F%2Fwww.cscjes.org.uk%2F
South East Wales (Caerphilly, Monmouthshire, Newport, Blaenau Gwent, Torfaen) | https://sewaleseas.org.uk/

**Comment by RichardTaylor** [comment]
The first one at least appears to be a Joint Committee [of local councils] and so subject to FOI on that basis:

https://democracy.gwynedd.llyw.cymru/ieListMeetings.aspx?CommitteeId=243
https://www.legislation.gov.uk/ukpga/2000/36/schedule/1/paragraph/25

I'd list this as "GwE Joint Committee" 

Also 

https://www.cscjes.org.uk/how-we-work is run by a joint committee
It receives and responds to FOI requests
https://www.rctcbc.gov.uk/EN/Council/CouncillorsCommitteesandMeetings/Meetings/CentralSouthConsortiumJointEducationService/2021/05/27/Reports/Item13.JointCommitteeFOI2021.pdf

I'd list this as "Central South Consortium" and tag it to indicate it's a joint committee. 

These will need notes explaining what they do.

**Comment by confirmordeny** [comment]
I think we should add these.

**Comment by confirmordeny** [comment]
Added here: https://www.whatdotheyknow.com/body/gwe - where appropriate these were tagged as joint committees.
