### ISSUE TITLE
Decide if to campaign against the EIR 20 working day extension for complex/high volume requests 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1183]
The Environmental Information Regulations have a clause enabling a further 20 working day extension for complex/high volume requests https://www.legislation.gov.uk/uksi/2004/3391/regulation/7

Do we want to campaign against that? We are unsure following initial discussions at the moment as it may be the longer time to consider a request leads to more information being released. 

More time at the initial stage means it will take longer to get to appeal stages: internal review, and to the ICO and beyond. 

FOI/EIR are often used for journalistic or other time-sensitive purposes, a delay can reduce the impact/newsworthiness of information released.  

We do campaign on other timeliness issues including the lack of time limits for internal reviews and public interest tests, not campaigning on this one appears to be an anomaly. 

Are there any options for research to inform our position?  Could we find similar requests, some treated under FOI and the others under EIR where this extension was used, and compare them? Sounds tricky.  

Once decided, add to the principles page #1021

**Comment by FOIMonkey** [comment]
+1 This just happened to one of my requests and it's very annoying.
