### ISSUE TITLE
Decide if and how we want to specifically track requests for our logging data  

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1185]
Currently for our own monitoring of our service provision, to ensure compliance with legal deadlines, and for the preparation of transparency reports we track various kinds of requests for information which we receive. 

We have a "User Data Request Log" which we use for requests for user-data from those other than the data-subject, and which we are not treating as a GDPR rights based request.   A request for statistical information from our logs / analytics eg. the number of views on a specific request / document isn't typically a request user-specific data, nor is it typically a GDPR rights based request, so isn't currently logged. 

The typical circumstances in which we get a request for logging data are where a data protection breach by a public body has occurred, data has been published on our website, and the public body is seeking to assess the impact of their breach, perhaps to inform a report to the Information Commissioner, or to inform a decision on if to make such a report.   

Options:
* Expand scope of "User Data Request Log" to "Data Request Log" (Would this also cover research data requests, perhaps it does already .. is it getting too broad?)
* Add an inbox label eg. `Risk: Log data request` (To go alongside `Risk: police-request` and `Risk: User data request`)
   * An inbox label only would mean we don't have records going back more than 2 years
 
I am very wary of introducing extra bureaucracy, however we already have a  "User Data Request Log" - I suggest extending its scope, and clarifying that we don't include requests we have dealt with under GDPR. [A request by a user for information on who took an action on a request they made would be dealt with under GDPR rather than considered a user-data request I think].

**Comment by garethrees** [comment]
What benefit does tracking this add? It doesn't seem particularly core to our activities – and in most cases we reject these asks anyway – so not clear to me why what we'd get from spending the time doing this.

**Comment by mdeuk** [comment]
> What benefit does tracking this add? It doesn't seem particularly core to our activities – and in most cases we reject these asks anyway – so not clear to me why what we'd get from spending the time doing this.

I'm with Richard on this one, there is the possible risk of added bureaucracy, but:

- Logging formal requests helps us demonstrate transparent administration
- Keeping records helps us to ensure consistency in decision making, and allows for cross-referencing of repeat requests (remembering that we've had some where we get more than one request on the same topic, or those over an extended timeframe)
- Formalising our processes maintains a "professional image" and demonstrates responsible data controller practices.

> and in most cases we reject these asks anyway – so not clear to me why what we'd get from spending the time doing this.

I think we'd benefit from being able to demonstrate that. If we think of transparency reports, you can usually derive quite quickly the number of requests _accepted_, _complied with_, or _rejected_.

I think the key is how we keep things simple. We don't need to go over-the-top here, we just need something that lets us keep a record. We could probably retrofit this into the existing GDPR solution without too much work.

**Comment by RichardTaylor** [comment]
A good approach here might be to consider if we want to include this information in transparency reports, if we do then a logging system which makes it accessible would be ideal. 

I raised this as it's a gap/anomaly in our logging which I thought warranted consideration.

**Comment by RichardTaylor** [comment]
A request for personal data included in a data breach by a public body is another type of data request which we don't specifically log and would be caught by the proposal to expand the scope of the "User Data Request Log" to a "Data Request Log".

**Comment by garethrees** [comment]
I think an extra inbox label is the maximum amount of effort that's warranted here in terms of tracking.

It'll be a small enough amount to manually review the outcome (comply/reject) for each year's transparency report.

I don't think we care about individual cases after the 2 year retention policy; only the trends, which can be compiled by reviewing the transparency reports.

**Comment by HelenWDTK** [comment]
I've created `x/log data request` - let's see how we get on with that for now.
