### ISSUE TITLE
Blog on use of FOI by elected representatives

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1186]
We should base this on information available in public on the site or elsewhere online. 

Accounts to review for possible content

https://www.whatdotheyknow.com/user/michelle_vince
https://www.whatdotheyknow.com/user/tony_dixon
https://www.whatdotheyknow.com/user/arfon_jones
https://www.whatdotheyknow.com/user/billy_mcaloon
https://www.whatdotheyknow.com/user/neil_nerva
https://www.whatdotheyknow.com/user/helen_pollard_2
https://www.whatdotheyknow.com/user/ross_walker
https://www.whatdotheyknow.com/user/crocels_news
https://www.whatdotheyknow.com/user/rory_s_fiveash
https://www.whatdotheyknow.com/user/ian_lewis_2
https://www.whatdotheyknow.com/user/pwharton
https://www.whatdotheyknow.com/user/councillor_janet_thompson
https://www.whatdotheyknow.com/user/rebecca_denness
https://www.whatdotheyknow.com/user/john_cramp_2

Former councillor: 
https://www.whatdotheyknow.com/user/clive_carter

Previous blog on this subject

https://www.mysociety.org/2009/11/28/whatdotheyknow-beats-parliamentary-question/

We could also note use by members of the House of Lords. 

We should be alert to the potential for impersonation.

**Comment by ajparsons** [comment]
Mentioned a bit here: https://www.itspublicknowledge.info/foi-and-elected-representatives

And circles back to some links above but: https://research.mysociety.org/html/reforming-foi/l/6.3482.yxj7q.5ndm8.jglx8._8era.html

**Comment by WilliamWDTK** [comment]
There are also several users with MP in their username. Here are at least some of them:

- https://www.whatdotheyknow.com/user/zarah_sultana_mp
- https://www.whatdotheyknow.com/user/sharon_hodgson_mp
- https://www.whatdotheyknow.com/user/office_of_diane_abbott_mp
- https://www.whatdotheyknow.com/user/nicky_morgan_mp
- https://www.whatdotheyknow.com/user/mike_hill_mp
- https://www.whatdotheyknow.com/user/john_mcdonnell_mp
- https://www.whatdotheyknow.com/user/dr_therese_coffey_mp
- https://www.whatdotheyknow.com/user/dr_phillip_lee_mp
- https://www.whatdotheyknow.com/user/david_amess_mp

And some with MSP:

- https://www.whatdotheyknow.com/user/elaine_murray_msp
- https://www.whatdotheyknow.com/user/gordon_macdonald_msp

**Comment by confirmordeny** [comment]
What we shouldn't do is (a) state that people are who they say there are or (b) say that we think they are imposters - at least not without further discussion.

**Comment by garethrees** [comment]
Should note that they're not subject to FOI themselves.

User question:

> I found the cost of my MP's constituency staff (c£140k which seems to be the same for most MPs). I have now written to my MP 3 times asking for how these costs are apportioned, how many staff are employed and how they are appointed. He still doesn't answer my request. Is there anything else I can do eg using freedom of information request? Are MPs employing family members without an advert for the post and a full application and interview process?

@FOIMonkey's response:

> MPs are not subject to FOI, and as they employ staff themselves, the info is unlikely to be held by anyone who is.

**Comment by RichardTaylor** [comment]
>User question (summarised):

>>   I want to investigate the cost of my MP's staff. I've written to them multiple times but they don't answer. I want to understand whether they're following a fair recruitment process. Is there anything else I can do like make an FOI request?

We list the [Independent Parliamentary Standards Authority (IPSA)](https://www.whatdotheyknow.com/body/ipsa) which sets, administers and regulates MPs’ staffing and business costs, pay, and pensions. While MPs are the employers of their staff IPSA may hold some of the information sought.  IPSA also proactively publish quite a lot of information, though it can be very hard to get information out of their website.

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
