### ISSUE TITLE
Agree and document a tag for use when a public body scares requestors by mentioning fees

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1188]
We advise:

>Authorities often include standardised text in their acknowledgement messages saying they “may” charge a fee, which, understandably, can be a little frightening. Ignore such notices. They hardly ever will actually charge a fee. 

https://www.whatdotheyknow.com/help/requesting#fees

We could tag requests and bodies which scare requesters with statements about fees and charges. 

https://wdtkwiki.mysociety.org/wiki/Authority_Performance_Tags

Example:

>I also attach a copy of West Dunbartonshire Council current Freedom of Information charging regime for your information. 

https://www.whatdotheyknow.com/request/applicationssoftware_request_20#incoming-2026384

Proposal - update https://wdtkwiki.mysociety.org/wiki/Authority_Performance_Tags with:

Problem:
>Body makes statements about fees and charges which could frighten requesters

Proposed tag for requests and bodies: fee_scare

**Comment by garethrees** [comment]
`fee_scare` – great tag! +1 from me.

**Comment by RichardTaylor** [comment]
Updated: 

https://wdtkwiki.mysociety.org/wiki/Authority_Performance_Tags

Closing.
