### ISSUE TITLE
Review and improve coverage of Transport for London's subsidaries 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1192]
There are many Transport for London subsidiaries:

https://tfl.gov.uk/corporate/about-tfl/how-we-work/corporate-governance/subsidiary-companies

We list some in their own right already eg. 

https://www.whatdotheyknow.com/body/dlrhttps://www.whatdotheyknow.com/body/lbl

The feature for "Record and show relationships between bodies" https://github.com/mysociety/alaveteli/issues/4714 would help here. 

The notes on both our listings for TfL and the subsidiaries could be improved.  

We could list more subsidiaries. 

Proposal:

* https://github.com/mysociety/whatdotheyknow-theme/issues/648
* Consider adding additional subsidiaries separately.

**Comment by mdeuk** [comment]
I think we can close this one off, in favour of #648.
