### ISSUE TITLE
Blog post - Using FOI and WhatDoTheyKnow - a guide for criminals

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1193]
This could be an engaging angle for a blog to raise important points about the harms and benefits of running the service. 

Often public bodies ask us to take material down from our website on the grounds it could be misused by criminals. We try to act responsibly, but are reluctant to remove material on the basis of potential misuse by criminals when there are benefits which arise from us continuing to publish the material. 

We could quote from [a judgment](https://www.judiciary.uk/wp-content/uploads/2021/07/Various-Claimants-v-IPSA-judgment.pdf):
>As a democracy, we put our faith and confidence in our belief that people will abide by the law. We deal with those who do not, not by cowering in the shadows, but by taking action against them as and when required.

We shouldn't have to think of, and try to eliminate, every possible way, criminals might misuse information. It is reasonable to assume we live in a law abiding society, and the deterrence, and if necessary punitive, aspects of the justice system will perform their roles.  

Examples:
* [How to steal a tube train](https://www.mysociety.org/2017/02/23/could-you-join-the-whatdotheyknow-team/)
* WhatDoTheyKnow provides a huge number of letterheads for public bodies, many of which are in easily editable form, easy for fraudsters to misuse. 
  * There are some special cases of this which we could get into. 
* Empty property data
* Use data released to avoid paying road tolls. (Do we want to go public on this - one for some discussion). 

We could explain our approach to running our service in a responsible manner, and note that where our service is used directly for criminality eg. harassment we do, if a court order is provided, release user data to aid investigations.  We could note most issues of this nature we encounter are not as a result of running a FOI service, but just a result of running a service publishing user-generated content. 

This could be one of the shorter alternatives to a large post on harms vs benefits #1082 

Related:  Blog Post - How we process requests for user data #1077

**Comment by RichardTaylor** [comment]
Someone asked a council for a copy of their penalty charge notice envelope. They released it, but in black and white and with "sample" written over it. Presumably they realised the potential for easy misuse and sought to frustrate that:

https://www.whatdotheyknow.com/request/578938/response/1387494/attach/3/Penalty%20Charge%20Notice%20Sample.pdf

**Comment by confirmordeny** [comment]
I think it would be very unlikely that mySociety would publish something like this. There would be reputational risk. In addition, charities have a duty of care towards people they interact with. I am not a lawyer and this is not therefore legal advice but there are some criminal offences where helping/encouraging the criminal is also an offences (e.g. conspiracy charges, incitement etc).  I am going to close it.
