### ISSUE TITLE
Volunteer Plan - Blog Idea - Current Projects blog

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1194]
To enable us to better promote projects where we need to seek help from people as we have done in the recently with finding the email addresses of BIDs

A suggestion is that we could agree as team three key projects each quarter and the details of these along with the links to any spreadsheets or other resources could be added to a blog, which is then posted on the mySociety and WhatDoTheyKnow blog pages.

The projects could be from existing GitHub tickets or from suggestions from the team, perhaps something for the Community and Activism meeting?

This would mean that it would be potentially seen by more people. In addition we can tweet a link to the blog, add to a banner and also link to it directly from the  volunteer webpage.

**Comment by garethrees** [comment]
FWIW I wouldn't commit to any particular rhythm _publicly_ – we don't know if it will work, we don't know if we'll stick to it, we don't know if we'll have capacity to do it quarterly, even if we do think it's a good idea, and it doesn't account for unforeseen situations that we need to deal with.

In practical terms, all I'm really saying is rather than titling it something like "Quarterly Project Update", its more like "WDTK Projects June 2022". That way we give ourselves a bit of flexibility over the next update – could be July 2022; could be December 2022. "Quarterly" should be our internal _aim_ rather than public _commitment_.

**Comment by sallytay** [comment]
Ideas noted from the Community Activism Meeting.

Noted that this is the start of he non-core admin community - the idea of the 'project' included are a first step into helping us

Ideas for first blog:
Encourage people to classify requests.

We could seek meta-data eg. if there is a list of parish councils, if there are email addresses, if the data is a PDF, if there’s a CSV etc.  - If we have any lists already where we are missing some data we could ask people to search these for us, perhaps by area?

Ideas for the development of this in the further

Can we use projects ourselves? and use this to get people involved

It would be good to use maps to track progress on eg. pharmacies. 

@Foimonkey  has a spreadsheet of areas where we have parish council coverage, could make a map from that and include it in a blog. 

How could we provide community/feedback/gamify/leaderboard.

**Comment by garethrees** [comment]
One of the key current projects is campaigning on the poor authority performance (i.e. https://github.com/mysociety/whatdotheyknow-theme/issues/1173).

I think this should be limited to 3 "projects" (time-bound things we're actively working on) and 3 evergreen activities (things that will always need doing – classifying, delivery errors, body updates, etc).

**Comment by sallytay** [comment]
Update:

Although we did not use this idea it could still be part of how we recruit volunteers in the future.

Points to consider:
>Good content ideas but some require some technical work that we don't have resources to do at this time
>We have had success with the use of the email banner and blog on helping us to find missing email addresses, perhaps this is a better way forward.

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
