### ISSUE TITLE
Formulate a policy/help page on the re-use/citation of released information

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1195]
We have recently received an email from an academic in the support inbox about quoting material released in response to a request in a chapter of a book:

> I just wanted to check and make sure that the material published on your site is available via the Fair Use policy; if someone could get back to me and let me know, that would be much appreciated. I am also, in case it's of need or interest, happy to send a copy of the chapter to you in its draft form.

@sallytay said:

> As we are happy for material on site to be used by others I think we should support this, we can ask them to credit us perhaps and take them up on the offer to see the finished chapter.

@RichardTaylor pointed out:

> We don’t own any rights in the information released, so we can’t grant permission for reuse. 
>
>We also don’t want to get into giving legal advice on reuse. 
>
>We could make clear that we have no objection to, and indeed encourage, use of material we are publishing and encourage citing the WDTK page as a source. 
>
>I see there is already a citation mentioned in the correspondence, we could add that as a citation in the system, and also add this paper when it’s published. 
>
>I can’t; from a quick look; see that we already have a help page on reuse - we should have one.

Hence, this ticket.

The copyright will presumably rest with the authority, and I'd assume this would come under the [Re-use of Public Sector Information Regulations](https://ico.org.uk/for-organisations/guide-to-rpsi/what-is-rpsi/), and I'd imagine an academic would be able to get advice on such things internally to their institution.

We could provide basic advice on re-use, and mention the RPSI regulations.  We could even implement a process for requesting re-use for users other than the original requester.

See also:

- mysociety/alaveteli#1823
- #1144

**Comment by WilliamWDTK** [comment]
[https://ico.org.uk/for-organisations/guide-to-rpsi/obligations/](https://ico.org.uk/for-organisations/guide-to-rpsi/obligations/):

> People who want to make a request for re-use must submit the request in writing, with their name and address for correspondence, and specify the information they want to re-use and the purpose they intend to use it for.
> 
> If you make your information available under [the Open Government Licence](http://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/uk-government-licensing-framework/open-government-licence/) (OGL) no request has to be made, but re-users must follow the terms of the OGL. 
> 
> When you receive a request to re-use information you must respond within 20 working days. You can extend this time if the information is extensive or the request raises complex issues, but you must inform the requester of this within the 20 day period.
> 
> You must permit re-use in response to a request, unless you are a library, museum or archive, in which case you can decide whether to permit re-use. Remember that RPSI does not apply to information that would be exempt from disclosure under information access legislation, and so you do not have to permit re-use of exempt information.
> 
> If you have not previously disclosed the information requested, then you should also deal with this as an access request under the appropriate legislation eg FOIA, EIR, the Freedom of Information (Scotland) Act or the Environmental Information (Scotland) Regulations in order to decide whether the information is exempt. This will be the first stage of dealing with the request and you must go on to deal with the re-use request.  
> 
> You must make the information for re-use available in the format and language in which you hold it. If you don’t already hold it in an open and machine readable format with metadata, but it’s possible and appropriate to make it available in this way, then you should do so. ‘Machine readable’ means that the information is structured so that software can extract specific elements of the data.

**Comment by WilliamWDTK** [comment]
See, for example, [this response](https://www.whatdotheyknow.com/request/fire_alarm_maintenance_5#incoming-2035675):

> The Public Sector Information Regulations provide a framework for public
> sector organisations to licence the re-use of their information.  Please
> request a re-use licence in order to re-use the information. Without the
> necessary permission, you can breach our copyright.
> 
>  
> 
> Brief extracts of any material may be reproduced without our permission,
> under the “fair dealing” provisions of the Copyright, Designs and Patents
> Act 1988 for the purposes of research for non-commercial purposes; private
> study; criticism; review and news reporting. All are subject to an
> acknowledgement of ourselves as the copyright owner.  For guidance notes
> on a range of copyright issues, see the Office of Public Sector
> Information web site.

It seems the Office of Public Sector Information has been part of the National Archives since 2006, and [information about Public Sector Information](https://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/about-psi/) is available on the NAs' website.

**Comment by garethrees** [comment]
We do have https://www.whatdotheyknow.com/help/officers#copyright, linked to from the sidebar on the request page, which also links to https://www.whatdotheyknow.com/help/how#copyright.

We also have https://www.whatdotheyknow.com/help/requesting#reuse

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
