### ISSUE TITLE
Work through requests in an error state

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1196]
We could work through those requests on the [admin summary](https://www.whatdotheyknow.com/admin) with an `error_message` state, attempting to resolve delivery errors or otherwise update bodies (perhaps by marking them as defunct as necessary).  There may be some where the issue has been resolved, and we just need to reset the state.

At the present time, there are 195:

![image](https://user-images.githubusercontent.com/99501342/168444375-17806e9d-0947-4062-a918-aaeb90853329.png)

Once done, we could perhaps change the processing of identified delivery errors to marking those which come in the alerts in the inbox as `error_message`, archiving the inbox thread and dealing with it through Alavateli. (Possible suggestion for #1103).

**Comment by garethrees** [comment]
Thanks for ticketing, but I'm going to close this as the "work" is already represented in Alaveteli itself. I don't think we need to track that in two places.

It does seem like there's a policy proposal here of changing the way we handle delivery errors, but that seems better placed in https://github.com/mysociety/whatdotheyknow-theme/issues/1103?

Happy to reopen if I've misunderstood.

**Comment by WilliamWDTK** [comment]
No, that seems appropriate.  I'll add a comment to #1103
