### ISSUE TITLE
Update privacy page regarding retention of and access to IP addresses for sign-ins

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1203]
After [I noticed and mentioned](https://mysociety.slack.com/archives/CNH83HJP4/p1653423739276479) the [addition of user sign-in IP addresses to the admin interface](https://github.com/mysociety/alaveteli/pull/6822), @FOIMonkey notes that our privacy policy needs updating to reflect this, especially since this information is now visible by admins.

**Comment by FOIMonkey** [comment]
The current privacy policy currently says that a user's IP "will not normally be seen by anyone". I'm not sure that's true anymore.

**Comment by WilliamWDTK** [comment]
> I'm not sure that's true anymore.

Indeed, I happened across the feature when I was dealing with a problem that didn't require that information.

**Comment by WilliamWDTK** [comment]
This is something that could additionally be mentioned in small text on the sign-in page, akin to how it's done for emails and names etc on sign-**up**:

![](https://user-images.githubusercontent.com/99501342/170134482-b250c80e-bca1-4c78-881e-a7a72ca710b1.png)

See also: #980

**Comment by mdeuk** [comment]
Slightly contentious, I'm tagging this as a _bug_ - it ought to be properly mentioned in the privacy notice, but it isn't. We should fix that as soon as practicable.

**Comment by FOIMonkey** [comment]
+1 I've escalated this to review. 

The current [policy](https://www.whatdotheyknow.com/help/privacy) talks about what information we collect when a user makes a request, but needs to be much clearer about what information we collect when you log in to the site, as well as the fact that this is now much more visible.

**Comment by garethrees** [comment]
I've disabled this and purged any recordings.

**Comment by garethrees** [comment]
Just to note I've written up a small "[report](https://groups.google.com/a/mysociety.org/g/wdtk-review/c/iL4685wVfzA/m/lioga3A0AQAJ)" on this for wider awareness. Discussion should continue here though.

**Comment by garethrees** [comment]
I think this is fixed by https://github.com/mysociety/alaveteli/pull/7592.

**Comment by WilliamWDTK** [comment]
While we can now say that "in normal circumstances, this data is infrequently accessed by a human", it is more frequent/easily available than before, but this may not require any wording changes. However, is it the case that we "are likely to be assessing it in bulk, in order to understand an issue with the site, rather than at a granular level of individual users"?

**Comment by garethrees** [comment]
> While we can now say that "in normal circumstances, this data is infrequently accessed by a human", it is more frequent/easily available than before, but this may not require any wording changes.

More easily available yes, but not more frequent in normal circumstances.

> However, is it the case that we "are likely to be assessing it in bulk, in order to understand an issue with the site, rather than at a granular level of individual users"?

The policy says "likely" at a bulk level, which to me doesn't preclude looking at specific individuals (or set thereof) when investigating service misuse.

**Comment by RichardTaylor** [comment]
I think pulling IP addresses into the web-application is sufficiently different to holding web-server logs to warrant a note, although technically it doesn't enable anything new and just makes data we were already holding easier for us to access and work with. 


```diff
Our own logging
In addition to the information you give us about yourself in order to use the site 
(e.g. your name and email address), we collect and log some additional information in order 
to analyse and fix problems with the site
+, as well as to tackle misuse of our service
.

+As of [date] we have been recording IP addresses used to sign-in to WhatDoTheyKnow within our web-system.
+WhatDoTheyKnow administrators can view IP addresses used to sign into a specific account, and view 
+ the accounts which have been signed in to from a particular IP address. 

Our webserver logs maintain a history of page requests. This includes information about requests,
including the client IP address, data submitted (which might include your email address when you 
log on to the site), request date and time, page requested, browser version and referrer. 

-We routinely keep this information for 60 days. 
+We routinely delete both our web-server logs, and the IP addresses recorded on sign-in, 
+from our systems after 60 days. 
+This period may be extended in-light of actual, or impending, requests for user-data. 

Note that in normal circumstances, this data is 
infrequently accessed by a human, and when it is, they are likely to be 
+either
assessing it in bulk, in order to understand an issue with the site
- , rather than at a granular level of individual users.
+ or investigating misuse connected to a specific user or IP address.



```

I can see misuse could be considered to come under "problems with the site", but it would be good to be clear. 

Related:

* https://github.com/mysociety/whatdotheyknow-theme/issues/987#issuecomment-1442237719
