### ISSUE TITLE
Destroy all of the WhatDoTheyKnow admin account's tracks

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1205]
Destroy all of the (presumably accidentally added) tracks on the [WhatDoTheyKnow](https://www.whatdotheyknow.com/user/whatdotheyknow) admin account ([User 201388](https://www.whatdotheyknow.com/admin/users/201388)).

It might be good to do it automatically, since they cannot be bulk-destroyed from the admin page, and the page takes ages to reload on submission.

I destroyed about three manually before I got bored, there are about 90-100 left.

**Comment by FOIMonkey** [comment]
I looked this morning and these have now all been deleted.

**Comment by MattK1234** [comment]
Yeah, sorry, that was me last night... but I forgot to update this ticket and close the log.
