### ISSUE TITLE
Update interesting things that we know because of WhatDoTheyKnow

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1207]
Update section on interesting requests made on WhatDoTheKnow
https://www.whatdotheyknow.com/help/about#useful

Old link to a Guardian article:
https://www.theguardian.com/news/datablog/2012/mar/20/freedom-of-information-foi

Previous list https://docs.google.com/document/d/18WOOv629oAhFrqeneTjAcclN9R86TAOGav_KJ2V0WX4/edit#

I've set up a very basic blank spreadsheet at https://docs.google.com/spreadsheets/d/1xC6tAa6--0x26NnrP4LzVJMg8SlAUorVjSyoYCfDfWw/edit#gid=0

We could use this for tasks for new volunteers or as something to add to the current projects blog https://github.com/mysociety/whatdotheyknow-theme/issues/1194

We can also add everything that has been noted on the WDTK slack channel recently

**Comment by garethrees** [comment]
What value does a tracking sheet add? Can we just tweet them directly?

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
