### ISSUE TITLE
Encourage due-skepticism in relation to correspondence from public bodies to the team

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1212]
A number of recent issues could have been dealt with better with a bit more due scepticism over claims made by public bodies. 

We often get takedown requests or other correspondence from public bodies. 

Often these are very strongly worded and intimidatory, and they often misrepresent the legal situation, or take a one-sided view. 

It can be difficult, or surprising, for new administrators who have perhaps been used to being very deferential to public bodies, and especially the police and courts, to question, and if appropriate challenge, what we are asked to do. 

One step we could take is adding an item to the "Things to advise not to do" section of the induction call:

https://wdtkwiki.mysociety.org/wiki/Agenda_For_Induction_Call#Things_to_advise_not_to_do.21

* Don't take claims made by public bodies at face value. If they say we must do something, question it.  (Examples we've had: bodies demanding we remove them from the site as they [wrongly] claim not to be subject to FOI; bodies insisting we must, by law, remove material, on spurious grounds].

**Comment by RichardTaylor** [comment]
I've made the proposed induction call agenda update. 

We could do more.

**Comment by garethrees** [comment]
Calling this closed
