### ISSUE TITLE
Give institutional gmail accounts to volunteers

### ISSUE THREAD

**Issue by FOIMonkey** [mysociety/whatdotheyknow-theme#1213]
Having to all be logged in on the WDTK support account creates barriers to working collaboratively, particularly when it comes to the joint drafting of documents.

Currently we have @whatdotheyknow.com email addresses, but as email can't be sent from these using mail servers with a wdtk domain, messages sent using these addresses are often wrongly flagged as being spam. 

These issues would be resolved by having access to institutional gmail accounts.

**Comment by mdeuk** [comment]
> Having to all be logged in on the WDTK support account creates barriers to working collaboratively, particularly when it comes to the joint drafting of documents.

+1 - when working through documents it becomes difficult to see who is doing what, and you lose the ability to assign tasks to individuals - which can be incredibly useful. It also creates barriers when working with GDPR tracker, owing to the fact that edits show as being made generically.

> Currently we have @whatdotheyknow.com email addresses, but as email can't be sent from these using mail servers with a wdtk domain, messages sent using these addresses are often wrongly flagged as being spam.

A workaround to this part is to use the mySociety SMTP server - but it isn't perfect. It also still requires a volunteer to use their own Google account (whether paid for or part of the free Gmail product), which means we lose out on the ability to use certain functionality within Google Workspace that might be helpful to us.

Linking to #1028.

**Comment by FOIMonkey** [comment]
+1 As we share one account, if a pro-admin needs to create docs on the drive in ref. to embargoed requests, these would be accessible to non-pro admins.

**Comment by FOIMonkey** [comment]
Individual accounts would also make it easier to step away from incoming WhatDoTheyKnow mail if an admin needs/wants to take a break. Currently the mail comes into my personal inbox from multiple sources in many different ways. During times of stress/distress, it may not be easy to construct the mail rules needed to make these quickly go away. Having a proper account would mean that volunteers could just chose not to log in to it.

**Comment by garethrees** [comment]
> make it easier to step away

A recent improvement that may not be obvious is that the main lists – [volunteers](https://groups.google.com/a/mysociety.org/g/wdtk-volunteers) and [review](https://groups.google.com/a/mysociety.org/g/wdtk-review) – are google groups, so you can quickly change your subscription from "all mail" to "digest" or "none" under "My membership settings" in the sidebar.

**Comment by FOIMonkey** [comment]
Individual accounts would prevent the issue of unsigned comments being left in documents. These make it harder to know how many people's viewpoints you are trying to work into a document, and reduce transparency of internal decision making. If we had our own accounts, we wouldn't need to remember to sign stuff.

**Comment by mdeuk** [comment]
> Individual accounts would prevent the issue of unsigned comments being left in documents.

Unsurprisingly, I agree with you @FOIMonkey - it also means we can't rely on central authentication in some of our tools (e.g. the Tracker), which necessitates some clunky workarounds.

There _**is**_ an advantage to having the team account [^1], but there is an even bigger advantage to also having individual mailboxes - from a records management and well-being perspective.

[^1]:  for one, I wouldn't wish to handle the support mail in a group, as we'd lose functionality. I'd also not want to use delegation, because this also causes a loss of functionality (as Gmail currently won't allow addons to be used).

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
