### ISSUE TITLE
Blog post on ICO decision notice relating to Independent Office of Police Conduct referrals

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1215]
https://ico.org.uk/media/action-weve-taken/decision-notices/2022/4020402/ic-130218-s2s8.pdf

It is a strange case because the public body claim to have "further redacted" material they had already released to the requester while engaging with the Information Commissioner's decision making process.

The decision notice states:

>The IOPC have confirmed all details in Section F of the referral form
relate to information connected to the criminal investigation and fall
within criminal offence data. 
...
>

Section F of the form requests a "Description of the Complaint, Recordable Conduct Matter or Incident" 
 

It's not clear from the decision notice if the Information Commissioner agreed with the IOPC on this point, but the IOPC position taken in this case is applied to other cases this could prevent the disclosure of information relating to referrals of cases to the Independent Office of Police Conduct by police forces. 

There are a number of other factors which make this case potentially blog/news worthy. 

A search for the decision notice link will bring up the review group thread.

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
