### ISSUE TITLE
Blog post on examples of FOI leading to proactive publication

### ISSUE THREAD

**Issue by ajparsons** [mysociety/whatdotheyknow-theme#1216]
I have a few examples of where FOI has led to more proactive publication:

* MPs Expenses (foi rather than wdtk)
* LNER using us as a platform

Do we have any other good examples of where requests through the site have led to authorities proactively publishing information in advance rather than waiting for a request?

**Comment by RichardTaylor** [comment]
Also note that the dataset provisions of FOI  - as I understand them - require a FOI request to trigger ongoing proactive publication of an up-to-date version of the dataset - if that's reasonable.  This is a powerful law which we would ideally be promoting. 

Related:

* https://github.com/mysociety/whatdotheyknow-theme/issues/1044
* https://github.com/mysociety/whatdotheyknow-theme/issues/1032

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
