### ISSUE TITLE
Add help page section on rate cap removal

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1217]
A starting point could be the message shown to users who hit the rate cap

https://github.com/mysociety/alaveteli/blob/a27a28ef18e8c23f2757272d0629ec0c2f705799/app/views/user/rate_limited.html.erb

The reason for this is we want to remove restrictions on those making good use of the service, we want to encourage and enable requests to be made in public via the service. 

Related:
* https://github.com/mysociety/alaveteli/issues/7083
* https://github.com/mysociety/alaveteli/issues/6789

**Comment by garethrees** [comment]
What do we want to say? Could it just be integrated into the page itself?

**Comment by HelenWDTK** [comment]
I think this is better dealt with by changing the text when you hit the limit itself.
