### ISSUE TITLE
Wiki page on "Reporting to the ICO"

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1218]
I'm currently processing threads on the review group and I've hit one which suggests we should report a data breach made by an authority to the ICO.

As this is a relatively common action, I'd expect to be able to find a wiki page that just tells me how to do this.

We have a page relating to [handling a personal data breach](https://wdtkwiki.mysociety.org/wiki/Guidelines_for_handling_a_personal_data_breach), but that contains lots of unnecessary context around the early stages of identification and evaluating seriousness, etc.

What I want to do is search "Report to ICO" and land on a page that tells me:

* Why I might want to do this (a backlink to [handling a personal data breach](https://wdtkwiki.mysociety.org/wiki/Guidelines_for_handling_a_personal_data_breach))
* What the steps are
* What canned responses and/or templates I can use
* What I should do after I've done it (usually, indicate when we should destroy our copy)

**Comment by RichardTaylor** [comment]
I've started a wiki section on the [handling a personal data breach](https://wdtkwiki.mysociety.org/wiki/Guidelines_for_handling_a_personal_data_breach) page:  [How do we report to the ICO](https://wdtkwiki.mysociety.org/wiki/Guidelines_for_handling_a_personal_data_breach#How_do_we_report_to_the_ICO.3F)

including links to the templates/canned response. 

The Google Docs templates omitted key elements of the canned response, I have made suggestions to move a number of paragraphs over into them. 

> What I should do after I've done it (usually, indicate when we should destroy our copy). 

I've addressed this by a further note under [Guidelines for handling a personal data breach > A data breach by an authority](https://wdtkwiki.mysociety.org/wiki/Guidelines_for_handling_a_personal_data_breach#A_data_breach_by_an_authority)

**Comment by RichardTaylor** [comment]
There is a section in the [volunteer recruitment plan](https://github.com/mysociety/whatdotheyknow-theme/issues/1038#issuecomment-1095051201) on Wiki Updates, however it looks like it might be quite limited and wouldn't cover this:

>Main support inbox page, induction call page/recruitment to the admin page, new page for 'Classifying plus' role.

**Comment by garethrees** [comment]
Thanks; good start! Will open new issues for any further improvements.
