### ISSUE TITLE
Document the magic which makes the GDPR tracking spreadsheet and associated alerts and other features work

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1220]
I've made a start, by explaining how to find where the magic bits are kept at:

https://wdtkwiki.mysociety.org/wiki/Tracking_Sheet_Scripts

**Comment by RichardTaylor** [comment]
Reopening as this is about ~code, and https://github.com/mysociety/whatdotheyknow-private/issues/79 is about how to use the system.

**Comment by mdeuk** [comment]
> Reopening as this is about ~code, and [mysociety/whatdotheyknow-private#79](https://github.com/mysociety/whatdotheyknow-private/issues/79) is about how to use the system.

No, we don’t need two tickets for this - documentation for usability also concerns the codebase.

Given that we already have a ticket, in the correct place, which can be used for both, I’m re-closing the ticket here.
