### ISSUE TITLE
Develop an updated policy (on the internal wiki) about requests for records of deceased people

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1221]
This can probably be done in conjunction with #774 / #1050.

See:
- #774
- #779
- #1050

**Comment by WilliamWDTK** [comment]
The only mention is [here](https://wdtkwiki.mysociety.org/wiki/Personal_Data_in_General), and that's marked as out of date.

**Comment by RichardTaylor** [comment]
We have a policy of as far as possible setting out our policies in public.  If something's covered on the public help pages we don't need to repeat it on the private wiki. 

Line 2 of the Wiki main page states:

>As far as possible the site's policies are made public via help pages such as: [How we run WhatDoTheyKnow](https://www.whatdotheyknow.com/help/how).

Hopefully following #774 our public help pages are reasonably good on this subject. Is there something specific you want to add? Can we do it in public?

In terms of the Wiki pointers to relevant bits of the public policy help pages from relevant pages on the wiki might be useful in some cases, but I think effort is probably best directed to the public help pages, where more people benefit from it.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
