### ISSUE TITLE
Blog post on useful template phrases

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1223]
We've collected a nice number of snippets that could be helpful to our users _now_, before they're implemented in some kind of snippet library within Alaveteli (https://github.com/mysociety/alaveteli/issues/6164).

[#6164](https://github.com/mysociety/alaveteli/issues/6164) suggests a help page, but a quicker option would be to publish in a blog post, with the aim of treating that as a first draft of the help page content.

**Comment by FOIMonkey** [comment]
+1 I like this idea a lot, and it might help to reduce the number of users adding the unnecessary Heather Brooke wording to requests - "I am writing to make an open government request for all the information to which I am entitled under the Freedom of Information Act 2000".

**Comment by FOIMonkey** [comment]
We could also add something to this about how to turn question into a valid request for info. @confirmordeny wrote something on this once that we could improve on:
![2022-06-13](https://user-images.githubusercontent.com/11962965/173343636-ef258b05-e185-486a-bf66-d41164df259d.png)

**Comment by garethrees** [comment]
> how to turn question into a valid request for info

Oh, yes, this would be great!

**Comment by RichardTaylor** [comment]
I prefer a help page because it keeps users on the site, also any incoming links to the advice would come to WhatDoTheyKnow.

**Comment by garethrees** [comment]
> I prefer a help page because
Yeah, I get that

**Comment by garethrees** [comment]
> I prefer a help page because…

Yeah, I get that, but a blog post is easier to get from idea to published. A help page becomes easier when there's existing content, so a blog post is a way of getting there. It's a tradeoff of getting something _good_ now vs _best_ later (perhaps much later).

**Comment by FOIMonkey** [comment]
See this response where the police pointed to our blog rather than our help pages: https://www.whatdotheyknow.com/request/voi_and_other_2_wheel_scooters#incoming-1806964

A blog is a good start.

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
