### ISSUE TITLE
Agree and document a process for keeing the Legitimate interests snippets library up-to-date

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1228]
Options:

* Suggest additions/edits are made after sending a response including a legitimate interests balance test if factors not in the library were used and it appears they might be relevant again. 
* Have a regular admin task, once a month say, to make updates

Perhaps a mix of those two would be ideal.

**Comment by HelenWDTK** [comment]
Keeping this up to date and adding is part of my role, along with adding/updating templates etc.
