### ISSUE TITLE
Review use of legitimate interests snippets library

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1229]
The library was created on 21 April 2022. 

Maybe after about 6 months, so in early 2023, review if this is useful. 

Questions for the review:

* Is it being kept up-to-date?
* Is it being used? 
* Who is it being used by? (New admins / long-standing admins / volunteer admins / paid admins / all admins / wider mySociety staff etc.)
* Are the benefits outweighing the costs of having and maintaining the library 
* We have an LIT snippets library, do we want to expand it to cover other balance tests' factors eg. necessity and human rights? [This may have naturally happened]

The resolution of this ticket in six-months time might be a simple closure on the grounds: "Yes, all is clearly fine, this has become part of our routine processes and its obviously working exactly as intended. The library has made it easier for new admins, existing admins, and wider mySociety staff, to respond to rights based requests relating to the processing of personal information on WDTK. "

**Comment by RichardTaylor** [comment]
There have been a handful of tweaks since it was created. We've neither completely abandoned it, but nor are we routinely updating it every time we create potentially reusable material. Here's the summary of the latest edit history as of 31 October:

<img width="309" alt="Screenshot 2022-10-31 at 12 37 16" src="https://user-images.githubusercontent.com/547695/199032021-cfa2466a-5248-4f8b-8d9b-78f4eaf6b45a.png">

Determining how much it's being used is harder to do, usage depends on individuals' practices, we don't know if content comes from previous similar requests or the library

**Comment by sallytay** [comment]
To quickly answer a couple of the questions:

>Is it being kept up-to-date?

Probably not as much as could be - my initial thoughts were that it would be a document that anyone in the team could update as they found more snippets that would be useful, perhaps we need to set that out better to encourage more updates.

>Is it being used?

I can only speak for myself, but I use ut

>Are the benefits outweighing the costs of having and maintaining the library

I think it is a good resource to have and contains a lot of useful information, so I don't think we should maintain it, but perhaps we need to look at how we can do this better

**Comment by WilliamWDTK** [comment]
I used it when I was preparing a response recently.

It might be worth trying to keep adding things to it, but it is just another thing to do.

**Comment by HelenWDTK** [comment]
The library is now routinely used by admins when responding to rights based requests relating to the processing of personal information on WDTK. Some of the wording in favour of publication is now part of the the blank templates used to generate responses. It can always be further added to and improved, but it would be unrealistic to think it would ever cover every scenario in every case that we might look at.
