### ISSUE TITLE
Canned response for refusing a takedown request

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1230]
We often get takedown requests where we're not obliged to act (i.e. not a GDPR Rights based request).

I think we should have a short, generic "thanks, but no" response for these situations. It should include some of the info on legitimate interests (which although is for GDPR, is useful for explaining how we approach these) and escalation routes (probably only a court order in these cases).

**Comment by garethrees** [comment]
Attempting to draft this in reply to a specific case (i.e. writing the template I wish I had) in [a doc](https://docs.google.com/document/d/1tViVtcQ3u3jTylis3jEOlmy7sGkUwTmpwHSJOKhHX2g/edit).

**Comment by RichardTaylor** [comment]
We have principles of 

* seeking to run the service responsibly 
* running the service in an open and transparent manner

Often takedown requests which we are not legally obliged to consider still prompt careful consideration by us.  We consider the harms vs benefits of continued publication in quite some depth. We have, for example, dealt with claims that material we are publishing is:

* harmful to public health
* of assistance to terrorists 
* of assistance to [other] criminals - fraudsters, thieves etc. 
* damaging the ability of the land registry to make money by selling data 
* promoting hate/division

> I think we should have a short, generic "thanks, but no" response 

While we are often not obligated to explain our position in detail to those raising an issue, we often do. 

Sometimes we add an annotation to the relevant thread, or even blog and tweet about the issue. Sometimes that's not appropriate.  

>We often get takedown requests where we're not obliged to act (i.e. not a GDPR Rights based request).

There many types of takedown requests which are not GDPR rights based requests where we do act to seek to reduce legal risk to mySociety, eg. reports of defamation, breach of confidence, breach of copyright or other intellectual property rights etc.  We don't just say "thanks but no" in these cases we make a genuine effort to understand and respond to concerns raised. 

If an issue could lead to legal action, not engaging with it substantively at an early stage could put us in a weak position.

**Comment by garethrees** [comment]
Don't disagree with any of the above, but we need to make these types of issue quicker to deal with.

**Comment by RichardTaylor** [comment]
>a short, generic "thanks, but no" response for these situations.

This doesn't meet our usual standard of correspondence and engagement with those raising legitimate concerns in a considered way. This isn't our usual tone. 

Not explaining our reasons risks our reputation.

**Comment by HelenWDTK** [comment]
Template added to the monster. Issue closed as complete.
