### ISSUE TITLE
Blog on poor FOI response performance from Department for International Trade

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1232]
Latest Government FOI stats show the Department for International Trade was late responding to 55% (71/129 ) of requests taken into account for January to March 2022. 

The FOI performance of this department has been dropping over recent quarters. 

https://www.gov.uk/government/statistics/freedom-of-information-statistics-january-to-march-2022

We can add colour to these statistics by citing overdue requests made via WDTK

https://www.whatdotheyknow.com/body/dit/awaiting?#results

**Comment by RichardTaylor** [comment]
If we publish this blog, link to it via a reply to 

https://twitter.com/rosenbaum6/status/1536995000252305409

**Comment by RichardTaylor** [comment]
If we made FOI requests we could make a FOI request for any report to relevant ministers on FOI performance, and any response.

If we did more traditional journalism we could contact the department for a comment, or better, seek a comment from the relevant minister.

**Comment by mdeuk** [comment]
> If we did more traditional journalism we could contact the department for a comment, or better, seek a comment from the relevant minister.

@MyfanwyNixon what do you think here? IMO, affording a ‘right of reply’ seems a decent thing to do… even if it is a Sir Humphrey bluster!

**Comment by MyfanwyNixon** [comment]
Yes, I'd regard it as just going the extra mile - no harm in it and might result in more balanced piece if they do respond. Obvious downside is that it delays publication if you're hoping to jump on the story while it's still a hot potato.

If Pauline, mySociety's policy person, were here (currently off sick), I'd suggest co-ordinating with her to see if it were something we'd want to wrap into her work. Not sure if @ajparsons has a view, given previous research/mini sites covering poor performance of government depts.

**Comment by ajparsons** [comment]
Getting our minisite back up to date is something I hope to be able to pass onto a new hire at some point in the next few months. 

There is a broader question of what the most effective approach is for us to raise awareness of poor performance, but then do we have resources to do that more effective thing, etc.

**Comment by garethrees** [comment]
The Department for International Trade (DIT) has broken #FOI laws more often than it has followed them, new figures have revealed.” https://twitter.com/GeorgeGreenwood/status/1538797759754559488

**Comment by HelenWDTK** [comment]
I think, after a year, that the time to do this has passed.
