### ISSUE TITLE
Show more clearly the links between layers of regional/local government in Wales

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1234]
Following the listing of Welsh "Corporate Joint Committees”:

 https://www.whatdotheyknow.com/body/list/cjc

we could:

* Add links our pages on relevant local higher tier councils in Wales to the Corporate Joint Committees.
* Link from the Corporate Joint Committee pages to the relevant local higher tier councils and National Park pages. (This is just linkifying existing notes)
* Similarly add links to show other relationships between councils and bodies made up of councils in Wales eg. City Deal organisations. 

We could seek to do this in a structured way this by adding tags such as 

`member_of:north_wales_corporate_joint_committee`

to each relevant council and national park, enabling us to then provide a tag search link to the members' list from the committee page.  (Technically there's a confusing factor - legally the members appear to be the human representatives of the bodies not the bodies themselves - I suggest ignoring that). 

For the more general ticket on showing relationships between bodies see: https://github.com/mysociety/alaveteli/issues/4714

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
