### ISSUE TITLE
Make outstanding text based changes to the site

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1236]
Many outstanding tickets are for text only changes to the site. 

These could be collated for concerted action. 

So that text changes are ready for developer implementation we need to be sure the proposed new text is finalised and agreed. 

I am raising this ticket so I can suggest action on this area when prioritisation is considered.

**Comment by confirmordeny** [comment]
We have some progress on site text since July 2022. In addition, we have a label for tickets relating to the help text.
