### ISSUE TITLE
Determine if to campaign for amendments to the special FOI treatment of HMRC

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1237]
Section 18, and perhaps section 20, of the Commissioners for Revenue and Customs Act 2005 (CRCA) appear to result in certain FOI requests to Revenue and Customs being treated differently than if they were made to other bodies. 

https://www.legislation.gov.uk/ukpga/2005/11/crossheading/information

These laws appear to prohibit the disclosure of material which might otherwise be released under FOI. 

S44 of the FOI Act which exempts information from disclosure if disclosure is prohibited by or under any enactment   https://www.legislation.gov.uk/ukpga/2000/36/section/44 

FOI doesn't override the more specific legislation. 

Proposal: Collect evidence on this point and seek to come to a decision on if we should lobby to regularise the position of Revenue and Customs with respect to FOI. 

There may be a wider set of such more specific laws which interfere with FOI. 

--
The Commissioners and the officers of Revenue and Customs may together be referred to as Her Majesty’s Revenue and Customs (HMRC).[*](https://www.legislation.gov.uk/ukpga/2005/11/section/4)

**Comment by FOIMonkey** [comment]
+1 

On a related note, I had wondered if any tax data could also be classed as environmental information, such as the CCL, as there is no s44 equivalent in EIR. I think @confirmordeny tried similar re: the aggregates levy/ landfill tax without much success, but they didn't pursue it to the tribunal level.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
