### ISSUE TITLE
Update public and internal documentation to cover takedown requests on the grounds of harm to the public

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1239]
At 

https://www.whatdotheyknow.com/help/how#what_happens

we list some types of takedown request we deal with. We've not included the rare, but important, case of concerns raised that our publication of material is contrary to the public interest. 

Similarly the induction call for new admins and the review group escalation criteria do not currently specifically mention such cases. 

Proposed new subheading at 

https://www.whatdotheyknow.com/help/how#what_happens

**Concerns publication of material is contrary to the public interest**

Takedown requests where there are concerns that our publication of material may be harming the public interest are rare. We recognise the potential impact of a wrong decision in these cases may be significant, so we consider them carefully. 

Concerns we have dealt with in this area include suggestions material we are publishing may have an adverse effect on public health, may promote hate, or may assist terrorists, or other criminals. 

Often we can seek to reduce the harm, or potential, harm by taking steps which do not impact the publication of the core FOI request and response. We can redact extraneous material from requests, or add annotations containing warnings, or providing advice on the interpretation of material for example. 

We consider the balance of the interests in favour of continued publication verses those in favour of taking the material down and come to a judgment on the responsible course of action. 

---- 
I think it is true that we've not taken substantive FOI request/response material down in response to this class of concern. We might want to mention that. 

We can point to our public position from internal documentation.

**Comment by RichardTaylor** [comment]
Proposal: a new inbox label for public interest takedowns, under "Risk".

**Comment by RichardTaylor** [comment]
>Proposal: a new inbox label for public interest takedowns, under "Risk".

Done. `label:risk:-public-interest-impact `  

We can rename that if we come up with a better descriptor for these cases.

**Comment by garethrees** [comment]
> We can rename that if we come up with a better descriptor for these cases

The proposed (and acted upon) label name doesn't make much sense to me.  "Risk: Contrary to public interest" would be clearer.

I think the specific risk element is "Harm from publication", so I'd perhaps shorten this down to "Risk: Harm"? This does seem similar to `Risk: Safeguarding` though.

**Comment by RichardTaylor** [comment]
We should consider if we want to adopt a "takedown to assess" approach in cases of potential harm to the public. (See related ticket on "takedown to assess" in personal data breach cases https://github.com/mysociety/whatdotheyknow-theme/issues/952 )

My view is that in both cases we should see a decision to take material down as a significant action which should be justified.

**Comment by RichardTaylor** [comment]
>I think it is true that we've not taken substantive FOI request/response material down in response to this class of concern. We might want to mention that.

This is no-longer true.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
