### ISSUE TITLE
Document our journalism strategy

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1240]
Document our current journalism strategy in our usual style for producing documentation which is to start by writing down current practice. 

When do we do journalism as part of our role running WhatDoTheyKnow?
How do we do journalism?

We will then be in a stronger position to discuss developments and improvements.

**Comment by RichardTaylor** [comment]
Perhaps related to this is the question of what we do when we come across potentially newsworthy material while running the service.

**Comment by RichardTaylor** [comment]
Something we could do in the future is identify when MPs are requesting the release of information in Parliament and make a FOI request in public for the material. 

eg. at

https://www.theyworkforyou.com/debates/?id=2021-05-19d.733.3#g733.7

MPs considered requesting the release of 
>"the DHSC internal review of their operation during the pandemic as referenced by the Prime Minister’s official spokesman on 12 May.”

These requests could be tagged, and linked to the relevant section of TheyWorkForYou. 

This is something we could seek to do in a formulaic way, so we can defend making the requests in the interests of transparency rather than in the pursuit of any non-FOI/transparency related political cause.

This is technically off-topic for this ticket, but something to consider when we move to discussing developments and improvements.

**Comment by garethrees** [comment]
Not quite _journalism_, but spotted [this article about archivists](http://annas-blog.org/blog-how-to-become-a-pirate-archivist.html) that may be interesting to work in to this in some way. Providing an archive is key to enabling journalism. Haven't read it yet; just enjoyed the title.

**Comment by RichardTaylor** [comment]
It's important for us to consider taking journalistic actions when we find ourselves holding material which we are not prepared to publish. 

eg. https://www.whatdotheyknow.com/request/covid_19_adverse_reaction_proced#comment-108347

**Comment by RichardTaylor** [comment]
Example of journalistic action when we're holding newsworthy material:

https://twitter.com/WhatDoTheyKnow/status/1169267051791290370?s=20&t=plVsLIkuVb7zScMR3o7twg

**Comment by RichardTaylor** [comment]
What do we do when we come across, or are pointed to, ineffectually redacted material, which we think should be released?

* Is continued publication sufficient, have we done our job, even though no-one else might ever notice and act on the material?
* What can individual administrators do with publicly accessible information which they've learned of via administrating the site?

**Comment by garethrees** [comment]
> A new project from the Internet Archive re government papers has launched. It's focussed on the US and Canada for now, but it might be one for us to watch with interest. http://blog.archive.org/2022/09/06/building-democracys-library-celebrate-with-the-internet-archive-on-october-19/

**Comment by RichardTaylor** [comment]
Can we make FOI requests to "seed" the site and demonstrate good use of it, especially on bodies to which few requests have been made? 

We could come up with types of request we're always happy to see made eg. requests for governing body, or other committee, papers which are not already published. 

We should certainly use WDTK to make FOI requests where we need/want data in connection with running the service. This crosses between journalism, operationally running the service, and campaigning, there are examples at https://github.com/mysociety/whatdotheyknow-theme/issues/1243 

I'd like to see us go further and make requests in other circumstances:
* Where we spot information being requested by users, but we think we can make, and pursue, a request in a manner more likely to lead to release.
* Where the ICO or a court/tribunal has ordered the release of material, and the request isn't on WDTK, we could request the material, if we think it would be justified. 

The big challenge/risk here is avoiding being, or appearing to be, party-politically partisan, or to be seen to be campaigning on issues unrelated to our core activities.  Notes and annotations could be used to explain the context of requests, and seek to proactively address such concerns. 

A much less constrained option would be to make requests on broad grounds eg. 

* Where we think the information in question will inform public debate

I think that's where the significant potential lies, it's also where the bigger risks emerge. 

We should find out if mySociety has addressed some of these issues before.

**Comment by garethrees** [comment]
> Can we make FOI requests to "seed" the site and demonstrate good use of it, especially on bodies to which few requests have been made?

FWIW I've written https://github.com/mysociety/alaveteli/pull/7363 so that we'll be able to add tag-based-notes to suggest some good generic requests.

**Comment by FOIMonkey** [comment]
> This is probably worth a separate issue in its own right, 

The riot is this way ➡️ https://github.com/mysociety/whatdotheyknow-private/issues/55

> but there's a difference between me:
> 
> 1. Making a request in my own time using my account registered under my personal email address
> 2. Making a request using my admin account and signing off "Gareth Rees"
> 3. Making a request using my admin account and signing off "Gareth Rees on behalf of mySociety"
> 4. Logging in as the "whatdotheyknow" user and making a request

The first two are identical, (except if your boss thinks you're procrastinating). 

The third one is different, because that would be the organisation making the request. As for the fourth, I'm not sure WDTK has sufficient legal personality to make a request without an individual's name/mySociety also being attached.

**Comment by RichardTaylor** [comment]
It may be that 2,3,&4 are technically identical, they could all be requests by and on behalf of mySociety. What they technically are, and how they appear, and the reputational and other risks associated with them are likely to be different though. 

1 could also be the same, especially if it was directly related to "work", the situation is likely to depend on the content and on the contractual situation.

There are other situations (some of which have, I think, I happened):

* A mySociety contractor makes a request in connection with the work they're contracted to do. (Such a request could be made under an organisational name (other than mySociety), an individual name, or a pseudonym.) 
* A mySociety funded/supported partner makes a request in connection with their work with mySociety
* A mySociety member of staff makes a request under a pseudonym as part of their job.  (This could be done for different reasons which have varying degrees of defensibility.) 

Key reasons this matters:

* Maintaining the reputation of mySociety/WhatDoTheyKnow
* Compliance with charity law. 
* Understanding where legal risk lies
* Understanding who has the standing to refer to the ICO or beyond
* All involved clearly understanding the position, and having a shared understanding
