### ISSUE TITLE
Improve coverage of NHS service provides

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1241]
Those providing NHS services are often subject to FOI, irrespective of if they are public sector bodies, private companies, charities. 

We have recently listed some major private sector GP service providers 

https://twitter.com/WhatDoTheyKnow/status/1536806601767763969

How can we appropriately prioritise and breakdown this work given doing it en-masse appears impractical is something to consider. 

On a policy point we have considered listing bodies on the grounds they provide NHS services. The intent of the FOI act appears to be make such bodies subject to FOI but some might not be technically covered.  GPs and pharmacies clearly are, the position of some other organisations is less clear. 

Propose we add NHS service providers, we should consider if we need any more body tags to explain why we are adding bodies. surgery, pharmacy and nhs are existing well used tags, we might want to use nhs_service_provider too where a more specific tag isn't relevant. `

https://www.whatdotheyknow.com/body/list/nhs_service_provider

Related tickets:

* https://github.com/mysociety/whatdotheyknow-theme/issues/1184 
* https://github.com/mysociety/whatdotheyknow-theme/issues/23

**Comment by RichardTaylor** [comment]
We did a chunk of these by listing

https://www.whatdotheyknow.com/body/list/nhs_ambulance_service_provider via https://github.com/mysociety/whatdotheyknow-theme/issues/1319

**Comment by RichardTaylor** [comment]
We could list Patient Transport Services (non emergency ambulance service providers)  https://www.whatdotheyknow.com/body?tag=nhs_non-emergency_ambulance_service_provider

**Comment by confirmordeny** [comment]
I would support adding all NHS service providers to the site.

**Comment by HelenWDTK** [comment]
https://wdtkwiki.mysociety.org/wiki/Authority_suggestions
