### ISSUE TITLE
GDPR template text ordering issue 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1242]
We have

>If you believe there is further information we should consider in respect of any impact to your interests, rights, or freedoms, please let us know, ideally outlining the precise nature of your concerns.

Under a heading of Search Engines. I'm going to shift it to come under "Legal Basis". This happened as the template evolved, it was never designed / authored as a whole. 

I'm going to fix this for GDPR-RtE refuse multiple requests and GDPR-RtE refuse single request it may occur elsewhere but I'm not aware of other occurrences of the issue.

**Comment by RichardTaylor** [comment]
Fixed in canned responses and canned responses library.

**Comment by mdeuk** [comment]
At one point, this was under a section called "Compliance" or "Conclusion". We replaced the former with "Privacy Notice" - I only know of a few references to the latter! 

We should probably look at the logical flow of the template overall.
