### ISSUE TITLE
Blog on CCG aboliton and move to ICB / ICP 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1244]
Requires: https://github.com/mysociety/whatdotheyknow-theme/issues/1022

* Note our coverage of the new bodies 
* Show and quote some of the struggles our users have been having seeking information from the predecessor STPs / emergent ICB/P/Ss - and say how great it is the new ones are formally subject to FOI. 
 
All ICBs will be subject to FOI via

https://www.legislation.gov.uk/ukpga/2022/31/schedule/4/paragraph/60/enacted

ICPs will be subject to FOI because [they are joint committees of councils and ICBs](https://www.legislation.gov.uk/ukpga/2022/31/part/1/crossheading/integrated-care-partnerships/enacted), so all members are public bodies so [Section 6 of the Freedom of Information Act](https://www.legislation.gov.uk/ukpga/2000/36/section/6) will apply.

**Comment by RichardTaylor** [comment]
We could mention the problems we've had with new email addresses for ICBs not working for two weeks after the bodies were established. 

We could note the issues with there being many bodies with names like, or in some cases matching "Integrated Care Partnership" but them not being the new joint committees. 

We could note the issue at https://www.whatdotheyknow.com/request/gp_level_of_service_concerns_sub#incoming-2079192  where a CCG/ICB states a FOI request in-progress at the time of transition will not continue to be processed:

>On the 1^st of July 2022, the Integrated Care Board (ICB) was formally established. As a consequence, NHS Oxfordshire CCG was dissolved and no longer exists. Therefore, your FOI request will not be processed.

**Comment by RichardTaylor** [comment]
Tweet on the ICB not concluding the request made to the CCG

https://twitter.com/WhatDoTheyKnow/status/1546882556980781059

**Comment by RichardTaylor** [comment]
Once we've written the blog we could, if it was deemed in-line with our [campaigning strategy](https://github.com/mysociety/whatdotheyknow-theme/issues/1243), let organisations which might want to use our service such as local health watch bodies, or organisations supporting those with certain conditions, and health journalists, know about it, and our service.

**Comment by RichardTaylor** [comment]
Related

* https://github.com/mysociety/whatdotheyknow-theme/issues/1415

**Comment by RichardTaylor** [comment]
>ICPs will be subject to FOI because [they are joint committees of councils and ICBs](https://www.legislation.gov.uk/ukpga/2022/31/part/1/crossheading/integrated-care-partnerships/enacted), so all members are public bodies so [Section 6 of the Freedom of Information Act](https://www.legislation.gov.uk/ukpga/2000/36/section/6) will apply.

We are now less confident about this, as the Partnerships might not be deemed to be "body corporate" in-line with the general treatment of non-limited liability partnerships in relation to other aspects of the law in England and Wales. 

The partnerships are joint committees. Joint committees are subject to FOI in their own right in certain circumstances, via 

https://www.legislation.gov.uk/ukpga/2000/36/schedule/1/paragraph/25

and 

https://www.legislation.gov.uk/ukpga/1972/70/section/102

but that doesn't apply here as it only applies to joint committees of local authorities. 

So the FOI status of ICPs might be something we need to campaign on as part of:

* https://github.com/mysociety/whatdotheyknow-theme/issues/1458

**Comment by RichardTaylor** [comment]
Another example of an issue with the transition:

https://www.whatdotheyknow.com/request/the_provision_of_telehealth_tech#incoming-2159875

Also it appears there is just one, generic, "transfer scheme"

https://nhssomerset.nhs.uk/wp-content/uploads/2022/07/Transfer-Scheme-for-CCGs-to-ICBs-Level-1-and-2-FINAL.pdf

There is no explicit reference to access to information requests. The responsibility to respond to a request could perhaps be considered a "liability" covered by:

>On the transfer date, all the property, rights and liabilities of the transferor, other than that transferred under paragraph 2 (staff transfer), are transferred to the transferee

**Comment by RichardTaylor** [comment]
Surprisingly it appears many ICPs are yet to be established. 


It may be only the ICB is formally subject to FOI so we should just have placeholders for the ICP and ICS pointing to the entry for the ICB. There may be regional variation as to the extent to which the ICPs / ICBs "exist". 


Ideas:

* FOI request to each ICB asking if the ICP has been established yet, and if it has ask for a contact email for FOI requests, link to its meeting papers online, date of its first meeting, memebers, governing document, record of decision establishing it etc.   (Some of this material may be in published ICB minutes)
* Manually review each ICB's website and papers and look for signs the ICP has or has not been established. 
* Write to NHS England, perhaps as a FOI request, to see if they have information on which ICBs have as yet established ICPs.

**Comment by RichardTaylor** [comment]
>we should just have placeholders for the ICP and ICS pointing to the entry for the ICB

The Government has asked that arrangements be made for ICPs to have a secretariat. If the "body" has a secretariat then there's a group to whom requests can be made. 

https://www.gov.uk/government/publications/integrated-care-partnership-icp-engagement-document/integrated-care-partnership-icp-engagement-document-integrated-care-system-ics-implementation#timings-and-establishment-of-icps

The Government has also stated:

>each ICP should publish a single point of contact by April 2022, so that local partners can get in touch and discuss how they might be involved

https://www.gov.uk/government/publications/integrated-care-partnerships-engagement-findings/integrated-care-partnership-icp-engagement-summary

Again this indicates that contacting an ICP is something which should be practical. 


(To throw in some more confusion,[ the Government also refers to the "The ICS partnership"](https://www.gov.uk/government/publications/integrated-care-partnership-icp-engagement-document/integrated-care-partnership-icp-engagement-document-integrated-care-system-ics-implementation#next-steps), and in doing so it doesn't mean the ICP.

**Comment by RichardTaylor** [comment]
I've added a note to ICPs:

>Integrated Care Partnerships may not be formally subject to FOI, though we expect them to be organisations [with a secretariat](https://www.gov.uk/government/publications/integrated-care-partnership-icp-engagement-document/integrated-care-partnership-icp-engagement-document-integrated-care-system-ics-implementation#next-steps) to which requests can practically be addressed.

>Do consider making your request to a member of the Integrated Care Partnership which is clearly subject to FOI such as the local [Integrated Care Board](https://www.whatdotheyknow.com/body/list/icb), or relevant local council. Do [get in-touch with us](https://www.whatdotheyknow.com/help/contact) if you are having trouble obtaining information held by an Integrated Care Partnership as [we are interested in improving access to information held by such partnership bodies](https://github.com/mysociety/whatdotheyknow-theme/issues/1458).

**Comment by RichardTaylor** [comment]
There is a parallel with the recent changes to Government departments:

https://www.gov.uk/government/news/making-government-deliver-for-the-british-people

The change hasn't been instant, and there has been a period of transition.  We are still awaiting email addresses for new departments a few weeks after they have been created.

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
