### ISSUE TITLE
Consider creating an inbox label for username change requests

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1246]

**Comment by RichardTaylor** [comment]
Go for it!

It's an important one to track to make the case for https://github.com/mysociety/alaveteli/issues/285 (and perhaps related features for cases where there are different desired outcomes).

**Comment by garethrees** [comment]
> It's an important one to track to make the case for https://github.com/mysociety/alaveteli/issues/285

While I think the case for this is totally clear already, I don't object to the proposal.

Closing as there's been 2 agreements.

**Comment by WilliamWDTK** [comment]
[Here](https://mail.google.com/mail/u/0/#label/Help%2FHelp%3A+help-user+account+management%2FUsername+change+request)

**Comment by WilliamWDTK** [comment]
> (and perhaps related features for cases where there are different desired outcomes).

Like encouraging users to choose a good name at time of account creation.
