### ISSUE TITLE
Greater transparancy surrounding data breaches by public bodies via WhatDoTheyKnow

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1248]
In our last transparency report we published the fact there were 96 inbox threads, and 40 review threads relating to such data breaches:

https://www.mysociety.org/2021/12/16/whatdotheyknow-transparency-report/

We could do more to be open about the number and severity of such breaches. 

We want to be careful:

* We don't want to draw attention to data breaches too quickly where the material may still be in Google's cache. In some cases we might not want to draw attention to a specific case at all if the breach has not been contained and the information is available on archive sites. 
* Readers may place some of the blame for the impact of the data breaches on WhatDoTheyKnow - they may consider running the service without proactive moderation of responses is irresponsible. 

What we could do:
* Write a [regular] blog post which amounts to a specific transparency report focusing on data breaches by public bodies via WhatDoTheyKnow. We could describe the information released in breaches, but perhaps not point to specific threads. 
* Better [request tagging](https://github.com/mysociety/whatdotheyknow-theme/issues/1158), but this risks drawing attention to breaches.  [We already often annotate requests where we have taken material down, and anyone watching annotations by user/whatdotheyknow, or otherwise viewing the content would see these]
* Routinely make FOI requests for notifications public bodies have sent to those whose personal data was involved in a breach. Sometimes we suspect these notifications haven't been as clear about what happened as one might have hoped. 
* Improve the content on this subject in future transparency reports. (Including t[he 2022 report](https://github.com/mysociety/whatdotheyknow-theme/issues/1170))

Closely linked:

* https://github.com/mysociety/whatdotheyknow-theme/issues/1128

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas. Things have improved a lot since the deployment of excel analyzer.
