### ISSUE TITLE
Consider tagging of bodies running 11+ exams

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1249]
This is fairly niche, but I noticed a request in the timeline to [CSSE](https://www.whatdotheyknow.com/body/csse), and I'd been pondering on [TBGS](https://www.whatdotheyknow.com/body/tbgs) on Slack a little while ago.  These two bodies I believe are essentially the same thing, but are tagged in different ways.  We could also give them a unifying overall tag.

We'd probably want to make an overview of where all grammar schools might be, some querying of GIaS might be in order.

**Comment by RichardTaylor** [comment]
>We'd probably want to make an overview of where all grammar schools might be

Are you suggesting both a tag for these bodies, and seeking to make our coverage comprehensive? 

Both sound like good ideas.

**Comment by WilliamWDTK** [comment]
> > We'd probably want to make an overview of where all grammar schools might be
> 
> Are you suggesting both a tag for these bodies, and seeking to make our coverage comprehensive?
> 
> Both sound like good ideas.

Yes. Essentially:

1. Standardise tagging
2. Make a list of areas in which (state) grammar schools exist (probably using GIAS, e.g. [this search (link may not persist)](https://get-information-schools.service.gov.uk/Establishments/Search?tok=8UAzEz34), [results.csv](https://github.com/mysociety/whatdotheyknow-theme/files/8985616/results.csv))
3. See if there is a similar consortium in existence in each area
4. Check if it is on WDTK, if yes, update it, if no, add it

**Comment by WilliamWDTK** [comment]
I think relevant information can probably be found (i.e. links to these bodies, where they exist) on the local authority for the area (the one that would ordinarily manage education).

**Comment by WilliamWDTK** [comment]
`exam_board`

**Comment by HelenWDTK** [comment]
https://wdtkwiki.mysociety.org/wiki/Tagging_suggestions

**Comment by confirmordeny** [comment]
I have created a tag here: https://www.whatdotheyknow.com/body/list/eleven_plus_exam_board
