### ISSUE TITLE
Improve documentation relating to how and when we make Google removal requests

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1250]
I've just noted:

>Using the "starts with" option to remove URLs starting eg. `https://www.whatdotheyknow.com/request/[request_ID]/ `and `https://www.whatdotheyknow.com/cy/request/[request_ID] `may be an efficient way to request removal of all attachments on a request, including "view as HTML" links.  

at 

https://wdtkwiki.mysociety.org/wiki/Main_Page#Google

I think that's sufficiently non-obvious, and potentially time-saving,  to document.

**Comment by mdeuk** [comment]
> The issue is that this doesn't leave an obvious enough footprint. When I've used this is recent breach cases, someone else has come along later and added the individual urls anyway, thinking I'd forgotten to do it.

Agreed - the portal is rather poor from a UX perspective.

The “starts with” format works well on both Google and Bing consoles - but it’s still a nuisance to do. Unfortunately, automating this isn’t so easy, otherwise I’d be encouraging pursuit of this.
