### ISSUE TITLE
Consider listing operators of "lifeline transport links"

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1251]
In the early months of the covid-19 pandemic the Government stepped in "to support lifeline transport links to the Isle of Wight and the Isles of Scilly"

https://www.gov.uk/government/news/emergency-fund-of-up-to-105-million-to-support-lifeline-transport-links-to-the-isle-of-wight-and-the-isles-of-scilly

The suggestion is that we should list the relevant operators on WhatDoTheyKnow on the basis we think they should become subject to FOI given the importance of the service they provide. 

We already list bodies on the basis of:

* [public_infrastructure](http://www.whatdotheyknow.com/body/list/public_infrastructure) - controls significant national infrastructure

The "lifeline transport links" support followed support for rail and bus service providers 

https://www.gov.uk/government/news/government-ensures-ticket-refunds-and-protects-services-for-passengers-with-rail-emergency-measures
https://www.gov.uk/government/news/almost-400-million-to-keep-englands-buses-running 

With bus services described as "vital" and trains as "essential". 

"Vital", "essential" and "lifeline transport links" are just words from the press releases rather than formal definitions of groups of services / service providers. 

Freight services were also supported:

https://www.gov.uk/government/news/vital-routes-for-supplies-and-people-kept-open-through-coronavirus-support-package

UK public funds were also spent to support the hospitality industry 

https://en.wikipedia.org/wiki/Eat_Out_to_Help_Out

Thoughts:

* If we list "lifeline transport links" it seams by that logic we ought also list bus and train service providers. 
* We'd be listing commercial companies which are not usually supported by the state and which compete with each other. They don't have the character of public bodies. 
* If the commercial market failed and the Government stepped in permanently, and nationalised the services, they would be public bodies and we'd list them. 

I don't think we should list Isle of Wight ferry operators on the basis of the support they received during the early months of the covid-19 pandemic. We could point to the public money spent on supporting them as evidence they are significant national infrastructure though. 

We should urge the focusing of FOI requests to relevant public bodies, eg. regulators and Government departments, and not the private sector service providers.  

If we listed bodies on the basis they provided a vital/lifeline service there would be an argument for listing air ambulance services run by charities, and their road based equivalents, mountain rescue /search and rescue organisations, the RNLI and others.  

Taxis are a vital service to many, should we list taxi companies? I'd say obviously not, they're not public bodies. 

What about supermarkets - they're clearly a critical part of our national infrastructure, and vital for life, but they are not public bodies.  

I think we should focus more tightly on public bodies, or bodies with the character of public bodies, or which have been given responsibilities which should lie with Government.

**Comment by RichardTaylor** [comment]
>I think you that have misunderstood the argument, and have drawn false comparisons here, but I see little point in relitigating what has already been discussed at length elsewhere.

This was not my intention. 

I thought we'd reached a point where we had a proposal worth ticketing, which was, as per the title of this ticket:  'Consider listing operators of "lifeline transport links"' 

There were a couple of related questions:

The first question was if there is a formal definition of "lifeline transport links" we could just use. I don't think there is. 

The second unresolved question is if we can come up with our own definition of "lifeline transport links", and that's what I have discussed in the ticket. 

How about we add "lifeline ferry services"? On the basis that ferries provide services where there are fewer practical alternatives than rail, bus and taxi services which typically serve circumstances where an alternative option is reasonably practical.

>We listed the bulk of the TOCs on the basis of EIR obligations
If there are transport companies under the control of the Government then we could list them in-line with 
 
https://www.itspublicknowledge.info/sites/default/files/Decision044-2021.pdf

**Comment by HelenWDTK** [comment]
We decided not to add these, so I'm closing this (and also hoping that we'll change our minds one day).
