### ISSUE TITLE
Reduce bureaucracy

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1255]
I suspect there are a few ideas which could come under this heading. 

I'll start with:

* Remove the email subject column from the GDPR tracker spreadsheet. 

  While [finding a working shortcut for "paste and match style" ](https://github.com/mysociety/whatdotheyknow-private/issues/19#issuecomment-1156262339)reduced the degree to which copying and pasting subject lines into this spreadsheet causes a hassle, there are still outstanding issues eg. the word "Inbox" often being appended to copied text, sometimes after a line break causing it to appear in the next row of the sheet. 

* Streamlining the "Inbox Stats" presented in the "Admin and Operations Journal" as part of the bi-weekly Sprint Planning Meeting.

* Streamlining the "Work of note for the last two weeks" section of the  "Admin and Operations Journal" and the similar content in the "Thanks and team updates" section of the Community & Activism Call agenda. 

* Reviewing the threshold for escalation of defamation cases to review - a suggestion which is on the review agenda currently

**Comment by mdeuk** [comment]
> * Remove the email subject column from the GDPR tracker spreadsheet.
>   While [finding a working shortcut for "paste and match style" ](https://github.com/mysociety/whatdotheyknow-private/issues/19#issuecomment-1156262339)reduced the degree to which copying and pasting subject lines into this spreadsheet causes a hassle, there are still outstanding issues eg. the word "Inbox" often being appended to copied text, sometimes after a line break causing it to appear in the next row of the sheet.

Case ingestion is due to be automated - I’m loathe to make any change to this at the moment, but it is something to be looked at.

> * Streamlining the "Inbox Stats" presented in the "Admin and Operations Journal" as part of the bi-weekly Sprint Planning Meeting.

We should be looking at automating the production of any statistics - it is perhaps excessive to be producing them manually.

**Comment by RichardTaylor** [comment]
There are two agenda templates for the review call, one at the top of document, and one as a separate linked document.

**Comment by mdeuk** [comment]
> There are two agenda templates for the review call, one at the top of document, and one as a separate linked document.

I do wish we’d stop using rolling agendas like this - it would be less painful if an agenda doc was there for either a given call, or a shorter period.

Some of the documents are excessive (>100 pages) as they don’t get split, which causes performance issues.

**Comment by WilliamWDTK** [comment]
> I do wish we’d stop using rolling agendas like this - it would be less painful if an agenda doc was there for either a given call, or a shorter period.
> 
> Some of the documents are excessive (>100 pages) as they don’t get split, which causes performance issues.

One could always link to the (folder of) previous agenda(s), for ease of access.

**Comment by RichardTaylor** [comment]
We're storing the volunteer agreement and associated documents on the wiki 

https://wdtkwiki.mysociety.org/wiki/Recruitment_to_admin_team

and we also have a couple of copies in Google docs. 

We should have just one copy of the current unsigned materials ready to send out to prospective volunteers.

**Comment by mdeuk** [comment]
> We're storing the volunteer agreement and associated documents on the wiki
> 
> https://wdtkwiki.mysociety.org/wiki/Recruitment_to_admin_team
> 
> and we also have a couple of copies in Google docs.
> 
> We should have just one copy of the current unsigned materials ready to send out to prospective volunteers.

It would probably make sense to have these automatically generated on demand from a template - so that we are pre-populating any relevant details on the template. A Google fo should do the trick.

We’ve not looked at these templates substantively for a while, so it’d also be good to check if it still does what we want. Should we, perhaps, also be looking at using a digital signature tool, as the current process is perhaps clunkier than we’d like it to be?

I’d be happy to look at a ticket for this one

> We're storing the volunteer agreement and associated documents on the wiki
> 
> https://wdtkwiki.mysociety.org/wiki/Recruitment_to_admin_team
> 
> and we also have a couple of copies in Google docs.
> 
> We should have just one copy of the current unsigned materials ready to send out to prospective volunteers.

I’ve split this into #1294, I agree it is an issue.

**Comment by mdeuk** [comment]
> We're storing the volunteer agreement and associated documents on the wiki
> 
> https://wdtkwiki.mysociety.org/wiki/Recruitment_to_admin_team
> 
> and we also have a couple of copies in Google docs.
> 
> We should have just one copy of the current unsigned materials ready to send out to prospective volunteers.

I’ve split this into #1294, I agree it is an issue.

(repost as threading had messed up first time)

**Comment by sallytay** [comment]
@garethrees and me have been talking about streamline the admin and operations journal in general, taking one of the initial suggestions above:

>Streamlining the "Inbox Stats" presented in the "Admin and Operations Journal" as part of the bi-weekly Sprint Planning Meeting.

Before working on this it would be useful to know what information that you would find useful in this section.

I think it is useful to look at the total number of threads in each sprint - but what else would you like to see?

**Comment by RichardTaylor** [comment]
The [new policy asking admins to note the date/time at which the decision making policy permits action to be taken on a case ](https://wdtkwiki.mysociety.org/wiki/Decision-making_policy)could, if followed, lead to significant extra bureaucracy.

**Comment by RichardTaylor** [comment]
The practice of copying all previous correspondence on a case into a Google docs based reply under a heading of eg. 

"Our Understanding Of Your XXXX"

I don't think this achieves much, if anything. A précis of the key points would better show our understanding and focus the correspondence, it would focus our minds on the key issues while preparing the correspondence too, as well as remove a tedious bureaucratic exercise.

**Comment by garethrees** [comment]
> copying all previous correspondence on … "Our Understanding Of Your XXXX"

+1, this should be a _synthesis_ of our understanding, based on what we've been told.

**Comment by garethrees** [comment]
> The [new policy asking admins to note the date/time at which the decision making policy permits action to be taken on a case ](https://wdtkwiki.mysociety.org/wiki/Decision-making_policy)could, if followed, lead to significant extra bureaucracy.

Working in a team has benefits _and_ costs. There's a cost to coordination, but we do want to keep things simple. It's not suggested that this be used on every action. It's a question of judgement. If you're thinking "other people will have stuff to say on this" or "I'm not totally confident that what I'm suggesting is the right thing to do", etc then that's the time to pull this out.

**Comment by mdeuk** [comment]
> > copying all previous correspondence on … "Our Understanding Of Your XXXX"
> 
> +1, this should be a _synthesis_ of our understanding, based on what we've been told.

+1, summarising _can_ be tricky sometimes, but it has considerable benefit, especially if the decision requires subsequent review.

> Working in a team has benefits _and_ costs. There's a cost to coordination, but we do want to keep things simple.

+1, the tools and processes should work together reasonably well, so as to  allow for efficient administration. We're already some way there - we've just got to look at what we can refine. I do share the concern here - but, I also think there is an advantage, when seeking the views of others (or consensus), to outlining a clear timescale + next steps (e.g. if no reply, the action will either be taken or not).

I suppose the catchy strapline is - measure twice, cut once…

**Comment by FOIMonkey** [comment]
>  I also think there is an advantage, when seeking the views of others (or consensus), to outlining a clear timescale + next steps (e.g. if no reply, the action will either be taken or not).

+1 I think it strikes the right balance between not wanting to slow things down and allowing space for a wider variety of views to be heard on any particular issue, especially the more controversial ones.

**Comment by RichardTaylor** [comment]
I just wanted to send a standard response to a FOI officer asking for their name to be removed. 

This used to be possible with three clicks and me signing my name (via a canned response). 

I don't think we have a canned response for this any more. This could be because these kinds of request have become rarer - which is good. 

I found a link to a draft Google docs template for such a response from the caned responses archive document, but completing that would have been massive overkill. 

I used the history of the canned responses archive document to find an old template response. I brought it up-to-date, and in-line with our public help pages, and used it. 

I hope this note helps illustrate how bureaucracy and complexity is being added.

**Comment by RichardTaylor** [comment]
We should stop cases coming to the review call more than once, unless there is substantial new material / progress. (Related https://github.com/mysociety/whatdotheyknow-theme/issues/1436 )

**Comment by HelenWDTK** [comment]
It looks like almost all of the individual suggestions here have either been implemented or are now out of date. I'm closing this as complete. I think individual examples are probably better documented separately rather than on one catch all ticket, as it makes these easier to track/know when they have been completed.
