### ISSUE TITLE
Update notes of eir_only train operating companies to cite Scottish ICO decision that Abellio Scotrail Ltd was subject to the EIR

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1256]
In the decision at

https://www.itspublicknowledge.info/sites/default/files/Decision044-2021.pdf

it was determined the "high degree of contractual control" given to Scottish ministers via the franchise agreement under which Abellio Scotrail Ltd delivered the ScotRail franchise meant the company was subject to the EIR. 

We can seek to extend this argument to other rail operators who work under a franchise agreement giving the Government control over their operations. 

Bodies to review for adding an additional note to:

https://www.whatdotheyknow.com/body/list/railways

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
