### ISSUE TITLE
Blog on the value of an archive of FOI requests and responses

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1259]
In order to defend publication, and explain why we do what we do, it would be good to have an article to point to on this subject. 

Inspiration:

https://archive.org/about/

https://www.nationalarchives.gov.uk/about/our-research-and-academic-collaboration/our-research-priorities/priority-research-themes/impact-value-and-affect/

https://www.nationalarchives.gov.uk/about/our-research-and-academic-collaboration/our-research-priorities/priority-research-themes/openness-access-and-use/

https://en.wikipedia.org/wiki/Wikipedia:Why_Wikipedia_is_so_great

---

I was recently considering why we were going to the effort of preserving some data on bin collection days in a council from a few years ago. We were going to spend staff and volunteer time on the case due to problematic material appearing in the data and redaction being required. Even with something like that it's a historic record, it might be of interest to people in the future to see eg. how often bins got emptied in the 2010s. More practically one could envisage the data being of use to staff, or staff representatives, in the future - perhaps it could be used, along with other sources, on the efficiency of bin collection, how hard staff were worked, or how effective automation has been on making the process more efficient.   While there are other ways to track growth of an area, seeing the change in bin collection patterns, might be one interesting perspective on growth. 

We shouldn't think that we can come up with all the things people might do with the information in our archive. One could envisage art made from bin collection patterns in an area for example. Applications don't always have to be worthy.

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
