### ISSUE TITLE
Social / off-topic Slack channel for WhatDoTheyKnow admins

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1260]

**Comment by mdeuk** [comment]
Related: #1028, #1213

**Comment by FOIMonkey** [comment]
+1 As a temp fix, I can always post Isle of Wight memes on main when the inbox is on zero!

**Comment by FOIMonkey** [comment]
We still have the WDTK workspace I can add people to, but that would exclude staff. It's good to get to know the people who you "work" with and share a common interest with, particularly when the inbox is on zero.  It's all about community, connection and building something bigger. But really, we just need somewhere to talk about trains without annoying everyone else!

**Comment by FOIMonkey** [comment]
To further add to this, I think it helps to think about this in terms of what people might want access to in relation to an interest/hobby, rather than their job.

**Comment by WilliamWDTK** [comment]
There are now two members of staff in the WDTK workspace, although only one is active there, the inactive one no longer working on WDTK as part of their role.
