### ISSUE TITLE
Treat a Dudley Metropolitan Borough Council email address as a no reply address

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1262]
In light of the bounces at eg.

https://www.whatdotheyknow.com/request/dudley_council_officer_equality#incoming-2075103

and

https://www.whatdotheyknow.com/request/trip_to_cannes#incoming-2046850

and

https://www.whatdotheyknow.com/request/bullying_59#incoming-1879888

treat `foi@dudley.gov.uk` as a "no reply" address by adding it to model_patches.rb

**Comment by mdeuk** [comment]
Fix submitted in PR #1264
