### ISSUE TITLE
Link to the Charity Commission for Northern Ireland database

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#1267]
From a recent discussion on Slack, it was noted by @RichardTaylor that:

> I had forgotten we had magic to detect the type of Charity number and wondered if I needed to so something special with tagging Scottish charities - and found I don't.

We do this by handling the 'charity' tag through special functionality in [/lib/views/public_body/_more_info.html.erb](https://github.com/mysociety/whatdotheyknow-theme/blob/master/lib/views/public_body/_more_info.html.erb) - however, this only works for charities that appear on the registers of the Charity Commission for England and Wales (CCEW), or the Office of the Scottish Charity Regulator (OSCR). We should add the Charity Commission for Northern Ireland (CCNI) to this.

The format for CCNI is broadly similar to CCEW (it appears to be the same software) - with a slight nuance. Charities in NI use an alphanumeric identifier (e.g. [NIC102724](https://simoncommunity.org/legal)), but the database only accepts the numeric identifier - so we will need to accommodate this.

https://www.charitycommissionni.org.uk/charity-search/?searchText=#{ tag_value } would seem to be a valid structure to use.

**Comment by garethrees** [comment]
If I understand correctly, all we'd need is a minor change to the sidebar and to tag NI charities as `NIC:102724`?

```diff
diff --git a/lib/views/public_body/_more_info.html.erb b/lib/views/public_body/_more_info.html.erb
index 17a111c..8ee6c67 100644
--- a/lib/views/public_body/_more_info.html.erb
+++ b/lib/views/public_body/_more_info.html.erb
@@ -17,6 +17,9 @@
     <% if tag_value.match(/^SC/) %>
       <%= link_to _('Charity registration'),
                     "https://www.oscr.org.uk/about-charities/search-the-register/charity-details?number=#{ tag_value }" %><br>
+    <% elsif tag_value.match(/^NIC/) %>
+      <%= link_to _('Charity registration'),
+                    "https://www.charitycommissionni.org.uk/charity-search/?searchText=#{ tag_value }" %><br>
     <% else %>
       <%= link_to _('Charity registration'),
                     "https://register-of-charities.charitycommission.gov.uk/charity-search/-/results/page/1/delta/20/keywords/#{ tag_value }" %><br>
```

**Comment by garethrees** [comment]
Oh, no, I _don't_ understand correctly. Usually we tag `charity:SC1234`. If we tagged `charity:NIC1234` with the same linking method then we'd still be inputting the NIC prefix into the query param. That's easy enough to strip out though, and I think the consistency of using the full ID as the tag value (i.e. `charity:NIC1234`) and then manipulating that to construct the link is the best approach.

Drafted this improvement at https://github.com/mysociety/whatdotheyknow-theme/pull/1284

**Comment by mdeuk** [comment]
> Oh, no, I _don't_ understand correctly. Usually we tag `charity:SC1234`. If we tagged `charity:NIC1234` with the same linking method then we'd still be inputting the NIC prefix into the query param. That's easy enough to strip out though, and I think the consistency of using the full ID as the tag value (i.e. `charity:NIC1234`) and then manipulating that to construct the link is the best approach.

Sorry, that's my fault - I should have been clearer as to what I meant.

> Drafted this improvement at #1284

I haven't been able to test it, but this LGTM. 👍
