### ISSUE TITLE
Change our decision making approach following failure to reach a consensus decision

### ISSUE THREAD

**Issue by FOIMonkey** [mysociety/whatdotheyknow-theme#1269]
Our current policy states:
> One pragmatic option for administrators who disagree with an action is not to take part in it themselves and let others take the proposed action
https://wdtkwiki.mysociety.org/wiki/Policies#Decision_making_approach

I adopted this approach for the first time in a recent case where I strongly disagreed with the decision taken, but did not openly say that I was doing this. On reflection, it was unfair on others who were willing to progress the case, and who were still seeking consensus, not to have said that this was what I was doing.

I'd like to change the policy here to recommend that any admin actively choosing not to work on something out of principle rather than apathy should be encouraged to state this is the case. One option in this case would have been to have had this minuted this on the call when my dissent was noted, but I also could have replied to the thread. 

Disagreement is healthy, and transparency around this should be encouraged.

**Comment by garethrees** [comment]
> recommend that any admin actively choosing not to work on something out of principle… should be encouraged to state this is the case

Feels sensible to me. In practice I think (_hope_!) this is relatively rare, so when it _does_ happen we're at a little bit oblivious in recognising it's happening.

> Disagreement is healthy, and transparency around this should be encouraged.

Agree, and thanks for the positive spirit in which this suggestion was made!

**Comment by FOIMonkey** [comment]
This was agreed today and I've updated the wiki.
