### ISSUE TITLE
Users attempting to contact the WDTK are forced to use the volunteering form

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1270]
Users attempting to contact the WDTK team using the "I have another issue, or feedback relating to the WhatDoTheyKnow.com website, that I want to raise with the team that runs WhatDoTheyKnow." option are forced to use the volunteer form.

This was noted by someone who attempted to contact us and was forced to use that form.

https://user-images.githubusercontent.com/99501342/178277476-b4f4e63a-22ce-4c9d-acbe-38b7d868650f.mp4

To note: I hadn't seen the existing thread in the inbox about the issue.

**Comment by sallytay** [comment]
The original contact form should still be available with the I'd like to volunteer form as an additional option.

I can see that the "I have another issue, or feedback relating to the WhatDoTheyKnow.com website, that I want to raise with the team that runs WhatDoTheyKnow." is now directly linking to the new form not the original one.

**Comment by mdeuk** [comment]
This appears to be happening because the label "I have another issue, or feedback relating to the WhatDoTheyKnow.com website, that I want to raise with the team that runs WhatDoTheyKnow."  is still pointing to houdini goal 3, whereas it should now be goal 4. I will submit a PR.
