### ISSUE TITLE
Volunteer form does not check for repetition

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#1272]
The new 'I want to volunteer' form added in #1179 / #1208 does not appear to sense check responses so as to stop the same reply being given in every freeform text field.

This leads to form-spam being generated, as the spammer's script merely inserts the same nonsense in each field.

**Proposal:** Prevent repetition by validating the data inserted, ensuring a unique value is present in each field (where required).

**Comment by garethrees** [comment]
> Checking "I'm not sure yet" with other tasks. You probably could argue there are situations where that's applicable, though.

I'd definitely interpret this as "I'm open to suggestion"..

> Proposal: Prevent repetition by validating the data inserted, ensuring a unique value is present in each field (where required).

We do have a [`ContactValidator`](https://github.com/mysociety/alaveteli/blob/develop/app/validators/contact_validator.rb) but we'd need to [complect](https://youtu.be/SxdOUGdseq4?t=1891) that to handle the "volunteer" vs "general purpose" forms.

IDK if we can do this easily with HTML validations?

> This leads to form-spam being generated

Have we had lots already?

**Comment by mdeuk** [comment]
> Have we had lots already?

@FOIMonkey crunched the numbers on https://github.com/mysociety/whatdotheyknow-theme/issues/1473#issuecomment-1327373887 - at the time of writing there had been 16 in the week.

It's not a _massive_ issue, just a little bit of an admin nuisance.

**Comment by garethrees** [comment]
@gbp I _think_ you did something that checks for repetitive content? Close if so.
