### ISSUE TITLE
Review use of bullet points / styling in contact form

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#1276]
When the various contact forms on /help/contact are rendered, we are rendering the headline text in bullet points, and then rendering the form itself in another bullet point.

### Why is it an issue?

Rendering a bullet point next to the form looks a little peculiar, and slightly less polished than our UX usually is. This is probably nitpicking, and it might purely be an aesthetic complaint, rather than broken functionality.

<img src="https://user-images.githubusercontent.com/249418/178630108-93a4d69c-2c62-4daa-87fe-88e6fe650057.png" width="500px" alt="Image of the WhatDoTheyKnow volunteer contact form, showing that there are three visible bullet points - two for the listing of options, and one for the form itself. An orange circle has been drawn over the bullet point for the form, and the annotation 'Why?' has been added">

### Possible solution

We already have a css selector which will [remove visible bullet points](https://github.com/mysociety/alaveteli/blob/master/app/assets/stylesheets/responsive/_help_style.scss) from unstructured lists, but applying this this also removes the padding on the left margin, which makes the form slightly less logical in appearance.

<img src="https://user-images.githubusercontent.com/249418/178629717-12688fcc-93e1-4aa8-8fd8-a86fb9314a83.png" width="500px" alt="Image of the WhatDoTheyKnow volunteer contact form, showing that the bullet points have been removed from visible styling, and there is no no padding on the left hand side. An orange bracket has been on the left hand side, indicating where there should be space, and the annotation 'Lack of space to breathe' has been overlaid">

### Suggested fix

This is a relatively obscure usage, so if adding to the core stylesheet is deemed to be overkill, a hack would be to apply styling at a local level (e.g. `<li style="list-style-type:none;">`). This would, perhaps, only need to be applied to the list item containing the form itself - so as not to remove the visible bullet from areas where we might wish to retain it.

Example:
<img src="https://user-images.githubusercontent.com/249418/178631163-fc3177cc-dc51-4732-b753-8fe6d3a185ef.png" width="500px" alt="Image of the WhatDoTheyKnow volunteer contact form, showing that the bullet points for the list items still exist, but that the bullet point appearing at the left hand side of the form has been removed. A green circle has been drawn where the bullet point ought to have been, and the annotation 'Bullet point removed, space preserved' has been overlaid.">

This isn't necessarily a perfect solution, so I'll open the floor to the design gurus who might have a better idea than me.

**Comment by mdeuk** [comment]
> I'm not sure the form even needs to be rendered as part of the list ([#1208 (comment)](https://github.com/mysociety/whatdotheyknow-theme/pull/1208#discussion_r889930165)).

I'm not sure why we do it like that - perhaps it was for styling (it's been like that since d8df394b47fc3b823eeb817b0ae39531b0db222b).

If we move the form out of the list, you do gain a slight nuisance, in that the container renders directly off the left-hand side, whereas we'd previously had it in-line with the list elements.
<img src="https://user-images.githubusercontent.com/249418/179018522-13d801fb-7451-4248-8bea-1ee868b2f248.png" alt="Contact form, as shown in previous comments, but having now been moved on the page slightly. The yellow bounding box now renders directly from the start of the left hand margin">

I'm agnostic as to which is _**better**_, but I do have a slight preference for keeping positioning as it were - as this allows for a logical "flow" and for the user to focus on things in a straight line - e.g. read the list and then the form is neatly rendered for them in the place they expect it to be.

**Comment by garethrees** [comment]
> I'm not sure why we do it like that - perhaps it was for styling

Yeah nor me and haven't / likely won't have time to _really_ dig in to.

> I do have a slight preference for keeping positioning as it were

Agreed for same reasoning.

Open to contributions on this but unlikely we'll actively look at it until the next time we happen to work on the contact form.

**Comment by mdeuk** [comment]
> Open to contributions on this but unlikely we'll actively look at it until the next time we happen to work on the contact form.

I'll stick a PR in with the kludge I'd proposed - I'm sure there's a _better_ solution, but it's so trivial that it doesn't really seem worth pondering much more.
