### ISSUE TITLE
Add ambulance trusts to a separate category from other health trusts

### ISSUE THREAD

**Issue by FOIMonkey** [mysociety/whatdotheyknow-theme#1279]
I've noticed whilst classifying that Ambulance Trusts get added to lot of batch requests that are not relevant to them because they are listed under heath trust.

eg: https://www.whatdotheyknow.com/request/information_with_regards_to_mela_154

The work of Ambulance trusts is fundamentally different from other trusts, so it would make some sense to split them out.

This could also help batch category picker users.

**Comment by RichardTaylor** [comment]
This looks simple at first glance as there are only 10 Ambulance Trusts in the UK, plus the Ambulance Services for each of Wales, Scotland and Northern Ireland, plus the special arrangements for the Isle of Wight. ([Source](https://aace.org.uk/uk-ambulance-service/))

I have started a more general ticket for categories/tags for the other classes of NHS trust:

* https://github.com/mysociety/whatdotheyknow-theme/issues/1281


Proposal:

* Tag the ambulance trusts "ambulance_trust". 
* If we just had a category for ambulance trusts we'd miss out the bodies responsible for providing ambulance services in Wales, Scotland, Northern Ireland (maybe) and the Isle of Wight.  Perhaps we want also want a tag "ambulance_service" for the bodies responsible for the provision of the primary emergency/acute ambulance service in a region. This could be the one we make public via a category. 
* We also have organisations which contract to the NHS to provide ambulance services on behalf of an ambulance trust or other responsible commissioning body ([example](https://www.whatdotheyknow.com/body/ukems)).  We have  https://www.whatdotheyknow.com/body/list/nhs_service_provider but we could be more specific with nhs_ambulance_service_provider
* Document this at https://wdtkwiki.mysociety.org/wiki/NHS_Bodies which is linked from https://wdtkwiki.mysociety.org/wiki/Policies#Tagging

**Comment by RichardTaylor** [comment]
>Tag the ambulance trusts "ambulance_trust".

Done: https://www.whatdotheyknow.com/body?tag=ambulance_trust

> Perhaps we want also want a tag "ambulance_service" for the bodies responsible for the provision of the primary emergency/acute ambulance service in a region. This could be the one we make public via a category.

Done: https://www.whatdotheyknow.com/body/list/ambulance_service

>We have https://www.whatdotheyknow.com/body/list/nhs_service_provider but we could be more specific with nhs_ambulance_service_provider

I've used that tag on the one I'm aware of 
https://www.whatdotheyknow.com/body?tag=nhs_ambulance_service_provider

>Document this at https://wdtkwiki.mysociety.org/wiki/NHS_Bodies 
Done.  https://wdtkwiki.mysociety.org/wiki/NHS_Bodies#Ambulance_Services

--

That's all done, we might, in the future want to distinguish between emergency/acute ambulance services and others - eg. those which are primarily transport. I've added a note on that on the wiki page.
