### ISSUE TITLE
Categories / tags for each of the different types of NHS trust

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1281]
There are 

* Hospital trusts (also known as acute trusts)
* Mental health trusts
* Ambulance services trusts
* Community health trusts

https://en.wikipedia.org/wiki/NHS_trust

Currently we list them all together under

https://www.whatdotheyknow.com/body?tag=nhstrust

We could usefully have tags/categories to distinguish them. 

More specific ticket for tagging ambulance trusts:

* https://github.com/mysociety/whatdotheyknow-theme/issues/1279

**Comment by RichardTaylor** [comment]
Actually this shouldn't be closed. Still to do:

Update those categories other than ambulance_service for Scotland, Wales and Northern Ireland.

**Comment by WilliamWDTK** [comment]
And it needs wikificating, too.

**Comment by RichardTaylor** [comment]
>wikificating

It's been documented at

https://wdtkwiki.mysociety.org/wiki/NHS_Bodies

**Comment by HelenWDTK** [comment]
https://wdtkwiki.mysociety.org/wiki/Tagging_suggestions
