### ISSUE TITLE
Consider removing excessively large categories eg. NHS Trusts and Local Councils

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1282]
https://www.whatdotheyknow.com/body/list/nhstrust

The reason is to deter batch requests to all of them (which are rarely relevant to all of them)

We would do this only after introducing categories for each type of Trust:

* https://github.com/mysociety/whatdotheyknow-theme/issues/1281

I suggest we first look to see if just introducing the more specific categories, in addition to the overall category, sufficiently addresses the issue of misdirected requests, so I'm proposing no action on this now.

**Comment by RichardTaylor** [comment]
This could be generalised into removing excessively broad categories in-favour of more precise ones. 

We could get rid of

https://www.whatdotheyknow.com/body?tag=local_council

Once we have a full set of alternatives eg. 

https://www.whatdotheyknow.com/body/list/highways
https://www.whatdotheyknow.com/body/list/UTLA
https://www.whatdotheyknow.com/body/list/parish_council

**Comment by RichardTaylor** [comment]
What about things like Schools, Surgeries and Parish Councils?

Perhaps these should only be selectable in the batch select tool either as a "[sample](https://github.com/mysociety/alaveteli/issues/6864)" or by Town/County. (We don't currently have the structured data in our database to do the geographic selection). 

Related:

* https://github.com/mysociety/alaveteli-professional/issues/190
* https://github.com/mysociety/alaveteli/issues/2500

**Comment by FOIMonkey** [comment]
> (We don't currently have the structured data in our database to do the geographic selection).

I've been tagging parish council's by the districts/counties when I've been adding them, which could be used to group them together. There are an awful lot we don't have data for, but it could be doable.

**Comment by garethrees** [comment]
> We could get rid of https://www.whatdotheyknow.com/body?tag=local_council…

I'd have more of a preference of adding additional categories (e.g. [Local councils (Scotland)](https://www.whatdotheyknow.com/body/list/scotland_council) to _complement_ this one.

**Comment by mdeuk** [comment]
> > We could get rid of [https://www.whatdotheyknow.com/body?tag=local_council…](https://www.whatdotheyknow.com/body?tag=local_council%E2%80%A6)
> 
> I'd have more of a preference of adding additional categories (e.g. [Local councils (Scotland)](https://www.whatdotheyknow.com/body/list/scotland_council)) to _complement_ this one.

This is my preference - albeit, I wonder if we can use geographical tagging to do it automatically. This would have the handy benefit of improving our geographical tagging, which then feeds into the workstream for #416, #825, and #908.

**Comment by RichardTaylor** [comment]
The issue here has been addressed in respect of NHS Trust and Local Councils by adding lots more more specific categories and reducing the prominence of the overall categories. 

>What about things like Schools, Surgeries and Parish Councils?

The cap on the size of a batch stops requests to the entirety of these categories. 

I think we can consider this done, even though the large categories do still exist. 

We could return to remove them if their presence prompts people to make excessively broad batch requests.
