### ISSUE TITLE
Use Companies House data to help keep the WhatDoTheyKnow database up-to-date

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1285]
Seek to:

* Identify defunct / inactive companies. 
* Spot and act on company name changes.

Companies House data download which might help us do this

https://download.companieshouse.gov.uk/en_output.html

or we could obtain data via their API

https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/reference

Related ticket for NHS bodies: https://github.com/mysociety/whatdotheyknow-theme/issues/828

**Comment by mdeuk** [comment]
One where this would have been useful is the [Great British Railways Transition Team](https://www.whatdotheyknow.com/body/gbrtt) (111666).

Confusingly, the entity we had been listing, Great British Railways Transition Team has been rebranded to [Network Rail One Limited](https://find-and-update.company-information.service.gov.uk/company/13538745/filing-history). The new entity, which has the same name, [is now company 14066335](https://find-and-update.company-information.service.gov.uk/company/14066335/filing-history) - which was, oddly enough, previously known as Network Rail One Limited. This change took place on 27 April 2022.

The [PSC](https://find-and-update.company-information.service.gov.uk/company/14066335/persons-with-significant-control) declared as Network Rail Holdco Limited (company [04423711](https://find-and-update.company-information.service.gov.uk/company/04423711/filing-history)); whereas, the [previous entity PSC](https://find-and-update.company-information.service.gov.uk/company/13538745/persons-with-significant-control) was Network Rail Limited ([04402220](https://find-and-update.company-information.service.gov.uk/company/04402220)) - which is the company that holds the shares in Holdco.

If we had been consuming Companies House open data on a continuous-integration, or even periodic basis, we might have caught this one sooner - albeit, if we'd have been automating this, we might very well have renamed the entity we list and confused things a little.

The way to solve that conundrum might well be to do a periodic matching exercise against data exposed in the API and have this routed in the same way as a change request - meaning an administrator can review what's changed and make any relevant database edits. In essence, marking the [automaton](https://dictionary.cambridge.org/dictionary/english/automaton)'s homework.
