### ISSUE TITLE
Blog on contrasting approaches by different public bodies responding to similar requests information

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1290]
eg. 

ScotRail released the number of tickets sold by each of their booking offices since 2009

https://www.whatdotheyknow.com/request/statistics_of_how_many_tickets_h_4#incoming-2080706

but the Department for Transport refused to release information on which is the quietest ticket office

https://www.whatdotheyknow.com/request/quietest_ticket_office

[Example taken from Slack]

If we had 3-6 examples we could do a blog on this subject.

**Comment by WilliamWDTK** [comment]
A particularly useful place to find such example might be batch requests.  Where they have been classified, that can aid discovery.

**Comment by RichardTaylor** [comment]
Another request on  the ticket office stats, again copied from Slack:
https://www.whatdotheyknow.com/request/statistics_of_how_many_tickets_h_2#incoming-2080953

**Comment by WilliamWDTK** [comment]
Or even the same body:

[This one was refused](https://www.whatdotheyknow.com/request/number_of_times_afolake_jaja_has#incoming-2085179), [this one was answered](https://www.whatdotheyknow.com/request/number_of_times_timothy_raggatt#incoming-2064248) (answer being zero).

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
