### ISSUE TITLE
More comprehensive tagging of authorities with `dpr:nnnnnnnnn`

### ISSUE THREAD

**Issue by MattK1234** [mysociety/whatdotheyknow-theme#1291]
We currently have 1113 authorities tagged with a DPR number, linked to the ICO's register of fee payers.

When tagged this produces a nice link for 'Data Protection Registration' in the right sidebar of the body page.

I've just tagged up a few hundred more via a CSV upload.

**Comment by mdeuk** [comment]
> I've just tagged up a few hundred more via a CSV upload.

Thank you!

Q: Did you source the data manually (e.g. by [querying the ICO DB](https://ico.org.uk/esdwebpages/search)), or did you use the [(rather bulky) extract](https://ico.org.uk/about-the-ico/what-we-do/register-of-fee-payers/download-the-register/) to do it?

**Comment by MattK1234** [comment]
> Q: Did you source the data manually (e.g. by [querying the ICO DB](https://ico.org.uk/esdwebpages/search)), or did you use the [(rather bulky) extract](https://ico.org.uk/about-the-ico/what-we-do/register-of-fee-payers/download-the-register/) to do it?

I did that lot manually but for my next load I'm going to have a play around with the extract 😄

**Comment by WilliamWDTK** [comment]
I had a look at the extract before (December 2021).  There is a column for public authorities in there, which is supposed to identify whether they are subject to the FOIA, but it's self-reported (as far as I'm aware) and sometimes inaccurate.

I generated a JSON file with all records tagged public authorities, it was 60MB.  Unfortunately, I can't find the script I used to do so.  It might have been one of the occasions where I used the terminal, which wasn't a particularly wise move.

**Comment by RichardTaylor** [comment]
Might be worth clarifying why we are doing this:

* Does it help us keep the body database up-to-date?
* Are we interested in bodies declaring they're subject to FOI in their DPR register entries?
* Does it help Search Optimisation of our pages?

**Comment by mdeuk** [comment]
> Might be worth clarifying why we are doing this:
> 
> * Does it help us keep the body database up-to-date?

I’d say it does - but also, it’s similar to other database linkages, there is a benefit to our users in provision of links to open data.


> * Are we interested in bodies declaring they're subject to FOI in their DPR register entries?

Truthfully, id be more interested if it was more than a tickbox on a form - there’s a good bit of inconsistency in this data, which is a shame, as it would actually be very useful to have had an authoritative source from the ICO to refer to. Perhaps this is a useful lobbying point?

> * Does it help Search Optimisation of our pages?

I think the only benefit could be if users were searching based on the ICO data protection fee payer number - as we don’t present it in a visible format. If we thought it would be beneficial to display the number itself, we probably could, it’s not a very long thing.

**Comment by MattK1234** [comment]
I'd agree it's similar to how/why we tag schools with `urn:` etc.

It provides a method for someone to click through to the data protection register entry from the WDTK body page. I doubt it's used much.

In doing this I found a few different things:
- Found some bodies we didn't list that we should, therefore increasing number of bodies available to our users.
- Found some bodies requiring renaming, mergers etc, helping keep body database up to date. (One of the renames had been incorrect for around 12 years)
- When I couldn't find a dpr entry further research sometimes found the body to be defunct, allowing it to be updated on WDTK and prevent requests going to dead bodies

Separately, it gave me a chance to play with the csv import etc a bit more, as I haven't used it in a while


I'm not suggesting we go through and tag every body, but it's maybe something we can be mindful of when we create new bodies or update existing ones.

**Comment by HelenWDTK** [comment]
https://wdtkwiki.mysociety.org/wiki/Tagging_suggestions
