### ISSUE TITLE
Update the text on the Recruitment to the admin team wiki page

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1298]
Linked to the volunteer recruitment plan #1038 

The update is to replace some out of date text and add in details of the ways that recruitment to admin team can take place,

Proposed text for the update is here https://docs.google.com/document/d/1dfNfRAdSylkkjs2ACe3dctTX09Vf72PNDnYnTOiLFbI/edit#

Please let me know if you have any comments or suggestions 

The plan is to put the update live next week on 26th July

**Comment by sallytay** [comment]
Thank you for all your comments and suggestions - the Wiki page has now been updated.

Please let me know if there are any format changes that would make the page easier to use, or of course feel free to add those yourselves.

**Comment by garethrees** [comment]
Closing as it looks like this has been resolved.
