### ISSUE TITLE
Campaign for expansion of scope of FOI to clearly cover bodies such as the National Fire Chiefs Council 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1299]
https://www.whatdotheyknow.com/body/national_fire_chiefs_council

Further examples 

* ACPO / National Police Chiefs' Council - both were eventually made subject to FOI specifically 
* Cambridge University Bursars' Committee. "The Bursars Committee refused, claiming to be a private club legally distinct from the University and therefore not covered by the FOI Act." ([Reference](https://web.archive.org/web/20061007232941/http://www.gradunion.cam.ac.uk/issues/openness/))

Currently FOI does cover corporate bodies where every member is "a person acting on behalf of a relevant public authority or of a company wholly owned by the wider public sector"
https://www.legislation.gov.uk/ukpga/2000/36/section/6

This could be argued to apply to each of the above cases, however it doesn't appear to be clear-cut, and a counter argument could be made. Clarity in law would be preferable.  

Caution - we don't want to make unions of public sector staff subject to FOI. 

We do want to see bodies discharging public functions subject to FOI in relation to those public functions - such a definition would be along the ["functions of public administration" lines used by the Environmental Information Regulations](https://ico.org.uk/for-organisations/guide-to-the-environmental-information-regulations/what-are-the-eir/#3).

**Comment by garethrees** [comment]
Linking to #1243
