### ISSUE TITLE
Re-order category headings

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1300]
* To improve user-experience with the "Add bodies to batch" interface.

**Comment by RichardTaylor** [comment]
Changed order of Health Bodies:

* Put categories with all members defunct towards the bottom
* Raised the more significant categories.
* Put very large categories: "NHS bodies" and "NHS trusts" at the bottom (to encourage use of more specific sets of bodies)

**Comment by RichardTaylor** [comment]
Listed ambulance services under "Emergency services" as well as Health.

**Comment by RichardTaylor** [comment]
Do we want categories for local/regional health bodies to appear under both Health, and "Local and regional"? 

I think Health alone is probably enough, and has been the general practice.

**Comment by confirmordeny** [comment]
I have done some work on the order of categories.

**Comment by HelenWDTK** [comment]
closing as complete
