### ISSUE TITLE
Body categorisation challenges

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1301]
It might be nice to list eg. The Department for Education under the Education category at 

https://www.whatdotheyknow.com/body/list/all

(and also in the Pro  "Add authorities to batch" system)

Similar for Department for Health under Health etc. 

This could be done via further sub-categories eg. "Central government Health bodies" etc. 

One for discussion. 

Related:

* https://github.com/mysociety/whatdotheyknow-theme/issues/1300

**Comment by garethrees** [comment]
I _think_ the issue here is that we only have a category _heading_ for "Education"?

> This could be done via further sub-categories eg. "Central government Health bodies" etc.

I agree this seems like the best approach.
