### ISSUE TITLE
New Wiki page - FOI Database administrator guide

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1303]
To help the on boarding of new volunteers who are going to concentrating on keeping the bodies database up to date I've made a new Wiki page, with some draft text

The idea behind it is that is is quick guide to be able to find policies and guidance on the tasks related to this. I found when I first started that I spent too long trying to find the information that I was looking so this is just to make this a little easier for people.

The content links to existing resources so if they are updated it won't affect this page.

I'd welcome any thoughts on the content or anything that I've missed that should be on there.

https://wdtkwiki.mysociety.org/wiki/FOI_database_administrator_guide
.

**Comment by WilliamWDTK** [comment]
I've made a few small changed to the Wiki page, mainly formatting, but I've added some more details, and some appropriate categories.

**Comment by sallytay** [comment]
The new page has now been created
