### ISSUE TITLE
Update to Agenda for the Induction call Wiki page

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1304]
When we have been processing new volunteer applications recently, the format seems to have settled into flow where we invite the potential new volunteer for an induction call, which is a 'meet and greet'. 

We then ask for the agreements and policies to be signed and this is generally followed up by a training call, where we show them in more detail how the systems work, once all their admin permissions have been granted.

To follow this approach this I've made two draft call agendas, one for the induction call and one for the training call. Of course there will be some cases where we might do everything in one call, in which case we can just combine them. Both are based on the content of the existing agenda for the induction call

I'd appreciate any thoughts, comments or suggestions you have on these. I'll looking to complete the pages by Tuesday 26th July

Induction call agenda https://docs.google.com/document/d/1awMa6mkI72qUgZNwELmxJGK_qW9QGEYnpVsZChbrJLg/edit#
Training call agenda https://docs.google.com/document/d/1BMOx9ZikKps6nkl159tf0COhlLuFtGspLY1rjykkyI8/edit#

**Comment by WilliamWDTK** [comment]
I've added a few comments and made some changes, though I can see that someone else has done some before me.

A thought:

- What are the criteria for an existing volunteer joining the calls / what is their purpose?

I've often been unavailable at the time of these calls in the past, but I'm also not sure what I can add, so it would (perhaps) be good to document something on this, unless it's a "me" problem.

**Comment by RichardTaylor** [comment]
I've added

>Specifically introduce how we deal with GDPR rights based requests

to the training call agenda in light of https://github.com/mysociety/whatdotheyknow-private/issues/29

**Comment by sallytay** [comment]
Thank you, a good suggestion.

I'll work through al the suggestions today

**Comment by sallytay** [comment]
> A thought:
> 
> * What are the criteria for an existing volunteer joining the calls / what is their purpose?
> 
> I've often been unavailable at the time of these calls in the past, but I'm also not sure what I can add, so it would (perhaps) be good to document something on this, unless it's a "me" problem.

There is no specific criteria currently for an existing volunteer to join the call. The general way it has worked is that anyone on the admin team is welcome to join the call, primarily to meet the potential new volunteer and add anything that you feel relevant to the conversation such as some examples of what you have worked on or your experience as a volunteer 

It is always better to have a least two people on the call, much like you would expect in job interview.

However I appreciate that they are not for everyone and I wouldn't expect everyone to take part.

Happy to look at drawing up some guidance in the future if that would help though.

**Comment by sallytay** [comment]
A quick update.- I've added the new text to the Agenda for the induction call page and will add the new text to the training call page tomorrow.

**Comment by sallytay** [comment]
The content for the training page has now also been added, there's still a bit of format tweaking to complete

**Comment by sallytay** [comment]
This has been updated
