### ISSUE TITLE
Tag university course-related / admission statistics requests

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1306]
Example tags:

- `admission_statistics`
- `course:A100` or `ug_course:A100`

To do:

- Decide tagging
- Add to Wiki
- Start tagging

See:
- #1302

**Comment by FOIMonkey** [comment]
+1 This will be good for when we get tag based notes.

**Comment by mdeuk** [comment]
+1, I've been doing light tagging with some of our more _frequent_ transport related requests, in the hope that it might help people find things more quickly (and reduce requests for the _exact same information_). Whether it works, I'm not sure, but thematic tagging is something I'd love for us to do more of.

Linking to https://github.com/mysociety/alaveteli/issues/4918 - I wonder what a classification AI / bot would 'think' of some of the datasets we have? 🤖

**Comment by WilliamWDTK** [comment]
At my own university, they appear overwhelmingly to be related to A100.

Some looser,  non-accreditated degrees might not have quite a simple 1-1 relationship (eg a course with the same name as mine but at a different university has a completely different course code, only one digit in common).

**Comment by RichardTaylor** [comment]
Just noting the wiki page to note these on is

https://wdtkwiki.mysociety.org/wiki/Request_tags

It might be one for [an automated notice based on the correspondence text](https://github.com/mysociety/alaveteli/issues/34#issuecomment-897510363), rather than relying on manual tagging.

**Comment by HelenWDTK** [comment]
https://wdtkwiki.mysociety.org/wiki/Tagging_suggestions
