### ISSUE TITLE
Volunteer contact form CV questions

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1307]
We've recently had an message through on the form where the person who contacted us appears to have pasted their CV into the form.  This is OK, but not ideal, especially since I think that part of the value of them is the formatting (assessing computer literacy etc), but maybe that's just me.  Perhaps we could extract the CV question, and ask specifically for a link or to wait for our response to send it by email.

We could also have a file upload, though I imagine that complicates the situation somewhat.

Something like this:

![](https://user-images.githubusercontent.com/99501342/180074079-f9bf777c-1af1-48d9-a68f-61a00e05d9d7.png)

**Comment by garethrees** [comment]
Maybe a quicker solution is just to change the text area to a [`url` input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url) with client side [validation](https://stackoverflow.com/a/58071141)?

<img width="671" alt="Screenshot 2022-07-21 at 15 22 16" src="https://user-images.githubusercontent.com/282788/180237869-b490ff52-811a-4979-8774-90c94c71f452.png">

**Comment by WilliamWDTK** [comment]
As something separate from the current big box, or instead?

!["Do you have any previous relevant experience that you could tell us about?" question, explanatory text and text area input field](https://user-images.githubusercontent.com/99501342/180494825-cb4bea29-59bc-4431-9b75-49f0061a5867.png)
