### ISSUE TITLE
Change our decision make approach to reduce conflicts of interest.

### ISSUE THREAD

**Issue by FOIMonkey** [mysociety/whatdotheyknow-theme#1308]
Currently our policy states:

> "Positive agreement between two administrators is sufficient agreement to go-ahead with all but the most risky / controversial actions."

I'm proposing something like: 

> "Positive agreement between two administrators who are not closely related is sufficient agreement to go-ahead with all but the most risky / controversial actions."

This reduces potential conflicts from having two volunteers in the same household able to approve each others actions without wider consultation.

**Comment by garethrees** [comment]
I don't have a problem with this change 😺

**Comment by mdeuk** [comment]
> I don't have a problem with this change 😺

Me either - it seems like a common sense move. 👍

**Comment by RichardTaylor** [comment]
Action taken. Updated https://wdtkwiki.mysociety.org/wiki/Policies#Decision_making_approach
