### ISSUE TITLE
Document a policy for inappropriate/questionable user profile photos

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1309]
We currently don't say much beyond:
![](https://user-images.githubusercontent.com/99501342/180234057-d89dee78-d307-43af-8daf-279663982066.png)

**Comment by garethrees** [comment]
This issue was triggered by a complaint (perhaps our first!) about an inappropriate profile picture.

We now have [a policy page](https://wdtkwiki.mysociety.org/wiki/Profile_picture_policy). I think the complaint that triggered the issue would be covered under the latter of the two bullet points on the uploader page.

**Comment by RichardTaylor** [comment]
I've noted on the new wiki page that the "Set Photo" page states:

: Please don't upload offensive pictures. We will take down images that we consider inappropriate. 

https://www.whatdotheyknow.com/profile/set_photo

While this isn't public it is available to logged in users. It's already a semi-public policy. 

We try to make our policies public as far as we can.  

I think what we have may well be public enough, but we could mention it on the help pages, perhaps as part of the House Rules too.

**Comment by WilliamWDTK** [comment]
The items identified for development on the thread concerned (not necessarily related to the precise issue, though) were:
>Developing a policy for such cases (public: House Rules & uploader / private: Wiki / both), taking the following risks/aspects into account:
>
>- What is offensive/inappropriate?
>- Will we just clear these pictures, warn the user, ban/suspend?
>- What if the image is illegal, or raises concerns of potential illegality elsewhere (I'd say this case doesn't)?
>- What if it causes a concern for the safety of the user or any other person?
>- Copyright: we probably don't want to, and may not be able to, rely on the same arguments we use for copyright in relation to FOI responses.

The following possible risks were noted (for general cases):
>Some images could be illegal, form harassment, hate crimes etc

**Comment by sallytay** [comment]
Note from the discussion on this at the High risk case and policy meeting:

The policy published in the right place is better than policy on help pages
