### ISSUE TITLE
Consider how wiki Template:Tag can be updated

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1313]
I'll do this myself.  I can't assign things to myself, though.

Wording etc.

**Comment by mdeuk** [comment]
> I can't assign things to myself, though.

I have ticketed this up.

**Comment by WilliamWDTK** [comment]
In some sentence situations, having "Bodies tagged `banana`" doesn't fit with the wording.  I've now changed it to use icons.  It's a bit primitive, but hopefully works.

>{{Tag|body|rejects_org_request}} gives "[🏷rejects_org_request🏢](https://www.whatdotheyknow.com/body/list/rejects_org_request)"
>
>{{Tag|request|rejects_org_request}} gives "[🏷rejects_org_request✉](https://www.whatdotheyknow.com/search/tag:rejects_org_request/requests)"
>
>{{Tag||rejects_org_request}} gives "🏷rejects_org_request"
>
>{{Tag|banana|rejects_org_request}} gives ""
>
>{{Tag||}} gives "🏷"
>
>{{Tag|body|}} gives "[🏷🏢](https://www.whatdotheyknow.com/body/list/)"
>
>{{Tag|request|}} gives "[🏷✉](https://www.whatdotheyknow.com/search/tag:/requests)"
>
>{{Tag}} gives ""

**Comment by WilliamWDTK** [comment]
If other volunteers are happy that that is a reasonable solution, we can close this.
