### ISSUE TITLE
Blog on terrible state of most public sector disclosure logs. Also credit any good ones. 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1316]
See 

https://github.com/mysociety/whatdotheyknow-theme/issues/1315#issuecomment-1194772178

Could note how WDTK is already a partial disclosure log, and public bodies could link to it. 

Could note how public bodies could use WDTK, for free, as a disclosure log system by generating [copies of] requests on WDTK and responding to them.

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
