### ISSUE TITLE
Add "Make sure the information you are asking for is not already publicly available" to advice on making responsible requests

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1317]
The text:

>Make sure the information you are asking for is not already publicly available.

is already on the request form for the free, public, site. 

This ticket proposes adding it to 

https://www.whatdotheyknow.com/help/requesting#responsible

which, as following that advice is part of the house rules, will make following it part of our house rules. 

We could insert a new bullet point, as the second bullet, stating:

* **Don't make requests for information which is already published**.  Search WhatDoTheyKnow and the public body's website to check the material you are seeking isn't already available.

**Comment by confirmordeny** [comment]
I agree.
