### ISSUE TITLE
Consider adding private prison providers

### ISSUE THREAD

**Issue by FOIMonkey** [mysociety/whatdotheyknow-theme#1318]
We list providers in Scotland because FOISA covers:

> A person (a)providing services under a contract with the Scottish Ministers for the running of a prison or part of a prison in Scotland; or (b)providing services under a subcontract to a contract of the type specified in (a) above.

https://www.legislation.gov.uk/ssi/2016/139/schedule/2/made

Private providers in rUK are not covered.

We should consider listing them.

The Prison Reform Trust have said:

>Currently, private organisations providing public services are not liable to the same requirements to disclose under FOI. Private prisons are providing the same service as state run prisons. The rights to information about the regimes and establishment should be the same. Prisoners in the main have no choice in whether they are held in a private or state run prison and the rights of people held in these prisons should be equivalent.

https://publications.parliament.uk/pa/cm201213/cmselect/cmjust/96/96vw57.htm

**Comment by RichardTaylor** [comment]
Our policy is to list these 

>we've considered, and pretty much agreed, a policy of listing bodies if they'd be subject to FOI anywhere in the UK.

https://wdtkwiki.mysociety.org/wiki/Criteria_for_listing_public_bodies

I suspect we'll hit  #1320 

Note we have a slightly odd listing for 

https://www.whatdotheyknow.com/body/hm_prison_kilmarnock

which we'll want to review 

Data from 2019

https://www.justice.gov.uk/about/hmps/contracted-out

**Comment by RichardTaylor** [comment]
Spreadsheet 

https://docs.google.com/spreadsheets/d/1vD-nkh4E8SNWlFOsm_edZyQ7TmoLzC_jWKVnK3L0r6Q/edit#gid=0

**Comment by RichardTaylor** [comment]
https://www.whatdotheyknow.com/body?tag=scottish_prison_contractor

**Comment by RichardTaylor** [comment]
As the Scottish Private Prisons have their own special FOI eaail addresses I think we need to keep their separate listings Serco Ltd in respect of HMP Kilmarnock"

**Comment by mdeuk** [comment]
> Our policy is to list these
> 
> > we've considered, and pretty much agreed, a policy of listing bodies if they'd be subject to FOI anywhere in the UK.
> 
> https://wdtkwiki.mysociety.org/wiki/Criteria_for_listing_public_bodies
> 
> I suspect we'll hit #1320
> 
> Note we have a slightly odd listing for
> 
> https://www.whatdotheyknow.com/body/hm_prison_kilmarnock
> 
> which we'll want to review

That listing is probably accurate - we're listing the correct operator (Serco Ltd is the usual trading entity of the contractor); however, we ought to check if there is any merit in listing the PFI holder - Kilmarnock Prison Services Limited.

We already list the other private prison in Scotland - HMP Addiewell - through its contract operator ([Sodexo Justice Services](https://www.whatdotheyknow.com/body/hm_prison_addiewell)), and the PFI entity ([Addiewell Prison Limited](https://www.whatdotheyknow.com/body/addiewell_prison_limited)). Sodexo is listed with short name HM Prison Addiewell, as this is the entity that would hold the _day to day_ records.

**Comment by mdeuk** [comment]
Serco:
<img src="https://user-images.githubusercontent.com/249418/181328375-9feeb51a-0108-46a3-a615-94136651cbb4.png" alt="Screenshot from the HM Prison Kilmarnock website, which states 'We would also recommend making use of the webpage of the information rights group WhatDoTheyKnow to submit and track your FOI requests.'" width="500px">
I like the last bit 😃

**Comment by mdeuk** [comment]
> As the Scottish Private Prisons have their own special FOI email addresses I think we need to keep their separate listings. I propose changing the body names to eg. "Serco Ltd in respect of HMP Kilmarnock"

Agreed - this also makes sense based on the legislative differences, e.g. that there is _**definite**_ coverage under FoISA and EI(S)R for that entity, whereas others are far from clear as the legislation isn't so coherent.

**Comment by HelenWDTK** [comment]
Closing as the proposals has been duly considered.
