### ISSUE TITLE
Policy on listing a group of companies

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1320]
Sometimes a company operates as, and presents itself to the public as "X Group". 

It's often hard to find out exactly which company within the group is doing what. 

Often the group shares a website and a contact address. 

We already have a related policy on listing subunits of public bodies, this is in some respects the inverse of that. 

A group probably isn't subject to FOI, it will be the relevant specific company within the group. We like to list, and send requests to, specific legal entities which are subject to FOI (or which we think should be subject to FOI). 

As usual we should consider what best serves our users, and what's practical, proportionate and maintainable. 

Proposal:
>Where a group of companies operates as, and presents itself to the public as, "X Group" we can list the group as an authority on WhatDoTheyKnow. We can mention any specific companies in the group in the notes. If a group shares a website and a contact address that is a factor in favour of listing them as a group. 

Counter example: If a specific company in a group has a key contract with the public sector which makes it subject to FOI, eg. it runs GP surgeries, then we may want to list the specific company that holds the contract in question. 

If agreed we can note the policy at: 
https://wdtkwiki.mysociety.org/wiki/Policies#Public_authority_records

**Comment by RichardTaylor** [comment]
See https://www.whatdotheyknow.com/body/care_plus_group for an example, should we separately list and link all the subsidiaries?  What should the body name be?

**Comment by confirmordeny** [comment]
I think that would be a good policy providing people could continue to add companies from the group.

**Comment by confirmordeny** [comment]
There is an argument for adding the Crown to the site as an experiment.

**Comment by RichardTaylor** [comment]
Another example to consider 

https://www.whatdotheyknow.com/body/grosvenor

**Comment by confirmordeny** [comment]
Now done: https://wdtkwiki.mysociety.org/wiki/Authorities_not_subject_to_FOI_policy#Entities_that_are_not_legal_persons
