### ISSUE TITLE
Add links to other mySociety services on body pages

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1321]
Ideas for a body page eg. 

https://www.whatdotheyknow.com/body/aberdeen_city_council

* [Read mentions of Aberdeen City Council in Parliament via TheyWorkForYou.](https://www.theyworkforyou.com/search/?q=%22Aberdeen+City+Council%22) ([#1332](https://github.com/mysociety/whatdotheyknow-theme/issues/1332))
* [View a map of the Aberdeen City Council area via MapIt](https://mapit.mysociety.org/area/2650.html) ([#818](https://github.com/mysociety/whatdotheyknow-theme/issues/818))
* [UK Climate Action Plan Explorer: Aberdeen City Council](https://data.climateemergency.uk/councils/aberdeen-city-council/) ([#1331](https://github.com/mysociety/whatdotheyknow-theme/issues/1331))

**Comment by RichardTaylor** [comment]
Linking to WriteToThem would be nice, but we'd need an appropriate landing page on that site. I don't think there is a council page on WriteToThem.  You can link to an example postcode for a council area but the page reached will be for a specific ward not the whole council.

**Comment by garethrees** [comment]
I've created specific issues for each of the suggestions as they each have their own implementation concerns. Happy for this to continue existing as a bucket for collecting them all together and stubbing out ideas.

**Comment by garethrees** [comment]
I think this would warrant improving the organisation of the sidebar (very quick spike just to demonstrate gist of idea).

![Screenshot 2022-08-03 at 12 45 15](https://user-images.githubusercontent.com/282788/182600104-2e15c40c-f28a-4fe6-8095-d71e448c6573.png)

**Comment by garethrees** [comment]
Linking to https://github.com/mysociety/whatdotheyknow-theme/issues/1391

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
