### ISSUE TITLE
Document Derry/Londonderry body naming policy

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1322]
Essentially:

- Use "Derry/Londonderry"
- If we get a complaint or request to change it to one of "Derry" or "Londonderry", do so.  If we discover that a particular institution uses one form rather than another, use that form.  Proactive research into preferred form is not generally undertaken, due to the number of bodies already present in the database which would need time-consuming manual review.

**Comment by RichardTaylor** [comment]
>If we get a complaint or request to change it to one of "Derry" or "Londonderry", do so.

Presumably limited to cases where there is a good reason such as one name or the other being in the body's official name.

**Comment by confirmordeny** [comment]
I have started something here: https://wdtkwiki.mysociety.org/wiki/Naming_of_public_authorities_policy#Derry.2FLondonderry

**Comment by confirmordeny** [comment]
I think the policy is OK for now. Please consider closing the issue.

**Comment by sallytay** [comment]
I think that policy should work and everyone seems comfortable with it. - we can always add to it at a later date if we need to. I'll close this.
