### ISSUE TITLE
Replace `, Londonderry` at the end of Northern Irish schools' names with `, Derry/Londonderry`

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1323]
See:
#1322

**Comment by WilliamWDTK** [comment]
Consider reviewing other bodies, but we don't want to change those automatically.  Schools, we perhaps could.

**Comment by confirmordeny** [comment]
I have started doing this.

**Comment by confirmordeny** [comment]
I have made this change for all of the schools.

**Comment by confirmordeny** [comment]
I think this can be closed.
