### ISSUE TITLE
merge City of London and Common Council authorities

### ISSUE THREAD

**Issue by confirmordeny** [mysociety/whatdotheyknow-theme#1324]
We should reconsider merging the City of London and the Common Council of the City of London authorities. We originally added the common council because it is named in schedule 1 of the Freedom of Information Act 2000 we then later added the City of London because we felt other areas sometimes called "city cash" should not escape scrutiny.I know how we got here but we have two bodies that are both tagged as local authorities with the same identifier. Is it time to merge these? I would propose we use the City Of London name for the merged authority.

**Comment by HelenWDTK** [comment]
+1 To this - I find it confusing when doing batch requests to have the COL listed twice.

**Comment by WilliamWDTK** [comment]
The requests have now all been moved by devs. This was not done manually due to the quantity.

**Comment by WilliamWDTK** [comment]
Do we want to delete the [Common Council of the City of London](https://www.whatdotheyknow.com/body/common_council_of_the_city_of_london) ([body 595](https://www.whatdotheyknow.com/admin/bodies/595))?

**Comment by confirmordeny** [comment]
I have removed the email address but left as a signpost. People who have read Schedule 1 of the Act might look under this name: https://www.whatdotheyknow.com/body/common_council_of_the_city_of_london

**Comment by WilliamWDTK** [comment]
>People who have read Schedule 1 of the Act might look under this name

I somehow doubt there are very many people that use Schedule 1 as their starting point.

But it does also have the benefit of not breaking links.

**Comment by WilliamWDTK** [comment]
Do we want to tag duplicate requests that may now exist (or all transferred requests), to add a tag-based note?

**Comment by WilliamWDTK** [comment]
I've sent a message to the City of London letting them know what we've done

**Comment by confirmordeny** [comment]
Thank you
