### ISSUE TITLE
remove House of Commons Administration Committee (and move requests to the House of Commons)

### ISSUE THREAD

**Issue by confirmordeny** [mysociety/whatdotheyknow-theme#1325]
We added the House of Commons Administration Committee to the site when a request to the House of Commons was refused and the following reason was given:

_"This information is not held by the House of Commons.  The process of managing and administering media passes is managed on behalf of the Administration Committee. "_

https://www.whatdotheyknow.com/request/press_accreditation_2

That was back in October 2013. By October 2014, the House of Commons wrote to the requester to say:

_"It has come to our attention that our response of 14 October 2013 has caused some confusion.

The Administration Committee is a select committee of the House of Commons and is not a separate public authority."_

I understand why we did what we did back around a decade ago but it is now time to reconsider?

**Comment by RichardTaylor** [comment]
We could remove the email address from the House of Commons Administration Committee and update the notes to point users to the House of Commons. 

This would enable us to retain the history of what happened. 

(Interest: At least one of the requests in question on to the committee is one I made).

**Comment by RichardTaylor** [comment]
New proposal in light of the new "notes" feature:

Move all the requests currently under /body/house_of_commons_administration_committee to /body/house_of_commons and add a note to each of them saying :

>This request was originally made specifically to the House of Commons Administration Committee. We listed the committee separately for a period because [a previous request for information to the House of Commons was rejected on the grounds that the information is held by the Committee](https://www.whatdotheyknow.com/request/press_accreditation_2). We understand this issue has now been resolved and information held by House of Commons Committees is currently available via requests to the House of Commons.   

Also update

https://www.whatdotheyknow.com/body/house_of_commons

accordingly, and mention the fact requests for information from committees of the House of Commons can be made there.

**Comment by confirmordeny** [comment]
I have made the Committee page into a 'signpost' authority:
https://www.whatdotheyknow.com/body/house_of_commons_administration_committee

**Comment by confirmordeny** [comment]
I added a note to the House of Commons authority page also.
