### ISSUE TITLE
Put Welsh translated category names in the system

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1333]
The Welsh Government has helpfully translated some of our category names into Welsh for us. 

The WDTK system takes Welsh translations, we just need to put them in. 

There are about 100 category names / descriptions which have been translated 

The translated file is at

https://docs.google.com/document/d/1S6ng96vFb_cqkt-rnI3-gZ3USzW5RM9ccGSlYd0GwYc/edit

This might be a good thing to do as a team as doing 100 copy and pastes alone could be tedious. (I don't think it can be easily automated by non-developers).

**Comment by mdeuk** [comment]
I’m happy to do it - the list was a copy and paste to begin with, sadly.

Diolch yn fawr! 🏴󠁧󠁢󠁷󠁬󠁳󠁿

**Comment by RichardTaylor** [comment]
Reported all done via Slack.

**Comment by mdeuk** [comment]
> Reported all done via Slack.

Indeed! And we've [tweeted about it too](https://twitter.com/WhatDoTheyKnow/status/1554833771567804417) - I'm very much a fan of Helo Blod! 🏴󠁧󠁢󠁷󠁬󠁳󠁿
