### ISSUE TITLE
Categories for tags of form `parent_mapit:AREA_ID`

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1334]
Example where such a category has been created:

https://www.whatdotheyknow.com/body/list/parent_mapit:2595

now links to a page titled:

> Found 108 public authorities in the category ‘Bodies in the Powys Council Area’ "

and body pages state eg. 

>Abbey Cwm-hir Community Council

>[A town or parish council](https://www.whatdotheyknow.com/body/list/parish_council) and [a body in the Powys Council area](https://www.whatdotheyknow.com/body/list/parent_mapit:2595) ([admin](https://www.whatdotheyknow.com/admin/bodies/139694))

## Situation without categories ##
Without a category associated with a tag a link is eg.

https://www.whatdotheyknow.com/body?tag=parent_mapit%3A2597

and the title is eg.

> Found 2 public authorities matching the tag ‘parent_mapit:2597’ 

and there's no prominent link from body pages to the list

## Implementation 

Actioning this would practically require a developer to add the category names and descriptions in bulk

A non-developer could prepare a spreadsheet of category names, tags, and descriptions for upload.

**Comment by RichardTaylor** [comment]
Should we use the word body, organisation, or authority. Authority is the one we use publicly in text on the site, though our URLs contain "body". 

>[a body in the Powys Council area](https://www.whatdotheyknow.com/body/list/parent_mapit:2595)

>[an organisation in the Powys Council area](https://www.whatdotheyknow.com/body/list/parent_mapit:2595)

>[an authority in the Powys Council area](https://www.whatdotheyknow.com/body/list/parent_mapit:2595)

I propose using "authority", though I think "organisation" is the most natural term for me. 

I've updated

https://www.whatdotheyknow.com/body/list/parent_mapit:2595

and

https://www.whatdotheyknow.com/body/list/parent_mapit:152225

**Comment by confirmordeny** [comment]
The term "public authority" work well for individuals e.g. GPs and coroners. It is also consistent with the EIR and with FOI law.

**Comment by garethrees** [comment]
> Should we use the word body, organisation, or authority

Linking to #1345

**Comment by HelenWDTK** [comment]
https://wdtkwiki.mysociety.org/wiki/Tagging_suggestions

**Comment by confirmordeny** [comment]
This was done. See for example: https://www.whatdotheyknow.com/body/adstone_parish_meeting

I will close as complete.
