### ISSUE TITLE
Consider policy on rate capping - if we had more options for finer control of rate caps

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1335]
Ticket for the feature in the software:

* https://github.com/mysociety/alaveteli/issues/7207

If we had the option would we set a weekly cap lower than 7 times the daily cap, or a monthly cap lower than ~30 times the daily cap?

Would we reduce the cap below its current level for those who have misused the service?

**Comment by RichardTaylor** [comment]
>If we had the option would we set a weekly cap lower than 7 times the daily cap, or a monthly cap lower than ~30 times the daily cap?

I think we should do this as we have had a number of cases on WhatDoTheyKnow where people have been making requests up to the daily limit every day for many days.

>Would we reduce the cap below its current level for those who have misused the service? 

I can envisage using this on rare occasions.  eg. to limit a warned user to one more request, and if that's in breach of our rules we'd ban.

**Comment by HelenWDTK** [comment]
We don't yet have the ability to do this, and we tend to try to avoid debating hypotheticals (though not always successfully). We can revisit this if https://github.com/mysociety/alaveteli/issues/7620 is ever implemented.

**Comment by WilliamWDTK** [comment]
Rate limiting has been changed in https://github.com/mysociety/alaveteli/pull/8859

(Mentioned in https://github.com/mysociety/whatdotheyknow-private/issues/415)
