### ISSUE TITLE
Document threshold (if there is one) for notes being "important" and the body being tagged `important_notes`

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1336]
Also consider documenting somewhere what the `important_notes` tag does. @RichardTaylor suggests that it "presents the notes to the user on the pro request page, and think in the batch picker too".

**Comment by HelenWDTK** [comment]
Have added some notes to https://wdtkwiki.mysociety.org/wiki/Tagging_policy - I don't think it's possible to set a threshold, as it would be a judgement call based on the circumstances. I'd personally see it as being for things that have a likelihood of materially impacting whether you get a response, or the time taken to respond, and not for things like extra information about how a body is constituted or the powers that it has. I am not sure precisely how it works, but I imagine that if you were making a batch request to 200 councils and all the council notes were displayed, the page would probably be unusable.
