### ISSUE TITLE
Royal Trustees

### ISSUE THREAD

**Issue by confirmordeny** [mysociety/whatdotheyknow-theme#1337]
Should we add the Royal Trustees to the site?

https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/972623/Royal_Trustees_Report_21-22.pdf

**Comment by RichardTaylor** [comment]
Yes. 

Notes could be based on the linked document:

>The Royal Trustees are the body which determines the annual grant of public money to the monarch, as provided for by the [Sovereign Grant Act 2011](https://www.legislation.gov.uk/ukpga/2011/15/contents).
>
>The Royal Trustees were established by [section 10 of the Civil List Act 1952](https://www.legislation.gov.uk/ukpga/Geo6and1Eliz2/15-16/37/section/10). The members of the body are the Prime Minister, the Chancellor of the Exchequer and the Keeper of the Privy Purse. The Keeper of the Privy Purse is a royal household official[*](https://discovery.nationalarchives.gov.uk/details/r/C232).

**Comment by RichardTaylor** [comment]
Note

https://www.gov.uk/government/organisations/royal-trustees-office

>Royal Trustees' Office has closed

>The Royal Trustees were responsible for reviewing and reporting on Civil List expenditure. As of 2012, funding for the monarch comes from the Sovereign Grant. The Grant is now subject to audit and review by the Auditor and Comptroller General.

This could usefully make clear the Royal Trustees continue to exist.

**Comment by RichardTaylor** [comment]
Listed:

https://www.whatdotheyknow.com/body/the_royal_trustees

**Comment by confirmordeny** [comment]
Thank you.
