### ISSUE TITLE
Clear outstanding "reported for administrator attention" flags on requests relating to a missuse issue

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1338]
Following the misuse described at 

https://www.mysociety.org/2022/03/09/freedom-of-information-requests-around-the-academic-status-of-dr-tsai-ing-wen/

There are still threads left with unresolved requires_admin flags.

/admin indicates there should only be ~30 of them. 

These need classifying appropriately.

**Comment by RichardTaylor** [comment]
Suggestion action via the admin interface to avoid messages being sent to users.

**Comment by HelenWDTK** [comment]
Closing as complete
