### ISSUE TITLE
Recruit a native Welsh-speaking volunteer

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1339]
This could be something for targeted recruitment via the job board.

Ideally native, or fluent if not.

Possibly just someone to translate / consult on Welsh-related matters, but even better if they're interested in volunteering in a broader way.

**Comment by sallytay** [comment]
I think this is a great idea for targeted volunteer recruitment, something we can look at when this current round has finished.

**Comment by garethrees** [comment]
Note that IME there are many arguments around the "correct" Welsh to use depending on the region of the speaker (particularly North vs South 😧). Better than our current situation at least.

We did at one point have someone doing this. Could reach out to see if they're interested in returning.

**Comment by WilliamWDTK** [comment]
- [https://thirdsectorsupport.wales/app/uploads/2021/02/Attracting-Welsh-Speaking-Volunteers.pdf](https://thirdsectorsupport.wales/app/uploads/2021/02/Attracting-Welsh-Speaking-Volunteers.pdf)
- [https://volunteering-wales.net/index.htm](https://volunteering-wales.net/index.htm): includes from-home volunteering and has a section for Welsh-language roles.  It could be a good way to specifically target Welsh speakers.
- [https://thirdsectorsupport.wales/app/uploads/2021/02/Promoting-Welsh-Language-Through-Volunteering.pdf](https://thirdsectorsupport.wales/app/uploads/2021/02/Promoting-Welsh-Language-Through-Volunteering.pdf)

**Comment by garethrees** [comment]
Note that Rails has pulled it's `.cy` locale files because they can't find a volunteer to translate them (https://github.com/svenfuchs/rails-i18n/issues/1006#). These translate some [basic interface](https://github.com/svenfuchs/rails-i18n/blob/3c4a77af98f43025d0a21a981e61ffbc07c27b6d/rails/locale/cy.yml) text. Would be a good place to start.

**Comment by HelenWDTK** [comment]
Nid oes cynlluniau i wneud ymgyrch recriwtio gwirfoddolwyr wedi'i thargedu ar hyn o bryd. Rwyf wedi ychwanegu nodyn am sgiliau iaith Gymraeg i'r dudalen wici berthnasol, i sicrhau bod y mater hwn yn cael ei ystyried.
