### ISSUE TITLE
Build capacity to respond to takedown requests so we can continue to publish material when it is in the public interest to do so

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1340]
There has been some action on this to-date including seeking to recruit a legally focused trustee. 

Actions on this point could include:

* Fundraising
* Seeking insurers/underwriters/partners 
* Making connections with, and working with, organisations who are more adept at using the courts than we are
* Planning for responses to situations we expect might occur

**Comment by confirmordeny** [comment]
I support the intent behind this. It isn't a typical GitHub issue though.
