### ISSUE TITLE
Decide if to list freeport governance bodies, and if so list them comprehensively  

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1341]
eg. 

https://www.freeporteast.com

>Freeport East is a partnership between Hutchison Ports, Harwich Haven Authority, New Anglia LEP, South East LEP, Essex County Council, Suffolk County Council, East Suffolk Council, Tendring District Council, Babergh and Mid Suffolk Councils and the Haven Gateway Partnership.

It will not be subject to FOI due to the presence of non-public bodies as partners. 

It, and other freeport bodies might be subject to EIR

We have a list of announced freeport locations 
>Today, I can announce the eight freeport locations in England: East Midlands airport; Felixstowe and Harwich; Humber; Liverpool city region; Plymouth; Solent; Thames; and Teesside.

https://hansard.parliament.uk/commons/2021-03-03/debates/C8618796-C14D-4695-8DC0-20BC6C6DDED4/FinancialStatement

See also

* https://github.com/mysociety/whatdotheyknow-theme/issues/1114

**Comment by confirmordeny** [comment]
I would add them.

**Comment by RichardTaylor** [comment]
The bodies we want to list are known as freeport governance bodies. See eg. Para 4.3.2 at https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/935491/Freeports_Bidding_Prospectus_final.pdf 

I've edited the title here accordingly. 

Para 4.3.1 of that document states:

>The government does not require bidders to have formal governance in place at the point when they bid, or win. However, it expects and encourages Freeport bidding coalitions to form informal steering groups to help bring involved parties together, delegate the work of completing specific requirements, and shape bids collaboratively.

We should decide if we want to list bodies formed to apply to become freeport governance bodies before they are anointed as freeport governance bodies. 

The eight designated freeports have been provided for in legislation:

https://www.legislation.gov.uk/primary+secondary?title=freeport%20designation

The regulations define the areas for the freeports, and name and define sites within each freeport, but they do not identify their governance bodies.  

If we could make FOI requests as the WhatDoTheyKnow team we could request the identities of current Freeport Governance Bodies from the Department for Levelling Up, Housing and Communities and/or the Treasury, along with copies of their governance documents and contact email addresses.

**Comment by RichardTaylor** [comment]
>Bidders set out the proposed membership for their Governance Body in their bids. As stated in the Prospectus, final governance structures will be agreed between bidders and HMG.

https://www.theyworkforyou.com/wrans/?id=2021-03-08.164432.h

**Comment by garethrees** [comment]
Some discussion of freeports & charter cities https://bylinetimes.com/2022/08/15/beware-the-charter-cities-conspiracy-theory/

**Comment by RichardTaylor** [comment]
>The bodies we want to list are known as freeport governance bodies

A "Responsible Authority" has been appointed in respect of a number of free ports, under 

https://www.legislation.gov.uk/ukpga/1979/2/part/VIIIA

These bodies are identified in legislation 

https://www.legislation.gov.uk/primary+secondary?title=%22Free%20Zone%22 

They may be given responsibilities eg. 

https://www.legislation.gov.uk/uksi/2022/1048/article/5/made

We could list these, those currently in-place appear to be:

| Free Zone Name  | Responsible Authority | Legislation link | Existing WDTK link if on WDTK |
| ------------- | ------------- |------------- |------------- |
| Customs Site No. 1 Teesside | Casper Shipping Limited | https://www.legislation.gov.uk/uksi/2022/1049/made | Not listed |
| Customs Site No. 1 Thames | P&O Ferrymasters Limited | https://www.legislation.gov.uk/uksi/2022/1049/made |Not listed |
| Customs Site No. 1 Plymouth | Devonport Royal Dockyard Limited | https://www.legislation.gov.uk/uksi/2022/1048/article/4/made |Not listed |
| Customs Site No. 1 Felixstowe | The Felixstowe Dock and Railway Company | https://www.legislation.gov.uk/uksi/2022/1047/article/4/made |Not listed |
| Customs Site No. 1 Solent | Solent Gateway Limited | https://www.legislation.gov.uk/uksi/2022/915/article/4/made |Not listed |

Responsibilities which we might consider state/public functions include requirements to:

* (j)take reasonable steps to ensure that no unauthorised activity is carried out in the free zone;

* (k)take reasonable steps to ensure that any goods specified in a notice made under regulation 18C(2) (free zone businesses – conditions) of the Special Procedures Regulations are not brought into the free zone;

* (l)take reasonable steps to ensure that no goods leave the free zone otherwise than in circumstances where their removal would be in accordance with provision made by or under the Taxation (Cross-border) Trade Act 2018(2);

* (m)take reasonable steps to ensure that persons carrying out any activities in the free zone comply with any customs obligation related to the free zone;

It is not clear to me if these bodies are the "governance bodies" or if they are organisations with operational powers rather than governance responsibilities.

**Comment by HelenWDTK** [comment]
https://wdtkwiki.mysociety.org/wiki/Authority_suggestions
