### ISSUE TITLE
Adopt a policy of making FOI requests copies of letters to data subjects informing them of bulk data protection breaches made via WhatDoTheyKnow

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1342]
In the interests of protecting our reputation and that of FOI itsself we could check to see if such letters are accurate and informative. 

There is a risk we could draw more attention to such breaches damage the reputation of FOI. 

We could only make such requests where we have concerns about the content of the letters, that might be more proportional than a  policy to make routine requests. 

We want to do what we can to prevent data breaches. 

Related:

* https://github.com/mysociety/whatdotheyknow-theme/issues/1243
* https://github.com/mysociety/whatdotheyknow-theme/issues/1128
* https://github.com/mysociety/whatdotheyknow-theme/issues/1017

**Comment by HelenWDTK** [comment]
Having tried this in a few cases, the response has been to refuse to release it citing the health and safety exemption. There are no plans to implement this at this time, but we can consider this on a case by case basis if we suspect there to have been an issue.
