### ISSUE TITLE
Update text on Why do we remove email addresses and mobile phone numbers from responses?

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1344]
We have two sections on different pages that refer to the automatic removal of email addresses and mobile phone numbers from the site

Section: https://www.whatdotheyknow.com/help/officers#mobiles
States
If you need to know what an address was that we’ve removed, please get in touch with us. Occasionally, an email address forms an important part of a response and we will post it up in an annotation. Our volunteer team doesn’t have the capacity to deal with large numbers of requests to reveal email addresses so currently our service is not suited to requests for email contact details.

The last line was added in relation to ticket https://github.com/mysociety/whatdotheyknow-theme/issues/363 

Section: https://www.whatdotheyknow.com/help/how#email_addresses
States 
Because our service automatically redacts email addresses and mobile phone numbers from responses, it isn’t well suited to making requests for contact email contacts — but if you need to know an address that we’ve removed, please [get in touch](https://www.whatdotheyknow.com/help/contact) with us. Occasionally, an email address forms an important part of a response and if we’re asked to reveal it we may post it in an annotation.

Could we amend the text at https://www.whatdotheyknow.com/help/how#email_addresses to say:

Our service automatically redacts email addresses and mobile phone numbers from responses, if you need to know an address that we’ve removed, please [get in touch](https://www.whatdotheyknow.com/help/contact) with us. However our volunteer team doesn’t have the capacity to deal with large numbers of requests to reveal email addresses so currently our service is not suited to requests made to specifically ask for email contact details.

Occasionally, an email address forms an important part of a response and if we’re asked to reveal it we may post it in an annotation.

**Comment by mdeuk** [comment]
> Could we amend the text at https://www.whatdotheyknow.com/help/how#email_addresses to say:
> 
> Our service automatically redacts email addresses and mobile phone numbers from responses, if you need to know an address that we’ve removed, please [get in touch](https://www.whatdotheyknow.com/help/contact) with us. However our volunteer team doesn’t have the capacity to deal with large numbers of requests to reveal email addresses so currently our service is not suited to requests made to specifically ask for email contact details.
> 
> Occasionally, an email address forms an important part of a response and if we’re asked to reveal it we may post it in an annotation.

I wonder if this, perhaps, introduces some duplication of what's in the previous paragraph.

I've taken a stab at simplifying it a little - @sallytay, does this amended version make sense?

"To guard all parties against spam, and to encourage keeping all correspondence on WhatDoTheyKnow, we automatically remove most email addresses and some mobile numbers from responses to requests. For technical reasons we don’t always manage to remove them from attachments, such as certain PDFs.

If you need to know an address that we've removed, please [get in touch with us](https://www.whatdotheyknow.com/help/contact). It's worth noting though, that as our team is small, we've not got the capacity to deal with a large number of these requests, so our service isn't currently well suited to being used to gather email addresses.

Occasionally, an email address forms an important part of a response and if we’re asked to reveal it, we may post it in an annotation."

**Comment by sallytay** [comment]
@mdeuk yes the amended version does make sense

**Comment by mdeuk** [comment]
> @mdeuk yes the amended version does make sense

Great! I've pushed this as https://github.com/mysociety/whatdotheyknow-theme/pull/1327/commits/017b2649ec2de03804892c6509ca99e298c20f4b (added onto PR #1327).
