### ISSUE TITLE
Wiki page on refuge addresses 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1351]
See

https://groups.google.com/a/mysociety.org/g/wdtk-volunteers/c/sAGe-cD8XfA

**Comment by confirmordeny** [comment]
I have started a policy on this here: https://wdtkwiki.mysociety.org/wiki/Policy_on_refuges

**Comment by confirmordeny** [comment]
Addressed hereL https://wdtkwiki.mysociety.org/wiki/Sensitive_addresses_and_locations_policy
