### ISSUE TITLE
Add a glossary to the site's help pages

### ISSUE THREAD

**Issue by confirmordeny** [mysociety/whatdotheyknow-theme#1353]
Suggested text here: https://wdtkwiki.mysociety.org/wiki/Glossary

**Comment by garethrees** [comment]
This is fantastic!

**Comment by mdeuk** [comment]
> This is fantastic!

Agreed, this is a fabulous body of work, thanks for kicking it off, @confirmordeny!

I wonder if we could use something like [Tocbot](https://tscanlin.github.io/tocbot/) to make it easily accessible for browsing users? This might have the handy benefit of also resolving #878.

**Comment by confirmordeny** [comment]
A question for the coders ... what format would you want this in? For example, I know that html has special tags for glossaries <dl>, <dd> and <dt>. I think I would be able to put the glossary in that format if it would help.

**Comment by confirmordeny** [comment]
I have created a file here - it isn't perfect but I have taken in about as far as I can: 
https://github.com/confirmordeny/whatdotheyknow-theme/blob/confirmordeny-work-in_progress-2/lib/views/help/glossary.html.erb

**Comment by confirmordeny** [comment]
This has been published: https://www.whatdotheyknow.com/help/glossary :)
