### ISSUE TITLE
Dealing with old external identifiers

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1355]
For example, old URNs where a maintained school turns into an academy of the same name.  Both from a tagging, search and display perspective (multiple links with the same name looks odd, and isn't easily understandable).

This situation might occur anywhere we are linking to some external source, although often we might want to create new bodies anyway.

We could establish a policy of a 1:1 relation between WDTK bodies and records in selected external databases deemed authoritative.

**Comment by mdeuk** [comment]
> For example, old URNs where a maintained school turns into an academy of the same name. Both from a tagging, search and display perspective (multiple links with the same name looks odd, and isn't easily understandable).

The approach previously used with NHS bodies was to use a 'predecessor' tag (e.g. body [52346](https://www.whatdotheyknow.com/admin/bodies/52346)) - so we could perhaps introduce the concept of a predecessor and successor tag on the old and new bodies, which would then allow us to render a slightly more helpful link between the two.

This might be one where we would want to use the upcoming feature discussed in https://github.com/mysociety/alaveteli/issues/387 to render something automatically in the public body notes - which could have the happy benefit of rendering a "this body has closed, here's where to find the replacement" style note automatically on the predecessor, making for a slicker user experience.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
