### ISSUE TITLE
Review and improve volunteer account policies

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1356]
Just grouping together some related issues:

* https://github.com/mysociety/whatdotheyknow-private/issues/30
* https://github.com/mysociety/whatdotheyknow-theme/issues/1213
* https://github.com/mysociety/whatdotheyknow-theme/issues/1028
* https://github.com/mysociety/whatdotheyknow-private/issues/55
* https://github.com/mysociety/whatdotheyknow-theme/issues/1343
* https://github.com/mysociety/whatdotheyknow-private/issues/11
* https://github.com/mysociety/internal/issues/65
* https://github.com/mysociety/sysadmin/issues/1388
* https://github.com/mysociety/sysadmin/issues/1167

**Comment by HelenWDTK** [comment]
Closing this in favour of the remaining individual tickets. We can add a milestone if we want to link stuff up again, but it has sat here a while with no engagement, so seems stale.
