### ISSUE TITLE
Translate `lib/views/general/_responsive_footer.html.erb` to Welsh

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#1358]
> I suppose the one thing we could do that's very minimal but quite powerful is add "Established 2008" to the footer to demonstrate that longevity? I've done that in https://github.com/mysociety/whatdotheyknow-theme/pull/1357.

_Originally posted by @garethrees in https://github.com/mysociety/whatdotheyknow-theme/issues/934#issuecomment-1219393829_

The footer isn't translated at the moment, which looks odd when viewed on [/cy](https://www.whatdotheyknow.com/cy) 🏴󠁧󠁢󠁷󠁬󠁳󠁿  - we ought to correct that.

**Comment by garethrees** [comment]
Oh yeah!

This would need #514 so that the translation strings could be added.

**Comment by mdeuk** [comment]
> Oh yeah!
> 
> This would need #514 so that the translation strings could be added.

Either that or we do it the way we've done the help pages… not that I'd advocate that solution, the binfire that is #1327 shows why it isn't always a grand idea.

I'll have to get my head around Transifex.

**Comment by garethrees** [comment]
I _believe_ only the help pages work with the localised filename; other partials don't.

**Comment by mdeuk** [comment]
> I _believe_ only the help pages work with the localised filename; other templates don't.

I'm not sure what templates will honour it - but I checked on sandbox this morning, and popping a localised version into [/lib/views/general](https://github.com/mysociety/whatdotheyknow-theme/tree/master/lib/views/general) worked.

If we're content with the wording, I could work up a Helo Blod request to have it professionally translated?

**Comment by garethrees** [comment]
Sorry, I don't want us to go down the route of having a bunch of different ways of translating view templates. The way help pages are done makes them too difficult to update (https://github.com/mysociety/alaveteli/issues/3075) and I don't want to introduce of that maintenance burden.

**Comment by mdeuk** [comment]
> Sorry, I don't want us to go down the route of having a bunch of different ways of translating view templates. The way help pages are done makes them too difficult to update ([mysociety/alaveteli#3075](https://github.com/mysociety/alaveteli/issues/3075)) and I don't want to introduce of that maintenance burden.

Happy to agree on maintainability (although, one could argue the footer isn't really an issue - it gets roughly [one change a year](https://github.com/mysociety/whatdotheyknow-theme/commits/master/lib/views/general/_responsive_footer.html.erb)). The current help page translations are a nuisance to maintain.

The current /cy homepage is, unfortunately, pretty poor as it is a confusing mix of English with a couple of Welsh strings interspersed. These, of course, come upstream from Alaveteli itself.

If we _**were**_ looking to use Transfiex here (#514), where might be the best place to start?

**Comment by garethrees** [comment]
> If we _**were**_ looking to use Transfiex here (#514), where might be the best place to start?

Exactly there (#514)! https://github.com/mysociety/whatdotheyknow-theme/issues/514#issuecomment-1220457763

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
