### ISSUE TITLE
Establish tagging guidance for NHS bodies / GPs etc

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1360]
A user has contacted us wanting to help add GPs to our database.  In order to produce some good and comprehensive instructions, we should consider what tags we want on such bodies.

Starting list for consideration and amendment:
`nhs`
`surgery`
`hscr`
`dpr:[number]`
`cqc:[REF]`
`NHSODSID:[REF]`
`NHSORG:[REF]`
`run_by:[COMPANY SLUG]`
`nhsorg:[REF]`
`nhsorgid:[REF]`
`[COUNTY/TOWN/LOCATION]`
`nhs111`
`urgent_care`
`ch:[COMPANY NUMBER]`
`limited`
`company`
`NHSChoicesID:[REF]`
`nhs_service_provider`

**Comment by mdeuk** [comment]
A couple of thoughts:

|Tag                                 |  What does it do                                        | Retain?              |
| ------------------------- | --------------------------------------------- |  -----------------|
| `NHSChoicesID:[REF]`   | This refers to the former NHS Choices website. There is equivalent codes for the NHS [Services Near You](https://www.nhs.uk/nhs-services/services-near-you/) page | ❓ |
| `NHSORG:[REF]` <br> `nhsorg:[REF]` | These refer to the NHS Digital Organisational Data Service - every provider has one. As an example, Guy's and St Thomas' is [RJ1](https://www.nhs.uk/Services/Trusts/Overview/DefaultView.aspx?id=RJ1), and Guy's Hospital itself is [RJ121](https://www.nhs.uk/Services/hospitals/Overview/DefaultView.aspx?id=RJ121). Linking to these on the [ODS portal](https://odsportal.digital.nhs.uk/) could be viable - but it is possibly easier to use nhs.uk, as the search there accepts ODS codes. | ✅ <br>switch the key to lowercase |
`NHSORGID:[REF]`<br>`nhsorgid:[REF]` | These appear to be the identifiers the ODS uses, e.g. GSTT is [89800](https://odsportal.digital.nhs.uk/Organisation/OrganisationDetails?organisationId=89800) and Guy's itself is [28394](https://odsportal.digital.nhs.uk/Organisation/OrganisationDetails?organisationId=28394). We should probably use the ODS codes themselves - but it may be worth trying to identify if we can programmatically search for them on ODS using our usual _build a link_ routine. |  ❓ <br>switch  the key to lowercase |
| `cqc:[REF]` | Agree with #1364, putting these in is good for our open data. | ✅ |
| `nhs111` | Sadly, there's so many providers of NHS111 that this is necessary. A 2020 FOI request to NHS England had the number as [58](https://www.whatdotheyknow.com/request/list_of_nhs111_providers_and_the), and there is also the Welsh service, which is provided by [WAST](https://www.whatdotheyknow.com/body/welsh_ambulance_services_nhs_trust), and  the Scottish service, [NHS24](https://www.whatdotheyknow.com/body/nhs24). Linking to MapIt could help here - but I'm not sure the data is available there (yet?). | ✅ |
| `[COUNTY/TOWN/LOCATION]` | Helpful, but now we've got MapIt (#818 / #1330), I wonder if we can do something clever here. These _do_ form the starting point to regional / country portals (#416 / #715 / #716 / #717 / #747) | ✅ |
| `surgery`<br>`urgent_care` | I suspect these fall under a similar theme to `nhs111` in that there are too many providers for us to be specific in a generic way. Perhaps this is best viewed on the basis of linking on a regional basis - so as to, say, allow for a search of urgent care providers in the Greater Manchester area. | ✅ |
| `dpr:[number]` | [ICO database](https://ico.org.uk/esdwebpages/search) of data controllers #1291 | ✅ |
| `ch:[COMPANY NUMBER]` <br>`limited` <br>`company` | Link to [Companies House Service](https://find-and-update.company-information.service.gov.uk/) and allows for generic categorisation. We could probably replace `limited` and `plc`, but there doesn't seem a good reason to. `company` may make sense where there are other entities - for example doctors surgeries which might be _partnerships_ but not necessarily an LLP | ✅ |
|`hscr` | The core theme here appears to be bodies related to [Health and Social Care regulation](https://www.whatdotheyknow.com/body/list/hscr), e.g. CQC, GMC. There is some junk data also tagged here in respect of NHS providers in Manchester (and curiously, [Sandyford](https://www.whatdotheyknow.com/body/sandyford_nhs_ggc) - which should fall under [NHSGGC](https://www.whatdotheyknow.com/body/nhs_greater_glasgow_and_clyde)). Logged as #1368, I will look at this | ✅ |


It would probably make a good bit of sense for us to look at what Wikidata does - again looking at GSTT, they list this as [Q16993504](https://www.wikidata.org/wiki/Q16993504), and thanks to the efforts of Wikidata contributors, they already have a [good way of matching data back to WDTK](https://www.mysociety.org/2020/05/13/whatdotheyknow-in-wikidata/). We should look at the best way of linking to this, as it is a fabulous resource.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
