### ISSUE TITLE
Blog on why we do (or don't) list sports governing bodies

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1361]
Should we list sports governing bodies
Action from Community and Activism meeting on 18 August.

Look at: (Sport England, Sport Wales .. Check NI Scotland), and list them comprehensively.  

Consider: 
Their role in distribution of public [lottery] funds. 
We could list the governing bodies as foi_no but direct users to Sport England, Wales etc

We should draft the blog first before listing them, as the research for the blog will help in making our decision

Linked ticket https://github.com/mysociety/whatdotheyknow-theme/issues/839

**Comment by confirmordeny** [comment]
_"Sports bodies wield extensive powers, whether it be the capacity to label an athlete as a “drugs
cheat”, to classify their behaviour as racist, or restrict freedom of expression in the sporting arena."_

Quote modified to remove footnote references.
http://irep.ntu.ac.uk/id/eprint/31582/1/PubSub9059_Boyes.pdf

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
