### ISSUE TITLE
Tag `cqc:` with provider ID on all/more relevant bodies

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1363]
Ensure it is provider, and not location.  Can be found from https://www.cqc.org.uk/search/all?filters[]=services%3Aall.

**Comment by garethrees** [comment]
There's a bit of discussion in #1364 about whether to tag up provider _and_ location.

> Perhaps there's a benefit to capturing both - in which case, we could refactor to `cqclocation:` and `cqcprovider:`?

I don't really have a sense of what either of these means, or which is more useful and valuable to users.

Looking at the example referenced in https://github.com/mysociety/whatdotheyknow-theme/issues/1364#issuecomment-1235318944, the location ([1-211357754](https://www.cqc.org.uk/location/1-211357754)) has more detail than _and links to_ the provider ([1-152944110](https://www.cqc.org.uk/provider/1-152944110)) entry.

![Screenshot 2022-10-21 at 12 52 28](https://user-images.githubusercontent.com/282788/197189719-15785878-9648-4688-a5de-a882d6f964df.png)

**Comment by HelenWDTK** [comment]
https://wdtkwiki.mysociety.org/wiki/Tagging_suggestions
