### ISSUE TITLE
[#1360] Cleanup junk from `hscr` tag

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#1368]
Cleanup the [`hscr`](https://www.whatdotheyknow.com/body/list/hscr) tag so as to remove bodies which ought to be listed elsewhere.

Relates to #1360

**Comment by confirmordeny** [comment]
What is the category intended for?

**Comment by mdeuk** [comment]
> What is the category intended for?

I haven't a clue. My [assumption](https://github.com/mysociety/whatdotheyknow-theme/issues/1360#issuecomment-1221657752) would be that was intended for regulatory entities, and that we've had a tagging error at some point.

**Comment by confirmordeny** [comment]
I am going to assume hscr = health and social care regulator
https://www.hcpc-uk.org/about-us/who-we-work-with/other-regulators/health-and-social-case-regulators/

**Comment by confirmordeny** [comment]
Done. See: https://www.whatdotheyknow.com/body/list/hscr

I have also change the name associated with the category.

Documented here: https://wdtkwiki.mysociety.org/wiki/Authority_tags#Health_and_social_care_regulator

I will close but please open a new ticket if I missed something.
