### ISSUE TITLE
System data request for all public bodies with no email addresses

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1371]
Would it be possible to get a list of all public bodies that currently have no email address.

We did run this report in April, ref ticket https://github.com/mysociety/whatdotheyknow-theme/issues/1084

It would be good to have an updated ahead of the new FOI database administrator volunteers starting

**Comment by mdeuk** [comment]
I wonder if it might be possible to use the script @garethrees popped in https://github.com/mysociety/whatdotheyknow-theme/issues/1084#issuecomment-1093030957 using a cron job? Then we'd able to get this periodically (say, monthly).

We've a slew of volunteers just now that have a uncanny knack for being able to find data in the most unusual places, so it'd be really helpful to have more regular access to this data.

**Comment by garethrees** [comment]
Did https://github.com/mysociety/alaveteli/pull/7250 instead.
