### ISSUE TITLE
Draft text about misunderstandings re. "organisational" requests

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1373]
People/organisations wanting things removed or questioning requests etc often seem to refer to "requests made by [our] organisation".

We could draft some text to challenge this, and explain how our service works.

**Comment by RichardTaylor** [comment]
This may be more canned-response / wiki text than help page text, though we could make something public too.

**Comment by WilliamWDTK** [comment]
See https://docs.google.com/document/d/1oHTp3VOJuRjVzJPjeIQdCtg0kdPuCsz6x4l5khPyYy0/edit#heading=h.raqx7cggqbs8

**Comment by confirmordeny** [comment]
We have something in the help text that covers this: "WhatDoTheyKnow is not making any requests. We are sending requests on behalf of our users, who are real people making the requests." 
https://www.whatdotheyknow.com/help/officers#vexatious

There may be a case for reordering material but we have a ticket for that already: https://github.com/mysociety/whatdotheyknow-theme/issues/883

**Comment by confirmordeny** [comment]
I will close.
