### ISSUE TITLE
Decision matrix for server log analysis requests

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1378]
Currently we don’t have a simple, shared view of what constitutes a breach serious enough that we feel obligated to spend our own time assisting the authority who caused the breach. 

We can’t cover every eventuality in a framework, but I think we’ve seen enough of these to be able to cover most. Here’s the type of thing I’m thinking.

<img width="633" alt="Screenshot 2022-08-31 at 10 11 56" src="https://user-images.githubusercontent.com/282788/187643103-493b6a25-dc78-432c-b615-cf6bc4f4b002.png">

We have some [guidelines](https://wdtkwiki.mysociety.org/wiki/Guidelines_for_handling_a_personal_data_breach#How_to_evaluate_the_seriousness_of_a_data_breach) for evaluating the seriousness of a data breach so there might be further attributes that we’d want to pull in, but I think having something like this makes it clear to everyone what the threshold is.

**Comment by FOIMonkey** [comment]
This seems like a helpful way forward that would really aid decision making in these cases. At the moment, I think (understandable) concerns around resourcing have lead to us sometimes being a bit too quick to refuse these requests. This shifts the focus back to the severity and impact of the breach. 

I think that if something like this had been in place, it would have resulted in us releasing data in all of the recent cases where I have felt most uncomfortable in being having to say no.

**Comment by mdeuk** [comment]
+1, I like the idea of this.

I do need to dig out a text book on risk matrices (it's been a while) - we could be making better use of these simple scoring models for decision making in general around breaches.

**Comment by HelenWDTK** [comment]
I think this has been overtaken by the introduction of the new serious data breach policy, as we now have an agreed and documented definition as to what serious means.
