### ISSUE TITLE
Better tools for server log analysis requests

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1379]
At present “providing log data” takes 30-60+ minutes. While this doesn’t seem like much, when accounting for the additional context switching it can really throw someone’s day out. In addition to the time element, there’s extra mental fatigue involved in figuring out what to do and how to do it each time. People are stretched as it is, and so this extra burden is quite unwelcome.

For this to be less of a burden, we need to develop tooling to make it a 3-6 minute task. I’m imagining a command line script that given a URL, prints out stats for each variation:

```
# Checks en, cy, html & pdf versions:
$ rails-page-views –from=2022-01-01 –to=2022-01-31 /request/123/response/456/attach/1/foo.pdf
Possible humans views: 23
Possible bot views: 13
Total views: 36
```

**Comment by mdeuk** [comment]
This looks like it would be a considerable improvement.

Longer term, I wonder if there could be a UI shim around it, so that the task can be requested using the Alaveteli admin UI, and then run in the background as a batch task?

I'd envision the output would be returned, once completed, in the form of an email, since it could take some time to process, so you probably don't want a browser sitting polling for a response.

**Comment by garethrees** [comment]
> I wonder if there could be a UI shim around it, so that the task can be requested using the Alaveteli admin UI, and then run in the background as a batch task?

I'd say not impossible, but pretty unlikely given the technicalities involved. We need to look at the webserver logs – not the rails app server logs – which are a step removed from what the app has access too. Alaveteli also supports both Apache and Nginx (and no reason why enterprising re-users couldn't use other newfangled web servers) so it all ends up getting really complicated.

There might be some other internal tooling we could build up, but I think we need to just focus on making it easy based on what we have right now before putting too much thought into that.

**Comment by mdeuk** [comment]
To clarify: I meant a frontend that kicks off the (potential) script proposed, nothing more than that. I can appreciate the technicality of things behind the scenes - I'm still recovering from my own test install. 😃

**Comment by garethrees** [comment]
Should also count zip downloads of entire requests in this analysis.
