### ISSUE TITLE
Promote `missing_email` bodies with on-site banner

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1382]
Once it's all sorted:

# Suggested text 1 (change requests):
**Title:**
<pre>Fancy helping us out?</pre>
**Body:**
<pre>&lt;p&gt;We have some authorities in our list without email addresses. You can help us find them!&lt;/p&gt;
&lt;p&gt;There's &lt;a href="https://www.whatdotheyknow.com/body/list/missing_email"&gt;a list of the ones with missing email addresses here&lt;/a&gt;, just click on the "Ask us to update FOI email" link, and fill out the details.  Remember to put details of the source of the email in the source URL / notes box.&lt;/p&gt;</pre>

[ann#139](https://www.whatdotheyknow.com/admin/announcements/139/edit)

# Suggested text 2 (Google Sheet):
1. Get an export, and make it ready for upload
2. Put it in a Google Sheet, share publicly
**Title:**
<pre>Fancy helping us out?</pre>
**Body:**
<pre>&lt;p&gt;We have some authorities in our list without email addresses. You can help us find them!&lt;/p&gt;
&lt;p&gt;There's &lt;a href="URL HERE"&gt;a list of the ones with missing email addresses here&lt;/a&gt;, just fill out the details in the appropriate columns.  Remember to put details of the source of the email in the source column.&lt;/p&gt;</pre>

[ann#138](https://www.whatdotheyknow.com/admin/announcements/138/edit)

**Comment by WilliamWDTK** [comment]
I think this is now ready to be done, we just need to decide which method we want to go for.  I'd suggest 1 is easier, we can always transition to 2 at a later date.

**Comment by FOIMonkey** [comment]
I think option one is best for now. I don't think we need to take it offsite into a google sheet.

**Comment by garethrees** [comment]
Yeah we don't have a CSV export right now so option 1 is easiest to get running soonest

**Comment by WilliamWDTK** [comment]
We could try translating the announcement to Welsh, but shall I set it to visible now?

**Comment by WilliamWDTK** [comment]
I've added a note about doing the research, and publish option 1. Option 2 remains there, but hidden for now.  I won't close this, because it would be good to translate it to Welsh.

<pre>
&lt;p&gt;We have some authorities in our list without email addresses. You can help us find them!&lt;/p&gt;
&lt;p&gt;There's &lt;a href="https://www.whatdotheyknow.com/body/list/missing_email"&gt;a list of the ones with missing email addresses here&lt;/a&gt;, just do a little bit of research to find the correct address, click on the "Ask us to update FOI email" link, and fill out the details.  Remember to put details of the source of the email in the source URL / notes box. Tip: try looking for Freedom of Information policies or Publication Schemes, otherwise, just use a generic email address.&lt;/p&gt;
</pre>

**Comment by mdeuk** [comment]
> We could try translating the announcement to Welsh, but shall I set it to visible now?

If you're happy with the wording, I'll send it for translation today?

**Comment by WilliamWDTK** [comment]
To note, this announcement is quite long. @garethrees suggests turning it into a blog post and linking to that.

As an interim, the more detailed instructions could be moved to the relevant tag note, leaving a shorter announcement. (Proposed by @FOIMonkey).

@mdeuk, we might therefore want to wait to see what we do about that before getting anything translated.

**Comment by WilliamWDTK** [comment]
I've now updated the announcement and the relevant tag note.  Both need translating to Welsh.

**Tag note:**
<pre>
&lt;p&gt;Unfortunately, we don't have a working email address for this authority.&lt;/p&gt;
&lt;p&gt;To help us out, just do a little bit of research to find the correct address, click on the "Ask us to update FOI email" link, and fill out the details.  Remember to put details of the source of the email in the source URL / notes box.&lt;/p&gt;
&lt;p&gt;Top tip: try looking for Freedom of Information policies or Publication Schemes, otherwise, just use a generic contact email address.&lt;/p&gt;
&lt;p&gt;If you manage to find one, if you prefer, you can also &lt;a href="/help/contact"&gt;let us know by contacting us&lt;/a&gt;.&lt;/p&gt;
</pre>

**Announcement:**
<pre>
&lt;p&gt;We have some authorities in our list without email addresses. You can help us find them!&lt;/p&gt;
&lt;p&gt;There's &lt;a href="https://www.whatdotheyknow.com/body/list/missing_email"&gt;a list of the ones with missing email addresses here&lt;/a&gt;.&lt;/p&gt;
</pre>

**Comment by WilliamWDTK** [comment]
We could try translating the announcement and tag note now. We'll want to make sure the interface-referencing bits use the right language.

I've put [a document here](https://docs.google.com/document/d/16kcBPaa6HYJzrG6FCuqcQPoXNc-uu1NJHml_gPNDsac/edit?usp=sharing), which I'll add the text to be translated to.

---

**Title:**
<pre>Fancy helping us out?</pre>

---

**Announcement (tag):**
<pre>
&lt;p&gt;We have some authorities in our list without email addresses. You can help us find them!&lt;/p&gt;
&lt;p&gt;There's &lt;a href="https://www.whatdotheyknow.com/body/list/missing_email"&gt;a list of the ones with missing email addresses here&lt;/a&gt;.&lt;/p&gt;
</pre>

---

**Tag note:**
<pre>
&lt;p&gt;Unfortunately, we don't have a working email address for this authority.&lt;/p&gt;
&lt;p&gt;To help us out, just do a little bit of research to find the correct address, click on the "Ask us to update FOI email" link, and fill out the details.  Remember to put details of the source of the email in the source URL / notes box.&lt;/p&gt;
&lt;p&gt;Top tip: try looking for Freedom of Information policies or Publication Schemes, otherwise, just use a generic contact email address.&lt;/p&gt;
&lt;p&gt;If you manage to find one, if you prefer, you can also &lt;a href="/help/contact"&gt;let us know by contacting us&lt;/a&gt;.&lt;/p&gt;
</pre>

**Comment by mdeuk** [comment]
> We could try translating the announcement and tag note now. 

These look good to go (thanks for adding the extra notes to the doc) - are we ready to send it?

FYI: It can take up-to 4 working days for the translators to do their magic.

**Comment by WilliamWDTK** [comment]
I think we are, do they want notes in the same document, or will that mess up word limits?

**Comment by mdeuk** [comment]
> I think we are, do they want notes in the same document, or will that mess up word limits?

There's a field for notes in the translation form, so it's just a copy/paste job for that part.

**Comment by WilliamWDTK** [comment]
Here's an example:
![image](https://user-images.githubusercontent.com/99501342/190136277-344204d7-3a0a-497e-b7b1-af25fe1d0786.png)
https://www.whatdotheyknow.com/cy/body/cwm_gwaun_community_council_pembrokeshire?no-cache

**Comment by WilliamWDTK** [comment]
(It's been translated.)

**Comment by confirmordeny** [comment]
We have a banner now that says: "We have some authorities in our list without email addresses. You can help us find them! There's [a list of the ones with missing email addresses here](https://www.whatdotheyknow.com/body/list/missing_email?page=2)." I feel that the original point has been addressed.
