### ISSUE TITLE
Consider adding Cancer Alliances to the site

### ISSUE THREAD

**Issue by confirmordeny** [mysociety/whatdotheyknow-theme#1383]
See also: https://www.england.nhs.uk/cancer/cancer-alliances-improving-care-locally/#map

**Comment by confirmordeny** [comment]
Here is one example: https://northerncanceralliance.nhs.uk/about-us/

**Comment by RichardTaylor** [comment]
We should list these bodies. 

>Here is one example: https://northerncanceralliance.nhs.uk/about-us/

From the point of view of the public that looks like a body/organisation. It has its own website/domain, contact address, Twitter handle, and chair.  

From a quick sample others look similar. 

We would list a "partnership" without question. These appear to be in practice partnerships, but under the name of an "alliance" .

We should list them comprehensively as there are only 21 of them, listed on the link above.

We could note they receive millions of pounds of public, NHS, funding https://www.england.nhs.uk/cancer/cancer-alliances-improving-care-locally/nhs-england-support-and-funding-for-cancer-alliances/ 

They will probably be subject to FOI by virtue of their members being subject to FOI. (Though "members" may not be a clear cut concept here). 

They may be subject to FOI as a result of providing NHS care, if they do. 

One person could research web addresses, email addresses etc. and write a note for these bodies, or we could set up a shared spreadsheet to share the work. 

It appears all the contact details are already in one-place at 

https://www.england.nhs.uk/cancer/cancer-alliances-improving-care-locally/cancer-alliance-contacts/

Asides:

* The linked NHS England finance information is for 2019/20. The bodies still appear to exist though. FOI could be used to obtain more up-to-date information from NHS England. 
* FOI requests for their founding documents / constitutions / governing documents  / terms of reference, members lists etc. would be useful to aid understanding of exactly what these bodies are.

**Comment by confirmordeny** [comment]
I have started adding them. I am using the wiki to record my progress: https://wdtkwiki.mysociety.org/wiki/Cancer_Alliances

**Comment by confirmordeny** [comment]
All now added. I have also documented our approach here: https://wdtkwiki.mysociety.org/wiki/Authorities_not_subject_to_FOI_policy#NHS_bodies

I will close now.
