### ISSUE TITLE
Create strategy and plan for the use of tag-based notes on WhatDoTheyKnow

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1389]
@FOIMonkey has said a plan would be to:
- [ ] Tag up requests and responses with the existing campaign tags (for [authorities](https://wdtkwiki.mysociety.org/wiki/Authority_performance_tags) and [requests](https://wdtkwiki.mysociety.org/wiki/Request_tags)),
- [x] Start a Google Doc to draft the notes 
- [ ] Look at some of the geotags / authority type tags to see if these could be used.

Our thanks to the devs is noted.

**Comment by WilliamWDTK** [comment]
Here is the [working document for the wording of tag-based notes](https://docs.google.com/document/d/1XA5h3KIWG1yi-thTi0-Rqgu233h_C1RU6erQc8YjiOA/edit?usp=sharing) (accessible within mySociety).

**Comment by FOIMonkey** [comment]
@confirmordeny has added a note to all the council's that are education authorities: 

https://www.whatdotheyknow.com/body/list/lea

It is so much easier now to add information about the powers of authorities if we want to do so. I can see real value in this in helping us to prevent requests from being misdirected.

**Comment by FOIMonkey** [comment]
At the moment, a note that's applied to a tag will apply to all things with that tag, regardless of type. eg requests, messages and authorities This means that we're going to need to tweak the [performance tags](https://wdtkwiki.mysociety.org/wiki/Authority_performance_tags) a little.

My suggestion would be best to append `_request` to the end of the existing request tags, although this will make them even longer. It should be trivial to switch out the existing tags.

**Comment by WilliamWDTK** [comment]
I'm not sure if/when there's going to be a distinction, but I suppose it could be worth waiting until that is implemented if it is going to be implemented in the near future.

**Comment by WilliamWDTK** [comment]
@mdeuk has suggested we consider Welsh translation in the context of tags, though it wasn't specified that this idea related specifically to tag-based notes.

**Comment by mdeuk** [comment]
> @mdeuk has suggested we consider Welsh translation in the context of tags, though it wasn't specified that this idea related specifically to tag-based notes.

Indeed - as we have the ability to specify both versions it would make sense if some of our _**generic**_ multi-authority tags were translated. It strikes me as a good use of our professional translation service, we've just got to choose the right ones! 🏴󠁧󠁢󠁷󠁬󠁳󠁿

**Comment by FOIMonkey** [comment]
We should find out if we need to warn the devs before applying a note to a lot of bodies. I'm thinking things like `parish_council `which applies to 9,000+ bodies. It might be the way that this change has been implemented makes things unlikely to fall over.

**Comment by gbp** [comment]
> We should find out if we need to warn the devs before applying a note to a lot of bodies. I'm thinking things like `parish_council `which applies to 9,000+ bodies. It might be the way that this change has been implemented makes things unlikely to fall over.

Go for it. I can't see any issues with the site being impacted or falling over.
