### ISSUE TITLE
Make it easier to copy and paste performance tags

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1390]
The current template for the [authority performance tags](https://wdtkwiki.mysociety.org/wiki/Authority_performance_tags) makes it difficult to copy and paste them quickly.

Currently, you get almost the entire cell ("🏷response_link🏢 (public)") whereas what I actually want copied is "response_link".

Here's a video showing what I mean:

https://user-images.githubusercontent.com/282788/188624537-c663e87a-fb83-455f-b03b-836a60603382.mov

I think a quick and easy fix would be to only link the public/private parts, and move the emojii outside of the link:

![Screenshot 2022-09-06 at 12 29 01](https://user-images.githubusercontent.com/282788/188624878-d9e99822-ee47-49d5-806a-18a08e12c4d1.png)

**Comment by WilliamWDTK** [comment]
I'll sort this later, the proposed solution seems probably a good one.

**Comment by WilliamWDTK** [comment]
This is now done. It now looks like the below, and you can now double-click on the tag to select it for copying, as it is no longer part of the links.

![](https://user-images.githubusercontent.com/99501342/188682172-d247fde4-4c9f-463e-aa7e-0680969b4bcb.png)
[Screen capture](https://user-images.githubusercontent.com/99501342/188683246-5c26e04a-5c49-48c2-95e4-c2aa985ea289.webm)

Template:Tag

{{Tag|body|rejects_org_request}} gives "🏷🏢 rejects_org_request [(public)](https://www.whatdotheyknow.com/body/list/rejects_org_request) [(admin)](https://www.whatdotheyknow.com/admin/tags/rejects_org_request?model_type=PublicBody)"

{{Tag|request|rejects_org_request}} gives "🏷✉ rejects_org_request [(public)](https://www.whatdotheyknow.com/search/tag:rejects_org_request/requests) [(admin)](https://www.whatdotheyknow.com/admin/tags/rejects_org_request?model_type=InfoRequest)"

{{Tag||rejects_org_request}} gives "🏷 rejects_org_request"

{{Tag|banana|rejects_org_request}} gives ""

{{Tag||}} gives "🏷 "

{{Tag|body|}} gives "🏷🏢  [(public)](https://www.whatdotheyknow.com/body/list/) [(admin)](https://www.whatdotheyknow.com/admin/tags/?model_type=PublicBody)"

{{Tag|request|}} gives "🏷✉  [(public)](https://www.whatdotheyknow.com/search/tag:/requests) [(admin)](https://www.whatdotheyknow.com/admin/tags/?model_type=InfoRequest)"

{{Tag}} gives ""

**Comment by garethrees** [comment]
Amazing, thanks so much!
