### ISSUE TITLE
Add a feed of FOI mentions in parliament

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1391]
FOI is [often mentioned in parliament](https://www.theyworkforyou.com/search/?q=%22freedom+of+information%22). Conveniently, we run a site that tracks this and has [an RSS feed](https://www.theyworkforyou.com/search/rss/?s=%22freedom+of+information%22) of the mentions.

This would be a nice way of linking up our services.

Idea via https://github.com/mysociety/whatdotheyknow-theme/issues/1240#issuecomment-1238239446

**Comment by garethrees** [comment]
Related to https://github.com/mysociety/whatdotheyknow-theme/issues/1332

**Comment by HelenWDTK** [comment]
Where would you see this going?

**Comment by garethrees** [comment]
IDK; could be a homepage section; could be a help page.

We could reduce this from an imported feed to just the link as it is above.

Why do I think this is worth considering?

* It helps promote another tool we run that can help citizens become more active
* It helps demonstrate that FOI is valuable for all (if they use it in forming legislation, then clearly it's not just a "toy")
* It helps promote mySociety wrt donations and membership
