### ISSUE TITLE
Add the date of the funeral of Elizabeth II as a bank holiday to the WhatDoTheyKnow system

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1392]
We don't yet know the date of the funeral, and therefore the date of the bank holiday. 

If the funeral and associated bank holiday fall on an working day this will extend FOI deadlines. 

If the funeral is on day which would have been a non-working day anyway then adding it to WhatDoTheyKnow is not important as there will be no impact on FOI deadlines. 

The proclamations of the bank holiday were made from 1:06:25 at

https://www.bbc.co.uk/iplayer/episode/m001chcz/hm-the-king-the-proclamation-of-hm-the-king

however they referred to unpublished papers - the draft proclamations - so we don't yet know the details.

the BBC iPlayer link is not expected to persist

One proclamation refers to England, Wales and Northern Ireland, the other to Scotland.

It appears the text of the proclamations will appear at

https://privycouncil.independent.gov.uk/orders-in-council/the-accession-council/

We also expect them to appear at

https://www.thegazette.co.uk/all-notices/notice?noticetypes=1101

**Comment by mdeuk** [comment]
> We don't yet know the date of the funeral, and therefore the date of the bank holiday.

Monday 19 September is the date that has just been [announced by the BBC](https://twitter.com/BBCBreaking/status/1568631657174892546).

We've briefly discussed the technical steps on Slack - it would, perhaps, be best to hold off making changes on Alaveteli until a mySociety developer can verify.

**Comment by RichardTaylor** [comment]
There is now a press release giving the funeral date as Monday 19th September at 

https://www.royal.uk/arrangements-funeral-her-majesty-queen

The Bank Holiday Proclamation itsself has now been published, and it states the Bank Holiday is Monday 19th September 

https://privycouncil.independent.gov.uk/wp-content/uploads/2022/09/2022-09-10-Bank-Holiday-Proclamations-and-Sealing-Orders.pdf

>We've briefly discussed the technical steps on Slack 

I'll check Slack, but we have an admin accessible interface for adding Bank Holidays which we can use.

**Comment by mdeuk** [comment]
> I'll check Slack, but we have an admin accessible interface for adding Bank Holidays which we can use.

It's not quite as simple as the usual procedure - owing to the fact that a change made here will only affect **new** requests. There's a bespoke bit of code that needs to be run, so it'd probably be a good idea for this to be acted on simultaneously.

**Comment by RichardTaylor** [comment]
> a change made here will only affect new requests.

I see there's a discussion of an additional step to be taken to make the change apply to existing requests, that doesn't stop us applying the change now.  

>probably be a good idea for this to be acted on simultaneously.

Certainly it would be nice to either have everything in-order or know what we're [not] going to do before a tweet/blog.

**Comment by RichardTaylor** [comment]
Bank holiday added to the system for 19 September 2022. 

I'll note on the thread about updating the blog that may want to wait for developers to run a script to update existing requests before drawing attention to our actions.
