### ISSUE TITLE
Update in-progress request deadlines in light of new bank holiday on 19 September

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1393]
Reportedly adding a new bank holiday to the system doesn't impact existing requests.

A developer has posted a script for making this update in Slack.

Related:  https://github.com/mysociety/whatdotheyknow-theme/issues/1392

**Comment by WilliamWDTK** [comment]
We could also add a tag to the relevant requests, so we can then add a note explaining the situation.

**Comment by mdeuk** [comment]
> We could also add a tag to the relevant requests, so we can then add a note explaining the situation.

+1, this is an excellent suggestion.

The title used on [gov.uk's list](https://www.gov.uk/bank-holidays#england-and-wales) is "Bank Holiday for the State Funeral of Queen Elizabeth II" - so a reasonable translation into a tag could be `qe2-state-funeral-20220919` (or a similar variant).

**Comment by mdeuk** [comment]
As an addition to the tags, in order to keep the note relatively brief, we could link to a help page which contains the longer-form explanation / links to the [proclamation](https://privycouncil.independent.gov.uk/wp-content/uploads/2022/09/2022-09-10-Bank-Holiday-Proclamations-and-Sealing-Orders.pdf). If there is an announcement from ICO or OSIC, a link to those announcements could also be added.

This will be static once agreed, so it wouldn't be much effort for us to setup.

**Comment by gbp** [comment]
I have updated due dates for any request which needed to account for the new bank holiday, and these have been tagged with `impacted_by:qeII-day-of-mourning`.

**Comment by gbp** [comment]
A note has been added to requests: 

<img width="762" alt="image" src="https://user-images.githubusercontent.com/5426/190107936-75f8962c-6594-4eff-8bc6-966d85232ce1.png">

Please feel free to edit the wording if needed https://www.whatdotheyknow.com/admin/notes/8302/edit

**Comment by garethrees** [comment]
> I have updated due dates for any request which needed to account for the new bank holiday, and these have been tagged with `impacted_by:qeII-day-of-mourning`.

Nice! Can you paste the script that you used here so that we have it for future reference?

I think that can then close the issue?

**Comment by RichardTaylor** [comment]
Minor text tweak to:

>The deadline for a response to this request has been updated to take into account the new Bank Holiday for the State Funeral of Queen Elizabeth II.

The fact there was a manual bulk recalculation isn't something our users need to know. We've not done anything manual on a per request basis. I also prefer "deadline" to "due date". I resisted the opportunity to note FOI law requires requests to be responded to "promptly" as we want to keep it succinct.
