### ISSUE TITLE
Create help page for 19 September bank holiday

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#1397]
As the bank holiday on [19 September](https://privycouncil.independent.gov.uk/wp-content/uploads/2022/09/2022-09-10-Bank-Holiday-Proclamations-and-Sealing-Orders.pdf) is an exception to the normal rule - in that it is being applied late on, due to exigent circumstances, and will apply to requests already in progress, it would make sense - for reasons of permanence - to have a short help page, which we can link to from tag-based notes.

### Why?
This is an unusual event - linked to the state funeral of the late Queen Elizabeth II - and is being added on with only a few days notice. 

Our users won't necessarily be experts in the nuance of FoI legislation, so might not expect that a public body will be entitled to use this bank holiday in their response timeline. Similarly, they may not necessarily expect that we'll re-calculate the due date of their requests, so this is bound to generate support queries.

We're already planning to add a note via tag, but to keep the text there to a minimum, it would help us to have a help page. Keeping this 'on site', rather than on the blog helps for consistency, and it also allows us to have it translated for our Welsh-speaking users.

Relates to #1392, https://github.com/mysociety/whatdotheyknow-theme/issues/1393#issuecomment-1242812444 and #1396

**Comment by RichardTaylor** [comment]
What we want to achieve here might be achieved via a tag on all requests impacted, and a tag based note. 

A whole help page on this might be too much for a transient one-off event.

**Comment by sallytay** [comment]
Agreed at on the admin and ops not to create a new help page for this one off event but to use a tag on all requests impacted and with  a tag based note that we could point to in the banner, ref https://github.com/mysociety/whatdotheyknow-theme/issues/1396

**Comment by garethrees** [comment]
> A whole help page on this might be too much for a transient one-off event.

I agree, help pages should be for more "evergreen" information. We already have a blog post we can link to.

> a large tag-based note at the top of each request just takes too much space on the request thread.

I think this only needs to be a one liner to the effect of "We've accounted for the [extra bank holiday for the Queen's funeral](https://www.mysociety.org/2022/09/09/a-change-in-the-monarchy-how-it-does-and-doesnt-affect-foi/) in the due date calculations for this request."
