### ISSUE TITLE
Blog - Public interest test extensions

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1400]
Write a blog on: Public interest test extensions 

When the response deadline is moved back to allow the authority to consider the public interest in applying an exemption. 

Notes:

>See Christopher Cook / Alex Parsons / Martin Rossenbaum writing about the indefinite delays. 
>See what we’ve already written
>WDTK blog can link to examples  « This is what value  we add. 
>Could develop exactly what we’re campaigning for - how long would we give bodies for Public Interest tests?
>Alex mentions “set firm deadlines for internal review and public interest tests “ in https://www.mysociety.org/2022/04/29/pacac-makes-the-positive-case-for-foi-but-there-is-more-work-to-do/

**Comment by garethrees** [comment]
We had a German journalist contact us about a UK request they'd made saying (em mine):

> …I wanted to ask you about how many extensions are legal under the UK FOI law. I've got a request out to UK trade, sent in July, and they've just told me they are extending the deadline for a second time.
>
> They are citing a public interest test for my request, saying that because they are still deciding on the public interest issue the answer can be extended. I've looked at the law and the language on this seem pretty vague, though _I'd be surprised if it allowed for indefinite extensions_. 
>
> Mostly though it seems like the public interest test they are citing is really more of a "do we actually want to respond to this" test.

**Comment by garethrees** [comment]
Just assigning as this is being worked on

**Comment by garethrees** [comment]
https://www.mysociety.org/2023/07/06/as-time-goes-by/
