### ISSUE TITLE
Tag based notes for `forthcoming` tag

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1402]
https://www.whatdotheyknow.com/body/list/forthcoming

Suggested text:

>This is a placeholder page created before this public body came into existence. If this body is now up and running please [contact us](https://www.whatdotheyknow.com/help/contact) and let us know"

This requires removing this, or similar, text from existing notes. 

See also:

* https://github.com/mysociety/alaveteli/issues/7298

**Comment by FOIMonkey** [comment]
+1 Seems sensible, and will make things easier moving forward.
