### ISSUE TITLE
Update Reading Council notes and tags following the council ceasing to refuse to deal with emailed requests

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1404]
https://www.whatdotheyknow.com/body/reading_borough_council

The note at https://www.whatdotheyknow.com/body/reading_borough_council currently states:

>WhatDoTheyKnow has written to the Information Commissioner expressing concern about the way Reading Borough Council have been handling requests for information. The council appears to be refusing to recognise valid FOI requests, responding with strange messages such as: "if you do not wish to submit your request via our online service, Please re-send your request via this mail address, [email address] stating you do not wish to submit your request through the online service."

>A response from the Commissioner suggests they have allocated this systemic issue with Reading Borough Council's handling of FOI requests the reference IC-137275-N2L7.

>Ex-BBC Political Journalist Martin Rosenbaum faced these problems at Reading Council. He [reports](https://twitter.com/rosenbaum6/status/1458126976531771396) he "sent an internal review insisting my request was legally valid and they then caved in". Requesters might want to follow that approach.

>The Information Commissioner's guidance explicitly recognises email – [including emails sent via WhatDoTheyKnow](https://www.whatdotheyknow.com/help/officers#email_only) – to be a valid correspondence address for Freedom of Information requests.

We have now noted an improved response at 

https://www.whatdotheyknow.com/request/limit_on_taxi_numbers_8#incoming-2119472

Proposed new note:

>For a period Reading Council refused to deal with requests which had not been submitted via the council's own web-form. We understand this issue has now been resolved and the council has changed its stance. If you do experience any new cases [do let us know](https://www.whatdotheyknow.com/help/contact). 

Remove `refuses_emailed_request` tag

**Comment by HelenWDTK** [comment]
Closing as complete
