### ISSUE TITLE
Add tag based notes for Authority Performance Tags

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1405]
Take care to provide useful advice and not deter making requests 

https://wdtkwiki.mysociety.org/wiki/Authority_performance_tags

**Comment by RichardTaylor** [comment]
Share drafts with the team first before adding

**Comment by garethrees** [comment]
Drafts being considered in https://docs.google.com/document/d/1XA5h3KIWG1yi-thTi0-Rqgu233h_C1RU6erQc8YjiOA/edit#heading=h.o1elrscgndic

**Comment by RichardTaylor** [comment]
I did response_link yesterday because it came up while admining the site - I wanted to add the tag and a note to a body and it seemed silly to add a body specific note. 

Thread at 

https://groups.google.com/a/mysociety.org/g/wdtk-volunteers/c/RszCyEwGP6E

**Comment by RichardTaylor** [comment]
Example note in the style of saying we've noted an issue, offering a public link to other requests/bodies to which the tag has been added, and suggesting users contact us with other examples:

https://www.whatdotheyknow.com/request/unpublished_planning_process_res_2

This note is on just one request at the moment so I think experimenting live is OK there.

**Comment by RichardTaylor** [comment]
Related, see use of tags at:

* https://github.com/mysociety/whatdotheyknow-theme/issues/1445#issuecomment-1277818403 - https://www.whatdotheyknow.com/search/tag:pit_delay/all 

and

* https://github.com/mysociety/whatdotheyknow-theme/issues/1456 -  https://www.whatdotheyknow.com/search/tag:s22_concerns/all

**Comment by RichardTaylor** [comment]
New tag, with a note, created:
https://www.whatdotheyknow.com/body/list/eir_charges

**Comment by RichardTaylor** [comment]
Noting that someone has started a note for 
https://www.whatdotheyknow.com/body/list/eir_charges  with a title in `<h3>` tags, which looks smart.

**Comment by confirmordeny** [comment]
I added the heading in the <h3> tags but that was my only contribution.

**Comment by RichardTaylor** [comment]
Tag added at 

https://www.whatdotheyknow.com/search/tag:refuses_emailed_request/all

(There was no draft in the document). 

There is potentially an issue of tag and tag note proliferation on bodies which we should be aware of.

**Comment by RichardTaylor** [comment]
>There is potentially an issue of tag and tag note proliferation on bodies which we should be aware of.

Noted in respect of councils at:

* https://github.com/mysociety/whatdotheyknow-theme/issues/1429

**Comment by HelenWDTK** [comment]
Closing as complete
