### ISSUE TITLE
Apply a district-level-authority tag to relevant local councils

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1408]
Tag all councils with functions of a district-level authority

Proposed tag: district-level-functions 

This tag can be added bodies covered by a set of existing tags/categories 

* District councils
* Metropolitan borough councils
* London borough councils
* Unitary Authorities
* Isle of Scilly Council
* City of London Corporation

https://en.wikipedia.org/wiki/Local_government_in_England#Billing_authorities

The district-level-function tag would I suspect be applied to the same set of bodies which are

* Principle local planning authorities
* HMO registration authorities  

among many other functions, this one tag could prevent maintaining lots of more specific tags on specific functions

This would build on work done at https://github.com/mysociety/whatdotheyknow-theme/issues/579#issuecomment-1192489549

it may negate the need for 

* https://github.com/mysociety/whatdotheyknow-theme/issues/1101

**Comment by FOIMonkey** [comment]
This seems sensible. Should be quick to do as well, as we've already tagged the Councils by type.

**Comment by confirmordeny** [comment]
What would the tag be called?

*billing_authority
*DIS would align with MapIt.

**Comment by RichardTaylor** [comment]
>  *DIS - which I believe would align with MapIt.

The DIS tag has already been copied over from MapIt, but it is not applied to as many bodies as proposed here

https://www.whatdotheyknow.com/search/tag:DIS

**Comment by RichardTaylor** [comment]
>I agree with the idea. I am not sure about the proposed wording for the tag. We don't normally use hyphens or dashes in tags. 

I therefore propose

`district_level_functions`

I think that's more generic than the various others eg. billing_authority which I expect will cover the same set of bodies.

**Comment by confirmordeny** [comment]
Great. 

Started work on this: https://www.whatdotheyknow.com/body/list/district_level_functions

**Comment by RichardTaylor** [comment]
Excellent. I've proposed a note for this new tag at

https://github.com/mysociety/whatdotheyknow-theme/issues/1410

**Comment by confirmordeny** [comment]
some basic documentation here: https://wdtkwiki.mysociety.org/wiki/Council_Tags#Tags_showing_a_Council.27s_status.2Fpowers

**Comment by RichardTaylor** [comment]
As a check, we're expecting 309 of these councils in England

https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1064277/Council_Tax_Levels_Set_by_Local_Authorities_in_England_2022-23_-_Technical_Notes.pdf


We don't currently comprehensively tag relevant councils `england` but we do have regional tags.

**Comment by confirmordeny** [comment]
We now have 309.

**Comment by confirmordeny** [comment]
Can we close this?

**Comment by RichardTaylor** [comment]
>Can we close this?

It appears this has been completed for England.  

It also appears the `england` tag is on all the bodies which have been tagged, though I've not checked this.  Once the search engine catches up with the changes we can hopefully confirm there are 309 entries at:

https://www.whatdotheyknow.com/search/tag:england%20AND%20tag:district_level_functions/all

We should consider Scotland, Wales and Northern Ireland.  

**Propose actions - read through before acting**

== Scotland ==

All Scottish councils are single tier ([ref](https://en.wikipedia.org/wiki/Subdivisions_of_Scotland)), so we can tag them all `district_level_functions`

We can do this easily by using the "add tag to all" function on the admin page for a list of bodies tagged `scotland_council
`
https://www.whatdotheyknow.com/admin/bodies?utf8=%E2%9C%93&query=scotland_council&commit=Search

== Wales == 

Two tier local government in Wales was abolished in 1996 ([Ref](https://en.wikipedia.org/wiki/Districts_of_Wales))

We can tag the Welsh unitary authorities with `district_level_functions`

We can do this easily by using the "add tag to all" function on the admin page for a list of bodies tagged `welsh_unitary_authority`

https://www.whatdotheyknow.com/admin/bodies?utf8=%E2%9C%93&query=welsh_unitary_authority&commit=Search

== Northern Ireland ==

There are 11 councils in Northern Ireland 

We can tag them  with `district_level_functions`

We can do this via

https://www.whatdotheyknow.com/admin/bodies?utf8=✓&query=ni_local_council&commit=Search



Ideas which are so closely related we could deal with them here:

* Create a category associated with the `district_level_functions` tag
* Consider a `district_level_functions_england` tag and category (We don't need to replicate this for other countries of the UK as we already have tags which cover these groups, as they don't have two-tier councils). It would be easier to do this by adding the tag to those bodies currently tagged district_level_functions before we expand the tag to cover other countries. 


I'm not acting immediately myself to allow for comment, but if anyone else agrees do go-ahead.

**Comment by FOIMonkey** [comment]
The public search still hasn't caught up, but the tag page and the admin panel showed the right amount of entries. 

The proposal seemed sensible, so I've done all of the above apart from creating the category. 

I made sure to add `district_level_functions_england` before tagging the rest.

**Comment by confirmordeny** [comment]
Categories have been created:
https://www.whatdotheyknow.com/body/list/district_level_functions
https://www.whatdotheyknow.com/body/list/district_level_functions_england

**Comment by confirmordeny** [comment]
I will close as ticket is substantially complete.
