### ISSUE TITLE
Blog - promote missing email address project

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1409]
As mentioned on ticket https://github.com/mysociety/whatdotheyknow-theme/issues/1382

Now that we have our new bodies database administrators in place, it would be good to some more promotion of bodies with missing email addresses project, particularly as the banner seems to have work so well.

There's a draft there if anyone wants to take a look or add anything extra in

https://docs.google.com/document/d/1h_SEimMFbIE1Iswu6rm_S6mScv25Kl1vwPblV6f1twU/edit#

**Comment by sallytay** [comment]
This has now been reviewed by Gareth and Myf and is scheduled to be published on Monday

**Comment by garethrees** [comment]
Done! https://www.mysociety.org/2022/09/26/help-whatdotheyknow-find-contact-addresses-for-public-authorities/
