### ISSUE TITLE
Note for bodies tagged `district_level_functions`

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1410]
Proposed note:

>This council has the functions of a district level council.  Councils of this type are usually the primary planning authority and council tax billing authority and have responsibility for, among other things, refuse collection, housing, food safety inspections, dog wardens, parks and street cleaning as well as cemeteries and crematoria. 

Sources:
https://www.gov.uk/understand-how-your-council-works
https://www.bassetlaw.gov.uk/council-and-democracy/elections-in-bassetlaw/the-role-of-a-district-councillor/

**Comment by RichardTaylor** [comment]
Once we've we've got the note we could expand to also

* blog
* add a mention on the help pages
* Promote via a pro banner

to encourage better targeting of requests using the new categories.  I won't clutter things up with lots of separate tickets for these things at the moment. 

https://www.whatdotheyknow.com/body/list/district_level_functions_england
https://www.whatdotheyknow.com/body/list/district_level_functions

**Comment by HelenWDTK** [comment]
Closing as complete
