### ISSUE TITLE
Update HM Prisons Independent Monitoring Boards authorities

### ISSUE THREAD

**Issue by gbp** [mysociety/whatdotheyknow-theme#1413]
User reporting that:

> there are quite a few that are years out of date, prisons that have closed, others that have amalgamated with others and changed names so it does need a complete overall.

**Comment by FOIMonkey** [comment]
Up to date list of Prisons: https://www.gov.uk/government/collections/prisons-in-england-and-wales

**Comment by FOIMonkey** [comment]
I've triaged the none immigration IMBs that we list: https://docs.google.com/spreadsheets/d/1P_OtInbFKj-POt29uDHrG9bvgpsmauYvkuxyh9jQVrU/edit#gid=0

There are 22 that we list which are not on the government list. These may be defunct, renamed or merged (don't know which at this stage).
There are 21 on the gov. prisons list that are not on WDTK (again, these may have been renamed).

**Comment by FOIMonkey** [comment]
Finally finished these updates 🎉
