### ISSUE TITLE
Move bid notes from individual to tag-based

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1417]
We list [297 business improvement districts](https://www.whatdotheyknow.com/body/list/bid), so would be easier to script this. _Could_ be done manually though.

**Comment by WilliamWDTK** [comment]
Since this could be more general than BIDs, I've added #1420. If this is specific to BIDs, though, we could close that ticket.

**Comment by RichardTaylor** [comment]
>Could be done manually though.

Spreadsheet manipulation, like scripting, can avoid tedious manual work. 

The feature requested at:

* https://github.com/mysociety/alaveteli/issues/6442

would make edits like this easier for non-developers to make.

**Comment by HelenWDTK** [comment]
Done 🚂
