### ISSUE TITLE
Adapt letter template paragraph spacing

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1418]
If possible, adjust letter template paragraph spacing such that we don't need to manually add blank lines between paragraphs or between headings and body text.

**Comment by WilliamWDTK** [comment]
This would also avoid the issue where a blank line is inserted at the beginning of a new page before the rest of the text.

**Comment by mdeuk** [comment]
> Does this refer to our Google docs templates for providing GDPR etc. responses?

Yes.

I suspect some of these glitches come from the fact that this was initially a Word template, that and the original author’s way of working might be different from what is best practice… 🙂

It should be reasonably trivial to fix this in the master template. A useful approach as a starter for ten might be to create a copy (template gallery > WDTK Letter Template) and then we can tinker with the formatting.

**Note:** it’s best not to touch anything above “Dear” on page one, or to change the formatting there [^1][^2].

[^1]: This is setup specifically for print, as there is the assumption that in some cases we’ll actually send correspondence by post. 

[^2]: Similarly, the little grey line in the background on that page is important - it’s the fold line for a DL envelope.

**Comment by WilliamWDTK** [comment]
https://docs.google.com/document/d/1Non9GxQgAFjNrrJPR6OOtP9g42DYRQs6r5jFLG0z55E/edit?usp=sharing

**Comment by WilliamWDTK** [comment]
I've just done some changes to the styles in that document, it looks OK, except for the bullet list.
![image](https://user-images.githubusercontent.com/99501342/193423565-73d51acf-8651-4c5a-9531-3523f60d46dd.png)

Trouble is, styles in Google Docs are rather limited (Normal Text + Title + H1-H6), at least compared to what I'm used to in LibreOffice…

**Comment by mdeuk** [comment]
> Trouble is, styles in Google Docs are rather limited (Normal Text + Title + H1-H6), at least compared to what I'm used to in LibreOffice…

Yep, compared to Microsoft Word, it is pretty limiting.

The changes here look **ok** - I've fixed the header on page 1 as the formatting was causing a large gap between lines, and I've checked that the address window is in the right location [^1] - it took a little bit of finagling to achieve that.

Once we're happy with the styling, we can push this into the default without too much issue. It'd be a good idea to note down the settings for future reference.

[^1]: The box should be 93x39mm sitting roughly 25mm off the left side of the doc, and roughly 50 - 55mm from the top. Our box isn't quite wide enough, but we make it work.

**Comment by WilliamWDTK** [comment]
To be honest, I think this is finished. The only thing I want to change is the bullet spacing, but I think it's impossible to do that automatically, as there is no specific setting, so it'll have to be done manually.

I would propose:
- [ ] Setting this as the default letter template (after removing all the ipsum, but leaving some basic structure (incl. quotes)
- [ ] Transferring our existing templated responses to the new format. I would propose doing this manually to a new document, and taking the opportunity to fix any errors.

If this is agreed, then I can do this.

**Comment by WilliamWDTK** [comment]
One other thing, first page footer:

-0.57cm left indent, but with centred text and no blank line after page number:
![image](https://user-images.githubusercontent.com/99501342/195929810-244842ce-bfb1-47e3-9e7f-79466c88162f.png)
(This is my favourite)

-0.57cm left indent, but with centred text:
![image](https://user-images.githubusercontent.com/99501342/195929599-9b3ba33f-5846-46bf-b693-9da352bc7f0a.png)

2.6cm left indent:
![image](https://user-images.githubusercontent.com/99501342/195928742-1e0e981e-2e4b-4a0a-8a81-295fa49690ab.png)

-0.57cm left indent:
![image](https://user-images.githubusercontent.com/99501342/195929064-32a70f19-3f9a-4fb9-89d4-f1c53c1f9de8.png)

Original 8.49cm left indent:
![image](https://user-images.githubusercontent.com/99501342/195929270-d5ab9737-8e44-428c-8ae3-d789a1ab1642.png)
(I'm not so keen on this)

**Comment by mdeuk** [comment]
The positioning of the footer is deliberate - it follows the logo. Unless we’re also moving the logo position I’d be inclined to probably leave the footer ‘as is’.

**Comment by WilliamWDTK** [comment]
> Unless we’re also moving the logo position

No, looks horrible:
![image](https://user-images.githubusercontent.com/99501342/195935987-f4b80835-2daa-44c0-a399-3a5551675801.png)

Although I still like the centred footer, it even gives us two more lines of the first page.

**Comment by FOIMonkey** [comment]
> -0.57cm left indent, but with centred text and no blank line after page number

+1 for this version, but no strong preference.

Thanks for all the hard work on this one. I think it's looking great.

**Comment by WilliamWDTK** [comment]
I think this is done, really.

**Comment by WilliamWDTK** [comment]
I'm in the process of updating our existing templates…

**Comment by mdeuk** [comment]
Just to note: I used this successfully to do a response to a user yesterday.

some feedback:
- The formatting is good, but use of justified text did throw me off a bit.
- The improved headings are good. We might wish to use a lighter weight than we do, but it looks decent.
- The centre aligned header on continuation pages is a -1 from me (it gets in the way of the reader’s  eyeline), but I’m happy to go with what others prefer.
- The ‘title’ style might need a little more padding before/after.

Overall though, I think this is a **decent improvement**, it conveys a professional image and is easy to work with.

thanks for your considerable efforts here, @WilliamWDTK! 👍

**Comment by WilliamWDTK** [comment]
I'd put justified in as an experiment, I decided I didn't like it, so I've since removed it.

I find it works better in some styles of document than others.

I'll consider the title padding.

I personally like the centre-aligned header.

See #1454 (I'm currently working on it)

**Comment by WilliamWDTK** [comment]
I've updated the title padding to be 10 pts before and after.

**Comment by WilliamWDTK** [comment]
I think this is done, it can be re-opened if necessary.
