### ISSUE TITLE
Establish policy/guide on when to use I and we

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1419]
I'd suggest that if a named individual is not checking, approving, and putting their name to something, then 'I' should not be used, only 'we'.

**Comment by sallytay** [comment]
+1 agree with this

**Comment by confirmordeny** [comment]
I have marked up the style guide with a suggested change to cover this off. Copying in @MyfanwyNixon.

**Comment by MyfanwyNixon** [comment]
Thanks - if we are talking about social media, blogs, policy docs etc, I agree. We practically always put out mySociety communications under 'we' unless there is a distinct reason not to do so (for example the CEO announcing a final decision about a difficult case).

**Comment by confirmordeny** [comment]
The style guide has now been amended so I will close the issue.
