### ISSUE TITLE
Identify bodies whose specific (non tag-based) notes are the same as others

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1420]
The notes could then be converted, following manual review, to tag-based notes.

**Comment by WilliamWDTK** [comment]
It might also be possible to do this for parts of notes, but we would want it to identify significant parts (whole sentences or paragraphs).

**Comment by garethrees** [comment]
Might want to create a script to do this, but we can also record instances that we manually spot so generalised the name.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
