### ISSUE TITLE
Agree a plan for what to do when we learn a public body plans to require FOI requests be made via a web-form

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1428]
We have a blog post on "Challenging public bodies who refuse to accept FOI requests by email"

https://www.mysociety.org/2022/08/01/public-bodies-refusing-emailed-foi-requests/

Our view as stated there is:

>This practice is against the law. For a Freedom of Information request to be valid, all that’s [required](https://ico.org.uk/for-organisations/guide-to-freedom-of-information/receiving-a-request/#1) is that a) it’s made in writing; b) it includes the requester’s name and an address for correspondence; and c) it describes the information being requested.

Proposed actions to take when we find out a body is planning to refuse to accept FOI requests by email:

* Write privately to the body and ask for an alternative contact address 
* Add a note to the body page on WhatDoTheyKnow alerting users to the impending issue, and urging them to contact us if they have problems getting their request through. 

Other things we could do:

* Let the body know how we deal with this kind of thing by finding other email addresses to send requests to. We already make this policy public in the post. 
* Write to councillors, or who ever is accountable for the body, urging a change in policy. (We'd need to work out the details. Would this be a public letter? Would we blog it?)
* Tweet mentioning the body, relevant journalists, and the ICO, noting we think their proposed action is against the law and asking them to reconsider.  
* We could write (privately?) to the ICO urging them to take proactive action, without waiting for a request for a decision from the Commissioner in a specific case.

**Comment by RichardTaylor** [comment]
If we wanted to act in-public, but not appear to be jumping too quickly to being critical in public we could write a tweet starting with the public body's username, such tweets probably won't be shown to all our followers.

**Comment by RichardTaylor** [comment]
Without an agreed approach we've ended up doing nothing in the run-up to a change by a public body. 

Well, nothing active in terms of contacting the public body, we have been monitoring the situation, advising our users, and getting ready to find an alternative address to send requests to, if and when the previous address is turned off. 

We want to take an approach which is in-line with mySociety's published strategy 

https://www.mysociety.org/2021/11/24/three-shifts-well-make-to-repower-democracy/

which calls for a move from "outside critique" and "calling for change" to "driving institutional change", "working with allies and agents of change inside of institutions" and seeking to operate "with the consent and collaboration of these existing institutions". 

--
I don't think our previous/current stance should be characterised as "outside critique" and "calling for change"; our approach to this issue has been one of being activists, acting to ensure our users' requests get through despite a policy change at the body. We've been a nuisance to public bodies, preventing their policy change from having the effect they desired, and in some cases apparently prompting a reversal in policy, and practice as a result.  

We've achieved change on this issue by getting our users' requests through - by acting, by doing, by demonstrating, which is one of our primary routes for having an impact in other areas too.  Perhaps what we are doing is "forcing changes to be made" which is cited as a desirable approach in the strategy.

**Comment by RichardTaylor** [comment]
The plan should include a plan for the day the policy change comes into effect (if our actions in the run-up fail to prevent the change).

**Comment by RichardTaylor** [comment]
I'm not keen on private lobbying, I think we should operate in public, transparently.

**Comment by RichardTaylor** [comment]
Possible direct tweet:

>@example_council We think your plan to tell those making #FOI requests by email that they need to use a web-form instead is against the law. We urge you to reconsider. Hopefully @ICOnews can advise. [link to council page on WDTK] [[link to our blog on the subject](https://www.mysociety.org/2022/08/01/public-bodies-refusing-emailed-foi-requests/ )] [@mentions of relevant media/journalists]

One might expect councillors to be following such public correspondence with their council, and any media coverage might be expected to influence councillors.

**Comment by RichardTaylor** [comment]
New draft tweet which is more precise about what we think is against the law:

>@Council Refusing to process valid #FOI requests sent by email and telling those requesters they need to use a web-form is against the law. We urge you to reconsider. Hopefully @ICOnews can advise [link to council page on WDTK] https://www.mysociety.org/2022/08/01/public-bodies-refusing-emailed-foi-requests/ [@mentions of relevant media/journalists]

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
