### ISSUE TITLE
Declutter council pages

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1429]
Issues:

* Too many categories shown in the list
* Potentially too many notes boxes if we add others as we have done in respect of responsibility for education. 

eg.  https://www.whatdotheyknow.com/body/bradford_city_council
<img width="1081" alt="Screenshot 2022-10-01 at 22 56 41" src="https://user-images.githubusercontent.com/547695/193429835-37ec545e-0e7d-468e-8d4f-35f0c061fcf8.png">

Ideas: 

* Move the [excess] categories somewhere else on the page?

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
