### ISSUE TITLE
Mention the different repos earlier on the GitHub page on the wiki

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1430]
I think it would be better mention the different repos earlier on.

https://wdtkwiki.mysociety.org/wiki/GitHub

**Comment by FOIMonkey** [comment]
The issue with moving it up, is that we might want a new person to read the instructions/info first, but I agree it's not ideal as is.

It might make sense to split into two pages - one for with info on what GitHub is, how we use it, and most of the instructions etc and another with the Repo list on.

**Comment by RichardTaylor** [comment]
I have added a "Quick Links" line at the top of the page. 

I think this may resolve this issue. 

Strategically we want the wiki to both work as a guide for those new to WhatDoTheyKnow, or those not working on it regularly, as well as an operationally useful resource for all.

**Comment by FOIMonkey** [comment]
I still think splitting it would be a more elegant solution - we could then link to both from the main page. I'll create a repo page and see what that looks like.

**Comment by FOIMonkey** [comment]
https://wdtkwiki.mysociety.org/wiki/GitHub_repositories - We could make the main page link here, and keep the other page for instructions/info. I didn't list the mySoc repos there, because almost none of us can see those, but it'd be trivial to add them.

**Comment by WilliamWDTK** [comment]
I didn't necessarily mean a list of repos, but more referencing in the instructions to the fact that their are multiple.

Also some explanation about the differences.

**Comment by FOIMonkey** [comment]
Ah, got you. Mea Culpa. There would be a definite benefit to adding to/improving the current descriptions of what issues should go where.

**Comment by HelenWDTK** [comment]
Closing as complete (I think).
