### ISSUE TITLE
Update pro terms GDPR links so they point to UK GDPR in-line with the privacy statement for the free service

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1431]
Currently 

https://www.whatdotheyknow.com/pro/pages/legal

states:

>The legal basis for the processing of your payment information is Contract (this is as laid out in [6(1)(b)](https://gdpr-info.eu/art-6-gdpr/) – of the GDPR, in force from 25 May 2018). In general, the legal basis for processing your personal data on the site is Legitimate Interests ([6(1)(f)](https://gdpr-info.eu/art-6-gdpr/) of the GDPR).

Propose change to:

>The legal basis for the processing of your payment information is Contract (this is as laid out in [6(1)(b)](https://www.legislation.gov.uk/eur/2016/679/article/6) – of the UK GDPR). In general, the legal basis for processing your personal data on the site is Legitimate Interests ([6(1)(f)](https://www.legislation.gov.uk/eur/2016/679/article/6) of the UK GDPR).

We have already updated the links and references in this way in our [terms relating to the free service](https://www.whatdotheyknow.com/help/privacy#legal_basis), this ticket proposes consistency. 

Do we need to do anything special when making changes to these terms? It appears not, given they state:

> We reserve the right to update and change these Terms from time to time without notice and at our sole discretion.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
