### ISSUE TITLE
Present FOI & Transparency research papers on the front page

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1433]
A specific of https://github.com/mysociety/whatdotheyknow-theme/issues/791.

95% of our users won't necessarily read the papers, but it shows that we're about more than just running a service. 

Basically copy & paste of https://economicprinciples.org. Should be quite a quick win.

<img width="1618" alt="Screenshot 2022-10-04 at 17 23 21" src="https://user-images.githubusercontent.com/282788/193873175-ffe00b56-37a5-4e4a-ac33-a4cc088284f3.png">

The paper summaries can get quite long. We don't want to have to write lots of new content for updates, so I think just rendering the title and image is fine.

We should have a "[**Donate £10**](https://www.mysociety.org/donate) to support our research or [browse more](https://research.mysociety.org/section/research)" link at the end. 

I don't think [research.mysociety.org](https://research.mysociety.org) has a feed so we'd have to manually update them now and then, but that feels fine. Not worth a huge engineering effort as they're relatively low frequency. We can either just hard code the ones we want, or create a data structure and pick a random selection, along the lines of:

```ruby
@research_articles = [
  { title: 'Improving oversight of Access to Information',
    url: 'https://research.mysociety.org/publications/improving-oversight' },
  # and so on…
]
```

```erb
<% @research_articles.sample(6).each do |article| %>
  <div class="research-article">
    <!-- … -->
  </div>
<% end %>
```

**Comment by garethrees** [comment]
Some relevant papers

* [Improving oversight of Access to Information](https://research.mysociety.org/publications/improving-oversight)
* [Public FOI: Freedom of Information in central government](https://research.mysociety.org/publications/public-foi)
* [Freedom of Information in Local Government](https://research.mysociety.org/publications/freedom-information-local-government)
* [WhatDoTheyKnow and Central Government FOI](https://research.mysociety.org/publications/whatdotheyknow-and-central-government-foi)
* [Research into mySociety’s online Freedom of Information platform, Alaveteli](https://research.mysociety.org/publications/mysocietys-online-freedom-of-information-platform)
* [Clearing House](https://research.mysociety.org/publications/clearing-house)
* [Reforming FOI](https://research.mysociety.org/publications/reforming-foi)
* [FOI Monitor](https://research.mysociety.org/publications/foi-monitor)
* [Better case management of FOI and SARs: Research findings](https://research.mysociety.org/publications/case-management-foi-sars-research-report)

There's also some [WDTK-specific datasets](https://data.mysociety.org/categories/whatdotheyknow/).

**Comment by lucascumsille** [comment]
PR here: https://github.com/mysociety/whatdotheyknow-theme/pull/1542/files#
