### ISSUE TITLE
Correct or clarify statement on adding citations on the volunteering page

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1435]
At 

https://www.whatdotheyknow.com/help/volunteers

Under a list of tasks anyone can do we have:

>We always need help with promoting the good use of WhatDoTheyKnow. If you spot one of our requests being quoted in a news article or on a blog then you can add a citation to the request. 

Anyone can add citations via annotations, but adding links to the "in the news" section is not currently open to all.  What exactly do we want non-core volunteers to do, and how?

Related ticket:

* https://github.com/mysociety/alaveteli/issues/6886

**Comment by HelenWDTK** [comment]
Closing as complete
