### ISSUE TITLE
Review and improve the complaints process

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1436]
https://www.whatdotheyknow.com/help/complaints

Consider both the internal process and what we say publicly about it. 

Issues:

* We need a proportionate process which works given our resources. There's no point having a process if we don't have the resources to run it. 
  * Do we have the organisational size and structure to enable independent reviews of decisions
* Is escalating issues ourselves through the complaints process a positive thing, or something which leads to surprise from the point of view of a complainant if we tell them ~"we've already taken this case through our complaints process" and "we confirm our final decision". 
* Is a lack of objection to a proposed course of action from a group a complaint is escalated to sufficient to consider the matter escalated and approved? 

This was a core aspect of consideration of the ["review process changes" considered in February 2021](https://docs.google.com/document/d/1pIovTj5A7HpURCj0Q4CkC7oZyyIrtVTC3LvlLAjhFiM/edit#heading=h.bxx9ijqxi373), but I think that exercise was largely inconclusive, despite some changes and improvements being made.

**Comment by RichardTaylor** [comment]
Yesterday the WhatDoTheyKnow team discussed a complaints case on the regular "high risk cases" call. All those present had some exposure to the case. There were individuals with opposing views/suggestions on aspects of the case on the call. 

It was suggested that the process was a reasonable way to consider a complaint, even though it didn't involve an independent person reviewing the case. I think there was general agreement with that view. 

We currently tell complainants:
>you can request that another member of the team review what has taken place and seek to resolve the matter. 

I think what that is intended to mean is that a complainant can prompt a decision taking by one team member [acting alone, or from the complainant's perspective perhaps acting alone] and and ensure someone else in the team reviews it - as an initial step in the process of seeking to resolve a complaint.  

We don't currently promise an internal, independent, review, at an early stage of the complaints process; although from time to time where it appears practical and proportionate, we do carry out such reviews. 

Currently the final stage of referral to trustees would almost always amount to the complaint being considered by an independent group. However if the complaint is about a case which eg. poses significant legal or reputational risk, then it might have been escalated there before a complaint prompts such escalation too.  

Councils often fund solicitors to consider complaints externally and independently. That's expensive though. 

In the vast majority of cases where there is a complaint the complainant has can complain to the Information Commissioner - their service is free at the point of use - for both mySociety and the complainant and they offer that independent, external, regulation (and they have enforcement powers).

Other complaints can be pursued via other regulators eg. the Charity Commission.

**Comment by RichardTaylor** [comment]
I think its worth noting that the published complaints process was never designed, we just wrote down what we were doing. 

It appears there is a suggestion to have the "group including mySociety’s Chief Executive" consider a complaint and [if is not to be referred to the trustees] make a final decision on it. 

This would be a more active, and clear, action than merely considering the matter.

**Comment by mdeuk** [comment]
Linking to #1453, we need to ensure that any changes made are easy to understand… being a hopefully straightforward policy, this might be a helpful exemplar for this project.

**Comment by RichardTaylor** [comment]
Some progress has been made and the meaning of 

>"the matter is discussed internally with a group including mySociety’s Chief Executive to resolve it."

has been clarified internally 

https://wdtkwiki.mysociety.org/wiki/Complaints_policy

**Comment by RichardTaylor** [comment]
> Some progress has been made and the meaning of
> 
> > "the matter is discussed internally with a group including mySociety’s Chief Executive to resolve it."
> 
> has been clarified internally
> 
> https://wdtkwiki.mysociety.org/wiki/Complaints_policy

Further consideration of this point is on the agenda for the review call on 17 November 2022

**Comment by RichardTaylor** [comment]
We have recently discussed the threshold for considering a matter a complaint. 

We have some [old internal notes](https://wdtkwiki.mysociety.org/wiki/Complaints_policy#Legacy_material) which I interpret as saying that if a correspondent is providing new information, in other words that the case is being pursued, there's no need to trigger the complaints process and review by another administrator.  If the correspondent remains unhappy once the initial admin has pursued things as far as possible then it's a complaint, so another admin should review it. 

It has been proposed that the threshold for considering a matter a complaint becomes not merely that a correspondent remains unhappy, but that they actively ask for their case to be considered as a complaint.  A suggestion has been raised that this is in-fact our current policy. It is in-line with what we publish at https://www.whatdotheyknow.com/help/complaints but my view is that to-date we've proactively identified complaints and we've not relied on correspondents saying ~"I wish to complain" or similar. 

**Proposal** to proactively identify complaints. I don't think we should require someone who is unhappy with something we've done to say "I complain" or use similar "magic words" before we treat their concern as a complaint.  My view is this is a continuation of the current position, but others disagree. Our written policies do leave room for different interpretations. 

I think the issue we have is that our complaints process is disproportionate for low-level cases where a correspondent is merely unhappy with one administrator's decision, and the matter can be resolved by bringing in a second administrator. 

**Proposal**: not to escalate a case outside the admin team, until a review by a second admin has taken place and the correspondent is still unhappy, or where no second review has taken place within say two weeks. Sometimes the outcome/purpose of escalation is to seek a second admin to review the case.

**Comment by WilliamWDTK** [comment]
I made a comment in Slack today, to essentially say that it is not clear what the stages of the complaints procedure are. We always say, "Stage 1, Stage 2, Stage 3", but the stages aren't actually numbered.

It is also not entirely clear what the stages are.  This is something that ought to be clarified. A flow chart (both internally and publicly) might be nice.

**Comment by RichardTaylor** [comment]
The Independent Office for Police Conduct provide guidance to police forces on recognising complaints which we could take inspiration from:

>A complaint is any expression of dissatisfaction with a police force that is expressed by or on behalf of a member of the public... There must also be some intention from the complainant to bring their dissatisfaction to the attention of the force or local policing body. A complaint does not have to be made in writing, nor must it explicitly state that it is a complaint for it to be considered as one

https://www.policeconduct.gov.uk/sites/default/files/Documents/statutoryguidance/2020_statutory_guidance_english.pdf

**Comment by RichardTaylor** [comment]
From a [document comment](https://docs.google.com/document/d/1JyWDTx6HIPm06X__2xBP8LbMrN5fHERZBxqiFlr9wIM/edit?disco=AAAAody1hm8) on the phrasing we require complainants to use to have their complaint treated as a complaint:

>I also dislike requiring a "magic word", because it is an unnecessary bit of gatekeeping.

**Comment by RichardTaylor** [comment]
We now have an example of a concern which has not been treated as a complaint, perhaps due to the lack of magic words:

https://mail.google.com/mail?extsrc=sync&client=docs&plid=ACUX6DNJ8K7JJn5jBTxV3piuxHAHoOeOVkrbM3Q

https://docs.google.com/document/d/1TwkIS1dFjrum5TysIFAGJgrgRB17E3A5eWzMuU5H91o/edit#bookmark=id.3hu81paw64fb

**Comment by RichardTaylor** [comment]
We might want to consider what the purposes of our complaints process are. 

Presumably they include:

* Giving people an opportunity to resolve concerns with us promptly, and without involving regulators, or the courts. This is benefits both us, and those with concerns.  
* Enabling us to improve our policies and practices in-light of of concerns raised. 
* Ensuring decisions are made at an appropriate level within the organisation, and there are appropriate governance and oversight arrangements in-place covering the operation of the service. 
* Ensuring that we come to a final decision in cases where concerns are raised, and we communicate that clearly, enabling those with concerns to escalate them to regulators and the courts if they consider that appropriate.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
