### ISSUE TITLE
Add note to appropriate wiki page about what to do with Google Docs notifications in the inbox

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1437]

**Comment by FOIMonkey** [comment]
What are we meant to do with them? I tend to archive them after a while, but don't know if that's right.

**Comment by sallytay** [comment]
Yes that's what I do - that seems to be the best thing to do with them?

**Comment by garethrees** [comment]
I tend to delete them so that when I search for a case reference number I get _the cases_ rather than loads of threads containing comment & suggestion notifications. That history is stored within the doc itself.

**Comment by WilliamWDTK** [comment]
The reason I made the ticket is because I saw one, checked the wiki for what to do and couldn't find anything.

Unless it's one of the cases where an `@`-mention is made to draw attention to something, I was thinking that the email notifications don't add much, so could be immediately archived, rahter than left for an indeterminate time. Or, as @garethrees has proposed, deleted.

**Comment by FOIMonkey** [comment]
It'd never occurred to me that archiving them would clutter up the search results, but that makes sense. I'd be happy to start deleting them if it makes life easier.

**Comment by HelenWDTK** [comment]
I've added a note about deleting google docs notifications where the support account hasn't been @ mentioned for a specific reason as part of the mailbox triage steps on the support mailbox page. Closing as complete.
