### ISSUE TITLE
Produce policy on recognising GDPR requests

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1440]
On the wiki, we currently link to ICO guidance that isn't very detailed.

It might be good to have some sort of policy on recognising GDPR requests.

For example:
- What is the difference between a Takedown request and a GDPR RtE request?

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
