### ISSUE TITLE
New repo for 'running the site' tickets

### ISSUE THREAD

**Issue by confirmordeny** [mysociety/whatdotheyknow-theme#1441]
Consider creating a separate repo on GitHub for tickets which relate to how we run the site and not the code for the site itself.  Examples of things that could be moved to the new Repo include:

- Tickets about strategy.
- Tickets about new policies and policy changes.
- Tickets about the GDPR tracker.

This came out of a discussion on Slack.

**Comment by garethrees** [comment]
Not -1, but it does add complexity in managing access and adding overhead around the already tricky-to-answer "what goes where?" question.

> Tickets about the GDPR tracker

@mdeuk OOI, can the custom code for this be checked in to GitHub? That _would_ be worth a repo in its own right.

**Comment by mdeuk** [comment]
> > Tickets about the GDPR tracker
> 
> @mdeuk OOI, can the custom code for this be checked in to GitHub? That _would_ be worth a repo in its own right.

It can, at least… in theory. There isn’t any native support for Git (or indeed other version control systems), but [clasp](https://developers.google.com/apps-script/guides/clasp) can act as a broker here, so I don’t think it’ll be a problem.

A repo with the same permissions as the _other place_ might not be an awful idea, it’ll reduce further congestion from slow moving tickets. 😃

**Comment by confirmordeny** [comment]
I am going to close my own ticket here. We have discussed the idea and there are pros and cons.
