### ISSUE TITLE
Blog on meeting with the Information Commissioner's Office

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1444]
@ajparsons has [notes on a meeting with the Information Commissioner's Office](https://docs.google.com/document/d/1OEVfgbzKOwu1AZPX3CyAs3hDfcmb5yF_H2TPHmFzw0M/edit#heading=h.ybkc0mbqwg73) which could be spun into a blog post. 

We do have a policy of operating transparently.  How far this extends to campaigning and if campaigning should be done as publicly as possible is I think an open question. 

The blog could mention that if anyone wants to read about the meeting from the other perspective they could make a FOI request for the ICO's notes!

**Comment by ajparsons** [comment]
So my opinion on this one is I'm fine talking in a broad way that we are talking to the ICO and the kind of things we're talking about (and would throw a paragraph in if there was a transparency equiv of the month notes we do on climate), but the most best way to talk about several of the things in that meeting about is to wait until the ICO have published some things in public (and the most significant points had that in the near future) and talk about that then.

Would be interested in any other examples of best practice in this area.
