### ISSUE TITLE
Campaigning against public interest test delays

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1445]
Issue: Public bodies can delay responding to requests for information by saying they are taking time to consider if the public interest is served by releasing the information in question, or not. 

**Background:**

* Many of the exemptions in the Freedom of Information Act are subject to a public interest test. ([See Section 2 of the Act](https://www.legislation.gov.uk/ukpga/2000/36/section/2))
* There is no legal deadline for a FOI response once a public interest test is being considered. Bodies have: "until such time as is reasonable in the circumstances" to respond. ([See Section 10(3) of the Freedom of Information Act](https://www.legislation.gov.uk/ukpga/2000/36/section/10))
* 20 working days to consider a public interest test is set out as being "best practice" in the [FOI code of practice](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/744071/CoP_FOI_Code_of_Practice_-_Minor_Amendments_20180926_.pdf), however this is a weak document, it is only deemed "[desirable](https://www.legislation.gov.uk/ukpga/2000/36/section/45)" that public bodies comply. 

**Why speed of response matters:**
* A prompt response means if necessary a prompt appeal can be made. Slow public interest tests result in requests being stuck at the initial stage for too long. 
* Many FOI requests relate to newsworthy material, a key aspect of news is often its timeliness. Public bodies can avoid releasing material while the subject matter is newsworthy by delaying responses. 
* Timeliness is key for many other applications of material released via FOI. eg. activism often needs to be based on up-to-date information, or campaigners will be basing their campaigns on out of date material. FOI enables informed participation in public debate, it doesn't do that effectively if the information is out of date. 

**What we are already doing:**

* By running our public service we are publishing lots of evidence showing the public interest tests delay FOI responses. This can be used by the regulator, the Information Commissioner, and by others, seeking to enforce and improve information access rights. 

* We are collating evidence of public interest test delays. We have added a note added to [requests tagged pit_delay](https://www.whatdotheyknow.com/search/tag:pit_delay/all):
>>>We are concerned about the amount of time the Public Interest Test is taking in this, and other cases. We are collecting [examples of delays due to slow public interest tests](https://www.whatdotheyknow.com/search/tag:pit_delay/all) with a view to campaigning for quicker responses. [Contact us if you would like to help](https://www.whatdotheyknow.com/help/contact), especially if you have personal experiences to share.

**Points of caution:**

* It's important to get public interest tests right: 
   * we don't want to see material released where release would be contrary to the public interest. 
   * we don't want public interest tests to conclude more rapidly, but err more on the side of caution and not release so much material. 

**What we could do next:**

* Identify and tag more requests where there has been a public interest delay
* Analyse the dataset of requests where there has been a public interest delay
  * Could use sub-tags
  * Could shift data into a spreadsheet and pull out meta data eg.  if request is ongoing/complete. How long the public interest take took, or is taking, and what if the result was to withhold/release or release in-part.   
     * Do we need site features or developer help to enable this to be done efficiently? 
* Can we crowdsource, or recruit volunteers, specifically to work on identifying and analysing the data here?
* Do we need to do the hard work - is identifying the extreme cases enough?
* Can we get stories behind the delays from requesters, to explain the impact. 
* Monitor relevant referrals to the ICO and beyond. 
* Decide exactly what we want
  * If we want a law change, what do we want the new law to say?

**Possible outputs:**
* Ongoing publication of material on WhatDoTheyKnow, but better organised and presented. Continue to highlight the problem, but do that better. 
* Blogs, tweets, highlighting the issue. Drawing them to the attention of the ICO, public bodies, relevant media and those responsible for the public bodies in question. 
* Letters to MPs (encourage users to write via WriteToThem?)
* Write to the ICO
* Submissions to relevant Parliamentary committees

**Desired outcomes:**
* People get the information they want, and are entitled to, quicker.

**Comment by RichardTaylor** [comment]
New note text in light of the fact the note is on both completed and in-progress requests:

>We are concerned about delay in the consideration of the public interest test in this and other cases. We are collecting [examples of delays due to slow public interest tests](https://www.whatdotheyknow.com/search/tag:pit_delay/all) with a view to campaigning for quicker responses. [Contact us if you would like to help](https://www.whatdotheyknow.com/help/contact), especially if you have personal experiences to share.

**Comment by RichardTaylor** [comment]
We need to decide on a threshold for considering a request to be subject to a public interest test delay. 

Proposal: We tag requests where: "a response to a request has not been provided within the usual 20 working day deadline due to consideration of a public interest test". This would be akin to identifying requests where a "public interest test extension" has been claimed.

**Comment by RichardTaylor** [comment]
Is the exemption detection system good enough to identify cases of a public interest test exemption being claimed 

Do we want manual tagging of another class of request?

**Comment by RichardTaylor** [comment]
Note tweaked again:

>We are concerned about public interest tests delaying responses to requests for information. We are collecting [examples of such delays](https://www.whatdotheyknow.com/search/tag:pit_delay/all) with a view to campaigning for quicker responses. [Contact us if you would like to help](https://www.whatdotheyknow.com/help/contact), especially if you have personal experiences to share.

**Comment by FOIMonkey** [comment]
The Independent Commission on FOI recommended changes in 2016:

> Recommendation 1: That the government legislates to amend section 10(3) to abolish the public interest test extension to the time limit, and replace it instead with a time limit extension for requests where the public authority reasonably believes that it will be impracticable to respond to the request on time because of the complexity or volume of the requested information, or the need to consult third parties who may be affected by the release of the requested information. This time limit extension will be limited to an additional 20 working days only.

https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/504139/Independent_Freedom_of_Information_Commission_Report.pdf

**Comment by RichardTaylor** [comment]
Closely related:

* https://github.com/mysociety/whatdotheyknow-theme/issues/1183

**Comment by garethrees** [comment]
Linking back to another note on this topic https://github.com/mysociety/whatdotheyknow-theme/issues/1243#issuecomment-1271432213.

**Comment by garethrees** [comment]
> This request from August 2022 about Liz Truss’ trip to Brazil has been PIT’d again, meaning it has so far lasted 5.8x longer than her term as Prime Minister🥬 [[link](https://www.whatdotheyknow.com/request/liz_truss_brazil_2018)]

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
