### ISSUE TITLE
Improve coverage of bodies responsible for estate management schemes

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1447]
These bodies have powers akin to planning powers

https://www.whatdotheyknow.com/body/list/estate_management_scheme

* Can we list them comprehensively?
* Do we have the major ones covered?

At the time of writing we list:

* [Church of England](https://www.whatdotheyknow.com/body/church_of_england)
* [Grosvenor](https://www.whatdotheyknow.com/body/grosvenor)
* [The Dulwich Estate](https://www.whatdotheyknow.com/body/the_dulwich_estate)
* [Welwyn Hatfield Borough Council](https://www.whatdotheyknow.com/body/welwyn_hatfield_borough_council)

**Comment by RichardTaylor** [comment]
FOI request which could help with this:

https://www.whatdotheyknow.com/request/list_of_estate_management_scheme

**Comment by confirmordeny** [comment]
We now list ten. There is no central list as far as I can tell so hard to know how comprehensive our coverage is.

https://www.whatdotheyknow.com/body/list/estate_management_scheme
