### ISSUE TITLE
Blog on remaining FOI loopholes relating to bodies almost, but not entirely, owned by public bodies

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1448]
Follow-up on old blog 

https://www.mysociety.org/2010/01/20/foia-loophole/

Note examples of bodies "poisoned" by a small fraction of ownership/control/members by those other than public bodies, taking them out of FOI. 

https://www.whatdotheyknow.com/search/tag:poisoned/all

**Comment by RichardTaylor** [comment]
On dealing with "poisoned bodies" I see The Re-use of Public Sector Information Regulations 2015 covers bodies where more than half the directors/members are public appointees. 

>a corporation established or a group of individuals appointed to act together for the specific purposes of meeting needs in the general interest, not having an industrial or commercial character, and—
>
>(i)financed wholly or mainly by another public sector body; or
>
>(ii)subject to management supervision by another public sector body; or
>
>(iii)more than half of the board of directors or members of which, or in the case of a group of individuals, more than half of those individuals, are appointed by another public sector body;

https://www.legislation.gov.uk/uksi/2015/1415/regulation/3/made

We could seek to expand the scope of FOI to those bodies considered public bodies under The Re-use of Public Sector Information Regulations, some "poisoned" bodies, and partnerships of public bodies come into this classification.

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
