### ISSUE TITLE
Blog on listing bodies responsible for estate management schemes

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1449]
Following:

* https://github.com/mysociety/whatdotheyknow-theme/issues/1447

>We're now poking one of the UK's biggest beasts. We're listing the £55 billion pound Grosvenor Group, which is privately owned by one of the world's richest people: Hugh Grosvenor, 7th Duke of Westminster.  We're listing them on the basis of their planning powers over vast swathes of London.  https://www.whatdotheyknow.com/body/grosvenor

>This is a great example of how we think being subject to access to information law should in more cases follow the function of a body, rather than body ownership.

>Interestingly this also strengthens / broadens the grounds on which we list the Church of England as they have such powers too.

>What FOI requests might we expect to be made? Local councils assess planning applications against the "local plan", do these bodies have a local plan? What are their policies on allowing changes to properties to eg. add solar panels or exterior insulation? How are decisions made? Do they have something akin to a planning committee?

We could look at the degree of proactive transparency at these bodies. 

It would be great if there were some initial, example, FOI requests to these bodies before we drew attention them. 

We could put a note on them with suggestions about what could be requested. These could be based on material from the blog.

**Comment by RichardTaylor** [comment]
Twitter thread

https://twitter.com/WhatDoTheyKnow/status/1580869407412129792

In line with the escalation approach 
internal discussion > on site note/annotation  > tweet > blog  .....   [media coverage?, citations in debates?]

**Comment by RichardTaylor** [comment]
More blog text:

> Private landowners have a lot of power but normally that is about protecting their own interests - that isn't the case for estate management schemes. The schemes are only granted where "in the Minister’s opinion likely to be **in the general interest** that the landlord should retain powers of management in respect of the house and premises". (emphasis added). https://www.legislation.gov.uk/ukpga/1967/88/section/19The are very few mechanisms for holding the operators of these schemes to account - there is no electorate and as far as I know, no specific regulator. We can help fill the accountability gap.

**Comment by confirmordeny** [comment]
I think the time has passed on this.
