### ISSUE TITLE
Remove foi_no tag from bodies which are no-longer not subject to FOI 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1450]
The scope of FOI law was broadened via [S103 of the Protection of Freedoms Act 2012](https://www.legislation.gov.uk/ukpga/2012/9/section/103), making bodies owned by more than one public body subject to FOI. 

This was a law we lobbied for

https://www.mysociety.org/2010/01/20/foia-loophole/

**Comment by RichardTaylor** [comment]
I've removed foi_no and the associated note from 

https://www.whatdotheyknow.com/body/russell_group

**Comment by RichardTaylor** [comment]
Quick review of other bodies mentioned in the 2010 blog

* Connexions Nottinghamshire Limited  - doesn't appear to have been listed https://www.whatdotheyknow.com/search/Connexions/all 
*  Coventry and Solihull Waste Disposal Company – no foi_no tag https://www.whatdotheyknow.com/body/cswdc 
*  G-Mex Limited - not listed https://www.whatdotheyknow.com/search/G-Mex%20/all 
* Higher Education Statistics Agency (HESA)  - added foi_maybe tag rather then foi_no needs research https://www.whatdotheyknow.com/body/hesa
* [Manchester Airport PLC](https://www.whatdotheyknow.com/body/manchester_airport_plc) - up to date

**Comment by confirmordeny** [comment]
I think it is the vice chancellors (ex officio) who are the members of the Russell Group company rather than the universities. If I am right then that's another loophole.

**Comment by RichardTaylor** [comment]
>I think it is the vice chancellors (ex officio) who are the members of the Russell Group company rather than the universities.

We can check this via

https://find-and-update.company-information.service.gov.uk/company/06086902

The incorporation document has subscribers (members) signing "On behalf of the University of X", see from p43:

https://find-and-update.company-information.service.gov.uk/company/06086902/filing-history/MTc1OTM4ODg0YWRpcXprY3g/document?format=pdf&download=0

The latest memorandum and articles suggest members have to be higher education institutions. It indicates members are the subscribers and "such other higher education institutions as a a simple majority of all the appointed Directors ... shall admit". 

It's clear from that I think both the original members, and any new ones, are higher education institutions. 


https://find-and-update.company-information.service.gov.uk/company/06086902/filing-history/MzAwNTE4MjMyOWFkaXF6a2N4/document?format=pdf&download=0

Notably it is claiming to not to be subject to FOI as of 26 September 2022 

https://www.whatdotheyknow.com/request/2022_entry_admission_statistics_4#incoming-2131719

It could be "poisoned" by a non-public body member, but looking at [its member list](https://russellgroup.ac.uk/about/our-universities/) I don't think it is.  

Perhaps it could be "poisoned" by Scottish members? The Scottish members are not covered by Schedule 1 of the Freedom of Information Act so are not relevant public bodies for the purposes of  https://www.legislation.gov.uk/ukpga/2000/36/section/6 ?  I can't see anything online about a loophole for Scottish / UK mixed bodies.

**Comment by confirmordeny** [comment]
I have done some searches based on the "foi_no" tag and other relevant tags (e.g. company_owned_by_local_gov). 

As a result, I have removed "foi_no" from https://www.whatdotheyknow.com/body/veritau.

There were no other obvious cases where "foi_no" needed to be removed. I will close as complete recognising that a new issue can be opened if specific authorities are identified as needing to be recategorised.
