### ISSUE TITLE
Consider the GDPR s17 RtE template provided by the ICO

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1451]
Can we use this to improve our own?

I was thinking that when #1418 is completed, I'd transfer our existing responses to the improved format, which would be a good option to otherwise review their content.

>Lastly, you mentioned that it would be helpful to see a copy of the right to erasure template that the ICO’s own Info Access team use. I’ve attached it, just in basic Word document format. As I’m sure you appreciate, I need to say that it was drawn up for our internal purposes, is a working document, and using it doesn’t necessarily guarantee that you’re fully compliant - but I hope it’s useful to you as a reference, and please let me know if you have questions about it. As you probably know, but I can’t help saying, we have guidance here:[ Right to erasure | ICO](https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/individual-rights/right-to-erasure/). I’d advise that when you receive a request for erasure, you carefully consider the “When does the right to erasure apply?” section of the website guidance – when I was handling requests I was surprised by how many did not meet the criteria.
>
>We’ll be proactively disclosing more of our templates soon, and can flag that with you when it happens. Let me know if there’s anything in particular you’re interested in seeing.

**Comment by mdeuk** [comment]
A copy of the template referred to is now on the [team Google drive](https://drive.google.com/drive/u/3/folders/10_iFq2LezzDe9_kgzVqcai9TesXSG8BY).

We already do a good bit of what _this_ template covers - but there is certainly merit in looking at how others word things, and considering how we can adopt a more "user friendly" way of explaining what is, at times, quite a complicated matter.

Clear and simple explanations (aka [plain english](http://www.plainenglish.co.uk/)), and are of value to everyone, but are especially important for those who may have lower literacy levels.

Perhaps a question for our guru, @FOIMonkey: are we aware of any other "best practice" examples we can use as part of our consideration?

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
