### ISSUE TITLE
Check if coverage of legal regulators is comprehensive

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1452]
This could be based on:

https://legalservicesboard.org.uk/about-us/approved-regulators

A tag for these bodies might be helpful, and could aid with reviewing our coverage of them.

**Comment by confirmordeny** [comment]
We already have these ones: https://www.whatdotheyknow.com/body/list/approved_regulator

**Comment by confirmordeny** [comment]
Compare with: https://wdtkwiki.mysociety.org/wiki/Legal_services_regulators

**Comment by confirmordeny** [comment]
We have good coverage of approved regulators and a list of three unapproved regulators: https://wdtkwiki.mysociety.org/wiki/Legal_services_regulators
