### ISSUE TITLE
Update existing letter templates to use new style

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1454]
Following #1418, update existing templates.

I'll sort this myself for now.

# GDPR & Information rights
## Data breach
- [x] ICO covering letter
- [x] Breach through site misuse by employee
- [x] Body answering SAR through WDTK no ICO
- [x] Report to public body
## RtE
- [x] Confirm ID/material
- [x] Confirm ID/material (HMO)
- [x] FOI Officer Cont. pub.
- [x] HMO Landlord LI Resp.
- [x] RtE Rej.  LI Resp.
## SAR
- [x] SAR Response

**Comment by mdeuk** [comment]
LMK if you need a hand with this 👍

**Comment by WilliamWDTK** [comment]
I've now done all those listed.

I've combined both "Confirm ID/material" responses into one, since the HMO one only had two extra sentences.
