### ISSUE TITLE
Reconsider pros/cons of offering private requests

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1455]
Pros:

* Income from Pro service - which "private" requests is a part of. 
* Attracting requests which might not otherwise be made via WDTK, raising the possibility they will be published when acted on, or eventually published. 

Questions:

* Are we facilitating some requests being made in private which would be public if the private option wasn't offered?
* Are we pursuing transparency by offering a "private" option/
* Are the theoretical benefits materialising, or likely to materialise, to such a degree that its worth continuing to offer private requests?

Related:

* https://github.com/mysociety/alaveteli/issues/6567
* https://github.com/mysociety/alaveteli-professional/issues/578

**Comment by FOIMonkey** [comment]
> Are we facilitating some requests being made in private which would be public if the private option wasn't offered?

No. We are facilitating requests being made in private which would be made in private offsite if the private option wasn't offered. The vast majority of these are then published. Over time, this will tend towards them all being public due to the need to actively maintain an embargo.

> Are we pursuing transparency by offering a "private" option?

Yes. Pro has been a great success in taking large amounts of information out of journalist's inboxes and into the public domain. The private request feature is a key part of that.

> Are the theoretical benefits materialising, or likely to materialise, to such a degree that its worth continuing to offer private requests?

The evidence that I've seen so far suggests yes. I'd go further and say that we should promote/market it more.

**Comment by garethrees** [comment]
> Pro has been a great success in taking large amounts of information out of journalist's inboxes and into the public domain

I agree:

```ruby
# InfoRequests that have at some point been private that are now publicly searchable
InfoRequest.is_searchable.joins(:info_request_events).where(info_request_events: { event_type: 'set_embargo' }).size
# => 116,669
```

I do agree with https://github.com/mysociety/alaveteli/issues/6567, so it'll be interesting to see whether that makes material difference in the proportion of requests that are public-by-default vs intentionally private initially.

**Comment by RichardTaylor** [comment]
>Pro has been a great success in taking large amounts of information out of journalist's inboxes and into the public domain. The private request feature is a key part of that.

Is it happening in a timely manner when stories are published or when the embargoes expire though?

**Comment by FOIMonkey** [comment]
> Is it happening in a timely manner when stories are published or when the embargoes expire though?

I honestly don't think that matters. The transparency benefit comes from the fact that the source data is published at all when it otherwise would not have been.

**Comment by garethrees** [comment]
We can't _force_ people to make public FOI requests 🏑. We can only encourage 🥕. We need to play the long game. Maybe over time we'll raise the "difficulty" of making private requests (more clicks, price, limit on number of requests, whatever) ad/or reduce how long privacy periods can be, and many other options. Folding our arms and being dismissive of their needs isn't going to help us meet them where they are.

**Comment by RichardTaylor** [comment]
>  Is it happening in a timely manner when stories are published or when the embargoes expire though?
>> I honestly don't think that matters.

This appears at odds with our campaigns for speedier FOI responses.

**Comment by FOIMonkey** [comment]
> This appears at odds with our campaigns for speedier FOI responses.

Response times by authorities ≠ Publication times by journalists.

**Comment by RichardTaylor** [comment]
This could be a case of trying to breed better horses rather than focusing on inventing the motor car. 

We should probably pursue both though.
