### ISSUE TITLE
Campaigning against concerning use of the "information intended for future publication" exemption

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1456]
**Issue**
Public bodies can refuse to respond to requests for information on the grounds they intend to publish the information in the future. 

Bodies which have used the "information intended for future publication" exemption may may not publish the information in the manner, and at the time, they said they would, or might not publish it at all. 

Reference:

https://www.legislation.gov.uk/ukpga/2000/36/section/22

**Comment by RichardTaylor** [comment]
Campaigning tag and note initiated:

https://www.whatdotheyknow.com/search/tag:s22_concerns/all

**Comment by garethrees** [comment]
Linking back to a note on this topic https://github.com/mysociety/whatdotheyknow-theme/issues/1243#issuecomment-1271805361.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
