### ISSUE TITLE
Campaign to improve access to information held by partnerships of public sector bodies

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1458]
**Issue**
Many prominent bodies with key public roles may not really exist, they might not be considered to be a legal entity / body corporate for the purposes of FOI law. Obtaining information held by these bodies can be challenging, individual members might claim not to hold the information, and the bodies themselves may claim not to exist. 

**Sets of bodies this might impact**

* [Local Safeguarding Children Partnerships](https://www.whatdotheyknow.com/body/list/lscp)
* [Safer roads, or safety camera, partnerships](https://www.whatdotheyknow.com/body/list/srp)
* [Local Resilience Fora](https://www.whatdotheyknow.com/body/list/local_resilience)

Historic bodies this issue may have impacted:

* [NHS Sustainability and Transformation Partnerships](https://www.mysociety.org/2017/09/11/nhs-stps-foi/)

**Relevant body tags**

* https://www.whatdotheyknow.com/body/list/denies_existing 

**Scotland**
This might not be an issue [in Scotland where partnerships are legal entities](https://www.legislation.gov.uk/ukpga/Vict/53-54/39/section/4?view=extent#extent%3Dscotland). 

**ICO guidance**

para 32
https://ico.org.uk/media/for-organisations/documents/2614663/information-held-by-a-public-authority-for-purposes-of-eir.pdf
repeated at para 34
https://ico.org.uk/media/for-organisations/documents/1148/information_held_by_a_public_authority_for_purposes_of_foia.pdf

**Potential positives**
If the right to access information held by a partnership does not rely on all members being public bodies, this means partnerships cannot be "poisoned" and taken out of the scope of FOI by the presence of members which are not public bodies. 

**Actions** 

* Continue to list relevant "bodies"  
* Provide advice to users on relevant body pages on WhatDoTheyKnow (need to decide on an approach)
  * List just like any other body?
  * List but suggest users make requests to a partner which is clearly subject to access to information law? 
  * List with advice and let requesters decide which approach to take
* Collect examples of cases where this issue caused a problem.

**Comment by garethrees** [comment]
Linking back to note on this topic https://github.com/mysociety/whatdotheyknow-theme/issues/1243#issuecomment-1284431419

**Comment by RichardTaylor** [comment]
There's a recent relevant ICO decision notice (from November 2022) requiring a council to provide information which they suggested was only held by the Safeguarding Adults Board, and not by the council, even though the council was a member of the board:

https://ico.org.uk/media/action-weve-taken/decision-notices/2022/4022789/ic-174594-n0n9.pdf

While the decision was in favour of the release of material in this case, it relies on the council having a reason to hold the material "for its own purposes". It actually I think shows the need to make these partnership bodies subject to FOI. It does also though provide a route for requesters to get some information relating to these bodies now.

**Comment by RichardTaylor** [comment]
Noting a new type of partnership we've come across, medical schools run by multiple universities eg. 

https://www.whatdotheyknow.com/body/bsms

**Comment by RichardTaylor** [comment]
While this ticket is linked to the proposed blog on ICPs / ICBs, just to explicitly note that Integrated Care Partnerships are a class of "body" to which this ticket may relate: 

https://www.whatdotheyknow.com/body/list/icp

**Comment by RichardTaylor** [comment]
From call discussion:

It's unlikely those drafting legislation will be keen on a non legal entity being made subject to FOI. 

This might be one for the ICO to solve via guidance. eg. suggesting that partnerships identify a "lead partner to deal with FOI requests" and perhaps advise that they should not argue they don't hold information on the grounds the partnership do, but they don't. 

[Do the ICO actually already have this guidance somewhere deep on their website?]

Another resolution might be to encourage legislators and government not to give civic responsibilities to partnerships.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
