### ISSUE TITLE
Offer specific advice about making requests in a neutral manner

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1460]
Types of request this relates to:

* Requests about the circumstances surrounding how someone left a job
* Requests about the complaints record of a regulated professional
* [There may be more]

We could consider adding advice on this point to:

* House rules
* Help pages
* Text next to the request box [probably not proportionate]

**Comment by RichardTaylor** [comment]
We could try and encourage, and enable, more effective requests in this area. 

Imagine motivations of requesters:

* Someone experiences what they consider unacceptable behaviour by a regulated professional. They want to use FOI to see if there are other similar reports, with a view to this strengthening any case they make to a regulator / employer for action. 

Is this a circumstance FOI can help in? Does FOI have a role in informing regulatory action? Is the right thing to do in our society to pursue concerns entirely privately? 

* Someone ceases to do an important and high-profile public role with no public explanation. Someone might journalistically, reasonably, want to find out what happened, and if there is a story, potentially a public interest story, there. 

We want to enable such requests, but encourage them to be made in way which doesn't cause us, or the requester, problems, and maximises the chances of a substantive response. 

* Someone may seek to misuse our service to defame or harass. 
While we want to assume good faith, we should recognise some people misuse our service.  While such people are perhaps unlikley to read advice, it might still be worth explaining that eg.  
   * we remove material which is extraneous to a request if it is drawn to our attention
   * we co-operate with the justice system, if a proper court order is obtained to provide user-data, we don't shield those who have criminally misused our service from the consequences of their actions.
   * we act to remove potentially defamatory material if it is drawn to our attention

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
