### ISSUE TITLE
Draft GDPR RtE response for request (not account) deletion

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1463]
Should refer to standard account closure options, but also option to move requests to separate account and anonymising them, leaving existing account intact.

**Comment by WilliamWDTK** [comment]
We have some modified ones for this, so shouldn't be too hard.

**Comment by WilliamWDTK** [comment]
>Alternatively, if it would satisfy you, we have one other option: we can leave your account as it is, and just transfer this request to a separate anonymous account, and remove your name from it in a similar way to the other option. This would make the request you are concerned about anonymous, but leave all of your other requests as they are, and you would retain access to your account.
>
>Please let us know if you would like to take us up on either of these offers, and specify which.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
