### ISSUE TITLE
Don't offer/promote referrals to the ICO for `foi_no`-tagged bodies

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1470]

**Comment by WilliamWDTK** [comment]
E.G., on updating [this request](https://www.whatdotheyknow.com/help/unhappy/2021_footfall_reports), I'm offered the advice of referring my request to the Information Commisioner.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
