### ISSUE TITLE
Review accuracy acknowledgement timescale note for body 2279

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1471]
[Gloucestershire Hospitals NHS Foundation Trust](https://www.whatdotheyknow.com/body/gloucestershire_hospitals_nhs_foundation_trust) ­– [body 2279](https://www.whatdotheyknow.com/admin/bodies/2279)

[Note 614](https://www.whatdotheyknow.com/admin/notes/614/edit) present since 2012.

Should acknowledgements still arrive within 2 days?

**Comment by sallytay** [comment]
From the information on the trust's website, the acknowledge timescale now appears to be out of date - there is no mention of two day acknowledgement

https://www.gloshospitals.nhs.uk/about-us/our-trust/freedom-information/
Says "Once we have received your request we aim to respond within 20 working days or sooner. When responding we will first state whether or not we hold the information you are looking for."

**Comment by RichardTaylor** [comment]
Looks like a very old note we should now remove.

**Comment by sallytay** [comment]
This has now been done and the note updated with some basic information about the trust
