### ISSUE TITLE
Consider listing inspectors / examiners

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1472]
Should we list those licenced to carry out 

* Gas safety inspections https://www.gassaferegister.co.uk/ 
* Boat safety inspections https://www.boatsafetyscheme.org/requirements-examinations-certification/arranging-a-bss-examination/find-an-examiner/

Should they be considered to have a public role if they are making assessments / judgments on behalf of the state (or which are required by public bodies)

**Comment by RichardTaylor** [comment]
Arose from considering:

* https://github.com/mysociety/whatdotheyknow-theme/issues/1466

**Comment by confirmordeny** [comment]
I have added Gas Safe as it is effectively a regulator: https://www.whatdotheyknow.com/body/gas_safe_register

**Comment by confirmordeny** [comment]
I don't think there is much to be gained in adding the boat safety examiners. They seem to be private individuals.

**Comment by confirmordeny** [comment]
In addition to public sector inspectorates/regulators, we have policies on listing exam boards and professional/trade bodies (essentially, we list those that control access to professions or perform regulatory functions). We also list the smaller 'independent' police forces. I can't think of many other instances where private organisations act as inspectors/examiners. There are cases where only people with specific qualifications can carry out checks e.g. MOTs but I am fairly sure we wouldn't want to add these individuals. 

See also: https://wdtkwiki.mysociety.org/wiki/Competent_Person_Scheme_Operators

Given the addition of Gas Safe and the analysis above, I will close.
