### ISSUE TITLE
Comprehensively list associations of local councils

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1474]
We list these bodies

https://www.whatdotheyknow.com/body/list/aolc

We have nine at the time of writing. 

We are probably not comprehensive in our coverage. 

There is a national association of local councils with a list of more local bodies:

https://www.nalc.gov.uk/about-county-associations

There are far more than nine on that list.

**Comment by confirmordeny** [comment]
In progress: https://wdtkwiki.mysociety.org/wiki/Associations_of_local_authorities

**Comment by confirmordeny** [comment]
We now have 66. Our coverage isn't 100% complete but it is reasonably comprehensive. I will close the issue.

https://www.whatdotheyknow.com/body/list/aolc
