### ISSUE TITLE
Make it so default/automatic prominance reasons for whole requests hidden as vexatious / SAR etc. can be used without editing

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1475]
eg. we have a current default prominence reason of:

>We consider it is not a valid FOI request as it was correspondence about your personal circumstances, and we have therefore hidden it from other users.
>
>If you would like to know what information a public authority holds about you, you should make a “Subject Access Request” in private. The Information Commissioner’s website provides advice on accessing your own personal information: https://ico.org.uk/your-data-matters/your-right-of-access

Which could become 

>We consider this was not a valid FOI request as it was correspondence about the requester's personal circumstances, and we have therefore hidden it from other users.

The text currently used is intended for writing to users, not as a prominence reason.

**Comment by WilliamWDTK** [comment]
If this is changed, I think it might be worth looking back at that point to see if we want to change any of the existing prominence reasons.

**Comment by HelenWDTK** [comment]
Closing in favour of https://github.com/mysociety/alaveteli/issues/7383
