### ISSUE TITLE
Change the body background colour from grey to white

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1478]
It's a matter of taste but I think this might modernise the appearance of the site, and make it look less unusual. 

Proposed:
<img width="1137" alt="Screenshot 2022-10-30 at 01 23 43" src="https://user-images.githubusercontent.com/547695/198857307-216172b5-432e-4d26-b273-e9109bda7121.png">

Current:

<img width="1140" alt="Screenshot 2022-10-30 at 01 15 47" src="https://user-images.githubusercontent.com/547695/198857324-a22bd0fe-785f-4a55-b89b-6ffc3e3b399b.png">

**Comment by RichardTaylor** [comment]
Related:

* https://github.com/mysociety/whatdotheyknow-theme/issues/791

**Comment by mdeuk** [comment]
Related:
- https://github.com/mysociety/alaveteli/issues/7252
