### ISSUE TITLE
Find email addresses for Integrated Care Partnerships

### ISSUE THREAD

**Issue by FOIMonkey** [mysociety/whatdotheyknow-theme#1481]
We list a good number of ICPs that we don't have contact addresses for. As these have now been established for a while, we should look at fixing this.

Current suggestions include

- Sending requests to ICPs to ICBs. 
- Making FOI requests to ICBs to ask for the ICP contact details.

**Comment by RichardTaylor** [comment]
>As these have now been established for a while

While the legislation has been in-place for a while the ICPs might not actually be in-place yet.  

One ICP met for the first time on 20 September 2022 - https://www.youtube.com/watch?v=lIpn3CgarHQ - others may not have been established yet. 

>Making FOI requests to ICBs to ask for the ICP contact details.

While our reason for making such requests would be to find contact addresses, we might find cases of ICPs not being established. 

Related:

* https://github.com/mysociety/whatdotheyknow-theme/issues/1244
* https://github.com/mysociety/whatdotheyknow-theme/issues/1415

**Comment by confirmordeny** [comment]
We made these into signpost pages in the end: https://www.whatdotheyknow.com/body/list/icp
