### ISSUE TITLE
Blog post on the ability to hide individual attachments on WhatDoTheyKnow

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1482]
Once the fix for

* https://github.com/mysociety/alaveteli/issues/1005

is live on WhatDoTheyKnow, and perhaps also after we've got a few examples of its use which we can talk about (which we could collect on this ticket) we should blog about the new feature and how it helps us pursue our principle of running the service as transparently as possible. 

We might want to note it may help us with legal issues in some, albeit rare, circumstances where issues can arise when material is taken down, which wouldn't have arisen if the material was published all-along. 

This is an excellent transparency feature we should talk about. 

I suspect it might warrant both a technical blog and a service-operation blog, this being the ticket for the latter.

**Comment by garethrees** [comment]
I've written up a draft https://docs.google.com/document/d/116GcyH153mcFSd3eDCn2J6PJDhuWjJlsG3RUnAPdWpA/edit#

**Comment by garethrees** [comment]
Couple of tiny comments left for someone to second-check, but just phrasing and not substance so this is good to go.

**Comment by MyfanwyNixon** [comment]
I've scheduled this to go out on the 24th - just to leave a gap between posts, though we can always change it if preferred.
