### ISSUE TITLE
Expand our coverage of Independent Monitoring Boards to cover boards for more short term holding facilities

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1485]

**Comment by RichardTaylor** [comment]
Seven more bodies have been added at

https://www.whatdotheyknow.com/body/list/sthf_imb

based on 

https://publicappointments.cabinetoffice.gov.uk/appointment/member-volunteers-needed-on-independent-monitoring-boards-imb-at-kent-coast-short-term-holding-facilities-sthf-south-and-east-short-term-holding-facilities-sthf-london-short-term-holding-fa/

**Comment by confirmordeny** [comment]
I think we now have them all. https://wdtkwiki.mysociety.org/wiki/IMBs_for_Short-Term_Holding_Facilities

**Comment by confirmordeny** [comment]
See also:
https://www.whatdotheyknow.com/body/list/sthf_imb
https://imb.org.uk/prison-volunteer/prison-volunteer-uk/be-a-prison-volunteer-in-scotland-northern-ireland/#STHF
