### ISSUE TITLE
Establish tag and tag-based note for bodies with a "journalism, art or literature" exception

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1488]
In FOIA 2000, these are:
- BBC ([body 32](https://www.whatdotheyknow.com/admin/bodies/32))
- Channel 4 ([body 682](https://www.whatdotheyknow.com/admin/bodies/682))
- Gaelic Media Service / Seirbheis nam Meadhanan Gaidhlig ([body 1152](https://www.whatdotheyknow.com/admin/bodies/1152))
- S4C ([body 683](https://www.whatdotheyknow.com/admin/bodies/683))

The only common tag between these bodies currently is `media`, which also applies to bodies not subject to this exception (like the British Film Institute ([body 4723](https://www.whatdotheyknow.com/admin/bodies/4723))).

All these bodies currently have a manual note, from which the proposed general note has been adapted.

**Proposed tag:** `media_exception`

**Proposed note:**
>Under the Freedom of Information Act 2000, you only have the right to information that is not held for the purposes of journalism, art or literature. Requests for information held for these purposes may be refused. If your request for information has been refused for this reason, and you don't think it should have been, don't hesitate to contact us.

**Comment by confirmordeny** [comment]
Done. https://www.whatdotheyknow.com/body/list/journalism_derogation
