### ISSUE TITLE
Add bank holiday for the Coronation of King Charles Ⅲ

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1490]
https://www.gov.uk/government/news/bank-holiday-proclaimed-in-honour-of-the-coronation-of-his-majesty-king-charles-iii:

>The Prime Minister has decided to proclaim an additional bank holiday to mark the Coronation of His Majesty King Charles III next year.
>
>The bank holiday will fall on Monday 8 May, following the Coronation on Saturday 6 May.

[. . .]

>The bank holiday will take place across the United Kingdom.

It does not yet appear on the [main bank holiday page](https://www.gov.uk/bank-holidays).

**Comment by mdeuk** [comment]
Although the SI for this hasn't yet been published, I think we've a good enough source - I've added it on Alaveteli and Tracker.

**Comment by RichardTaylor** [comment]
>I've added it on Alaveteli

That was meant to say WhatDoTheyKnow I think. 

Confirmed it's in WDTK  at `admin/holidays`

<img width="949" alt="Coronation of His Majesty King Charles III
2023-05-08" src="https://user-images.githubusercontent.com/547695/200955020-be9b04ee-85c6-4e95-878a-3ddb96e4c041.png">

**Comment by mdeuk** [comment]
> > I've added it on Alaveteli
> 
> That was meant to say WhatDoTheyKnow I think.

In this context, it is one and the same - but yeah, I mean the WhatDoTheyKnow instance of Alaveteli 😃
