### ISSUE TITLE
Consider creating inbox label to track replies to emails generated by third-party classifications of old requests

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1491]
There is an email of this nature in the inbox at the moment. I only create this issue rather than making the label myself as I didn't know what to call it.

**Comment by garethrees** [comment]
Couple of very off the top of my head suggestions to riff on:

* `Help: confused-by-classification`
* `Help: third-party-classification`
* `Help: old-classification`

**Comment by HelenWDTK** [comment]
I went with Help: old-classification
