### ISSUE TITLE
Provide a good explanation of what Environmental Information is.

### ISSUE THREAD

**Issue by FOIMonkey** [mysociety/whatdotheyknow-theme#1493]
This came up in relation to a support issue relating to one of the TOCs, and I'm ticketing it so I can archive the thread! 

We list a good number of bodies that are eir_only, so there is value in making sure requesters understand what information is covered. 

This could be through better notes on the authority pages, improving the help pages or a blog post that we could link to.

**Comment by confirmordeny** [comment]
See also: https://www.whatdotheyknow.com/help/glossary#environmental_information
