### ISSUE TITLE
2022 Moderation Report - Data Collection 5 (Users)

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1498]
Can we get stats from the site for the below; for the time period: 1 November 2021 - 31 October 2022
User Information

- [x] Total number WDTK users

- [x] Number of new users

- [x] Number of banned users

- [x] Number of user accounts anonymised at user's request in 2022

Data collection as last year's ticket https://github.com/mysociety/whatdotheyknow-theme/issues/925

Deadlines are:
Data collection by 24 November
The report is scheduled to be compiled week beginning 27 November
The annual report is scheduled to go out on 15 December

**Comment by garethrees** [comment]
# User accounts

```ruby
require 'csv'

from_date = Time.zone.parse('2021-11-01').at_beginning_of_day
to_date = Time.zone.parse('2022-10-31').at_end_of_day
period = from_date..to_date

users_created_before_cutoff = User.where('created_at <= ?', to_date)
users_created_in_period = User.where(created_at: period)
users_updated_in_period = User.where(updated_at: period)

# Total number of users created before the end date who've confirmed their email
active_total = users_created_before_cutoff.where(email_confirmed: true).count

# Number of users created within the given period who are still active
# i.e. confirmed their email, have not been banned, and have not closed
# their account.
new_in_period = users_created_in_period.active.count

csv = CSV.generate do |csv|
  csv << ['User accounts', 'Total']

  csv << [
    'WhatDoTheyKnow users with activated accounts', active_total
  ]

  csv << [
    "New user accounts activated in #{to_date.year}", new_in_period
  ]
end

puts csv
# User accounts,Total
# WhatDoTheyKnow users with activated accounts,239540
# New user accounts activated in 2022,16217
```

| User accounts                                | Total  | 
|----------------------------------------------|--------| 
| WhatDoTheyKnow users with activated accounts | 239540 | 
| New user accounts activated in 2022          | 16217  |
