### ISSUE TITLE
Respond to ICO consultation on prioritising access to information complaints

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1502]
https://ico.org.uk/about-the-ico/media-centre/news-and-blogs/2022/11/ico-launches-consultation-on-how-it-prioritises-foi-complaints/

We might want to suggest looking at WDTK to see if an issue is systemic, and prioritising systemic issues.

**Comment by RichardTaylor** [comment]
Deadline for responses is 19 December 2022.

**Comment by RichardTaylor** [comment]
This is being considered by mySociety internally at 

https://github.com/mysociety/policy/issues/16

**Comment by RichardTaylor** [comment]
On Tuesday the House of Commons voted against requiring the Government to release a bunch of documents https://www.theyworkforyou.com/debates/?id=2022-11-08b.180.0#g180.2 

That, and the ICO wanting to prioritise access to information cases in the public interest, prompted me to wonder about what, if any, role the ICO should take in respect of a request for those documents, or similar motions in Parliament. 

You could say a couple of hundred MPs want them released so they should be released...  or you could say the House of Commons has voted not to require their release so they shouldn't be released, and the ICO shouldn't presume to rule on something the House of Commons has voted on.

**Comment by garethrees** [comment]
Just tagging @ajparsons to add some notes about our thinking here. Don't want to just copy & paste from internal chat.

**Comment by ajparsons** [comment]
[Draft document](https://docs.google.com/document/d/1dQc_VFV7lu6F81UD8qbXDhz_tjbS0HNV_E0J2vO1Eqw/edit#)

(have incorporated general point above that the ICO appeal process is actually a bit late to really speed things up)

Would like some feedback ahead of a release next week or the week after? Want to give a week or so to see if we can get some comment from users/others.

There's a slight chicken and egg problem with the opinium polling blog post - but I'll think about that.

**Comment by RichardTaylor** [comment]
The ICO are considering prioritising complaints based on who made them. 

Could we cheekily suggest that a request being made in public via WDTK should be a factor in favour of a higher prioritisation, on the grounds the response will be available to all, so the potential for it to have public benefit / impact will be greater than a request made privately.

**Comment by RichardTaylor** [comment]
It's great that through the consultation document the ICO have published the basis on which they currently prioritise
certain cases.  

They should be transparent about what their new process/criteria is, and how it's working. 

Those making referrals should be told what the criteria for prioritisation are and given the chance to make the case that their referral warrants prioritisation.

Related:

* https://github.com/mysociety/whatdotheyknow-theme/issues/1003

**Comment by confirmordeny** [comment]
Since the deadline has passed, I think this can be closed.
