### ISSUE TITLE
Comprehensively tag bodies with Royal Charters `royal_charter`

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1505]
[2022-09-01 Record of Charters Granted (PDF)](https://github.com/mysociety/whatdotheyknow-theme/files/9975093/2022-09-01-Record-of-Charters-Granted.pdf)

Not all of them will be subject to FOI, so we should only add the tag to existing bodies. We might use it as inspiration for adding others.

I'll start some work on it, and add a comment with the page I get to. If someone else decides to work on it simultaneously, they can post a comment, assign themself, and start on the last page.

**Comment by confirmordeny** [comment]
We can also add a "ch:" tag to create a link to Companies House. For example: https://find-and-update.company-information.service.gov.uk/company/RC000688

**Comment by WilliamWDTK** [comment]
I've not individually checked ones I don't think are likely to be subject, which is all the various worshipful companies of XYZ.

Some aren't listed individually, like:
- Glasgow Royal Infirmary
- Dumfries & Galloway Royal Infirmary

Ones I've noticed that we might want to add (I've not researched them):
- ZSL
- Royal Institution of Chartered Surveyors

I've got to the end of 32, although it's not been 100% comprehensive.

**Comment by confirmordeny** [comment]
I would like to add RICS.

**Comment by confirmordeny** [comment]
From memory, there are two livery companies ('worshipful ..,') on the site as they have regulatory functions.

**Comment by confirmordeny** [comment]
I did the final page (page 67).

**Comment by WilliamWDTK** [comment]
I'm going to do a bit more, starting where I left of (32).

**Comment by WilliamWDTK** [comment]
Does anyone know what "Date sealed" means?

**Comment by WilliamWDTK** [comment]
Done-ish

I think there's a general issue to work out about transferral of charters between successor organisations.

It's not 100% clear whether the Royal Charter of the Victoria University of Manchester will have transferred to the successor University of Manchester in 2004.

Forestry Commissioners

Arts Council

Queen Elizabeth House

Westcott House, Cam

Chelsea Col, UoL

English sports council

That list is a bit of a mess.

Kings COll Lond

college of optometrists

Cyber security

**Comment by confirmordeny** [comment]
Hi WilliamWDTK, 
Does this link help?

https://find-and-update.company-information.service.gov.uk/company/RC000797

**Comment by WilliamWDTK** [comment]
See also the list from CH:
[Companies-House-search-results royal charter.csv](https://github.com/mysociety/whatdotheyknow-theme/files/9996090/Companies-House-search-results.royal.charter.csv), which can be worked on [here](https://docs.google.com/spreadsheets/d/1mO_FPxCuQS-kIEMJ7Eejsh_7c2hGMgEXLBve8kIV6j8/edit#gid=1838018219)

**Comment by confirmordeny** [comment]
I am going to close this because I think the original issue was substantially resolved (and perhaps fully complete). If there are specific gaps identified, a new issue or issues can be raised.
