### ISSUE TITLE
Delete the old-style letter templates (that have been replaced)

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1506]
Contained in the following:
- https://drive.google.com/drive/folders/1vuhmFNOtVH_fwikNuAmCvle1fuyptu6p
- https://drive.google.com/drive/folders/10Lb7jAUircJwWyinxolWgWi7LN2IxZtS
- https://drive.google.com/drive/folders/1o5BecBqQK_AC-W9EbYGk60kXICF5KngM

**Comment by mdeuk** [comment]
I would suggest moving them to an “Archive” folder so that we can make sure we’ve migrated all the relevant parts that we might wish to retain.

We could then delete this, after a reasonable period of time, perhaps in a month or so?

**Comment by FOIMonkey** [comment]
I created a template archive folder and have moved them all there.
