### ISSUE TITLE
Consider changing `surgery` category description

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1507]
https://www.whatdotheyknow.com/admin/categories/125/edit

**Current title:**
> NHS Primary Care Providers

No change proposed.

---

**Current description:**
> a NHS Primary Care Provider

**Proposed description:**
> an NHS Primary Care Provider

---

**To do:**

- [x] Cross-reference with style guide, and note results
- [x] Await feedback
- [x] Make change, or close this issue

**Comment by FOIMonkey** [comment]
+1 as N starts with a vowel👍

**Comment by WilliamWDTK** [comment]
Matches "FOI", see the [style guide](https://docs.google.com/document/d/12RER4ToOQfzBrsc_X1JXNGTUi7vOS-1okB_VCE9sum8/edit#heading=h.t4ow8r1merqf):
> *FOI* is pronounced as a set of initials, so (although spellcheckers don’t seem to like it) we talk about *an FOI request*, not *a FOI request*.

**Comment by WilliamWDTK** [comment]
I think this is sufficiently uncontroversial to just make the change, which I've now done.
