### ISSUE TITLE
Create and populate a new tag/category for bodies with degree awarding powers

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1508]
We have discovered "university" doesn't quite cover this, as there are bodies with degree awarding powers which are not universities eg. 

https://www.whatdotheyknow.com/body/london_business_school  (that body is though a constituent member of the University of London)

Proposed tag:

`awards_degrees`

Next step:

Add 

`awards_degrees` tag to all 287 bodies with "university" in their name or tags?  (We can do this via the bodies admin page, following a search for "university").

**Comment by confirmordeny** [comment]
I have created the tag/category: https://www.whatdotheyknow.com/body/list/awards_degrees

Some of the bodies with "university" in the name are not universities e.g. they are academy trusts, health boards or subsidiaries of universities. There are currently 155 public authorities with the new tag - definitely not a complete list.

**Comment by confirmordeny** [comment]
There are now 162 bodies in this category.  According to the OFS register, there are also 162 bodies with degree awarding power in the UK. The lists may not be identical but we have certainly created and populated a new category as per the issue that was originally raised.
