### ISSUE TITLE
Document processes relating to leaving unsent drafts in the inbox

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1509]
A good place to document this would be

https://wdtkwiki.mysociety.org/wiki/Support_mailbox#2._Process

The documentation should cover 

* when unsent drafts are, or can be, used as part of our process
* how to continue a thread, or escalate it, while leaving the draft intact. 
* why drafts are left unsent (presumably as sending them loses the formatting?)
* note that if comment from others is desired the draft should be escalated outside the inbox
* consider if the process works for those accessing the inbox in different ways eg.  IMAP / Web / Delegated Access

**Comment by WilliamWDTK** [comment]
The Inbox Monster has an impact on this, by allowing messages to be added to a thread which has only the initial message and a draft reply, whereas before this was impossible.

**Comment by confirmordeny** [comment]
Partially fixed by the "Inbox monster" ... remainder closed as not planned.
