### ISSUE TITLE
Assist users in obtaining information from .ods files

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1511]
From time to time the Government responds to a request to point to an already published .ods spreadsheet file on the Government website. 

While theoretically the Government using an open data standard is great, these files can be challenging for users to open and use. 

The Government do include[ a link to advice on using such files](
https://www.gov.uk/guidance/using-open-document-formats-odf-in-your-organisation#odf-compatible-software) next to every download link, although it isn't advice that's aimed at the public. 

Some requesters will be very happy with a response providing a link to an .ods file in which they can find the data they're seeking, others won't be able to obtain the information they're seeking via such a link. 

Things we could do:

* Upload the document to our Google Docs account and
  * Link to it from an annotation
  * Provide a link to the user privately
 * Extract the data requested from the sheet and paste it into an annotation. 
* Advise users that they can seek advice and assistance from the Government under FOI and any reasonable request as to a "means of correspondence" has to be complied with under Freedom of Information law. We could advise a user that they could respond to say the information is not reasonably accessible to them if it's in a .ods file (especially perhaps if extracting it requires some skills they don't have), and ask for their request to be reconsidered. 
* We could lobby public bodies and ask them to consider accessibility issues like this. 
* There could be a culture issue here. FOI officers might be more keen to issue a refusal linking to already published information, rather than being helpful.  Perhaps the FOI process in general, and especially in certain public bodies, discourages helpful and accessible responses.

**Comment by HelenWDTK** [comment]
Closing in favour of https://github.com/mysociety/alaveteli/issues/7027
