### ISSUE TITLE
Consistency of donation links

### ISSUE THREAD

**Issue by confirmordeny** [mysociety/whatdotheyknow-theme#1513]
On each WhatDoTheyKnow request page, there are three donation links. The first appears near the top on the right hand side next to a heart. The second and third appear in the footer in a blue button with the text "Donate Now". 

The blue button links to a WhatDoTheyKnow specific landing page with the heading "Help keep WhatDoTheyKnow running". The  first link is to a more general page (https://www.mysociety.org/donate/). 

I just wondered if the first link should also be to the WhatDoTheyKnow specific page.

**Comment by sallytay** [comment]
I would say that they should all be the same - unless there was a reason for the first link to be different but I can't think of one

**Comment by HelenWDTK** [comment]
These now go to the same place
