### ISSUE TITLE
Add information about (non-WDTK) complaints to resources page

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1515]
- [x] Police
- [ ] LAs
- [ ] Schools
- [ ] Home Office / Immigration
- [ ] NHS
- [ ] Other…

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
