### ISSUE TITLE
Translate house rules (`/lib/views/help/house_rules.html.erb`) to Welsh

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#1516]
The house rules document, when viewed on /cy is not translated into Welsh, making for a somewhat poor experience.

Thanks to @confirmordeny for bringing this up.

File: [/lib/views/help/house_rules.html.erb](https://github.com/mysociety/whatdotheyknow-theme/blob/master/lib/views/help/house_rules.html.erb)
Webpage: https://www.whatdotheyknow.com/cy/help/house_rules

**Comment by WilliamWDTK** [comment]
The translation has been completed.

https://docs.google.com/document/d/1RGXNfmdoehPhg0vltMQK5GJZLqQz53LU/edit?usp=share_link&ouid=105138457347886418603&rtpof=true&sd=true

**Comment by mdeuk** [comment]
> The translation has been completed.
> 
> https://docs.google.com/document/d/1RGXNfmdoehPhg0vltMQK5GJZLqQz53LU/edit?usp=share_link&ouid=105138457347886418603&rtpof=true&sd=true

This has now been templated, and PR #1521 has been raised.

Diolch, Helo Blod! 🏴󠁧󠁢󠁷󠁬󠁳󠁿
