### ISSUE TITLE
Decide and document policy on correction of errors/typos in request bodies/titles

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1527]

**Comment by confirmordeny** [comment]
Just to clarify is this about the name of authorities and the titles of requests?

**Comment by WilliamWDTK** [comment]
No, it's about the titles and bodies of the requests (or the initial or subsequent outgoing messages thereof):

![Screenshot showing general layout of a request to identify the parts concerned.](https://user-images.githubusercontent.com/99501342/224498198-3557c2e1-403c-4663-8f4e-c6a564cc8194.png)

Sometimes users ask us to correct errors or typos in the bodies or titles of requests. Changing the title can cause URLs to change, and any change, particularly if not just fixing a typo, but some larger error, can misrepresent correspondence.

**Comment by MattK1234** [comment]
Would also be good to think about when we notice things of our own accord, should we fix them or not?

**Comment by WilliamWDTK** [comment]
> Would also be good to think about when we notice things of our own accord, should we fix them or not?

I'd say not.

Also, I'd possibly be inclined to reject requests for this in all cases, but particularly:
- Where the change to the request's title would change the URL.
- Where the request has received a response / is particularly old.
- Where it would change the meaning.

I think we should decide a policy, or make it firmer from existing practice, document it, then write a template email response to requests for it to be done.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
