### ISSUE TITLE
Blog post about new generalised notes

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1530]
https://github.com/mysociety/alaveteli/milestone/58

**Comment by garethrees** [comment]
Got a [first draft](https://docs.google.com/document/d/18WhGUp2X2ItE23GzVT1NsXG393t7kFKSyOdGH-kL5SU/edit#) done.

**Comment by garethrees** [comment]
Just copying a quick chat about some workings out on how many notes we've added via tag:

> gareth Yesterday at 17:40
> Is it possible to find out how many records a note with a notable_tag applies? I want to say something like “So far, we’ve created X notes via tag which apply to Y records”
> 
> graeme 14 hours ago
> 
> ```rb
> Note.where.not(notable_tag: nil).pluck(:notable_tag).inject(0) { |n, tag| n + InfoRequest.with_tag(tag).count }
> # => 8009
> ```
> 
> graeme 14 hours ago
> 
> ```rb
> Note.where.not(notable_tag: nil).pluck(:notable_tag).inject(0) { |n, tag| n + PublicBody.with_tag(tag).count }
> # => 15642
> ```
> 
> graeme 14 hours ago
> 
> ```rb
> Note.where.not(notable_tag: nil).count
> # => 46
> ```
> 
> graeme 14 hours ago
> hmmm, those counts could contain duplicate requests/bodies
> 
> graeme 14 hours ago
> 
> ```rb
> Note.where.not(notable_tag: nil).pluck(:notable_tag).inject([]) { |a, tag| a += InfoRequest.with_tag(tag).pluck(:id) }.uniq.count
> # => 7998
> 
> Note.where.not(notable_tag: nil).pluck(:notable_tag).inject([]) { |a, tag| a += PublicBody.with_tag(tag).pluck(:id) }.uniq.count
> # => 15283
> ```
> 
> graeme 14 hours ago
> "So far, we’ve created 46 notes via tag which apply to 7998 requests and 15283 authorities"
> 
> gareth 3 minutes ago
> That’s incredible, thanks!
> 
> gareth < 1 minute ago
> At 30 seconds per note added manually ((7998+15283)/2) that’s 11640.5 minutes (11640.5/1440) – 8 full days , or 25 working days ((8*24)/7.5), if my maths is correct
>

**Comment by garethrees** [comment]
This is good to go. Title could be better, but good enough if we can't come up with anything immediately.

**Comment by MyfanwyNixon** [comment]
Agree this is good to go - I'll set it up in Wordpress.

**Comment by MyfanwyNixon** [comment]
OK - that's all ready and can publish out whenever.

**Comment by MyfanwyNixon** [comment]
I've scheduled it for Weds morning (we have another post going out tomorrow).
