### ISSUE TITLE
Blog post on addition of prominence_reason to entire request

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1531]
https://github.com/mysociety/alaveteli/issues/6746

Not a huge feature, but would be a good opportunity to talk more generally about our prominence options and how we always try to run the site transparently through adding a reason.

Could even add https://github.com/mysociety/alaveteli/issues/7214 without too much effort as a cherry on top for this post.

**Comment by WilliamWDTK** [comment]
I'll start working on a short blog for this. I'm not sure that [mysociety/alaveteli#7214](https://github.com/mysociety/alaveteli/issues/7214) has been implemented yet, but it may well be by the time a draft has been prepared, depending on my speed.

**Comment by WilliamWDTK** [comment]
A [document for the draft](https://docs.google.com/document/d/1fCf1-9lONgKTxn7n3ZHPjDjx_YJ_j7OsXC1F9PUtbOo/edit?usp=sharing) has been created.

**Comment by WilliamWDTK** [comment]
To be honest, aside from a couple of small things (small factual things, plus finding a cover image), I think the draft is ready to go, unless we do want to mention https://github.com/mysociety/alaveteli/issues/7214.

**Comment by WilliamWDTK** [comment]
Tagging @MyfanwyNixon to perhaps review it at some point

**Comment by MyfanwyNixon** [comment]
Thanks! I've also made a few suggestions but broadly happy with this. Let me know if you'd like me to do the necessary on Wordpress once it's ready, or if you're happy to.

**Comment by WilliamWDTK** [comment]
This has been scheduled for publication, so can probably be closed, since I see no reason to wait for it to be published before doing so.

**Comment by garethrees** [comment]
🎉 https://www.mysociety.org/2023/06/12/ever-more-transparency-for-alaveteli/
