### ISSUE TITLE
Manual WhatDoTheyKnow Transparency Report for 2023

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/whatdotheyknow-theme#1536]
A WhatDoTheyKnow Transparency Report was produced in [2021](https://www.mysociety.org/2021/12/16/whatdotheyknow-transparency-report/) and [2022](https://www.mysociety.org/2022/12/15/whatdotheyknow-transparency-report-2022/). 

This ticket is for a 2023 version.

**Comment by HelenWDTK** [comment]
Noting #1535

**Comment by RichardTaylor** [comment]
I'd like to more clearly separate the substantive takedowns from others; substantive being those involving the core substance of a FOI request/response.  

We might want to have various levels of "substantive" 

*  removing just one or two bits of personal data from a release; 
*  when we have to take a significant element of a request/response down (which is very rare)
*  when largely non-FOI correspondence includes, often incidentally / accidentally some element which could be seen as FOI

We know that we go to great lengths to avoid removing FOI requests/responses from public view, and ideally that would be reflected the report. To-date we've not really been collecting data on takedowns that really enables us to show how we've been able to preserve the archive of requests/responses. 

Preserving the archive is one aim, but we also want to do the right thing. Not every substantive takedown is bad.  Perhaps if the report did drill down to a handful of substantive cases, we could write a couple of sentences on each one.

**Comment by RichardTaylor** [comment]
>if the report did drill down to a handful of substantive cases, we could write a couple of sentences on each one.

Ideally we'd already have a blog on each one.
