### ISSUE TITLE
Promote WDTK to the Cardon Banfield Foundation

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1537]
We could contact the Cardon Banfield Foundation (CBF) and encourage them to use WDTK for proposed project to obtain information, including via FOI,  to "ensure that the spending of public finances in the effort to tackle homelessness is effective and transparent". 

They are currently recruiting volunteers to work on the project, including by making and following up FOI requests:

https://www.charityjob.co.uk/volunteer-jobs/cardon-banfield-foundation-cbf-/researcher/871605

Interestingly they've recently obtained an ICO decision notice (in November 2022) requiring a council to provide information which they suggested was only held by the Safeguarding Adults Board, and not by the council, even though the council was a member of the board. 

https://ico.org.uk/media/action-weve-taken/decision-notices/2022/4022789/ic-174594-n0n9.pdf

**Comment by RichardTaylor** [comment]
Decision notice noted at:

* https://github.com/mysociety/whatdotheyknow-theme/issues/1458#issuecomment-1355482877

**Comment by garethrees** [comment]
Great find! This might be a great organisation to reach out to as part of the JRCT project to help support marginalised communities. Will come back to this.

**Comment by HelenWDTK** [comment]
Closing as complete
