### ISSUE TITLE
blog post idea re adding National Centre for Circus Arts

### ISSUE THREAD

**Issue by confirmordeny** [mysociety/whatdotheyknow-theme#1540]
blog post idea re adding National Centre for Circus Arts

**Comment by confirmordeny** [comment]
The wording draft is here: https://docs.google.com/document/d/1R-sEAgo8vexF5smLbK2FzjvnjybB6xyIhqyZIL04SnM

**Comment by confirmordeny** [comment]
The blog post has been drafted now.

**Comment by garethrees** [comment]
Published! https://www.mysociety.org/2023/01/04/all-the-fun-of-the-foia/
