### ISSUE TITLE
Consider adding note to NHS England along the lines of their ~standard "Not Held" responses

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1544]
I.E.:

- NHS England ≠ The NHS in England
- Suggest contacting constituent parts etc.

**Comment by confirmordeny** [comment]
Here is an example of the 'not held' response: https://www.whatdotheyknow.com/request/nitrous_oxide_cylinders_stolen_f#incoming-593391

**Comment by confirmordeny** [comment]
I support this suggest even the term _**National** Health Service_ has the potential to cause confusion.

**Comment by WilliamWDTK** [comment]
Slightly different wording [here](https://www.whatdotheyknow.com/request/supplier_and_spend_details_3#incoming-1942697):

> NHS England does not hold information in relation to your request.
>
>This information may however be held by Berkshire West Clinical
Commissioning Group (CCG). As such, you may wish to redirect your enquiry
to Berkshire West Clinical Commissioning Group CCG at the following web
link:
>
>[2][https://www.berkshirewestccg.nhs.uk/cont...](https://www.berkshirewestccg.nhs.uk/contact-us/freedom-of-information-foi/)
>
>It may help to know that NHS England is not the same as ‘the NHS in
England’. The NHS in England is not a single organisation but is made up
of a range of organisations such as Hospitals, Clinical Commissioning
Groups (CCGs) and Ambulance Trusts. NHS England is responsible for
commissioning primary care services such as GP and dental surgeries, as
well as some specialised secondary care services. Therefore, any recorded
information NHS England may be able to provide in response to an FOI
request will generally relate to the services NHS England commissions.
>
>For information on commissioned services and the types of information NHS
England holds can be found on our [3]website and [4]publication scheme.
For further information on the NHS, its structure and other NHS
organisations please refer to the NHS [5]website.




>2. [https://www.berkshirewestccg.nhs.uk/cont...](https://www.berkshirewestccg.nhs.uk/contact-us/freedom-of-information-foi/)
>3. http://www.england.nhs.uk/ourwork/
>4. [https://www.england.nhs.uk/contact-us/pu...](https://www.england.nhs.uk/contact-us/pub-scheme/)
>5. [http://www.nhs.uk/NHSEngland/thenhs/abou...](http://www.nhs.uk/NHSEngland/thenhs/about/Pages/authoritiesandtrusts.aspx)

**Comment by confirmordeny** [comment]
I have added a note here: https://www.whatdotheyknow.com/body/nhs_england

I will therefore close.
