### ISSUE TITLE
Celebrate WDTK's 15th Birthday

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/whatdotheyknow-theme#1545]
WhatDoTheyKnow turns 15 in February 🥳

This is a huge milestone that we should mark in someway, both on the day itself and throughout the year.

I'm creating this as a place to collect ideas and suggestions.

**Comment by mdeuk** [comment]
As a first step, we have the **birthday cake** logos from the 10th birthday:
https://github.com/mysociety/whatdotheyknow-theme/pull/449
https://github.com/mysociety/whatdotheyknow-theme/pull/453/ (Pro)

These were removed in #573, so we'll need to restore them (or, perhaps jazz them up a bit first!).

**Comment by garethrees** [comment]
Linking to:

* https://github.com/mysociety/whatdotheyknow-private/issues/133
* https://github.com/mysociety/orgsites/issues/1270
* https://github.com/mysociety/research/issues/240

**Comment by RichardTaylor** [comment]
* Write to funders to given them an update on what's happened since. 
* Talk about longevity of the service and what it takes

**Comment by HelenWDTK** [comment]
Closing as complete (because of the blog), as I don't think anything else is planned, though I am sure it will be noted again as part of the 20th anniversary celebrations.
