### ISSUE TITLE
Review and publish details of what we mean by reactive moderation

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1547]
Our reactive moderation policy is public at:

https://www.whatdotheyknow.com/help/how

We have some internal notes covering: "activities which we don't consider are breaches of this general policy" at: 

https://wdtkwiki.mysociety.org/wiki/Reactive_moderation_policy

We could make those notes public. 

Also as noted internally we could consider expanding the scope of activities we do which could amount to proactive moderation.  

The key issue is the degree to which we can scan subject lines of requests/responses to look for notable material on the site. 

If we are proposing exposing ourselves to more risk as a result of a policy shift we should consider the changes on the risk call.

**Comment by RichardTaylor** [comment]
Closely related:

* https://github.com/mysociety/alaveteli/issues/2663

**Comment by RichardTaylor** [comment]
Closely related:

* https://github.com/mysociety/whatdotheyknow-theme/issues/1575

**Comment by HelenWDTK** [comment]
I think the current public policy is clear and there are no plans to change this.
