### ISSUE TITLE
List Students' Unions on WhatDoTheyKnow

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1549]
These bodies are generally not subject to FOI. 

They have the character of public bodies. 

They are akin to a local council for students. 

They control the spending of public funds. 

Listing them could aid student journalism, and encourage use of WhatDoTheyKnow by student journalists.

**Comment by confirmordeny** [comment]
I tend to agree that students' unions should be listed on WhatDoTheyKnow. We may want to begin in a modest way by only adding students' unions that receive £1 million a year or more in funding from public bodies.

**Comment by garethrees** [comment]
Hmm, I don't recall my Students' Union having a significant amount of power! I don't have an opinion either way yet, but I think we should flesh out some of these points.

> They are akin to a local council for students.

They do have elections and elected individuals contribute to decisions about the running of the organisation, but you could make the argument that companies have an elected board. That doesn't make them subject to FOI.

> They control the spending of public funds.

Presumably because they receive funds from the parent university? One could argue that they are no longer public funds once the uni decides to gift them to the SU. The Uni is accountable for sure, but not sure the SU ought to be accountable for receiving this funding.

**Comment by RichardTaylor** [comment]
>We may want to begin in a modest way by only adding students' unions that receive £1 million a year or more in funding from public bodies.

Alternatively we could start by listing Students' Unions for Universities, and add those for other bodies on request, or later.

**Comment by RichardTaylor** [comment]
>The Uni is accountable for sure, but not sure the SU ought to be accountable for receiving this funding.

The law explicitly makes a Students' Union "accountable for its finances"  [[Section 22(1) of the Education Act 1994](https://www.legislation.gov.uk/ukpga/1994/30/section/22)].  In addition almost all Students' Unions are charities and so their trustees are accountable for ensuring they operate in-line with the law, including when it comes to spending.  The Universities or other institutions do have a monitoring role. 

>Hmm, I don't recall my Students' Union having a significant amount of power! 

Generally the union would be the prime route for representing the views of students to the institution, including often via seats, and votes, on key committees.  They also regulate their own activities, buildings, etc.

**Comment by garethrees** [comment]
We do actually list [Birkbeck College Students' Union](https://www.whatdotheyknow.com/body/birkbeck_students_union).

Back in August 2018 (volunteers@ thread) we discussed our decision not to list the National Union of Teachers. A volunteer did some significant investigation into the case. On scanning the thread, one of the main points were essentially that one can opt out of being part of the union. That is true of SUs – one can move uni (though I don't think you can choose your SU independently of your Uni…)

What makes an SU different to these, or other trade unions? We don't appear to list other unions.

**Comment by RichardTaylor** [comment]
>We do actually list [Birkbeck College Students' Union](https://www.whatdotheyknow.com/body/birkbeck_students_union).

For the reasons given on its page. 

Generally listing Students' Unions is something we have considered, and to-date rejected, from time to time over pretty much the entire time WhatDoTheyKnow has been running.

**Comment by confirmordeny** [comment]
We made a decision to add students' unions of universities (but not of other educational institutions). We currently list 18: https://www.whatdotheyknow.com/body/list/students_union

**Comment by confirmordeny** [comment]
We now list over 100: https://www.whatdotheyknow.com/body/list/students_union

I will close here but this wouldn't prevent a new ticket being raised re closing gaps in coverage.
