### ISSUE TITLE
List professional bodies that act as money laundering supervisory authorities

### ISSUE THREAD

**Issue by confirmordeny** [mysociety/whatdotheyknow-theme#1550]
In some cases, professional bodies can act as money laundering supervisory authorities for their members. In other cases, the equivalent regulatory role is carried out by the FCA (e.g. for auction platforms and banks), the Gambling Commission (for casinos) or HMRC.

I would like to add the UK professional bodies that act as money laundering supervisory authorities to the site. By that, I mean the ones that are not already listed on the site. There is a list here:

https://wdtkwiki.mysociety.org/wiki/Money_laundering_supervisory_authorities

**Comment by RichardTaylor** [comment]
In other cases we've proposed writing a draft blog to explain why we're listing the bodies in question. 

We could also draft some text to be added to this class of body, again explaining why we list them. 

Presumably most, if not all, are not subject to FOI or similar access to information legislation. 

We do already list at least one

https://www.whatdotheyknow.com/body/bar_council

**Comment by confirmordeny** [comment]
Essentially, complete - see https://www.whatdotheyknow.com/body/list/mlsa
