### ISSUE TITLE
Adopt a policy of writing to relevant elected representives and other responsible individuals to alert them to poor access to information practices in bodies they are responsible for

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1551]
We have taken [such action in a data breach case](https://wdtkwiki.mysociety.org/wiki/Guidelines_for_handling_a_personal_data_breach#Reporting_to_Elected_Representatives_or_others_responsible_for_public_bodies), we could extend the practice to cover access to information issues. 

We could do this in public, eg. by sending concerns via Twitter and/or adding annotations to say what we've done.

**Comment by garethrees** [comment]
This seems unlikely as a default _policy_. It's worth having in a list of considerations for increasing escalation.

**Comment by confirmordeny** [comment]
closed as not planned
