### ISSUE TITLE
Blog on using Transparency International UK's integration with WhatDoTheyKnow to seek information on UK ministerial meetings

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1552]
Spin out blog from tweets in the thread at:

https://twitter.com/WhatDoTheyKnow/status/1612461387598512130

In addition to the material in the tweets we could note:

* The variation in the substance of responses, some are fulsome, others are surprising "not held" responses, or refusals to release anything more than what has already been reported.  Differences in application of the treatment of the personal information exemptions are notable.  
* There is at least one occurrence of a minister making the decision on if to release information about a ministerial meeting. 
* Even though these are requests to Government departments at least one has a very long overdue response.
* There is a lot of withheld material

We could note that we're in favour of proactive publication of material, and note the importance of timely release of material. 

The proactive release of the existence of these meetings is delayed, often by up to six months. 

We could suggest meeting information is released more promptly, and that the kind of basic information about the meetings should be proactively released too.

**Comment by RichardTaylor** [comment]
It was reported to the Community and Activism call that contact has been made with the site operators and it was suggested that the blog should await any response. 

I don't know what the content of this contact was or if it is accessible to the team in any way.

**Comment by RichardTaylor** [comment]
I have written a draft blog 

https://docs.google.com/document/d/1AoB6VSugJObIYeGNApJ3KPNY55US-0O_IeYvUMgPWmY/edit?usp=sharing

**Comment by ajparsons** [comment]
For me, it'd be good to hold on this a few weeks because I think this topic would fit well in the relaunched democracy newsletter and I'd like to be talking more to TI (and potentially openDemocracy, who had a campaign around this) before I do that. 

I think I'd write something shorter with a slightly different angle, and so there's no conflict with this more WDTK focused blog - but just want to have everything planned out to make sure we're making the most of all the opportunities.

**Comment by garethrees** [comment]
@ajparsons has said we're okay to go with this. I think so too; really nice blog and worth just getting it out there. @MyfanwyNixon, one to schedule at your convenience 🗞️

**Comment by MyfanwyNixon** [comment]
Thanks - will look to get this out tomorrow morning.

**Comment by MyfanwyNixon** [comment]
I put it live today in the end: https://www.mysociety.org/2023/02/16/opening-up-government-ministers-meetings-with-lobbyists/
- but will give it some promo on social media tomorrow.
