### ISSUE TITLE
Report substantive takedowns via the review process

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1554]
I think we should do this on the grounds substantive takedowns, the takedown of the core substance of FOI requests and responses, goes against our principles and aims and poses a reputational risk, which in-turn risks the service having the potential impact it otherwise might. 

Ideally we'd have [public, live, transparency over such issues](https://github.com/mysociety/alaveteli/issues/1203 ). There are though legitimate balances to be struck between transparency and other considerations eg. data protection. 

Related:

* https://github.com/mysociety/whatdotheyknow-theme/issues/1149

**Comment by HelenWDTK** [comment]
There are no plans to change the current escalation criteria or call structure at this stage. It think this aim is ultimately best served through #[1203](https://github.com/mysociety/alaveteli/issues/1203)
