### ISSUE TITLE
Header obscures jumplinks title

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/whatdotheyknow-theme#156]
When following a link to a specific section of the page, eg https://www.whatdotheyknow.com/help/requesting#quickly_response, the title is obscured by the black header.

![screenshot 2014-08-08 14 37 42](https://cloud.githubusercontent.com/assets/944656/3857222/33b562e0-1f01-11e4-84dc-8cb07ae60488.png)

**Comment by garethrees** [comment]
Closing this as it only affects admins. Its a bit annoying, but not worth the energy to fix.
