### ISSUE TITLE
Volunteer role - Takedown monitor

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1560]
Ideally we'd operate transparently enough such that anyone could look at a [public takedown log](https://github.com/mysociety/alaveteli/issues/1203) and monitor what we're removing, currently though only admins can see what is being removed, and to follow what's happening really needs monitoring of specific cases. 

The outcome could be reports to oversight eg. the review group or even trustees, or public reports via blogs. 

This might help us understand the decisions we're making, and transparency and oversight might help encourage better decisions. 

Related:

* https://github.com/mysociety/whatdotheyknow-theme/issues/1554
* https://github.com/mysociety/whatdotheyknow-theme/issues/1092

**Comment by WilliamWDTK** [comment]
One could perhaps envision this role being undertaken by a volunteer not otherwise involved in the process.

**Comment by garethrees** [comment]
Is there a first step of this that could be included in next year's [Transparency Report](https://github.com/mysociety/whatdotheyknow-theme/issues/1536)? What's the next "feature" we could add that's not too far away from where we are now?

**Comment by RichardTaylor** [comment]
>What's the next "feature" we could add that's not too far away from where we are now?

In terms of features we're getting into the realms of:

* https://github.com/mysociety/alaveteli/issues/1203

I've given that question[ some thought](https://github.com/mysociety/alaveteli/issues/1203#issuecomment-1384349965) though and making [an admin version of a takedown log](https://github.com/mysociety/alaveteli/issues/7519), presented as a filter on the existing admin timeline, might be a step forward.
