### ISSUE TITLE
Document policy on signing actions where authorship is not automatically clear 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1561]
* Contributions to Google docs from the support account. 
* Annotations made via the WhatDoTheyKnow account
* Emails sent from the support mailbox

**Comment by RichardTaylor** [comment]
>Contributions to Google docs from the support account.

This has been documented at:
https://wdtkwiki.mysociety.org/wiki/Collaborative_working

>Emails sent from the support mailbox

This is covered at 

https://wdtkwiki.mysociety.org/wiki/Support_mailbox#.E2.9C.8D.EF.B8.8F_2._Process

**Comment by HelenWDTK** [comment]
Closing as complete
