### ISSUE TITLE
Changes to inside information policy

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1562]
*  State that we are not concerned about information in FOI responses, where there are no complicating factors eg. accidental releases / failed redactions.
*  Use the review process and escalation via the review group / call to escalate issues. 

Internal discussion thread:

https://groups.google.com/a/mysociety.org/g/wdtk-volunteers/c/53uKEuSlh2Y

**Comment by RichardTaylor** [comment]
Becoming aware of material present in a private/embargoed thread might be a complicating factor.

**Comment by confirmordeny** [comment]
The above points have been considered. No action planned on this at present time.
