### ISSUE TITLE
Blog on potential for using WhatDoTheyKnow for investment research and news 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1563]
Outline:

* FOI and WhatDoTheyKnow are potentially great tools for obtaining information about listed companies to inform investment decisions. 
* Note that searches of WhatDoTheyKnow can be done to identify recently released information mentioning specific companies. 
* Conduct searches for an set of listed companies and note what's on the site.
* Give examples of the kind of FOI requests which have, or could be, made:
 * Requests on meetings between representatives of companies and government, and what they've been talking about. (Links to https://github.com/mysociety/whatdotheyknow-theme/issues/1552 )
 * Requests to local councils for early information on planing discussions (pre-application advice) which could reveal proposals to build new facilities etc.

Questions we could pose publicly if we're not certain of the answers:

*Is using material released privately to one individual via a FOI request to inform an investment decision "insider trading"? Is using the same material if released publicly via WhatDoTheyKnow not "insider trading"? 

Why?

* Encourage impactful use of the service, and potentially use by another class of potential requester. 

What we could do afterwards:

* Encourage specialist media to run articles based on ours. 
* See if [Bloomberg](https://www.bloomberg.com/professional/solution/bloomberg-terminal/) and similar want to buy/use some feeds? (Perhaps they're already incorporating FOI responses into their information services?)

Related:

* https://github.com/mysociety/whatdotheyknow-theme/issues/1562

Cautions:

* We should be clear we're not offering financial advice
* The author should declare, on the article, any interests in companies mentioned; and perhaps ideally the author should not have any interests in any companies mentioned. 
* Note https://www.bbc.co.uk/editorialguidelines/guidance/conflicts-of-interest/financial-journalism/ (they're not the law but they do give pointers to it)

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
