### ISSUE TITLE
Create a list of organisations/organisation types that we'd most like to see made subject to FOI

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/whatdotheyknow-theme#1564]
This came up on the last Community & Activism Call, and would be helpful from a campaigning point of view.

I think a good starting point would the list of foi_no bodies that we already have, and also the types of authorities that we are happy to list that can be found on the Wiki.

We will probably need a prioritisation ballot of some kind, but given the number of authorities, it will need further thought as to what that might look like.

We could try to generate a shortlist and throw it out to the users to decide.

**Comment by garethrees** [comment]
I think coming up with a list of potentials is a good idea and see what our "internal" agreement is like, but +1 on engaging the user community a bit in making these calls.

**Comment by RichardTaylor** [comment]
How about 

https://www.whatdotheyknow.com/body/list/foi_no

ordered by the number of requests made in the last 3 months to identify those our users appear most interested in making requests to?

If we could "collapse" the list at

https://www.whatdotheyknow.com/body/list/foi_no

so there was one entry for categories of body with lots of members our list would be shorter and easier to read (spreadsheet wrangling could achieve that)

I note

* https://github.com/mysociety/whatdotheyknow-theme/issues/1014

where our reason for not listing them is mainly I think that there's no need to serve our users, but we still want them subject to FOI I think.  

Linking also to

* https://github.com/mysociety/whatdotheyknow-theme/issues/1458 


Lastly we should take care over making clear if we want a body subject to public access to information law in respect of some, or all, or its activities.

**Comment by confirmordeny** [comment]
We have a fairly detailed list here: https://wdtkwiki.mysociety.org/wiki/Possible_additions_to_FOI
