### ISSUE TITLE
Consider tracking the fraction of support cases we deal with via "one touch" / "on first touch"

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1565]
In terms of monitoring if we're working efficiently looking at the the fraction of support cases we deal with via "one touch" / "on first touch" might be useful. 

Cautions:

* Elements of current processes eg. noting that a case has been logged creates messages on threads 

Reasons against using this as a metric:

* Could deter escalation and discussion

**Comment by HelenWDTK** [comment]
I had a quick look, and the 2022 data shows circa 73% of inbox threads contained 2 messages or less. 

In addition to the cautions that have already been noted, the messages that we send out when performing on site admin actions pass also pass through the support account. These will likely make up a large chunk of the threads that we didn't need to respond to at all, skewing the stats.

That said, I think there is merit in looking for patterns in the remaining 27% of cases as part of any wider analysis to look for site improvements that can reduce overall mail volume.

Relevant to #1546

**Comment by mdeuk** [comment]
> Just to add another cautionary note that makes inbox stats tricky - we've got spam in the inbox too, especially currently form derived spam.

We track that element already[^1] - https://github.com/mysociety/whatdotheyknow-theme/issues/1473#issuecomment-1328322365.

[^1]: There is a _rare_ case where this won't work (https://github.com/mysociety/whatdotheyknow-private/issues/163) - it doesn't happen very often.

**Comment by HelenWDTK** [comment]
Closing as complete via stats gathered as part of the annual inbox analysis.
