### ISSUE TITLE
Help page, or help page section, aimed at researchers seeking data about requests/responses on the site

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1569]
Much of the relevant material is at 

https://www.whatdotheyknow.com/help/privacy#research

and perhaps

https://www.whatdotheyknow.com/help/api
 
but having some content aimed at researchers might be a good idea.

**Comment by RichardTaylor** [comment]
Related

* https://github.com/mysociety/alaveteli/issues/7534

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
