### ISSUE TITLE
Clarify the note on the UKAEA

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1572]
The note for the [UKAEA](https://www.whatdotheyknow.com/body/ukaea) reads:

>Please note that the UK National Atmospheric Emissions Inventory is maintained by AEA.[\[1\]](http://naei.defra.gov.uk/)

It is not clear whether "AEA" is the same as "UKAEA".

**Comment by RichardTaylor** [comment]
The note appears out of date given 

https://naei.beis.gov.uk/about/ 

states:

>The UK National Atmospheric Emissions Inventory (NAEI) is developed and maintained by [Ricardo Energy & Environment](http://ee.ricardo.com/cms/), in collaboration with [Aether](http://www.aether-uk.com/), [UKCEH](http://www.ceh.ac.uk/), [Forest Research](https://www.forestry.gov.uk/forestresearch), [Rothamsted Research](https://www.rothamsted.ac.uk/), [ADAS](https://adas.co.uk/) and [Gluckman Consulting](http://www.gluckmanconsulting.com/).

The solution is just to delete the note. 

I've done that. 

In doing this the question of if to list, or mention, the "UK National Atmospheric Emissions Inventory" elsewhere arises, I've started a separate ticket for considering that:

* https://github.com/mysociety/whatdotheyknow-theme/issues/1573
