### ISSUE TITLE
List the UK National Atmospheric Emissions Inventory

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1573]
>"The NAEI compiles estimates of emissions to the atmosphere from UK sources such as cars, trucks, power stations and industrial plant. These emissions are estimated to help to find ways of reducing the impact of human activities on the environment and our health." - https://naei.beis.gov.uk/about-the-website 

Reasons against listing:

* It's not a body. It appears to be a system/project produced under a public sector [contract](https://bidstats.uk/tenders/2022/W44/785908032), rather than a public body. Lots of public bodies are involved in commissioning the system/project. 

Reasons for listing:

* It has a website https://naei.beis.gov.uk/ and a contact team/address. Requests to it might well get answered, it would serve our users to list it. 
* It is fulfilling an important public, statutory, role. https://naei.beis.gov.uk/about/national-inventory-system  

Options:

* List the main company which holds the contract for the system/project, in connection with its significant public sector contract/function. 
* Add a placeholder page for the "UK National Atmospheric Emissions Inventory" explaining what it is linking to related public bodies.

**Comment by RichardTaylor** [comment]
We could mention the "UK National Atmospheric Emissions Inventory" on the pages of bodies which fund it, those bodies are listed at https://naei.beis.gov.uk/about/

**Comment by confirmordeny** [comment]
Now added as a signpost page here: https://www.whatdotheyknow.com/body/naei
