### ISSUE TITLE
Help page section on why we don't list certain bodies we're often asked to list

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1574]
We could explain why we don't generally list eg. 

* Charities
* MP's offices
* Trade Unions

and offer advice. 

Could locate this near:

https://www.whatdotheyknow.com/help/requesting#authorities

**Comment by garethrees** [comment]
Had a request to add an independently operated leisure/community centre today. Feels like we've had quite a few of these over time.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
