### ISSUE TITLE
Devise and publish policy on when to shift to pre-moderation on a specific thread

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1575]
We've had two cases now I think where we've made threads requester_only so that we can pre-moderate responses prior to publication. 

We should write down when we do this. 

In the cases to-date the reasons for taking this exceptional action were:

* to seek to prevent the inappropriate release of a child's personal data, in a case where the risk of that occurring was present. 
* to attempt to reduce legal risk to mySociety 

Related: 

A ticket for doing it in a way which involves minimising the removal of material and doesn't require unpublishing whole threads:

* https://github.com/mysociety/alaveteli/issues/7557

**Comment by HelenWDTK** [comment]
Closing as precedent documented on wiki.
