### ISSUE TITLE
Consider accessibility impacts of our use of emoji

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1576]
We're using emoji in notes ([example](https://www.whatdotheyknow.com/body/nhs_mid_and_south_essex_integrated_care_board)), and there is a proposal to use them in the help pages. 

There are loads of guidelines / recommendations online. 

It appears we don't get to add/define alt text for emojis ourselves, they have text descriptors already inherently associated with them, so we should consider if those descriptors suit the situation we're using emoji in.  

Should we preferably be using icons with our own alt text rather than emoji? 

See also:

* https://github.com/mysociety/whatdotheyknow-theme/issues/1453#issuecomment-1283695760

**Comment by RichardTaylor** [comment]
Closely related - are we using emoji which have good cross-platform support?   (Noted as it appears we were using one internally that doesn't display on a Mac!).

**Comment by garethrees** [comment]
One thing that _is_ a little annoying with emoji is using them in URLs, or content (like headings) where URLs may be auto-generated.

An example of this is on MediaWiki where an emoji in the title creates much less readable page anchor in the URL.

<img width="311" alt="Screenshot 2023-02-03 at 14 51 55" src="https://user-images.githubusercontent.com/282788/216633739-e973bf80-8ea2-4b58-a831-153bc4191def.png">

<img width="350" alt="Screenshot 2023-02-03 at 14 51 59" src="https://user-images.githubusercontent.com/282788/216633766-eceba850-3938-4bc9-9292-a9fb15957338.png">

**Comment by garethrees** [comment]
Considered
