### ISSUE TITLE
Possible promotion of the search for a new mySociety Chair of Trustees

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1585]
In [this blog post on the internal blog about the search for a new Chair of Trustees](https://blogs.mysociety.org/internal/?p=10057) ([also covered publicly](https://www.mysociety.org/2023/02/13/could-you-steer-our-board/)), a suggestion was made about adding a note to external-facing email signatures to raise awareness. The suggestion was

> mySociety is looking for a new Chair of Trustees – could it be you? [Find out more and apply](https://apply.workable.com/mysociety/j/081CD0E3B2/).

We could also promote it through the WDTK Twitter account, or potentially a banner on-site.

**Comment by WilliamWDTK** [comment]
I've made an announcement [here](https://www.whatdotheyknow.com/admin/announcements/148/edit), but it's not publicly visible.

**Comment by HelenWDTK** [comment]
Thanks for this. I've added the link to the signature and added the banner to the site.
