### ISSUE TITLE
Restore recommendations to the review call agenda

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1600]
Recommendations were not included on the latest agenda. 

A reasoned recommendation associated with an agenda item is a common and I think helpful way of focusing discussion and aiding the meeting to come to a view. 

In exceptional cases multiple options could be presented in lieu of a recommendation.

**Comment by WilliamWDTK** [comment]
By way of reason for the change, @HelenWDTK [said](https://mysociety.slack.com/archives/CNH83HJP4/p1676365147779499):
> *This week* \[2022-02-16\] *I'm trying out changing "proposed action" on the risk agenda to "decision needed", because it says at the top, "discuss things - which actually need a decision", so that'll act as a natural filter.*

The idea seems to be that it will stop things being added to the agenda where no decision is required.

From what I recall, the general opinion was positive of the change, and I don't recall any objections being raised in the meeting. However, I can't find anything written to this effect.

Beyond the reason stated above, I personally think there's something to be said for keeping it lighter, and allowing people new to an issue to not be coming into something with a decision already proposed. Equally, having a ready-made decision could save time, and improve understanding for those not already involved in an issue (which is, of course, the purpose of review).

I think a sensible proposal here would be to continue to evaluate the performance of the agenda format, to see how it works in practice.

**Comment by HelenWDTK** [comment]
> From what I recall, the general opinion was positive of the change, and I don't recall any objections being raised in the meeting.

That's correct. I raised this in advance of the meeting and asked for feedback under AOB at the end of the meeting, which was entirely positive. I'm going to close this, as there are no plans to go back to the previous format.

If it seems like it's not working out, we'll just try something else. 

I'll update the template accordingly.

**Comment by RichardTaylor** [comment]
While it's not directly relevant to this ticket I note:
 
>stop things being added to the agenda where no decision is required

may result in the exclusion of cases on the basis they have been concluded (I suspect many people would be happy with this but it reduces the amount of review/oversight, and gives excessive focus to in-progress cases). 

To work with the new system perhaps there should be standing "decisions" on each case, prompting consideration of eg. if to reverse actions taken or if to make any related policy changes. 


See also: https://github.com/mysociety/whatdotheyknow-theme/issues/1557
