### ISSUE TITLE
Review rules for community and activism call agenda

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1609]
There are a long list of rules, many of which are not being followed, currently at 

https://wdtkwiki.mysociety.org/wiki/Community_&_Activism_call

**Comment by garethrees** [comment]
I've reviewed the page and made some minor phrasing tweaks. I'm happy that this page represents a good description of what makes these calls work well in general.

The point is that we've been doing this for a long time and have built up some documentation of what we think usually works well, and discourages things that we've found don't work well. At the end of the day, it's the Service Manger's discretion as to exactly how this gets put together.

There's been general positivity around the format recently, so we won't be allocating resource to review something that's working well.
