### ISSUE TITLE
Check if and where we've got a limit set on file uploads for those responding via the web-service and consider increasing it

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1611]
Noted in Slack that we appear to have a 50mb limit

**Comment by garethrees** [comment]
No limit; probably a timeout. No plans to change right now

**Comment by mdeuk** [comment]
> No limit; probably a timeout. No plans to change right now

Just noting - we definitely do have a limit, but it appears to be set at httpd level, as the error is generated by nginx.

To test, I generated two test files - 49mb and 51mb in size.

The 49mb file uploads using the officer form without issue, but, the 51mb is rejected (prior to upload), with the error:

```
413 Request Entity Too Large

nginx
```

I suspect there probably isn't much call for changing this, but thought it'd be worth noting anyway.

**Comment by garethrees** [comment]
Ah, we do have a bit of a "fun" setup with a few various layers. That'll be set above alaveteli installs. Either way, seems like an edge case that isn't routinely causing issues.
