### ISSUE TITLE
Decide if to list Local Government Pension Scheme Funds 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1612]
See

https://www.whatdotheyknow.com/body/local_government_pension_scheme

Where the notes currently state:

>There are 85 separate pension funds in the Local Government Pension Scheme.[[1](https://www.gov.uk/government/statistics/local-government-pension-scheme-funds-for-england-and-wales-2021-to-2022/local-government-pension-scheme-funds-for-england-and-wales-2021-to-2022-technical-notes)]

>A [list of Local Government Pension Scheme funds, along with the local authority which administers each of them can be found on the LGPS Scheme Advisory Board website](https://www.lgpsboard.org/index.php/client-list). Freedom of Information requests can be directed to the relevant local authority which acts as a fund administrator. Fund administrators are generally local councils, but also include the [London Pensions Fund Authority](https://www.whatdotheyknow.com/body/lpfa), [Transport for West Midlands](https://www.whatdotheyknow.com/body/tfwm), [The South Yorkshire Pensions Authority](https://www.whatdotheyknow.com/body/south_yorkshire_pensions_authority), [The Environment Agency](https://www.whatdotheyknow.com/body/environment_agency) and the [Northern Ireland Local Government Officers' Superannuation Committee](https://www.whatdotheyknow.com/body/nilgosc).

>There are a number of "Investment Pools" associated with the Local Government Pension Scheme, [we list these individually on WhatDoTheyKnow.com](https://www.whatdotheyknow.com/body/list/lgps_pool).

>The [The Local Government Pension Scheme Advisory Board](https://www.whatdotheyknow.com/body/the_local_government_pension_scheme_advisory_board) is also listed on WhatDoTheyKnow.

We only list one LGPS fund (rather than fund administrator) the [West Midlands Pension Fund](https://www.whatdotheyknow.com/body/west_midlands_pension_fund) 

Options:

1. Not listing LGPS pension funds and moving the requests from [West Midlands Pension Fund](https://www.whatdotheyknow.com/body/west_midlands_pension_fund)  to the [Wolverhampton City Council](https://www.whatdotheyknow.com/body/wolverhampton_city_council) page. (The responses come from the council.)
2. List all the pension funds as bodies. Mention and link to the body which administers them in the notes. This could serve our users well even if the funds are not actually bodies, many have websites and specific contact details. 
3. List all the pension funds as signposts, pointing to the body which administers them in the notes.
4. Don't list the pension funds but mention them in the notes of the body which administers the fund. 

I propose going with option 1.

**Comment by RichardTaylor** [comment]
A user has written by email to support option 1. 

They note: 

>>The biggest problem though I foresee, is that that this might make it more difficult to tag all the pension funds as to which pool they belong to. 

If we don't list the pension funds themselves we can't tag them as being members of a specific pool. We can't tag a body we don't list. 

What we can do is improve the notes on the pools to list the funds which make them up, this has been done at:

https://www.whatdotheyknow.com/body/northern_lgps

we could do it for the others.

**Comment by HelenWDTK** [comment]
A user has written in support of the second option, as they felt this might make it easier for other  users to navigate the data.

**Comment by HelenWDTK** [comment]
https://wdtkwiki.mysociety.org/wiki/Authority_suggestions

**Comment by confirmordeny** [comment]
I have moved the requests away from [West Midlands Pension Fund](https://www.whatdotheyknow.com/body/west_midlands_pension_fund) and made it a signpost authority

**Comment by confirmordeny** [comment]
We know list them all here as signposts: https://www.whatdotheyknow.com/body/list/pension_scheme
