### ISSUE TITLE
Tag, and add relevant note to, administrators of Local Government Pension Schemes

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1613]
For background see:

https://www.whatdotheyknow.com/body/local_government_pension_scheme

Not all fund administrators are currently tagged:

https://www.whatdotheyknow.com/body/list/lgps_fund_administrator

The tag could be added to ~80 local councils. 

Ideally we'd have a custom note for each council mentioning the name of the specific fund they administer.

**Comment by HelenWDTK** [comment]
https://wdtkwiki.mysociety.org/wiki/Tagging_suggestions

**Comment by confirmordeny** [comment]
I have tagged them: https://www.whatdotheyknow.com/body/list/lgps_fund_administrator

**Comment by confirmordeny** [comment]
A note has been added albeit not a custom note.
