### ISSUE TITLE
Prizes for finding interesting content

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1614]
mySociety is currently seeking proposals for work to identify environmental information information requests on WhatDoTheyKnow: 

https://www.mysociety.org/2023/03/06/call-for-proposals-environmental-information-regulations-how-are-they-working-in-practice-at-the-local-level/

One of the specific things the organisation is seeking to identify is:

>cases where information is being withheld under FOI but should have been considered under EIR

From a campaigning point of view it would be slightly more interesting to seek:

>cases where information is being withheld under FOI but should have been **released** under EIR

Offering a prize, or entry into a prize draw, for finding those might be a reasonable approach (ideally perhaps those for which the deadline for an appeal/challenge has not been reached)  . 

There are many other types of occurrence we're interested in finding for campaigning purposes too:

* Cases of public bodies refusing requests and directing requester's to their own web-forms (and other [authority performance issues](https://wdtkwiki.mysociety.org/wiki/Authority_performance_tags) we track).  
* Citations - linking FOI requests to news articles, research and other outputs

As for prizes, something mySociety could offer at little cost to them is a month's Pro access. This might also have the benefit of providing Pro to those who might make good use of it, generating more interesting and impactful content for the site. 

Cautions:

* "Needle in a haystack" kinds of cases might not be representative of wider use, so might not be as important as they seem. 
* Prizes might be a poor way of funding work, but could be of interest to some users.

**Comment by garethrees** [comment]
Linking to https://github.com/mysociety/alaveteli/issues/6253 as related.

**Comment by garethrees** [comment]
Going to close this as I don't think we realistically have the means to do this in any meaningful way right now.
