### ISSUE TITLE
Promote the Call for proposals – Environmental Information Regulations via WhatDoTheyKnow

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1615]
We could use the site-wide banner to promote:

https://www.mysociety.org/2023/03/06/call-for-proposals-environmental-information-regulations-how-are-they-working-in-practice-at-the-local-level/

**Comment by WilliamWDTK** [comment]
I've created and published a [announcement](https://www.whatdotheyknow.com/admin/announcements/149/edit).

># Interested in researching requests for environment information?
>
>To support mySociety's work on climate, we're looking for someone to research the use of requests for environment information of WhatDoTheyKnow. If you're interested, you can [find out more about the call for proposals](https://www.mysociety.org/2023/03/06/call-for-proposals-environmental-information-regulations-how-are-they-working-in-practice-at-the-local-level/).

![image](https://user-images.githubusercontent.com/99501342/224511828-e0bb481b-bf95-4b85-90a6-23b4f02ef460.png)

**Comment by RichardTaylor** [comment]
I've tweaked 

>environment information

to 

>environmental information 

and 

>information of WhatDoTheyKnow

to 

>information on WhatDoTheyKnow
