### ISSUE TITLE
Improve notes for Local Government Pension Scheme Pools so they all list the funds which make them up

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1616]
This has been done at 

https://www.whatdotheyknow.com/body/northern_lgps

We could do it for the other bodies at

https://www.whatdotheyknow.com/body/list/lgps_pool

Suggested by a user. 

Ticket arising from: https://github.com/mysociety/whatdotheyknow-theme/issues/1612#issuecomment-1456950550

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
