### ISSUE TITLE
Add section in house rules to cover abusive messages to mySociety staff/volunteers

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/whatdotheyknow-theme#1619]
Potentially link to mySoc's [Code of Conduct](https://github.com/mysociety/orgsites/issues/1318).

Suggest we add that threats and abusive language will result in:

- No further contact from mySociety staff
- A ban from using the site

As the same addition is being suggested across all mySoc's key sites - see https://github.com/mysociety/writetothem/issues/490 - let's make the messaging as uniform as possible.

**Comment by garethrees** [comment]
I think we can broadly change phrases like "in your requests or annotations" to "in your usage of the service", which would include user support, user to user messages, and any other route for user-generated content.

**Comment by HelenWDTK** [comment]
The main aim is to make this consistent, and to be clear what isn't acceptable. Hopefully we'll find appropriate wording that can work everywhere, (there is an identical ticket for each service).

There may be site specific changes that we want to make in addition. I think "usage of the service" still implies site usage, but it would be an improvement on what we have now.
