### ISSUE TITLE
Link to walkthrough blog posts?

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/whatdotheyknow-theme#162]
WDTK's Help pages are already pretty comprehensive, I know, but since I've recently written these walkthrough blog posts, it might be worth linking to them, maybe from a 'beginner's guide' section or similar.

They are:
- [x] How to make a Freedom of Information request https://www.mysociety.org/2014/08/15/how-to-make-a-freedom-of-information-request-with-whatdotheyknow/
- [x] Keep up with hot topics in your local area (ie, subscribe to your local council) https://www.mysociety.org/2014/09/19/how-to-keep-up-with-hot-topics-in-your-local-area/
- [x] Subscribe to FOI requests on any topic https://www.mysociety.org/2014/09/29/subscribe-to-foi-requests-on-any-topic/

**Comment by Gemmamysoc** [comment]
I've added links to these useful resources to the new 'Beginner's Guide' help page.
