### ISSUE TITLE
Review list of announcements and remove any outdated ones

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1620]
We have a [list of site announcements](https://www.whatdotheyknow.com/admin/announcements). I've just been through and removed 1 duplicate and a few that are definitely out of date (referring to surveys that have closed and deadlines that have passed).

This wasn't conclusive, so consider checking the rest. Particularly announcements [`94`](https://www.whatdotheyknow.com/admin/announcements/94/edit) and [`28`](https://www.whatdotheyknow.com/admin/announcements/28/edit)

**Comment by HelenWDTK** [comment]
Done 🙂
