### ISSUE TITLE
Local Gov re-organisation 2023

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#1635]
There are four unitary Councils forming on 1 April:
- Cumberland Council
- Westmorland and Furness Council
- North Yorkshire Council
- Somerset Council

We should use 'forthcoming' placeholders (https://github.com/mysociety/alaveteli/issues/7347) to create the new bodies, and relevant tag based notes to act as signposts between old and new. 

This is the parent ticket for changes - a child will be raised for each of the four unitaries.

**Comment by mdeuk** [comment]
Governance of Cumbria Fire and Rescue Service transfers from Cumbria County Council on 1 April, to the Cumbria PCC [^1].

We already list the PCC as [`body 14190`](https://www.whatdotheyknow.com/body/cumbria_pcc), but curiously, we don't list the FRS.

I have listed Cumbria FRS as `forthcoming` ([`body 153200`](https://www.whatdotheyknow.com/body/cumbria_fire_and_rescue_service)), and will add both to the updates for #1636 and #1637.

[^1]: as per [The Police, Fire and Crime Commissioner for Cumbria (Fire and Rescue Authority) Order 2022 S.I. 2022/1230](https://www.legislation.gov.uk/uksi/2022/1230/contents/made), [Fire England](https://fireengland.uk/news/home-secretary-approves-cumbria-pcc-proposal-take-responsibility-fire-and-rescue-service), and [local media](https://www.newsandstar.co.uk/news/20595753.cumbria-police-crime-commissioner-take-control-fire-service/) [reports](https://www.itv.com/news/border/2022-08-03/cumbria-pcc-to-take-control-of-cumbria-fire-and-rescue-service)

**Comment by HelenWDTK** [comment]
Closing as complete. Great work 👏
