### ISSUE TITLE
[#1635] Implement LG reorg for West Cumbria: Cumberland Council

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#1636]
This ticket covers the implementation of LG re-organisation in **West Cumbria**.  

## New organisation:
- [Cumberland Council](https://www.cumberland.gov.uk)

**⚠️ Note:** We currently list the Cumberland Shadow Authority - [`body 138728`](https://www.whatdotheyknow.com/body/cumberland_shadow_authority).

## Predecessors:
- Allerdale Borough Council - [`body 42`](https://www.whatdotheyknow.com/body/allerdale_borough_council)
- Carlisle City Council - [`body 108`](https://www.whatdotheyknow.com/body/carlisle_city_council)
- Copeland Borough Council - [`body 137`](https://www.whatdotheyknow.com/body/copeland_borough_council)
- Cumbria County Council - [`body 147`](https://www.whatdotheyknow.com/body/cumbria_county_council)

**⚠️ Note:** The functions of the County Council are being split between the two new unitary authorities.

## Relevant legislation / links
- [The Cumbria (Structural Changes) Order 2022](https://www.legislation.gov.uk/uksi/2022/331/contents/made)
- [Local Government Reorganisation - Delivering Two New Councils for Cumbria](https://newcouncilsforcumbria.info)
- [DLUHC Cumbria, Somerset and North Yorkshire councils direction: explanatory note](https://www.gov.uk/government/publications/cumbria-somerset-and-north-yorkshire-councils-direction/cumbria-somerset-and-north-yorkshire-councils-direction-explanatory-note)

Related
- #1635
- #1637

**Comment by mdeuk** [comment]
Bodies have been tagged with `lg_reorg2023` tags which are linked to tag based notes.

| Body | Tag addedr |
|--------|--------|
| Allerdale Borough Council | [`lg_reorg2023:west-cumbria`](https://www.whatdotheyknow.com/body/list/lg_reorg2023:west-cumbria) |
Carlisle City Council | [`lg_reorg2023:west-cumbria`](https://www.whatdotheyknow.com/body/list/lg_reorg2023:west-cumbria) |
Copeland Borough Council | [`lg_reorg2023:west-cumbria`](https://www.whatdotheyknow.com/body/list/lg_reorg2023:west-cumbria) |
Cumbria County Council | [`lg_reorg2023:cumbria`](https://www.whatdotheyknow.com/body/list/lg_reorg2023:cumbria) |

**Comment by mdeuk** [comment]
District and Borough Councils marked as `defunct` as of 12:01am with redirect in place to the successor body.

County Council marked as defunct, with redirect in place to the two new unitaries, along with the PFCC and FRS.

**Comment by HelenWDTK** [comment]
Closing as complete
