### ISSUE TITLE
[#1635] Implement LG reorg for East Cumbria: Westmorland and Furness Council

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#1637]
This ticket covers the implementation of LG re-organisation in **East Cumbria**.  

## New organisation:
- [Westmorland and Furness Council](https://www.westmorlandandfurness.gov.uk/)

**⚠️ Note:** We currently list the Westmorland and Furness Shadow Authority - [`body 138729`](https://www.whatdotheyknow.com/body/cumberland_shadow_authority).

## Predecessors:
- Barrow in Furness Borough Council - [`body 61`](https://www.whatdotheyknow.com/body/barrow_in_furness_borough_council)
- Cumbria County Council - [`body 147`](https://www.whatdotheyknow.com/body/cumbria_county_council)
- Eden District Council - [`body 184`](https://www.whatdotheyknow.com/body/eden_district_council)
- South Lakeland District Council [`body 353`](https://www.whatdotheyknow.com/body/south_lakeland_district_council)

**⚠️ Note:** The functions of the County Council are being split between the two new unitary authorities.

## Relevant legislation / links
- [The Cumbria (Structural Changes) Order 2022](https://www.legislation.gov.uk/uksi/2022/331/contents/made)
- [Local Government Reorganisation - Delivering Two New Councils for Cumbria](https://newcouncilsforcumbria.info)
- [DLUHC Cumbria, Somerset and North Yorkshire councils direction: explanatory note](https://www.gov.uk/government/publications/cumbria-somerset-and-north-yorkshire-councils-direction/cumbria-somerset-and-north-yorkshire-councils-direction-explanatory-note)

Related
- #1635
- #1636

**Comment by mdeuk** [comment]
Local media reports that there is a [new Parish Council due to be created for Barrow-in-Furness](https://cumbriacrack.com/2022/09/20/new-parish-council-for-barrow-set-to-be-created/). We should ensure that we list this.

**Comment by mdeuk** [comment]
Bodies have been tagged with `lg_reorg2023` tags which are linked to tag based notes.

| Body | Tag added |
|--------|--------|
| Barrow in Furness Borough Council | [`lg_reorg2023:east-cumbria`](https://www.whatdotheyknow.com/body/list/lg_reorg2023:east-cumbria) |
| Cumbria County Council | [`lg_reorg2023:cumbria`](https://www.whatdotheyknow.com/body/list/lg_reorg2023:cumbria) |
| Eden District Council | [`lg_reorg2023:east-cumbria`](https://www.whatdotheyknow.com/body/list/lg_reorg2023:east-cumbria) |
| South Lakeland District Council | [`lg_reorg2023:east-cumbria`](https://www.whatdotheyknow.com/body/list/lg_reorg2023:east-cumbria) |

**Comment by mdeuk** [comment]
District and Borough Councils marked as `defunct` as of 12:01am with redirect in place to the successor body.

County Council marked as defunct, with redirect in place to the two new unitaries, along with the PFCC and FRS.

**Comment by HelenWDTK** [comment]
Closing as complete
