### ISSUE TITLE
[#1635] Implement LG reorg for Somerset: Somerset Council

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#1639]
This ticket covers the implementation of LG re-organisation in **Somerset**.  

## New organisation:
- [Somerset Council](https://www.somerset.gov.uk)

**⚠️ Note:** This is a _**continuing authority**_ of Somerset County Council [`body 344`](https://www.whatdotheyknow.com/body/somerset_county_council)

## Predecessors:
- Mendip District Council - [`body 257`](https://www.whatdotheyknow.com/body/mendip_district_council)
- Sedgemoor District Council - [`body 334`](https://www.whatdotheyknow.com/body/sedgemoor_district_council)
- Somerset West and Taunton Council - [`body 91531`](https://www.whatdotheyknow.com/body/somerset_west_and_taunton_council)
- South Somerset District Council - [`body 360`](https://www.whatdotheyknow.com/body/south_somerset_district_council)

## Relevant legislation / links
- [The Somerset (Structural Changes) Order 2022](https://www.legislation.gov.uk/uksi/2022/329/contents/made)
- [About your new Somerset Council](https://www.somerset.gov.uk/how-the-council-works/about-your-new-somerset-council/)
- [DLUHC Cumbria, Somerset and North Yorkshire councils direction: explanatory note](https://www.gov.uk/government/publications/cumbria-somerset-and-north-yorkshire-councils-direction/cumbria-somerset-and-north-yorkshire-councils-direction-explanatory-note)

Related
- #1635

**Comment by mdeuk** [comment]
A tag based note has been added to the district and borough councils: 

| Body | Tag added |
|--------|--------|
| Mendip District Council | [`lg_reorg2023:somerset`](https://www.whatdotheyknow.com/body/list/lg_reorg2023:somerset) |
| Sedgemoor District Council | [`lg_reorg2023:somerset`](https://www.whatdotheyknow.com/body/list/lg_reorg2023:somerset) |
| Somerset West and Taunton Council | [`lg_reorg2023:somerset`](https://www.whatdotheyknow.com/body/list/lg_reorg2023:somerset) |
| South Somerset District Council | [`lg_reorg2023:somerset`](https://www.whatdotheyknow.com/body/list/lg_reorg2023:somerset) |

**Comment by mdeuk** [comment]
District and Borough Councils marked as `defunct` as of 12:01am with redirect in place to the successor body.

**Comment by garethrees** [comment]
Seems like an indexing [issue](https://groups.google.com/a/mysociety.org/g/alaveteli-dev-private/c/2w4lkKnSdO8/m/hS1MmwILAgAJ) here.

**Comment by mdeuk** [comment]
> Seems like an indexing [issue](https://groups.google.com/a/mysociety.org/g/alaveteli-dev-private/c/2w4lkKnSdO8/m/hS1MmwILAgAJ) here.

Yeah - it's the only one that seemed to malfunction. How very curious…

**Comment by gbp** [comment]
Fixed https://groups.google.com/a/mysociety.org/g/alaveteli-dev-private/c/2w4lkKnSdO8/m/k0XXBv0jAgAJ
