### ISSUE TITLE
[#1635] Mark South Yorkshire Passenger Transport Executive as defunct

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/whatdotheyknow-theme#1640]
South Yorkshire Passenger Transport Executive https://www.whatdotheyknow.com/body/sypte is being legally dissolved with effect from **31st March 2023** and the powers and functions vested in South Yorkshire Mayoral Combined Authority https://www.whatdotheyknow.com/body/south_yorkshire_mayoral_combined_authority.

**Comment by mdeuk** [comment]
Related:
- #1635

**Comment by mdeuk** [comment]
A tag based note has been added to SYPTE - this will get switched over on 1 April when we add the `defunct` tag, pointing toward SYMCA ([`body 52350`](https://www.whatdotheyknow.com/body/symca))

| Body | Tag added |
|--------|--------|
| South Yorkshire Passenger Transport Executive | [`lg_reorg2023:south-yorkshire`](https://www.whatdotheyknow.com/body/list/lg_reorg2023:south-yorkshire) |

**Comment by mdeuk** [comment]
SYPTE marked as defunct 2023-04-01 12:00am - redirect in place to SYMCA.
