### ISSUE TITLE
Tweak to policy for listing bodies which are not subject to access to public information laws

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1642]
Currently our key published explanation is that we list bodies which:

>aren’t subject to the Act but which we think should be

in recent discussions, and I think consultation responses, we've been saying that we're more concerned about access to public information held by organisations, rather than if making the organisations subject to FOI is, or isn't, the best way to make that information accessible. 

Recently we've been considering bodies which are responsible for public infrastructure such as schools, roads, and hospitals under "Private Finance Initiative" schemes.  We might want to list such bodies (generally private companies or companies owned by members from the public and private sectors), but don't necessarily want them to be subject to FOI directly.  We might be happy with improvements to the law and practice surrounding accessing information held by contractors in response to a request to the contracting public body. 

Enabling requests to PFI contract holders and showing how they are dealt with might help prompt changes to the law. 

We could add to our list of reasons for listing a foi_no body

> organisations holding public information which we think should be accessible via access to information laws

**Comment by HelenWDTK** [comment]
I think bodies that "aren’t subject to the Act but which we think should be" covers this off, so I'm closing this. We can revisit if we wish to expand our coverage at some point in the future.
