### ISSUE TITLE
Check local and private acts from the UK Parliament to identify new bodies to list

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1643]
See:

* [UK Local Acts](https://www.legislation.gov.uk/ukla)
* [UK Private and Personal Acts](https://www.legislation.gov.uk/ukppa)

Bodies I've spotted include those running cemeteries and those which would need some research eg. "Faversham Oyster Fishery Company".

There is a possibility we could also tag existing bodies and connect them

**Comment by confirmordeny** [comment]
now listed here: https://wdtkwiki.mysociety.org/wiki/Authority_suggestions
