### ISSUE TITLE
Add PFI hubs to the site

### ISSUE THREAD

**Issue by confirmordeny** [mysociety/whatdotheyknow-theme#1645]
Add all PFI hubs in Scotland to the site ... or at least those where there are contact details.

**Comment by RichardTaylor** [comment]
>or at least those where there are contact details.

I propose adding them all, with missing contact details if required. 

We have a linked inbox thread

There are five of these Scottish "hub companies", which are, or were, it appears, a vehicle for obtaining private investment for public infrastructure such as roads, hospitals and schools. We should consider them together:

    [hub South East](http://www.hubsoutheastscotland.co.uk/about)
    [hub East Central](http://www.hubeastcentralscotland.co.uk/)
    [hub North](https://www.hubnorthscotland.co.uk/)
    [hub West](http://hubwestscotland.co.uk/)
    [hub South West](http://www.hubsouthwestscotland.co.uk/)


We have listed one so far


https://www.whatdotheyknow.com/body/hub_east_central_scotland

I suggest a tag based note we can apply to all of them

**Comment by HelenWDTK** [comment]
https://wdtkwiki.mysociety.org/wiki/Authority_suggestions
