### ISSUE TITLE
Call the house rules something else

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/whatdotheyknow-theme#1663]
Whilst looking at strengthening the language around unacceptable behaviour, there's been a suggestion that we change 'House rules' to 'Conditions of use'.

I'm strongly in favour of changing the name. I tend not to use house rules when talking to users, and prefer to call them 'site rules' instead.

**Comment by RichardTaylor** [comment]
There is previous discussion on this point at:

https://docs.google.com/document/d/1ffX3BCFweAFH3QAWOP659HYvWYD9amdjTJ6O2uQ6ZjI/edit?skip_itp2_check=true&pli=1#bookmark=id.vnnxl9q07yi2

A concern raised was the language "House Rules" could be elitist. 

I think it's unusual language and using more common, plain English, would be preferable. 

I think:

> I recall “house rules” for social media was a fad from central government departments and similar many years ago that I think we followed.

was my contribution, see eg. 

https://gds.blog.gov.uk/social-media-house-rules/
https://www.gov.uk/government/organisations/planning-inspectorate/about/social-media-use#social-media-house-rules
https://www.google.com/search?q=site%3Agov.uk+"house+rules"

I don't think we should be following Government trends like this, doing something different would help show our independence.  


**Other Services**

* Facebook has "Community Standards" https://transparency.fb.com/en-gb/policies/community-standards 
* Reddit has the "Reddit Content Policy", which contains the site's "Rules" https://www.redditinc.com/policies/content-policy
* Twitter has "The Twitter Rules" https://help.twitter.com/en/rules-and-policies/twitter-rules
* Wikipedia has "Policies and Guidelines" https://en.wikipedia.org/wiki/Wikipedia:Policies_and_guidelines 
* There is a "Google Groups Content Policy" https://support.google.com/groups/answer/4561696?hl=en

**Comment by mdeuk** [comment]
I've added a PR - #1671 - which adds a couple of different `/help` urls as a redirect for the house rules. This will allow us to refer to them using a choice of phrases, as necessary, without breaking any existing links.

**Comment by garethrees** [comment]
WalesOnline uses "house rules", but that links to a "[Community Standards](https://www.walesonline.co.uk/community-standards/)" page.

![Screenshot 2023-05-12 at 10 10 23](https://github.com/mysociety/whatdotheyknow-theme/assets/282788/b76308c6-2d45-4560-a395-f04a7ae04405)

I like "Community Standards" as that's kind of what we're getting at – understanding that WDTK is a shared "place" and that we should be respectful of others while "in" it.

GitHub uses "Community Guidelines", but I think "Standards" sets the tone in a better way; it implies there are minimums that should be met.

![Screenshot 2023-05-12 at 10 13 07](https://github.com/mysociety/whatdotheyknow-theme/assets/282788/e4681928-d6db-4740-8c64-13ccf56dbf22)

**Comment by garethrees** [comment]
Linking to https://github.com/mysociety/whatdotheyknow-theme/pull/1665 which includes commits to use "Conditions of use".

**Comment by mdeuk** [comment]
“Conditions of use” probably fits our requirements a bit better.

We will need to ensure that we don’t break any links against what is already there - as `house_rules` is referred to in a lot of places (support emails and such).

**Comment by HelenWDTK** [comment]
I tend to use "site rules" when writing to users.

**Comment by confirmordeny** [comment]
The BBC's terms of use are written in a way that is fairly easy to understand: https://www.bbc.co.uk/usingthebbc/terms-of-use/
