### ISSUE TITLE
Review listing of TfL subsidiaries / external references

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1664]
Review whether we list TfL's listed subsidiaries, and, if not, whether/how we want to list them. TfL provide a helpful list on their website:

https://tfl.gov.uk/corporate/about-tfl/how-we-work/corporate-governance/subsidiary-companies

**Comment by WilliamWDTK** [comment]
It is listed with the DPR for TfL and LUL

**Comment by mdeuk** [comment]
Linking to:
- #1192 
- #648

I think we can repurpose _this_ ticket in order to correct the anomalies which have been noted in the existing listings.

**Comment by confirmordeny** [comment]
I think we should list each company separately

**Comment by HelenWDTK** [comment]
Closing as complete 🚇
