### ISSUE TITLE
Check the Freedom of Information (Removal of References to Public Authorities) Order 2023

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/whatdotheyknow-theme#1676]
A load of authorities have recently been removed from FOI. We should see if we still list any of these, as most will now be defunct:

https://www.legislation.gov.uk/uksi/2023/392/schedule/made

**Comment by mdeuk** [comment]
Pattern matching, based on the body names[^1], suggested we had 14 of the 34 bodies [listed](https://github.com/mysociety/whatdotheyknow-theme/files/11398917/Clipboard.2Exls-2.xls).

13 were marked already marked as defunct - with the remainder, the SEAC (body [4832](https://www.whatdotheyknow.com/admin/bodies/4832)) being marked as defunct on 2023-04-08.

[^1]: using OpenRefine to clean the dataset, cross-referencing the `all-authorities` extract.

**Comment by HelenWDTK** [comment]
Fab. Closing as complete.
