### ISSUE TITLE
Find `ch:` tags with less than 8 character values, and add leading `0`s as necessary

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1677]
Values preceeded by letters may not be affected, or, if they are, the zeroes may need to go after the letters. I've not fully investigated.

It might be good to have dev help to get a list of affected bodies, otherwise it may be very difficult. (Unless a volunteer analyses a download with a computer.)

**Comment by mdeuk** [comment]
I ran some queries in OpenRefine, against the all-authorities csv, and found **`27`** bodies with a `ch` tag that had less than 8 digits. All have now been padded out.
