### ISSUE TITLE
Make the language around real names more inclusive

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/whatdotheyknow-theme#1678]
We've had our attention drawn to the fact that our guidance on the use of real names in the privacy policy mentions women being able to use their maiden names after getting married. 

"Women may use their [maiden name](https://www.whatdotheyknow.com/help/glossary#maiden_name)"

A man can change their name as a result of marriage, and this also doesn't reflect name changes that are made following a civil partnership. This is probably due to the text mirroring the wording in the ICO guidance back in the day.

**Comment by garethrees** [comment]
"You can use your maiden name" would work in [the context](https://www.whatdotheyknow.com/help/privacy#real_name).

**Comment by mdeuk** [comment]
> "You can use your maiden name" would work in [the context](https://www.whatdotheyknow.com/help/privacy#real_name).

Aye, that would work.

In the end, I went with _If you have one, you may use your maiden name_[^1], on #1684. Hope that is OK.

[^1]: It could, equally, have been "You may use your maiden name, if you have one" - but, this seemed to work well enough.
