### ISSUE TITLE
Blog post on how we merge authorities

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1694]
More an internal process, but useful for alaveteli reusers.

Here's the general steps:

* Create the new authority with the correct new name & email address
* Mark the old authority as “defunct” (which keeps the requests, but prevents new ones)
* Add a note directly to the old authority with an link that points to the new authority and a short explanation. [Aberdeen College](https://www.whatdotheyknow.com/body/aberdeen_college) is an example on WDTK.
* In some cases, we might add a note to the new authority to explain the merge (See [North East Scotland College](https://www.whatdotheyknow.com/body/nescol) as an example)

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
