### ISSUE TITLE
Improved stats on volume per label per month

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1697]
An extension of https://github.com/mysociety/whatdotheyknow-theme/issues/1546 based on https://github.com/mysociety/whatdotheyknow-private/issues/219#issuecomment-1570247382.

We've now got [a prototype of volume per label per month](https://lookerstudio.google.com/u/1/reporting/8d277cd9-315d-43b7-86c8-8b592ba08aec/page/BZYTD/edit).

Couple of things would be useful to help us target improvements to make.

1. Use a single colour for the heatmap shading.
2. Reduce the set of labels to the ones we care about.
3. Incorporate a sparkline, or even better, run chart for each row.

**Comment by HelenWDTK** [comment]
3 is not possible in looker studio, but the run charts are here. https://docs.google.com/spreadsheets/d/13oFTpL0B-uBLRMIKdprnSqLflO5duUF2m0lWOvlBM2I/edit#gid=1656456109

For two, I added a dropdown filter at the top, so you can pick and choose.

**Comment by garethrees** [comment]
So good! 🙏
