### ISSUE TITLE
Add rotating pre-footer on high traffic pages

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1708]
…or maybe all pages – one for discussion.

We've built up a bunch of nice homepage sections:

* How it works
* Blog feed
* YouTube videos
* Research papers
* Newsletter signup
* …and many more that we could think up…

We could signal boost the content here by randomly picking one of these sections to render as a pre-footer. Here's a hacked in version.

![Screenshot 2023-06-15 at 17 47 40](https://github.com/mysociety/whatdotheyknow-theme/assets/282788/e2850c65-9cdc-4c9f-962e-00e8f19a4031)

We'd need to fix the margins/padding on the major page components. At present the footer has a top margin, which is not ideal when you want to render something that adjoins it. We might also want to cache the random section for a period of time for a given page.

**Comment by HelenWDTK** [comment]
I'm not a fan of this one.

**Comment by WilliamWDTK** [comment]
> I'm not a fan of this one.

For what reason(s)?

**Comment by mdeuk** [comment]
> I'm not a fan of this one.

I'm not a massive fan either.

The added "noise" might be a nuisance to some.

More pertinently, however, it also presents the potential of causing some accessibility problems, so it would need particular care to ensure that it doesn't make it more difficult for users to use the site.

It's not a "no", as I think some more review as to _what_ the idea is would be needed… but, I can't say I'd favour this just now.

**Comment by garethrees** [comment]
Just to clarify (and I appreciate this might not be clear from the initial description), I didn't mean rotating in the sense of an animated slideshow or carousel; just that on any given request page you may see a different section.

I'm open to suggestions. The reason for writing this up as an option is so that we give avenues for visitors to learn more about FOI and the work we do, why it's important, and how/why they should use their rights more.

**Comment by HelenWDTK** [comment]
> The added "noise" might be a nuisance to some.

☝️ This. I don't like the idea of shoving extra content onto that part of the request page. I think it'd make it look cluttered.
