### ISSUE TITLE
Add "Why FOI is useful" homepage section

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1710]
Our front page says _what_ wdtk/foi is, and _how_ to use it (the 1,2,3 and some examples of bodies and recent requests), but not _why_.

It would be good to put together a short list of why FOI/WDTK is a great utility. We do this for the [pro use cases](https://www.whatdotheyknow.com/pro/pages/journalists) but we don't make a good case for the situations in which FOI might be a good tool more generally.

A couple that come to mind:

* It can reveal key facts and figures https://www.mysociety.org/2023/06/15/foi-helps-campaigns-sometimes-in-unexpected-ways/
* It can be used to compare and contrast https://www.mysociety.org/2023/06/07/freedom-of-information-uncovers-inequalities-in-our-schooling-system/
* It can show demand for proactive publication
* You can build a new dataset
* It can show how or why decisions got made (e.g. meeting minutes)
* It sews seeds for others to dig in to (i.e. they see something interesting in your request that you didn't explore further)
* Requesting in public builds a set of templates for others https://www.mysociety.org/2023/06/13/paul-bradshaw-and-whatdotheyknow/

We'll need to hone this list down to our key messages. 6-8 items.

In terms of display, I was thinking emoji + bold key point + very short explanation + maybe a link to relevant content, if we have it.

<img width="781" alt="Screenshot 2023-06-16 at 11 23 31" src="https://github.com/mysociety/whatdotheyknow-theme/assets/282788/1e86a550-e92e-41ff-9afe-d7f45e3731e0">

**Comment by garethrees** [comment]
NB, we should probably sharpen the phrasing of "Why FOI is useful" – treat that as a working title.

The problem we're trying to tackle here is the kind of circular conversation like "FOI is great? Oh yeah, why? Because you can ask for anything and they more-or-less have to give it you you. Cool, but what should I ask for? Anything!"

Giving people mental models of approaches to take ("Find key facts and figures", "Compare and contrast", "Build a dataset", "Understand decisions", and so on) might help them apply FOI to their area of interest.

Hypothetically, let's say I'm interested in why my area of the city feels less green than others. Without a good understanding of these things, the best request I might be able to make is "Why does my area feel so concrete?".

With the above mental models, I might be able to construct a much better set of questions:

* Number of trees in my area (key fact)
* Number of trees in the fancy bit (compare & contrast)
* Number of tree protection orders in each (surface a dataset)
* Minutes of meetings where greenery has been discussed (understand decisions)

**Comment by garethrees** [comment]
For clarity, assigning @HelenWDTK to put together a first draft of these in a Google doc. Doesn't need to go to HTML until we're basically happy with the content.

**Comment by garethrees** [comment]
Just linking to [this](https://twitter.com/createstreets/status/1677921886204833793) which is a great example of showing people what to do.

**Comment by garethrees** [comment]
Here's a bit more of a fleshed-out example.

![Screenshot 2023-07-19 at 12 36 48](https://github.com/mysociety/whatdotheyknow-theme/assets/282788/2c6f4406-9f7c-40a7-a0e8-5de0bdcf83b9)

**Comment by garethrees** [comment]
* Fill in the gaps: build/extract a dataset that didn't exist
* Compare and contrast: contextualise behaviour/experience in one area against others

**Comment by garethrees** [comment]
For those on today's S&T, I'm [linking](https://docs.google.com/document/d/1PdzrBoKVsn85jkA4083nL-V5pEXwpK_281BPkjkhgL0/edit) to the WIP I presented on this. It's still private between Helen and I right now, so will let her publish here when she's comfortable with sharing.

**Comment by JenMysoc** [comment]
For gareth to review and deploy while travelling this week

**Comment by garethrees** [comment]
Just recording some WIP from a presentation I made that evolved this a bit by including some surrounding content (general what is FOI, then how WDTK helps)

![Chair of Trustees induction](https://github.com/mysociety/whatdotheyknow-theme/assets/282788/f2a90c23-0be0-446c-bf0a-e99df035a71f)

![Chair of Trustees induction (1)](https://github.com/mysociety/whatdotheyknow-theme/assets/282788/edcbed47-cc92-4f07-bdfe-e4027fd43fd7)

![Chair of Trustees induction (2)](https://github.com/mysociety/whatdotheyknow-theme/assets/282788/49852bc1-d679-4680-9824-6f1c94e367df)

**Comment by garethrees** [comment]
"Turn anecdotes into evidence"
