### ISSUE TITLE
Add help page on our relationship to search engines

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1713]
We often point people towards search engines in relation to information they hold and are publishing that we have no control over.

[This document appendix](https://docs.google.com/document/d/1LC8fBw5tBoKMCtC_F6pJ_U-oTjOQrRTibWRs1FCvYpU/edit#heading=h.xvy81k1jj7rw) looks like it would make a great help page that we can reference instead of writing it out each time.

I don't think we'd necessarily want a sidebar link for this, so we could link to it from relevant sections of `/help/privacy`.

**Comment by mdeuk** [comment]
Related:
- #987
- #1453
- https://github.com/mysociety/whatdotheyknow-private/issues/25
- #877 [^1]

[^1]: in that, we'd probably also link from here.

**Comment by confirmordeny** [comment]
good idea
