### ISSUE TITLE
Assess listing of Food Hygiene Inspection authorities

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1724]
- [ ] Find the statutory basis for the authorities
- [x] Assess whether a single existing tag identifies all relevant bodies, and only relevant bodies
- [ ] If not, decide on a tag
- [ ] Consider adding tags to link to the FSA's database with IDs

I'm assigning this to myself

**Comment by WilliamWDTK** [comment]
As part of assessing whether a single tag covers all authorities, I'm extracting in the process of extracting them here: https://docs.google.com/spreadsheets/d/13-4LDNMoAh3APvcPJlCbCmdLrO0Y8itiacTgZCVWjI4/edit?usp=sharing

**Comment by WilliamWDTK** [comment]
I think we want to use `LocalAuthorityIdCode`, as that's what's used in the URLs *à la* [`https://ratings.food.gov.uk/authority-search-landing/416`](https://ratings.food.gov.uk/authority-search-landing/416).

**Comment by WilliamWDTK** [comment]
And, no, there is no single appropriate tag currently in use

**Comment by WilliamWDTK** [comment]
Tbh, I think I just need to decide on a suitable tag + possibly a category, and import the IDs as above

**Comment by mdeuk** [comment]
> Tbh, I think I just need to decide on a suitable tag + possibly a category, and import the IDs as above

Something like `fsa_la_id`, perhaps?

The advantage of using something simple is that we could then render the link in https://github.com/mysociety/whatdotheyknow-theme/issues/1724#issuecomment-1682392930 on body pages…

**Comment by confirmordeny** [comment]
I think this is a good idea.

**Comment by HelenWDTK** [comment]
https://wdtkwiki.mysociety.org/wiki/Authority_suggestions
