### ISSUE TITLE
Improve the tagging for Housing Associations

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/whatdotheyknow-theme#1739]
It would be good to:

- [x] Split the Housing Associations in Scotland from those in England, using `housing_association_scotland`
- [x] Remove individual notes from Housing Associations in England
- [x] Add tag based note from `housing_association` - #1403
- [x] Check that these are tagged `foi_no` where appropriate

**Comment by mdeuk** [comment]
Linking to #1403

**Comment by confirmordeny** [comment]
We use rslscot for the Scottish ones.

**Comment by confirmordeny** [comment]
Individual notes have been kept where they contain useful information about individual authorities.

**Comment by confirmordeny** [comment]
All done (note we have only split out [1]Scotland and [2]rest of UK)
