### ISSUE TITLE
fix broken/out-of-date links in help page on requesting:

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/whatdotheyknow-theme#174]
Question <a href="https://www.whatdotheyknow.com/help/requesting#ico_help">Can you tell me more of the nitty gritty about the process of making requests?</a>:

Links out to this URL
http://www.ico.org.uk/for_the_public/access_to_official_information.aspx
which should probably now be
http://ico.org.uk/for_the_public/official_information

and http://www.itspublicknowledge.info/nmsruntime/saveasdialog.asp?lID=1858&sID=321
should probably be
http://www.itspublicknowledge.info/YourRights/YourRights.aspx
or even
http://www.itspublicknowledge.info

Question <a href="https://www.whatdotheyknow.com/help/requesting#data_protection">Can I request information about myself?</a>

This URL
http://www.ico.org.uk/for_the_public/personal_information.aspx
isn't wrong but redirects to http://ico.org.uk/for_the_public/personal_information  so may as well be changed too

**Comment by garethrees** [comment]
These links now all point to the suggested urls
