### ISSUE TITLE
Blog post about submitting a pilot to test responses from a batch

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1740]
We often say this but don't have an example to point to.

Couple of things it could cover:

* How to choose a [representative sample](https://www.whatdotheyknow.com/help/requesting#responsible)? [^1]
* How to phrase questions (for dataset creation, yes/no, single figure answers, etc) (via https://github.com/mysociety/alaveteli-project/issues/169)
* How to think about the internal structure of an authority to get the info you're after (via https://github.com/mysociety/alaveteli-project/issues/169)

[^1]: I know in that page we mean _only_ make a request to a sample, but in the context of batch it's likely the user eventually wants a full dataset if the pilot is interesting.

**Comment by HelenWDTK** [comment]
I think this is better as a help page/integrated into one, as it'd be a bit short as a stand alone blog.

Batch requests are almost always made when user want a complete data set, so the representative sample point is not really relevant. When you sent a test to a smaller subset, you're really only trying to tease out any clarification requests or s12/s14 refusals so you can preempt these when wording your main question.

Beyond that, the data that you get back will inevitable vary in form and format regardless of how you word your question. You are limited by the fact that you have the right to request recorded information, not that your eventual form or questionnaire is filled it (though some users try).
