### ISSUE TITLE
Help page on demystifying the ICO appeals process

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1743]
We should have some guidance around ICO appeals to be able to point to.

Related:

* https://github.com/mysociety/whatdotheyknow-theme/issues/1742
* https://github.com/mysociety/whatdotheyknow-theme/issues/1003
* https://github.com/mysociety/whatdotheyknow-theme/issues/851

**Comment by garethrees** [comment]
Oops, https://github.com/mysociety/whatdotheyknow-theme/pull/1748 was only a part of this.

**Comment by HelenWDTK** [comment]
I've done a fair bit of work on starting to draft this now, and have tried to cover the OSIC as well.

Should I try to separate the OSIC content out, as that process is a bit different, but if not, What should the page title/url be? 

Personally, I think it'd be good to have info relating to both in the same place if it is possible to do so in a way that is not too confusing.

**Comment by JenMysoc** [comment]
This is done an awaiting deploy based on URL which has been agreed as help/appeals

**Comment by JenMysoc** [comment]
can we close this? @garethrees I believe you merged what we needed?
