### ISSUE TITLE
Blog post about most common spreadsheet-based data breaches

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1745]
A followup to https://www.mysociety.org/2013/06/13/whatdotheyknow-team-urge-caution-when-using-excel-to-depersonalise-data/

* Still an issue (add stats if we can?)
* Common cases (pivot tables, cached data, hidden rows/sheets)
* New tools available ("check for hidden content" button; add some screenshots around how to do it to show how easy it is)
* Sad to see authorities only releasing PDF; not as reusable/accessible. More ideal to convert to CSV if possible. It's not hard to click the "check" button.

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
