### ISSUE TITLE
[#1725] Fix minor glitches in `about_foisa`

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#1750]
Looks like some errors snuck in here - probably my fault.

1. The 'what is the…' header wraps when it ought not to. This seems to be because the anchor is on a new line, and is not spaced with `&nbsp;`
2. The last line states "on the OSIC on their website" - it should be one or the other.

**Comment by garethrees** [comment]
Fixed by dbaceee
