### ISSUE TITLE
Expand Cambridge Uni notes re colleges

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1760]
https://www.whatdotheyknow.com/body/university_of_cambridge

We should expand the notes that information held by colleges should be requested from them as the university won't hold it

We could briefly conduct research to establish a quick guide to division of responsibilities

**Comment by confirmordeny** [comment]
I have expanded the note slightly https://www.whatdotheyknow.com/body/university_of_cambridge
