### ISSUE TITLE
FOI for the Everyday

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1762]
One of my favourite stories that I often cite is [this tweet](https://twitter.com/WhatDoTheyKnow/status/1025388510474379264) about information on coach drop-off points in Llandudno.

It's great to be able to show a huge spectrum of FOI use, from hard-hitting journalism and academic research, right down to the individual just making a few peoples' day a bit easier.

Would be good to have a few more of these examples. My initial thinking is that we could make a short listicle style blog (5-10 examples), and then later work those into the core site somehow.

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
