### ISSUE TITLE
Add note re Worcs Reg Services to relevant authorities

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1772]
Not a body in own right, requests to be made to relevant bodies. Worth listing perhaps for search etc.

https://www.worcsregservices.gov.uk/

**Comment by mdeuk** [comment]
What about a [`signpost`](https://www.whatdotheyknow.com/body/list/signpost) stub, pointing to the [relevant councils](https://www.worcsregservices.gov.uk/all-services/about-us/fois-and-eirs/)?

**Comment by confirmordeny** [comment]
We have added a note on the pages for each of the partners - 
e.g. https://www.whatdotheyknow.com/body/bromsgrove_district_council

See also: https://www.whatdotheyknow.com/body/list/wrs_partner
