### ISSUE TITLE
Data breach form output requires unique email subject

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#1774]
The current email generated by the data breach form is outputting messages with a subject:

> New data breach report

… this leads to threading problems, as if two or more reports come in, Gmail interprets them as being related to each other, so combines them in a thread.

It _is_ possible for WDTK admins to rectify this, through Inbox Monster, but it is time consuming. It would also be less ideal if this code migrates upstream, since re-users may not have the same internal tooling.

**Comment by mdeuk** [comment]
A solution to this may be to use a refined version of [the code used by the volunteer contact form](https://github.com/mysociety/whatdotheyknow-theme/blob/master/lib/volunteer_contact_form.rb#L67).

Given cases will not have been logged at the time of the form being submitted, using a generic, randomly generated, alphanumeric identifier for the transaction could be suitable.

**Comment by HelenWDTK** [comment]
+1 this happened recently, when an authority used the form to report an unrelated issue, and the message was joined to an existing thread about a separate ongoing case.

**Comment by HelenWDTK** [comment]
+1 This has happened again, and has led to unrelated issues being threaded on one of the groups.
