### ISSUE TITLE
Consider tagging bodies (limited companies) that have a use of 'Limited' exemption

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1781]
Perhaps `limited_exemption` (I've just used it once).

@confirmordeny might be interested in this.

**Comment by confirmordeny** [comment]
I think it is a good idea.

**Comment by confirmordeny** [comment]
Documented here: https://wdtkwiki.mysociety.org/wiki/Legal_form_tags#limited_exemption
