### ISSUE TITLE
List openreach and other telecoms infrastructure providers

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/whatdotheyknow-theme#1782]
We were asked by a user to add openreach to enable EIR requests to be made to them, which we decided to do. I have been unable to locate a good address to do so at this stage. 

We have also been asked to list HYPEROPTIC LTD and GIGACLEAR LIMITED, so we need to decide if we think they are subject to EIR and if we want to list them.

**Comment by confirmordeny** [comment]
Now listed here: https://wdtkwiki.mysociety.org/wiki/Authority_suggestions

**Comment by confirmordeny** [comment]
We have added Openreach here: https://www.whatdotheyknow.com/body/openreach_limited
