### ISSUE TITLE
Consider tagging for bodies responding on behalf of others or joint processing/governance services

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1783]
Sometimes requests to a minor body are responded to by a larger ("host") body.

Sometimes, two or more authorities might centralise responses to FOI requests (among other services).

Etc.

How could we tag this? Is it desirable to record it?

**Comment by HelenWDTK** [comment]
https://wdtkwiki.mysociety.org/wiki/Tagging_suggestions
