### ISSUE TITLE
Ideas for the Community & Activism Call - 2023-11-09

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1803]
The next call will be on 2023-11-09

As per usual, if there's anything that you'd like to flag for the agenda, either make a note of it here, or use the flag for the c&A label in the inbox.

**Comment by garethrees** [comment]
Should we remove Notes from the text indexed for authority search? It's getting terrible 😞 (https://github.com/mysociety/alaveteli/issues/7552#issuecomment-1779488513)

**Comment by HelenWDTK** [comment]
> Should we remove Notes from the text indexed for authority search? It's getting terrible

1000 times yes! 🙏

**Comment by WilliamWDTK** [comment]
>Should we remove Notes from the text indexed for authority search?

Certainly notes from tags. It _might_ be useful in certain instances to keep indexing any body-specific notes (e.g. where we note alternative names beyond the short one).

**Comment by confirmordeny** [comment]
Should we remove the listings for Integrated Care Partnerships?

**Comment by confirmordeny** [comment]
Should we change the default text for new requests?

**Comment by confirmordeny** [comment]
Should we have a category for requests that are refused but with a helpful suggestion e.g. re submitting a more focused request that will be within cost limit? [suggestion from a user]

**Comment by garethrees** [comment]
https://github.com/mysociety/whatdotheyknow-private/issues/214

**Comment by garethrees** [comment]
Some themes/terms to test https://github.com/mysociety/alaveteli/issues/6402#issuecomment-1788602809
