### ISSUE TITLE
Make it more obvious that responses will be automatically published

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1810]
We spoke about this on https://github.com/mysociety/whatdotheyknow-theme/issues/1803. The TL;DR is that we're seeing more FOI officers being surprised about publication.

The first step we decided was to gather some insight from FOI officers as to why they didn't see the footer. We're not sure if it's being cut off by case management systems, not obvious enough, or other unknown reasons.

We had a couple of ideas for making it more obvious:

* Use HTML emails and highlight that part of the email
* Prefix the line with an emoji warning symbol ⚠️
* Add a warning “banner” (like some enterprise systems do for "external senders") with the key message of automatic publication and point to more details in footer. Could do this in plain text or HTML.
* A combination of some/all of the above.

I've ticketed this in WDTK as I think we should experiment here first before then merging in to core if we see some improvements.

**Comment by garethrees** [comment]
A rephrasing to emphasise "permanent online archive" might help:

```diff
- Disclaimer: This message and any reply that you make will be published on the internet.
+ Disclaimer: This message and any reply that you make will be published in our permanent online archive of information requests.
```

**Comment by mdeuk** [comment]
> A rephrasing to emphasise "permanent online archive" might help:

I think that'd be a good first step. Including an emoji would also be a "cheap" way of enhancing this [^1].

Tying in with what's already there, what about this slight revision?

> ```diff
> - Disclaimer: This message and any reply that you make will be published on the internet.
> + ⚠️ Disclaimer: Just so you know, this message, and any reply you send, will be published online, in our permanent archive of information requests.
> + If you want to know more, or need help…
> ```

… the thinking being, we then position the officers page as the "help" [^2].

If you want to make it doubly obvious, adding a second ⚠️, after "requests" might also work.

[^1]: unless they are using a very old client / OS, I'd expect it to render in _some_ form 
[^2] linking to #1749 here, just so that it is on our radar.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
