### ISSUE TITLE
Collect reporter's details on data breach form

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1813]
Following #1777, I am now pretty confident that collecting the reporter's details on the data breach form is the right thing to do, so this should be considered a development ticket.

Therefore, contact details should be collected as on the other forms. This means using the details of the logged-in user, otherwise providing a name field and an email field to be filled in.

I think the `Reply-To` should be set to the form-filler, and not the DPO email address.

The DPO email field should remain separate and optional.

**Comment by HelenWDTK** [comment]
+1 I've had to respond to some recent reports in a vague way because of this, and there has been correspondence that we have been unable to reply to.
