### ISSUE TITLE
Provide canned removal message for ATAS

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#1822]
We're seeing an uptick in ["ATAS"](https://www.gov.uk/guidance/academic-technology-approval-scheme) related messages, which relate to individuals personal circumstances.

At the moment, the generic templates on Alaveteli don't cover the specific information that is helpful to convey to individuals, so it is time consuming to carry out admin actions on these requests.

We could, perhaps, use a [variant of the setup for immigration related matters](https://github.com/mysociety/whatdotheyknow-theme/blob/master/lib/views/admin_request/_hidden_user_explanation_reasons.html.erb) (body `93723`).

**Comment by mdeuk** [comment]
I've added https://github.com/mysociety/whatdotheyknow-theme/pull/1823/commits/d5f6ee4c36d7c5aa5a64bbac9dcda3f0a0912838 in pr #1823, which hopefully covers this off.

**Comment by HelenWDTK** [comment]
This has already been done 🎉
