### ISSUE TITLE
Add a tag to NHS Trusts that have a CAMHS

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1838]
A user has contact us for assistance with making requests to Trusts with a CAMHS, so we could consider tagging the Trusts. (We don't currently have a list.)

**Comment by confirmordeny** [comment]
It doesn't seem like there is a list

**Comment by WilliamWDTK** [comment]
Completing this would probably require manual research, rather than simply comparing a list.

**Comment by HelenWDTK** [comment]
https://wdtkwiki.mysociety.org/wiki/Tagging_suggestions
