### ISSUE TITLE
Authority deletion issue

### ISSUE THREAD

**Issue by confirmordeny** [mysociety/whatdotheyknow-theme#1844]
Struggling to delete this duplicate: https://www.whatdotheyknow.com/body/the_biometrics_and_forensics_ethics_group

might be a cache issue

**Comment by WilliamWDTK** [comment]
It has two embargoed requests, and you are not a `pro_admin`

**Comment by WilliamWDTK** [comment]
Sorry, I probably shouldn't have closed this until I'd transferred the requests.

I just attempted to transfer the requests https://www.whatdotheyknow.com/admin/requests/1103531 and https://www.whatdotheyknow.com/admin/requests/1063824 to the body https://www.whatdotheyknow.com/admin/bodies/92230, but the request pages return an error, so I am unable to complete this at the moment.

**Comment by confirmordeny** [comment]
@HelenWDTK fixed this by adding the email address back in. Authority now deleted.
