### ISSUE TITLE
Blog post on meta requests

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1856]
At a recent FOI conference, in response to an audience question a speaker mentioned that they'd made a meta request (can't remember if they used those specific terms), and the audience member was surprised they could do this and hadn't heard of the idea.

We could write a blog post that acts as a simple guide for what they are and why they're useful, some examples and some template phrasing.

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
