### ISSUE TITLE
Mistakenly destroyed issues

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1858]
On 11th April some issues in this repo were mistakenly permanently destroyed. We managed to preserve at least some of the issue titles. Creating an issue here to record them for searchability.

* Review volunteer agreement documents
* #JustAsk: Inspire users to be curious and make their first requests
* Blog posts around ICO appeal victories in common scenarios
* Add structure to incoming support mail

**Comment by HelenWDTK** [comment]
Added #1860

**Comment by HelenWDTK** [comment]
I am not sure I have a complete record for Blog posts around ICO appeal victories in common scenarios (Issue #1742), as I only have a record of 2 posts. 

Thanks to @confirmordeny and @WilliamWDTK, I am confident that we do have the complete history of the volunteer agreement ticket, so I will restore that one.

**Comment by HelenWDTK** [comment]
Added #1861

**Comment by HelenWDTK** [comment]
Added #1862
