### ISSUE TITLE
Blog posts around ICO appeal victories in common scenarios

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/whatdotheyknow-theme#1862]
Replaces #1742, deleted in error

On 10 July 2023 @garethrees wrote:

Telling individual stories can help bring concreteness to a process that feels abstract. We can then pull these in to more general guidance.

Couple of suggested themes to get this started:

Forcing a response after the deadline passed
Successful challenge of misapplied redactions
Successful challenge of public interest test assessment

***

On 18 July 2023 @garethrees wrote:

Notes on success rate https://twitter.com/rosenbaum6/status/1681265325424222209
***
On 18 July 2023 @HelenWDTK wrote

> Notes on success rate

That's for the FTT vs the ICO (so orgs and requesters). ICO appeal data is here:
<img width="853" alt="254267106-62ee22e2-2f4e-4c15-a4ee-be2ca903c661" src="https://github.com/mysociety/whatdotheyknow-theme/assets/120410992/73662a4c-e379-458c-b3f0-f0b1705ed2ba">

**Comment by HelenWDTK** [comment]
I don't think this represents a full record of what was on the ticket before (the first post seems incomplete), so if anyone has a copy of the rest of it, please add it in. The title seems quite self explanatory though 🙂

**Comment by mdeuk** [comment]
> I don't think this represents a full record of what was on the ticket before (the first post seems incomplete), so if anyone has a copy of the rest of it, please add it in. The title seems quite self explanatory though 🙂

I've added the first message on that one, from 10 July 2023; my mailbox archive suggest there was only 3 messages overall.

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
