### ISSUE TITLE
Improve the language on selected help pages with poor readability

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/whatdotheyknow-theme#1885]
Part of #1749

We will make some targeted improvements to specific help pages. These have been prioritised by reading ease scores, and those that contain information which would be most important to site users.

- [x] House rules
- [x] About
- [x] Making requests

**Comment by mdeuk** [comment]
It strikes me that it may be best if we can conclude #1663 before merging the change to the rules, so as to make the change simpler.

**Comment by HelenWDTK** [comment]
> It strikes me that it may be best if we can conclude https://github.com/mysociety/whatdotheyknow-theme/issues/1663 before merging the change to the rules, so as to make the change simpler.

That would be ideal (I personally hate the term house rules). This is linked to a funding deadline around the end of June, so realistically, it might need working into future changes instead. I'm not sure if more than a simple text change would be needed for that.
