### ISSUE TITLE
Update OSIC links / contacts

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#1886]
OSIC have changed their domain from `itspublicknowledge.info`, to `foi.scot` [^1].

We should validate the links within relevant help pages, monster templates, and the public body page, as applicable.

[^1]: https://x.com/FOIScotland/status/1797623078526005713

**Comment by garethrees** [comment]
awesome domain!

**Comment by mdeuk** [comment]
Domain is [now in use for email](https://x.com/FOIScotland/status/1821196417106579559). I've now updated body 2586 with this.

## Already done:

- [x] Update homepage, and publication scheme urls.

## Still to do:

- [ ] Update [`/help/about_foisa`](https://github.com/mysociety/whatdotheyknow-theme/blob/master/lib/views/help/about_foisa.html.erb)
- [ ] Update [`/help/appeals`](https://github.com/mysociety/whatdotheyknow-theme/blob/master/lib/views/help/appeals.html.erb)
- [ ] Update [`/help/environmental_information`](https://github.com/mysociety/whatdotheyknow-theme/blob/master/lib/views/help/environmental_information.html.erb)
- [ ] Update [`/help/exemptions`](https://github.com/mysociety/whatdotheyknow-theme/blob/master/lib/views/help/exemptions.html.erb)
- [ ] Update [`/help/no_response`](https://github.com/mysociety/whatdotheyknow-theme/blob/master/lib/views/help/no_response.html.erb)

**Comment by mdeuk** [comment]
With the help of GPT, here is a direct mapping of urls in the remaining files. It's probably worth noting that this is just a starting point, as there may well be a different url for some [^1].

<details>
<summary>Output of tool</summary>

| filename | url | new_url | error |
|---|---|---|---|
| .\appeals.html.erb | mailto:enquiries@ItsPublicKnowledge.info |  | No connection adapters were found for   'mailto:enquiries@ItsPublicKnowledge.info' |
| .\appeals.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-03/Application_Form_-_Website.docx | https://www.foi.scot/sites/default/files/2022-03/Application_Form_-_Website.docx |  |
| .\environmental_information.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-04/InformationNotHeldEIRs%20%281%29.pdf | https://www.foi.scot/sites/default/files/2022-04/InformationNotHeldEIRs%20(1).pdf |  |
| .\environmental_information.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-04/BriefingRegulation104bManifestlyUnreasonableRequests.docx%20%281%29.pdf | https://www.foi.scot/sites/default/files/2022-04/BriefingRegulation104bManifestlyUnreasonableRequests.docx%20(1).pdf |  |
| .\environmental_information.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-04/EIRsGuidanceRegulation104cRequestswhicharetoogeneral.pdf | https://www.foi.scot/sites/default/files/2022-04/EIRsGuidanceRegulation104cRequestswhicharetoogeneral.pdf |  |
| .\environmental_information.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-03/EIRBriefingsExceptions.pdf | https://www.foi.scot/sites/default/files/2022-03/EIRBriefingsExceptions.pdf |  |
| .\environmental_information.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-03/EIRBriefingsExceptions.pdf | https://www.foi.scot/sites/default/files/2022-03/EIRBriefingsExceptions.pdf |  |
| .\environmental_information.html.erb | https://www.itspublicknowledge.info/sites/default/files/2023-03/EIRsGuidanceRegulation104eInternalCommunications.pdf | https://www.foi.scot/sites/default/files/2023-03/EIRsGuidanceRegulation104eInternalCommunications.pdf |  |
| .\environmental_information.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-04/EIRsGuidanceRegulation105cIntellectualpropertyrights.pdf | https://www.foi.scot/sites/default/files/2022-04/EIRsGuidanceRegulation105cIntellectualpropertyrights.pdf |  |
| .\environmental_information.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-03/EIRBriefingsExceptions.pdf | https://www.foi.scot/sites/default/files/2022-03/EIRBriefingsExceptions.pdf |  |
| .\environmental_information.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-04/EIRsGuidanceRegulation105fThirdpartyinterests.pdf | https://www.foi.scot/sites/default/files/2022-04/EIRsGuidanceRegulation105fThirdpartyinterests.pdf |  |
| .\environmental_information.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-04/EIRsGuidanceRegulation105gProtectionoftheEnvironment.pdf | https://www.foi.scot/sites/default/files/2022-04/EIRsGuidanceRegulation105gProtectionoftheEnvironment.pdf |  |
| .\environmental_information.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-04/EIRs%20Guidance%20Regualtion%2011%20Personal%20Data.pdf | https://www.foi.scot/sites/default/files/2022-04/EIRs%20Guidance%20Regualtion%2011%20Personal%20Data.pdf |  |
| .\environmental_information.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-04/EIRsGuidanceRegulation105aInternationalRelations.pdf | https://www.foi.scot/sites/default/files/2022-04/EIRsGuidanceRegulation105aInternationalRelations.pdf |  |
| .\environmental_information.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-04/EIRsGuidanceRegulation105bCourseofJustice.pdf | https://www.foi.scot/sites/default/files/2022-04/EIRsGuidanceRegulation105bCourseofJustice.pdf |  |
| .\exemptions.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-03/BriefingSection25InformationOtherwiseAccessible.pdf | https://www.foi.scot/sites/default/files/2022-03/BriefingSection25InformationOtherwiseAccessible.pdf |  |
| .\exemptions.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-04/BriefingSection37CourtRecords.pdf | https://www.foi.scot/sites/default/files/2022-04/BriefingSection37CourtRecords.pdf |  |
| .\exemptions.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-04/BriefingSection36Confidentiality.pdf | https://www.foi.scot/sites/default/files/2022-04/BriefingSection36Confidentiality.pdf |  |
| .\exemptions.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-03/BriefingSection26ProhibitionsOnDisclosure.pdf | https://www.foi.scot/sites/default/files/2022-03/BriefingSection26ProhibitionsOnDisclosure.pdf |  |
| .\exemptions.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-03/BriefingSection27InformationIntendedforFuturePublication.pdf | https://www.foi.scot/sites/default/files/2022-03/BriefingSection27InformationIntendedforFuturePublication.pdf |  |
| .\exemptions.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-04/BriefingSection31NationalSecurityandDefence.pdf | https://www.foi.scot/sites/default/files/2022-04/BriefingSection31NationalSecurityandDefence.pdf |  |
| .\exemptions.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-04/BriefingSection31NationalSecurityandDefence.pdf | https://www.foi.scot/sites/default/files/2022-04/BriefingSection31NationalSecurityandDefence.pdf |  |
| .\exemptions.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-04/BriefingSection32InternationalRelations.pdf | https://www.foi.scot/sites/default/files/2022-04/BriefingSection32InternationalRelations.pdf |  |
| .\exemptions.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-03/BriefingSection28RelationswithintheUnitedKingdom.pdf | https://www.foi.scot/sites/default/files/2022-03/BriefingSection28RelationswithintheUnitedKingdom.pdf |  |
| .\exemptions.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-04/BriefingSection33CommercialInterestsandtheEconomy.pdf | https://www.foi.scot/sites/default/files/2022-04/BriefingSection33CommercialInterestsandtheEconomy.pdf |  |
| .\exemptions.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-04/BriefingSection35LawEnforcement.pdf | https://www.foi.scot/sites/default/files/2022-04/BriefingSection35LawEnforcement.pdf |  |
| .\exemptions.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-04/BriefingSection34InvestigationsbyScottishPublicAuthoritiesandProceedings.pdf | https://www.foi.scot/sites/default/files/2022-04/BriefingSection34InvestigationsbyScottishPublicAuthoritiesandProceedings.pdf |  |
| .\exemptions.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-04/Briefing_Section40AuditFunctions.pdf | https://www.foi.scot/sites/default/files/2022-04/Briefing_Section40AuditFunctions.pdf |  |
| .\exemptions.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-04/BriefingSection29FormulationofScottishAdministrationPolicy.pdf | https://www.foi.scot/sites/default/files/2022-04/BriefingSection29FormulationofScottishAdministrationPolicy.pdf |  |
| .\exemptions.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-04/BriefingSection39HealthSafetyandtheEnvironment.pdf | https://www.foi.scot/sites/default/files/2022-04/BriefingSection39HealthSafetyandtheEnvironment.pdf |  |
| .\exemptions.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-04/BriefingSection39HealthSafetyandtheEnvironment.pdf | https://www.foi.scot/sites/default/files/2022-04/BriefingSection39HealthSafetyandtheEnvironment.pdf |  |
| .\exemptions.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-04/BriefingSection36Confidentiality.pdf | https://www.foi.scot/sites/default/files/2022-04/BriefingSection36Confidentiality.pdf |  |
| .\exemptions.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-04/BriefingSection33CommercialInterestsandtheEconomy.pdf | https://www.foi.scot/sites/default/files/2022-04/BriefingSection33CommercialInterestsandtheEconomy.pdf |  |
| .\exemptions.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-04/BriefingSection41CommunicationsWithHerMajestyetcandHonours.pdf | https://www.foi.scot/sites/default/files/2022-04/BriefingSection41CommunicationsWithHerMajestyetcandHonours.pdf |  |
| .\exemptions.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-04/BriefingSection38PersonalInformationGDPR.pdf | https://www.foi.scot/sites/default/files/2022-04/BriefingSection38PersonalInformationGDPR.pdf |  |
| .\exemptions.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-04/BriefingSection30PrejudicetotheEffectiveConductofPublicAffairs.pdf | https://www.foi.scot/sites/default/files/2022-04/BriefingSection30PrejudicetotheEffectiveConductofPublicAffairs.pdf |  |
| .\glossary.html.erb | https://www.itspublicknowledge.info/sites/default/files/2022-03/FeesandExcessiveCostofComplianceBriefing.pdf | https://www.foi.scot/sites/default/files/2022-03/FeesandExcessiveCostofComplianceBriefing.pdf |  |
| .\requesting.cy.html.erb | https://www.itspublicknowledge.info/your-rights | https://www.foi.scot/your-rights |  |
| .\requesting.html.erb | http://www.itspublicknowledge.info/YourRights/tipsforrequesters.aspx | https://www.foi.scot/how-do-i-ask |  |
| .\requesting.html.erb | http://www.itspublicknowledge.info/YourRights/YourRights.aspx | https://www.foi.scot/your-rights |  |

</details>


[^1]: e.g. the appeals form has a [`2022`](https://www.foi.scot/sites/default/files/2022-03/Application_Form_-_Website.docx), and [`2024`](https://www.foi.scot/sites/default/files/2024-08/ApplicationForm2024.docx) version. The link doesn't redirect automatically.
