### ISSUE TITLE
Add tags to the four tag-less bodies

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1894]
As part of my work for #1874, due to my dodgy Python script, which didn't handle bodies with no tags properly, I have discovered that the following bodies are untagged. It seems like it would be a good idea to fit them into one category or another.

    ID: 4777
    Name: Criminal Justice Council
    ID: 4834
    Name: Engineering Construction Industry Training Board
    ID: 4841
    Name: The National Institute for Biological Standards and Control
    ID: 111881
    Name: Independent Review Mechanism

- [x] [Criminal Justice Council](https://www.whatdotheyknow.com/body/criminal_justice_council)
- [x] [Engineering Construction Industry Training Board](https://www.whatdotheyknow.com/body/ecitb)
- [x] [The National Institute for Biological Standards and Control](https://www.whatdotheyknow.com/body/nibsc)
- [x] [Independent Review Mechanism](https://www.whatdotheyknow.com/body/independent_review_mechanism)

**Comment by confirmordeny** [comment]
Done one: https://www.whatdotheyknow.com/body/ecitb

**Comment by confirmordeny** [comment]
Done. All four now have a tag.
