### ISSUE TITLE
Remove reference(s) to "View FOI address" link from help page(s)

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1905]
- [x] [`https://www.whatdotheyknow.com/help/officers#spam_problems`](https://www.whatdotheyknow.com/help/officers#spam_problems): _You can check the address we’re using with the “View FOI email address” link which appears on the page for the authority. [Contact us](https://www.whatdotheyknow.com/help/contact) if there is a better address we can use._

**Comment by garethrees** [comment]
Related to https://github.com/mysociety/alaveteli/issues/8264
