### ISSUE TITLE
Look into what has happened with Lloyds Pharmacy to see if there are any new bodies that we need to add

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/whatdotheyknow-theme#1906]
We should look into whether there is on obvious successor organisation

We should also try to find out if other members go the Healthcare Group might be subject to FOI by providing dispensing services: eg LloydsPharmacy Clinical Homecare (LPCH / Lloyds Pharmacy Clinical Homecare Ltd, ch: 2764914), and  LloydsPharmacy Healthcare Services (LP HCS Limited, ch: 14477534).

**Comment by confirmordeny** [comment]
added to list on wiki and closed here
