### ISSUE TITLE
Simplify 'EIR only' text

### ISSUE THREAD

**Issue by confirmordeny** [mysociety/whatdotheyknow-theme#1912]
I am referring to the text that appears here for example: https://www.whatdotheyknow.com/new/bristol_water_plc

**Comment by confirmordeny** [comment]
In particular: "Air, water, soil, land, flora and fauna (including how these effect human beings)" could be changed to "Air, water, soil, land, flora and fauna (including how these **a**ffect **people)**"

**Comment by HelenWDTK** [comment]
This comes from Alaveteli, so would need raising/changing there: https://github.com/mysociety/alaveteli/blob/46337bb275460348b43258aa2077846c88cd16b0/app/views/request/new.html.erb#L156
