### ISSUE TITLE
Review UKPN listing

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/whatdotheyknow-theme#1921]
A user has told us that UK Power Networks (Operations) Limited does not hold a DNO licience itself so is not a Public Authority for EIR, and that the licence is held by the 3 subsidiaries: 
Eastern Power Networks (EPN) 
London Power Networks (LPN) 
South Eastern Power Networks (SPN)

We should look into this and update the listing if needed.

**Comment by georgiakelsey** [comment]
User has discovered that GTC is the IDNO for their area and has suggested that they be added.

Their email customer.services@gtc-uk.co.uk

**Comment by confirmordeny** [comment]
There are now separate entries for the individual companies. See https://www.whatdotheyknow.com/body/uk_power_networks
