### ISSUE TITLE
Facebook links incorrect

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/whatdotheyknow-theme#200]
Hello

Links on the bottom of various pages link to the Facebook page ostensibly at 

https://www.facebook.com/WhatDoTheyKnow 

This now returns a 404. But earlier today, https://www.facebook.com/WhatDoTheyKnow linked to a Facebook user called Nora Serino. This was reported by one of our users, and I experienced the same. 

Either a 404 or the above user's page isn't correct... 

Thank you

**Comment by garethrees** [comment]
![screen shot 2015-05-29 at 15 08 37](https://cloud.githubusercontent.com/assets/282788/7884288/8f130958-0614-11e5-98c1-06c59816386e.png)

**Comment by kingqueen3065** [comment]
If I'm signed in to Facebook, on attempting to go to https://www.facebook.com/WhatDoTheyKnow I consistently get the following, as does the user who alerted me.
![ss 2015-05-29 at 03 21 05](https://cloud.githubusercontent.com/assets/11923618/7884547/94d0bc62-0616-11e5-81e8-07f41aab5f5b.jpg)
If I'm signed out of facebook and attempt to go to that page, I consistently get a 404 as follows. 
![ss 2015-05-29 at 03 21 52](https://cloud.githubusercontent.com/assets/11923618/7884568/b32758f6-0616-11e5-9d71-2668d3489fcd.png)

**Comment by garethrees** [comment]
@kingqueen3065 we got the URL wrong in #196. Sorry about that; deploying the fix (#201) now.

**Comment by garethrees** [comment]
Fixed

**Comment by kingqueen3065** [comment]
Thank you!
