### ISSUE TITLE
Better Twitter Avatar

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#202]
Should https://twitter.com/whatdotheyknow match the logo on https://www.facebook.com/whatdotheyknowcom?

cc @MyfanwyNixon @wrightmartin

**Comment by MyfanwyNixon** [comment]
It'd certainly make sense, and that Twitter one is looking a bit shonky

**Comment by garethrees** [comment]
Unless anyone has any objections I'll change this on Monday (2015-06-08).

**Comment by garethrees** [comment]
Done
