### ISSUE TITLE
Broken link from help pages on fees/charges

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#203]
At

https://www.whatdotheyknow.com/help/requesting#fees 

In "More details from the Information Commissioner" "More details" is linked to https://ico.org.uk/upload/documents/library/freedom-of-information/practical-application/chargingafee.pdf which is no longer present. 

Suggested replacement:

https://ico.org.uk/for-organisations/guide-to-freedom-of-information/receiving-a-request/#15

Which is the ICO's guidance to organisations under the heading: "Can we charge for the information?"

**Comment by garethrees** [comment]
Fixed in 0573198
