### ISSUE TITLE
Better Twitter Banner

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#207]
https://twitter.com/whatdotheyknow

After updating the twitter logo (#202) I also added the hero background image as the twitter banner.

Looks good, but we should use the opportunity to add some text about WDTK.

I was thinking we could take the existing hero text, but fix the numbers and make the URL more obvious. 

e.g:

![screen shot 2015-06-08 at 12 16 39](https://cloud.githubusercontent.com/assets/282788/8033676/4553c0c0-0dd8-11e5-8a44-c994f6146b6c.png)

**Comment by wrightmartin** [comment]
![wdtk-twitter-bg](https://cloud.githubusercontent.com/assets/2292925/8283211/e6056184-18ed-11e5-942c-fe08a816f494.jpg)

**Comment by garethrees** [comment]
Looks great. Would it be worth it saying "Make a request with WhatDoTheyKnow**.com**", or, to make it less "technical" – "Ask on WhatDoTheyKnow.com"?

**Comment by wrightmartin** [comment]
Yes, I prefer 'ask', nice one

**Comment by wrightmartin** [comment]
I've had a rethink, using a template that has a good guide to what's visible and when

![bitmap](https://cloud.githubusercontent.com/assets/2292925/9874349/7780281e-5b9d-11e5-9ba1-60096086306f.png)


![twitter-banner](https://cloud.githubusercontent.com/assets/2292925/9874325/60ac7070-5b9d-11e5-968d-c941ee032e4a.jpg)

**Comment by garethrees** [comment]
:+1: awesome. Could you email the file to me to avoid any compression applied by attaching it here?

Cheers

**Comment by wrightmartin** [comment]
Done!

**Comment by garethrees** [comment]
Twitter seems to crop it quite a lot

![screen shot 2015-09-15 at 12 14 07](https://cloud.githubusercontent.com/assets/282788/9875813/1ff90aa0-5ba9-11e5-862b-4cdb5098b838.png)

**Comment by garethrees** [comment]
Nearly works for the Facebook page too:

![screen shot 2015-09-15 at 15 14 26](https://cloud.githubusercontent.com/assets/282788/9878891/dc95a4b2-5bbc-11e5-8f6e-6246c60702ae.png)

**Comment by garethrees** [comment]
Added to https://www.facebook.com/whatdotheyknowcom and https://twitter.com/WhatDoTheyKnow
