### ISSUE TITLE
Spreadsheet listing major public bodies

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/whatdotheyknow-theme#209]
Following the news that we may now link directly to the WDTK domain from Google Adwords, could I please have a spreadsheet which lists:

The names of top 50 public bodies (in terms of numbers of requests), including variants if possible (eg DWP; department for work and pensions)
The URL for that body, eg https://www.whatdotheyknow.com/body/dwp

This will then allow me to set up adwords that take the user directly to the relevant page.
Thank you!

**Comment by garethrees** [comment]
@jacksonj04 

```sql
SELECT name, short_name, url_name, info_requests_count
FROM public_bodies
ORDER BY info_requests_count DESC
LIMIT 50;
```

**Comment by garethrees** [comment]
even better…

```sql
COPY (
  SELECT name, short_name, url_name, info_requests_count
  FROM public_bodies
  ORDER BY info_requests_count DESC
  LIMIT 50
) TO stdout WITH CSV HEADER;
```

**Comment by garethrees** [comment]
Emailed a CSV from the [above query](https://github.com/mysociety/whatdotheyknow-theme/issues/209#issuecomment-110717962) to @MyfanwyNixon.
