### ISSUE TITLE
Add All UK Publically Run Schools to WhatDoTheyKnow

### ISSUE THREAD

**Issue by robinhouston** [mysociety/whatdotheyknow-theme#21]
**RichardTaylor opened this issue May 31, 2011**

Using data, inc. contact emails from Edubase dataset on data.gov.uk ; include new tags to use Edubase ID to aid maintenance.

**Comment by garethrees** [comment]
We have [10k+ schools](https://www.whatdotheyknow.com/body?tag=school), so considering this "done" – others can always be suggested through the change requests form.
