### ISSUE TITLE
Add all Town/Parish Councils to WhatDoTheyKnow

### ISSUE THREAD

**Issue by robinhouston** [mysociety/whatdotheyknow-theme#22]
**RichardTaylor opened this issue May 31, 2011**

Probably well suited to be a volunteer task. Could be done via FOI requests to all council tax collecting councils asking for the list of Town/Parish councils in their area and a contact email.

Would probably need a some developer support for the bulk upload / checking for duplications etc.

**Comment by garethrees** [comment]
Started listing these but doesn't look like its complete https://www.whatdotheyknow.com/body?tag=parish_council

**Comment by RichardTaylor** [comment]
Try to gamify with a map showing progress. 

Linked to: https://github.com/mysociety/alaveteli/issues/3477

**Comment by RichardTaylor** [comment]
A volunteer has noted they believe we are currently comprehensive in:

>Fenland, Huntingdonshire, Shropshire, West Suffolk, Cotswold, South Cambs, Nottinghamshire, Dacorum, North East Derbyshire, Peterborough, Sollihull, Waverley, West Berks and South Gloucestershire

**Comment by RichardTaylor** [comment]
Reportedly coverage of: Rutland, Kent and Medway, Merseyside, Berkshire, Buckinghamshire and Lancashire is now also comprehensive.

**Comment by FOIMonkey** [comment]
Cumbria, North Yorkshire, Isle of Wight, Essex, Oxfordshire and West Sussex also appear complete.

**Comment by garethrees** [comment]
Is there a list of areas that we could create a checklist from in the initial comment in this issue?

**Comment by FOIMonkey** [comment]
I've been attempting to check what we have against a list of district councils to create one. From what I can tell, I think we have full coverage for 120+ districts and circa 150 left to go, if you exclude London. Some of the remaining districts will be unparished, so the real number will be smaller than that.

**Comment by RichardTaylor** [comment]
We are not currently comprehensive in North Northamptonshire, there is a list of town and parish clerk contacts in the district at:

https://www.east-northamptonshire.gov.uk/directory/9/town_and_parish_clerk_contacts

**Comment by FOIMonkey** [comment]
I've geotagged every town, parish and community council that we list in England and Wales. I've used the data to produce a table of our current coverage: 

https://docs.google.com/spreadsheets/d/1gPa5P1nlpaBhvj_6_-XLlQ6cku7RIUHegsy_YzeP2lA/edit?usp=sharing

Caveat - not every parish has a meeting/council, so we will be at full coverage for some areas when the figure is below 100%
95 councils could not be matched to a parish on mapit and so are not included in this data.

**Comment by HelenWDTK** [comment]
Copying from another issue: https://www.ceredigion.gov.uk/your-council/councillors-committees/town-and-community-councils/

**Comment by WilliamWDTK** [comment]
Has this been done now? I had an idea there was a large-scale import done.

**Comment by HelenWDTK** [comment]
I got it up to 9,244, and there are just over 10,000 in total, so we can't say we have all of them yet. That might be enough coverage to close this off though - there were no contact details for most of the missing ones. I'd personally prioritise checking that the details we have are up to date before adding any more.

**Comment by HelenWDTK** [comment]
We've had a good go at this now.
