### ISSUE TITLE
New Homepage Announcement

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#229]
> I've drafted a blog post ready for launch, and would be glad if someone could fact-check it. 
> https://blogs.mysociety.org/mysociety/?p=24657&preview=true
> 
> * Parts where I particularly need confirmation (because I made assumptions):
> 
> > like almost everything we do these days, the changes will be subjected to scrutiny from our Research team.
> 
> and
> 
> > As with all site improvements, the design will be rolled out as an option on the wider Alaveteli codebase, so that it can be implemented by anyone running an Alaveteli site.
> 
> * Also:
> 
> Have we performed user testing? It would be nice to mention that, if so.
> Anything else I have missed about the thinking behind the design, @wrightmartin?
> 
> Finally it will just need a screenshot dropped in as the feature image, plus it would be nice to include shots of the various page elements as they are mentioned.
> 
> _– @MyfanwyNixon_

**Comment by garethrees** [comment]
> like almost everything we do these days, the changes will be subjected to scrutiny from our Research team.

I've filed a ticket with team research https://github.com/mysociety/research/issues/65.

> As with all site improvements, the design will be rolled out as an option on the wider Alaveteli codebase, so that it can be implemented by anyone running an Alaveteli site.

There are no plans to do this immediately, but its definitely something we'd like to do and we'll be aiming to put it in to a future sprint. We need to collect some data first (see above). The source is available of course, in https://github.com/mysociety/whatdotheyknow-theme.

**Comment by MyfanwyNixon** [comment]
@garethrees Thanks for the input!
I have amended the final paragraph to:
> Provided that we discover that the design has been effective in the areas mentioned above, we hope to roll it out as an option on the wider Alaveteli codebase, so it can be implemented by anyone running an Alaveteli site.

> Meanwhile, the open source code can be [accessed on Github](https://github.com/mysociety/whatdotheyknow-theme) by anyone who would like to use it.

**Comment by garethrees** [comment]
Done https://www.mysociety.org/2015/06/23/well-what-do-you-know-its-a-new-look-for-whatdotheyknow/
