### ISSUE TITLE
Add all GPs Surgeries to WhatDoTheyKnow

### ISSUE THREAD

**Issue by robinhouston** [mysociety/whatdotheyknow-theme#23]
**RichardTaylor opened this issue May 31, 2011**

A number of users have made FOI requests prompting the release of practice manager's email addresses eg.

http://www.whatdotheyknow.com/user/john_thompson
http://www.whatdotheyknow.com/user/alfred_bennett

**Comment by garethrees** [comment]
We've started listing these https://www.whatdotheyknow.com/body?tag=surgery. Not sure how complete it is though

**Comment by RichardTaylor** [comment]
Current status is we list 379 GPs. 

Possible source of more:

https://www.nhs.uk/Services/

Visit that page then click on each CCG, then the GP tab.  Data is far from comprehensive. some CCGs have nothing under the GP tab.

**Comment by RichardTaylor** [comment]
Access to contact emails for GPs is discussed in the paper at

https://www.jmir.org/2020/1/e15603

Specific section link:  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6996746/#sec-9title

Some data from 2017 is available at 

https://www.whatdotheyknow.com/list/all?utf8=%E2%9C%93&query=%22Medicine+Optimisation+contact+information+for+GP+practices+in+your+CCG%22&request_date_after=&request_date_before=2022%2F12%2F01&commit=Search

This is an area where we could use WhatDoTheyKnow ourselves to obtain information to use to improve and expand the service (and also give ourselves an extra maintenance challenge!)

The question of if and when we can use our service ourselves is being considered via https://github.com/mysociety/whatdotheyknow-theme/issues/1243

**Comment by garethrees** [comment]
We spoke about this on last night's community & activism call. I've ticketed up two technical suggestions that we could think about if we start to see misuse:

* https://github.com/mysociety/alaveteli/issues/8364
* https://github.com/mysociety/alaveteli/issues/8365

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/Authority_suggestions
