### ISSUE TITLE
Blue Twitter/Facebook Logo

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#235]
Need this changed before we can really update the Twitter theme

![](https://pbs.twimg.com/profile_images/607866768741265408/lGYEG6WT_400x400.jpg)

**Comment by wrightmartin** [comment]
![social-icon](https://cloud.githubusercontent.com/assets/2292925/9873965/3900aaa2-5b9b-11e5-97cd-57f4759a01b7.png)

**Comment by garethrees** [comment]
Added to https://twitter.com/WhatDoTheyKnow

**Comment by garethrees** [comment]
Added to https://www.facebook.com/whatdotheyknowcom
