### ISSUE TITLE
Notes field on PublicBody#show is not highlighted

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#237]
Very easy to miss the notes; might be important.

https://www.whatdotheyknow.com/new/bis
https://www.whatdotheyknow.com/body/bis

Not sure it needs to be quite as bold as on the new request page, but could probably do with _something_?

---

`/bis/new`

![screen shot 2015-06-24 at 09 59 35](https://cloud.githubusercontent.com/assets/282788/8326250/bdbc9e84-1a57-11e5-8aed-389428c02745.png)

`/body/bis`

![screen shot 2015-06-24 at 10 00 25](https://cloud.githubusercontent.com/assets/282788/8326263/dcb26472-1a57-11e5-9441-e6c788520a1d.png)

**Comment by FOIMonkey** [comment]
This was fixed by https://github.com/mysociety/alaveteli/pull/7258
