### ISSUE TITLE
Move "Edit text about you" link on Profile page?

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/whatdotheyknow-theme#241]
One of our users couldn't find the "Edit text about you" link, despite searching the page several times, but found it when I sent a screenshot with an arrow. He's embarrassed but I can see how it happened: there's something about the position of the link that can make it appear "hidden in plain sight" - particularly if there's a link at the end of the "text about you", but also I think because it's out of line with the other three profile editing links. 

![ss 2015-06-26 at 07 51 55](https://cloud.githubusercontent.com/assets/11923618/8396489/9da8a00c-1d9f-11e5-86d4-b67f82319b5f.png)

It's by no means a major issue, but if this could be taken into account if and when this page happens to be worked on for other things, it would be great if it could be moved or made more prominent in some way.

**Comment by garethrees** [comment]
Will cover in https://github.com/mysociety/alaveteli/issues/1524
