### ISSUE TITLE
Blue favicon

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#246]
To match new theme

**Comment by wrightmartin** [comment]
Some rough ideas below. We should also add the opengraph thumbnails, apple touch icons, android icons and windows phone icons at the same time 

![512 copy 2](https://cloud.githubusercontent.com/assets/2292925/8751246/cb0c5a58-2ca3-11e5-9763-3ca0a91f200c.png)
![512 copy 3](https://cloud.githubusercontent.com/assets/2292925/8751248/cb0f9a60-2ca3-11e5-8280-e5df8f36e62c.png)
![512 copy 4](https://cloud.githubusercontent.com/assets/2292925/8751244/cb0b1882-2ca3-11e5-890b-4c89849db0f5.png)
![512 copy](https://cloud.githubusercontent.com/assets/2292925/8751247/cb0f0c8a-2ca3-11e5-8be8-e3e831f687c3.png)
![512](https://cloud.githubusercontent.com/assets/2292925/8751245/cb0bec12-2ca3-11e5-997e-d688a590f75a.png)

**Comment by garethrees** [comment]
I think the `?` is the clearest, and its not a massive change from the current one.
