### ISSUE TITLE
Requests to Scottish authorities - change text to refer to Scottish act

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/whatdotheyknow-theme#250]
A user has made the following comment / request:

"I work for a public body in Scotland and am a strong supporter of FoI and happy to respond to requests. However I do find it irritating to have requests formatted in terms of the 2000 UK Act rather than the 2002 Scottish Act which is actually significantly stronger.
I'd like to make a change request that your standard wording is updated to quote the correct Act for Scottish requests.
Thanks and keep up the good work"

I think he has a point and it would be great if a change could be made to our text.

**Comment by RichardTaylor** [comment]
The suggestion has been made that the problem might be users copying and pasting boiler-plate text into requests citing the 2000 UK FOI Act when making requests to Scottish bodies rather than any problem with the site. 

More details have been requested from user who reported this.

**Comment by RichardTaylor** [comment]
We've had a confirmation that the original concern raised was related to text a user put in the body of the request - the person who got in touch with us thought it was part of a WhatDoTheyKnow.com template, but it isn't. 

I'm going to close this as there doesn't appear to be a problem with WhatDoTheyKnow - but it's something to think about when advising users.
