### ISSUE TITLE
Help text doesn't direct users to check for existing information

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/whatdotheyknow-theme#257]
A public authority has raised the point that our help text doesn't direct users to check our site to see if the information they are about to request is already available due to previous requests. I know this is one of the key reasons we run this service and I agree that this should be in the help text. https://www.whatdotheyknow.com/help/about

**Comment by garethrees** [comment]
It does show a dropdown of similar requests as the user is typing their message though. I doubt many people really read all the docs before making their request.

**Comment by garethrees** [comment]
![screen shot 2015-08-20 at 17 30 52](https://cloud.githubusercontent.com/assets/282788/9389134/4f2e663c-4761-11e5-9b3f-81426121ac51.png)

**Comment by garethrees** [comment]
It also prompts users to view other requests to the same authority:

![screen shot 2015-08-20 at 17 32 04](https://cloud.githubusercontent.com/assets/282788/9389165/7e99c614-4761-11e5-9171-a30251a0e530.png)

**Comment by garethrees** [comment]
That said, it wouldn't hurt to mention it in the help pages.

**Comment by kingqueen3065** [comment]
Yes; I did point out to the officer that auto-suggests come up, and I agree that not many people would read the help pages (other than nerds like me), but I do think they have a valid point and it wouldn't hurt to put it in.

**Comment by Gemmamysoc** [comment]
This is in the [Beginner's Guide](https://www.mysociety.org/2014/08/15/how-to-make-a-freedom-of-information-request-with-whatdotheyknow/) which we'll shortly link to on the Help pages.
