### ISSUE TITLE
Stated number of users is incorrect

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/whatdotheyknow-theme#266]
At https://www.whatdotheyknow.com/help/about#how_many we say there are over 30,000 users. We now have over 90,000 users.

**Comment by garethrees** [comment]
Lets make this dynamic so that we don't have to do it again. Something like:

```ruby
number_with_delimiter(User.count.round(-3), :locale => @locale)
```

**Comment by garethrees** [comment]
\> 80,000

```json
"confirmed_user_count": 82249,
```
