### ISSUE TITLE
Broken link to "what constitutes an FOI request" info

### ISSUE THREAD

**Issue by lizconlan** [mysociety/whatdotheyknow-theme#270]
The link http://aka.justice.gov.uk/information-access-rights/foi-guidance-for-practitioners/procedural-guidance/foi-what-constitutes has been replaced by a page stating that the information has been archived and a link to the archived information. (Which is here: http://webarchive.nationalarchives.gov.uk/20150730125042/http://www.justice.gov.uk/information-access-rights/foi-guidance-for-practitioners/procedural-guidance/foi-what-constitutes)

There doesn't currently appear to be anything similar available from an official source.

(Currently linked from the help/privacy page)

Broken out from #267

**Comment by garethrees** [comment]
Is there an obvious contact person on the archived page? Might be worth half an hour of digging around?
