### ISSUE TITLE
Incorrect geolocation

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/whatdotheyknow-theme#281]
I'm getting the banner again, "Hello! You can make Freedom of Information requests within United States of America at MuckRock.com" screenshot http://puu.sh/lFryt/0c25e7dfe7.png . My current IP is 146.198.204.21

Some time ago, following a spate of this, Ian updated the IP geolocation database and it hasn't happened for a while.

Cheers

Doug

**Comment by kingqueen3065** [comment]
Again today - IP 85.119.101.65

**Comment by garethrees** [comment]
We now use a version of geoip that updates itself (https://github.com/mysociety/alaveteli/commit/a13d1ea07b4050f831aed6926279d8995a53fb42), so I expect this shouldn't happen as often.
