### ISSUE TITLE
Add advice to our users in light of the Investigatory Powers Bill if it becomes law

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#299]
A WhatDoTheyKnow.com user has written asking us about the impact of the Investigatory Powers Bill on the privacy of users of our service. 

If the Bill becomes law we might want to add some content to our help pages about its effect. 

This might be something to do across mySociety and perhaps something we should blog about too.

CC @MyfanwyNixon

**Comment by MyfanwyNixon** [comment]
Happy to blog about it - and even more happy if someone can brief me first :)

**Comment by garethrees** [comment]
We've updated https://www.whatdotheyknow.com/help/privacy pretty recently, and the IP Bill was passed in 2016, so I think we're as up to date as we need to be.
