### ISSUE TITLE
Suggestion: put sign in form above registration form on mobile website

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/whatdotheyknow-theme#302]
On the mobile website, the registration and sign-up form are on the same page, and the registration form is first:
![screenshot_2016-03-10-16-34-29](https://cloud.githubusercontent.com/assets/11923618/13676680/b14d4f00-e6de-11e5-8834-30dfa8a20ccc.png)
![screenshot_2016-03-10-16-34-39](https://cloud.githubusercontent.com/assets/11923618/13676686/b5bf4bf6-e6de-11e5-9901-34c9c045bf70.png)
Hopefully most people will log in more than once so for a user ease point of view, to my mind it would make more sense to have the log-in form first and the registration form below the fold. Also we have people with limited technical experience who attempt to sign up whilst they are already signed up and get very mixed up, perhaps this could be a minor change to mitigate against that.
Unimportant though

**Comment by WilliamWDTK** [comment]
See also:
- https://github.com/mysociety/alaveteli/issues/8186
