### ISSUE TITLE
Warn users we redact email contact details from replies

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#308]
Users obtaining email contact details find they the addresses they wanted redacted from their response; this often confuses them and they ask the volunteer team to help and unredact the responses. 

Sometimes users write to the public body and complain, the public body then gets confused, and I suspect our reputation is damaged as they don't understand why their message isn't getting through. 

We should warn users that this will happen. 

See also a proposed technical solution:

https://github.com/mysociety/alaveteli/issues/10

This probably involves adding to the text at:
- https://www.whatdotheyknow.com/help/officers#mobiles (Actually we don't always obscure emails in annotations - should we?) 

and
-  in the right column of the "make a request" page with advice, add a section warning against making requests for email contact details. 

I think ideally we do want to support making requests for email contact details so this issue is just to deal with the immediate issue of users not being aware that our system currently redacts them from responses.

**Comment by HelenWDTK** [comment]
We cover this here: https://www.whatdotheyknow.com/help/how#email_addresses Closing as complete
