### ISSUE TITLE
Implement standard mySociety footer on whatdotheyknow.com

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/whatdotheyknow-theme#310]
Moving this from https://github.com/mysociety/sysadmin/issues/676, where there is lots of background and discussion.

WhatDoTheyKnow does have the mySociety logo top right and 'WDTK is a mySociety project' bottom left; however the introduction of a new footer would make the affiliation more prominent.

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/whatdotheyknow-theme/pull/312
