### ISSUE TITLE
Number of FOI requests indicated when filters are applied

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/whatdotheyknow-theme#32]
The homepage says there are 'over 107,536 requests' (strangely specific for an 'over' number?).

I went to 'view requests' and filtered for all reports, 20-26 Feb. With 20 pages of results, the figure should surely be 500? 

The number below the search box indicating 'FOI requests found' showed 103,335. This changes to 103,243 when I navigate to page 20. I am confused.

**Comment by garethrees** [comment]
This is fixed.

Home page now says the exact number of requests, and the request/search pages show "About N requests".
