### ISSUE TITLE
Analyse drop-outs in the Adwords -> completion user journey

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/whatdotheyknow-theme#340]
ref #298 

As with mysociety/writetothem#345 and https://github.com/mysociety/theyworkforyou/issues/1165 I think that we should do some analysis on the journey from Adword click to drop-out/conversion, and refine our ads/landing page/the site/goals according to what we find.

The Adwords conversion rate for WDTK, looking at the last 30 days, is 4.66%.

@garethrees or @jacksonj04 can you confirm that there's just one success goal for this conversion tracking, confirmation page of the request-making page? The conversion rate seems high, but not impossibly so.

Cost per conversion is showing as US$18.30. That's not particularly cheap, but of course it's not 'real' money, and we also get value from people visiting the site to have a browse, without making a request.

We may wish to:
- Add further success goals. Eg, spending a certain amount of time on the site, or making a search on a word or phrase. I can't do this so a dev would need to.

I think we should definitely:
- isolate data for people arriving from Adwords ads (even better if we can do it per ad group, as that would help us weed out and pause any ad groups that aren't delivering 'qualified traffic' - ie people likely to convert)
- look at their path through the site
- find the most common points of drop-out. 
-  decide whether, for drop-outs, the issue is with the Ads or WDTK itself

Some of these could enrich and inform currently proposed experiments, see https://github.com/mysociety/alaveteli-experiments/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20adwords
I think I can do most of this part, unless anyone else feels inspired to do so!

**Comment by garethrees** [comment]
We're not too focused on simply growing requests now – that's happening quite well on its own!
