### ISSUE TITLE
Install Readspeaker or similar

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/whatdotheyknow-theme#341]
@kingqueen3065 suggests:

> would mySociety consider using Readspeak on their websites? It works quite well. For an example, try the "Listen" button on here: http://www.disabilitynewsservice.com/bus-companies-using-loopholes-to-evade-access-laws/

Clearly this would be a good step towards further accessibility on our sites - and possibly fulfills some of our desires to reach wider audiences.

http://www.readspeaker.com/benefits-of-text-to-speech/ explains some of the people this addition would help, among them:
- People with learning disabilities
- People who have literacy difficulties
- People with visual impairment

No explicit price list online; would have to approach them. Given the vast amount of content on the site this might not be the most practical model; also as mentioned on [TWFY](https://github.com/mysociety/theyworkforyou/issues/1169) I suppose one question is to what degree such users tend to have sorted out solutions for themselves, eg screen readers.

**Comment by MyfanwyNixon** [comment]
This suggestion has also been ticketed on FMS, TWFY and WTT.

**Comment by lizconlan** [comment]
All I could find on pricing is http://www.readspeaker.com/pricing/ which reveals their pricing model as "a one-time setup fee and an annual rental service fee" but doesn't go into specifics. As an indication though, it looks as though their standard pricing is based on "pageviews per month" - no mention of not-for-profit pricing but as their central message is "contact us", no harm in asking.

**Comment by garethrees** [comment]
Don't operating systems have this built in these days? OS X has built-in text to speech, although it doesn't do the clever highlighting of the current sentence. I'm not sure how well this would work for Alaveteli, given that the text is often pretty unstructured and most of the content often comes in attachments that we struggle to parse to text.

**Comment by garethrees** [comment]
@MyfanwyNixon is going to send an initial enquiry in to pricing.

**Comment by MyfanwyNixon** [comment]
Contacted.

**Comment by garethrees** [comment]
I don't think this is something we're going to get to any time soon. I think our approach should be writing markup in an accessible way that allows third party readers to operate correctly.
