### ISSUE TITLE
Marking messages as spam in the WDTK mailbox

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#347]
See "Marking messages as spam in the WDTK mailbox" sent to `dev@wdtk`.

**Comment by lizconlan** [comment]
Had a dig into this but didn't come up with anything concrete...

The email address being used is already an alias (which gets processed by a script to remove auto responses before forwarding) so we can't just add an alias.

I checked the SPF and record, which appears to be correct ([spf-record.de](http://www.spf-record.de/spf-lookup?domain=whatdotheyknow.com)) suggested a couple of errors but these appear to be red herrings.

The only think I can think is that Google is confused by the fact that the alias is forwarding to multiple addresses, it fits the technical description of a distribution list and is mistakenly treating it as a subscription-based mailing list as per https://en.wikipedia.org/wiki/Email_alias (the "Control issue" and "Abuse issue" sections may be of interest).

After discussing this with @garethrees, a possible next step could be to contact Google to ask if they have any insight into why this is happening and what we might be able to do to fix it.

**Comment by lizconlan** [comment]
Have contacted Gmail support via the Gear wheel > Help > Feedback mechanism

Along the lines (I forgot to copy-paste (sorry) and as it wasn't a regular email, I didn't get a copy) of:

> The address we're using as an alias for our real Google Apps support account is being incorrectly identified as a mail list by Gmail. Anyone logged into the underlying account trying to flag incoming mail as spam is asked if they want to unsubscribe from the alias address leaving us worried that we're flagging our own account as a spammer. [Plea for help and/or advice]

(Our address details purposely left out of this in-public comment)

**Comment by garethrees** [comment]
Still waiting on response from google

**Comment by garethrees** [comment]
Any response?

**Comment by lizconlan** [comment]
To try/check - see if we have [Google's DKIM information](https://support.google.com/a/answer/174124?hl=en) in our DNS settings. (A different problem but H/T @edent https://shkspr.mobi/blog/2014/01/why-are-messagelabs-blocking-my-emails/ for the nudge)

**Comment by lizconlan** [comment]
Contacting Google via Gear wheel > Help > Feedback appears to have been a dead end. May have to find another point of contact and retry (if [DKIM](#issuecomment-271251295) has no effect)

**Comment by lizconlan** [comment]
Ah, intel from @sagepe - apparently we're adding a `List-id` header... /o\

**Comment by garethrees** [comment]
> apparently we're adding a `List-id` header

What's the TL;DR implication of this? Presumably that's why Google is suggesting its a mailing list? What are the next actions? Can we remove the header?

**Comment by sagepe** [comment]
Having discussed this briefly with @crowbot we think the header can probably be removed. It apparently dates back to the time that this was a genuine list, rather than an actual mailbox.

Most of the advantages of the `List-Id` header seem to be related to client behaviours, filtering, etc.

It's simple enough to remove from the exim config, and if it did cause any problems, simple enough to add again.

**Comment by sagepe** [comment]
I've removed the config that was adding the List-Id header (commit `8eb6ca4` in the internal puppet repo).

**Comment by lizconlan** [comment]
ToDo - towards the end of the sprint, check whether this has fixed the problem

**Comment by lizconlan** [comment]
Looks like this has worked \o/ 🎉
