### ISSUE TITLE
User suggestion: Note image size limit on profile page

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/whatdotheyknow-theme#348]
'There appears to be a display size limit, so why not tell the public what that limit is ?. My suggestion is that size 96 x 96 pixels should be mentioned on the [[profile] page (https://www.whatdotheyknow.com/profile/set_photo), or on another web page, as it would help people get the best possible picture.'

**Comment by garethrees** [comment]
It doesn't matter, as the photo gets cropped square (by the user, so they can select the best part) and then scaled down.
