### ISSUE TITLE
Survey to requesters: include "to make the answer public"

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/whatdotheyknow-theme#351]
A user has informed me regarding the automated survey sent some time after a user's first FOI request, entitled "Can you help us improve WhatDoTheyKnow?", 

"The only reason I used your site was to make the answer public. I thought that was the whole point of your site. Curiously, it is not even mentioned in your survey, as far as I could see."

I can't find a way of triggering the survey myself to see the options, but assuming the above is true, then adding this option would make sense.

**Comment by kingqueen3065** [comment]
having seen the survey now, there isn't a question as to "why" people used WhatDoTheyKnow to make a FOI request, but it does sort of ask around it i.e. how easy WhatDoTheyKnow is to use, what other mechanisms (if any) one has used to make a FOI request, etc. etc. I should imagine that one of the reasons people might have or give might be that it's in public (for better or for worse - thinking of the minority of people who use it as a way of publicising potentially defamatory allegations, as well as those who want their request and response to be in public for the best of transparency reasons!)

**Comment by Gemmamysoc** [comment]
We're going to chat about this with the mySociety research team in December - will let you know any plans from there

**Comment by Gemmamysoc** [comment]
We spoke to @Rebeccarumbul and @ajparsons from the mySociety research team about this. They haven't assessed the results of the survey yet, but the Alaveteli developers have given them access to the responses. Based on the assessment of responses, the research team will decide on whether to continue to run the survey (but a shorter, more succinct version) or to stop running it.

**Comment by garethrees** [comment]
Just assigning @ajparsons as team research will be looking at this

**Comment by MattK1234** [comment]
I've just had a look through the new user survey and this question/choice isn't included.

**Comment by confirmordeny** [comment]
If the question has been removed then perhaps we can close this issue?

**Comment by garethrees** [comment]
Yeah this is pretty old and the survey got updated [in 2021](https://github.com/mysociety/whatdotheyknow-theme/issues/580#issuecomment-874051225) so I imagine this question got dropped.
