### ISSUE TITLE
Qualify our offer to reveal email addresses

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/whatdotheyknow-theme#363]
We often get asked to reveal email addresses obfuscated by Alaveteli. Occasional requests aren't a problem, but the following two situations could perhaps be made clearer in the [WhatDoTheyKnow FUQ](https://www.whatdotheyknow.com/help/officers#mobiles) which states:
> If you need to know what an address was that we've removed, please get in touch with us. Occasionally, an email address forms an important part of a response and we will post it up in an obscured form in an annotation. 
1. Often authorities respond to requesters telling them that the information is held by another authority and FOI requests may be made to them via email at <email address>. The requester contacts us for the email address and we direct them to the relevant page to send a request to the new authority. Or authorities have email signatures saying to contact <email address> to request an internal review; the user requests the email address and we explain that they can send an internal review using our website. Help text to redirect some of that would be great.
2. Sometimes people use our service to request a lot of contact details; for example details of all GP practices associated with a named CCG. Or they send multiple FOI requests to (for example) all primary schools in an area, asking for contact details for their caretaker or whatever. Us admins then have to respond saying that we can't afford the time to reveal large numbers of email addresses, and retrospectively advise requesters that it is therefore not appropriate to use our service to request contact info, particularly in bulk. Help text to make this clear would also be of use.
Cheers

Doug

**Comment by Gemmamysoc** [comment]
I have added this to policies review document that we'll discuss in person on 2nd February.

**Comment by garethrees** [comment]
We've added:

> Our volunteer team doesn’t have the capacity to deal with large numbers of requests to reveal email addresses so currently our service is not suited to requests for email contact details.
