### ISSUE TITLE
Add comment to help pages about additional log retention when notified of impending court order

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#364]
At 

https://www.whatdotheyknow.com/help/privacy#cookies

relating to webserver logs we say:

>We routinely keep this information for 28 days.

Is "routinely"  sufficient or should we explicitly add a line saying:

> From time to time we are required by law to hold material for a longer period when we are formally notified of pending requests to seek court orders to obtain user information. We always seek to minimise both the amount of information retained, and the length of additional time we hold material for.

**Comment by Gemmamysoc** [comment]
I have added this to policies review document that we'll discuss in person on 2nd February.
