### ISSUE TITLE
Investigate whether particular users have the same IP address

### ISSUE THREAD

**Issue by lizconlan** [mysociety/whatdotheyknow-theme#365]
See support email for details

**Comment by lizconlan** [comment]
still to do - sanitise the preserved log files (taking ages so may defer this until after the break)

**Comment by garethrees** [comment]
Can probably just drop them – maybe make a note of what we did to generate them.

**Comment by lizconlan** [comment]
Notes written up in a Google Doc which I don't want to link to in public as it includes speculation about potentially vexations accounts - but it should be in an internally shared Google Drive folder

There's one more log file to clean/investigate (and there's some more followup which would be interesting but I don't want to soak up dev/bug fix time doing so) at the moment but this won't take long a isn't urgent as it's a copy of a current log, I no longer have any unredacted expired material.

**Comment by garethrees** [comment]
> Notes written up in a Google Doc which I don't want to link to in public as it includes speculation about potentially vexations accounts - but it should be in an internally shared Google Drive folder

You can make the doc "@mysociety.org only" and link here :)

> There's one more log file to clean/investigate… I no longer have any unredacted expired material.

Can you just delete it if there's no value there?

**Comment by lizconlan** [comment]
log files deleted

**Comment by lizconlan** [comment]
Internal only brain dump here: https://docs.google.com/document/d/1BYo5F4i6-2zkMA_qFQBK1cIwzcbKgUcPRKG7QoC6YYY
