### ISSUE TITLE
Downloaded correspondence has large black box in PDF

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/whatdotheyknow-theme#367]
The "Download a zip file of all correspondence" option is broken; at the moment the correspondence.pdf file has a black box superimposed over the title of the request.

![ss 2016-12-17 at 08 38 30](https://cloud.githubusercontent.com/assets/11923618/21289583/f3d026d4-c498-11e6-8407-b8e261594b74.png)

example:

[employment_rights_act_1996.zip](https://github.com/mysociety/whatdotheyknow-theme/files/659082/employment_rights_act_1996.zip)

Thanks

**Comment by garethrees** [comment]
Probably related to https://github.com/mysociety/alaveteli/issues/3102

**Comment by lizconlan** [comment]
Note to self - look at the downloaded correspondence.pdf file, not the page

**Comment by lizconlan** [comment]
Not specific to admin logins

**Comment by garethrees** [comment]
> Note to self - look at the downloaded correspondence.pdf file, not the page

Pretty sure this gets cached, so be aware that you may need to clear if you make changes

**Comment by lizconlan** [comment]
@garethrees brilliant timing!
