### ISSUE TITLE
Assist volunteer admins to add large set of new schools

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#380]
A user of WhatDoTheyKnow has provided a spreadsheet of around 15,000 schools with email addresses which they've found on local authority websites.  The user's spreadsheet has Edubase IDs, and many schools already listed on WhatDoTheyKnow have the same IDs in tags like urn:xxxxxx 

In order to remove those schools we already list from the spreadsheet before uploading it a list of the urn tags from WhatDoTheyKnow is required. 

See WhatDoTheyKnow email support thread subject line: "Primary School Contact Details"

**Comment by garethrees** [comment]
```sql
\copy (SELECT public_bodies.url_name, has_tag_string_tags.value FROM has_tag_string_tags INNER JOIN public_bodies ON has_tag_string_tags.model_id=public_bodies.id WHERE has_tag_string_tags.model = 'PublicBody' AND has_tag_string_tags.name = 'urn') To '/tmp/school-urns.csv' With CSV
```

**Comment by garethrees** [comment]
Emailed CSV to `team@`.
