### ISSUE TITLE
Wording tweak for bodies tagged EIR_Only

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#382]
Currently when a body is [tagged EIR_Only](https://www.whatdotheyknow.com/body?tag=eir_only) (Only subject to Environmental Information Regulations, and not the Freedom of Information Act) the WhatDoTheyKnow system adds the following:

>"You can only request information about the environment from this authority. "

What we mean in really is: "As we understand it you only have a legal right to obtain information about the environment from this body". 

In many cases the bodies in question have the character of a public body and we'd be happy for users to make any "Freedom of Information" style requests to them. 

For example a request to the Cardiff Harbour Authority https://www.whatdotheyknow.com/body/cardiff_harbour_authority for non-environmental material would I think be an acceptable use of WhatDoTheyKnow.

**Comment by MattK1234** [comment]
Looks like this was done by https://github.com/mysociety/alaveteli/pull/4931

We now say:

> You only have a right in law to access information about the environment from this authority

which seems to fit the bill.
