### ISSUE TITLE
Add banner advertising the current call for volunteers 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#383]
Can we have a banner on the site pointing to the current blog post seeking new volunteer administrators? 

https://www.mysociety.org/2017/02/23/could-you-join-the-whatdotheyknow-team/

Suggested text:

>We're seeking more volunteers to help us run this site. [See our blog post for more information.  ](https://www.mysociety.org/2017/02/23/could-you-join-the-whatdotheyknow-team/)

Thanks,

**Comment by RichardTaylor** [comment]
I hope it's OK to reopen this on the grounds I can't see the banner on the site yet.

**Comment by garethrees** [comment]
Sorry, I'd thought this got deployed, but it had not. Just deployed it.
