### ISSUE TITLE
Facilitating requests to Crown Dependencies

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/whatdotheyknow-theme#388]
A suggestion from a regular user.

I remember sometime you ago you saying that you put the idea of adding crown dependencies like the Isle of Man on the back burner due to the way that the system works. 

> I have a few suggestions. 

1. Why don't you change the background when people make an FOI to somewhere like Isle of Man and put in a note that different laws apply.
2. How about setting up a different domain like whatdotheyknow.im. You can allow people to use your user accounts from the main site but it would show it is different.

**Comment by garethrees** [comment]
I think this would come under a new international install of alaveteli and is out of scope for WDTK
