### ISSUE TITLE
Compact view of own requests

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/whatdotheyknow-theme#396]
A user writes:

"Hi, is there a way to change the format of the list of my requests, so that each request is just one line and takes less space? I ask because if I will be making say 50 requests, it would be nice to be able to see as many of them as possible on the screen at once instead of having to scroll and change pages. 
Thanks"

**Comment by garethrees** [comment]
There's no way to do this at the moment.

Will link to https://github.com/mysociety/alaveteli/issues/1524 for when we get to improving these pages.
