### ISSUE TITLE
Post new Help pages on WDTK

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/whatdotheyknow-theme#397]
The final text for the new WDTK Help pages is here: https://docs.google.com/document/d/1qrv-qpODKnUkTgbtr0pzkQeeeaXDmVksNAePYUbGSSk/edit# 

Please speak to me if anything is not clear :) 

## Updates
- [x] about.html.erb
- [x] requesting.html.erb
- [x] privacy.html.erb
- [x] officers.html.erb
- [x] credits.html.erb
- [x] api.html.erb

## New pages (need to be added to menu)
- [x] principles.html.erb 
- [x] house_rules.html.erb
- [x] how.html.erb - needs links, check markup - headings seem a bit badly structured.
- [x] complaints.html.erb
- [x] volunteers.html.erb
- [x] beginners.html.erb

## Other
- [ ] Welsh versions

## Checks
- [x] Curly single and double quotes
- [x] Space at end of `<ul>`
- [x] Is cookie table complete? 
- [x] Duplication of "deleting requests" section in `privacy.html.erb`
- [x] Unresolved comments/suggestions in the original
- [x] Check for missing sections referred to from the main app.

**Comment by kingqueen3065** [comment]
It needs Rob adding to the credits. Possibly others as well.

**Comment by Gemmamysoc** [comment]
okay, added :)
