### ISSUE TITLE
Broken link to ICO guidance - outgoing message footer

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#400]
The outgoing message footer contains a link to

https://www.whatdotheyknow.com/help/ico-guidance-for-authorities

which WhatDoTheyKnow redirects to:

https://ico.org.uk/media/for-organisations/documents/how-to-disclose-information-safely-removing-personal-data-from-information-requests-and-datasets/1432979/how-to-disclose-information-safely.pdf

The ICO have moved that document to a new URL - the number has changed - it's now at:

https://ico.org.uk/media/for-organisations/documents/how-to-disclose-information-safely-removing-personal-data-from-information-requests-and-datasets/2013958/how-to-disclose-information-safely.pdf

**Comment by garethrees** [comment]
Fixed by https://github.com/mysociety/whatdotheyknow-theme/commit/8226559da7b4a4952e098ee56ec91561ad5e019c
