### ISSUE TITLE
"Delivered" for non-delivered items

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/whatdotheyknow-theme#404]
This request: https://www.whatdotheyknow.com/request/erp_systems_392?nocache=incoming-988091#incoming-988091

says "Successful" and a green tick, but there's a MDF and on expanding the text contradicts - "This message could not be delivered." 

![untitled-1](https://user-images.githubusercontent.com/11923618/26856728-89f8b6e8-4b1d-11e7-8c6c-e78e1fbb65ac.png)
 

```
Delivery logs removed and copied to private repo https://github.com/mysociety/sysadmin/issues/823
```

Also: the ongoing email delivery problems to Selby College; IIRC the BOFH was going to look at this - any news? (sorry, that was meant in jest, I don't mean to suggest the sysadmin is a B or F H, I don't know her/him)

**Comment by garethrees** [comment]
Its on my list to reply to that thread – I will do so imminently. TL;DR is that we don't think there's anything wrong our end and were going to see if they would be willing to talk to us to get to the bottom of it. This new request might help us debug further though.

**Comment by garethrees** [comment]
Ah, this looks like a caching issue of the delivery status. I think I know [what this is](https://github.com/mysociety/alaveteli/blob/develop/app/views/request/_outgoing_correspondence.html.erb#L16).

The request is now showing failed.

![screen shot 2017-06-07 at 10 20 50](https://user-images.githubusercontent.com/282788/26871450-12618198-4b6b-11e7-9244-89d2bb61472c.png)

**Comment by garethrees** [comment]
Okay so there are two issues here:

- The short status gets cached incorrectly. I think we can remove the front end caching now because the calculation is cheaper since https://github.com/mysociety/alaveteli/pull/3476.
- The original issue, where we're sending mail to `@selby.ac.uk` and its failing, but seems to work when sent to the same address outside of the app.

**Comment by kingqueen3065** [comment]
gareth: excuse my thickness but does this mean I should do something? "Edited the title so that this ticket is about the caching problem. We'll track the actual mail delivery issue in mysociety/sysadmin#823 and the email thread." - I don't have access to that repository

cheers

**Comment by garethrees** [comment]
No action required on your part!

Ah, yes, it is a private repo. I was going to reply to the email thread yesterday, but then waited to see if there was any new info from this new request. I'll check in with our sysadmin today to see what the status is.
