### ISSUE TITLE
Typo in /help/officers

### ISSUE THREAD

**Issue by mbimmler** [mysociety/whatdotheyknow-theme#406]
In https://www.whatdotheyknow.com/help/officers  the very first question reads
"I just got here from bottom of an FOI request, what is going on?"
but misses a "the" and needs to read
"I just got here from the bottom of an FOI request, what is going on?"
instead.

[A user notified us about this]

Thanks!

**Comment by garethrees** [comment]
@lizconlan this is marked as awaiting deploy but there's no commit or PR referencing it? Its not live yet. Is there anything stopping us getting this shipped?

**Comment by lizconlan** [comment]
This is now on the live site \o/
