### ISSUE TITLE
Make option to send follow-up to different address more prominent

### ISSUE THREAD

**Issue by mbimmler** [mysociety/whatdotheyknow-theme#407]
When writing a reply, we offer users the option to not simply reply to the sender of the last incoming message, but to either the main contact for the authority or any other (?) sender that has been involved in the thread.  This is very useful, as sometimes the last incoming message may have been sent by a "Do Not Reply" mailbox sending automatic notifications, but not allowing incoming messages. Another typical case is the Home Office which likes to send its responses from a "FOI Responses" mailbox that does not allow incoming messages, puzzling many a user who tries to follow up after a response.

The "Don't want to address your message to...... You can also write to...." message appears to be quite prominent because it is at the top of the "draft a reply" page as seen by the user. However, it seems that some users completely miss out on the possibility because their eye jumps right to the message box where they start typing and then they only look at things below the message box. 

Any good usability / design ideas of how we could make this option of writing to a different email address more prominent?  I briefly thought of putting the sentence below the text box but that makes little sense, as clicking on the link to choose a different recipient takes you to a new page and hence the entire message typed in the text box would get lost. So the user does need to make this decision before starting to type...

**Comment by garethrees** [comment]
Closing as this is being considered in https://github.com/mysociety/alaveteli/issues/4354
