### ISSUE TITLE
html displaying on 'you will be emailed updates' alert

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/whatdotheyknow-theme#408]
When you follow a request, this displays:

![fireshot screen capture 1131 - bullying in plymouth city council - a freedom of _ - www_whatdotheyknow_com_request_bullying_in_plymouth_city_counci](https://user-images.githubusercontent.com/944656/27275410-30f7d27a-54cf-11e7-82df-b53c98276c54.png)

Similarly with an unfollow:

![unfollow](https://user-images.githubusercontent.com/944656/27275435-4ad6c4f8-54cf-11e7-9ab4-bc60cc7f24c8.png)

**Comment by garethrees** [comment]
Just reopened https://github.com/mysociety/alaveteli/issues/3978#issuecomment-309369209 with the same comment, so closing this one. Thanks for reporting!
