### ISSUE TITLE
Remove link to FOI register from API page

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#414]
There's a link which no longer works to FOI register on GitHub at https://www.whatdotheyknow.com/help/api 

A user reported this to us.

**Comment by garethrees** [comment]
Oh, I thought I'd fixed this in https://github.com/mysociety/whatdotheyknow-theme/pull/403.

**Comment by lizconlan** [comment]
In the first para of the final section

![screen shot 2017-08-29 at 16 13 37](https://user-images.githubusercontent.com/27760/29828583-143ce678-8cd5-11e7-9fa6-47a74feea84d.png)
