### ISSUE TITLE
Try Varnish 3.0

### ISSUE THREAD

**Issue by sebbacon** [mysociety/whatdotheyknow-theme#43]
Alaveteli 6.x includes a queue of request pages that should be invalidated (e.g. because a new reply has come in, or the user has changed their user name).  There's a script (`purge-varnish`) which consumes the queue and makes `PURGE` requests to Varnish.

When we deployed it, Varnish started falling over periodically.  We thought this was a bug that may have been fixed in 3.0 (sorry for no reference!).

So it would be worth installing Varnish 3.0 from squeeze backports and re-enabling the purge functionality (can't remember how we disabled it, but relevant settings are `VARNISH_HOST` in `general.yml`, the current varnish VCL, and the init script that ensures the `purge-varnish` process is running).  Note also that the `purge` VCL verb has become `ban` in 3.0 - there's a brief comment in the sample VCL at `scripts/varnish-alaveteli.vcl`.

**Comment by garethrees** [comment]
We don't really integrate varnish any more, so closing
