### ISSUE TITLE
Add new conversion in Adwords

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/whatdotheyknow-theme#432]
We currently only have one action that counts as a conversion for WDTK in Adwords - making a request.
Louise notes that there are two other activities which would be good to add:

- spending a significant amount of time on the site (this is currently a goal in Analytics)
- signing up for an email alert

**Comment by HelenWDTK** [comment]
@MyfanwyNixon  Is this something that we are still interested in doing, or can this be closed now?

**Comment by MyfanwyNixon** [comment]
I think this may be something we can't even track any more in the new analytics, so I will close it.
