### ISSUE TITLE
Pro logo pixalated on retina screens

### ISSUE THREAD

**Issue by gbp** [mysociety/whatdotheyknow-theme#439]
![screenshot-2017-11-16-wdtk-pro](https://user-images.githubusercontent.com/5426/32905457-edb95152-caf1-11e7-9525-093afb4559a4.png)
![screenshot-2017-11-16-wdtk](https://user-images.githubusercontent.com/5426/32905458-ee0e6f84-caf1-11e7-9391-a3f1ca3adad4.png)

**Comment by garethrees** [comment]
This got merged in https://github.com/mysociety/whatdotheyknow-theme/commit/42b20b2c97d8a2182a6faa438160571b43bd8e95
