### ISSUE TITLE
Unclosed tag in classification form

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/whatdotheyknow-theme#446]
Hi

I viewed [this request](https://www.whatdotheyknow.com/request/development_viability_of_futuris?post_redirect=1) when logged in as a Pro Admin, and while logged out, and it appears like this, as expected:

![ss 2017-12-13 at 09 29 08](https://user-images.githubusercontent.com/11923618/33963546-2f78c9ae-e04d-11e7-8232-1e16150bd4cf.png)

When logged in as a standard user, it looked like this:

![ss 2017-12-13 at 09 29 48](https://user-images.githubusercontent.com/11923618/33963557-3a250e4e-e04d-11e7-8684-2eabd19419f5.png)

Logging back out makes it appear OK again.

My immediate suspect is an unclosed tag in HTML or CSS in the "please classify other user's request" dialogue, which displays only when logged in as a non-admin user.

![ss 2017-12-13 at 09 33 55](https://user-images.githubusercontent.com/11923618/33963628-7ab835a8-e04d-11e7-8337-4c96536bb26e.png)

**Comment by garethrees** [comment]
@wrightmartin things rings a bell and I'm _sure_ we ended up fixing this?

**Comment by garethrees** [comment]
Nope, still looks like there's a bug with the classification form:

<img width="1511" alt="screen shot 2018-10-19 at 17 58 11" src="https://user-images.githubusercontent.com/282788/47232803-a29e3f80-d3c8-11e8-8e7f-c8d286dea552.png">

**Comment by garethrees** [comment]
```
I ended up doing a search across all the .po files for `<small>` and then hand checking them one by one - here’s where I found them

    modified:   locale/ar/app.po
    modified:   locale/bg/app.po
    modified:   locale/bs/app.po
    modified:   locale/ca/app.po
    modified:   locale/cs/app.po
    modified:   locale/cy/app.po
    modified:   locale/de/app.po
    modified:   locale/en/app.po
    modified:   locale/en_RW/app.po
    modified:   locale/en_UG/app.po
    modified:   locale/es/app.po
    modified:   locale/es_NI/app.po
    modified:   locale/es_PY/app.po
    modified:   locale/gl/app.po

    modified:   spec/fixtures/locale/en/app.po
    modified:   spec/fixtures/locale/en_GB/app.po
    modified:   spec/fixtures/locale/es/app.po

```

**Comment by garethrees** [comment]
Strangely, transifex currently shows the broken `msgid` – even though the `po` file shows the correct one

![screen shot 2018-12-20 at 10 39 08](https://user-images.githubusercontent.com/282788/50337395-e3b9e980-0508-11e9-9425-f2df9cf3a8e1.png)

![screen shot 2018-12-20 at 10 39 24](https://user-images.githubusercontent.com/282788/50337394-e3b9e980-0508-11e9-890a-987fadf4b04c.png)

(and `app.pot` has the correct `msgid` too)

**Comment by lizconlan** [comment]
[Error appears to have snuck in here](https://github.com/mysociety/alaveteli/commit/bce54f66531d53390a181902ec9b090051f6497b#diff-6eb476981269d44b2705def1df9648aeR2534)

**Comment by lizconlan** [comment]
Hmm... if you download the `app.pot` file from Transifex, it's done this...

```
msgid ""
"The authority do <strong>not have</strong> the information <small>(maybe "
"they say who does)</small>"
msgstr "The authority do <strong>not have</strong> the information "
"<small>(maybe they say who does)"
```
(string wrapping of the `msgstr` mine to make it easier to see in this thread)

Our local copy of the `app.pot` file looks like this...

```
msgid "I'm still <strong>waiting</strong> for my information <small>(maybe you got an acknowledgement)</small>"
msgstr ""
```

Presumably - although I have not managed to track down any confirming documentation - as we've set the project source language to "en" and supplied an `en/app.po` translation file - it's merging that in as the default translations which are then inherited as the source for all other languages rather than (as I'd previously assumed) using the `msgstr` from the uploaded `app.pot` file.

Useful to know.

**Comment by lizconlan** [comment]
To fix
- [x] fix the `en/app.po` translation
- [x] `tx push -s -l en -r alaveteli.apppot`
- [x] edit the now broken translations in Transifex (fetch from history, add </small> tag, save)
- [ ] ???
