### ISSUE TITLE
Banner on WDTK re. WDTK 10th birthday party

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/whatdotheyknow-theme#450]
Please can we have a banner on WDTK that says:

'WhatDoTheyKnow is 10! To express an interest in attending WhatDoTheyKnow's 10th birthday party, please fill in [this form](https://docs.google.com/forms/d/e/1FAIpQLScO4SYE-qbUgKq0HlOGhSMQPyjk6iL2ypr5zJmhcHebI0vwGw/viewform)'

**Comment by lizconlan** [comment]
Done!
