### ISSUE TITLE
Add text describing the pro service to the help page aimed at FOI officers

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#454]
On the help page for officers we have a section titled:

"I can see a request on WhatDoTheyKnow, but we never got it by email!"

https://www.whatdotheyknow.com/help/officers#spam_problems

but not:

"I've got a request by email but I can't see it on WhatDoTheyKnow.com"

We've had a small handful of FOI officers contacting us; FOI officers may need reassuring they can still reply and their replies will get through. 

We do mention private requests at:

https://www.whatdotheyknow.com/help/requesting#private_requests

but that's not a section aimed at FOI officers.

**Comment by garethrees** [comment]
We should add ths note https://github.com/mysociety/alaveteli/blob/c59917b3fe4ce6c9a2bac84d5374e3d2ab4797e9/app/views/outgoing_mailer/_followup_footer.text.erb#L5-L8

**Comment by garethrees** [comment]
Just pasting some text I've been using to reply to information officers that may be useful when drafting some of this:

> For various reasons, some requests may not appear immediately on the WhatDoTheyKnow website.
> 
> * Our search indexing takes some time before requests are indexed for public visibility.
> * Admins may hide requests from other users if they contain personal information in the request.
> * Requests may be made through our new WhatDoTheyKnow Pro [1] service, which allows journalists, activists and campaigners to keep requests and responses private while they work on their investigation.
> 
> We do state that "Please note that in some cases publication of requests and responses will be delayed.” in the footer of the request emails we send.
> 
> Our decision if to publish, or not, a correspondence thread does not impact a public body's duties to respond.
> 
> I can confirm that the email addresses are valid addresses to reply to.

(Via https://github.com/mysociety/whatdotheyknow-theme/issues/473#issuecomment-407677013)

**Comment by RichardTaylor** [comment]
Adding a +1 as a FOI officer as been in-touch to suggest this.

**Comment by garethrees** [comment]
Not aimed at FOI officers as much but https://github.com/mysociety/whatdotheyknow-theme/pull/586 has been merged and so https://www.whatdotheyknow.com/help/pro includes some more general info on batch and embargoes.

**Comment by FOIMonkey** [comment]
+1 We had an authority write today because they were concerned that a request they had received wasn't shown on their page on the site.

**Comment by FOIMonkey** [comment]
+1 I have dealt with a couple of queries this past week from FOI officers who were confused as to why they couldn't see requests on the site, and wondered if this meant that they had been withdrawn.

**Comment by FOIMonkey** [comment]
I've come up with some text that'll hopefully do for now https://github.com/mysociety/whatdotheyknow-theme/pull/1520 We can always expand on it later.

I accidentally closed this when leaving myself notes on my fork whilst I went to check my spelling 🤦‍♀️ It has been a long day! 😅

**Comment by HelenWDTK** [comment]
Closing as complete
