### ISSUE TITLE
Improve personal info warning text on new requests page

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/whatdotheyknow-theme#462]
A user has suggested adding text to the warning:

> Everything that you enter on this page, including your name, will be displayed publicly on this website forever.
> 
> ...
> 
> Can I request information about myself? No! 

They suggest:

> maybe you need to put out the risk - after "forever" something like , "So be careful about putting personal details on here - they can be used by an identity thief to defraud you. If you want information just about yourself, you're better off writing directly to the authority

**Comment by garethrees** [comment]
I think the help pages are clear about the advantages and consequences of publication, and we're pretty clear about not requesting personal info, so going to close this.
