### ISSUE TITLE
Consider spam levels and determine if requests can be left open longer

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#463]
Have other anti-spam measures improved things such that the time before a request is made "authority_only" or "nobody" could be increased?

Re-opening requests is something which takes admin time. The aim with this suggestion is to reduce the number of requests for admin action. 

Closed requests often confuse public body staff. (The response they get is often misinterpreted as a bounce)

**Comment by garethrees** [comment]
We tweaked the timelines in https://github.com/mysociety/alaveteli/pull/4660 so that it stays as `authority_only` for longer. Closing as assumed fixed, but feel free to reopen if its still a big problem.
