### ISSUE TITLE
More links to subsections in help pages

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#464]
Some of the new sub-headings in the help pages don't have direct links; 

Specifically it would on occasion be useful to link directly to:

> Removal of public servants’ personal information from responses 

at

https://www.whatdotheyknow.com/help/privacy#your_rights

**Comment by HelenWDTK** [comment]
The specific instance mentioned here has already been fixed, so I'm going to close this in favour of #1140
