### ISSUE TITLE
Improvement to clarity of privacy page

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#469]
Currently
https://www.whatdotheyknow.com/help/privacy
begins
> WhatDoTheyKnow is run by the charity mySociety: [see more details here](https://www.whatdotheyknow.com/help/about#who). 

Proposal to improve clarity:

>WhatDoTheyKnow is run by [mySociety](https://www.mysociety.org/). 
>
>For full details of mySociety's structure, governance, and details of the relevant registrations with the Information Commissioner and The Charity Commission see: [Who makes WhatDoTheyKnow?](https://www.whatdotheyknow.com/help/about#who)

**Comment by RichardTaylor** [comment]
If edits to the privacy page are to be made maybe:
>General Data Protection Act

could become
>General Data Protection Regulations

I think that's just correcting a typo.

**Comment by Gemmamysoc** [comment]
Message from Mark C: To really clarify things, we should change first line of the [privacy page](https://www.whatdotheyknow.com/help/privacy) to: 'WhatDoTheyKnow is run by mySociety, a project of the charity UK Citizens Online Democracy.'
