### ISSUE TITLE
Extra time for schools to reply missing in some parts of the interface

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#477]
When a request to a body, including one tagged "school", is made the following text is shown:

>Currently waiting for a response from [school name], they must respond promptly and normally no later than [date twenty working days after request] ([details](https://www.whatdotheyknow.com/help/requesting#quickly_response)). 

In respect of a school the deadline may be up to 40 working days later, to account for school holidays, so despite the use of the word "normally", the statement may be misleading. 

This wording was carefully chosen, and the current functionally prevents anything incorrect being stated, however if might help our users if it became, in the case of bodies tagged "school":

>Currently waiting for a response from [school name], they must respond promptly and, in term time, normally no later than [date twenty working days after request] ([details](https://www.whatdotheyknow.com/help/requesting#quickly_response)). 

WhatDoTheyKnow already has special treatment for schools which are late, or very late, responding to requests; the addition of the ",in term time," text is taken from the approach taken in those circumstances.

**Comment by garethrees** [comment]
We say this in [overdue alerts](https://github.com/mysociety/whatdotheyknow-theme/blob/7ee6c4f88d4e015f24a357ed6894cad56e7d59ba/lib/views/request_mailer/overdue_alert.text.erb#L3-L6) and when making [followups](https://github.com/mysociety/whatdotheyknow-theme/blob/106735b5c4828be4922676a77ece59d5f988aad7/lib/views/followups/_followup.html.erb#L79-L84).

Are you asking for this text to be added when initially making a request?

Could you paste a screenshot of where you're expecting to see this?

**Comment by RichardTaylor** [comment]
Yes, I am suggesting considering saying something special about the deadline in respect of schools as soon a request is made to a school. 

An example of the current text is the bisque coloured box in the screenshot:

![screen shot 2018-07-11 at 16 41 16](https://user-images.githubusercontent.com/547695/42583641-4c17e00a-8529-11e8-8be3-29beafae1c7d.png)

**Comment by garethrees** [comment]
Got it, thanks! Sorry, wasn't sure where we are and aren't showing the message.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
