### ISSUE TITLE
Add, or improve, public notes on authorities

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#483]
Notes can assist users and improve internal and external search listings.  

We can describe what a body does, why it's subject to FOI/EIR (or if it's not why we list it anyway), and perhaps suggest the types of information it holds. We can also link to related bodies from the notes.

**Comment by MattK1234** [comment]
From #599:

Relating to Local Resilience forums - listed at https://www.whatdotheyknow.com/body?tag=local_resilience:

A future consideration would be improving the notes, at the moment they mostly have an address. We could explain more about what these organisations are, and what sort of things can be requested from them.

**Comment by MattK1234** [comment]
Whilst doing this we could also look at the links, making sure we have a home page link, as well as disclosure log and publication scheme if they have one.

Tags, for example ch:xxxxxxx where relevant could also be added.

**Comment by garethrees** [comment]
closing in favour of specific issues
