### ISSUE TITLE
Add impactful FOI requests to homepage

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/whatdotheyknow-theme#485]
We show plenty of information about how the site works and is active, but we don't talk about it's impact at all.

The homepage should show some examples of where requests have had great impact.

Content is available https://2017.mysociety.org/foi/ https://www.mysociety.org/50-news-stories-uncovered-by-whatdotheyknows-users/

**Comment by garethrees** [comment]
Closing as a duplicate of https://github.com/mysociety/alaveteli/issues/2812
