### ISSUE TITLE
Charity registration links in WDTK lead to out of date resources

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#486]
Charity organisations in both England/Wales and Scotland that have their metadata tags appropriately recorded are generating erroneous 'Charity Registration' links in the "More about this authority" panel. It would appear that the search URLs we use in both scenarios have expired at some point in the past, and are not being appropriately re-directed elsewhere.

### Example 1 - Scottish charity
Steps to reproduce:

1. Visit WDTK page for authority - https://www.whatdotheyknow.com/body/jobs_and_business_glasgow
2. Click 'Charity registration' link - 
http://www.oscr.org.uk/CharityIndexDetails.aspx?id=SC023930
3. Note 404 error

**Proposed fix:** Change search URL for Charity searches in Scotland to: https://www.oscr.org.uk/search/charity-details?number=_<CHARITYNUMBER>_#results (where <CHARITYNUMBER> is the charity reg number starting SC)

### Example 2 - English charity
Steps to reproduce:
1. Visit WDTK page for authority - https://www.whatdotheyknow.com/body/national_trust
2. Click 'Charity registration' link - 
http://www.charity-commission.gov.uk/SHOWCHARITY/RegisterOfCharities/CharityFramework.aspx?RegisteredCharityNumber=205846
3. Note that a generic page appears which is generic and has not carried out any search, meaning a duplicitous task is required.

**Proposed fix:** Change search url for Charity searches in England and Wales to: http://beta.charitycommission.gov.uk/charity-search/?q=_<CHARITYNUMBER>_ (where <CHARITYNUMBER> is the charity reg number)

**Comment by garethrees** [comment]
Thanks for an awesome bug report! 🙇

**Comment by lizconlan** [comment]
I've tweaked this slightly for the Charity Commission website to go to http://beta.charitycommission.gov.uk/charity-details/?regid=CHARITYNO&subid=0 instead so that it (should) go straight to the charity's main project page rather than a list of search results.

I imagine that this - and the URL - may change as it's intended as a public prototype.
