### ISSUE TITLE
"Hidden" incoming correspondence text is hitting bounding box

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#487]
Specific case of https://github.com/mysociety/alaveteli/issues/4018

Fixed for core in https://github.com/mysociety/alaveteli/pull/4735 but needs a fix for this theme too https://github.com/mysociety/alaveteli/pull/4735#pullrequestreview-138212713.

**Comment by zarino** [comment]
This was actually a bug in core. Here’s the fix: https://github.com/mysociety/alaveteli/pull/4753
