### ISSUE TITLE
Don't imply redaction time is a factor in considering right to erasure requests

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#489]
Where we say 

>Removing these details is time-consuming for our volunteers

at https://www.whatdotheyknow.com/help/privacy#erasure

we should make clear that the amount of time it takes volunteers to act on a removal request is not a factor when it comes to our consideration of what we can legally justify publishing following a right to erasure request. 

The section probably needs a re-write, perhaps including considering the headings, and linking to headings. See #464 on more links to subheadings in help pages.

**Comment by HelenWDTK** [comment]
Closing as complete
