### ISSUE TITLE
Remove asktheeu prompt from request page

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/whatdotheyknow-theme#490]
It doesn't need to be there on the request page. In the interest of removing some noise from this page we should ditch it.

**Comment by garethrees** [comment]
> It doesn't need to be there on the request page

This _does_ [generate traffic to AskTheEU](https://github.com/mysociety/alaveteli-experiments/blob/master/experiments/can-we-drive-traffic-from-wdtk-to-asktheeu.md) though, which is a goal of ours.

**Comment by garethrees** [comment]
I think its even better now compared to the [screenshot in the experiment writeup](https://cloud.githubusercontent.com/assets/739624/15118227/319e97ec-1603-11e6-9c11-56c3bcad423d.png), given that it appears below any action a user will take:

![screen shot 2018-07-31 at 11 57 44](https://user-images.githubusercontent.com/282788/43455802-fbf7ccee-94b8-11e8-8525-40d14a2281d3.png)

**Comment by garethrees** [comment]
I'm going to close this issue, as I don't think we should remove it, but we'd totally be open to other ideas around it.
