### ISSUE TITLE
New house rules to cover abuse of the site

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#493]
The current house rules:

https://www.whatdotheyknow.com/help/house_rules

don't explicitly forbid creating new accounts to evade a ban, or to evade a rate-limiting cap. 

Multiple accounts are sometimes legitimate eg. a whistleblower who already has an account wanting to make a request anonymously. 

We probably don't want to expand the rules to cover every possible eventuality, there's some benefit in keeping them concise and readable. Something to consider.

**Comment by RichardTaylor** [comment]
We've just had a user on WhatDoTheyKnow re-submit a request which administrators had hidden. 

A new rule, or rule, could cover this too; something like:

>Do not seek to evade the actions of site administrators by, for example, creating new accounts to evade a ban, or a rate-limiting cap, or by republishing material which you know has been removed by moderators.

**Comment by garethrees** [comment]
@RichardTaylor if you're happy with the above wording we can get this updated.

**Comment by garethrees** [comment]
I've made a PR with the above wording. We'll get this merged as-is unless we hear anything before Friday, but we can always change it later.

**Comment by RichardTaylor** [comment]
I'm happy with using the words I proposed.
