### ISSUE TITLE
add date by which an internal review should be completed

### ISSUE THREAD

**Issue by confirmordeny** [mysociety/whatdotheyknow-theme#5]
This is minor improvement I am suggesting re WhatDoTheyKnow that relates at least partly to the law/guidance on FOI in the UK.  Authorities should be completing internal reviews within twenty working days just as they should be responding to requests within twenty working days.

Waiting for a response message:
"Currently waiting for a response from Cardiff University, they must respond promptly and normally no later than 26 September 2011"
http://www.whatdotheyknow.com/request/cardiff_university_treatment_of

Waiting for a internal review message:
"Waiting for an internal review by Department of Health of their handling of this request. "
http://www.whatdotheyknow.com/request/total_amount_of_cfsme_sufferers

Suggest changing to:
"Waiting for an internal review by Department of Health of their handling of this request which should be completed no later than dd month 2011 "

see also: http://www.ico.gov.uk/for_organisations/freedom_of_information/~/media/documents/library/Freedom_of_Information/Detailed_specialist_guides/TIME_LIMITS_INTERNAL_REVIEWS.ashx

**Comment by HelenWDTK** [comment]
Closing in favour of https://github.com/mysociety/alaveteli/issues/5043
