### ISSUE TITLE
Broken link on advice page

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/whatdotheyknow-theme#506]
https://www.whatdotheyknow.com/help/officers#email_only

The link "Paragraph 107 of the Information Commissioner’s Guidance on recognising a request" is broken - looks like this content has now moved to https://ico.org.uk/media/for-organisations/documents/1164/recognising-a-request-made-under-the-foia.pdf (the link I generate when trying to point directly at the anchored paragraph is a bit odd so I'm not sure if it's viable to do that - see what you think).

**Comment by MyfanwyNixon** [comment]
https://ico.org.uk/media/for-organisations/documents/1164/recognising-a-request-made-under-the-foia.pdf#%5B%7B%22num%22%3A86%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C87%2C714%2C0%5D

I got this by right-clicking the menu item and selecting 'copy link location' - but if I paste that same link into a different browser, it doesn't take me to the anchor point.

**Comment by garethrees** [comment]
Yeah, I get taken to the first page. I'll just update the PDF URL. Thanks!
