### ISSUE TITLE
Create transifex project for whatdotheyknow-theme

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#514]
Theme overrides can't be translated without this.

Guidance at https://github.com/mysociety/alaveteli/wiki/Generate-theme-translations.

Prompted by https://github.com/mysociety/whatdotheyknow-theme/issues/510

**Comment by garethrees** [comment]
Had a quick look at this following the instructions but can't seem to generate the `.pot` source file:

```
$ dc run --rm app bin/rake gettext:find_theme THEME=whatdotheyknow-theme
[+] Running 1/0
 ⠿ Container alaveteli-db-1  Running                                                                                       0.0s
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - /alaveteli/lib/themes/whatdotheyknow-theme/locale-theme/app.pot
po_parser.ry:317:in `detect_file_encoding'
po_parser.ry:308:in `parse_file'
/bundle/vendor/ruby/2.7.0/gems/gettext-3.4.3/lib/gettext/tools/msgmerge.rb:56:in `run'
/bundle/vendor/ruby/2.7.0/gems/gettext-3.4.3/lib/gettext/tools/msgmerge.rb:38:in `run'
/alaveteli/lib/tasks/gettext.rake:8:in `msgmerge'
/alaveteli/lib/tasks/gettext.rake:48:in `xgettext'
/alaveteli/lib/tasks/gettext.rake:57:in `find'
/alaveteli/lib/tasks/gettext.rake:78:in `block (2 levels) in <top (required)>'
Tasks: TOP => gettext:find_theme
(See full trace by running task with --trace)
```

IDK if something has changed such that `find_theme` used to find or create the source file and now doesn't. Probably need to figure out the underlying command to generate it.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
