### ISSUE TITLE
Incorporate permanent adverts seeking volunteers into the site

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#516]
This could be an advert in the header with a link to a new help page on volunteering which could include some of the text from recent blog posts seeking volunteers.  

Related: https://github.com/mysociety/alaveteli/issues/1198 

@MyfanwyNixon

**Comment by garethrees** [comment]
Duplicate of https://github.com/mysociety/whatdotheyknow-theme/issues/7
