### ISSUE TITLE
Improve efforts to seek donations - both on the website site and in emails

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#519]
With ideas from:

https://foundation.wikimedia.org/wiki/2016-2017_Fundraising_Report#Online_Fundraising_Banners

aiming to raise funds to help with maintenance, administration and development of the site. 

Building on experience from https://github.com/mysociety/whatdotheyknow-theme/issues/284 and https://github.com/mysociety/alaveteli-experiments/issues/98

**Comment by garethrees** [comment]
Saw a nice little example of this on [the Bristol Cable](https://thebristolcable.org/)

![img_7335](https://user-images.githubusercontent.com/282788/47004170-dce9b180-d128-11e8-8fd1-413a66af6c07.JPG)

Also:

"SAME PRICE AS NETFLIX, BUT FOR A STRONGER DEMOCRACY" – https://www.citybureau.org/press-club/

**Comment by MyfanwyNixon** [comment]
On Krita:
![screenshot_2018-08-25 post-download page krita](https://user-images.githubusercontent.com/944656/47005637-140d9200-d12c-11e8-9946-763896350eab.png)

**Comment by garethrees** [comment]
I think the first step here is adding `/help/donate` with the contents of https://www.mysociety.org/2018/10/19/ensuring-whatdotheyknow-is-around-for-the-next-half-a-million-requests/ on it, so that we have somewhere to link to?

**Comment by garethrees** [comment]
Requires https://github.com/mysociety/whatdotheyknow-theme/issues/7.

We currently have `/help/volunteers` which encompasses donation (of money, and time) so maybe this is a good place to go to for now.

We should add a "Help WDTK" footer to all outgoing mail to users.

**Comment by garethrees** [comment]
I think the next step here, after merging https://github.com/mysociety/alaveteli/pull/4936 and https://github.com/mysociety/whatdotheyknow-theme/pull/532 is to do https://github.com/mysociety/whatdotheyknow-theme/issues/542.

**Comment by garethrees** [comment]
Closing in favour of https://github.com/mysociety/whatdotheyknow-theme/issues/542.
