### ISSUE TITLE
Contact us page needs option for 'I want to volunteer'

### ISSUE THREAD

**Issue by ajparsons** [mysociety/whatdotheyknow-theme#524]
We send people interested in volunteering to the contact page, but this doesn't really have a good option to filter those people through. 

This is the closest and requires a weird tickbox:

![image](https://user-images.githubusercontent.com/8157058/47284061-c1c1ea80-d5dd-11e8-9163-14d3f899ac0e.png)

Suggest adding another option *explicitly* about volunteering.

**Comment by garethrees** [comment]
Linking to https://github.com/mysociety/whatdotheyknow-theme/issues/7

**Comment by sallytay** [comment]
Closed as resolved by https://github.com/mysociety/whatdotheyknow-theme/issues/1179
