### ISSUE TITLE
Volunteer messaging

### ISSUE THREAD

**Issue by ajparsons** [mysociety/whatdotheyknow-theme#533]
(This is a few notes ahead of the team meeting to try and flesh out what I think a problem is, and people can either expand or knock back)

Key points:

- We have to tell people how to help us
- We have to give people multiple options on how to help us
- We should make it easy to help us

This is coming off the recent blog posts - my feeling is we're not really set up to deal with anyone other than 'super committed' - we need processes that filter people who want to help us into either alternative actions, or into a pool of 'interested persons' where we can try and escalate their involvement later. 

Our public messaging is not always clear what we want people to do. The volunteer blog post nicely describe the problem, but then sends people to contact forms without a clear volunteer option (and a primary design consideration of these forms is to encourage people *not* to contact us - but #524 is directly about this). Democracy Club just puts a google form up when recruiting - this would be a good immediate action even if we were just gathering people's emails to follow up later. 

Lots of people can’t volunteer (lack of specific skills or time), the obvious thing they can do is give money - but in neither of the WDTK posts do we ask people do that. I think the admin role seems in the right kind of ball park for a crowd-funder (which is a separate issue) - but our current messaging around that is confusing! Between the two posts we say "here is a role that we're hoping an institutional funder will pay for - but in the meantime can someone do it for free?" - and so I come away a bit confused as to what you want me, an interested person, to do. I feel, unless I know someone with a big cheque book, you just want me to be patient and it'll sort itself out. But is that really what we want people to do?

This thread: https://twitter.com/WhatDoTheyKnow/status/1054415493354999808 is good at making the behind the scenes work of volunteers visible but what is it asking? It makes the work of volunteers seem important (which is it!) but frankly it also sounds like hard work. This seems like it’s probably true and so is a problem we need fixing! But how can I as someone reading this thread help these important volunteers out and support the site I like? Currently this means going from the thread to the blog post to a contact form (which, as covered, isn't really aimed at volunteers). The thread feels more like a 'this is hard, give us money to make it easier' than a 'this is rewarding and good work, please join us' thread - which would emphasise either the positive aspects, or that you're planning to spread the work over a much wider pool. 

Threads like this are good because they are straight in the feed of an interested audience (I think generally we don't do enough threads). But need to be linked to a clear ask and there's no need to treat the blog post as the path to that - useful bits can be lifted out as screenshots and then directly link to a call to action. 

My feeling is the structure of both blog posts and threads should look more like this:

- Problem we're trying to solve. 
- The several ways you can help - filtering off at different levels of activity:
    - Give us money to support our activities - unstructured, volunteers work hard, buy then a drink! 
     - Give us money to support our activities - structured, please give money to meet this specific goal and share this kickstarter.
     - Please fill out this google form and tell us how much time you can give (evening a month, evening a week, etc), do you have legal skills? etc
     - Want to make a serious commitment of time - email us! (this isn't really meant to catch anyone, but makes the other level seem like it's not the top of the pyramid). 

There's a session at the team meeting about this but any thoughts people have are good so we go into that with a better sense of considerations I haven't picked up on.

**Comment by MyfanwyNixon** [comment]
These are all excellent points, thanks for taking the time to think it through. 
The two blog posts will be given extra amplification next week since they're in the FOI newsletter. For now I can (and should have) add the 'donate' module to the foot of each post.

Small point about why we don't do many Twitter threads: it's probably because of using Hootsuite, where the auto-scheduling (which purportedly puts your tweet in front of the maximum number of people) is always beguiling, but doesn't allow for threading.

**Comment by garethrees** [comment]
Just noting https://github.com/mysociety/whatdotheyknow-theme/pull/530, which adds clearer links to the volunteer-specific help page.

**Comment by ajparsons** [comment]
Follow up notes from team meeting:

This is generally a area of interlocking capacity problems.  While the key idea that we could increase capacity via a wider pool of people who do less has value, there are several issues:

- Website is not set up to facilitate this work - would require development work for unknown future pool of volunteers (chicken egg problem, can't invest to make it easier with this pool, can't recruit until we have something they can do). 
- Doesn't relieve much responsibility from core volunteers - is more likely to do work that is worth doing, but currently not being done. 

Recruitment efforts has a number of people in the pipeline, but hasn't landed anyone yet. Developers are working on changes to site to ease load. The success of these seems the quickest route to solving core problem - if either fails or is significantly delayed the above should be revisited.

**Comment by HelenWDTK** [comment]
We have the volunteer help page now, and a specific volunteer contact form. Closing as complete
