### ISSUE TITLE
Identify requests which have been appealed to the ICO or Tribunal 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#537]
This is something volunteer administrators could do, to help highlight requests of interest. 

Requests can be tagged, see:

https://github.com/mysociety/alaveteli/issues/2302

Many requests in respect of which there is an ICO or Tribunal decision may be newsworthy and worth blogging about.

**Comment by HelenWDTK** [comment]
I think that this is a task that volunteers do from time to time at the moment, but it is extremely difficult to do in an automated manner/at scale. ICO decision notices very rarely mention WhatDoTheyKnow, and they are issuing a large number at the moment as a consequence of the work that they are doing to clear the backlog. This would be definitely worth revisiting once #17 and/or #420 have been implemented, which may unlock the possibility of automating this process.
