### ISSUE TITLE
A/B tests on donate page

### ISSUE THREAD

**Issue by ajparsons** [mysociety/whatdotheyknow-theme#542]
Following on from [donation analysis](https://blogs.mysociety.org/internal/2018/11/23/donation-analysis/)  - this is the key ticket.

Basically we want to be able to run A/B tests on the location and content of the donate link on the WDTK requests page. @zarino says this is actually super easy and customisable through google analytics - so this is a ticket to a) ask someone to do this b) draw out any additional problems/info needed.

**Comment by zarino** [comment]
Here’s an example of the JavaScript involved with a recent A/B test we did on the People’s Assembly homepage: https://github.com/mysociety/pombola/pull/2269/files

It pretty much boils down to:

```
window.cxVariation = cxApi.chooseVariation();
if(window.cxVariation === 1){
    // Change content on page
}
```

Then you set up your success criteria in the Content Experiment section of Google Analytics, and you’re away.

**Comment by ajparsons** [comment]
For reference, I have created issue stubs for the first three experiments in the alaveteli-experiments repo

https://github.com/mysociety/alaveteli-experiments/issues/115
https://github.com/mysociety/alaveteli-experiments/issues/116
https://github.com/mysociety/alaveteli-experiments/issues/117

**Comment by wrightmartin** [comment]
Can we add one to this for changing the design? I think the red box design is a big miss here - I'd guess it gets mistaken for an error message? I assume in the spirit of this ticket we would A/B test a design change?

**Comment by wrightmartin** [comment]
Quick redesign of what the donate call _could_ look like

![desktop hd](https://user-images.githubusercontent.com/2292925/50159346-5e4af500-02ce-11e9-960b-85fddda6c4d6.png)

**Comment by zarino** [comment]
@wrightmartin Is there a danger of it starting to look too much like a sidebar advert? The sort of thing we’ve all been trained to ignore ;-)

**Comment by wrightmartin** [comment]
> @wrightmartin Is there a danger of it starting to look too much like a sidebar advert? The sort of thing we’ve all been trained to ignore ;-)

Yep - but it's okay, because we're testing that too https://github.com/mysociety/alaveteli-experiments/issues/115

**Comment by garethrees** [comment]
So far:

> * https://github.com/mysociety/alaveteli-experiments/issues/115 – varying placement of banner

This made an improvement so we've made it permanent

> * https://github.com/mysociety/alaveteli-experiments/issues/116 – varying text of banner

`Donate £n Now` vs `Donate Now` doesn't seem to make much difference

So the next thing to test is:

> * https://github.com/mysociety/alaveteli-experiments/issues/117 – varying buttons on banner

**Comment by garethrees** [comment]
[psyche.co](https://psyche.co) have quite a nice prominent banner. I like the user testimonial. I wonder if we could collect a bunch of these from Twitter?

<img width="1600" alt="Screenshot 2022-03-21 at 09 06 35" src="https://user-images.githubusercontent.com/282788/159231771-2cd55b82-a481-41b2-a9d1-06c9d943d5ca.png">

<img width="499" alt="Screenshot 2022-03-21 at 09 08 51" src="https://user-images.githubusercontent.com/282788/159231858-14dbb868-7fc9-4e1d-8087-931f123d3bf2.png">

Their parent site [aeon.co](https://aeon.co) has similar. I love that they're clear about their mission, and I can see why that creates a resonance with potential donors.

<img width="1443" alt="Screenshot 2022-03-19 at 10 35 29" src="https://user-images.githubusercontent.com/282788/159232054-af72e352-812b-4d2d-8151-55cf7917d986.png">

We should [integrate better wording](https://github.com/mysociety/alaveteli-experiments/issues/116#issuecomment-551003140) into our banners.

**Comment by HelenWDTK** [comment]
@ajparsons (or anyone else), has this been completed now to the extent this issue can be closed?

**Comment by ajparsons** [comment]
I mean we're not doing it, probably not going to do it soon, if we do we can reopen this.
