### ISSUE TITLE
Suggest people request multiple bodies be added, use a spreadsheet

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/whatdotheyknow-theme#543]
We semi-regularly have people submit lots of "add new bodies" requests via the form at https://www.whatdotheyknow.com/change_request/new . For example, somebody requested recently a slew of County Down primary schools be added.

This is sub-optimal for them, cos they have to fill the same form out multiple times, and also sub-optimal for us, cos it would be much more efficient to do a spreadsheet bulk upload.

So whenever we have somebody request multiple like this, we generally contact them to thank them and to ask them if they do similar in the future to not use the form but to email team@ with a spreadsheet of bodies with three columns - name, request email, information source.

That's a bit stable door after the horse has bolted, though. So I'm thinking it would be good to have text on either the form, or on the help section at https://www.whatdotheyknow.com/help/requesting#missing_body , EITHER saying much of the above "if requesting a few bodies please send us a spreadsheet..." OR saying "if you're requesting a few at once please contact us so we can say the best mutual way to do this" or something.

Would lessen admin workload (I can't remember how to flag that)

**Comment by mdeuk** [comment]
> That's a bit stable door after the horse has bolted, though. So I'm thinking it would be good to have text on either the form, or on the help section at https://www.whatdotheyknow.com/help/requesting#missing_body , EITHER saying much of the above "if requesting a few bodies please send us a spreadsheet..." OR saying "if you're requesting a few at once please contact us so we can say the best mutual way to do this" or something.
> 

Below the form itself we say "Please contact us. When adding lots of authorities its often easier for us to deal with a spreadsheet or CSV." - would it perhaps help to move this text so that it is more prominent on the page?

> Would lessen admin workload (I can't remember how to flag that)

I haven't a clue how to (maybe I don't have rights!)

**Comment by wrightmartin** [comment]
## Option 1

Quick redesign of the existing form to make it clearer for people who want to give us multiple authorities

![desktop hd](https://user-images.githubusercontent.com/2292925/50632130-c3dde900-0f3e-11e9-8ea2-1382d1edfae5.png)


## Option 2
 
Concept of an enhanced process whereby users can upload their own CSV etc files

![desktop hd copy 2](https://user-images.githubusercontent.com/2292925/50632127-c3dde900-0f3e-11e9-807a-1a9dd0922f33.png)
![desktop hd copy](https://user-images.githubusercontent.com/2292925/50632128-c3dde900-0f3e-11e9-8899-91306dafa76e.png)

**Comment by mdeuk** [comment]
> ## Option 2
> Concept of an enhanced process whereby users can upload their own CSV etc files
> 
> ![desktop hd copy 2](https://user-images.githubusercontent.com/2292925/50632127-c3dde900-0f3e-11e9-807a-1a9dd0922f33.png)
> ![desktop hd copy](https://user-images.githubusercontent.com/2292925/50632128-c3dde900-0f3e-11e9-8899-91306dafa76e.png)

This option looks like it'd fit the bill perfectly. Ideally we should provide a sample CSV file to demonstrate the correct format, but, from a UX perspective this is excellent.

A question that comes to mind is, should we continue to ask for the source URL on the webpage itself; or, is this a field that we can include in the CSV? I don't think this will necessarily be a problem either way, but, it may be neater in cases where there are multiple authorities being added where the source is different. Perhaps that's a bit of an edge case.

**Comment by garethrees** [comment]
Closing as this isn't a very frequent thing, and we have the lo-fi "contact us" for lots of bodies / when you have a spreadsheet.
