### ISSUE TITLE
Users concerned they've been sent the survey link too soon

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#544]
This relates to the survey sent with the subject:

>Can you help us improve WhatDoTheyKnow

Users regularly respond by email to the support team to say ~"but I've not had a response yet"; I think the survey is suited to / intended for users who've not had a response however it does appear to confuse some users to ask them about their experience of the site before they've had a response. 

The solution might be some additional text on the survey.

**Comment by RichardTaylor** [comment]
+1 today from WDTK user support mail. 

Reply by email to the survey link:
>with ref your e.mail I am still awaiting a reply to my FOI

**Comment by MattK1234** [comment]
Further +1 on this. Another email was received in the support mailbox earlier today stating they hadn't received a response to their request yet.

> HowDoIKnow? They havent provided the info yet...

**Comment by RichardTaylor** [comment]
I think enough users are confused by this that action should be taken.

**Comment by mdeuk** [comment]
Further +1 here; a user has emailed in this morning, having received the survey yesterday. The public body in question was yet to send a substantive reply; therefore, this has caused some confusion.

I can see there is a survey question which covers this circumstance, however, it doesn't seem to be clear from the introduction that we're looking for feedback regardless of whether a reply has been received or not. Perhaps this could simply be covered off with some more text in the automated email itself.

The waffle I used may be stretching things a little… 😊

> The survey that you have received is something that we send to newer
> users of WhatDoTheyKnow to allow our development colleagues to better
> understand how our users utilise the service. This allows for research
> to be carried out, and, for new features to be prioritised based on
> the information we receive back.
> 
> There's no obligation to complete the survey; however, if you are able
> to do so, we'd be very happy to receive your reply.

**Comment by MattK1234** [comment]
Another user contacted the WDTK support team yesterday regarding this.

> I haven’t had a response yet?

I propose adding another paragraph to the automated email, maybe below "Whether or not...":

Please note that the survey can be completed even if you have not yet received a response to your request.

**Comment by RichardTaylor** [comment]
User correspondence today: 

>I can't do survey YET! I've not had my request answered yet.

I see there is action over at #580 on reviewing the survey.

**Comment by RichardTaylor** [comment]
+1 another WDTK user has written saying they can't complete the survey until they've had a response.

**Comment by RichardTaylor** [comment]
+1 a WhatDoTheyKnow.com user who has made requests but not yet had responses writes:

> it is much too early to ask me how to improve your service. Please come back to me in early APRIL and I will help you, I promise.

**Comment by RichardTaylor** [comment]
+1 This is still happening

**Comment by gbp** [comment]
Survey is currently being reworked as part of #580. Will try take a look at this too
