### ISSUE TITLE
Better vertical alignment for length warning text

### ISSUE THREAD

**Issue by zarino** [mysociety/whatdotheyknow-theme#546]
Once https://github.com/mysociety/alaveteli/pull/4987 is merged, this will need to be added to the WDTK styles, to vertically align the length message beside the Preview button:

```
.message-text-length {
  margin: 0.4em 0 0 0;
}
```

Possibly only at non-mobile widths?

**Comment by garethrees** [comment]
Very minor, but the issue as described is still an issue:

![Screenshot 2023-06-21 at 09 16 53](https://github.com/mysociety/whatdotheyknow-theme/assets/282788/9b3031d9-7cff-43b2-ade6-ef7cfd844f11)

**Comment by garethrees** [comment]
Fixed in https://github.com/mysociety/whatdotheyknow-theme/commit/7701093298dc25feb53d82cd40ca756b3d56ea67
