### ISSUE TITLE
Use ICO Register of Data Controllers to identify bodies to list on WhatDoTheyKnow 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#547]
The ICO register of data controllers contains a field in which controllers are asked if they're subject to FOI. 

We could use this to identify organisations subject to FOI which we don't list on WhatDoTheyKnow

https://ico.org.uk/about-the-ico/what-we-do/register-of-fee-payers/

**Comment by mdeuk** [comment]
Unfortunately, the register isn't actually available for download (and hasn't been for some time!) - the resulting error is always the same:

>  "The register of fee payers is currently unavailable to download. We apologise for any inconvenience."

I have made a FOI request for a copy of the dataset.

**Comment by MattK1234** [comment]
Just to note that I've tested the download again today and it is still not working.

**Comment by MattK1234** [comment]
The ICO register of data controllers is now available (and working!) at https://ico.org.uk/about-the-ico/what-we-do/register-of-fee-payers/download-the-register/

**Comment by mdeuk** [comment]
> The ICO register of data controllers is now available (and working!) at https://ico.org.uk/about-the-ico/what-we-do/register-of-fee-payers/download-the-register/

Indeed, all 738,771 rows of it!

I downloaded it last night - filtering against columns J 'Public_authority' and T 'DPO_or_Person_responsible_for_DP_Email' brings us some 10,234 entries… however, I would exercise some caution as the data does appear to be riddled with errors.

For example:
- on row 381,761 we have a listing for "The Ship Inn Saltburn Ltd" ([ZA420723](https://ico.org.uk/ESDWebPages/Entry/ZA420723)
- on row 391,897 we have a listing for "Elite Taxis Ltd" ([ZA435348](https://ico.org.uk/ESDWebPages/Entry/ZA435348))
- on row 663,210 we have a listing for "Chef Perfect Pizza Ltd" ([ZA655736](https://ico.org.uk/ESDWebPages/Entry/ZA655736))

… none of those companies are public bodies based on data from Companies House; however, the ICO database states `"This data controller states that it is a public authority under the Freedom of Information Act 2000 or a Scottish public authority under the Freedom of Information (Scotland) Act 2002"`

There does seem to be a useful volume of data here in general, but, we'll need to be acutely conscious of the fact that the dataset seems contain more than a few errors. Which is a shame.

**Comment by confirmordeny** [comment]
Now listed here: https://wdtkwiki.mysociety.org/wiki/Authority_suggestions
