### ISSUE TITLE
Xmas donate banner – 14th December - 6th January

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/whatdotheyknow-theme#548]
As per last year https://github.com/mysociety/whatdotheyknow-theme/issues/284
Please can we have this banner running from 14 December until 6 January?

**Comment by garethrees** [comment]
Done. Moving to awaiting deploy to remind us to remove it after Christmas.

**Comment by MyfanwyNixon** [comment]
Apologies, after chats with MarkC and AlexP, could we amend it to:

**Text**
If we've helped you hold authorities to account this year, could you help us do more in 2019?
**Link** 
https://www.mysociety.org/donate/?utm_source=whatdotheyknow.com&utm_medium=banner&utm_campaign=december_2018&utm_content=banner+hold+auth+source+data+learn

**Comment by garethrees** [comment]
Updated

**Comment by MyfanwyNixon** [comment]
Thank you!
