### ISSUE TITLE
Update info on internal reviews on Help pages to include Alex Parsons' research finding

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/whatdotheyknow-theme#552]
From Alex's research:

“Around half of internal reviews in local government change the outcome.” - very encouraging for requesters who ask for an internal review. Would be nice to update Help pages to include this to encourage ppl to ask for internal reviews if they don’t get satisfactory responses.

**Comment by garethrees** [comment]
Source: https://blogs.mysociety.org/internal/2018/12/12/update-on-foi-research

**Comment by MattK1234** [comment]
Superseded by #631
