### ISSUE TITLE
Expand section on retaining support emails on Help pages

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/whatdotheyknow-theme#553]
On the back of a user complaining that their personal info will be held in our user support mailbox for two years, can/should we expand this section https://www.whatdotheyknow.com/help/privacy#retention_support to include our legal basis for retaining personal information in email threads for 2 years in the support box? I know there is a section on our legal basis for processing underneath, but it doesn't really explain why we retain support emails.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
