### ISSUE TITLE
Add 'immigration correspondence' hide option to other bodies

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#555]
Please add the 'immigration correspondence' hide/notify option (setup on #535) to the following organisations:

- HM Passport Office (body 590)
- Chief Inspector of Borders and Immigration (body 8222)

These organisations ultimately deal with immigration related matters in some sense, and, therefore, they are occasionally being sent requests which we would ordinarily hide using this option if they had been sent to the Home Office.

Having a consistent option that we can use will hopefully allow us to get a better sense of how many requests we are dealing with in the future, and, ultimately make administration a bit simpler.

Thanks 😃

**Comment by garethrees** [comment]
For each of those authorities, we need to know:

* What the label next to the radio button should be
* What the pre-filled message should be
* What state the request should get put in to once submitted (presumably `not_foi`?)

**Comment by MattK1234** [comment]
I'd also suggest adding such to:

- Office of the Biometrics Commissioner - 54784

**Comment by sallytay** [comment]
This was noted again today in relation to the Passport Office, where we do receive a number of requests from users seeking information on the status of their personal passports.

Information below:

>What the label next to the radio button should be
	Personal passport correspondence
>What the pre-filled message should be
	Proposed:https://docs.google.com/document/d/16BDWkh82kq8ZK83tCuUuk3FHqwTw6-T0ZU0KrX7378s/edit
>What state the request should get put in to once submitted (presumably not_foi?)
	not_foi

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
