### ISSUE TITLE
Broken links on 'Find an authority' page

### ISSUE THREAD

**Issue by gbp** [mysociety/whatdotheyknow-theme#558]
https://github.com/mysociety/whatdotheyknow-theme/blob/master/lib/views/request/_select_authority_help.html.erb#L4-L5

- [x] Fix links 
- [x] Localise strings

**Comment by lizconlan** [comment]
Presumably these should go to `help_requesting` and `help_beginners` respectively

**Comment by garethrees** [comment]
Oops sorry looks like I completely missed that in https://github.com/mysociety/whatdotheyknow-theme/pull/545
