### ISSUE TITLE
Users who are suspended should not be sent site surveys

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#564]
There exists an unusual scenario where a user can create an account, make a request, and, then, be banned in short order.

If a user's account is banned prior to the survey being triggered (e.g. before two…ish weeks) it would perhaps be preferable if we did not send the "Can you help us improve WhatDoTheyKnow?" email, which is perhaps likely to receive a less favourable response than might be anticipated 🙂

Relates to #544

**Comment by garethrees** [comment]
Oops!

I think that should be a fairly simple change to https://github.com/mysociety/whatdotheyknow-theme/blob/master/lib/model_patches.rb#L138

```diff
- next if info_request.user.survey.already_done? || sent_to.include?(info_request.user_id)
+ next if info_request.user.survey.already_done? || sent_to.include?(info_request.user_id) || !info_request.user.active?
```

Would be nice to abstract this out in to `User#send_survey?` or similar.

**Comment by garethrees** [comment]
Related to https://github.com/mysociety/alaveteli/issues/5090
