### ISSUE TITLE
Files server has indexing turned off which makes info in some requests unavailable

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/whatdotheyknow-theme#565]
When admins manually upload more than one file submitted to us as FOI responses, we've generally relied on the directory index feature to list the files. Indexing has been turned off and it has made multiple FOI responses unavailable.
An example:
https://www.whatdotheyknow.com/request/mandatory_work_activity_communit_2#comment-29640

> "I received the CD and have uploaded the contents here: http://files.whatdotheyknow.com/request/mandatory_work_activity_communit_2/release-20120725/
> 
> The letter is postmarked 25/07/2012, and consisted of a jiffy bag, a CD and jewel case and cost £1.10 to post.
> 
> Ganesh - WhatDoTheyKnow volunteer"

That link http://files.whatdotheyknow.com/request/mandatory_work_activity_communit_2/release-20120725/ no longer works

**Comment by garethrees** [comment]
@sagepe we mentioned here that we could see if we can enable directory browsing except for at the top level. Could you have a look to see if that's possible?

**Comment by sagepe** [comment]
I've made a change that enables directory browsing for folders under `/request/`, so the links above should now work as expected.

**Comment by garethrees** [comment]
Amazing, thanks!
