### ISSUE TITLE
HTTPS on the Files server results in error

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/whatdotheyknow-theme#566]
hi

![image](https://user-images.githubusercontent.com/11923618/55810642-d63c6580-5adf-11e9-9246-f586657c1bc4.png)

That's https://files.whatdotheyknow.com/request/pre_application_advice_1700985pr/8985_Reissue_26.03.2019.zip

I have to use http://files.whatdotheyknow.com/request/pre_application_advice_1700985pr/8985_Reissue_26.03.2019.zip

The rest of WhatDoTheyKnow is SSL only. I know that FOI responses shouldn't include personal data etc. and this isn't login data etc. but still would suggest that the files server SSL should work, and also that all requests to non-encrypted HTTP should be redirected to SSL

**Comment by garethrees** [comment]
Closing as a duplicate of https://github.com/mysociety/whatdotheyknow-theme/issues/349.

**Comment by garethrees** [comment]
This has been fixed

**Comment by kingqueen3065** [comment]
thank you very much @garethrees
