### ISSUE TITLE
Clarify generic boilerplate on request email messages to public bodies

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#574]
At the moment when a request is generated on WDTK we include wording in the footer to the effect of:

> Please use this email address for all replies to this request:
> request-xxx-yyy@whatdotheyknow.com

A number of public bodies, particularly those using CRM systems, do not always appear to interpret this as being an absolute requirement; meaning that where a requestor has made several requests to the same public body [1] there is the potential  of confusion as correspondence is being directed to the wrong request on WDTK.

This is an occasional support topic in the WDTK support mailbox, however, it has been drawn to light again by a recent decision notice issued by the Scottish Information Commissioner ([089/2019](http://www.itspublicknowledge.info/ApplicationsandDecisions/Decisions/2019/201900396.aspx)), who now helpfully notes on their [website](http://www.itspublicknowledge.info/home/News/Decisionroundups/DecisionsRoundUp08to14June2019.aspx):

> **Responding to 'What Do They Know' requests**
Whatdotheyknow.com is an online platform through which people can make FOI requests to public bodies across the UK. This week we considered an unusual case where a response was sent to the wrong What Do They Know email address. Despite the response being available online, we concluded that the Council's response did not reach the requester within the FOI timescales. Authorities need to ensure that they use the contact details provided for each request, even where there may be multiple requests from the same requester.

We should consider whether or not the wording within the boilerplate can be strengthened to make this key point more obvious to FOI officers.

[1] or public bodies who share the same system, e.g. Councils and HSCPs who may share resources.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
