### ISSUE TITLE
Users should not be sent a site survey if their request is hidden by an administrator

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#575]
** This is somewhat similar to the issue in #564 and relates to #544 **

WDTK administrators have recently encountered a scenario whereby a user whose request has been hidden as not_foi shortly after had been submitted is still receiving the site survey email several weeks later, leading to a rather rude response being received back from the user.

Is it possible for Alaveteli to suppress generation of the site survey when the user's only request has been removed from public view? 

Example request: https://www.whatdotheyknow.com/admin/requests/583374 (submitted 15/6/19 21:26, hidden as not_foi 16/6/19 10:12, survey sent 30/6/19 8:41)

**Comment by garethrees** [comment]
Like in https://github.com/mysociety/whatdotheyknow-theme/issues/564#issuecomment-479807446, I think we could add `InfoRequest#can_send_survey?` to the model patches and then do something like

```diff
- next if !info_request.user.can_send_survey? || sent_to.include?(info_request.user_id)
+ next if !info_request.can_send_survey? || !info_request.user.can_send_survey? || sent_to.include?(info_request.user_id)
```

I think we could make `InfoRequest#can_send_survey?` something like:

```ruby
def can_send_survey?
  visible?
end
```
