### ISSUE TITLE
Update the credits with new volunteers etc.

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#578]
Under the volunteers heading
https://www.whatdotheyknow.com/help/credits#volunteers

Add [Matt Knight](https://www.whatdotheyknow.com/user/matt_knight) and [Martyn Dewar](https://www.whatdotheyknow.com/user/martyn_dewar) retaining the alphabetical order by surname in the list. 

Delete CF

Consider adding:
>The provision of the service is also supported by our volunteer [non-executive directors and trustees](https://www.mysociety.org/about/board/). 

Under the "Thanks are also due" heading consider adding a statement about the role of mySociety staff, not all of whom come under the credit for contributors to the code. Maybe make the second sentence:

>Many of [mySociety's staff](https://www.mysociety.org/about/team/), past and present, have contributed to the site's success. 

that does seam a little terse given the amount of work and effort it refers to!

**Comment by garethrees** [comment]
Just noting I've got a PR for this, but missed the surname-alphabetical order https://github.com/mysociety/whatdotheyknow-theme/pull/577
