### ISSUE TITLE
Review the automated user survey

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#580]
The survey sent with the subject "Can you help us improve WhatDoTheyKnow?" should be reviewed and consideration should given to improving it or stopping it. 

Results from the survey should be shared with developers, volunteers and publicly as appropriate. 
 
See also: #351 and #544

cc @ajparsons

**Comment by ajparsons** [comment]
Related ticket suggests I dropped the ball here - will add back into the list to look at but in the meantime if we're not getting value from the survey I'd lean towards stopping it regardless.

**Comment by RichardTaylor** [comment]
Thanks @ajparsons 

I'd like to see a consideration of the balance between the impact of annoying our users / making a demand on our users vs the benefits.

**Comment by MattK1234** [comment]
I had a look at the survey a couple of days ago. It includes questions like "Did you get a response from the Authority you have contacted?"

I'd assume if we wanted this sort of data we would look at the request statuses, which would show us info on existing users as well as new, if we wanted it to.

It doesn't display very well on a mobile either, you'd have to scroll left to right to read the questions and answers etc, rather than the answers being below the questions.

**Comment by ajparsons** [comment]
To update this ticket, I'm currently doing an analysis of the old results and will then recommend how to replace it.

**Comment by MattK1234** [comment]
There are a lot of good notes relating to this survey and possible alternatives at https://docs.google.com/document/d/1NjHeUbyZyVgRKmD0p9koie4RjLZnGd0j-zRMtG4duBw/edit#heading=h.stg9htu3282c

**Comment by ajparsons** [comment]
Thanks for the prod, I've added it to my backlog tracker. Would be good to transition before the end of the year.

**Comment by ajparsons** [comment]
Have shared plan and draft for feedback with staff and volunteers. Ideally would like to get sign-off and run for the last few months of the year to check for issues, and then be running a happy version for the start of 2021.

**Comment by ajparsons** [comment]
@garethrees : are the changes needed for this scheduled?

**Comment by garethrees** [comment]
> @garethrees : are the changes needed for this scheduled?

They are not – sorry, I didn't know we were ready to go on this. Will schedule for next sprint.

Linking to the [doc where we outlined the changes needed](https://docs.google.com/document/d/1kkObSkZXNgg_3bYnChVmEJ2yZXnFJA0AEm7Dxz_aC84/edit#) so that I can remember what to do when it comes to it.

**Comment by RichardTaylor** [comment]
Noting WhatDoTheyKnow user correspondence in reply to the survey today:

>please remove from mail list

The survey annoying users is one of the concerns raised above.

**Comment by ajparsons** [comment]
Where does this fit in the current priorities?

**Comment by garethrees** [comment]
End of March – mid April. We're slammed. Sorry 😔

**Comment by ajparsons** [comment]
Going to re-open this ticket until we've the final version of the new survey is live for my purposes (but yay!)

**Comment by ajparsons** [comment]
Update on this, I'm currently waiting on Alchemer to get back to me with a second technical fix to the survey. Will then give final version on URl.

**Comment by ajparsons** [comment]
Given up on the thing I was trying to do (not strictly needed)

@gbp: The survey URL is https://survey.alchemer.com/s3/5715101/WhatDoTheyKnow-user-survey?authority_id=XXX

**Comment by gbp** [comment]
This is now live and cronjob running daliy as expected
