### ISSUE TITLE
Include links to Companies House and ICO (DPR) registrations within public bodies

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#581]
Similar to #486, we should include links, where appropriate, to Companies House and the ICO's data protection register.

We already tag relevant information within bodies using the tags 'ch' and 'dpr'; therefore, it may be possible to simply expand on the code within #491.

**Comment by MattK1234** [comment]
Another potential link we could add would be for the NHS Choices website. 

A search for the tag 'NHSChoicesID' (https://www.whatdotheyknow.com/admin/bodies?utf8=%E2%9C%93&query=NHSChoicesID&commit=Search) shows 2,733 matches. Mostly destal practices.

This would be quite useful for people to check they are writing to the right location etc, mainly when there are multiple practices with the same name.

The link could be in the format of https://www.nhs.uk/Services/GP/Overview/DefaultView.aspx?id=#####
