### ISSUE TITLE
[Rails 5.1] Rewrite `alias_method_chain` theme overrides

### ISSUE THREAD

**Issue by lizconlan** [mysociety/whatdotheyknow-theme#594]
Required by mysociety/alaveteli#3970

Rails 5.1 removes `alias_method_chain` ([deprecated in 5.0](https://apidock.com/rails/Module/alias_method_chain)) which we [currently use in our model patches](https://github.com/mysociety/whatdotheyknow-theme/blob/e7bac47ee99c3467ad6f1670c2c986aca91011c9/lib/model_patches.rb#L158) to add survey methods to `RequestMailer` so we'll need to update this when we upgrade.

These articles might be helpful:
* https://blog.bigbinary.com/2016/08/21/rails-5-deprecates-alias-method-chain.html
* https://www.justinweiss.com/articles/rails-5-module-number-prepend-and-the-end-of-alias-method-chain/
* https://stackoverflow.com/questions/39580999/alias-method-chain-is-deprecated-rails-5-upgrade

**Comment by garethrees** [comment]
given we'e on rails 7 i think this has been resolved
