### ISSUE TITLE
Include info on donate page on why a card might be rejected

### ISSUE THREAD

**Issue by MattK1234** [mysociety/whatdotheyknow-theme#597]
A WhatDoTheyKnow user today reported:

> After two failed attempts, 
I managed to make a donation with a VISA card.

> The one thing which isn't clear, is what is meant by "date".

> Firstly I tried my expiry date and when that didn't work, tried the issue date.

> Neither worked so I tried 08 / 19 (or 08 / 2019) and that didn't work.

> I rang my bank, which could see what I'd done wrong and told me what to do.  

> To maximise your income, if you have the opportunity, it would help to flag up the reason/s why a card has been rejected, so would-be donors know what to do.

**Comment by dracos** [comment]
All we were given by stripe was "Your card was declined", which is what we would have shown (if Stripe don't automatically show that message in their handling). Looks like incorrect date was given, the expiry date would be the correct thing to do, this might change anyway due to SCA changes.

**Comment by MattK1234** [comment]
I'm going to close this. As mentioned, SCA may have changed this already, and I think most people would know which date to use.
