### ISSUE TITLE
Consider listing local resilience fora

### ISSUE THREAD

**Issue by MattK1234** [mysociety/whatdotheyknow-theme#599]
Should we add them?

There’s a list at 
https://www.gov.uk/guidance/local-resilience-forums-contact-details

One argument against is information they hold could probably be obtained by a FOI request to another local body eg. a fire or police service 

They do appear to be distinct bodies with their own secretariats though. They sometimes have their own websites and twitter feeds.

I suggest looking into them a bit more and weighing up the pros and cons.

It maybe their contact details are more changeable than those for the fire and police so we might introduce a maintainability challenge for little benefit 

Local Resilience Forums

**Comment by MattK1234** [comment]
I've looked through that list and most of the emails are (presumably) shared mailboxes (lrf@...) They all seem to be authority email addresses, not like the random ones we sometimes encounter with small councils etc. Perhaps that means they will change less often.

**Comment by RichardTaylor** [comment]
A volunteer has now produced a spreadsheet for us - we need to check, review, and upload, if we want to upload them.   

When we review the spreadsheet we can look to see if there are indications that they are distinct bodies with sufficient independence from their members, to inform our decision on if to add them.

**Comment by MattK1234** [comment]
The spreadsheet has now been uploaded.

I've used the tag `local_resilience`

They're all on the site at https://www.whatdotheyknow.com/body?tag=local_resilience

A future consideration would be improving the notes, at the moment they mostly have an address. We could explain more about what these organisations are, and what sort of things can be requested from them.

I'll add a note to the ticket for improving public notes (#483)

**Comment by garethrees** [comment]
Amazing!
