### ISSUE TITLE
Reduce the number of miscellaneous bodies below 250

### ISSUE THREAD

**Issue by confirmordeny** [mysociety/whatdotheyknow-theme#60]
There are currently 585 public authorities in the category ‘Miscellaneous’.  It should be possible to classify a large number of these into existing categories and set up some new categories where appropriate. I think that aiming to reduce the number of misc bodies by more than 50% is a worthwhile but attainable milestone.

**Comment by MattK1234** [comment]
That total has risen to 715.

**Comment by MattK1234** [comment]
Not much progress but over the past couple of days I've got the number of `miscellaneous` bodies down to 493.

**Comment by confirmordeny** [comment]
We are now on 460.

**Comment by FOIMonkey** [comment]
We've hit 248 and it's only taken a decade! #IssueZero

**Comment by mdeuk** [comment]
> We've hit 248 and it's only taken a decade! #IssueZero

Big thanks to all responsible for this, it does make a massive difference to usability. 😃
