### ISSUE TITLE
Add a safeguarding disclaimer to help pages

### ISSUE THREAD

**Issue by MattK1234** [mysociety/whatdotheyknow-theme#603]
> Thought possibly we could consider adding a 'Safeguarding' disclaimer on the 'How we run WDTK page after recent events which would demonstrate our commitment to safeguarding children and vulnerable adults when using the platform?

https://www.whatdotheyknow.com/help/how

Perhaps include links to useful contacts, such as the NHS, ChildLine, Samaritans.

**Comment by garethrees** [comment]
Related to https://github.com/mysociety/whatdotheyknow-theme/issues/607

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
