### ISSUE TITLE
Add section on categorisation to FOI officer questions help page

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#609]
A common reason FOI officers contact us is to query classifications of requests to their public body. 

We could add a new question to cover this, I'd slip it in before "How can I send a large file" saying:

>**Why is "Awaiting classification" or "Delayed" appearing on requests we've responded to?**

>We rely on our users to classify responses to their requests in the first instance however we are happy to correct any errors that are drawn to our attention. 

>Requests which have not been classified for a couple of months can have their classifications updated by any user. A request's classification can be changed via "Actions" > "Update the status of this request".

**Comment by MattK1234** [comment]
:+1:

**Comment by garethrees** [comment]
Merged and will be deployed to wdtk at some point over the next week or so
