### ISSUE TITLE
Add note to "Sorry, we couldn't find that page" error page on removed/moved requests

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#611]
Some users might arrive at the "Sorry, we couldn't find that page" error page because they've followed a link we've had to remove for legal / policy reasons.  Almost always the correspondence will still be on the site, but we will have had to change the URL due to problematic material being in the URL. In some cases users will need to sign in to see material we've made requester_only

We could note this on the error page and encourage users to search on our site for what they are looking for, and to seek to update, or get updated, any incoming links. 

We could link to our takedown policy and house rules. 

>Correspondence may be removed from public view on our site if it breaches our [house rules](https://www.whatdotheyknow.com/help/house_rules). The vast majority of such removals are due to people misusing the service for personal correspondence. 
>Even if we have removed personal correspondence from public view it is usually available to the user who initiated it if they [sign in](https://www.whatdotheyknow.com/profile/sign_in?r=%2Fhelp%2Fhow). 
>Occasionally we have to remove problematic material (such as potentially defamatory material) which appeared in the text of a link a request; such redaction changes, and breaks, the link. Such requests are almost always still available on our website, with redactions, and may be found via a search. You can read about [how we run our service](https://www.whatdotheyknow.com/help/how). 
>If you would like help locating a request please <a href="https://www.whatdotheyknow.com/help/contact">contact the volunteer team</a>. 

 
See also the 404 error page at
https://www.muckrock.com/jdofmsdkmlfsdm

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
