### ISSUE TITLE
Offer pointers to sources of advice on challenging takedowns

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#612]
It is very rare for WhatDoTheyKnow to take substantive FOI requests and responses down from our website. On the occasions we do we are transparent about what have done, and why, enabling others to challenge and pursue the matter. 

This issue is just to note that Twitter passes legal notices onto their users and offers some sources of advice, they say:

>Unfortunately, we cannot provide you with any legal advice and cannot provide any further information beyond what we provided in our notice. If you wish to seek legal counsel, here are some resources that may help.

>    For U.S. legal requests, you might consider contacting the American Civil Liberties Union (http://www.aclu.org/affiliates, +1 212-549-2500) or the Electronic Frontier Foundation (https://www.eff.org/pages/legal-assistance, info@eff.org, +1 415-436-9333). 
>    For non-U.S. legal requests, you might consider contacting a local attorneys’ association or law school, which may be able to provide you with contact information for specialised legal assistance on free expression issues or reduced-cost legal aid services available in your location.

https://help.twitter.com/en/rules-and-policies/twitter-legal-faqs

Should we have an equivalent advice section?

See also: https://github.com/mysociety/alaveteli/issues/2658#issuecomment-540614198

**Comment by garethrees** [comment]
Closing in favour of bigger picture issue at https://github.com/mysociety/whatdotheyknow-theme/issues/612
