### ISSUE TITLE
Consider contrast of "Make a request" button on the front page

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#613]
The "Make a request" button on the front page of WhatDoTheyKnow is yellow with white text. 

I don't think it's very easy to read the white text. 
<img width="251" alt="Screenshot 2019-10-22 at 19 37 48" src="https://user-images.githubusercontent.com/547695/67318490-764d5f80-f503-11e9-8ad0-db9b5c115df3.png">

**Comment by garethrees** [comment]
Hmm, this used to be black on white:

![Screenshot 2019-10-23 at 10 43 21](https://user-images.githubusercontent.com/282788/67380264-f61a0f00-f581-11e9-951c-ffa1931b49b8.png)

http://web.archive.org/web/20170205072647/https://www.whatdotheyknow.com/

**Comment by garethrees** [comment]
Probably related to the breakage in https://github.com/mysociety/alaveteli/issues/5419
