### ISSUE TITLE
Check and update listing of certain Higher Education institutions

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#617]
[Schedule 1 of the Freedom of Information Act](
http://www.legislation.gov.uk/ukpga/2000/36/schedule/1) makes: "a registered higher education provider of a description prescribed by regulations made by the Secretary of State for the purposes of [section 39(1) of the Higher Education and Research Act 2017](http://www.legislation.gov.uk/ukpga/2017/29/section/39)" subject to the Act; [what apparently are regulations in question](https://www.legislation.gov.uk/uksi/2018/1382/made) state:
> A higher education provider registered in the ‘Approved (fee cap)’ part of the register is prescribed as an eligible higher education provider for the purposes of section 39 of the Act. 

The register is that at:
https://www.officeforstudents.org.uk/advice-and-guidance/the-register/the-ofs-register/

There is some potential ambiguity over if all registered providers are subject to FOI, or just those eligible for funding. 

We can review that register and check we're listing all the bodies marked "Approved (fee cap)" as they are subject to Freedom of Information law. 

Ideally we'd include some kind of identifier to help keeping the database up-to-date in the future.

**Comment by confirmordeny** [comment]
I think we have very good coverage now and we can track through this list here: https://wdtkwiki.mysociety.org/wiki/Higher_education_institutions_with_Approved_(fee_cap)_status
