### ISSUE TITLE
Compare WhatDoTheyKnow's listing of schools with the official Government register

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#618]
Official register:

https://get-information-schools.service.gov.uk/

We should:
* Identify defunct schools and mark them as such on our site
* Add new schools we don't list. 
* Ideally we'd record connections between a body and it's successor, we currently do this via the notes field manually. See the "Record and show relationships between bodies" issue at https://github.com/mysociety/alaveteli/issues/4714 for automating this.  Perhaps we could start by using tags eg: successor:[url_name] predecessor:[url_name] then hope the software catches up. 

The published data doesn't contain email addresses, a volunteer could make a FOI request if there's not a reasonably up-to-date version with email addresses on WhatdoTheyKnow.

**Comment by HelenWDTK** [comment]
This was completed in 2020
