### ISSUE TITLE
Improve pre-drafted messages sent to users when requests are taken down via the admin system

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#622]
From the catch-up call:

Review canned responses including those "in the system" 

Add links to the house rules and warning of a ban into the standard one-click takedown responses from request admin pages.

**Comment by RichardTaylor** [comment]
All that's needed here is:

>Please see our house rules:
>https://www.whatdotheyknow.com/help/house_rules
>
>Repeated, or serious, breaches of our house rules will lead to your account being suspended. 

to be added to each of the standard responses.

**Comment by RichardTaylor** [comment]
It appears the "vexatious" and "not_foi" responses are in Alaveteli. 

Alaveteli doesn't have a "house rules" as a core element so it wouldn't be appropriate to make the change there. We'd need to pull a version of them into WhatDoTheyKnow-Theme?

The subject access, and immigration correspondence, messages are in WhatDoTheyKnow-Theme.

**Comment by garethrees** [comment]
> We'd need to pull a version of them into WhatDoTheyKnow-Theme?

Yeah, just need to duplicate and then edit the desired [`hidden_user_explanation`](https://github.com/mysociety/alaveteli/tree/0.39.1.1/app/views/admin_request/hidden_user_explanation) templates.

**Comment by RichardTaylor** [comment]
+1 

I just hid a correspondence thread as vexatious. I manually added our template warning for misuse and reference to the house rules, and added the standard footer to the message.  This could have been a two click operation if this issue had been addressed.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
