### ISSUE TITLE
Listing of Scottish RSLs on WhatDoTheyKnow

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#623]
The commencement of the [statutory instrument](http://www.legislation.gov.uk/ssi/2019/143/schedule/made) which extends the Freedom of Information (Scotland) Act to Registered Social Landlords (and certain connected bodies) in Scotland takes effect on 11 November 2019.

We already list a number of these bodies on WDTK (as foi_voluntary or similar); however, we now need to expand the dataset and populate our database with these newly designated bodies.

I have added a new category '[rslscot](https://www.whatdotheyknow.com/body?tag=rslscot)' to cover these bodies specifically; however, it would be a good idea, where possible, if we include additional metadata in the category tags (e.g. company / charity numbers, and, data protection registration numbers).

This 'issue' is intended for tracking purposes.

Relates to #11

**Comment by mdeuk** [comment]
When adding company details for RSLs it's notable that many are not companies registered at Companies House, but, instead, at the FSA (under the Co-operative and Community Benefit Societies Act). 

We should probably try and add a searchable link to their database (I will raise a ticket for this later).

**Comment by mdeuk** [comment]
This is still being worked on (slowly); we already have quite a few of the RSLs through previous work done by Alistair, however, some of the data behind the scenes is out of date and we're missing metadata.

I hope to have finished this soon.

**Comment by mdeuk** [comment]
This one has dragged on for quite a while owing to ill health (boo).

The Scottish Information Commissioner's office have been in contact to provide us with some helpful information to allow completion of this work; I will have this completed within the next few days.

**Comment by MyfanwyNixon** [comment]
Thanks for this Martyn! We've got a blog post drafted, which is awaiting a few comments. I'll forward it to the team email address.

**Comment by confirmordeny** [comment]
Done. https://wdtkwiki.mysociety.org/wiki/Registered_Social_Landlords_in_Scotland

**Comment by confirmordeny** [comment]
Done. See above.
