### ISSUE TITLE
Check corresponence of our public body databse with the Scottish ICO's database of Scottish bodies subject to FOI

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#624]
Scottish ICO database:

http://www.itspublicknowledge.info/YourRights/WhocanIask/Authorities_listed_in_Schedule_1_of_the_Act.aspx

#623 is a more specific issue.

**Comment by MattK1234** [comment]
I think @mdeuk may have done this in https://github.com/mysociety/whatdotheyknow-theme/issues/672#issuecomment-607840618

**Comment by HelenWDTK** [comment]
Closed as complete - this is not likely to be revisited given data quality issues with OSIC.
