### ISSUE TITLE
Consider a house rule against identifying anonymous/pseudonymous users 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#626]
Raising this issue following a single case, so it probably doesn't yet warrant action. 

Generally this issue can easily be dealt with if it's reported by removing annotations. 

https://www.whatdotheyknow.com/help/house_rules

**Comment by RichardTaylor** [comment]
A broader class of behaviour we might want to forbid:
https://en.wikipedia.org/wiki/Doxing

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
