### ISSUE TITLE
Fix broken outbound links

### ISSUE THREAD

**Issue by gbp** [mysociety/whatdotheyknow-theme#628]
The 'Hints for Practitioners' link on https://www.whatdotheyknow.com/help/officers#email_only is a 404. There have been others recently so we probably should review all outbound links to ensure they are all up-to-date.

See #606

**Comment by MattK1234** [comment]
There's another one at https://www.whatdotheyknow.com/help/unhappy#refer-to-ico - "the Information Commissioner's advice for those with concerns about accessing information " returns a 404.

**Comment by MattK1234** [comment]
Another broken link I've noticed today:

At https://www.whatdotheyknow.com/help/how:

`https://ico.org.uk/media/for-organisations/documents/1536/breach_reporting.pdf.` is a 404.

I'll try to find and suggest alternative links for the 404 ones soon.

**Comment by MattK1234** [comment]
lib\views\followups\_followup.html.erb contains a broken link: http://foiwiki.com/foiwiki/index.php/Internal_reviews

We could change it to https://www.whatdotheyknow.com/help/unhappy#internal_review instead.

**Comment by MattK1234** [comment]
I've reviewed every link on the help pages today and found another 2 broken links.

https://www.whatdotheyknow.com/help/privacy#full_address - Hints for Practitioners is a 404

https://www.whatdotheyknow.com/help/privacy#full_address - FOI register is a 404
