### ISSUE TITLE
Consider listing charities where all trustees are appointed by public authorities

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#629]
> …consider listing charities wholly controlled by public bodies to the categories of body we list on our service.
> 
> We'd list them as `foi_no` and would campaign to have them brought into the scope of the act.
> 
> I suspect a good test might be for all trustees to be appointed by and acting on behalf of public bodies.  (I'm not sure if Charity law permits a trustee not to be independent though).
> 
> This example case of a leisure centre trust where councils appoint the members certainly feels just like a wholly owned body to me, but "wholly owned" doesn't apply as it's not a charity.
> 
> I'm not sure if we haven't seen other classes of body - companies without share capital - which didn't clearly come under "wholly owned" - I can't recall an example - but we might want to take a similar stance there.
> 
> Richard

via `Charities Wholly Controlled by Public Bodies - Proposed New Class of Bodies to List` thread on `volunteers@`

**Comment by confirmordeny** [comment]
Even if a trustee is appointed by a public authority or a company, once appointed they are an independent trustee and are not representatives of the body that appointed them. Accordingly, no charity trustee should ever be 'acting on behalf of public bodies' (other than the charity itself). 

There is a note on the wiki that explains the position for unincorporated charities: https://wdtkwiki.mysociety.org/wiki/Charities_and_FOI

(Usual disclaimer re not being a lawyer etc)

**Comment by confirmordeny** [comment]
I think the title of this issue should be changed to "Adding charities where all trustees are appointed by public authorities".

**Comment by confirmordeny** [comment]
I have renamed this. I hope that is OK.

**Comment by confirmordeny** [comment]
I have made an edit to the title.

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/Authority_suggestions
