### ISSUE TITLE
Review the entry notes on Housing Associations

### ISSUE THREAD

**Issue by MattK1234** [mysociety/whatdotheyknow-theme#632]
They don't appear to be subject to EIR either: https://www.foiman.com/archives/3170

There's probably a few that need updating

https://www.whatdotheyknow.com/body/list/housing_association

**Comment by RichardTaylor** [comment]
We have people using housing association pages to make complaints. 

>"Please consider if your concerns would be best addressed via the Housing Association's complaints policy. If you are not happy with the association's response to your complaint you may be able to get help from a tenant panel, your local councillors or MP, or the Housing Ombudsman".  

https://www.housing-ombudsman.org.uk/useful-tools/fact-sheets/3123-2/    

I see some housing associations are listed on https://www.resolver.co.uk/ so we could point our users there in relevant cases.  https://www.resolver.co.uk/service_types/housing-associations-complaints  We need great care not to lose our service's focus and simplicity though.  Maybe this advice could be accessed via a "Do you have a complaint?" interstitial question?

**Comment by confirmordeny** [comment]
The updates have been made.  See also: #1739 and #1403.
