### ISSUE TITLE
Differentiate between FOIA and FOISA in internal review advice

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#633]
> Does it distinguish between FOIA and FOISA (because in the case of the later, an internal review *is* required before complaining to the SIC)?
>
> – https://twitter.com/alistair_sloan/status/1202294301906083841

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
