### ISSUE TITLE
Consider adding info about Egress Switch etc to help pages

### ISSUE THREAD

**Issue by MattK1234** [mysociety/whatdotheyknow-theme#640]
We seem to be encountering more instances of responses being sent via Egress Switch and other secure file transfer systems. It's clear that our users don't always know what to so when this happens, and I don't think we provide clear guidance on it anywhere.

Perhaps under <a href="https://www.whatdotheyknow.com/help/requesting#format">Will I get the information in the format I want?</a> or even in a section on it's own.

Something along the lines of:

Some authorities use secure file transfer systems to respond to requests via WhatDoTheyKnow. It's not entirely clear why they do this, as a response under the Freedom of Information Act should be considered "disclosure to the world", although in some cases we believe it is to make things difficult for our users.

If you receive a response that uses one of these systems, or you notice one on the site, please <a href="https://www.whatdotheyknow.com/help/contact">contact us</a>. We can usually access the response and upload it to our servers to make it available for all. If you are the requester, you could also write back to the authority requesting that a response is provided in an alternative, more accessible format.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
