### ISSUE TITLE
Update the blog info in the internal Wiki

### ISSUE THREAD

**Issue by MattK1234** [mysociety/whatdotheyknow-theme#642]
https://wdtkwiki.mysociety.org/wiki/Blog

THIS LINK NO LONGER WORKS*** (referring to the link on the Wiki)

Need to get the new link and update the page.

**Comment by MattK1234** [comment]
Shall need to ask Myf about this upon return from annual leave.

**Comment by MyfanwyNixon** [comment]
I think it should probably just say 'Email a member of the mySociety staff who can log in using the admin credentials (listed on the mySociety wiki) and send you an invitation'.

**Comment by MattK1234** [comment]
Thanks, I've updated the page. :smiley:
