### ISSUE TITLE
Add to the Twitter page in the internal Wiki

### ISSUE THREAD

**Issue by MattK1234** [mysociety/whatdotheyknow-theme#643]
https://wdtkwiki.mysociety.org/wiki/Twitter

Could add about DMs, message requests, that security alerts are sometimes triggered

Could also mention third party "Tweeting" systems other volunteers use that work well. I'm sure someone uses Tweetdeck.

**Comment by MattK1234** [comment]
Other things I've just recalled whilst browsing Slack and the catch up call notes:

-Hashtags, check they're appropriate (#sister was used which had some NSFW content. Don't overuse them

- Add ALT text when using images etc to improve accessibility.

From the Slack channel on 02/10/19

**Comment by MattK1234** [comment]
Handy text we could add:

Including an image will ensure more visibility
Tweet core messages several times, at different points in the day/week
Try to spread repeat tweets out
Check, double-check and check again for spelling and grammar errors
Think twice about the factual accuracy of what you are about to tweet

and now:
Add ALT text to your image (this can be done on Hootsuite via 'edit image details' when you upload it) for purposes of accessibility

**Comment by WilliamWDTK** [comment]
- [x] Mention DMs (already done)
- [x] Mention message requests
- [x] Add a note about receipt of security alerts, and replying to them in the support inbox.
- [x] Add note about Tweetdeck
- [x] Add note about hashtags
- [x] Add note about Alt text for images
- [x] Add note about adding images (already done, expanded slightly)
- [x] Add note about when to tweet (already done)
- [x] Add note about checking tweets before publishing (SPaG and factual accuracy) (already done)

I think this can be closed.
