### ISSUE TITLE
Review canned responses and ensure the list on the internal Wiki is up to date

### ISSUE THREAD

**Issue by MattK1234** [mysociety/whatdotheyknow-theme#644]
Check they are replicated in the wiki and up to date.
Check external links are still correct
Consider others we could create to save admin time

**Comment by sallytay** [comment]
The Wiki list was tidied and updated as part of ticket #777 

https://wdtkwiki.mysociety.org/wiki/Canned_responses

It is now up to date and will continue to be updated as we make any changes to the canned responses, see ticket #1060
