### ISSUE TITLE
Review bodies with a .gsi.gov.uk address

### ISSUE THREAD

**Issue by MattK1234** [mysociety/whatdotheyknow-theme#647]
From the internal Wiki to do list:

Review bodies with a .gsi.gov.uk address as we expect them to be going out of use https://www.whatdotheyknow.com/admin/bodies?utf8=✓&query=gsi.gov.uk&commit=Search

(many bodies we list are defunct so don't need updating, others are small so this isn't so important)

Also need to review the other gsi-family domain names
-gse.gov.uk
-gcsx.gov.uk
-gsx.gov.uk

**Comment by MattK1234** [comment]
I've done a quick review of these today.

At the time of writing, we've got (excluding bodies tagged `defunct`):

`.gsi.gov.uk` - xx bodies
<strike>`.gse.gov.uk` - 45 bodies</strike>
`.gcsx.gov.uk` - 1 body - <a href="https://www.whatdotheyknow.com/admin/bodies/5533">5533</a>
<strike>`.gsx.gov.uk` - 0 bodies</strike>

I think there's possibly a handful of the above that are defunct, and WDTK just needs updating. Others still list the GSI email on their website etc.

**Comment by HelenWDTK** [comment]
Closing as complete.
