### ISSUE TITLE
Welsh translation of /help/privacy is out of date

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#650]
The Welsh translation of the [Privacy Policy](https://www.whatdotheyknow.com/cy/help/privacy) is  out of date when compared to the corresponding English version.

We cannot necessarily assume that a Welsh speaker could understand the English version, therefore, they might not be able to exercise their legal rights. We should aim to correct that.

1. We make no reference to GDPR or DPA 2018 (only DPA 1998)
2. We make reference to Section 10 requests for removal of personal information that "causes you substantial or unnecessary damage or distress" - this is outdated as we should be referring to Article 17 of GDPR (or, Section 47 of DPA 2018 (_see also 6_)
3. We make no mention of our [retention period for support mail](https://www.whatdotheyknow.com/help/privacy#retention_support)
4. We make no mention of our [retention period for breaches](https://www.whatdotheyknow.com/help/privacy#retention_breach)
5. We make no mention of our [legal basis for processing](https://www.whatdotheyknow.com/help/privacy#legal_basis)
6. We make no specific mention of [GDPR rights](https://www.whatdotheyknow.com/help/privacy#your_rights), e.g. right to erasure/be forgotten, right of access, right to object, complaint rights

Affected file: https://github.com/mysociety/whatdotheyknow-theme/blob/master/lib/views/help/privacy.cy.html.erb

**Comment by MattK1234** [comment]
We did have a site wide banner on the go asking for volunteers to translate the page for us. We had a handful of responses to it, I don't think any went further than initial enquiries.

We've knocked the banner on the head for the time being to put up the delay expected banner related to Coronavirus (#669 refers).

One option is to follow up with some of the people who have contacted us already.

**Comment by MattK1234** [comment]
After having looked at some of the other Welsh translation pages today (namely https://www.whatdotheyknow.com/cy/help/requesting), it seems they are all a few updates behind the English equivalent. Ideally if we get a willing volunteer they might be able to review and update all the Welsh pages for us.
