### ISSUE TITLE
Consider adding airport operators to WDTK

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#651]
Based on the recent [ICO decision notice](https://ico.org.uk/media/action-weve-taken/decision-notices/2020/2617181/fer0844872.pdf) regarding Heathrow Airport we should consider listing other similar entities who would fall under the definition of an ‘airport operator’ or ‘statutory undertaker’ as per the Civil Aviation Act 2012.

We can list these bodies using the 'eir_only' tag so as to highlight their legal status.

The CAA list of certificated aerodromes may provide a starter for ten in terms of locating other relevant public authorities: https://www.caa.co.uk/Commercial-industry/Airports/Aerodrome-licences/Certificates/UK-certificated-aerodromes/

**Comment by mdeuk** [comment]
It would appear that Heathrow are appealing the ICO's decision - case ref **EA/2020/0101**

https://www.gov.uk/government/publications/information-rights-register-of-tribunal-cases/information-tribunal-register-of-current-cases

**Comment by RichardTaylor** [comment]
Some progress has been made

https://www.whatdotheyknow.com/body/list/airport

there is more to do. 

There are internal discussion threads and a spreadsheet. Do [contact us](https://www.whatdotheyknow.com/help/contact) if you want to help.

**Comment by sallytay** [comment]
Request from user: Would it be possible to add Teesside International Airport to the site as it is now wholly controlled by a public body (Tees Valley Combined Authority)?
Ref
https://northeastbylines.co.uk/stobart-pulls-out-of-teesside-international-airport/
https://www.thenorthernecho.co.uk/news/19084445.mayor-faces-criticism-scrutiny-teesside-airport-finances/

**Comment by RichardTaylor** [comment]
Teesside International Airport Limited listed

https://www.whatdotheyknow.com/body/teesside_international_airport_limited

**Comment by sallytay** [comment]
Update from inbox thread: "All public bodies which run commercial airports are now included in our list of airport operators at https://www.whatdotheyknow.com/body/list/airport ".  I'm not sure about the juxtaposition of public and commercial there, but it might be OK. We can then mark those as already being listed on WhatDoTheyKnow on the spreadsheet.

The next step for the others is finding a contact email address.

**Comment by RichardTaylor** [comment]
> "All public bodies which run commercial airports are now included in our list of airport operators at https://www.whatdotheyknow.com/body/list/airport "

This quote appeared in the thread as a statement explaining a position we expected to get to. It is a position we have now reached. The tagging of public bodies which run airports was an unexpected, but excellent, outcome of this work. 

>The next step for the others is finding a contact email address.

The email addresses for an additional ~90 airport operators have been found. I don't think there is significant further email address finding to be done here.

**Comment by RichardTaylor** [comment]
A key outstanding task is completing the field for the name of the airport operator (the name of the body to be listed).  The internal email thread has been updated to note this.

**Comment by HelenWDTK** [comment]
https://wdtkwiki.mysociety.org/wiki/Authority_suggestions
