### ISSUE TITLE
Add Community Safety Partnerships to WhatDoTheyKnow

### ISSUE THREAD

**Issue by MattK1234** [mysociety/whatdotheyknow-theme#652]
We do include some like the one in Birmingham. 

https://www.gov.uk/government/publications/community-safety-partnerships-contact-details

There's an Excel spreadsheet on the Gov website which we could utilise for a bulk upload.

We should consider tags and notes.

**Comment by MattK1234** [comment]
Oh. The `Gov.uk` page hasn't been updated since 10 April 2012

It might have a lot of outdated information...

**Comment by confirmordeny** [comment]
Done as signposts - https://www.whatdotheyknow.com/body/list/csp
