### ISSUE TITLE
Bulk addition of citations/annotations

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/whatdotheyknow-theme#660]
Richard says:
>There's a Twitter thread at https://twitter.com/lawsonstu/status/1226807153257787392 [...]
> There are 160 requests, the URLs for each are in the data download
> https://zenodo.org/record/3659971#.XkFBNi2cZ24  (That's a link to a webpage from which an Excel file is linked)
> Does a developer want to add a citation / annotation in bulk to them all - it would be rather a lot of manual clicking for an admin to do so.
> We could suggest the user fills in their profile with links to the outputs of their work, that's something we suggest from time to time, but that's a click away from the requests themselves.

**Comment by MattK1234** [comment]
Would we want the citations to link to https://www.timeshighereducation.com/news/uk-universities-paid-big-publishers-ps1billion-past-decade or elsewhere?

**Comment by MyfanwyNixon** [comment]
It looks like I was just quoting @RichardTaylor so he may have an opinion! However I think we could link to both the THE and the Zenodo page?

**Comment by HelenWDTK** [comment]
Have asked devs to add.
