### ISSUE TITLE
Add district salmon fisheries board in Scotland to WhatDoTheyKnow

### ISSUE THREAD

**Issue by MattK1234** [mysociety/whatdotheyknow-theme#665]
For background, search `Establishe who can do FOI` in the support mailbox.

This will likely involve a bit of research to establish their structure and governance. If it's not clear cut we might want to discuss it on a call. I'm creating it as a ticket so we don't lose it.

**Comment by confirmordeny** [comment]
District Salmon Fishery Boards are subject to Scottish EIR: https://www.foi.scot/sites/default/files/2022-04/Decision208-2021.pdf

**Comment by confirmordeny** [comment]
We have a partial list on the Wiki: https://wdtkwiki.mysociety.org/wiki/District_Salmon_Fishery_Boards

**Comment by confirmordeny** [comment]
Done: https://www.whatdotheyknow.com/body/list/dsfb
