### ISSUE TITLE
Dealing with delays during the Coronavirus pandemic

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#669]
[continued from discussion on volunteers@]

We've had a number of public bodies contact us to ask that we advise requestors of potential delays to FOI/EIR requests being handled owing to the Coronavirus pandemic.

It is possible that there is legislation due to be passed which may change the statutory timescales for responding to a request; however, in the meantime, it is perhaps prudent that we put in place some guidance for our users, especially as Alaveteli will still be treating requests as being expected to receive a reply within 20 working days and will therefore be sending auto-notifications which could cause some confusion.

**Comment by mdeuk** [comment]
Banner now in place on WDTK, using text from @MattK1234:

`The Coronavirus (COVID-19) pandemic is having an impact on response times to requests. Please see this information from the <a href="https://ico.org.uk/about-the-ico/news-and-events/icos-blog-on-its-information-rights-work/" alt="Link to guidance from the Information Commissioner's Office (opens in a new window)" target="_blank">Information Commissioner's Office</a>, and the <a href="http://www.itspublicknowledge.info/home/News/20200313.aspx" alt="Link to guidance from the Scottish Information Commissioner (opens in a new window)" target="_blank">Scottish Information Commissioner</a>. Please <a href="/help/contact">contact us</a> if you have any questions.`

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/249418/78028961-bdb00580-7357-11ea-953f-67564369bb70.png">

**Comment by mdeuk** [comment]
From the Scotland perspective this is being covered off by technical means under #672 - once this is implemented we may wish to formalise things by way of a help page.

**Comment by garethrees** [comment]
I've updated the banner to reflect that we've now published a [blog post](https://www.mysociety.org/2020/04/02/freedom-of-information-during-the-pandemic/) going in to further detail.

It starts with the text that [was previously in the banner](https://github.com/mysociety/whatdotheyknow-theme/issues/669#issuecomment-606610779).

![Screenshot 2020-04-03 at 08 54 36](https://user-images.githubusercontent.com/282788/78337347-c50a2580-7588-11ea-9f15-bda5ddd4ffba.png)

**Comment by MyfanwyNixon** [comment]
Would we like to update the banner to link to the updated blog post at https://www.mysociety.org/2020/07/10/foi-and-covid-19-an-update/?

Either way, I've linked to the new post from the top of the prior one.

**Comment by garethrees** [comment]
Updated the banner with the new URL 👍

**Comment by HelenWDTK** [comment]
I'm going to close this, as (hopefully) this is something that we will not need to do again.
