### ISSUE TITLE
Add Severnoaks DC autoresponder as an invalid reply address

### ISSUE THREAD

**Issue by MattK1234** [mysociety/whatdotheyknow-theme#670]
`autoresponder@sevenoaks.gov.uk` doesn't accept replies. This caused a user confusion today.

Seems it needs to be added to `ReplyToAddressValidator.invalid_reply_addresses` at https://github.com/mysociety/whatdotheyknow-theme/blob/master/lib/model_patches.rb

I should be able to get a PR in for this in the next couple of days.

**Comment by MattK1234** [comment]
I also propose adding a page to the internal wiki about this.

**Comment by garethrees** [comment]
Fixed by https://github.com/mysociety/whatdotheyknow-theme/pull/673

**Comment by MattK1234** [comment]
I've added a page to the internal Wiki at https://wdtkwiki.mysociety.org/wiki/Invalid_Reply_Addresses for future reference.
