### ISSUE TITLE
Temporary late calculation for Scottish authorities

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#672]
Looks like Scotland have extended the deadlines to 60 days (normal) / 100 days (extension) if I'm reading this correctly http://www.itspublicknowledge.info/home/News/20200401.aspx

I think we can fairly easily handle this in WDTK by adding a custom late calculator based on the `scotland` tag:

```diff
diff --git a/lib/model_patches.rb b/lib/model_patches.rb
index 7344b39..6301726 100644
--- a/lib/model_patches.rb
+++ b/lib/model_patches.rb
@@ -54,7 +54,9 @@ Rails.configuration.to_prepare do
 
         def late_calculator
           @late_calculator ||=
-            if public_body.has_tag?('school')
+            if public_body.has_tag?('scotland')
+              ScotlandLateCalculator.new
+            elsif public_body.has_tag?('school')
               SchoolLateCalculator.new
             else
               orig_late_calculator
diff --git a/lib/scotland_late_calculator.rb b/lib/scotland_late_calculator.rb
new file mode 100644
index 0000000..8074f6b
--- /dev/null
+++ b/lib/scotland_late_calculator.rb
@@ -0,0 +1,14 @@
+# -*- encoding : utf-8 -*-
+class ScotlandLateCalculator
+  def self.description
+    %q(Scotland has extended deadlines during COVID-19)
+  end
+
+  def reply_late_after_days
+    60
+  end
+
+  def reply_very_late_after_days
+    100
+  end
+end

```

I had a _very quick_ look at some (~5) Scottish and they all had the `scotland` tag. I expect we're missing some, but we can deal with any missing if they get raised to user support.

**Comment by garethrees** [comment]
> the Scottish Government’s proposed law would extend the initial deadline for public bodies to respond to FoI requests from 20 to 60 working days, with a possible further extension of 40 working days.
>
> https://theferret.scot/coronavirus-bill-scottish-information-commissioner/

So yes, initial of 60, +40 = 100 for very late.

**Comment by MattK1234** [comment]
> I had a very quick look at some (~5) Scottish and they all had the scotland tag. I expect we're missing some, but we can deal with any missing if they get raised to user support.

We've also got 8 tagged `Scotland`. I'm going to change them now to `scotland` to make life easier.

**Comment by MattK1234** [comment]
> We've also got 8 tagged `Scotland`. I'm going to change them now to `scotland` to make life easier.

Done!

**Comment by ajparsons** [comment]
This is a list of wdtk ids I've reconciled against a list of Scottish authorities for another project, might be helpful : https://gist.github.com/ajparsons/666cc8cc089645a48d3c6442674a49c5

**Comment by garethrees** [comment]
> This is a list of wdtk ids I've reconciled against a list of Scottish authorities for another project, might be helpful : https://gist.github.com/ajparsons/666cc8cc089645a48d3c6442674a49c5

omg super helpful! Ensured `scotland` is applied to all these (13 were missing the tag):

```ruby
WDTK_IDS = %w[4287 5688 535 5648 1284 5670 5673 1123 3548 513 5698 5703 5706 529 5709 5710 12791 13862 4706 5659 548 549 1134 1301 560 1288 573 1139 1140 4283 55539 4342 13863 55538 52200 52309 52199 52308 52252 52253 52359 55537 39 5637 40 45 5640 48 5642 5643 5644 5610 5612 5615 5616 5617 5618 5621 5622 5645 185 5655 133 162 5674 130 5611 163 168 5677 172 176 5678 178 191 5681 603 613 269 197 624 281 5689 5694 296 302 616 5697 5684 5701 636 265 5636 345 374 428 5708 5696 5667 5664 5660 315 5630 339 354 5626 1636 5663 5661 430 5624 5623 5669 1188 1190 1236 1264 1249 1261 1262 1237 1238 1239 1240 1241 1242 1265 1267 1243 1268 1244 1245 1269 1250 1246 1247 1248 4242 8128 1214 1217 1185 1215 4238 1216 54797 54884 87994 4268 2875 2876 4270 667 12853 4260 4261 4263 668 4264 4243 4271 4288 4251 3668 4172 2586 4280 4164 3312 3591 4277 1028 4253 3618 4255 52163 3644 4199 4254 5668 4272 4247 4244 4245 4248 4249 4702 6081 8131 8130 1179 8156 52069 52183 52185 4236 4297 55513 52155 89810 89820 89827 89661 89804 89805 89806 88951 89807 89808 89809 89811 89812 89813 89814 684 55512 89815 88950 89817 55521 89818 89819 89821 89823 89824 89825 89833 89828 89829 88243 89236 2939 64682 64680 54866 4290 51569 52325 52331 88110 52327 52333 4194 11260 52330 52344 52341 52328 92253 89234 58219 54819 54821 54824 54825 54826 54827 54828 54829 54830 54831 54833 54834 64616 54836 54838 54839 54840 54841 54842 54843 54844 54845 54846 54848 54849 54852 54853 54854 54855 54857 54858 54859 54860 54861 54862 54863 54864 54865 54867 54868 54869 54870 54871 54872 54873 54874 54875 54876 55960 57613 92356 57562 5638 5656 5676 5679 5682 5695 5635 5634 5711 5619 5632 5620 5629 5627 5625 5658 5628 1183 1191 1192 2887 4343 5686 5691 52396 91526 91527]

PublicBody.where(id: WDTK_IDS).each do |body|
  body.add_tag_if_not_already_present('scotland')
end
```

**Comment by mdeuk** [comment]
> > This is a list of wdtk ids I've reconciled against a list of Scottish authorities for another project, might be helpful : https://gist.github.com/ajparsons/666cc8cc089645a48d3c6442674a49c5
> 
> omg super helpful! Ensured `scotland` is applied to all these (13 were missing the tag):
> 
I've posted an update using data from OSIC's [master file](http://www.itspublicknowledge.info/YourRights/WhocanIask/Authorities_listed_in_Schedule_1_of_the_Act.aspx) - we now list quite a few more (including a couple of new bodies).
[foisa_covidbill.csv.zip](https://github.com/mysociety/whatdotheyknow-theme/files/4421257/foisa_covidbill.csv.zip)

**Comment by garethrees** [comment]
> All bodies modified are tagged `foisa_covidbill` for ease of reference in the future.

In 6b0982f I used the tag `scotland`, so that we wouldn't have to do any cleanup work of tags later – we just remove the code that applies the custom late calculator.

Is there a reason that we might not want to apply the calculation to some authorities tagged `scotland`?

I've also noticed we list some authorities as [`companyinscotland`](https://www.whatdotheyknow.com/admin/bodies?utf8=%E2%9C%93&query=companyinscotland&commit=Search) but without `scotland`. I can update those authorities if it's helpful?

**Comment by mdeuk** [comment]
> Is there a reason that we might not want to apply the calculation to some authorities tagged `scotland`?

None that I can think of - this was for operational convenience while I was uploading since the change wouldn't affect every entity we list for Scotland (for example, the OSIC data didn't cover bodies where only EIR applies or the body is voluntarily complying).

**Comment by MattK1234** [comment]
> I've posted an update using data from OSIC's master file

Just to note it seems their file is not particularly up to date as it has changed back a couple of `.gsi.gov.uk` email addresses which we had already updated, <a href="https://www.whatdotheyknow.com/admin/bodies/4343">Disclosure Scotland</a> for example.

I came across this whilst reviewing bodies as part of #647 . I've changed them back where I've noticed them.

**Comment by mdeuk** [comment]
> > I've posted an update using data from OSIC's master file
> 
> Just to note it seems their file is not particularly up to date as it has changed back a couple of `.gsi.gov.uk` email addresses which we had already updated, [Disclosure Scotland](https://www.whatdotheyknow.com/admin/bodies/4343) for example.
> 
> I came across this whilst reviewing bodies as part of #647 . I've changed them back where I've noticed them.

Ugh that’s poor - curiously, there are still GSi-type domains in existence more than a year after its alleged demise… but we of course shouldn’t put it to chance that everything pre March 2019 still works.

I’ll have another run through in case we’ve more lurking behind the scenes.

**Comment by MattK1234** [comment]
> I've also noticed we list some authorities as companyinscotland but without scotland. I can update those authorities if it's helpful?

`scotland` tag added to all :smiley:

**Comment by garethrees** [comment]
Amazing, thanks! I think we can call this closed.
