### ISSUE TITLE
Review the "Associations of Local Councils" entries on WhatDoTheyKnow

### ISSUE THREAD

**Issue by MattK1234** [mysociety/whatdotheyknow-theme#676]
https://www.whatdotheyknow.com/admin/bodies?utf8=%E2%9C%93&query=association+of+local+councils&commit=Search

We should check the tags and public notes accurately reflect their status.

> ICO, they have confirmed that  Derbyshire Association of Local Councils (and presumable others) are exempt from FOI requests. The ICO reference is FS50902131

We could check for the appearance of the DN on the ICO website and link to it from the body page.

**Comment by mdeuk** [comment]
> We could check for the appearance of the DN on the ICO website and link to it from the body page.

The DN for this one ([FS50902131](https://icosearch.ico.org.uk/s/search.html?collection=ico-meta&profile=decisions&query&query=FS50902131)) is still not visible on the ICO's database - it'd be good if we could get sight of it to understand the reasoning behind their decision.

**Comment by confirmordeny** [comment]
The decision notice is not available. 

If an association is incorporated as a company then it will be subject to FOI if its members are local councils (with a few exceptions relating to City of London).[1] If an association is not incorporated then legally it does not exist distinct from its members which are local councils and are subject to FOI. The conclusion is essentially the same in both cases. I am going to close this but people can re-open if they disagree.

[1] https://www.legislation.gov.uk/ukpga/2000/36/section/6
