### ISSUE TITLE
Review 'Local Safeguarding Children Boards'

### ISSUE THREAD

**Issue by MattK1234** [mysociety/whatdotheyknow-theme#677]
It appears some/most/all of these have become 'safeguarding children partnerships'.

Example: https://www.safernel.co.uk/nelsafeguarding-children-partnership/

> The North East Lincolnshire Safeguarding Children Partnership (NELSCP) replaced the Local Safeguarding Children Board on 29 June 2019.

**Comment by MattK1234** [comment]
https://www.whatdotheyknow.com/body?tag=lscb returns 147 results.

**Comment by RichardTaylor** [comment]
I've marked those local safeguarding children boards which no-longer exist defunct, and have tagged those bodies which are continuing to exist under the name of "board" lscp 

About 20 bodies have retained the name "board" while around 110 are using "partnership". 

https://www.whatdotheyknow.com/body/list/lscb
https://www.whatdotheyknow.com/body/list/lscp

There is a spreadsheet for collecting contact details, working on notes etc. 

https://docs.google.com/spreadsheets/d/15_q5abbEOcZewoMsykCWnNsE7_ZrxAb5wvgx8kN3kJ0/edit?usp=sharing

**Comment by RichardTaylor** [comment]
Done.

https://www.whatdotheyknow.com/body/list/lscp
