### ISSUE TITLE
Review NHS England bodies

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#680]
On the 1st of April a large number of changes were made to bodies which form part of NHS England:

![](https://digital.nhs.uk/binaries/content/gallery/website/services/ods/2020-stp/what-is-changing.png)

We should review the listing of bodies affected and consider what changes we need to make to the database. We may already list some of the STPs, however, the big change is likely to be the CCG closures/mergers as we will need to source new data for these bodies.

https://digital.nhs.uk/services/organisation-data-service/change-summary---stp-reconfiguration

**Comment by MattK1234** [comment]
A very helpful WhatDoTheyKnow user has helped us do the CCG changes. I think we're complete on them now, but we should check to be sure.

**Comment by RichardTaylor** [comment]
More changes are coming in April 2021

https://digital.nhs.uk/services/organisation-data-service/change-summary-reconfiguration-2021-ccg-mergers

We should look into what the NHS Organisation Data Service do and see if we can automate keeping our system in sync with theirs 

https://digital.nhs.uk/services/organisation-data-service

**Comment by mdeuk** [comment]
> 
> 
> More changes are coming in April 2021
> 
> https://digital.nhs.uk/services/organisation-data-service/change-summary-reconfiguration-2021-ccg-mergers
> 
> We should look into what the NHS Organisation Data Service do and see if we can automate keeping our system in sync with theirs
> 
> https://digital.nhs.uk/services/organisation-data-service

The first of these changes have now been pushed onto WDTK:

| New CCG Name                                       | ODS Code | WDTK Body ID |
|----------------------------------------------------|--------------|-----------|
| NHS Bedfordshire, Luton and   Milton Keynes CCG    | M1J4Y        | 110948    |
| NHS   Hampshire, Southampton and Isle of Wight CCG | D9Y0V        | 110949    |
| NHS Frimley CCG                                    | D4U1Y        | 110950    |
| NHS   North East London CCG                        | A3A8R        | 110951    |
| NHS Shropshire, Telford and   Wrekin CCG           | M2L0M        | 110952    |
| NHS   Black Country and West Birmingham CCG        | D2P2L        | 110953    |
| NHS Coventry and Warwickshire   CCG                | B2M3M        | 110954    |
| NHS   Kirklees CCG                                 | X2C4Y        | 110955    |
| NHS North West London CCG                          | W2U3Z        | 110956    |

We are using the ODS code with the tag '`nhsorg`' and using a second variant of this with the tag '`nhsorg_successor`' which will be added to predecessor bodies (e.g. [M1J4Y](https://www.whatdotheyknow.com/body?tag=nhsorg_successor%3AM1J4Y)).

**Comment by WilliamWDTK** [comment]
This is quite old now, has it been done?

**Comment by HelenWDTK** [comment]
Yes. I think this is even a reorganisation behind!
