### ISSUE TITLE
Clarify the difference between an IJB and a HSCP

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#681]
As Matt has recently noticed, many (if not all) of the Health and Social Care Partnerships (tagged `hscpscot`) are also tagged as Integration Joint Boards (`ijbscot`) - there is a difference between these entities.

More detail about the difference in models can be found at: https://hscscotland.scot/integration/

When we added the HSCP and IJBs many were still in the implementation stage so this likely made sense at the time; however, as there is now a delineation between functions we should clarify our tagging so as to prevent any confusion.

**Comment by MattK1234** [comment]
I'm closing this as having checked just now it looks like we've completed this. Do re-open if I've missed something!
