### ISSUE TITLE
'View as HTML' links broken

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#684]
The 'view as HTML' links for Word documents which are rendered using Google Docs viewer are currently broken on WDTK, leading users to an generic error screen with the message "No preview available".

<img width="800" alt="image" src="https://user-images.githubusercontent.com/249418/81382864-fbe2d680-9106-11ea-9b97-da5ea95b4ac8.png">

Looking at a sample request [653302](https://www.whatdotheyknow.com/request/653302/response/1568975/attach/html/3/attachment.docx.html), it appears that when we are rendering the code to trigger the Google viewer the URI is being malformed as we are not passing the base URL.

`<iframe src="https://docs.google.com/viewer?url=%2Frequest%2F653302%2Fresponse%2F1568975%2Fattach%2F3%2Fattachment.docx%3Fcookie_passthrough%3D1&amp;embedded=true" width="100%" height="100%" style="border: none;"></iframe>`

Changing the code to include the base URL results in a working webpage:
`<iframe src="https://docs.google.com/viewer?url=https:%2F%2Fwww.whatdotheyknow.com%2Frequest%2F653302%2Fresponse%2F1568975%2Fattach%2F3%2Fattachment.docx%3Fcookie_passthrough%3D1&amp;embedded=true" width="100%" height="100%" style="border: none;"></iframe>`

### Steps to reproduce

1. Visit any request where an attachment has been provided in Microsoft Word format; e.g. requests [653302](https://www.whatdotheyknow.com/request/crime_stats_for_the_greenway_str#incoming-1568975), [657334](https://www.whatdotheyknow.com/request/highway_organisation_chart_17#incoming-1565716)
2. Click on "View as HTML"
3. Note the Google error, as displayed above.

This is always reproducible; however, curiously, it doesn't appear to affect the rendering of all files via the Google viewer. We can, for example, still render Excel files successfully (as seen in request [654065](https://www.whatdotheyknow.com/request/654065/response/1561365/attach/html/3/Copy%20of%20Managed%20Station%20List%20March%202018.xlsx.html)).

**Comment by MattK1234** [comment]
Just adding a note here as the WDTK admin team have had contact from a user who was unable to access a response in `.doc` format. Presumably they didn't have MS Word or similar installed.

We added the text of the response as an annotation. This bug has caused a bit of admin work as the user would have normally been able to use the 'View as HTML' feature.

**Comment by mdeuk** [comment]
> Just adding a note here as the WDTK admin team have had contact from a user who was unable to access a response in `.doc` format. Presumably they didn't have MS Word or similar installed.
> 
> We added the text of the response as an annotation. This bug has caused a bit of admin work as the user would have normally been able to use the 'View as HTML' feature.

In this instance, it is request [658946](https://www.whatdotheyknow.com/request/how_much_uk_aid_was_sent_to_chin_3#incoming-1568604), the relevant HTML from the "view as HTML" page is:
`<iframe src="https://docs.google.com/viewer?url=%2Frequest%2F658946%2Fresponse%2F1568604%2Fattach%2F3%2Fattachment.doc%3Fcookie_passthrough%3D1&amp;embedded=true" width="100%" height="100%" style="border: none;"></iframe>`

If we scroll back to a very old request, such as [36467](https://www.whatdotheyknow.com/request/36467/response/124328/attach/html/3/Internal%20review%20of%202010%20170%20P1.doc.html), the Google viewer appears to be working without issue, which is odd.

`<iframe src="https://docs.google.com/viewer?url=https%3A%2F%2Fwww.whatdotheyknow.com%2Frequest%2F36467%2Fresponse%2F124328%2Fattach%2F3%2FInternal%2520review%2520of%25202010%2520170%2520P1.doc&amp;embedded=true" width="100%" height="100%" style="border: none;"></iframe>`

Bonkers theory: I seem to recall #410 and mysociety/alaveteli#4071 which appear to point at caching - are we seeing a code glitch which is only affecting cached files that have been generated recently?

**Comment by MattK1234** [comment]
I've just looked at 659263, which is loading OK.

I wonder if it was introduced in
https://github.com/mysociety/alaveteli/pull/5597 which would have been
deployed to WDTK recently?

**Comment by gbp** [comment]
@mdeuk @MattK1234 Thanks for reporting and your comments. We've just deployed a fix for this to stop this issue for new requests attachments.

We now need to manually expire the cache for old attachments - I'll work on that now.

**Comment by gbp** [comment]
Broken deploy was 15 days ago, within the cache directory, the command I'm using to clean this up is:
```
find . \
  -mtime -15 \
  -type f \
  -path './*/*/response/*/attach/html/**' \
  \( -exec grep -l "google.com/viewer?url=%2Frequest" {} \; -exec rm {} \; \)
```
