### ISSUE TITLE
Update wording of research section on privacy page.

### ISSUE THREAD

**Issue by MattK1234** [mysociety/whatdotheyknow-theme#685]
At https://www.whatdotheyknow.com/help/privacy#research we say:

> We would also like to share non-personal data from WhatDoTheyKnow with external researchers and are currently working on a policy which will allow us to take precautions against the release of sensitive personal information in cases where such data has been released in error. 

and

> When it is complete, our Research Data Release policy will be available on request.

This was introduced by #458 in early 2018.

Presumably the policy is complete now? We could update this.

**Comment by garethrees** [comment]
@ajparsons probably the best person to look at this.

**Comment by ajparsons** [comment]
Added to backlog list, aim to get to in June/July.

**Comment by MattK1234** [comment]
Thanks @ajparsons for this.

I think we also need to change the paragraph above, which currently says:

`We would also like to share non-personal data from WhatDoTheyKnow with external researchers and are currently working on a policy which will allow us to take precautions against the release of sensitive personal information in cases where such data has been released in error.

**Comment by ajparsons** [comment]
Yep, missed that bit. Will amend.

**Comment by garethrees** [comment]
Closed by https://github.com/mysociety/whatdotheyknow-theme/pull/713
