### ISSUE TITLE
Reversal of late calculator changes for Scottish Bodies [#672/#675]

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#689]
The [Coronavirus (Scotland) (No.2) Bill](https://beta.parliament.scot/bills/coronavirus-scotland-no2-bill) was passed by the Scottish Parliament on 20 May and received Royal Assent on 26 May.

This Act, amongst many other things, repeals the changes imposed by the Coronavirus (Scotland) Act in respect of Freedom of Information legislation.

We should now look to reverse the temporary changes enacted by #672 and #675.

**Comment by mdeuk** [comment]
Just to confirm, the Act is now published at http://www.legislation.gov.uk/asp/2020/10/enacted - sch4 part 8 refers.

**Comment by garethrees** [comment]
That's deployed now so the timelines of requests should be back to normal. As per https://github.com/mysociety/whatdotheyknow-theme/pull/675, ones made yesterday may still have the extended timeline.
