### ISSUE TITLE
No link to the FOI newsletter

### ISSUE THREAD

**Issue by ajparsons** [mysociety/whatdotheyknow-theme#692]
We run an FOI newsletter, but don't advertise anywhere on our FOI website. That newsletter is low on unique people, need to grow to get into a good platform to talking about FOI and our service more general. 

Suggested quick fix: take the sidebar bit we used to use for donations, put a link to a page somewhere that has a sign up form, see how that does. 

(e.g. the research newsletter has a little page like this https://research.mysociety.org/newsletter)

**Comment by garethrees** [comment]
An alternative, in a similar vein to https://github.com/mysociety/whatdotheyknow-theme/issues/1433 and https://github.com/mysociety/whatdotheyknow-theme/issues/1434, would be to include a front page (https://github.com/mysociety/whatdotheyknow-theme/issues/791) section:

<img width="1605" alt="Screenshot 2022-10-10 at 18 42 51" src="https://user-images.githubusercontent.com/282788/194924341-200dc676-d343-42a4-b7ed-7442acd457a4.png">

**Comment by garethrees** [comment]
Superseded by https://github.com/mysociety/whatdotheyknow-theme/issues/1570.
