### ISSUE TITLE
Consider mentioning that users should include FOI refs when following up or making an internal review request

### ISSUE THREAD

**Issue by MattK1234** [mysociety/whatdotheyknow-theme#693]
Suggestion by a user.

> I know your guidance states that requesters should include the URL of the original request, but it might be worth stating more clearly that an internal review request may not even be processed until the reference number of the original FOI has been supplied, as has happened in this case.

This raises some questions as surely the authority would be able to identify the request in question due to the unique emails etc.

Might be difficult as we don't expose the email subject to the user, sometimes references etc are stored in them so users struggle if they get asked for them.

**Comment by hsenag** [comment]
It would be interesting to see an example of an authority where this is an issue - seems primarily like a failing on the authority's part, but of course it doesn't hurt to be helpful if possible.

**Comment by MattK1234** [comment]
An example where the requester was asked for the FOI case reference is  https://www.whatdotheyknow.com/request/referrals_to_the_referred_casewo

**Comment by HelenWDTK** [comment]
This issue doesn't occur often, and on a lot of occasions, the user either can't see the case reference, or one is not provided. This might be something to revisit this if we get code changes to routinely expose the subject lines. Although a reference can help an authority find a request on their system, in most cases it'd not needed to get an authority to process your request for a review.
