### ISSUE TITLE
Improve visibility of "can I help out"

### ISSUE THREAD

**Issue by sebbacon** [mysociety/whatdotheyknow-theme#7]
Make "can I help out" a top level help page in its own right, rather than languishing at the bottom of the credits page.

**Comment by garethrees** [comment]
My immediate suggestions for this are:

* Add "Volunteer" (https://www.whatdotheyknow.com/help/volunteers) to main nav bar
* Add "Volunteer" (https://www.whatdotheyknow.com/help/volunteers) to footer

**Comment by lizconlan** [comment]
Ah, post deploy I realise that the Volunteer tab does not appear for Pro users:

Normal nav bar:

<img width="784" alt="screen shot 2018-11-05 at 12 49 15" src="https://user-images.githubusercontent.com/27760/47999076-455cfa80-e0f9-11e8-9420-e92de663c32f.png">

Pro version:

<img width="839" alt="screen shot 2018-11-05 at 12 50 35" src="https://user-images.githubusercontent.com/27760/47999118-6f162180-e0f9-11e8-9d39-59c5478e33c6.png">

**Comment by garethrees** [comment]
That's okay I think. Can't do everything for everyone. Pro's will be logged out at some point, so they'll likely see it before they sign in.

**Comment by garethrees** [comment]
I think we can consider this closed now https://github.com/mysociety/whatdotheyknow-theme/pull/530 is merged.
