### ISSUE TITLE
You're long overdue a response to your FOI request email tweaks

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#70]
Our system sends out emails with the subject: "You're long overdue a response to your FOI request". 

These messages do not explain that we rely on our users to classify their own responses in the first instance and that if they don't mark the request "successful", "refused" or whatever then they'll get one of these messages. 

We could improve the text to make this clear; and urge users to update the status of their own requests, perhaps providing the appropriate link right there in the email. 

There is a balance to be struck here between keeping the message simple, and cutting out a few emails to the team from users who can't understand why they're getting "overdue" messages when they've had a response. 

It could perhaps be done in one line an a link:

"If you have received a response please update the status of your request at:

[Link]

"

This is currently more of a suggestion for discussion arising from a few emails to team@ recently than something I necessarily want acted on - I think keeping the message simple needs to be given weight too.

**Comment by HelenWDTK** [comment]
Closing as there are no current plans to do this, and it is not a support issue that comes up often.
