### ISSUE TITLE
Privacy Notice should show version information

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#700]
We should, for transparency at a minimum, show some version information on the Privacy Notice - e.g. the date it was last revised or a version number.

If necessary, we could expand on this to include basic information about _what_ changed (e.g. we've updated our policy on x, or we've changed the name of the limited company) to aid understanding of how we seek to act in an open and transparent manner.

A good example of transparency is the ICO's own Privacy Notice which contains a [change log](https://ico.org.uk/global/privacy-notice/cha-nges-to-this-privacy-notice/) that can be referred to by the 'average user'.

**Comment by mdeuk** [comment]
> 
> 
> The authoritative history is https://github.com/mysociety/whatdotheyknow-theme/commits/master/lib/views/help/privacy.html.erb (and the "version" is the SHA of the most recent commit).
> 
> Could link to that URL?

I think that's probably fine - an idea from the Github and gov.uk policies would be to include the date the policy change takes effect in the policy itself. However, we could probably back that off to the commit history if necessary.

**Comment by garethrees** [comment]
> …include the date the policy change takes effect in the policy itself. However, we could probably back that off to the commit history if necessary.

Yeah, I'd rather not have to remember to keep dates up to date if we can avoid it.
