### ISSUE TITLE
Charity Commission links do not depreciate gracefully

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#711]
The Charity Commission for England and Wales have [updated](https://charitycommission.blog.gov.uk/2020/09/03/the-online-register-of-charities-new-and-improving/) their searchable database, and in doing so, have setup redirects from the old systems (apps and beta). However, these links do not depreciate gracefully, as the item that the user has searched for (in our case, the charity number we were passing in a URL) is not displayed, meaning the search has to be manually re-run.

This affects our "charity registration" links in the sidebar (e.g. those introduced in #582 / #614); but also affects our ["about" page](https://github.com/mysociety/whatdotheyknow-theme/tree/master/lib/views/help/about.html.erb) , which has a link to the older database on "apps".

**Comment by mdeuk** [comment]
We've previously used the structure:
`http://beta.charitycommission.gov.uk/charity-details/?regid=#{ tag_value }&subid=0`
 where #{ tag_value }) is replaced with the content of the 'charity' tag.

The _new_ database appears to not have such an easy way of creating links - however, the following does work as an example:
`https://register-of-charities.charitycommission.gov.uk/charity-search?p_p_id=uk_gov_ccew_portlet_CharitySearchPortlet&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&_uk_gov_ccew_portlet_CharitySearchPortlet_cur=1&_uk_gov_ccew_portlet_CharitySearchPortlet_delta=20&_uk_gov_ccew_portlet_CharitySearchPortlet_keywords=1076346&_uk_gov_ccew_portlet_CharitySearchPortlet_orderByCol=&_uk_gov_ccew_portlet_CharitySearchPortlet_orderByType=asc&_uk_gov_ccew_portlet_CharitySearchPortlet_priv_r_p_prevCol=&_uk_gov_ccew_portlet_CharitySearchPortlet_priv_r_p_useSession=true&_uk_gov_ccew_portlet_CharitySearchPortlet_priv_r_p_mvcRenderCommandName=%2Fsearch-results`

Changing the value of **_uk_gov_ccew_portlet_CharitySearchPortlet_keywords** to a different registration number (e.g. [269425](https://register-of-charities.charitycommission.gov.uk/charity-search?p_p_id=uk_gov_ccew_portlet_CharitySearchPortlet&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&_uk_gov_ccew_portlet_CharitySearchPortlet_cur=1&_uk_gov_ccew_portlet_CharitySearchPortlet_delta=20&_uk_gov_ccew_portlet_CharitySearchPortlet_keywords=269425&_uk_gov_ccew_portlet_CharitySearchPortlet_orderByCol=&_uk_gov_ccew_portlet_CharitySearchPortlet_orderByType=asc&_uk_gov_ccew_portlet_CharitySearchPortlet_priv_r_p_prevCol=&_uk_gov_ccew_portlet_CharitySearchPortlet_priv_r_p_useSession=true&_uk_gov_ccew_portlet_CharitySearchPortlet_priv_r_p_mvcRenderCommandName=%2Fsearch-results), [1144032](https://register-of-charities.charitycommission.gov.uk/charity-search?p_p_id=uk_gov_ccew_portlet_CharitySearchPortlet&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&_uk_gov_ccew_portlet_CharitySearchPortlet_cur=1&_uk_gov_ccew_portlet_CharitySearchPortlet_delta=20&_uk_gov_ccew_portlet_CharitySearchPortlet_keywords=1144032&_uk_gov_ccew_portlet_CharitySearchPortlet_orderByCol=&_uk_gov_ccew_portlet_CharitySearchPortlet_orderByType=asc&_uk_gov_ccew_portlet_CharitySearchPortlet_priv_r_p_prevCol=&_uk_gov_ccew_portlet_CharitySearchPortlet_priv_r_p_useSession=true&_uk_gov_ccew_portlet_CharitySearchPortlet_priv_r_p_mvcRenderCommandName=%2Fsearch-results)) produces an acceptable result, albeit, this URI is rather clunky.

It'd be preferable to link directly to the organisation page as we previously did - however, we do not appear to be able to reliably do this as the number referenced at **_uk_gov_ccew_onereg_charitydetails_web_portlet_CharityDetailsPortlet_organisationNumber** does not _always_ refer to the charity registration number - e.g. mySociety's 1076346 becomes [3078648](https://register-of-charities.charitycommission.gov.uk/charity-search?p_p_id=uk_gov_ccew_onereg_charitydetails_web_portlet_CharityDetailsPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_uk_gov_ccew_onereg_charitydetails_web_portlet_CharityDetailsPortlet_LIFERAY_SHARED_backToSearch=https%3A%2F%2Fregister-of-charities.charitycommission.gov.uk%2Fcharity-search%3Fp_p_id%3Duk_gov_ccew_portlet_CharitySearchPortlet%26p_p_lifecycle%3D1%26p_p_state%3Dnormal%26p_p_mode%3Dview%26_uk_gov_ccew_portlet_CharitySearchPortlet_cur%3D1%26_uk_gov_ccew_portlet_CharitySearchPortlet_delta%3D20%26_uk_gov_ccew_portlet_CharitySearchPortlet_keywords%3D1076346%26_uk_gov_ccew_portlet_CharitySearchPortlet_orderByCol%3D%26_uk_gov_ccew_portlet_CharitySearchPortlet_orderByType%3Dasc%26_uk_gov_ccew_portlet_CharitySearchPortlet_priv_r_p_prevCol%3D%26_uk_gov_ccew_portlet_CharitySearchPortlet_priv_r_p_useSession%3Dtrue%26_uk_gov_ccew_portlet_CharitySearchPortlet_priv_r_p_mvcRenderCommandName%3D%252Fsearch-results&_uk_gov_ccew_onereg_charitydetails_web_portlet_CharityDetailsPortlet_organisationNumber=3078648); yet, for others (e.g. [BBC CiN](https://register-of-charities.charitycommission.gov.uk/charity-search?p_p_id=uk_gov_ccew_onereg_charitydetails_web_portlet_CharityDetailsPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_uk_gov_ccew_onereg_charitydetails_web_portlet_CharityDetailsPortlet_LIFERAY_SHARED_backToSearch=https%3A%2F%2Fregister-of-charities.charitycommission.gov.uk%2Fcharity-search%3Fp_p_id%3Duk_gov_ccew_portlet_CharitySearchPortlet%26p_p_lifecycle%3D1%26p_p_state%3Dnormal%26p_p_mode%3Dview%26_uk_gov_ccew_portlet_CharitySearchPortlet_cur%3D1%26_uk_gov_ccew_portlet_CharitySearchPortlet_delta%3D20%26_uk_gov_ccew_portlet_CharitySearchPortlet_keywords%3Dbbc%2Bchildren%26_uk_gov_ccew_portlet_CharitySearchPortlet_orderByCol%3D%26_uk_gov_ccew_portlet_CharitySearchPortlet_orderByType%3Dasc%26_uk_gov_ccew_portlet_CharitySearchPortlet_priv_r_p_prevCol%3D%26_uk_gov_ccew_portlet_CharitySearchPortlet_priv_r_p_useSession%3Dtrue%26_uk_gov_ccew_portlet_CharitySearchPortlet_priv_r_p_mvcRenderCommandName%3D%252Fsearch-results&_uk_gov_ccew_onereg_charitydetails_web_portlet_CharityDetailsPortlet_organisationNumber=802052)) it works as you might expect it to.

I will drop them an email and see if we can get some assistance, as I'm somewhat reluctant to patch this only to have to patch it again once a more user-friendly URI structure becomes obvious (it appears they are [aware](https://twitter.com/ChtyCommission/status/1301875731140616195) of the issue).

**Comment by mdeuk** [comment]
The following format now appears to work:
https://register-of-charities.charitycommission.gov.uk/charity-search/-/results/page/1/delta/20/keywords/#{ tag_value }

I'll raise a PR.

**Comment by mdeuk** [comment]
> The following format now appears to work:
> [https://register-of-charities.charitycommission.gov.uk/charity-search/-/results/page/1/delta/20/keywords/#{](https://register-of-charities.charitycommission.gov.uk/charity-search/-/results/page/1/delta/20/keywords/#%7B) tag_value }
> 
> I'll raise a PR.

… and no sooner than doing that, a change has happened. 😅

Interestingly, the original format (from the beta) website is now also working. This potentially changes the fix outlined in #732, depending on the strategy we wish to use.

For example: mySociety's entry at http://beta.charitycommission.gov.uk/charity-details/?regid=1076346&subid=0
becomes https://register-of-charities.charitycommission.gov.uk/charity-details/?regid=1076346&subid=0

It's pleasing to see that the Charity Commission have been able to do this - they had alluded to a fix being forthcoming in an email we received on 6th October (which, for some reason, was archived in the team@ mailbox).

### What this changes (and why we are doing things differently)

The proposed fix in #732 works on the basis that we direct our users to a listing of charities that match the tag we are passing (the charity number); rather than directly to an individual entity (as we previously were). This could be a clunky workaround.

I think we are possibly serving our users best by using the format in the PR as this allows for the display of a listing of all entities that exist under the charity registration number (there can be several, e.g. [British Council](https://register-of-charities.charitycommission.gov.uk/charity-search/-/results/page/1/delta/20/keywords/209131) ha[s/d] 3).

We don't always know that the entity we list will be the 'main' part of the charity registration (e.g. the part that is designated as 'subid' 0), therefore, directing users to a pre-populated search for the charity number seems like a reasonable compromise. It is possible that 

### Proposed action

I propose continuing as intended, unless others wish to discuss an alternate strategy… i'll update the PR to this effect.

**Comment by garethrees** [comment]
Seems like a good approach to me given the nuances mentioned above, so I've merged #732. We can always update it again if we think of a better idea.
