### ISSUE TITLE
Create a whatdotheyknow.com/scotland page

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#715]
Similar to #416 - we should have a page which shows a list of public bodies in Scotland, making it easy for our users to target specific bodies, and to understand any specific nuances in local legislation (e.g. the application of FoISA, and the inclusion of bodies that aren't covered under the analogous FoIA).

As a first step, I will post a patch to create a redirect based on the "scotland" tag, as has been done elsewhere.

**Comment by mdeuk** [comment]
If I was nitpicking I would also add /alba, however this feels a little moot at this, stage given we currently have no Gaelic translations available. 🏴󠁧󠁢󠁳󠁣󠁴󠁿

**Comment by garethrees** [comment]
Added redirect in a746bbf4d5afb89f80c26d9b787d26ac1da8f767.
