### ISSUE TITLE
Create a whatdotheyknow.com/wales and /cymru page

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#716]
Similar to #416 - we should have a page which shows a list of public bodies in Wales, making it easy for our users to target specific bodies within Wales. We should include the Welsh language version for completeness.

As a first step, I will post a patch to create a redirect based on the "wales" tag, as has been done elsewhere.

**Comment by garethrees** [comment]
Added redirect in a746bbf4d5afb89f80c26d9b787d26ac1da8f767.
