### ISSUE TITLE
Full Name Note on Sign Up

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#72]
We have a "Your name" field on the "Sign Up" form. 

There's a note saying:

"If you are thinking of using a pseudonym, please read this first. " (linked to the relevant bit of our help pages)

However a user has pointed out we don't prompt users that they might want to sign up with their full name - not just their first name for example. 

The text of the note could perhaps be improved.  Ideas:
- "If you considering not using your full name, please read this first. " 
- "Advice on choosing a name"  (linked to the help)

See also #15 which proposes an alert / warning if someone signs up with just one name (though we need to allow it as some people really do only have one name!)

**Comment by garethrees** [comment]
Linking to https://github.com/mysociety/alaveteli/issues/6284 (which replaced #15).

**Comment by RichardTaylor** [comment]
Suggestion from FOI officer:

"changing the wording of your name field on the sign up form to state ‘your full real name’ or even just ‘your full name’, "

However we do want to enable (and perhaps in some cases encourage) the use of our service by whistleblowers and journalists opting to use false names.

**Comment by garethrees** [comment]
Closing in favour of https://github.com/mysociety/alaveteli/issues/6284
