### ISSUE TITLE
Implement technical changes to reduce volumes of personal correspondence sent to key bodies

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#722]
Although the majority of our users utilise WDTK to make transparency requests to public bodies, there are occasions where users are utilising WDTK as a method of contact for personal correspondence, e.g. to request information about their own social security benefits, their driving licence, or their biometric residence permit.

We have already implemented changes under #554 which adds questions to the request form for the Home Office. This has been moderately successful, however there are still a good number of requests which have to be manually removed by WDTK administrators afterwards.

A reasonable mitigation may be to include, where possible, a contact address for the public body, so that the user is signposted elsewhere.

**Comment by mdeuk** [comment]
Suggested bodies to look at:

Department for Work and Pensions `(dwp - 24)` 
HM Revenue and Customs `(hmrc - 592)`
Driver and Vehicle Licensing Agency `(dvla - 719)`
Driver and Vehicle Agency (Northern Ireland) `(dvani - 3300)`
HM Passport Office `(hm_passport_office - 590)`

We should also look at adding the email address for the Home Office `(home_office - 7)` into the existing codebase.

**Comment by mdeuk** [comment]
> We should also look at adding the email address for the Home Office `(home_office - 7)` into the existing codebase.

Added public.enquiries@ email address in d88e588; I'll PR this in due course.

**Comment by garethrees** [comment]
> Added public.enquiries@ email address in [d88e588](https://github.com/mysociety/whatdotheyknow-theme/commit/d88e588ac2969de9d5408dd072d214d97af3ca07); I'll PR this in due course.

Merged in 5f630c5.

**Comment by mdeuk** [comment]
Of note, our colleagues over in Australia have a nice generic ["stop and think" speedbump](https://www.righttoknow.org.au/new/nsw_police_force) that they deploy. The technical implementation is in [/views/requests/new.html.erb](https://github.com/openaustralia/righttoknow/blob/ace85f8376e2a753f89daf4e223d62e3b2dce5a4/lib/views/request/new.html.erb#L233) and **_appears_** to be based on how many hidden requests a body has - nicely done!

@FOIMonkey has suggested reaching out to find out if this seems to be effective at reducing takedowns.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
