### ISSUE TITLE
Add business improvement districts

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#726]
Currently just two business improvement district bodies are listed on WhatDoTheyKnow:

https://www.whatdotheyknow.com/body?tag=BID

We have a public spreadsheet for collecting more contact details:

https://docs.google.com/spreadsheets/d/1GGKWdrTIllDHetZO8K62GiYkD-2UL1jVcjfSJ_yu2zk/edit?usp=sharing

Some of these bodies will be subject to FOI, others might not be but can list them all as they are all effectively raising and spending taxes so have the character of a public body. 

>A Business Improvement District is a defined area in which a levy is charged on all business rate payers in addition to the business rates bill.

>A Business Improvement District is managed by a Business Improvement District body. This is often a private company but can be a partnership with the local authority. Most Business Improvement District bodies are not-for-profit companies.

https://www.gov.uk/guidance/business-improvement-districts

**Comment by mdeuk** [comment]
> Currently just two business improvement district bodies are listed on WhatDoTheyKnow:
> 
> https://www.whatdotheyknow.com/body?tag=BID
> 

Just for reference, I have changed the tag on these bodies from "BID" to "bid" - tags are currently case sensitive so this can occasionally have some unpredictable side effects when linking bodies.

A feature request to consider options re case sensitivity is open at: https://github.com/mysociety/alaveteli/issues/5307

**Comment by RichardTaylor** [comment]
Link to https://github.com/mysociety/alaveteli/issues/3477

**Comment by garethrees** [comment]
> Perhaps these could be the first set of bodies we add en-masse without email address?

I'd support this for two reasons:

1. We have an existing workflow that encourages users to find a missing email address when they attempt to make a request to the body.
2. We can always seek to compile the email addresses in a single batch via a spreadsheet and use the CSV import to _update_ (rather than add) the bodies.

**Comment by RichardTaylor** [comment]
>We have promoted the spreadsheet via a site banner. This has got a few updates made but not many.

Updates did keep dripping in slowly, both via email and the spreadsheet, and we've been pointed to what purports to  be a   comprehensive current list for Wales at

https://gov.wales/business-improvement-districts/business-improvement-districts-in-wales 

which a non-core volunteer has used as the basis of work to find contact details, websites etc.

**Comment by RichardTaylor** [comment]
Note there are "Industrial BIDS" and there is a UK list of them in a document dated 2019 at:

https://democracy.blaenau-gwent.gov.uk/Data/Executive%20Committee/201909261300/Agenda/att10970.pdf

**Comment by RichardTaylor** [comment]
Upload from spreadsheet complete. 

301 bodies now listed at https://www.whatdotheyknow.com/body?tag=bid

We know some of these will be defunct, and many lack email addresses, it's a best effort based on recent crowdsourcing and our listing of these bodies will continue to improve. We'll continue to seek contact addresses and respond to reports of errors.

**Comment by RichardTaylor** [comment]
Could review https://en.wikipedia.org/wiki/List_of_business_improvement_districts_in_London to cross check with our database.

**Comment by RichardTaylor** [comment]
>Could review https://en.wikipedia.org/wiki/List_of_business_improvement_districts_in_London to cross check with our database.

Looks like, from a sample, the spreadsheet upload generally covered these, but there may be some missing and some email addresses to add, these might be worth focusing on. [Spreadsheet to track progress](https://docs.google.com/spreadsheets/d/1tejPY6BltJw6_k8Qg9zQj-UEC0UluqnrvAiiqV1-wew/edit#gid=0).


>Note there are "Industrial BIDS" and there is a UK list of them in a document dated 2019 at:
https://democracy.blaenau-gwent.gov.uk/Data/Executive%20Committee/201909261300/Agenda/att10970.pdf

It looks, from a sample, as if we the spreadsheet upload covered these.  [Spreadsheet for reviewing](https://docs.google.com/spreadsheets/d/1Amp-RKjD04xdn7gIuhRfUwT5MqJM_lwULTTr6ciVJAs/edit#gid=0). 

It would be ideal to do more, but fundamentally this task is now done.

**Comment by RichardTaylor** [comment]
When drafting the blog (#1125) on this @MyfanwyNixon noted the practice (which I wasn't aware of) on WriteToThem:

>To date we’ve generally avoided listing bodies without email addresses, although this is a close copy of a model that's worked well on mySociety's WriteToThem site for many years  — where someone wants to email their MP or councillor and we don't have a contact, we will ask users to see if they can find the required details.
