### ISSUE TITLE
Verify the domain for Facebook

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/whatdotheyknow-theme#727]
More information at https://www.facebook.com/business/m/verify-your-domain and https://developers.facebook.com/docs/sharing/domain-verification

After a brief email discussion we've decided it's probably beneficial to do this so that we're regarded as valid by Facebook - and apparently it also gives us a bit more control over how posts are displayed on there.

**Comment by garethrees** [comment]
@sagepe Could you take this? TL;DR is that we need to add a TXT DNS record.

**Comment by sagepe** [comment]
@myf - you can add the domain into Facebook Business Manager as per the instructions [here I think](https://developers.facebook.com/docs/sharing/domain-verification/verifying-your-domain), then send me a DM with the DNS verification code ("Add this TXT record in your DNS configuration").

Also, I see that the internal wiki page for Facebook includes some notes on Business Manager, but these look a bit out of date and mention former employees with admin access, so we should check this and update the page.

**Comment by MyfanwyNixon** [comment]
Thanks! I've amended the Wiki to reflect the current admins (we'd removed ex-colleagues but not reflected this on the Wiki) and I've sent Sam the code.

**Comment by sagepe** [comment]
DNS updated with the code - this may take a few minutes to be fully visible externally, but when it is hopefully this will be reflected in the Business Manager site and this ticket can be closed.

**Comment by MyfanwyNixon** [comment]
Yes, all verified - thanks Sam!
