### ISSUE TITLE
Add a "ICO officer questions" help page

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#729]
We have a "FOI officer questions" page at:
https://www.whatdotheyknow.com/help/officers

**Comment by garethrees** [comment]
First step here is to shape the work. What do we want to say here?

* Should give a very, very brief overview, linking out to more specific sections, of
  * What is WDTK and what is it for?
  * How it works (requests in public, etc)
  * How we moderate (reactive)
* Volunteers will have best knowledge of specific issues that arise with ICO interactions

**Comment by mdeuk** [comment]
Question: Are we positioning this page as a (basic) primer for ICO case officers who are:

1. Looking to understand how WDTK works from a FOI/EIR perspective
2. Looking to understand how we handle data subjects information (e.g. DPA / GDPR matters)

… or some compilation of the two?

If we are focussing on 1 it may be beneficial if we ensure any references to legislation include the relevant Scottish legislation, since the page will likely also be of use to case officers at OSIC.

**Comment by MyfanwyNixon** [comment]
Oh good point, thanks Martyn. Definitely point 1; and as Gareth says, 'Volunteers will have best knowledge of specific issues that arise with ICO interactions' - so I'm happy to take your steer on whether you think we should include point 2.

**Comment by garethrees** [comment]
> Question: Are we positioning this page as a (basic) primer for ICO case officers who are:
> 
> 1. Looking to understand how WDTK works from a FOI/EIR perspective
> 2. Looking to understand how we handle data subjects information (e.g. DPA / GDPR matters)
> 
> … or some compilation of the two?

I think we can mostly summarise the first point, linking to existing pages where appropriate. That might also be true of point 2, but I think the key is having a summarisation/index of links that's very directed at the specific situations where we communicate with the ICO.

Seems like point 2 is a recurring issue, so worth including.

**Comment by MyfanwyNixon** [comment]
Thanks @RichardTaylor and @mdeuk for your input. [First draft here](https://docs.google.com/document/d/1kI6fOHAK1SIS8zUC3CzTMx3XDQz5QiCqtJwtEeiWlQQ/edit#), which I expect will undergo some revision! Fill your boots.

**Comment by MyfanwyNixon** [comment]
Thanks for the comments all, I've amended accordingly and I think this is probably ready to go live, unless anyone wants to address the two points remaining in my own comments.

**Comment by MyfanwyNixon** [comment]
Done! Thanks all.

**Comment by garethrees** [comment]
@MyfanwyNixon thanks so much! I'll have a proper read of this over the next couple of days and we'll schedule it in to get it HTML-ified!
