### ISSUE TITLE
Collect all places that someone can submit an inbound email to the support inbox

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#741]
A subtask of https://github.com/mysociety/whatdotheyknow-theme/issues/740

**Comment by garethrees** [comment]
## Contact Form

![contact-form](https://user-images.githubusercontent.com/282788/101157171-936ac200-3621-11eb-932e-1bea40b805bc.jpg)

* [`/help/contact`](https://github.com/mysociety/whatdotheyknow-theme/blob/master/lib/views/help/contact.html.erb) – here we have a few unfolding options to direct people towards help pages before they submit a query.
* [`/cy/help/contact`](https://github.com/mysociety/whatdotheyknow-theme/blob/master/lib/views/help/contact.cy.html.erb) – this uses a simplified contact form with no unfolding of options.

The Welsh version accounted for only 0.51% of visits in November 2020, so doesn't seem like a huge source of messages.

![Screenshot 2020-12-04 at 11 09 53](https://user-images.githubusercontent.com/282788/101156935-42f36480-3621-11eb-81de-30e9d0445615.png)

**Comment by garethrees** [comment]
## Public Body Change Requests

We have a situation-specific structured contact form for adding and updating public bodies.

![change-request](https://user-images.githubusercontent.com/282788/101157457-11c76400-3622-11eb-8fc3-915c0c37dafb.jpg)

* [Change request form](https://github.com/mysociety/alaveteli/blob/0.38.3.0/app/views/public_body_change_requests/new.html.erb#L5)
  * `/change_request/new`
  * `/change_request/:body_url_name`

There's an existing discussion around whether to require sign-in before submitting these forms (https://github.com/mysociety/alaveteli/issues/5957).

In November 2020, change requests accounted for a roughly equal amount of inbox submissions.

![Screenshot 2020-12-04 at 11 19 20](https://user-images.githubusercontent.com/282788/101157840-a92cb700-3622-11eb-988f-62f65dea2640.png)

**Comment by garethrees** [comment]
## Banned Users

![banned-users](https://user-images.githubusercontent.com/282788/101158782-3c1a2100-3624-11eb-9718-034cccac0658.jpg)

When a user is banned, we [direct them to the contact form](https://github.com/mysociety/alaveteli/blob/0.38.3.0/app/views/user/banned.html.erb#L23-L24) when they try to make a request.

On their profile pages, [we don't give them any option to contact us](https://github.com/mysociety/alaveteli/blob/0.38.3.0/app/views/user/show/_show_profile.html.erb#L64-L79).

Some old ban messages include the user support contact address. It wouldn't be difficult to replace this with a link to the contact form.

```sql
SELECT COUNT(*) FROM users WHERE ban_text ILIKE '%team@whatdotheyknow%';
 count
-------
    58
```

**Comment by garethrees** [comment]
## Reports

Signed in users can [report](https://github.com/mysociety/alaveteli/blob/0.38.3.0/app/mailers/request_mailer.rb#L66-L86) an entire request or specific parts (outgoing messages, incoming messages, and comments).

![report-content](https://user-images.githubusercontent.com/282788/101163402-776c1e00-362b-11eb-9350-494c5ec9eb6f.jpg)

Views to report pages don't seem that common – about 10% of general contacts.

![Screenshot 2020-12-04 at 12 22 15](https://user-images.githubusercontent.com/282788/101163354-67543e80-362b-11eb-99fe-1f1b6bad7515.png)

## Classifications

Similar to reporting, some classifications result in [a message](https://github.com/mysociety/alaveteli/blob/0.38.3.0/app/models/info_request.rb#L1017-L1027) being sent to site admins.

<img width="1792" alt="Screenshot 2020-12-04 at 12 25 05" src="https://user-images.githubusercontent.com/282788/101163732-ecd7ee80-362b-11eb-97dc-86613da3c04e.png">

These don't seem to account for too much mail:

![Screenshot 2020-12-04 at 12 27 18](https://user-images.githubusercontent.com/282788/101163924-4809e100-362c-11eb-8415-d902faae363e.png)

![Screenshot 2020-12-04 at 12 27 42](https://user-images.githubusercontent.com/282788/101163922-46d8b400-362c-11eb-8c9c-3c98dfd9276d.png)

**Comment by RichardTaylor** [comment]
>These don't seem to account for too much mail

From the support mailbox over the two year retention period I'm seeing:

"FOI response requires admin (attention_requested)", 1,418 threads (9.90% of total support mail) 
"FOI response requires admin (error_message)", 595 threads (4.15%  of total support mail)

That's by searching for the quoted phrase and reporting the thread count.

**Comment by garethrees** [comment]
> > These don't seem to account for too much mail
> From the support mailbox over the two year retention period I'm seeing…

Yeah, absolute numbers probably fairly high, but proportionally lower compared to other areas.

I'm going to hide these two messages to keep the thread tightly focused on the collection of data. We can discuss things like absolute volumes and which sources are most difficult to deal with, etc after we've built up a fuller picture.

**Comment by mdeuk** [comment]
Just to note: we get direct email to support@ for some GDPR requests (usually made using a third party automated tool) - this is the email address advertised on our [Facebook page](https://www.facebook.com/whatdotheyknowcom), but it's unclear if that's where the address came from.

We also get direct mail in response to Track messages - however, we could perhaps re-engineer those so as to be sent from a do-not-reply email address (similar to TWFY's notifications).

**Comment by garethrees** [comment]
We now have "Source" labels in the inbox, and I think more or less everything comes via a "structured" route rather than direct email, so closing this.
