### ISSUE TITLE
Reconsider notes on DWP page

### ISSUE THREAD

**Issue by MattK1234** [mysociety/whatdotheyknow-theme#745]
Moved in from the support inbox as a ToDo.

https://www.whatdotheyknow.com/body/dwp

DWP page notes give a link to an INF2 form from 2017 - Consider if to replace that with a link to - https://www.whatdotheyknow.com/request/the_inf2_form (or similar newer version of the form)

> As far as I can see, it's the same form; however perhaps a newer date would be more "attractive" for our users.
> 
> Ideally, we'd want to refresh the information text on that body page - it is rather unwieldy, and I suspect a fair proportion of our users don't read it, meaning we see a number of requests that relate very specifically to an individual's own circumstances. Some of this content could be special category information as it can relate to a person's health and wellbeing.
> 
> We do have a ticket for adding an interstitial to this body (similar to the version used for Home Office requests[1]) - #722. This may help us to stop some of these duplicate requests. Any feedback is welcome on this - e.g. what specific information we might want to include.
> 
> On the point of the DWP - we should consider whether or not we are serving our users best interests by listing the "Child Support Agency" and "Child Maintenance Options" separately. At one point these bodies were executive agencies, similar to JobCentre Plus, however this no longer appears to be the case.
> 
> In some cases we're seeing users inadvertently make requests which are being considered vexatious [2,3,4] as they are sending to CSA, CMO, and DWP separately - without realising they are actually the same entity.
> 
> This creates confusion, and I wonder if we'd be better serving our users if we mark those bodies as defunct and place a note suggesting that their request be made to the DWP instead. We could place the "brand name" of those entities in the information text for the DWP to tie things together.
> 
> [1] https://www.whatdotheyknow.com/new/home_office (view in incognito / private browsing)
> [2] https://www.whatdotheyknow.com/request/managing_information_disclosure_27
> [3] https://www.whatdotheyknow.com/request/managing_information_disclosure_28
> [4] https://www.whatdotheyknow.com/request/managing_information_disclosure_55

**Comment by mdeuk** [comment]
I thought that text looked familiar 😃

Linking to #722 since I think there is a parallel between both, in essence we probably want to take a two prong approach - have help text that is up to date, and use the interstitial to direct accordingly.

**Comment by HelenWDTK** [comment]
Found a 2022 release: https://www.whatdotheyknow.com/request/leaflet_inf2_3#incoming-2145280
