### ISSUE TITLE
Advise users to explain or avoid acronyms and avoid ambigious terms

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#749]
On the help page at

https://www.whatdotheyknow.com/help/requesting#responsible

we could add a bullet:

* **Avoid acronyms and ambiguous terms.**  Acronyms and jargon whose meaning might appear obvious to you may not be understood by officers receiving your request. Consider expanding acronyms, explaining highly technical terms, and pre-empting potential requests for clarification. 

That's just a first draft, it might be OK, but I'm happy for it to be improved.

**Comment by mdeuk** [comment]
> we could add a bullet:
> 
>     * **Avoid acronyms and ambiguous terms.**  Acronyms and jargon whose meaning might appear obvious to you may not be understood by officers receiving your request. Consider expanding acronyms, explaining highly technical terms, and pre-empting potential requests for clarification.

This wording looks good to me - @RichardTaylor I've raised a PR in #762, does it do what you are looking for?

**Comment by mdeuk** [comment]
Fixed in #762 and merged as 7e9e407
