### ISSUE TITLE
use the term "Public Information request" instead of "Freedom of Information request"

### ISSUE THREAD

**Issue by hsenag** [mysociety/whatdotheyknow-theme#75]
Some requests made through WDTK are to bodies not subject to any information law, or are actually EIR requests. The term "Freedom of Information" is closely linked to the specific acts (FOIA/FOISA). 

We've discussed instead using a more neutral term in emails to authorities - so I guess this would mean changing the subject line of the outgoing emails. The "to" line also says "FOI requests at {authority}", and the footer mentions "Freedom of Information" and "FOI" a couple of times, but they probably don't need to be changed.

The term "Public Information" is intended to make it clear we're not for DPA requests or any other private information requests.

There was general agreement about this idea when we discussed it on team@, though as I write this ticket I'm now wondering if it will harm the common case of a FOI request by making authorities less likely to realise that they need to consider it under the legislation.

**Comment by RichardTaylor** [comment]
See also https://github.com/mysociety/alaveteli/issues/5039

**Comment by garethrees** [comment]
Closing in favour of https://github.com/mysociety/alaveteli/issues/5039.
