### ISSUE TITLE
Add version information to House Rules

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#754]
We should, for the purposes of transparency, provide some version information on the House Rules, to indicate when they were last changed, and what that change might have been.

For practicality purposes, I'd propose that we use a solution in a similar vein to that of the Privacy Notice (#700), piggybacking off our existing version control logs.

**Comment by mdeuk** [comment]
Draft pushed in PR #755

**Comment by garethrees** [comment]
I've made a more generic version of #755 in #761 – see what you think!
