### ISSUE TITLE
Drop offer to make requests on a user's behalf

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#756]
Currently:

https://www.whatdotheyknow.com/help/privacy

states:

>You may, if you are really stuck, ask us to make the request on your behalf. Please contact us with a good reason why you cannot make the request yourself and cannot ask a friend to. 

Those sentences could just be deleted and what's left could still make sense. 

Members of the admin team now very rarely make requests on others' behalf.  We point to the option, already covered in the help pages, of making a request under a pseudonym.

**Comment by sallytay** [comment]
A note that this has come up again - I think it is fair to say that at the moment the admin team don't have the resources to do this so it would be useful to remove from the site so as to manage users expectations.

Sally

**Comment by HelenWDTK** [comment]
Closing this, as I and others have done this recently, so it is something that we do still offer.
