### ISSUE TITLE
Clarify statement on privacy consequences of registering with the site

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#757]
A correspondent has suggested the sentence:

>This data (your name, email address, alert subscriptions) is not used for any purpose other than the running of the site and will not be shared externally.

at

https://www.whatdotheyknow.com/help/privacy#consequences_registering

isn't clear in the context of the fact a user profile page containing a user's name is created and published. 

This is made clear in earlier statements saying: "Users with accounts gain a public profile page on the site ... Your profile page displays: Your name  ...." but it is perhaps contradicted by the later sentence, depending on how it is parsed.

**Comment by mdeuk** [comment]
Linking to #787 - there's a common issue here, so we might be able to fix both at the same time.

**Comment by HelenWDTK** [comment]
Closed as complete: https://www.whatdotheyknow.com/help/privacy#consequences_registering
