### ISSUE TITLE
Missing id attribute on help page, breaking link to page section

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#765]
The heading "Removal of public servants’ personal information from responses" at https://www.whatdotheyknow.com/help/privacy  is associated with a link:

https://www.whatdotheyknow.com/help/privacy#takedown

however there is no associated id="takedown" in the associated h4 tag to make it work.

**Comment by mdeuk** [comment]
This will be fixed once #758 is pushed.
