### ISSUE TITLE
Mention backpaging on the help pages

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#767]
The best place for this appears to be a new subheading at the end of the section titled: "Removal of information" at https://www.whatdotheyknow.com/help/how

**Backpaging** 

Administrators can "backpage" a request thread, this means the page is accessible to those who have the direct link to it, but it is not included in lists of requests or search results on the site.  This is similar to YouTube's "unlisted" or GoogleDoc's "anyone with the link" accessibility settings. When a request on WhatDoTheyKnow is "backpaged" meta-tags are added to the header of the request page, and linked attachments, to ask external search engines not to index the material.  This feature is rarely used, but can help us continue to publish material we might otherwise have to remove. Backpaging reduces the impact of our publication, it can, for example, be used to make it more likely that our interests in processing and publishing material outweigh any negative impacts on those whose personal information is involved.

**Comment by mdeuk** [comment]
This is now written up on pull request #781 - please check that I haven't missed anything 😃.

**Comment by MattK1234** [comment]
Done in PR #781. Looks like everything has been covered so closing this issue.
