### ISSUE TITLE
Improve the public notes on our page for the National Archives

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#772]
https://www.whatdotheyknow.com/body/national_archives

**Comment by RichardTaylor** [comment]
I've given this an initial attempt, there may be more we can do.

**Comment by confirmordeny** [comment]
I have made some edits today to say a bit more about what the National Archives is and I have reordered some content. I will close the ticket. A new ticket can be opened if any specific improvements are identified.

**Comment by RichardTaylor** [comment]
Further tweaks prompted by the closure of this ticket:

* Added the tag [`non_ministerial_department`](https://www.whatdotheyknow.com/body/list/non_ministerial_department) (not strictly a notes issue)
* Generalised some references to FOI just requests for information
* Noted that requests for information will be dealt with in consultation with the originating department. 
* Noted requests for Environmental Information shouldn't be rejected under "accessible by other means" as that's only a FOI exemption.  
* Mentioned the body runs Legislation.gov.uk
