### ISSUE TITLE
Help page changes - requests for personal information and requests for information relating to deceased people

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#774]
The statement 

>Use WhatDoTheyKnow only to request specific information, not for general correspondence with public authorities, and certainly not for correspondence about your own personal circumstances. 

at 

https://www.whatdotheyknow.com/help/house_rules

has been interpreted too broadly as forbidding requests on subjects a requester has any personal connection to.  Actually we want to permit and encourage requests related to people's personal circumstances eg. if someone has made an application to a public body it's reasonable to make a FOI request for policy/process under which that application is assessed. 

Proposed replacement:

>Use WhatDoTheyKnow only to request specific information, not for general correspondence with public authorities, and certainly not for personal correspondence. 

=======

>Do not use WhatDoTheyKnow to request your personal information from authorities. You should request this information privately via a Subject Access request, a procedure that is distinct from a Freedom of Information request.[ See advice on this from the Information Commissioner’s Office.](https://ico.org.uk/for-the-public/personal-information/) 

Propose generalising: 

>Only use WhatDoTheyKnow.com to request information which anyone could expect to obtain if they requested it. If you have a specific right to information, for example because you are seeking your own personal information, then you should correspond privately with the public body concerned to request it. Requests for your own personal information are known as Subject Access requests and [the Information Commissioner has published advice on making such requests](https://ico.org.uk/for-the-public/personal-information/). 

(We're seeing, for example, requests for military service records, and health records, where next-of-kin have rights to more information than the general public). 

========
At
https://www.whatdotheyknow.com/help/requesting
Propose a new heading following the section headed "Can I request information about myself?"

>**Can I request information about a deceased person?**
>When seeking information relating to a deceased person please carefully consider if a Freedom of Information request via WhatDoTheyKnow.com is appropriate and think about the potential impacts of making the request, and receiving a response, in public.
>WhatDoTheyKnow.com is only for making requests for information which anyone could expect to obtain if they requested it. There are some laws, and procedures, which give certain people special rights to information, such as the <a href="https://www.nhs.uk/common-health-questions/nhs-services-and-treatments/can-i-access-the-medical-records-health-records-of-someone-who-has-died/">Access to Health Records Act (1990)</a> and the <a href="https://www.gov.uk/guidance/request-records-of-deceased-service-personnel">Ministry of Defence procedure for accessing records of deceased service personnel</a>. Where the requester has a special right to the information being sought requests should be made privately and directly and not via WhatDoTheyKnow.com.

**Comment by RichardTaylor** [comment]
Update https://www.whatdotheyknow.com/help/how adding a new heading under the section headed: **Copyright**

>**Removal of information on compassionate grounds**
>On rare occasions, in exceptional circumstances, an editorial decision may be taken to remove requests, and/or responses, on compassionate grounds. Such cases are treated sensitively on a case-by case basis. Where requests relate to deceased individuals we have a presumption towards removing material on compassionate grounds, where the request is by a family member or friend who may not have considered the consequences of using our service.

**Comment by mdeuk** [comment]
I've consolidated all of these changes into pull request #780  - can you review and confirm all is as expected? 😃

**Comment by RichardTaylor** [comment]
Closing as these as the changes have been made and are live on WhatDoTheyKnow
