### ISSUE TITLE
Review and tidy up the canned responses in the support mailbox

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#777]
* Are there duplicates?
* Can the titles be improved and made more consistent?
* Do we need a Wiki-Page listing them and explaining when to use them (or is that instruction creep and another thing to maintain)?
* Are the templates appropriately generalised
* Is it clear enough where material needs to be added/removed from templates when using them?

**Comment by mdeuk** [comment]
Adding to the list:

- do the templates actually make sense to a non technical user? Are we using **plain English**?
- are we consistent on our formatting?
- can we automate any of the fill-in parts?

**Comment by RichardTaylor** [comment]
>Is it clear enough where material needs to be added/removed from templates when using them?

On this point I think its very useful to have templates which work in their initial generalised form [but can be tailored to specific circumstances]. 

I don't think we can have notes on where it's often useful to add a bit more information and templates which can be sent without modification. We can't do that within one template. Those two things are both desirable but incompatible.   Having a standard version and one ready for tailoring is perhaps an option but the number of templates and challenges with maintaining them, and just the complexity starts rapidly increasing. 

Some types of template we always customise - so having notes within those on where to add material is useful - and key to how we use them.

**Comment by MattK1234** [comment]
We do have a Wiki page already containing a copy of the canned responses but it is quite outdated now.

We created it after they all accidentally got deleted (because they appear as drafts on mobile/IMAP. Is it still worth keeping a backup somewhere. We'd need to ensure to keep it up to date though otherwise it is of limited value.

**Comment by sallytay** [comment]
Taking on board the comments above and as one of my induction tasks - I've started a full review of the canned responses to be updated within in the inbox and then also all added to the Wiki page.

I've detailed them all, along with proposed changes in this document https://docs.google.com/document/d/1nLr9B4HQ3_JbYmToK6pVBs7yBou83mmGmAojbFnmFGU/edit# that everyone should have access to.

I'm planning on starting the duplicate removal and minor updates next week. 

If you want to add any suggestions/comments etc on the documents please do.

Sally

**Comment by sallytay** [comment]
Thank you for your comments on the document of proposed changes.
I'm going to start actioning some of these today, although it will be a bit of lengthy process.

I'm logging everything I do on the document and will update the wiki in due course

If as a result of this you have trouble finding anything or think something is missing please let me know and I'll amend.

Sally

**Comment by sallytay** [comment]
Request to add a template for a Data breach, where a company send data to the support inbox. Will action as part of this review

Sally

**Comment by sallytay** [comment]
Update -  more updates were made to the templates, pre Christmas. Final stage of major redrafting and new responses planned for this sprint

Sally

**Comment by sallytay** [comment]
Update:

I've now reviewed and updated most of the original canned responses and made the changes in the inbox.

As you'll see on the review master, there are still some TO DOs which I hope to have completed by the end of the week
https://docs.google.com/document/d/1nLr9B4HQ3_JbYmToK6pVBs7yBou83mmGmAojbFnmFGU/edit#

I've started a record/backup of all the current canned responses here: (not those on the TODO list not yet added)
https://docs.google.com/document/d/1oHTp3VOJuRjVzJPjeIQdCtg0kdPuCsz6x4l5khPyYy0/edit#

I will be adding this link to the new look Wiki page for canned responses, along with an explanation of what each response should be used for

In the meantime if you think of any more 'new responses' can you raise a new ticket for them, or of course feel free to add them yourself in the inbox if you can just let me know so I can update the Wiki and back up list.

Sally

**Comment by sallytay** [comment]
All actions that were identified as part of this review have now been completed, along with the wiki being updated at https://wdtkwiki.mysociety.org/wiki/Canned_responses#Canned_responses

I believe this also resolves ticket https://github.com/mysociety/whatdotheyknow-theme/issues/644

My proposal would be to close this ticket at #644 with new tickets created for request for new canned responses as required?

Sally

**Comment by sallytay** [comment]
Actions on this ticket have been completed, the remaining actions are detailed on ticket #1060
