### ISSUE TITLE
Improve advice notes on pages for coroner's offices. 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#779]
WhatDoTheyKnow lists coroner's offices:

https://www.whatdotheyknow.com/body/list/coroners_office

We could usefully note:

>Records of inquest should be available on request. [The Chief Coroner's guidance](https://www.judiciary.uk/wp-content/uploads/2020/08/guidance-no-17-conclusions.pdf) states:

>"The Record should normally be treated as a public document. Most if not all of the details on it will have been read out in open court and as with documents ‘in the possession of a coroner in connection with an investigation’ it may be provided to ‘any person’ unless they are not ‘in the opinion of the coroner ... a proper person to have possession of it’ (which should be rare)"

>The law, [The Coroners (Investigations) Regulations 2013](https://www.legislation.gov.uk/uksi/2013/1629/regulation/27/made), states:
>The coroner may provide any document or copy of any document to any person who in the opinion of the coroner is a proper person to have possession of it. 

>Some material held by coroners will only be available to certain classes of requests such as "interested parties" and "next of kin". Requests for information on the basis the requester has a special right to the material due to their status as, for example, an interested party or next of kin, should not be made via WhatDoTheyKnow.com. 

Related issue:
* Show notes based on tag https://github.com/mysociety/alaveteli/issues/387 

The Chief Coroner's guidance goes on to discuss access by inspection .. I think that's fine to omit as it doesn't apply to directly WhatDoTheyKnow - though the section: "the signatures of jurors should be redacted. Similarly, other details, such as the address of the deceased, may be redacted where there is good reason for doing so. Details should not be redacted unless it is in the public interest to do so" would appear to remain relevant.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
