### ISSUE TITLE
Review and improve coverage of schools in Wales

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#783]
Coverage may be poor as recent updates have focused on England

**Comment by RichardTaylor** [comment]
We've just added 

https://www.whatdotheyknow.com/body/ysgol_gyfun_gwyr

on request. 

It is listed at 

https://get-information-schools.service.gov.uk/Establishments/Establishment/Details/401773

It might be worth comparing our database with the official register on that site.

**Comment by HelenWDTK** [comment]
Closing as complete via #1010
