### ISSUE TITLE
Review and improve coverage of schools in Scotland

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#784]
Coverage may be relatively poor as recent updates have focused on England

**Comment by mdeuk** [comment]
> 
> 
> Coverage may be relatively poor as recent updates have focused on England

We likely only need to list a relatively small number - e.g. the remaining grant-aided / special schools [aka ASL / ASN / SEN] that we don't already list.

The majority of schools in Scotland come under the control of the local authority (who also employ the staff, own the buildings, and set policy). They  are not public bodies in their own right in terms of FoISA.

https://www.legislation.gov.uk/ssi/2016/139/schedule/1/made
https://www.itspublicknowledge.info/ScottishPublicAuthorities/NewAuthorities/Supportforgrant-aidedandspecialschools.aspx

**Comment by HelenWDTK** [comment]
Closing as complete - I added the schools on the OSIC list that I could verify existed.
