### ISSUE TITLE
Clean-up repeated events on request admin pages

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#785]
There was, or perhaps still is, a bug which caused the creation of lots of repeated events of the form:

>allow_new_responses_from: authority_only => nobody
>editor: InfoRequest.stop_new_responses_on_old_requests 

on request admin pages

Can these event logs be deleted to make the event logs easier to read? I presume this is a suggestion which it would make sense to act on after the underlying bug is fixed.  

The related issue for the bug is still open at:
https://github.com/mysociety/alaveteli/issues/4776

**Comment by garethrees** [comment]
> I presume this is a suggestion which it would make sense to act on after the underlying bug is fixed.

Yeah. I've transferred this as a todo on https://github.com/mysociety/alaveteli/issues/4776, so closing this.
