### ISSUE TITLE
Help pages refer to Pro service as forthcomming 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#786]
At

https://www.whatdotheyknow.com/help/requesting#multiple

the is the statement:

> There is currently no automated system for sending the request to multiple authorities: you must copy and paste it by hand, although, see below for details of our forthcoming service WhatDoTheyKnow Professional. 

this is no-longer accurate.

**Comment by mdeuk** [comment]
I'd propose replacing:

>  There is currently no automated system for sending the request to multiple authorities: you must copy and paste it by hand, although, see below for details of our forthcoming service WhatDoTheyKnow Professional.
>
>There are some automated restrictions on the number of requests that can be sent through WhatDoTheyKnow at a time. These are for spam prevention and can be overridden on request. Before removing restrictions on accounts the team may make suggestions aimed at improving the requests, and checking information isn’t already published, or hasn’t already been collated centrally, and can’t be obtained by a request to just one body.
>
>If you are a journalist, activist, campaigner or someone else who would find it useful to have a tool enabling you to make requests to multiple bodies at the same time please[ find out more and get in touch](https://www.whatdotheyknow.com/pro). 

with a slightly tweaked version:

> There are some automated restrictions on the number of requests that can be sent through WhatDoTheyKnow at a time. These are for spam prevention and can be overridden on request. Before removing restrictions on accounts the team may make suggestions aimed at improving the requests, and checking information isn’t already published, or hasn’t already been collated centrally, and can’t be obtained by a request to just one body.
>
> There is currently no automated system for sending the request to multiple authorities: you must copy and paste it by hand; however, if you are a journalist, activist, campaigner or someone else who would find it useful to have a tool enabling you to make requests to multiple bodies at the same time, then you might be interested in our [WhatDoTheyKnow Pro service - click here to find out more](https://www.whatdotheyknow.com/pro).

This suggested change would improve the readability of the section slightly; however it might very well be that a re-write of some of the content would be more suitable. What do you think?

**Comment by garethrees** [comment]
Would be great if someone could attempt this themselves 🙏
