### ISSUE TITLE
Cover policy on requester_only vs hidden vs deletion in the published policies on the help pages. 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#788]
Currently the published policies on the help pages refer only to taking material down from our website. 

Actually we have hidden / requester_only and sometimes we delete material.  

We could provide more detail on our approach in public on the help pages.

**Comment by garethrees** [comment]
Also backpage

**Comment by mdeuk** [comment]
> Also backpage

Backpage should be covered off in #781 which is awaiting deployment - we can always update that if need be :)

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
