### ISSUE TITLE
Refresh and improve the home page / front page

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#791]
The headline is currently:
>Get answers from the government and public sector

how about:

>Get government and public sector information published

Can we do more to stress the value of having a FOI response published - to support whatever anyone does with it, eg. journalism, lobbying, research etc. ?

The front page states:
> It also publishes all requests online.

rather than eg. "all requests and any responses are published online" - though the publication of responses is mentioned elsewhere on the page. 

There is also quite a prominent technical error:
>You have the right to request information from any publicly-funded body

FOI and similar access to information laws apply to public bodies, not publicly-funded bodies.

**Comment by RichardTaylor** [comment]
Other Alaveteli installations have some much more engaging and interesting content on their front pages than WhatDoTheKnow does in the UK. 

**Ukraine's https://dostup.pravda.com.ua/**

There's section titled: "The lawyer comments" « Expert annotations. We could copy this and highlight advice and commentary on requests from the WhatDoTheyKnow.com team. Related ticket https://github.com/mysociety/alaveteli/issues/34 but perhaps we could work with what we currently have - for example starting a WhatDoTheyKnow-Comments User?

There are graphically engaging "publications" and "projects" sections. Perhaps these are "just" blog article links - but the integration, and particularly the images, are excellent.  WhatDoTheyKnow articles from the mySociety blog aren't shown at all on the WhatDoTheyKnow.com front page, there is a link to an integration with the mySociety blog, but it is unsophisticated and eg. it isn't possible to link to individual articles. 

**Ask the EU https://www.asktheeu.org**
Again far better blog integration. 


Also https://transparencia.be and https://www.asktheeu.org have a video on their front pages. I don't personally think that's the way to go. 

I think almost all the other instances of Alavetli have a more inviting and modern looking front page than WhatDoTheyKnow - from my looking though https://alaveteli.org/deployments/ 

The image on WhatDoTheyKnow's front page is really quite dismal - a brighter image with a background colour over the top for text as used elsewhere might be preferable to a drab image.

**Comment by RichardTaylor** [comment]
We don't know why some installations of Alaveteli thrive and others don't. 

I suspect that it's probably more down to local laws/culture than the design of a site's front page, however it may be that if a site presents itself as being "about" high-impact journalism and campaigning that might deter more low-level and personally/locally focused use of the service.

**Comment by WilliamWDTK** [comment]
And [AskTheEU.org](https://www.asktheeu.org/#general_frontpage) has a list of 2 top requests (presumably by the number of follows/tracks), both of which are fairly old.

We already have this data on the bottom of the [Tracks admin page](https://www.whatdotheyknow.com/admin/tracks).

**Comment by RichardTaylor** [comment]
We could publish some traffic statistics on the front page. 

eg.

>20,714,033 visitors to WhatDoTheyKnow.com this year

https://www.mysociety.org/2021/12/16/whatdotheyknow-transparency-report/

This could encourage use of the service.

**Comment by RichardTaylor** [comment]
We could get recent tweets onto the front page.

**Comment by HelenWDTK** [comment]
We've added lots of new content to the front page since this was started - research, newsletter promo, videos etc with more things proposed such as the FOI heroes section, and a bit on why FOI is useful/awesome.
