### ISSUE TITLE
Add mailbox used by Coventry City Council to model_patches.rb

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#793]
FOI responses issued by Coventry City Council are being sent from `myaccount -at- coventry.gov.uk` which is bouncing any replies that are sent to it.

Example (from request [722944](https://www.whatdotheyknow.com/request/common_seal_of_the_council_2#incoming-1749708)): 

> This is a delivery failure notification message indicating that
> an email you addressed to email address :
> -- [email address]
> 
> could not be delivered. The problem appears to be :
> -- Recipient email address is possibly incorrect
> 
> Additional information follows :
> -- 5.4.1 Recipient address rejected: Access denied. AS(201806281) [DB5EUR01FT048.eop-EUR01.prod.protection.outlook.com]
> 
> This condition occurred after 1 attempt(s) to deliver over
> a period of 0 hour(s).
> 
> If you sent the email to multiple recipients, you will receive one
> of these messages for each one which failed delivery, otherwise
> they have been sent.
> 
> Please contact ICT for further information.

**Comment by RichardTaylor** [comment]
Shall we consider doing necessary re-sends as part of this issue?

Do these fixes actually help at all with issues that have already happened or do they only prevent future issues occurring?

If we do a re-send to the address now identified as a no-reply address does the message go to the main foi address for the public body?
