### ISSUE TITLE
List school sponsors / academy trusts comprehensively

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#797]
We could seek to list "school sponsors" comprehensively.

example of a "school sponsor"

https://www.get-information-schools.service.gov.uk/Groups/Group/Details/5002#details

school_sponsor would be a good tag, it's slightly broader perhaps than [academy_trust](https://www.whatdotheyknow.com/body/list/academy_trust).

There are 5685 "establishment groups"

https://www.get-information-schools.service.gov.uk/Groups/Search?SelectedTab=Groups&b=1&b=4&search-by=all&searchtype=GroupAll

**Comment by mdeuk** [comment]
> We could seek to list "school sponsors" comprehensively.
> 
> example of a "school sponsor"
> 
> https://www.get-information-schools.service.gov.uk/Groups/Group/Details/5002#details
> 
> school_sponsor would be a good tag, it's slightly broader perhaps than [academy_trust](https://www.whatdotheyknow.com/body/list/academy_trust).

We already tag some of these bodies using the tag **spuid** (as per #698).

A related tag is **matuid** which relates to Multi-Academy Trusts, confusingly some bodies are both an academy trust and a sponsor - and are listed accordingly in the DfE GIAS database.

**Comment by WilliamWDTK** [comment]
Also, is it worth tagging `academies` that are also a single-academy trust as `academy_trust`?  We could also have a `satuid` to complement the `matuid`, with a similar link generated in the sidebar.  I just use `matuid` on body 88057, since it's the closest reasonable tag, but not ideal.

**Comment by RichardTaylor** [comment]
> a single-academy trust

Where a trust runs a single school we have been listing only the school. The reason for this was seeking to best serve our users. We thought people would be aware of the school name, and the trust would be a more abstract entity. Technically it is the trust which is subject to FOI and if the school itsself exists as a body in its own right is perhaps a philosophical point. 

This has been an exception to the general approach of basing what we do on FOI law. We usually only list bodies which clearly exist, but there are parallels eg. with our listing of police forces when [technically it is Chief Constables as corporations sole which are subject to FOI](https://www.legislation.gov.uk/ukpga/2000/36/schedule/1/paragraph/59) not their forces. 

We also try to list bodies by their common names, where an official name is [archaic and unwieldy](https://wdtkwiki.mysociety.org/wiki/Naming_of_public_authorities_policy#Special_cases), listing schools rather than a single-academy trust could be seen as a small extension of that approach. 

This approach should be documented if it isn't already.

>tagging academies that are also a single-academy trust as academy_trust

I think ideally the notes for a school run by a single-academy trust should explain the governance situation, that could be achieved via tagging and [tag based notes](https://github.com/mysociety/alaveteli/issues/6305). If the name of the trust and school are different though perhaps we would ideally want a tailored note.

**Comment by HelenWDTK** [comment]
https://wdtkwiki.mysociety.org/wiki/Authority_suggestions
