### ISSUE TITLE
Link to lists of latest requests, and latest responses 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#798]
Links to:

* [Latest responses](https://www.whatdotheyknow.com/search/variety:response/all)

and

* [Latest requests](https://www.whatdotheyknow.com/search/variety:sent/all) 

could usefully be offered, perhaps from the help pages. 

I've raised a similar ticket at:

https://github.com/mysociety/alaveteli/issues/6183

**Comment by garethrees** [comment]
Fixed by https://github.com/mysociety/alaveteli/issues/6183
