### ISSUE TITLE
Help page focused on those looking to find, and be alerted to, information on WhatDoTheyKnow

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#799]
We could have a help page aimed at journalists, activists, and others who want to find, and/or be alerted to, information on WhatDoTheyKnow

See also:
https://github.com/mysociety/alaveteli/issues/6184

See also:
https://github.com/mysociety/whatdotheyknow-theme/issues/798

**Comment by MyfanwyNixon** [comment]
I'd be happy to have a go at drafting this.

**Comment by RichardTaylor** [comment]
We could point to the advanced search options. 

We could also point to the add a body form - if we're not already listing bodies of interest (we could not be listing key local bodies, such as parish / town councils, or local NHS bodies). 

We could suggest searching the site to see if relevant activists / campaign groups / organisations are using the service, and suggest following them.

**Comment by MyfanwyNixon** [comment]
Here's some draft copy (which I'm sure can be improved): https://docs.google.com/document/d/18kczOgmn8hxLkQ8o50A6ovdE52PRJF-q__Du_M9ImS8/edit#

**Comment by MattK1234** [comment]
> Here's some draft copy (which I'm sure can be improved): https://docs.google.com/document/d/18kczOgmn8hxLkQ8o50A6ovdE52PRJF-q__Du_M9ImS8/edit#

I've just requested access for the support account as it's showing access denied currently.

**Comment by MyfanwyNixon** [comment]
Apologies for the delay; hopefully you can see it now @MattK1234

**Comment by MattK1234** [comment]
Looks great, thanks Myf! 😊
