### ISSUE TITLE
Clock for internal review

### ISSUE THREAD

**Issue by sebbacon** [mysociety/whatdotheyknow-theme#8]
```
The Information Commissioner has issued a "Good Practice Guidance" document:    http://www.ico.gov.uk/upload/documents/library/freedom_of_information/detailed_specialist_guides/foi_good_practice_guidance_5.pdf
20 days is late
40 days max.
```

Fix up the text: "The internal review should take 2-3 weeks for simple cases,
and up to 6 weeks even for complex reviews."
Awaiting internal review overdue state?

**Comment by garethrees** [comment]
Duplicate of https://github.com/mysociety/whatdotheyknow-theme/issues/5
