### ISSUE TITLE
Improve the page on volunteering

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#801]
https://www.whatdotheyknow.com/help/volunteers

>get in touch. 

This could be expanded to "get in touch, introducing yourself". 

Consider publishing and linking to the volunteer agreement. 

> Or find out FOI email addresses of authorities that we’re missing. 

Should be: "let us know about bodies which are missing from our service". 

(This doesn't link to a list of bodies we don't have email addresses for). 

Remove

> Ask us for leaflets to leave in your local library or coffee shop. 

as I don't think we're offering those any more.

**Comment by garethrees** [comment]
> (This doesn't link to a list of bodies we don't have email addresses for).

Linking to https://github.com/mysociety/alaveteli/issues/3477

**Comment by RichardTaylor** [comment]
This page should contain, and/or link to, far more information about what the site admin team does to keep the site running.

**Comment by sallytay** [comment]
Closed as completed in #1178
