### ISSUE TITLE
Add refusal advice for misleading auto-acknowledgements

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#805]
We'll soon have the ability to advise our users on how to challenge refusals.

Once we've run the initial set of advice and snippets, we should add some for the [increasing problem](https://groups.google.com/a/mysociety.org/g/alaveteli/c/FZ7Dk3swCCU/m/968PspmMAgAJ) of authorities pointing citizens towards their online forms.

We should include a wizard section around non-responses and misleading auto-acknowledgements.

We should have some template phrasing in the form of a Snippet to point users at our help page around recognising `@whatdotheyknow.com` email addresses.

Related:

* https://github.com/mysociety/alaveteli/issues/2045
* https://github.com/mysociety/research/issues/227

**Comment by RokeJulianLockhart** [comment]
@garethrees, https://github.com/mysociety/research/issues/227 is 404.

**Comment by garethrees** [comment]
It's a link to a private repo, sorry.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/mysociety/whatdotheyknow-theme/issues/805#event-15325715154

@HelenWDTK, why?

**Comment by HelenWDTK** [comment]
> > [#805 (comment)](https://github.com/mysociety/whatdotheyknow-theme/issues/805#event-15325715154)
> 
> @HelenWDTK, why?

I closed it due to the age and as it's not on our radar to do at the moment. Sadly we don't have the resources to do everything we'd like. We may still do this in the future as part of a larger block of work.
