### ISSUE TITLE
Remove links to housingcorp.gov.uk and update notes on Housing Associations

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#809]
It appears http://www.housingcorp.gov.uk/ no longer exists. 

Many notes for housing associations point to a document on that domain. 

The notes for housing associations generally need updating and improving in many cases. 

Caution is needed as not all notes on such bodies are the same.

**Comment by MattK1234** [comment]
A [quick search](https://www.whatdotheyknow.com/search/housingcorp.gov.uk/bodies?utf8=%E2%9C%93&query=housingcorp.gov.uk) reveals 55 bodies that contain the housingcorp.gov.uk domain within the notes.

A file containing all authorities is available at https://www.whatdotheyknow.com/body/all-authorities.csv which could be filtered down to locate the relevant bodies, make updates, and then reupload via the csv upload tool.

**Comment by confirmordeny** [comment]
We are now using tag-based notes and we link to an archived version of the Housing Corporation guidance.  See for example: https://www.whatdotheyknow.com/body/broadacres_housing_association

... which links to: https://web.archive.org/web/20080910184121/http://www.housingcorp.gov.uk/upload/pdf/FOIAInfoSheet.pdf

See also #1739, #1403 and  #632
