### ISSUE TITLE
Consider comprehensive listing of registered social housing providers in England

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#812]
Compare the UK Government List of registered [social housing] providers with bodies listed on WhatDoTheyKnow.com and consider adding bodies missing from WhatDoTheyKnow.com 

https://www.gov.uk/government/publications/current-registered-providers-of-social-housing/list-of-registered-providers-17-september-2020

List appears to be England only, though isn't labelled as such.

**Comment by confirmordeny** [comment]
Note that there appear to be over 1,500 at present

https://www.gov.uk/government/publications/registered-providers-of-social-housing/list-of-registered-providers-14-april-2022-accessible-version

**Comment by HelenWDTK** [comment]
https://wdtkwiki.mysociety.org/wiki/Authority_suggestions
