### ISSUE TITLE
Consider policy on informing people when we get requests for their personal information

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#814]
Requests could be:

* Court orders
* Police requests under PACE
* Subject Access Requests by third parties, where third party data is mixed up with the requester's personal data. 

We sometimes get notices of proposed requests/orders prior to the requests/orders themselves. 

We may not legally be able to provide notice to those whose data is involved straight away.

**Comment by garethrees** [comment]
Somewhat related to https://github.com/mysociety/whatdotheyknow-theme/issues/815.

**Comment by RichardTaylor** [comment]
Example of how Apple informed one of their users about a request from the FBI for their personal information:

https://twitter.com/ringo_ring/status/1390782451140767749

**Comment by RichardTaylor** [comment]
[Section 47.8 of the The Criminal Procedure Rules 2020](https://www.legislation.gov.uk/uksi/2020/759/article/47.8/made) states those who may apply to vary or discharge an investigation order (including a production order under the Police and Criminal Evidence Act 1984) are: an applicant; the respondent; or a person affected by the order.

If those affected by the order are not informed of it they can't avail themselves of their right to challenge it.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
