### ISSUE TITLE
Consider adding notes to the privacy page on the subject of confidentiality of support correspondence  

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#816]
Consider expanding:

https://www.whatdotheyknow.com/help/privacy#personal_information_contact

to say, if, and to what extent, we consider support correspondence to be confidential. 

Perhaps note we may have to consider releasing it in response to eg. court orders, and subject access requests from third parties:

https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/right-of-access/information-about-other-individuals/

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
