### ISSUE TITLE
Publish statistics on domains used most frequently by users signing up to the site

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#821]
This idea was raised by a new prospective volunteer as a way to show who is using the service, as a way of promoting it. 

Could we publish eg. how many users we have with domains from certain news organisations, universities, parliaments, councils etc. ?

Even if we didn't publish, having the data internally could help us make general statements about our users. 

This idea has been raised previously in the context of identifying potential institutional Pro subscribers. 

Caution: The results might be skewed by some of the Pro promotion work that's been done.

**Comment by garethrees** [comment]
This one will need careful consideration. I know it's somewhat common practice in the tech world, but I don't like the idea of manufacturing endorsement without consent.

I'm not sure how much of an effect GDPR would have, especially when we're talking corporate domains, but I'd certainly be frustrated if I signed up to a service and then a mySociety logo ended up on their homepage.

**Comment by mdeuk** [comment]
> This one will need careful consideration. I know it's somewhat common practice in the tech world, but I don't like the idea of manufacturing endorsement without consent.
> 
Agreed - I also think we have to be wary of exposing any factoid that might suggest we have a substantial proportion[1] of users who are using pseudonyms (for example, if we disclosed we had $x number of users using 'disposable' email addresses, or those which shield ones identity).

It sounds ridiculous, but I wouldn't put it past some authorities to use that kind of data as one which enabled them to invoke ID requirements.

[1] I don't know if we do or not - I've not analysed the data, and wouldn't plan to.
