### ISSUE TITLE
Flags for nations of the UK on pages for bodies, and requests to bodies, where the body has a tag for that nation

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#824]
This feature might:

* Help people realise the service applies to them, in their part of the UK
* Help admins realise which nation a request has been made in (as access to information law varies)

**Comment by RichardTaylor** [comment]
I see a link with

https://github.com/mysociety/alaveteli/issues/6172 Option to add and use a public body logo

as that also relates to helping people visually understand what the site is about

**Comment by confirmordeny** [comment]
This would be fine for England, Scotland and Wales but controversial for NI.
