### ISSUE TITLE
Decide how to tag NHS bodies

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#828]
We want to use tags on NHS bodies so we can use the offical NHS organisation data service database of NHS bodies at:

https://odsportal.digital.nhs.uk/

to help us keep our database up to date. 

Being able to work with the official register might help us

* Identify new bodies we want to add
* Identify defunct bodies we want to mark defunct
* Show links between bodies, eg. bodies working at the same site, hierarchies of bodies etc. 
* Work with geographical information better, eg. show bodies in a certain area, or which cover a certain area. 

Actions
* Decide which IDs to use from odsportal.digital.nhs.uk and what format to store them in as tags in our database. 
* Note the policy on the WDTK wiki at https://wdtkwiki.mysociety.org/wiki/Policies#Tagging and perhaps more usefully in the online tips on the public body addition admin page

If we actually use these tags / links the incentive for admins to use them will be increased. 

Note the existing health categories/tags as listed at

https://www.whatdotheyknow.com/admin/bodies/new

**Comment by HelenWDTK** [comment]
Noting at https://wdtkwiki.mysociety.org/wiki/Tagging_suggestions
