### ISSUE TITLE
Set up a canned response for use when we remove the rate-cap for a user

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#829]
Such a canned response could be based on recent such messages. 

We point users to our house rules, and urge them to use the service, and FOI, responsibly.

**Comment by mdeuk** [comment]
We already have a template such as this - it's called "rate limit removed".

**Comment by mdeuk** [comment]
> We already have a template such as this - it's called "rate limit removed".

I've now updated said template to include reference to the House Rules (we've used this for a couple of years, but the signpost wasn't necessarily explicit in the template) - hopefully this addresses the ticket.

I'll close this one off just now, but do feel free to re-open or amend the template directly if required 😃
