### ISSUE TITLE
Blog about the harms and benefits of running WhatDoTheyKnow

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#830]
We are acutely aware that harm can, on occasion, be caused as a result of us operating our service, that said we hope that on balance the positive benefits far outweigh any harm caused.

- Accidental releases of personal data are made worse because of our automatic publication (however they get spotted, and we and the ICO have acted to try and educate public bodies to prevent accidental releases).  
- We often hold personal data which was intentionally released, but in relation which there have been claims of harm, examples which have prompted lots of correspondence include:
	- Registers of landlords, licence holders and managers of houses in multiple occupation. 
	- Information about individuals who have taken part in public civic processes, such as commenting, supporting, or objecting in planning cases. 
	- Pseudonymised personal data released, for example in relation to university admissions criteria, and even 11+ exams. 
	- University graduation ceremony programmes
	- Publication of names of those responding to requests

**Comment by MyfanwyNixon** [comment]
This is drafted at https://docs.google.com/document/d/1e6U7Ys2HjVd5rQmNBmewpKlv7WRB-1wSxsA_391_Dck/edit but could definitely do with some input from volunteers. I've set permissions to 'anyone at mySociety' but shout if you need access, volunteers.

**Comment by WilliamWDTK** [comment]
On the duplicate ticket, @RichardTaylor mentions that it has been decided to not to one single blog on the harms/benefits, but do multiple focussing on a different area.

It is therefore possible that this ticket could be closed if we have tickets for all the sub-areas that we'd like to look at.

**Comment by HelenWDTK** [comment]
Closing this, as there are no plans to blog about this as a single blog. If there are individual topics that would have fit under this that someone wants/intends to write about, these can be covered separately as they arise.
