### ISSUE TITLE
ICO referral at /help/unhappy causes poor user experience

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#832]
When users click on [/help/unhappy](https://www.whatdotheyknow.com/help/unhappy) and follow the link to obtain the "here's how you refer to the ICO/OSIC" guidance, the user experience now that the refusals advice has been added is less than stellar.

### Steps to reproduce:

1. Visit https://www.whatdotheyknow.com/help/unhappy - click on "Refer your request to the Information Commissioner"
2. Click on the blue "Refer your request to the Information Commissioner" button
3. Note that the page will re-load with the addition of the #refer-to-ico anchor in the URL
4. Note that nothing _immediately_ changes, however after a few seconds the page _should_ move to the [correct section](https://www.whatdotheyknow.com/help/unhappy#refer-to-ico).
5. Note that only a stub of the text is visible without clicking on the arrow contained on the left hand side of the page
![image](https://user-images.githubusercontent.com/249418/121813305-6566da00-cc63-11eb-9e55-111847023c82.png)

### Expected behaviour
The text should be rendered, in its entirety without the user needing to click to expand the summary.

### Suggested fix

The ICO text is rather bulky, so I ponder if the best way to fix this would be for us to part it into a separate help page of its own - this would have the benefit of being able to link to this specific text in an intelligible way from support emails, and allow for ease of maintainability by non-developer volunteers.

Would this be an acceptable workaround?

**Comment by RichardTaylor** [comment]
Related ticket:  Link to the ICO's email address from advice on referrals to the ICO  https://github.com/mysociety/whatdotheyknow-theme/issues/831

**Comment by RichardTaylor** [comment]
Is it worth thinking long (hopefully not too long?) term about how [integrating referrals to the ICO into the site](https://github.com/mysociety/alaveteli/issues/2819#issuecomment-145066158) might work when making changes here?

**Comment by garethrees** [comment]
I've removed the `bug` label since users aren't _prevented_ from using functionality, but I agree that this isn't great.

> Note that only a stub of the text is visible without clicking on the arrow contained on the left hand side of the page

You should be able to click any part of the paragraph to unfold.

> The text should be rendered, in its entirety without the user needing to click to expand the summary.

I think we ought to be able to unfold the text when the related anchor is present.

> I ponder if the best way to fix this would be for us to part it into a separate help page of its own

We were actually thinking about this (https://github.com/mysociety/alaveteli/issues/6235), but it brought up a few complexities around how we present the page that we didn't have budget to deal with (https://github.com/mysociety/whatdotheyknow-theme/pull/817/commits/fe4c5c4fd1fde7aa2e07fbabd6c587d4b4a76260). The gist of this is that the bulleted list in the page intro requires the ICO section to be there. If we directed to a new page then  we'd still have to solve this for the other list elements (internal review, other means). 

![Screenshot 2021-06-14 at 08 48 38](https://user-images.githubusercontent.com/282788/121857359-73613d00-cced-11eb-9482-07303cc58285.png)

 I wouldn't be _against_ extracting, but I think the problem we should solve right now is to make the current behaviour a bit nicer.

**Comment by RichardTaylor** [comment]
>The text should be rendered, in its entirety without the user needing to click to expand the summary.

I've found myself writing to tell users they need to click the arrow to expand the text a couple of times when pointing them to either the refer to ICO or internal review sections of the page. 

I don't think it's obvious enough there's something to expand.

**Comment by RichardTaylor** [comment]
User feedback which I think is related:

>When I click on the "Refer your request to the Information Commissioner" button, nothing actually happens.

**Comment by RichardTaylor** [comment]
Some bullet points on the page end with a full stop, others don't.

**Comment by RichardTaylor** [comment]
I think this is another user confused about this page, and the "Refer your request to the Information Commissioner" button:

>Can you tell me how to request the FOI be forwarded to the ICO, when I select the button, it doesn't take me anywhere like to the FOI ICO page and when I check the FOI ICO page, I don't see the request. Is it a message that is sent privately to the ICO and if so, am I not suppose to receive a acknowledgment?

**Comment by garethrees** [comment]
Deployed https://github.com/mysociety/alaveteli/pull/6356 so this is now improved.

One thing I've noticed is that the yellow fade doesn't appear if you click one of the `#` links to change the anchor.

1. Visit https://www.whatdotheyknow.com/help/unhappy#internal_review
2. Click `#` next to "Using other means to answer your question"

Expected: Details tag unfolds with yellow fade
Actual: Anchor changes and the page jumps to the section, but details doesn't unfold

**Comment by RichardTaylor** [comment]
Excellent. This works as intended when following a link with an anchor tag. I've removed the following from a WhatDoTheyKnow template email:

>You need to click the little ">" arrow under the "Referring a request to the Information Commissioner" to see it.


On the point:

>the yellow fade doesn't appear if you click one of the # links to change the anchor.

I've always assumed the # links are intended to make the anchor link available for copy and paste, not for clicking. I wouldn't expect clicking a # anywhere on the help pages to do anything. 

That said if you visit the page without an anchor 

https://www.whatdotheyknow.com/help/unhappy

and click "Information Commissioner" from the bullet at the top:

* If that doesn't help, you can refer the request to the [Information Commissioner](https://www.whatdotheyknow.com/help/unhappy#refer-to-ico). 

then the section isn't unfolded or highlighted. That's the same issue as clicking on the # not unfolding and highlighting the section but in a situation which I think is more likely to be realistic.

**Comment by garethrees** [comment]
>  I wouldn't expect clicking a # anywhere on the help pages to do anything.

It does (and should) change the anchor. One might right click and then select "Copy Link Address" (or similar). Another way of doing the same is to left click the link, `cmd+l` to highlight the new URL and then `cmd+c` to copy it.

> and click "Information Commissioner" from the bullet at the top

Yeah, same issue as clicking `#` to unfold. Basically what we're missing is that, however the anchor changes, the relevant section should unfold.

**Comment by wrightmartin** [comment]
> One thing I've noticed is that the yellow fade doesn't appear if you click one of the # links to change the anchor.

Ah, no it won't because it only checks it on page load, sorry I didn't realise that was the intention. It's possible to change it but it's not a quick fix as I'll need to add functionality to check it on the click event too

**Comment by garethrees** [comment]
I didn't realise it was the intention either, until I used it! :) I've added this to the design backlog – doesn't seem like it ought to be a _huge_ amount of work, even though it's not a tiny tweak.

**Comment by wrightmartin** [comment]
> I didn't realise it was the intention either, until I used it! :) I've added this to the design backlog – doesn't seem like it ought to be a huge amount of work, even though it's not a tiny tweak.

Super, no not huge but there's always unknowns with clickhandlers
