### ISSUE TITLE
Review if Welsh versions of pages are being shown to those who'd find English more useful

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#833]
I've noticed quite often English speakers will contact the WhatDoTheyKnow.com team with references to /cy/ versions of a page on WhatDoTheyKnow. 

Often it appears they've found such pages via Search Engines. 

* Is this a problem (can we do some research)?
* Do we have the right headers/meta tags on the Welsh pages so that search engines can make an informed decision on if to show an English or Welsh page to users searching in each language, or with browser or search settings indicating a language preference?

**Comment by HelenWDTK** [comment]
I think this is partly a caching issue. We very very rarely get contacted by people who are confused by this, and most of the content on the welsh versions of attachment pages (which are most affected) is still in English, which will be why it shows up in search. If this looks like becoming a bigger issue, we should revisit this.

**Comment by WilliamWDTK** [comment]
I've anecdotal evidence of a user browsing the site and ending up on a Welsh page listing requests. When questioned, they weren't able to explain how it happened, and were confused why only some text was in Welsh (not the request text etc).

Just noting, not re-opening.
