### ISSUE TITLE
Expand help page section on postal answers to encourage users to get a copy of material released by post published

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#834]
https://www.whatdotheyknow.com/help/privacy#postal_answer

Text from support responses which might help:

> We would like to see the responses to requests made via our service on our website.
>
> There are a couple of options:
> 
> * You could add an annotation (via "actions") and copy and paste the public body's response there. If you do this make sure the material is material you want to make public, and it is appropriate to make public. Sometimes a public body will include your personal information in a response sent directly to you.
> 
> * You might want to just add an annotation with a note explaining what you have received, this might be the most efficient option if the substance of the response can be easily summarised. 
> 
> * You could reply to the public body, again via "actions" and request a response via the @whatdotheyknow.com email address associated with your request. Section 11 in both the Freedom of Information Act and the Freedom of Information Scotland Act requires public bodies to follow any reasonable request as to a means of communication - so if you ask them to respond via WhatDoTheyKnow.com they should. You will already have indicated a desire to have a response via WhatDoTheyKnow by making your request via our service. https://www.legislation.gov.uk/asp/2002/13/section/11  https://www.legislation.gov.uk/ukpga/2000/36/section/11
> 
> * If you've been sent a USB drive, or a CD with lots of data on, if you can make it available online and let us know where we can find them we may be able to take a copy and upload it to our site. In exceptional circumstances a volunteer may be prepared to receive a copy by post.
> 
> * If you've been sent paper documents you may wish to scan / photograph them. Again if you can make them available online and let us know where we can find them we may be able to take a copy and upload them to our site.

Something based on the above text could be placed in a new help page section, linked to both from the postal_answer section and anywhere else where an off-site response is mentioned.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
