### ISSUE TITLE
HTML appearing in question in refusal advice wizard

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#835]
I'm seeing

`Is there any indication of a plan, date or trigger for the publication? ICO guidance states that Section 22 may be applied if: <ul> <li>there is a publication deadline: publication could be at any date before then; or</li> <li>publication will take place once other actions have been completed; or</li>....  ` 

in the wizard rather than a formatted list.

**Comment by gbp** [comment]
Need to replace `plain` with `html`: https://github.com/mysociety/whatdotheyknow-theme/blob/87ae3cda57763b453d552ff2c54061f165203776/config/refusal_advice/section_22.yml.erb#L120
