### ISSUE TITLE
Logic fail in refusal advice wizard

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#836]
On answering no to 

>Is there any indication of a plan, date or trigger for the publication?

I was asked 

>Is this date far into the future?

**Comment by gbp** [comment]
`s/no/yes/`
https://github.com/mysociety/whatdotheyknow-theme/blob/87ae3cda57763b453d552ff2c54061f165203776/config/refusal_advice/section_22.yml.erb#L165
