### ISSUE TITLE
Develop and publish policy on listing sports governing bodies

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#839]
We list some sports governing bodies:

https://www.whatdotheyknow.com/body/list/sports_governing_body

We should have a help page section explaining why we list them, and what our criteria is for listing them.

**Comment by RichardTaylor** [comment]
Consider reflecting the stance taken by the official register of sports national governing bodies at:

https://www.sportengland.org/how-we-can-help/national-governing-bodies

**Comment by RichardTaylor** [comment]
We've had requests to add the Rugby Football Union and the English Cricket Board. 

We've not acted on them, but we have advised the users that we don't think these bodies are subject to FOI. Those asking us to add them might not have realised they were not subject to FOI. 

Some text for a response:
>
>Thank you for your email suggesting we list the [Sports Governing Body].
>
>We don't think this body is likely to be subject to FOI, and it doesn't clearly meet our criteria for listing on the grounds it's a body we want to see made subject to the Act. Our policy on listing bodies not subject to access to public information laws is at:
>
>https://www.whatdotheyknow.com/help/requesting#authorities
>
>We are carrying out some further research to allow us to make a comprehensive decision on our policy in this area - you may have seen we do list a handful of sports governing  bodies. 
>
>If there are any specific reasons why you think the [Sports Governing Body] should be subject to the FOI act, please do let us know as this will help with our research.
>
>Do consider if the information you are seeking might be available from bodies which are subject to Freedom of Information law eg. 
>
>The Department for Digital, Culture, Media and Sport
>https://www.whatdotheyknow.com/body/dcms
>
>Sport England 
>https://www.whatdotheyknow.com/body/sport_england
>
>National Lottery Community Fund
>https://www.whatdotheyknow.com/body/the_national_lottery_community_fund
>
>Regards,

**Comment by RichardTaylor** [comment]
The Government is committed to establishing an independent regulator of English football.

It appears the Government isn't happy with domestic and international self-regulation so is going to step-in. 

The Government regulator will almost certainly be a public body subject to FOI. 

What does say about the role the Football Association is currently playing?  Is this an indication that it was fulfilling a public role?

* https://www.gov.uk/government/news/government-takes-next-steps-towards-delivering-major-reform-of-football-in-england
* https://www.theyworkforyou.com/debates/?id=2022-05-10b.4.0

**Comment by RichardTaylor** [comment]
The importance of sports governing bodies in ensuring public safety can be seen via the recommendations of a recent Marine Accident Investigation Branch report into a stand up paddle-boarding accident report relating to an incident in which four lives were lost during a commercial stand up paddle-board tour accident at Haverfordwest Town Weir on the River Cleddau in Wales:

https://www.gov.uk/maib-reports/commerical-stand-up-paddleboarding-accident-on-river-weir-with-loss-of-4-lives

Paragraph 1.13.2  of the report is titled: ''Governance of sport in the UK'' and states:

>Governance of sport in the UK is the responsibility of the individual National Governing Body (NGB) for that sport. The national Sports Councils, Sport England, Sport Northern Ireland, sportscotland and Sport Wales, funded via their respective
governments, were empowered by royal charter to support, encourage and foster sport and physical recreation within their nation; they do not, however, act as regulator or have governance responsibilities for all sport in their respective nations.
Sports Councils are able to confer recognised status on an NGB. Recognised status means that the relevant Sports Council recognises that organisation as the body that governs and administers a sport on a national basis and described NGBs
as the custodians and guardians of their sport. 
>
>The Sports Councils do not have regulatory powers and recognition does not mean, they have approved an NGB’s
systems or processes.
>
>The Sports Councils’ recognition process for sporting NGBs was described in their 2017 Recognition Policy, which stated that NGBs were expected to deliver the following functions:
>
>>a) Control and regulate the environment of its sport;
>>b) Administer the practice and participation of its sport;
>>c) Develop its sport;
>>d) Influence both members and organisations of which it is a member.
>
>While not explicitly mentioning safety, the recognition process required an NGB to demonstrate that:
>
>>Where a sporting activity presents a risk of injury, the NGB should demonstrate it has taken measures to minimise and control risk to participants and has in place appropriate policies to manage the risk.

The recommendations of the report were:

>The UK national Sports Councils are recommended to:
>**2022/134** Complete their review of the governance of stand up paddleboarding in the UK and urgently ensure that the recognised national governing body(ies) have the resource, support and expertise to issue advice and guidance, including
appropriate training standards to control risk to those who take part in this fast-growing sport.
>**2022/135** Review and develop as necessary its criteria for conferring recognition as a national governing body, to include the management of safety and adherence to good practice by the governing body and any organisation or companies it accredits.
>**2022/136** Develop and publish a national governing body Guide to Good Practice.

I think this shows our society expects recognised national governing bodies for sports to fulfil a key public safety related function, and that's another strong reason for listing them on WhatDoTheyKnow.com.

**Comment by garethrees** [comment]
Removing blog-idea label as that's covered by https://github.com/mysociety/whatdotheyknow-theme/issues/1361.

**Comment by RichardTaylor** [comment]
>We should have a help page section explaining why we list them, and what our criteria is for listing them.

Actually if we list them we'll explain why in a note added to each of their body pages, and there will probably be a blog post too.  This probably doesn't warrant a special help page section. 

We don't tend to currently publicly explain why we don't list certain types of body ([though we did with courts](https://www.mysociety.org/2022/03/31/courts-on-whatdotheyknow-whats-the-verdict/)). We could have a help page section on bodies we don't list, and if we didn't list sports governing bodies we could note that there.

**Comment by RichardTaylor** [comment]
>We could have a help page section on bodies we don't list

Ticketed:
https://github.com/mysociety/whatdotheyknow-theme/issues/1574
