### ISSUE TITLE
Add ICO email address to help/unhappy

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#840]
User suggestion:

>If the ICO will usually accept an email with a link to the correspondence then maybe the help section could include the ICO email address, or even better a link which generated a standard email to the ICO containing that link,

Surprisingly we don't include the email address when we write:

> While the Information Commissioner asks for their form to be completed and evidence supporting a referral to be attached in practice we are aware they routinely consider referrals made via a simple email setting out the issues, containing a link to the request on WhatDoTheyKnow.com to provide evidence of the full history of the correspondence related to the request. 

at

https://www.whatdotheyknow.com/help/unhappy#refer-to-ico

The ICO offer a 

icocasework @ ico.org.uk email address at:

https://ico.org.uk/global/contact-us/email/

**Comment by mdeuk** [comment]
> The ICO offer a
> 
> icocasework @ ico.org.uk email address at:
> 
> https://ico.org.uk/global/contact-us/email/

I think I'd prefer to link to the webpage - just in case they change their email address.

Would you be happy with this, @RichardTaylor?

**Comment by RichardTaylor** [comment]
The email address required isn't very prominent on the linked page, and it's the second email address on the page.

**Comment by HelenWDTK** [comment]
The email address is now on this page
