### ISSUE TITLE
Update help pages to clarify ownership of requests once published

### ISSUE THREAD

**Issue by MattK1234** [mysociety/whatdotheyknow-theme#841]
As discussed on WDTK volunteer catch up call 24/06/2021 - https://docs.google.com/document/d/1ffX3BCFweAFH3QAWOP659HYvWYD9amdjTJ6O2uQ6ZjI/edit#

- Should make clear to pro and non pro users the requests aren’t “theirs” once published.  
- Treat like publishing under Creative Commons / Open licence 
- “You’re making this a public asset” .. “doing a public service”. 
- Issue with existing requests .. can’t retrospectively apply a public licence.

**Comment by garethrees** [comment]
At a minimum we need to clarify

* What circumstances might we hide material or destroy data on their requests
* Policies on re-embargoing. Need technical measures (https://github.com/mysociety/alaveteli-professional/issues/578) first, but even if they exist it needs to be clear in UI and/or help pages what the expectations should be.

**Comment by garethrees** [comment]
> Policies on re-embargoing… needs to be clear in UI and/or help pages what the expectations should be.

https://github.com/mysociety/alaveteli/issues/6567#issuecomment-1135678258 would be a good place for this.

Need to also check T&C's.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
