### ISSUE TITLE
Publicise position on log review when dealing with data breaches

### ISSUE THREAD

**Issue by MattK1234** [mysociety/whatdotheyknow-theme#842]
As discussed on WDTK volunteer catch up call 24/06/2021 - https://docs.google.com/document/d/1ffX3BCFweAFH3QAWOP659HYvWYD9amdjTJ6O2uQ6ZjI/edit#

Specify when we might do this (only in cases considered to be the most serious)
Specify the pros / cons of doing so, including the limited amount of useful information that can be gained, noting logfile retention periods and limited data on there the hit originates.
Cost?

**Comment by garethrees** [comment]
> the limited amount of useful information that can be gained

@sagepe could you write up a paragraph on our emerging "standard" practice here? I expect we have some phrasing from previous emails that we just want to generalise so that we can point data officers to.
