### ISSUE TITLE
Refusal advice for authority appears to have acted appropriately in send a followup action

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#844]
This doesn't seem quite right:
![image](https://user-images.githubusercontent.com/944656/123287006-50f9cb80-d506-11eb-8beb-ba1e89780e0a.png)

_Originally posted by @MyfanwyNixon in https://github.com/mysociety/whatdotheyknow-theme/issues/837#issuecomment-867713445_

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
