### ISSUE TITLE
Consider impact of draft online safety bill

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#847]
> louise: Has anyone read through the draft online safety bill? Feels like it might have implications for WDTK, in particular… We’ve got some time - not going to be in front of parl before early mid 2022, but would be good to know what the basic tenets are and where there might be things we need to think about

**Comment by RichardTaylor** [comment]
Discussion now at 

https://github.com/mysociety/whatdotheyknow-theme/issues/1171
