### ISSUE TITLE
PACAC inquiry into Cabinet Office's handling of FOI requests

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#848]
The Public Administration and Constitutional Affairs Committee launches an inquiry into the Clearing House processing of Freedom of Information (FoI) requests.

The Committee will be taking written submissions on its inquiry site until 31 August addressing the following issues;

* The Cabinet Office’s compliance with and implementation of the Freedom of Information Act 2020;
* The role and operation of the Cabinet Office Freedom of Information Clearing House including;
* Its handling of the cases that come to it;
* Its role in advising on and coordination of the handling of Freedom of Information cases across Government.
https://committees.parliament.uk/committee/327/public-administration-and-constitutional-affairs-committee/news/156429/cabinet-office-handling-of-foi-requests-inquiry-launched

– via https://groups.google.com/a/mysociety.org/g/research/c/iXRQWc-2UrY/m/y-zGa3u0AQAJ

**Comment by ajparsons** [comment]
Statistics-wise, I can pull something out for point 1 (and can make refs to our previous report). The latter points I have less to directly say on, but imagine others have more specific examples to pull out.
