### ISSUE TITLE
Review and improve advice for when no substantive response is received by the deadline

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#851]
When no response is received by the deadline we want to do a number of things:

* Inform users they can refer the matter to the ICO straight away, without needing to first complain to the public body. 
* Advise users on how they can effectively chase the public body and remind them of their duties under access to information law. 
* Offer detailed advice eg. on schools where the deadline is extended over holidays. This advice should be particularly prominent when relevant, eg. when we know a request went to a school. 

Two slightly tangential but relevant asides to consider:
* The FOI act requires responses to be provided promptly, so users might legitimately want to complain about a slow response well before the deadline. 
* Users often expect a prompt acknowledgement of their request and want to chase up a lack of acknowledgement after a few days, again well before the deadline. 

There is some good advice at 

https://www.whatdotheyknow.com/help/unhappy

> If you didn’t get a reply within 20 working days you can:
>
>    Refer your request to the Information Commissioner.

however there is a longstanding ticket for improving it to improve its clarity at #527

In terms of pointing users to that at the right point, the system is a bit inconsistent. The your request has been delayed banner says:

>Response to this request is delayed. By law, [public body] should normally have responded promptly and by [date]([details](https://www.whatdotheyknow.com/help/requesting#quickly_response)) 

The long overdue banner says:

> Response to this request is long overdue. By law, under all circumstances, [public body] should have responded by now ([details](https://www.whatdotheyknow.com/help/requesting#quickly_response)). You can complain by requesting an internal review. 

The internal review page now includes the snippets tool, and perhaps fortuitously, the top snippet shown by default is the one described as being for the circumstances of: 

>The authority has not confirmed or denied whether it holds the information. 

and states:

>I note that you have not confirmed or denied whether the authority holds this information, and have not applied an exemption that would remove this obligation.
>As you may be aware, Section 1(1) of the FOI Act (https://www.legislation.gov.uk/ukpga/2000/36/section/1) states that "Any person making a request for information to a public authority is entitled to be informed in writing by the public authority whether it holds information of the description specified in the request".
>I would be grateful if you could clarify whether or not this information is held, or specify which exemption of the duty to confirm or deny you are applying.

This ticket was raised after noting the most popular use of the new snippets system by far was in this case of no substantive response having been received by the deadline. 

Related to this issue is the idea for automatically identifying cases where there has been no response at all within the deadline. This may indicate an issue with outdated contact details on WhatDoTheyKnow. See #4935 and linked tickets. 

Also related is Automated appeals to ICO https://github.com/mysociety/alaveteli/issues/2819 which includes the idea of letting the regulator know about overdue requests.  

Suggested Actions:

* Rephrase the above snippet title and content to refer to "a lack of a substantive response".
* Rephrase the "long overdue" banner so it does not suggest requesting an internal review when there has been no response. 
* Have a special page and template response that isn't the general "internal review" page for use in this specific circumstance - given how common it is. 
* Consider how we can have snippets for the cases of a lack of a prompt response prior to the deadline, and for the lack of an acknowledgement.  We already have snippets for internal reviews, there is a ticket for snippets for drafting a request at https://github.com/mysociety/alaveteli/issues/6164, this is a proposal for extra snippets to use when sending a follow-up.  The internal review snippets are already being shown on send a follow-up form. I've ticketed this at: https://github.com/mysociety/alaveteli/issues/6370

**Comment by RichardTaylor** [comment]
A further ticket on improving the advice on referrals to the ICO is 

https://github.com/mysociety/whatdotheyknow-theme/issues/840

that is highly relevant here.

**Comment by RichardTaylor** [comment]
At the moment our advice doesn't cover what to do if an internal review response isn't forthcoming within the expected time-frame. 

We should advise users that it's reasonable to refer a case to the ICO if the public body won't carry out an internal review, or if, after 20 working days, there has neither been a substantive response to the internal review request or a reasonable justified extension set. 

Internal reviews should be completed in 20 working days, with an extension to 40 working days in exceptional cases. 

See section 5, on p21, of the Freedom of Information Code of Practice

https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/744071/CoP_FOI_Code_of_Practice_-_Minor_Amendments_20180926_.pdf

**Comment by RichardTaylor** [comment]
+1 

A user who hadn't had a substantive response by the deadline got in touch with the WhatDoTheyKnow team. 

We pointed them to https://www.whatdotheyknow.com/help/unhappy

They replied to say:

> thank you for your quick reply, and the link. I do apologize for bothering you, but I could not find the page with that very information!

**Comment by WilliamWDTK** [comment]
> We pointed them to https://www.whatdotheyknow.com/help/unhappy
> 
> They replied to say:
> 
> > thank you for your quick reply, and the link. I do apologize for bothering you, but I could not find the page with that very information!

I'm not sure that page is very well linked to.

**Comment by RichardTaylor** [comment]
This issue is very similar to the Alaveteli issue:

* https://github.com/mysociety/alaveteli/issues/6950
