### ISSUE TITLE
Refusal detection, advice, and snippets for requests handelled under the Environmental Information Regulations 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#852]
Currently I think the refusal detection, advice, and snippets focus only on FOI.

**Comment by garethrees** [comment]
> Currently I think the refusal detection, advice, and snippets focus only on FOI.

Yep!

EIR should be somewhat easier to add than FOISA (https://github.com/mysociety/whatdotheyknow-theme/issues/633) since we already have `eir` configured as an alternate legislation. Unclear on how much work it would be to add at this stage.

**Comment by RichardTaylor** [comment]
Something we could include is a reference to the higher threshold for deeming the public interest lies in withholding material when a public interest test is conducted under EIR than if it was conducted under FOI:

https://ico.org.uk/for-organisations/guidance-index/freedom-of-information-and-environmental-information-regulations/how-exceptions-and-the-public-interest-test-work-in-the-environmental-information-regulations/#a5

**Comment by RichardTaylor** [comment]
>we already have eir configured as an alternate legislation

However we don't currently set the law_used to eir in cases other than requests to eir_only bodies.  

That said we probably, counter-intuitively, don't need to identify threads as being EIR requests, or being dealt with under EIR in order to give EIR specific advice as usefully the text we'd be seeking to detect will be different, rather than as under FOI seeking to spot mentions of eg. "Section 12" or "s12" etc. we'd be looking for "Regulation 12" or "Regulation: 12" etc.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
