### ISSUE TITLE
Question on how pdfs get converted to html

### ISSUE THREAD

**Issue by Lextuga007** [mysociety/whatdotheyknow-theme#853]
I was wondering how the pdfs that my Trust is supplying in answers to the FOIs are being converted to html for example: https://www.whatdotheyknow.com/request/very_senior_managers_2#incoming-1733481. Is this done through code in the website, another program or manually? I'm trying to work out where my Trust is publishing FOIs in pdfs as these are not accessible and I want to change this.

Thanks in advance.

**Comment by garethrees** [comment]
Hey @Lextuga007 👋 

We use the [`pdftohtml` binary](https://github.com/mysociety/alaveteli/blob/0.39.0.0/lib/attachment_to_html/adapters/pdf.rb#L53-L61) via the [`poppler-utils `](https://github.com/mysociety/alaveteli/blob/0.39.0.0/config/packages.generic#L21) [package](https://packages.debian.org/stretch/poppler-utils).

We do have [an open issue](https://github.com/mysociety/alaveteli/issues/439) of using more modern tooling around this, but it's not on our immediate radar.

Happy to discuss further!

**Comment by Lextuga007** [comment]
Thanks so much for a quick response! I really appreciate it and I'll have a look at those tools. 

You are doing a great job at converting pfs but is it easier for them to be supplied in a more accessible format and what would that be? Html I'm sure is the best but not everyone who works with FOI is familiar with it of course!

**Comment by garethrees** [comment]
> Thanks so much for a quick response!

No problem!

> is it easier for them to be supplied in a more accessible format and what would that be? Html I'm sure is the best but not everyone who works with FOI is familiar with it of course!

Just to check my understanding, are you investigating what formats the trust could use to release information to citizens?

If that's correct, then I think it depends a little on the information that's being released.

For text-based responses, the main body of the email can be used – there's no specific need to include an attachment. [Here's one example](https://www.whatdotheyknow.com/request/weed_control_44#incoming-1840540) of an authority doing that.

One thing to note is that, for a number of reasons, we render _plain text_ versions of the email content. This does mean that any HTML formatting will be stripped, including [tables](https://github.com/mysociety/alaveteli/issues/1528) inserted into the main body content of an email.

If there's tabular data, we suggest CSV as a nice format to work with, but XLSX is also okay. Open source formats are preferred, though.

Of course, images can be attached as image files in an appropriate format.
