### ISSUE TITLE
Inconsistant capitalisation of exemption descriptions 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#856]
At

https://www.whatdotheyknow.com/help/unhappy#refusal-advice

currently we have

>Section 11 - Means by which communication to be made

and

>Section 21 - Information Accessible By Other Means

the latter is in title case, the former isn't. 

Obviously a very minor issue.

**Comment by garethrees** [comment]
Any preference on which to use? Easy to fix in https://github.com/mysociety/whatdotheyknow-theme/blob/master/config/refusal_advice/exemptions.yml.erb

**Comment by MyfanwyNixon** [comment]
mySociety house style is to capitalise the first letter of a title but not for subsequent words, so section 11 is correct and 21 should be amended. :)

**Comment by garethrees** [comment]
> section 11 is correct

Yeah, they use this style [in the legislation](https://www.legislation.gov.uk/ukpga/2000/36/section/11) too.
