### ISSUE TITLE
Limited number of citations?

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/whatdotheyknow-theme#857]
I've just identified that [an FOI request](https://www.whatdotheyknow.com/request/correspondence_with_the_oil_and) has led to multiple news stories/pieces of research, but it seems I can only add a maximum of three citations.

The links are:

- https://www.thetimes.co.uk/article/science-museum-gagged-by-sponsorship-deal-with-shell-58dt00kgr
- https://www.cityam.com/science-museum-under-fire-after-signing-gagging-order-with-shell-over-sponsorship-deal/
- https://greenworld.org.uk/article/science-museum-courted-sponsorship-oil-companies
- https://cultureunstained.org/smggaggingclause/ (this link confirms the FOI requests were made via WDTK and also refers back to [this prior request](https://www.whatdotheyknow.com/request/correspondence_with_royal_dutch#comment-98886))
- https://cultureunstained.org/2021/07/29/science-museum-signed-gagging-clause-with-sponsor-shell/
- https://www.ukscnlondon.org/science-museum-and-shell-sponsorship

and possibly more; I haven't looked too deeply.

**Comment by MyfanwyNixon** [comment]
cc @ashapond for your list of impacts.

**Comment by gbp** [comment]
Currently we limit how many citations are shown to the 3 latests ones. We don't limit how many citations can be added. Ideally we would have a 'show more' link which would either expand the lists or render to new request citations view.

**Comment by MyfanwyNixon** [comment]
Thanks Graeme - that explains it, and also reveals that this isn't clear to the user adding the citations! So if it does stay this way, perhaps a notification could be added.

**Comment by garethrees** [comment]
There's actually a subtle bug here, in that we don't show the _latest_ 3 but the first 3. Looks like @gbp just spotted that too given the edit:

> 3 ~latests~ oldest ones

I've created an issue https://github.com/mysociety/alaveteli/issues/6409.

**Comment by RichardTaylor** [comment]
While emails released at 

https://www.whatdotheyknow.com/request/correspondence_with_royal_dutch#comment-97896

have been explicitly cited (but not linked) at 

https://cultureunstained.org/smggaggingclause/#championbigoil 

the contract/agreement which is the core document behind the news does not appear to have been released via WDTK. 

In terms of the contract/agreement:

Channel Four states:
>This programme has exclusively obtained the sponsorship agreement 

https://www.channel4.com/news/revealed-science-museum-signed-gagging-clause-with-exhibition-sponsor-shell

The Times refers to:
>The contract, obtained by the group Culture Unstained...

https://www.thetimes.co.uk/article/science-museum-gagged-by-sponsorship-deal-with-shell-58dt00kgr

**Comment by garethrees** [comment]
Updated the ordering in https://github.com/mysociety/alaveteli/issues/6409.
