### ISSUE TITLE
Consider requesting a list of bodies with no request address from developers to review

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#859]
Only 20 of 178 such bodies can be viewed via www.whatdotheyknow.com/admin/

It's possible that if the full list was provided to admins there might be action which could be taken. 

A database extract containing the body name and WDTK link/url slug, and body number would be useful. 

Any volunteer, or group of volunteers, planning to take on this task could request data from developers to work on.

**Comment by RichardTaylor** [comment]
Ticket for making this available via the admin interface: https://github.com/mysociety/alaveteli/issues/6423

**Comment by RichardTaylor** [comment]
If such an extract is ever sought/provided including the tags and/or identifying bodies marked defunct might also be helpful.

**Comment by garethrees** [comment]
Fixed by https://github.com/mysociety/alaveteli/pull/7250.
