### ISSUE TITLE
Add address used by Ministry of Justice Digital & Technology team to model_patches.rb 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#860]
Add 
>D&TCDIO_Office at justice.gov.uk

to the list of no-reply email addresses as a workaround pending a fix of the underlying issue in Alaveteli

https://github.com/mysociety/alaveteli/issues/3465#issuecomment-810978437

fixing the underlying issue would be preferable as ideally users would be able to reply to this address.

**Comment by mdeuk** [comment]
> Add
> 
> > D&TCDIO_Office at justice.gov.uk
> 
> to the list of no-reply email addresses as a workaround pending a fix of the underlying issue in Alaveteli
> 
> [mysociety/alaveteli#3465 (comment)](https://github.com/mysociety/alaveteli/issues/3465#issuecomment-810978437)

This should be fixed, via the known workaround, when #866 is deployed.

> fixing the underlying issue would be preferable as ideally users would be able to reply to this address.

Agreed. The main issue here does need resolving - this workaround does 'work', but it is a nuisance for all parties concerned, so a fix for the underlying fault would certainly be preferable.
