### ISSUE TITLE
Remove suggestion people ask us for leaflets 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#861]
https://www.whatdotheyknow.com/help/volunteers#tellpeople

states:

> Ask us for leaflets to leave in your local library or coffee shop. 

In respect of the last two requests we've had for leaflets we've responded to say we don't have leaflets any more, so we should remove this text)

@MyfanwyNixon

**Comment by RichardTaylor** [comment]
This is a specific action, also noted as part of https://github.com/mysociety/whatdotheyknow-theme/issues/801

**Comment by confirmordeny** [comment]
This text must have been removed. I checked today and it isn''t there.
https://www.whatdotheyknow.com/help/volunteers#tellpeople
