### ISSUE TITLE
Review schools which have closed and reopened under the same name

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#863]
It appears some of our bulk updates have not properly handled the situation where a school has converted to an academy while retaining its name. 

eg. 

Stokesley School URN:121669 Community school closed on 31 March 2015. 
https://get-information-schools.service.gov.uk/Establishments/Establishment/Details/121669

its successor was
Stokesley School URN:141930 Academy converter
https://get-information-schools.service.gov.uk/Establishments/Establishment/Details/141930

In this case we'd detected the school had closed so marked it defunct, however we had not listed the successor. 

https://www.whatdotheyknow.com/body/stokesley_school

In this case we can use an oldurn:xxxx and urn:xxxx tag and add a note. 

We should try and identify and correct these issues in bulk. 

See also: https://github.com/mysociety/alaveteli/issues/6391

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/Authority_suggestions
