### ISSUE TITLE
Update the volunteer agreement

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#864]
Ideas:

* Elements of the mySociety staff handbook which are relevant to volunteers could be included. 

The volunteer agreement could be published.

**Comment by RichardTaylor** [comment]
mySociety has recently offered someone who made a contribution to the service 
 
>a formal “letter of appreciation” as a headed and signed PDF if it would be helpful for you to use as a reference.

An offer of a reference could be made in general to volunteers in the volunteer agreement. 

Perhaps it's obvious that a reference would be provided if a volunteer asked someone appropriate at mySociety if they'd be happy to provide one, but making the offer explicitly might make volunteers more comfortable asking.

**Comment by sallytay** [comment]
I've given the mySociety HR and Wellbeing manager a copy of the agreement to review and make any suggestions for improvements - along with giving her the comments and suggestions above. I'll update the ticket as soon as I get something back

**Comment by RichardTaylor** [comment]
Can we combine all the documents we send out to new volunteers into the volunteer agreement. 

We'd need to update it when the mySociety password policy changes but that appears to be a pretty stable document.

**Comment by mdeuk** [comment]
> Can we combine all the documents we send out to prospective volunteers into the volunteer agreement?
> 
> We'd need to update it when the mySociety password policy changes but that appears to be a pretty stable document.

Agreed. Once the copy is agreed we should be able to put this into one nicely formatted Google Doc which could then be issued automatically (as mentioned on #1294).

There could also be an opportunity to link this in with the end of year system access review that @garethrees usually arranges - meaning that those who perhaps haven’t filled in these docs in a while get a chance to review them again.

**Comment by sallytay** [comment]
+1 agree with this too.

I can add it in to the annual volunteer permissions audit process as this is now something that i do

**Comment by mdeuk** [comment]
> I can add it in to the annual volunteer permissions audit process as this is now something that i do

Sorry @sallytay, it must be the heat!

**Comment by RichardTaylor** [comment]
Include section on indemnifying volunteers for actions taken while volunteering.

**Comment by sallytay** [comment]
I have started the draft of the updated volunteer agreement.

This includes improvements of the existing text and a new section on Volunteer support.

While I know that recent cases have raised other issues that we may want to look to include in this when these have been agreed. The above draft is an improvement on what we currently have and can be updated further when we have those details.

The document below is open to comments and suggestions from the team.

https://docs.google.com/document/d/1AsnUEFEyGXhOVN4UOQ47ACO0ma6TJn1L/edit#

**Comment by sallytay** [comment]
Thank you for all you comments and suggestions for the updated volunteer agreement.

I will now pass this on to @crowbot @garethrees and the mySocietyHR and Wellbeing manager for further review

**Comment by RichardTaylor** [comment]
Linking to:

* https://github.com/mysociety/whatdotheyknow-theme/issues/1038 

* https://github.com/mysociety/whatdotheyknow-theme/issues/1104

It would be good to incorporate the output of those into the agreement. 

>I will now pass this on

I'd suggest developing the draft further first, so there is a clear proposal for review. Key issues could perhaps be identified first so agreement can be sought on those to guide the development of the draft.

**Comment by sallytay** [comment]
The draft agreement that I sent out already includes updated content based on suggestions taken both from other tickets and from comments made on the document that I initially sent out.

The idea here is to create an improvement on our current agreement, that's not to say that we won't update it again in the future. As we are about to recruit more people to the team I believe there is value in getting an improved agreement done so we are at least in a better place than we are now.

I agree that we do need to work on ticket #1104 but this is a lot work that will hold up having an improved agreement if we wait until this has been completed. This hasn't been scheduled to be worked on at this stage and is something that will be done when time allows.

Creating an improved agreement was part of ticket #1038 and I've included any suggestions that have come so far out of this project. At this time this is an ongoing open ticket that will updated once the current phase of recruiting the admin team is completed.

**Comment by FOIMonkey** [comment]
Will we need to re-sign this when done?

**Comment by RichardTaylor** [comment]
Volunteers often become aware of material on the service through their volunteering, and it isn't clear what they can do with it personally. Some clarity on expectations on this point might be useful. 

If a volunteer's attention is drawn to material by a takedown request presumably they shouldn't act personally in relation to that material while it is being considered, or if it is taken down.  What about if the material is republished, perhaps quietly, republished, are volunteers free to act on it then, even though it has come to their attention via their volunteering?

**Comment by RichardTaylor** [comment]
One approach could be to explain and encourage:

Explain:
>mySociety may not be in a position to support some activism based on material published on WhatDoTheyKnow due to issues related to capacity, risk appetite, and the need, and desire, to be, and to appear, impartial on areas unrelated to the organisation's core activities.

Encourage:
>mySociety encourages volunteers to act personally in respect of material which is publicly available on WhatDoTheyKnow, even if their attention was draw to it as a result of their volunteering.  [Possibly with a statement on take-downs under consideration]

Consideration should be given to what's being lost by this approach. By pushing activity to individuals the organisation loses out on content, reputation, traffic, impact - it's essentially turning away valuable donations. Perhaps there should be another step ... encouraging pursuit of a mutually beneficial arrangement with mySociety prior to individual action. 

I should note for public readers that there are additional terms applying to the administration of Pro requests.

**Comment by HelenWDTK** [comment]
Closing in favour of #1294
