### ISSUE TITLE
Consider tagging of Welsh bodies

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#868]
Currently we have:

https://www.whatdotheyknow.com/body?tag=welsh_establishment
https://www.whatdotheyknow.com/body?tag=wales
https://www.whatdotheyknow.com/body?tag=Wales

I think these are all in effect duplicates and should be merged. There is an open question on what to do with capitalisation, but I think it's fine to have a lower case "wales" tag, so long as it is associated with a category eg. "a Welsh public body". The lowercase tag is behind the scenes, and the properly capitalised category description is shown to the public.

**Comment by RichardTaylor** [comment]
welsh_establishment has been used in connection with schools.

**Comment by garethrees** [comment]
> I think it's fine to have a lower case "wales" tag, so long as it is associated with a category eg. "a Welsh public body". The lowercase tag is behind the scenes, and the properly capitalised category description is shown to the public.

I agree with this 👍

**Comment by garethrees** [comment]
> welsh_establishment has been used in connection with schools.

I'd go for "`wales`, `school`".

For anyone unfamiliar, `school` has [special behaviour](https://github.com/mysociety/whatdotheyknow-theme/blob/6810c9fed7ee57b86e5d23a7c55ba111437b444b/lib/model_patches.rb#L41) in WDTK.

**Comment by RichardTaylor** [comment]
>wales, school

Body tags on WhatDoTheyKnow are space separated so presumably the proposal is 

>wales school 

(I have just fixed lots of tags with rogue commas!)

I think schools have been tagged both welsh_establishment and school but that would be something to check when addressing this ticket.

**Comment by garethrees** [comment]
> (I have just fixed lots of tags with rogue commas!)

Ha, yeah, I know how the tags work – I was just being clear for any new volunteers that might pick this up that they are two distinct tags.

**Comment by WilliamWDTK** [comment]
With `welsh_establishment`, see also #1010

**Comment by garethrees** [comment]
linking to #908

**Comment by confirmordeny** [comment]
I have fixed the one remaining instance of "Wales" (with a capital W) tag.

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/Tagging_suggestions
