### ISSUE TITLE
Better account for school holidays in late calculations

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#872]
Recently received some correspondence from a school sent to a user after we prompted the user to follow up after a request became late.

> Thank you for contacting the school office today regarding your FOI request. I can confirm that your request was received in school on 19th July 2021 and I understand you were sent an email acknowledging receipt on this day. According to the Time Limits for Compliance under the Freedom of Information Act (Section 10) with 21st-23rd July being non-pupil days, 26th July - 3rd September being school holiday and 6th-7th September being non-pupil days a response is due by 1st October 2021. This date is based on the regulations that state that schools have whichever is the shorter of:
> 20  working days following the date of receipt, excluding any day which is not a school day (this effectively equates to a period of 20 school days); 
> 60 working days following the date of receipt. 
> The above variation to the response time can be applied without permision from the Information Commisioner. The relevant document can be viewed via this link: https://ico.org.uk/media/for-organisations/documents/1165/time-for-compliance-foia-guidance.pdf

We don't take "non-pupil" days into account in the [`SchoolLateCalculator`](https://github.com/mysociety/whatdotheyknow-theme/blob/master/lib/school_late_calculator.rb). We'll never get this completely perfect because schools run to their own schedule, but we may be able to be a bit more intelligent about the general summer holiday period.

**Comment by HelenWDTK** [comment]
Closing in favour of #477
