### ISSUE TITLE
Expand public justification for legal basis of processing

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#875]
Currently at 

https://www.whatdotheyknow.com/help/privacy#legal_basis

we write:

>The service also has a benefit to the public as any information released in response to the request is publicly available in a historic archive for anyone to use.

Our email templates for responding to takedown requests include:

>requests and their responses may well have been used to support news articles, academic research, lobbying, or other outputs we don't want to undermine any such activities.

I propose adding something like that latter sentence, after the first quoted sentence:

>The service also has a benefit to the public as any information released in response to the request is publicly available in a historic archive for anyone to use. Requests and their responses may well have been used to support news articles, academic research, lobbying, or other outputs and we are keen not to undermine any such activities by removing material from our website.

**Comment by RichardTaylor** [comment]
We could extend:

>There is also a benefit to authorities responding to requests, in that the automatic publication of the requests reduces duplicate requesting. 

to 

>There is also a benefit to authorities responding to requests, in that the automatic publication of the requests reduces duplicate requesting and sometimes requesters can be pointed to responses already provided via WhatDoTheyKnow.

**Comment by RichardTaylor** [comment]
We might want to add a sentence saying:

>When considering our processing of specific elements of personal information we do so on a case by case basis, taking into account the specific circumstances.

**Comment by RichardTaylor** [comment]
Text on necessity can be derived from 

https://github.com/mysociety/whatdotheyknow-theme/issues/1222

We should also mention human rights considerations as noted at:

https://github.com/mysociety/whatdotheyknow-theme/issues/996

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
