### ISSUE TITLE
Improve help page section: "Removal of public servants’ personal information from responses"

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#877]
https://www.whatdotheyknow.com/help/privacy#takedown

* We can link to our [standard] legitimate interests legal basis for publishing material rather than seeking to re-state it here. 
* We shouldn't say: "We will consider requests to remove the names of public servants when it seems that the interests, rights and freedoms of the data subject outweigh the public interest in publishing", as we consider all requests. The balance is between the interests of the data subject and our legitimate interests; though we consider our legitimate interests generally align with the public interest. 
* We might want to explain what we mean by a "a junior, non-decision making post" and be explicit that our view on this often differs from the views of public bodies.  We might want to link to ICO guidance relating to [personal data about 
public authority employees](https://ico.org.uk/media/for-organisations/documents/1187/section_40_requests_for_personal_data_about_employees.pdf) and [personal information more generally](https://ico.org.uk/media/for-organisations/documents/1213/personal-information-section-40-regulation-13.pdf). 
* We should make clear that those working for public bodies can (obviously) make right to erasure requests, the purpose of this section should be to note our specific policies / practices for dealing with such requests from public sector workers.

**Comment by RichardTaylor** [comment]
At 

https://www.whatdotheyknow.com/help/how#potentially_libellous

we mention "we are, under some circumstances, prepared to publish ... Requests for complaints and performance information about regulated professionals such as police officers, doctors and social workers."

Again here in relation to personal information we could note that where the personal information relates to a regulated professional such as a police officer, doctor or social worker, that might be a factor in favour of continued publication".

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
