### ISSUE TITLE
Improve navigation of help pages

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#883]
Review the text in each existing help section and potentially re title to make it completely clear to understand, making sure plain English is used. Perhaps add some new sections as a ‘gateway’ to finding the right advice. Titles of sections could be more active in their language. ‘What do I do if I’ve added personal information by mistake”  ‘If you need help with your request’ This would be something that I (Sally) could lead with input from WDTK and wider mySociety teams.

**Comment by HelenWDTK** [comment]
Closing in favour of #878 and #1453 amongst others.
