### ISSUE TITLE
Best practices for Information Managers

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#888]
i.e. people who _run_ the FOI system.

Could create a help page around how to:

* Create a good address – `foi@` address at a domain owned by the authority – makes it easier to transfer between individuals and email providers
* Auto acknowledgement with correct headers
* how to decommission an address (bounce message with pointer to new one)
* disclosure log
* publication scheme

Maybe we should propose something like robots.txt – `foi.json`:

```json
{
  "email": "foi@example.com",
  "publication_scheme": "https://…",
  "disclosure_log": "https://…"
}
```

Could integrate into https://github.com/mysociety/alaveteli/issues/4837 & other automated updates.

Wonder how many would actually add it though…

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
