### ISSUE TITLE
Sort out the `URN` tags

### ISSUE THREAD

**Issue by MattK1234** [mysociety/whatdotheyknow-theme#896]
https://www.whatdotheyknow.com/admin/bodies?utf8=%E2%9C%93&query=URN&commit=Search

The special code to note establishment information based on a tag string `urn` only works in lower case.

We have 13,527 instances of `URN` meaning that the link from the authority page to the DfE database is not displayed.

Suggest changing all these tags to be lower case in line with our generalised approach. Might need some CSV uploads to do this.

**Comment by garethrees** [comment]
Just to note that we've scheduled this for this sprint. I'll do it in the morning.

**Comment by garethrees** [comment]
Done!
