### ISSUE TITLE
Update guidance on using full name

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#897]
Our [help page](https://www.whatdotheyknow.com/help/privacy#real_name) states:

> See [this guidance](https://ico.org.uk/media/for-organisations/documents/1043418/consideration-of-the-identity-or-motives-of-the-applicant.pdf) from the Information Commissioner (October 2007)
> …
> Use a different form of your name. The guidance says that “Mr Arthur Thomas Roberts” can make a valid request as “Arthur Roberts”, “A. T. Roberts”, or “Mr Roberts”, but not as “Arthur” or “A.T.R.”.

The guidance is cited as October 2007, but it looks like the document was last updated in 2015 and no longer includes this statement.

It certainly used to, as this [BBC article](http://news.bbc.co.uk/1/hi/uk_politics/7826824.stm) indicates.

**Comment by confirmordeny** [comment]
We have updated the guidance. See 

- https://www.whatdotheyknow.com/help/privacy#real_name 
- https://ico.org.uk/media/for-organisations/documents/1164/recognising-a-request-made-under-the-foia.pdf 

I will close.
