### ISSUE TITLE
Testing Stripe

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#900]
We need to test Stripe for WDTK pro subscriptions.

Test all processes to make sure that they are working as they should be:
- New subscription
- Cancelling subscription
- Billing
- Automated emails
- plus ?
-
@sallytay will look at options of how we might do this, perhaps using mySociety credit card

**Comment by garethrees** [comment]
Just discussed and can't really remember what situation prompted this issue. Most likely a few reports of pro users who say they didn't get invoices/receipts (maybe they were expecting them to be "From:" whatdotheyknow, not Society Works?), but this is probably best addressed through https://github.com/mysociety/alaveteli/issues/7114.
