### ISSUE TITLE
Identify admins in user profile text

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#902]
To make sure that WhatDoTheyKnow admin team are identified in their WDTK user profiles.

Suggest that standard text could be used for all? 
"Official account used by the WhatDoTheyKnow.com team. If you need assistance, please contact us here: https://www.whatdotheyknow.com/help/contact"

13 out of the 22 admin users don't have any information on their profiles and others could update their profiles to include the text above, although they do identify themselves as pert of the WDTK team. Is there a way we could add this in bulk to the 13 users with no profiles or would they need to do that themselves?

Plus a could add a note to any 'onboarding' to the admin team to put this on the WDTK user profile and update the Wiki to ask admins to sign off annotations with 'WhatDoThyKnow Team' @sallytay happy to take this action

Sally

**Comment by sallytay** [comment]
Proposed next actions for this:

For WDTK staff admin accounts only that currently don't have any public profile information on their user account. @sallytay to check if they are happy to have the following text added to their user profile, if yes then add in bulk as detailed above:
“Official account used by the WhatDoTheyKnow.com team. If you need assistance, please contact us here: https://www.whatdotheyknow.com/help/contact”


Add a note to the Wiki https://wdtkwiki.mysociety.org/wiki/Policies#Annotations
On identifying yourself as either a volunteer or staff admin when making an annotation in your admin capacity, not applicable when making annotations in a personal capacity. Example text, "WhatDoTheyKnow.com volunteer" or "WhatDoTheyKnow.com support team" This is something our current team do, however a useful note for new members of the team.

Add to the next steps section of the induction call on the wiki, https://wdtkwiki.mysociety.org/wiki/Agenda_For_Induction_Call a note to advise new volunteer to update their WDTK user account profile to indicate that they are a WDTK volunteer. Using current volunteers account profiles as an example. Volunteers all use WDTK for different purposes so standard profile text isn't appropriate here.

Thoughts on the proposal welcomed along with any other guidance on this that you think could or should be added to the wiki.

Note: This was been raised to resolve an item flagged for the catch up call, that raised concerns that admins weren't always identifying themselves as such and that staff user profiles were not consistent.

**Comment by RichardTaylor** [comment]
>For WDTK staff admin accounts only that currently don't have any public profile information on their user account....“Official account used by the WhatDoTheyKnow.com team. If you need assistance, please contact us here: https://www.whatdotheyknow.com/help/contact "

I think my above comments on this still apply even to WDTK staff admin accounts
https://github.com/mysociety/whatdotheyknow-theme/issues/902#issuecomment-954324802

**Comment by HelenWDTK** [comment]
I'm happy that all of the accounts of volunteer/staff admins who take public actions have a good bio in place, so I'm going to close this, as there are other issues covering the technical improvements.

**Comment by WilliamWDTK** [comment]
Although there is the issue of people still listed as being volunteers or whatever when they're not. For example, [Tom Steinberg](https://www.whatdotheyknow.com/user/tom_steinberg) is apparently the director of mySociety.
