### ISSUE TITLE
Show maps of coverage areas for regional water and sewerage companies 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#904]
We list regional water suppliers:

https://www.whatdotheyknow.com/body/list/regional_water

and bodies responsible for sewers:

https://www.whatdotheyknow.com/body/list/sewerage_undertaker

Ideally we'd show a map on each body's page showing the area they cover. 

Perhaps a first step would be to get the boundaries into MapIt ?

https://github.com/mysociety/mapit/issues/381

**Comment by HelenWDTK** [comment]
We have this though: https://www.whatdotheyknow.com/list/water_maps
