### ISSUE TITLE
Write a blog, or help page section, about what we expect, or hope for, from FOI officers

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#906]
This would cover the concept of a FOI officer being the representative of the requester within an organisation. 

Such text might offer a counterpoint to what some within public bodies might think the role of a FOI officer is.

**Comment by HelenWDTK** [comment]
Noted here: https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas#Suggestions_on_Github
