### ISSUE TITLE
Improve template response for "Hide the request and notify the user" in cases of "Personal correspondence"

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#913]
The text currently says:

>We do not allow requests for information via WhatDoTheyKnow about your personal circumstances. We have therefore hidden your request from other users.

The issue with personal correspondence is generally not FOI requests being made about personal circumstances. If people make valid FOI requests which relate to their personal circumstances that's usually fine. 

The issue is usually people sending personal correspondence to public bodies which has nothing to do with a FOI request. 

The text would be better as:

>We do not allow WhatDoTheyKnow to be used for personal correspondence with public bodies. We have therefore hidden your correspondence from other users. 

This is a specific case of #622 

See also: Alaveteli issues: Make all system emails editable by administrators https://github.com/mysociety/alaveteli/issues/6314 and  Enable administrators to change the default texts of notification emails https://github.com/mysociety/alaveteli/issues/4688

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
