### ISSUE TITLE
Allow a `climate` tag to be added to requests

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#918]
There has been reluctance to implement 

Expose per-request tags publicly and enable searching and browsing using such tags  https://github.com/mysociety/alaveteli/issues/2302

in a general way. 

Perhaps it could be trialled with a "climate" tag.

**Comment by RichardTaylor** [comment]
Related: https://github.com/mysociety/caps/issues/152

**Comment by HelenWDTK** [comment]
Climate tags are able to be added to requests. Closing in favour of #995
