### ISSUE TITLE
Deal specially with requests made relating to council's climate action plans 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#919]
Such requests could be made via a special link from pages such as 

https://data.climateemergency.uk/councils/cambridge-city-council/

with special tags set as described at 

https://www.whatdotheyknow.com/help/api

on WhatDoTheyKnow they could be presented along with links back to the source page, and grouped with other similar requests.

**Comment by garethrees** [comment]
I don't think this is an issue for WDTK, as it would require implementation via https://github.com/mysociety/caps/issues/152.
