### ISSUE TITLE
Compare gov.uk/government/organisations with our bodies database

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#929]
https://www.gov.uk/government/organisations

Beware though, the Government list includes apparently defunct organisations eg. 

https://www.gov.uk/government/organisations/accelerated-access-review

which appear to be a review body which was established in 2014 and produced a final report in 2016, so probably doesn't exist any more. 

and bodies which are part of other bodies eg. 

https://www.gov.uk/government/organisations/bona-vacantia

**Comment by RichardTaylor** [comment]
See also

https://www.gov.uk/government/groups

These "groups" may warrant a listing in their own right, or might warrant a mention in the notes of their relevant parent body.

**Comment by RichardTaylor** [comment]
+1 if we'd have been doing this we'd have spotted 

https://www.whatdotheyknow.com/body/uk_commission_on_covid_commemoration

sooner

**Comment by RichardTaylor** [comment]
>See also
>
>https://www.gov.uk/government/groups

If we'd have been reviewing that we'd have spotted 

https://www.whatdotheyknow.com/body/aesac

sooner

**Comment by confirmordeny** [comment]
closed and added here: https://wdtkwiki.mysociety.org/wiki/Authority_suggestions
