### ISSUE TITLE
Prevent alerts on the internal_admin_user account being turned off

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#931]
The WhatDoTheyKnow admin team use alerts set up on the internal_admin_user to alert the team to bounce / error messages. 

These keep getting turned off. 

We don't know how. Perhaps someone has a system which automatically follows links in emails (sounds a bit risky!). 

This is a ticket, which I don't really expect to be fixed, suggesting, making them impossible to turn off.

**Comment by garethrees** [comment]
Could patch [`User::EmailAlerts.disable_by_token`](https://github.com/mysociety/alaveteli/blob/0416f6f3e2932c14fba7f88d1b79e7d445ba2f36/app/models/user/email_alerts.rb#L9-L16) in whatdotheyknow-theme like:

```diff
diff --git a/app/models/user/email_alerts.rb b/app/models/user/email_alerts.rb
index 591c4a512..6d6e6474c 100644
--- a/app/models/user/email_alerts.rb
+++ b/app/models/user/email_alerts.rb
@@ -43,6 +43,7 @@ def initialize(user)
     #
     # Returns a Boolean.
     def disable
+      raise 'nope' if user.url_name == 'internal_admin_user'
       user.update(receive_email_alerts: false)
     end
```
