### ISSUE TITLE
Improve documentation around handling lost access

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#933]
Creation of a clearer definition and process of how to handle users that have lost their log in details or lost access to the email address that they used to set up the account.

Current details are here for reference.
https://wdtkwiki.mysociety.org/wiki/Policies#User_accounts

Need a clear policy on what we are able to offer in these circumstances that both protect the security of our user accounts and enable the user to continuing to use the service.

Sally

**Comment by RichardTaylor** [comment]
Specifically consider loss of the two factor authentication code.

**Comment by mdeuk** [comment]
> Specifically consider loss of the two factor authentication code.

Linking to #795 - we could do better in this area.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
