### ISSUE TITLE
Make a statement on mySociety's commitment to keeping the service running

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#934]
Those considering using the service for a project might want some assurance the service is going to continue to remain active for the foreseeable future. 

A clear statement in the help pages on this subject might help encourage, and enable, use of the service by those making professional, and in some cases, commercial, use of it.

**Comment by garethrees** [comment]
This seems more like a blog post than help page topic.

**Comment by mdeuk** [comment]
> This seems more like a blog post than help page topic.

Feels like it could be a bit of both - a carefully worded bit of boilerplate on the /help/about page (perhaps) with a link to something more substantive on the blog.

The latter would certainly help with maintainability, and if we were to tag any relevant blog posts we could simply link to the relevant tag or category, meaning it'd be easy to keep 'up to date'.

**Comment by garethrees** [comment]
Ooh, perhaps we could dynamically link to the most recent mySociety annual report – they're all `YYYY.mysociety.org`. The report is usually published just before the new year, but we'd be "covered" for _most_ of the year.

**Comment by RichardTaylor** [comment]
My idea was this is something it would be good to put somewhere someone considering making serious use of the service, would come across it.  Imagine someone starting a research project and wondering if they can rely on the service to be around to cite in a report / publication. 

Related to this subject the site states:

>We offer no guarantee as to the availability of WhatDoTheyKnow Pro, and will not be liable if WhatDoTheyKnow Pro is unavailable for any reason.  

https://www.whatdotheyknow.com/pro/pages/legal

I appreciate why that's there, but I'm wondering if that could be made more reassuring  with a ~"but we're not planning on disappearing anytime soon".

**Comment by RichardTaylor** [comment]
mySociety's latest annual report states:

>mySociety has established a separate designated reserves fund which represents a cash fund to be used if a worst case scenario emerged and the charity had to be closed down. These funds would be used to support an orderly close down in this event. These monies are set aside in a ring-fenced bank account, requiring trustee approval to use. At the end of the financial year this designated reserves fund stood at £0.180m (2019/20: £0.180m).

https://register-of-charities.charitycommission.gov.uk/charity-search/-/charity-details/3078648/accounts-and-annual-returns

I suspect that primarily relates to redundancy costs, but I would hope it also covers seeking to pass on projects / archive data so that WhatDoTheyKnow would either continue to run, or in some way remain accessible. 

See also the ticket for a download of all requests/responses https://github.com/mysociety/alaveteli/issues/2271 which might help keep the request/response database published.

**Comment by garethrees** [comment]
Going to close this as I don't think there's much to say here. We've been around for nearly 15 years and have no intention of stopping. We continue to seek funding for our UK services and operate them as best we can when funding is limited.

I suppose the one thing we could do that's very minimal but quite powerful is add "Established 2008" to the footer to demonstrate that longevity? I've done that in https://github.com/mysociety/whatdotheyknow-theme/pull/1357.

**Comment by RichardTaylor** [comment]
I still think this is a really important ticket. 

Imagine an organisation considering a project using FOI, and deciding if to use WhatDoTheyKnow or to make requests privately. Without some assurance the service will be around for the duration of the project they may have no choice but to make their requests outside of WhatDoTheyKnow. 

Some people do already take the risk, but it would be good to help inform those decisions, even if we can't provide an assurance of an ongoing service.  

I suppose one could point to the "no intention of stopping" statement in comment on this thread.

**Comment by garethrees** [comment]
Are there places that we've seen this done? The only example I can think of is Basecamp's “[Until the End of the Internet](https://basecamp.com/about/policies/until-the-end-of-the-internet)” policy. I think working something around this into our principles page is a better angle (https://github.com/mysociety/whatdotheyknow-theme/issues/1021).

I think just saying "we aim to keep going" gives zero additional confidence. It's like all those blogs that you see with a single post along the lines of "I've refreshed my site and I'm _definitely_ going to start blogging more regularly from now on…" – and it never happens.

The best way to give confidence is through signs of life – regular [site](https://github.com/mysociety/alaveteli/pulls?q=is%3Apr+is%3Aclosed) [improvements](https://github.com/mysociety/whatdotheyknow-theme/pulls?q=is%3Apr+is%3Aclosed), regular [blog posts](https://www.whatdotheyknow.com/blog) and [tweets](https://twitter.com/whatdotheyknow), etc.

I don't think we can make guarantees; the world is way too complex. I think we _can_ back up that we've been running – and continued to grow – for the last 15 years and through the ongoing projects make it clear that there's always new stuff coming.

**Comment by RichardTaylor** [comment]
I think the statement by Basecamp is excellent and it would be great to take inspiration from that and say what we can along those lines.

**Comment by RichardTaylor** [comment]
>We've been around for nearly 15 years 

A presentation to the mySociety Birmingham Team meeting discussed anniversaries and noted significant "birthdays" / anniversaries for services / organisations can give an impression of sustainability.  (See notes to slide 230). 

I also note the mention of "Permanence" on slide 17.  The context isn't clear. Perhaps "Permanence" is an organisational aim?  There might be some organisational strategy which links to this ticket.

**Comment by garethrees** [comment]
Closing as I don't feel an independent statement like this is of much value. It'll come through in other activities (15th birthday, mySociety 20th birthday, project funding announcements, etc)
