### ISSUE TITLE
Promote the service to business / commercial users

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#941]
Another Alaveteli site https://handlingar.se/ states 
>Business
>Learn more about public procurement, gain new insights with information and data through the platform.

https://about.handlingar.se

We have a "Journalist?" link but not a "Business user?" link. 

We could set out how Businesses do, and could, use FOI and WhatDoTheyKnow.

Apparently some businesses employ lawyers to make and follow up FOI requests for them. Making commercial requests for a charge could be something we could offer as a commercial service (using Pro and perhaps Projects ourselves). 

Some find business use of FOI / WhatDoTheyKnow distasteful, we could make the public interest case for transparency improving public sector procurement etc. 

There is some poor commercial use of FOI / WDTK already, some of which is borderline spamming or worse. 

Ticket arises from discussions at the Adessium / Swedish Postcode Foundation Reflection Workshop

**Comment by RichardTaylor** [comment]
Note businesses often use FOI requests to generate news to put in their press releases. We could encourage those kinds of requests being made via WDTK.

**Comment by garethrees** [comment]
Linking to a couple of known commercial users

* https://www.tussell.com/ (a previous volunteer worked there, IIRC)
* https://contractsadvance.co.uk/ (they make use of [tags](https://www.whatdotheyknow.com/search/tag:contracts-advance/all))
