### ISSUE TITLE
whatdotheyknow.com/admin currently giving  "Sorry, there was a problem processing this page" error when logged in as an admin

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#942]
Reproduced on two browsers. 

Spotted when closing change request 5153 and being redirected to /admin afterwards, but I doubt that's relevant. 

Not urgent. Not required for my routine workflow (or anyone else's as far as I know).

**Comment by gbp** [comment]
Hitting this error https://github.com/mysociety/alaveteli/issues/4326
