### ISSUE TITLE
Review listings of Electricity Licencees

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#943]
List available via:

https://www.ofgem.gov.uk/publications/list-all-electricity-licensees-including-suppliers

Some may not be subject to EIR, we might want to list them all anyway, if we consider they have a public function. 

There is one body listed which has been set up to provide a reserve supply to a single site, we could exclude that if we don't think it's subject to EIR.

**Comment by HelenWDTK** [comment]
https://wdtkwiki.mysociety.org/wiki/Authority_suggestions
