### ISSUE TITLE
Devise and implement systems for coordinating and encouraging WhatDoTheyKnow related activism

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#947]
This ticket is for building up, improving, and coordinating the systems / processes we have which support the activism element of our work. 

* Corralling and progressing blog, tweet and other publicity ideas.  
* Monitoring success. What do we monitor, where and how. (Including what we make public)
* Identifying opportunities to act on. 
* Promoting and progressing the activism related issues on this repository. 

We have strong systems supporting other aspects of work, eg. dealing with high risk cases, we could be more organised in respect of the community and activism element of what we do. 

The better we get at this the easier it should be for existing team members to work together, and for others to join-in productively.

This ticket is inspired by the initiation of the new monthly community and activism call; that call is a key part of the process, but there are other elements to organise too.

**Comment by HelenWDTK** [comment]
Closing as complete via C&A call, A&O journal, Project work and me (this is a routine part of my job 🙂)
