### ISSUE TITLE
Decide if and when WhatDoTheyKnow can/should make FOI requests as WhatDoTheyKnow

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#948]
Including, but not limited to,

* If we should make requests users ask members of the team to make as WhatDoTheyKnow
* Are there certain types of request which are always safe for us to make, eg. meeting papers for governing bodies / boards

**Comment by sallytay** [comment]
Adding notes from Community and Activism Meeting (09/12/21)

No one is keen on signing off requests as WDTK

Everyone very keen on a sliding scale – staff using WDTK in personal capacity, staff using WDTK signing off like “Gareth on behalf of mySociety” to mySociety/WDTK instigating a campaign akin to AskTheEU commissioners expenses campaign

**Comment by RichardTaylor** [comment]
I raised this ticket, in the form of a binary question - if we should make requests as WDTK [or not] - as a potential agenda item for a future Community and Activism Meeting following the rules for items for that agenda. 

>Gareth on behalf of mySociety
That is substantively the same I think as a request from WhatDoTheyKnow, in that both would in-effect be requests sent by mySociety - the legal entity making the request in both cases would be mySociety.  ([ICO guidance on requests by organisations](
https://ico.org.uk/media/for-organisations/documents/1164/recognising-a-request-made-under-the-foia.pdf?page=9))

Staff and volunteer members have occasionally personally made requests directly relating to their roles on WhatDoTheyKnow in the past, for example seeking to obtain contact details for public bodies to add to the WhatDoTheyKnow database, or to make requests about way requests made via WhatDoTheyKnow have been handled.

mySociety has also, as I understand it, made requests for research purposes (after giving doing so very careful consideration). 

I think the position we're in is that those types of request can continue, but we're not happy to go further. 

I thought that this was an important fundamental point to make a decision on in light of the establishment of the Community and Activism Meeting and the potential for wanting to make use of the service ourselves, as a group, as a form of activism. 

I personally support the stance taken, but as with all our policies we should be open to reconsidering it in the future.
