### ISSUE TITLE
Better Management and Monitoring stats

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#949]
From a suggestion on the old catch up call agenda:

We’re not monitoring eg. requests this month, idea on the sprint planning call to note new body additions/edits and that has started there (that’s campaigning mostly) .. we should consider what it’s useful to monitor and ideally get the monitoring automatic, and where appropriate, public. 

Google emailed us to say: “In November, you had 1.5M users visit your website (Google Analytics)”

Should consolidate what performance monitoring we do, how often, etc. Avoid duplication. 

Collating the stats is one thing, we also need to interpret them, spot issues, act if required etc. 
Note the stats collated at https://docs.google.com/spreadsheets/d/1VJnFwWvWcwBaVLBO2albvqbIxlGinLGkQcgDVW7YHAk/edit#gid=0 - 15% year on year growth in request numbers for WDTK (Presented to grant wrap up call).

**Comment by garethrees** [comment]
There's also the [WDTK Request Stats](https://docs.google.com/spreadsheets/d/1zY3EuOhanWjPPH43iwmV5fVDFvsS47IkDskZqQbbyMY/edit) sheet which has data from the [`stats:show`](https://github.com/mysociety/alaveteli/blob/0.40.0.0/lib/tasks/stats.rake#L3-L4) command going back as far as 2012. ProjectDB largely replaced this at some point, but for some purposes I found the spreadsheet better, so I've continued to update it in a very ad-hoc manner (~6-24 month intervals) when I've needed to.

**Comment by mdeuk** [comment]
We _may_ be able to use [Data Studio](https://datastudio.google.com) to collate some of this data in an intelligible way - we already use it for some of our Information Rights reporting, but we're just scratching the surface.

There is some powerful capability to ingest data and blend from multiple sources (including Google Analytics itself), and we can display data in a variety of ways; so there is the potential of having a dashboard with the management information available "at a glance".

**Comment by HelenWDTK** [comment]
We now do this as part of the inbox stats tracking. Data is auto gathered on a daily basis for total public requests, total embargoed requests and total citations. Authority additions are manually logged fortnightly in the admin and ops journal. There is a data studio report based of the analytics.

Closing as complete
