### ISSUE TITLE
Consider and update policy on removing material from public view while reports of data breaches are dealt with

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#952]
The current text at

https://www.whatdotheyknow.com/help/how#accidentally_released

says:

>The first person to see the complaint about an accidental data release will start by hiding the minimum amount of material required to excise the problem.

This could be read as suggesting we always remove accidentally released personal information, it does not include an assessment step and consideration of if we want to, and if we have a legal basis for, continuing to publish the material.  Sometimes an accidental release of personal information will not be a problem. 

>In the case of a serious breach we suggest that the authority self-reports to the ICO. If the authority doesn’t acknowledge the data breach we will contact the ICO ourselves. 

Recent practice has been to inform both the body and the ICO of serious occurrences.

**Comment by mdeuk** [comment]
Suggest intertwining this with #937, which covers off the mechanics in the background.

**Comment by RichardTaylor** [comment]
From me on a case-specific email thread, responding to a suggestion that we should remove material from public ([and even requesters'](https://github.com/mysociety/whatdotheyknow-private/issues/88)) view on the basis of "concern for safety":

>I think we should have a higher threshold for removing material.
>
>We should at least think there is a credible concern worth considering, and I also think even at this initial stage we should be considering the balance of interests.  We should be asking if what we know, or can reasonably assume, about the risks outweighs the interests in continued publication.
>
>If we took material down on the basis of merely a concern being raised then we could be prompted to remove all sorts of material from the service, making the service less useful, less reliable, and less likely to be used and trusted by serious users.
>
>The principle of minimal redaction is also key, as is consideration of the position that it's reasonable to assume we live in a law abiding society.
>
>As with everything proportionality and balance is important. 

I want to make the right decisions. I want to make good, defensible, decisions. 

I think we have an agreed principle of wanting to act responsibly.

**Comment by HelenWDTK** [comment]
Closing as overtaken by the process changes involving serious data breaches and #937
