### ISSUE TITLE
Create standard annotations 

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#954]
It would be useful to have standard annotations for certain situations that occur regularly (action from Review Meeting as suggested by @RichardTaylor)

These could be added to the Wiki for ease of access (https://wdtkwiki.mysociety.org/wiki/Policies#Annotations)

One to include: "We have redacted a name from one of the released documents, acting in line with our published policies on how we run our service."

Next steps to create Wiki page linked to above and add some standard suggested annotations.

Sally

**Comment by HelenWDTK** [comment]
Closing as complete
