### ISSUE TITLE
Review how the refusals tool is being used

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#955]
Follow-up to initial observations after the first month

https://www.mysociety.org/2021/07/12/one-month-in-how-the-refusals-tool-is-helping-people-appeal-foi-requests/

A review of usage in the first six months would be possible early in 2022. 

In addition to how much is the feature being used, and is it leading to the release of more information:

* Are users finding appropriate advice, and using appropriate snippets? 
* Are there more areas on which advice and snippets could usefully be offered?
* Do any of the pieces of advice / snippets need to be improved?

**Comment by garethrees** [comment]
Planned for Januarry in https://github.com/mysociety/research/issues/229.
