### ISSUE TITLE
Make it easier for admins to add an annotation as the WhatDotheyKnow user

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#956]
Switching between accounts while administrating the site is currently a bit annoying.

**Comment by mdeuk** [comment]
+1, this would be a real timesaver.

It really would be handy if we could have a role based permission which, say for instance, allowed you to tick a box underneath the annotation form, to indicate that you wished the annotation to be posted as a site account.

This would have the handy advantage of, perhaps, also creating a log file entry to show _who_ made the annotation, which would keep our accountability standards high.

Linking to https://github.com/mysociety/alaveteli/issues/229

**Comment by garethrees** [comment]
I think this is now somewhat easier through https://github.com/mysociety/alaveteli/pull/6918.
