### ISSUE TITLE
Consider tags which explain why a body is subject to access to information legislation

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#963]
Sometimes it is not obvious why a body is subject to FOI or other access to information legislation. 

We can, and do, deal with this via free text in the notes, however it might be useful to have a standard way of tagging bodies with a link to the relevant legislation which we consider they are subject to. 

A standard tag could prompt the presentation of specific text if the feature suggested at https://github.com/mysociety/alaveteli/issues/387 (Show note based on a public body's tags) was implemented. 

We may want to link bodies to either a specific part of the Schedule to one of the FOI Acts eg. 
https://www.legislation.gov.uk/ukpga/2000/36/schedule/1/paragraph/43A

or one of the core provisions of an Act eg. 
https://www.legislation.gov.uk/ukpga/2000/36/section/3

The solution might be an agreed tagging convention using a key:value eg. 

law:https://www.legislation.gov.uk/ukpga/2000/36/schedule/1/paragraph/43A

If agreed wiki and inline help/hint updates could be made. 

This would give more structure to our database.

**Comment by HelenWDTK** [comment]
Closing in favour of the other more general tagging issues that cover this. We have started to do this to some degree since the introduction of tag based notes.
