### ISSUE TITLE
Review and improve coverage of NHS urgent care (out of hours) providers 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#965]
They are subject to FOI via:

https://www.legislation.gov.uk/ukpga/2000/36/schedule/1/paragraph/43A

and in Scotland:
https://www.legislation.gov.uk/asp/2002/13/schedule/1/paragraph/33

**Comment by RichardTaylor** [comment]
Category started with those urgent care providers also running the 111 service in part of the country 

https://www.whatdotheyknow.com/body/list/urgent_care

**Comment by confirmordeny** [comment]
Now listed here: https://wdtkwiki.mysociety.org/wiki/Authority_suggestions
