### ISSUE TITLE
Add information to help pages on who else to contact for advice

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#967]
For example

You could try writing to your local Member of Parliament (MP) or councillors. You can find and write to your elected representatives
via: http://www.writetothem.com

You could contact the Parliamentary and Health Services Ombudsman.
 https://www.ombudsman.org.uk/making-complaint/what-we-can-and-cant-help/government-organisations-we-can-investigate/l

Your local Citizens Advice Bureau may also be able to assist in pointing you towards suitable advice.

**Comment by RichardTaylor** [comment]
Perhaps the question this advice is answering is something like:

>Do I really want to make a request for information?

While Freedom of Information laws and other access to information rights are very useful, they are not always the best tools to use in every situation.

Perhaps we could have an analogy.. while FOI is a useful hammer, not every situation is a nail.  

I understand this ticket arose in relation to support correspondence, so perhaps the advice could be included in the system at

https://www.whatdotheyknow.com/help/contact

so we can divert users unhappy with a public body to more appropriate routes for obtaining help and advice than writing to us. 

Of course FOI may be used to collect information of use in a complaints process, or to support lobbying of an elected representative, so what's needed is not always clear cut.

**Comment by garethrees** [comment]
We do have a little bit of this at https://www.whatdotheyknow.com/help/unhappy#other_means

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
