### ISSUE TITLE
Create robust process for verifying users ID for GDPR and account management requests

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#970]
This is for when an individual contacts us to either gain access to a user account (password resets etc), change a name on a user account or makes a GDPR RtE request in relation to an account and they have not contacted us from the email address registered to the account.

The first step should be to ask them to contact us from the account email address.

Second step -  If that is not possible what evidence would we accept as valid ID that they are the account owner.

I've made some suggestions but I'm sure there will be more.

> Ask them to confirm what email address was used to set up the account - although this could be guessable
> If it is an old work email address - proof that they did once have access to that email account
> Visual identification ? Although does that prove that they are the account owner, they could just have the same name
> Email the address registered to the account to ask for verification, if a response is received saying it isn't them that could help clarify the situation but equality no response may be received.

When agreed this should be written up and added to the policy page of the wiki

Other actions
> Make this process clear on help pages so that when we are contacted about this can refer individuals to the help page

Sally

**Comment by WilliamWDTK** [comment]
See:
mysociety/whatdotheyknow-private#67

**Comment by HelenWDTK** [comment]
Closing as complete via https://wdtkwiki.mysociety.org/wiki/Verifying_ID_Policy
