### ISSUE TITLE
Review coverage of bodies implementing "City Deal" arrangments and make coverage comprehensive

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#971]
26 City Deals in England

https://www.gov.uk/government/collections/city-deals

6 City Deals in Scotland:

https://www.gov.scot/policies/cities-regions/city-region-deals/

Tag, which could in future be linked to a category

https://www.whatdotheyknow.com/body?tag=city_deal

**Comment by HelenWDTK** [comment]
https://wdtkwiki.mysociety.org/wiki/Authority_suggestions

**Comment by confirmordeny** [comment]
typo corrected
