### ISSUE TITLE
Consider treating a NHS England Address as a no-reply address and adding it to model_patches.rb

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#973]
At

https://www.whatdotheyknow.com/request/waiting_times_for_gender_identit#incoming-1897539

We have a response from 

`england.foicrm@nhs.net`

stating:

>Please do not reply to this email. This message has been sent from a
central mailbox. To communicate with NHS England regarding Freedom of
Information (FOI) requests, enquiries or complaints we ask these are sent
directly to NHS England’s customer contact centre. 

the response asks that correspondence is sent to the main request address we use for NHS England. 

I think we should treat the address as a non-reply address. I'm not 100% certain of that so I'd appreciate someone else considering this and acting on it, not just acting. 

There are quite a lot of hits for "Please do not reply to this email" in correspondence with NHS England:

https://www.whatdotheyknow.com/body/nhs_england?query=%22Please+do+not+reply+to+this+email%22

**Comment by mdeuk** [comment]
> I think we should treat the address as a non-reply address. I'm not 100% certain of that so I'd appreciate someone else considering this and acting on it, not just acting.
> 
I'm not particularly happy that we have to consider this - the system is clearly doing _something_ with those messages, and it isn't bouncing them back; but, unless we can get hold of a contact at NHS England to clarify what is going on, I think the solution proposed is reasonable.

**Proposal:** We could attempt to reach out to the [NHSE Head of Information Governance](https://www.england.nhs.uk/contact-us/privacy-notice/nhs-england-as-a-data-controller/) and clarify the position; and if that fails, implement this change.

**Comment by HelenWDTK** [comment]
They're still doing this, but there are no issues when requesters do reply to the email address, so I don't think we need to treat it as a bounce.
