### ISSUE TITLE
Data collection improvements to enable better transparency reporting -  System Data

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#975]
Suggestions transfered from ticket #938 

> Count edits to outgoing message bodies as censor/redaction/takedown events. Consider also potential double counting there may be edits to outgoing messages which have subsequently been removed from public view. Request for Stats for the WDTK Transparency Report 2021 - 2 #922
>
> Could we perhaps collect some metadata within Alaveteli when generating a ban - e.g. similar to how we set a prominence reason on a request (a dropdown of pre-defined options, then a freeform text box). This might allow us to automate production of this statistic with a degree of certainty. Originally posted by @sallytay in #925 (comment) https://github.com/mysociety/whatdotheyknow-theme/issues/925#issuecomment-984443864 
>
> Linked Use preselected ban reasons and optionally notify banned users from within the web-system mysociety/alaveteli#6699 
>
> On the subject of better data on why censor rules were put in place:
> * mysociety/alaveteli#6487
> * mysociety/alaveteli#4626
>
> Work on why there are hide events with no recorded reason as noted at Request for Stats for the WDTK Transparency Report 2021 - 2 #922 (comment) (Would the status of the request not help us fill in the gaps here?)
>
> Do we need a system for hiding material without notifying users (this is one situation in which admins might not use the canned responses in the system which I suspect are related to the recorded hide events / reasons).

This will be formed into a better defined plan of work

**Comment by garethrees** [comment]
> Could we perhaps collect some metadata within Alaveteli when generating a ban - e.g. similar to how we set a prominence reason on a request (a dropdown of pre-defined options, then a freeform text box). This might allow us to automate production of this statistic with a degree of certainty.

This would be resolved by implementing https://github.com/mysociety/alaveteli/issues/6699#issuecomment-985716618. This doesn't include predefined _plus_ free text, but a set of default options that get used in most cases is easy enough to group by when running the data collection scripts.

**Comment by garethrees** [comment]
> On the subject of better data on why censor rules were put in place:
> 
> * https://github.com/mysociety/alaveteli/issues/6487
> * https://github.com/mysociety/alaveteli/issues/4626

The addition of https://github.com/mysociety/alaveteli/issues/6487 resolves this in a way that's Good Enough for next year. We can filter on the canned replacement text which usually implies the reason for which the rule was added.

**Comment by garethrees** [comment]
> Work on why there are hide events with no recorded reason as noted at Request for Stats for the WDTK Transparency Report 2021 - 2 https://github.com/mysociety/whatdotheyknow-theme/issues/922

Created an issue to enable this collection https://github.com/mysociety/alaveteli/issues/6790.

> Would the status of the request not help us fill in the gaps here?

Maybe it would help in some cases, but IDK, we'd have to dig in to the current data to see if it's useful. We can try that next year if we don't get https://github.com/mysociety/alaveteli/issues/6790 implemented by then.

**Comment by garethrees** [comment]
> Do we need a system for hiding material without notifying users (this is one situation in which admins might not use the canned responses in the system which I suspect are related to the recorded hide events / reasons).

We've already got this – hiding using the prominence field. I think this – and the auditability – is also resolved by https://github.com/mysociety/alaveteli/issues/6790.

**Comment by garethrees** [comment]
So to close this issue, the following need implementation:

- [ ] https://github.com/mysociety/alaveteli/issues/6699
- [ ] https://github.com/mysociety/alaveteli/issues/6790

**Comment by garethrees** [comment]
These are now done.
