### ISSUE TITLE
Public policy on re-embargoing correspondence

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#976]
Pro users can embargo correspondence threads. They are initially private and then made public. 

Sometimes a pro user (or ex-pro user!) asks for correspondence threads to be re-embargoed.
 
The agreed policy is:

>once published requests should not be re-embargoed.

Once published on WDTK takedowns for previously pro requests are to be considered as they would for any other requests.

Though as with all policies that doesn't preclude making an exception. 

Also the idea of a 15 minute edit window to allow for correction of mistakes was supported

https://docs.google.com/document/d/1ffX3BCFweAFH3QAWOP659HYvWYD9amdjTJ6O2uQ6ZjI/edit?pli=1#bookmark=id.izmusihoo8k

This policy could be published at 

https://www.whatdotheyknow.com/help/pro#how-do-i-publish-a-request

This is a more specific version of the issue at 

https://github.com/mysociety/whatdotheyknow-theme/issues/841

See also: 

* Prevent ability to embargo after requests have been published for a while https://github.com/mysociety/alaveteli-professional/issues/578

**Comment by RichardTaylor** [comment]
The issue for technical implementation of this policy is at:

https://github.com/mysociety/alaveteli/issues/6321

**Comment by RichardTaylor** [comment]
>Though as with all policies that doesn't preclude making an exception.

We might want to go further on when we might, and might not, make an exception. 

eg. Requests relating to mistakes drawn to our attention promptly will be considered sympathetically. We would be highly unlikely to remove material which has been published for some time and/or which we are aware has been cited by others.

**Comment by sallytay** [comment]
I agree that we should do this so that our team also have a clear policy on when to act so that constituency in decision making is easier for everyone

**Comment by sallytay** [comment]
Although this ticket is to add the policy publicly, I have added this on to our Wiki for reference for the team should they have to deal with a request for this https://wdtkwiki.mysociety.org/wiki/Category:Pro

**Comment by RichardTaylor** [comment]
Our transparency reporting should cover re-embargoing. It's a kind of takedown. 

Related:
https://github.com/mysociety/alaveteli/issues/2658
https://github.com/mysociety/whatdotheyknow-theme/issues/975
https://github.com/mysociety/whatdotheyknow-theme/issues/938

**Comment by garethrees** [comment]
The response I've been using when contacted about this:

```
We do have a grace period to handle mistaken publication, but it looks like your requests been public for around 2 weeks now.

Our general policy is not to remove substantive FOI requests [1] since the information may be useful to others and responses may have been referenced elsewhere. As such, we don’t allow re-embargoing requests once they have been public for some time.

I accept that we could make this policy clearer within WhatDoTheyKnow, so I’ve noted your case against our development tracker on this issue.

Best,

[1] https://www/.[whatdotheyknow.com/help/how#](http://whatdotheyknow.com/help/how#)information_removal
```

**Comment by FOIMonkey** [comment]
Current Pro Ts&Cs make no mention of any restrictions. It's presented as a privacy option on single requests without any rules attached to it, and with no limits on when and how it is to be used. The term embargo is not even used. 

![2022-08-24](https://user-images.githubusercontent.com/11962965/186377481-1a3545e7-d104-43fd-9bb0-19de9a50a8ee.png)


The help pages don't mention not embargoing previously public stuff at all either: https://www.whatdotheyknow.com/help/pro#private-requests. 

It's presented as a useful feature.

All of the above would need fixing.

**Comment by garethrees** [comment]
> The term embargo is not even used

I've edited the phrasing above to reflect the phrasing we use in app. "Embargo" is the term in the codebase, but we don't use it publicly.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
