### ISSUE TITLE
Possible new fields for Police Request Log and operation of the log

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#979]
Current fields:

>Date sent WDTK 
>From (email address)
>Request (Link if there is one))
>Brief summary requet (do not add PII)
>Acknowledged by WDTK(Date)
>Court Order required 
>Court Order Produced 
>Data released (Y / N) 
>Link to folder of disclosed/protected data if applicable

Consider:

* Number of individuals' data involved / number of accounts involved
* Which police force / law enforcement agency is involved. 
* A reference number - this might help tie all the threads relating to a case together. 
* We could separate "Court order produced" from type of order.
* If we are to use this sheet for deadline tracking we should probably note deadlines. 

Also consider if this sheet could be used for all requests for user data, not just police / law enforcement requests. 

>Link to folder of disclosed/protected data if applicable  
We should consider the retention period on this.

**Comment by sallytay** [comment]
Thank you for the suggestions: I've the following columns as suggested
Number of individuals' data involved / number of accounts involved
Which police force / law enforcement agency is involved.
We could separate "Court order produced" from type of order.

For the other suggestions
"If we are to use this sheet for deadline tracking we should probably note deadlines.
I'd set this up for the Transparency report to keep track of police requests. It isn't designed for deadline tracking so I'm reluctant to add more columns than we need for it's purpose. However we could add it in if others feel it would be useful.

>A reference number - this might help tie all the threads relating to a case together
To auto generate reference numbers would require formatting on the sheet that would complicate the basic data. I think the logged email address and the inbox labels should enable us to be able to link threads together. 

>Also consider if this sheet could be used for all requests for user data, not just police / law enforcement requests
I'd like to keep the police requests separate as this is what we identified for the transparency report. However, we could add a sheet for user data requests from other sources?

>Link to folder of disclosed/protected data if applicable We should consider the retention period on this.
Yes we should - I would propose 2 years in line with our inbox retention policy but would welcome others thoughts

**Comment by RichardTaylor** [comment]
>I'd like to keep the police requests separate as this is what we identified for the transparency report.

The Transparency Report Page issue covers all requests to for user data, and proposes a breakdown specifically highlighting those from police/law enforcement.  A manual transparency report has been described as a precursor to an automated transparency report/page.  

https://github.com/mysociety/alaveteli/issues/2658
https://github.com/mysociety/whatdotheyknow-theme/issues/910

**Comment by sallytay** [comment]
>The Transparency Report Page issue covers all requests to for user data, and proposes a breakdown specifically highlighting those from police/law enforcement

Yes, that is a good point. I've now updated the log to be a User data request log and add a column to help quickly identify requests from the police. I've also made a new inbox label for user data requests

**Comment by RichardTaylor** [comment]
Having reviewed previous cases often there is a delay between initial contact, and the notification of, and receipt of, a court order and sometimes a number of different email threads are involved. 

Having a case reference to tie the threads together would I think be a good thing.

**Comment by RichardTaylor** [comment]
Having reviewed previous cases another interesting set / distinction is those requests for or on behalf of public bodies vs those for/on behalf of individuals / private organisations. 

We could have a public sector field/flag.

We also need to take care to note who the request is ultimately on behalf of rather than who makes it. That a request comes via solicitors probably isn't so important, we want to categorise based on who the solicitors are acting on behalf of.

**Comment by mdeuk** [comment]
> Having reviewed previous cases another interesting set / distinction is those requests for or on behalf of public bodies vs those for/on behalf of individuals / private organisations.
> 
> We could have a public sector field/flag.
> 
> We also need to take care to note who the request is ultimately on behalf of rather than who makes it. That a request comes via solicitors probably isn't so important, we want to categorise based on who the solicitors are acting on behalf of.

Categorisation by type would be useful.

I'll make a perhaps naive assumption that, for the most part, any such requests will be police matters; but being able to give a headline figure would be a good thing to have in the transparency report - particularly if we look to automate part of its production.

**Comment by HelenWDTK** [comment]
I've added categorisation by type, but there are no plans to add reference numbers at present. Closing as complete.
