### ISSUE TITLE
Consider reducing retention period, and amount of personal data kept, for web-server logs 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#980]
To protect our users, especially whistleblowers and journalists, from situations where we are compelled by law to release elements of web-server logs consider:

* Recording less information 
* Retaining what we do record for less time

Acting on this would need a public policy change at:
https://www.whatdotheyknow.com/help/privacy#our_logging

and the associated technical changes to implement that policy. 

The current position reflects a previous decision on what is necessary and justified. We should keep it under review. 

Note:  Possible direct conflict here with the ticket covering an Alaveteli feature for IP based tools to assist with moderating the site to prevent misuse - https://github.com/mysociety/alaveteli/issues/2691

**Comment by mdeuk** [comment]
I think we would be wanting a steer from @sagepe and colleagues on benefit -vs- risk here.

Presumably, the log rotation periods were chosen with a particular reason in mind - is there scope to reduce them without causing challenge to the reliable function of site infrastructure?

E.g. by limiting data capture, does it impact on the ability to troubleshoot issues, prevent abuse, and so on.

cc: @garethrees, @gbp, @sallytay

**Comment by garethrees** [comment]
Yeah, it's a tradeoff between availability for debugging (somewhat frequent) and minimising what we hold for the very infrequent but more (sometimes negatively) impactful data requests.

I'm pretty comfortable with our current retention window.

**Comment by sagepe** [comment]
We currently keep the more detailed application logs for 60 days as stated on the Privacy page and the less detailed access logs for 30 days.

Even compressed, the application logs are currently around 6G in size. We have had cause to look back through these, but it's unusual to look back as far as 60 days. I wouldn't object to bringing these in-line with the 30 day rotation in use for the access logs.

**Comment by RichardTaylor** [comment]
Compare what we do to Signal App which proudly doesn't collect user-data:

https://signal.org/bigbrother/

**Comment by garethrees** [comment]
No plans to change what we're doing here right now. We don't collect anything out of the ordinary, and keep it pretty minimal in general.
