### ISSUE TITLE
Make support escalation policy more easily accessible 

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#981]
Suggestion from inbox thread in relation to a minor potential defamation report

 >It would be good to have the current escalation policy easily accessible.

Suggest that an escalation document being created from the original WDTK Review process change document
https://docs.google.com/document/d/1pIovTj5A7HpURCj0Q4CkC7oZyyIrtVTC3LvlLAjhFiM/edit# 

And that this is then added to the Wiki on the page below - or perhaps there is a more suitable page
https://wdtkwiki.mysociety.org/wiki/Monthly_review

**Comment by HelenWDTK** [comment]
The escalation criteria have been added to the review process page. Closing this as complete
