### ISSUE TITLE
Consider additional tags for other regulatory registrations

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#982]
Suggestion from inbox thread 

Context, in relation to: https://www.whatdotheyknow.com/admin/bodies/57562

Should we have additional tags for
Scottish Housing Regulator (and Welsh and English equivalent  if they exist)
Financial Conduct Authority
Property Factors
Office of the Information Commissioner

**Comment by RichardTaylor** [comment]
I think the proposal here might be for additional, standard, key:value tags. 

We do already have a very well used tag dpr:xxxxxx for references to the ICO register of Information Controllers. (DPR = Data Protection Register presumably). 

The only key:value pair mentioned in the in-line notes on a public body admin page is: 

>charity:NUMBER if a registered charity

There are others which are dealt with specially by the system, turning them into links, eg. ch:NUMBER for Companies House registration numbers. 

There are a number of issues here:

* Deciding on standardised tags to use, and documenting them. 
* Updating the in-line prompts on body admin pages to cover common cases - probably including all those which result in special actions, eg. links on body pages. 

This work links to improving the structure of our database of public bodies, hopefully making it easier to maintain in the future. 

See also an issue on deciding, and documenting, how we should be tagging NHS bodies:

https://github.com/mysociety/whatdotheyknow-theme/issues/828

**Comment by mdeuk** [comment]
Linking to #1360 / #1363

**Comment by HelenWDTK** [comment]
https://wdtkwiki.mysociety.org/wiki/Tagging_suggestions
