### ISSUE TITLE
Consider removing separate listing for NHS Improvement

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#983]
Note

>"NHS Improvement and NHS England have worked together as a single organisation since 1 April 2019, to help improve care for patients and provide leadership and support to the wider NHS."

https://www.gov.uk/government/organisations/nhs-improvement

Should we continue to have a separate listing for 

https://www.whatdotheyknow.com/body/nhs_improvement

One issue with this kind of change is if we mark it defunct that can be misleading when a body isn't actually defunct but has merged, and continued to exist but as part of a larger entity.

**Comment by RichardTaylor** [comment]
Note discussion on the problem of a "defunct" tag resulting in misleading text at

https://github.com/mysociety/alaveteli/issues/3593#issuecomment-1035027271

**Comment by HelenWDTK** [comment]
closing as complete
