### ISSUE TITLE
Privacy page section on sharing personal information when we are required to do so by law 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#984]
https://www.whatdotheyknow.com/help/privacy

currently states

>We do not share IP addresses with anyone else unless required to by law (for example in the course of a police investigation for which a court order has been received). 

and

>We will not disclose your email address to anyone else unless we are obliged to by law, or you ask us to. 

These two statements don't cover the full scope of requests for personal data we have received, and may receive in the future.

eg. a police request asking which account is linked to a specific email address isn't really covered by the statement on disclosing an email address. 

eg.2. requests for correspondence with the WhatDoTheyKnow team, or requests for correspondence which has been hidden from public view on the site, are isn't covered by either of the the two statements either.   

We could have a new Privacy Page section following the between "Research" and "Encrypted Transfer of Data" covering legal requests for user data. 

We could cover:

* Briefly how we deal with such requests
* The potential scope of such requests

**Comment by MyfanwyNixon** [comment]
As a result of the quarterly data protection review meetings, we currently have this internal doc awaiting approval: https://docs.google.com/document/d/1yHYEmeFQKDLbbR11-qU3I-OtoyRl6Duve_Gg_BqZ-hc/edit#

It could inform the basis of this. Please also feel free to feed the thoughts above into the doc.

**Comment by RichardTaylor** [comment]
>requests for correspondence which has been hidden from public view on the site,

We have one case from January 2015 where something like the following happened:

1. A firm of solicitors acting for a client asked us to remove some extraneous potentially defamatory material from a correspondence thread. 
2. We removed the material
3. They asked us for a copy of the material removed 

In that case we provided a copy of the information we had removed. The position taken was that we weren't too concerned about releasing the material as it had been previously public on the site. We didn't think we were breaching anyone's privacy.  We also noted we thought they could obtain a court order for the material if we refused.

**Comment by RichardTaylor** [comment]
Consider policy on informing people when we get requests for their personal information #814

**Comment by RichardTaylor** [comment]
Often notice of impending formal legal action seeking user data prompts us to retain/preserve user-data. We should explain our approach to this on the help pages.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
