### ISSUE TITLE
Consider listing all courts individually on WhatDoTheyKnow

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#986]
This is something which has been considered internally, but we could discuss publicly here. 

By "court" here I mean eg. "Chelmsford Crown Court", a location with an office, webpage, and specific email address. 

Courts are listed at

https://www.find-court-tribunal.service.gov.uk

Context:

Individual courts are generally not bodies in their own right. FOI requests for information held by courts can be made via our listing for the courts service: https://www.whatdotheyknow.com/body/hmcts 

Reasons to list:

* Requests for information from individual courts may be responded to more quickly and efficiently if they are sent directly to the court in question. Requests made to the courts service centrally may be forwarded to individual courts, and sometimes a requester is directed to make their request to an individual court. 
* Listing courts individually would promote the fact FOI requests can be made for information held by courts. 
* While there is [an exemption for information amounting to court records relating to "a particular cause or matter"](https://www.legislation.gov.uk/ukpga/2000/36/section/32), statistical information, information on spending, room usage etc. could all be requested and expected to be released by courts. 
* Those making requests to for information held by courts to the courts service centrally are sometimes advised to make their requests directly to the court. 
* Requests made to a series of individual courts may not be aggregated for the purposes of considering the cost limits, more information may be obtained via a series of requests made to individual courts than would be obtained via a request made to the court service centrally. 

Reasons against:

* There are rights of access to information from courts which which it would be irresponsible, and sometimes illegal, to publish. (eg. under [section 5.8 of the Criminal Procedure Rules](https://www.legislation.gov.uk/uksi/2020/759/article/5.8/made)) Courts may release such material in response to requests made via WhatDoTheyKnow resulting in its publication.  

Options:

* List a handful of high-profile courts (the risk mentioned above would still be present, and might be heightened with high profile courts). 
* Enable making requests to individual courts, but don't automatically publish responses, and only allow trusted users / admins to publish responses - making clear who took the decision to publish. 

Conclusion
* Listing individual courts on WhatDoTheyKnow is currently high risk, and probably not the best way to pursue greater transparency from the court system. 

Note: There are currently three courts listed on WhatDoTheyKnow :

https://www.whatdotheyknow.com/body/list/court

* [Supreme Court of the United Kingdom](https://www.whatdotheyknow.com/body/uksc)
* The [High Court of the Justiciary](https://www.whatdotheyknow.com/body/high_court_of_the_justiciary) which is the supreme criminal court of Scotland. 
* The [Judicial Committee of the Privy Council](https://www.whatdotheyknow.com/body/jcpc)

Due to the nature of the work of those courts they are probably lower risk listings than others. In the case of the Supreme Court they have their own FOI contact point, and publication scheme https://www.supremecourt.uk/about/freedom-of-information.html  so should be used to dealing responsibly and appropriately with FOI requests.

**Comment by RichardTaylor** [comment]
The access to information provisions in [section 5.8 of the Criminal Procedure Rules](https://www.legislation.gov.uk/uksi/2020/759/article/5.8/made)) were mentioned above, there are also access to information provisions in [Part 5 of The Civil Procedure Rules 1998](https://www.legislation.gov.uk/uksi/1998/3132/part/5/made).

**Comment by sallytay** [comment]
Action from Community and activism meeting to create a blog post from this ticket.

@MyfanwyNixon would this be something that you could help us with?

**Comment by MyfanwyNixon** [comment]
yep sure thing.

**Comment by MyfanwyNixon** [comment]
Here's a draft, with not that much changed from Richard's useful framework above: https://docs.google.com/document/d/1cX5XPV7uAvLsx3Wdyt8H4psBhOgMkRxQZfXxcL1xo8Y/edit#

**Comment by sallytay** [comment]
As discussed at the Community and Activism meeting on 29 March. We agreed with the suggestions made and this is now good to publish

**Comment by RichardTaylor** [comment]
Do continue to polish the language where necessary but in essence it’s good
to go.

Richard

**Comment by MyfanwyNixon** [comment]
Thanks, I've set it to go out on the mySociety blog first thing tomorrow, with Richard as author.
Have also ticked 'WDTK Only' so will see if that has any effect.

**Comment by garethrees** [comment]
> Have also ticked 'WDTK Only' so will see if that has any effect.

None! But I _like_ that we publish this on the mySociety blog too.

**Comment by garethrees** [comment]
We've considered this, decided not to, and [blogged](https://www.mysociety.org/2022/03/31/courts-on-whatdotheyknow-whats-the-verdict/) about it.
