### ISSUE TITLE
Comprehensively list Areas of Outstanding Natural Beauty Conservation Boards

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#988]
At the time of writing we have four:

https://www.whatdotheyknow.com/body/list/aonbcb

There are 34 in England according to 

https://www.gov.uk/guidance/areas-of-outstanding-natural-beauty-aonbs-designation-and-management

There are 46 in the UK listed at 

https://landscapesforlife.org.uk/about-aonbs/aonbs/overview

Could link to the map at https://landscapesforlife.org.uk/about-aonbs/aonbs/overview

**Comment by RichardTaylor** [comment]
Can we collaborate with [the National Association for Areas of Outstanding Natural Beauty](https://landscapesforlife.org.uk/) to

* Use their maps 
* Promote our listings
* Mutually link between our resources relating to these bodies

In terms of mapping, it appears the Government publishes mapping data for the areas in England:

https://data.gov.uk/dataset/8e3ae3b9-a827-47f1-b025-f08527a4e84e/areas-of-outstanding-natural-beauty-england
https://naturalengland-defra.opendata.arcgis.com/datasets/areas-of-outstanding-natural-beauty-england/explore

**Comment by RichardTaylor** [comment]
Conservation Boards for areas of outstanding natural beauty are established by order of a Secretary of State (as respects England) or the National Assembly for Wales (as respects Wales) under [section 86 of   Part IV of the Countryside and Rights of Way Act 2000](https://www.legislation.gov.uk/ukpga/2000/37/part/IV) .

**Comment by RichardTaylor** [comment]
We have tweeted to seek a volunteer or volunteers for this task

 https://twitter.com/WhatDoTheyKnow/status/1493683163947798538

**Comment by confirmordeny** [comment]
I have emailed a spreadsheet to the team mailbox.

**Comment by FOIMonkey** [comment]
I have added these to the site. They are currently all tagged aonbcb, but we might want to change that. From the email:

> An AONB is a defined area of land with special legal protection but the designation of an AONB does not in itself result in the creation of a new public. Two conservation boards have been established:
> The Chilterns Conservation Board.
> -The Cotswolds Conservation Board.
> Conservation boards are listed in Part VI of Schedule 1 of the Freedom of Information Act 2000 and are therefore subject to FOI.
> 
> WhatDoTheyKnow already lists the above together with Norfolk Coast Partnership and Surrey Hills Area of Outstanding Natural Beauty Board.
> 
> The following appear to be constituted as Joint Committees:
> Cannock Chase.
> Clwydian Range.
> Dee Valley.
> Surrey Hills. 
> I believe these are subject FOI under para 25 of schedule 1 of the Freedom of Information Act 2000.
> 
> Several AONB partnerships  are established as Joint Advisory Committee’s under Section 102(4) of the Local Government Act 1972 and would appear not to be subject to FOI. These appear to include:
> Blackdown Hills;
> Clwydian Range and Dee Valley;
> Forest of Bowland;
> High Wield;
> Howardian Hills;
> Isles of Scilly;
> Kent Downs;
> Llŷn;
> Malvern Hills;
> Mendip Hills;
> Nidderdale;
> Quantock Hills
> Shopshire Hills;
> Solway Coast; and
> Wye Valley
> 
> In these cases, the local authorities should hold copies of any advice provided and so most of the information should still be FOIable.
> 
> Some AONB partnerships appear to have been established without creating a new legal person (e.g. a trusts or forums).  It ought to be possible to make FOI requests to the local authority that holds the records in these cases.
> 
> As an aside, Cranborne Chase Area of Outstanding Natural Beauty has registered as a data controller with the ICO but this is the only instance I found apart from for the two conservation boards.
> 
> I am not sure that the differences in the way the AONB partnerships are constituted really matters to most users of your site  (especially given the wider rights of access conferred by the Environmental Information Regulation 2004) and it might be better just to list all of them on the site and tag all as "AONB".

**Comment by FOIMonkey** [comment]
I have additionally tagged all of these aonb, and tagged the joint committees with joint_committee

**Comment by RichardTaylor** [comment]
>Several AONB partnerships are established as Joint Advisory Committee’s under Section 102(4) of the Local Government Act 1972 and would appear not to be subject to FOI.

I've tagged these ones [advisory_committee](https://www.whatdotheyknow.com/body?tag=advisory_committee), [foi_no](https://www.whatdotheyknow.com/body?tag=foi_no) and [eir_only](https://www.whatdotheyknow.com/body?tag=eir_only)

We might want to be more specific with our tagging so that we can effectively campaign to get joint advisory committees which are covered by [S102(4) of the Local Government act 1972](https://www.legislation.gov.uk/ukpga/1972/70/section/102) brought under FOI; we are currently using the advisory_committee tag more broadly. 

I think that closes this issue. 

These would be great bodies to add images to. Appropriately licenced images are available via Wikipedia, Unsplash and Geograph. It would be great if we could add an image to a body page. For a related ticket see https://github.com/mysociety/alaveteli/issues/6586
