### ISSUE TITLE
Blog post on children's and young people's data

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#989]
Once we have made the privacy page update:

>Help page section on children and young people's data #870 

we could write an accompanying blog. 

This could be an opportunity to promote the use of the service by those seeking information on access to universities - where the requester is often a young person, and the information sought, and released, relates to young people. This use of the service is one I think is particularly powerful and which I am personally proud to be supporting. 

There is some relevant text in [the harms and benefits of running WhatDoTheyKnow draft blog post](https://docs.google.com/document/d/1e6U7Ys2HjVd5rQmNBmewpKlv7WRB-1wSxsA_391_Dck/edit?usp=sharing), which we are no-longer considering publishing as one long piece. 

The blog proposed in this ticket could also explain why we value publishing our policies and working, so far as we can, in public.

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
