### ISSUE TITLE
Canned Response Limit reached in WDTK Support Inbox

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#990]
The templates (Canned Responses) that we use in the support inbox are currently limited to 50 which means that at the moment if a new one is added to the-oldest one of this is removed.

This appears to be a fixed limited that can not be changed.

There are a few potential solutions to this

>We move some of the less well used canned responses from the inbox to the Wiki rather than have been listed in the inbox
>For some of the less well used canned response we can use the canned response back up document in the shared drive rather than have been listed in the inbox

I'm not sure that either of these are ideal as it means having to look them up outside of the inbox.

Or
>We could look at buying an add on from the Google work place market place such as [Canned Responses Ultimate](https://workspace.google.com/marketplace/app/canned_responses_ultimate_for_gmail/825825168615) 
To note there is a free add on called [Canned Responses Pro](https://workspace.google.com/marketplace/app/canned_responses_pro_for_gmail/1031481257984), but this has a limit of 30 which is less than we have now.

Or there maybe another option within the standard gmail options that I'm not aware of.

If anyone has any thoughts or suggestions on this please let me know

Sally

**Comment by RichardTaylor** [comment]
>The templates (Canned Responses) that we use in the support inbox are currently limited to 50 which means that at the moment if a new one is added to the-oldest one of this is removed.

Thanks for working out what has been happening here. I had noticed some of the canned responses had disappeared. 


> We could look at buying an add on from the Google work place market place such as Canned Responses Ultimate https://workspace.google.com/marketplace/app/canned_responses_ultimate_for_gmail/825825168615
>  To note there is a free add on called Canned Responses Pro, but this has a limit of 30 which is less 
than we have now.

If we were going down that route then we'd presumably try the free option first and upgrade if we liked it. 

It's not clear but installing this add-on may result in exposing the data in our Google account to the app developer, if that's the case we shouldn't use it. From a quick look it's not clear who the app developer is - in terms of a legal entity. 

In respect of G-Suite itsself there are approved general contract terms in place satisfying the requirements of the UK GDPR in relation to international transfer of data [[1](https://cloud.google.com/security/compliance/eu-scc),[2](https://cloud.google.com/files/2016-12-30-common-opinion-for-google-workspace.pdf)], as I understand it, we would need to assure ourselves these were in-place for this add-on, and that appears unlikely.

**Comment by garethrees** [comment]
> From a quick look it's not clear who the app developer is - in terms of a legal entity.

Looks like its https://www.bitqueues.com for both Canned Responses Pro and Canned Responses Ultimate. They have a Privacy Policy and EULA and their address is listed, but I don't know how one looks up the official company record of a US company.

**Comment by RichardTaylor** [comment]
>https://www.bitqueues.com/ 

But what is the legal entity behind that domain name / website? 

We have statements like:

>COPYRIGHT 2018 BITQUEUES.COM , ALL RIGHT RESERVED.

is BITQUEUES.COM an entity? A company?  

The [privacy policy](https://www.bitqueues.com/privacy-policy/) mentions "Bitqueues Software" - is that an entity? A company?  

> their address is listed

the address given is:

>12600 SE, 30th Street, Bellevue
>Washington, D.C.  9805. USA

* 9805 is not a valid zip code according to the US Postal Service zip code lookup  https://tools.usps.com/zip-code-lookup.htm?citybyzipcode
* I can't find a 30th Street in Bellevue, Washington, D.C. via Google Maps. 
* There is a property with an address of "12600 SE, 30th Street, Bellevue" in Washington State.  That property's zipcode is 98005.  Google results suggest it is a multi-family residential property. 

A website having an address listed is something which can generally help give one confidence in it, however in this case I think there may be two errors in the address, in both the zip code and the state.  That doesn't give me confidence. 

>I don't know how one looks up the official company record of a US company.

I don't think it's clear that any entity is a US company. 

The [EULA](https://www.bitqueues.com/eula/) states 

>This EULA shall be governed and interpreted by the laws of India and the appropriate venue and jurisdiction for the resolution of any disputes shall be exclusively the Jurisdiction of Courts of Chandigarh, India only. Both parties hereby consent to submit to the exclusive jurisdiction of Courts of Chandigarh only. 

I think that would be unusual for a US company.  

The consideration of the entity behind the add-on arose due to the content of the "permissions" tab at

https://workspace.google.com/marketplace/app/canned_responses_ultimate_for_gmail/825825168615

<img width="365" alt="Screenshot 2022-02-22 at 13 24 54" src="https://user-images.githubusercontent.com/547695/155141468-47c9c5af-c046-44fa-ac5b-acfdc8c09fc0.png">

==== 

I very strongly support staff and volunteers being having access to tools to enable them to fulfil their roles efficiently. Spending on tools such as that proposed could increase the value for money obtained from staff and enable volunteers to make a greater contribution for less time and effort, and would be the right thing to do.

**Comment by sallytay** [comment]
On balance I think we need to look at another approach to this due concerns raised.

My suggestions would be:

Currently all templates/canned responses can also be accessed from the canned response back up document that is linked from the wiki page. We could:

>Remove the 'snippets' from the inbox list and create an easily searchable Google doc in the shared drive, that would also be linked from the canned response wiki page. 
>Currently we have templates set up in the inbox pointing people to the GDPR Google Docs templates - we could remove these and add them as links to the wiki page instead
>I don't think there are any templates on the inbox list that we don't use anymore but if we still need to reduce the inbox list further we could remove any that aren't used much and advise people to use the link the canned response back up document

Any other ideas or suggestions are welcome

**Comment by RichardTaylor** [comment]
I think we should look at what is most used, and keep those. 

I use the "explain WhatDoTheyKnow snippet" a fair bit for example so think it should be easily accessible. 

I'd also like "updated-resent-thanks" back as that's one I commonly used. 

In cases of responses we use in certain specific situations eg. HMO landlord data, notes on the wiki are useful, but they need to be kept up-to-date. In almost all areas we develop and improve our practice constantly, keeping wiki templates up-to-date and in-line with current practice is another job. In some of the less common specific situations searching the inbox and mailing lists for recent-past practice and using that as a basis for a new response might be the most efficient option.

**Comment by sallytay** [comment]
Thank you for the suggestion Richard, that seems like a sensible approach. I'll look into the most used templates and make sure that they are all on the list - including "updated-resent-thanks". 

Yes I agree the wiki notes / canned responses should be kept up to date - which any of us can do as we have information to add or can be added to a ticket and assigned to me so that I can schedule to work if I can't do is straight away.

**Comment by sallytay** [comment]
Update:
I've removed the responses created for the LSE issue as we are not really using them, but have kept them on the canned responses back up document and left them listed on the Wiki, should we need them again


I've added the snippet "updated-resent-thanks". back onto the inbox list

We currently have 47 template (canned) responses stored within the inbox, although the limit is 50, currently when one is added one is removed. I'll try to work out why this is.

In the meantime, we have 7 canned response that are not currently listed in the inbox:
>Advice on documents sent via email
>New GDPR case
>Reply on site not to us 
>Post-response-to-offsite-address 
>Classification-correction 
>Explain Reactive Moderation 
>incorrect use of update email address form 

I've not managed to get any particularly good usage figures from the inbox, so my proposal is to remove:

Volunteer Application - Stage 1 and Volunteer Application - Stage 2 - it is generally  me that uses these and I'm happy to take the text from the back up document in the shared drive and I can add notes to the Wiki to help find them too

Then we have 5 templates that link to the Google doc templates for GDPR cases - we could remove these from the inbox list and just get them directly from the shared drive to free up the space on the inbox list, But I realise that this may not work for everyone.

Sally

**Comment by garethrees** [comment]
> my proposal is to remove Volunteer Application - Stage 1 and Volunteer Application - Stage 2

I'd agree with this. It feels like a less common case type and one we'd probably take a bit more time replying to anyway as the context can vary quite a bit.

**Comment by sallytay** [comment]
I've removed Volunteer Application - Stage 1 and Volunteer Application - Stage 2 from the inbox template list, they are still available in the shared drive and I've added a link to the Wiki to help with locating them if you need to.

I've also removed the individual inbox templates for the GDPR RtE document response templates. There is one template/canned response listed with an easy link to the template folder, called GDPR RtE document templates. These are listed with links on the Wiki canned response page already.

These means that I've added back in all the other canned responses that were missing from the inbox list. There are 47 listed. At this point if a new canned response is added, one is removed so we need to be aware of that if adding new responses.

There are remaining canned responses improvements on https://github.com/mysociety/whatdotheyknow-theme/issues/1060

**Comment by RichardTaylor** [comment]
It appears we may now have a surprising resolution to this. 

The new "[Inbox Monster](https://wdtkwiki.mysociety.org/wiki/Tracker/Inbox_Monster)"  - a custom "pane" made using Google Apps scripts enables unlimited canned responses / templates to be created and used. 

https://wdtkwiki.mysociety.org/wiki/Tracker/Inbox_Monster_templates
