### ISSUE TITLE
Published guidance on how to prepare a spreadsheet of public bodies for adding to WhatDoTheyKnow

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#991]
If we wanted to encourage people to help with issues such as 

* Comprehensively list Areas of Outstanding Natural Beauty Conservation Boards #988 

it would be good to have published advice on what the minimal required, and ideal, spreadsheet would look like. 

A sample Google Sheets spreadsheet might be an idea. 

We could have a one big Google Sheets spreadsheet with multiple tabs for different classes of body we're considering adding, but we don't generally want to share the data being collected too widely, and often these pieces of work take a long time, and many never get finished.

**Comment by RichardTaylor** [comment]
>A sample Google Sheets spreadsheet might be an idea.

[The published all authorities CSV](https://www.whatdotheyknow.com/body/all-authorities.csv) is in effect a sample spreadsheet, but it's rather large and potentially intimidating for someone seeking guidance on how to collect data on a small set of bodies.

Previous practice has been for volunteers to set up a shared Google sheet and populate the first few rows. In recent years it has been hard to get others interested in helping fill in the gaps though.

**Comment by RichardTaylor** [comment]
>[The published all authorities CSV](https://www.whatdotheyknow.com/body/all-authorities.csv) is in effect a sample spreadsheet,

Yes, to an extent, but the column headings are incompatible with the CSV upload system as noted at:

https://github.com/mysociety/alaveteli/issues/6443

**Comment by mdeuk** [comment]
> > [The published all authorities CSV](https://www.whatdotheyknow.com/body/all-authorities.csv) is in effect a sample spreadsheet,
> 
> Yes, to an extent, but the column headings are incompatible with the CSV upload system as noted at:
> 
> [mysociety/alaveteli#6443](https://github.com/mysociety/alaveteli/issues/6443)

This one is a nuisance - it does make bulk updates a bit more difficult, as without access to the Alaveteli console you have to 'cobble together' sources in order to use the public CSV as the basis for updates.

**Comment by HelenWDTK** [comment]
Closing as complete via https://alaveteli.org/docs/running/admin_manual/ - can point to that.
