### ISSUE TITLE
Specifically promote use of WhatDoTheyKnow to obtain climate / environmental information

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#995]
Inspired by the "climate helpdesk" service offered by the German access to information web-service FragDenDtaat

https://fragdenstaat-de.translate.goog/aktionen/klima-helpdesk

which includes

* Examples of "Current environmental inquiries"
* Inquiry Ideas
* A [specific FAQ](https://fragdenstaat-de.translate.goog/aktionen/klima-helpdesk/faq/?_x_tr_sl=de&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=sc) containing further "possible topics" for requests

**Comment by garethrees** [comment]
This would likely be implemented in the form of a landing page (https://github.com/mysociety/whatdotheyknow-theme/issues/442#issuecomment-1041273063), but +1 on separating out this theme into a specific issue given that we have a [Climate programme](https://www.mysociety.org/climate/) of work.

**Comment by RichardTaylor** [comment]
>Inquiry Ideas

I spotted a Twitter thread suggesting changes to hospital operating theatre heating and ventilation protocols could be more significant in terms of reducing carbon dioxide emissions than even staff travel arrangements:
 
https://twitter.com/pete_labib/status/1494035612667633666?s=21

FOI could be used to obtain hospital operating theatre heating and ventilation protocols. Information on the current state would enable informed lobbying for change.

**Comment by garethrees** [comment]
I was about to create an issue titled "Create a whatdotheyknow.com/climate page", but it's essentially the same as this, so I've renamed this issue to be a little more specific about implementation, and dump a couple of extra ideas.

* Cover EIR
* link to CAPE (https://github.com/mysociety/whatdotheyknow-theme/issues/1331)
* resent related case studies (https://github.com/mysociety/whatdotheyknow-theme/issues/1297, via https://github.com/mysociety/alaveteli/issues/6589)
* https://github.com/mysociety/whatdotheyknow-theme/issues/918

**Comment by HelenWDTK** [comment]
We're in the process of adding 50+ EIR specific topic pages as part of the PJMF work, which is as good as we're going to get without the ability to add landing pages.
