### ISSUE TITLE
Proposed note on Court Service and Ministry of Justice body pages 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#998]
Option 1:

>Requests may be refused citing [the "court records" exemption in section 32 of the Freedom of Information Act](https://www.legislation.gov.uk/ukpga/2000/36/section/32). You may have a right to access some such information as a result of the provisions in [Section 5.8 of the Criminal Procedure Rules](https://www.legislation.gov.uk/uksi/2020/759/article/5.8/made) and [Part 5 of The Civil Procedure Rules 1998](https://www.legislation.gov.uk/uksi/1998/3132/part/5/made). Please take care with requests reliant on the procedure rules as information may be released which it not appropriate to publish. Please [contact WhatDoTheyKnow](https://www.whatdotheyknow.com/help/contact) with any concerns promptly (there is a "report this request" option under "Actions" on each correspondence thread). 

Option 2:

>You may have a right to access some information held by the Court Service or Ministry of Justice as a result of the provisions in [Section 5.8 of the Criminal Procedure Rules](https://www.legislation.gov.uk/uksi/2020/759/article/5.8/made) and [Part 5 of The Civil Procedure Rules 1998](https://www.legislation.gov.uk/uksi/1998/3132/part/5/made). Please take care with requests reliant on the procedure rules as information may be released which it not appropriate to publish. Please [contact WhatDoTheyKnow](https://www.whatdotheyknow.com/help/contact) with any concerns promptly (there is a "report this request" option under "Actions" on each correspondence thread). 

[Material accessible under the procedure rules is subject to the [Section 21 "Information accessible to applicant by other means" exemption in the Freedom of Information Act too](https://www.legislation.gov.uk/ukpga/2000/36/section/21).]

Related:

* Consider listing all courts individually on WhatDoTheyKnow #986

**Comment by RichardTaylor** [comment]
It would be good to incorporate some examples of the kinds of information in question eg .court listing information and outcomes and judgments. 

Proposal:

>Requests may be refused citing [the "court records" exemption in section 32 of the Freedom of Information Act](https://www.legislation.gov.uk/ukpga/2000/36/section/32). You may have a right to access some such information, for example judgments/decisions, as a result of the provisions in [Section 5.8 of the Criminal Procedure Rules](https://www.legislation.gov.uk/uksi/2020/759/article/5.8/made) and [Part 5 of The Civil Procedure Rules 1998](https://www.legislation.gov.uk/uksi/1998/3132/part/5/made). Please take care with requests reliant on the procedure rules as information may be released which it not appropriate to publish. Please [contact WhatDoTheyKnow](https://www.whatdotheyknow.com/help/contact) with any concerns promptly (there is a "report this request" option under "Actions" on each correspondence thread).

**Comment by confirmordeny** [comment]
I have added such a note on HM Court and Tribunal Service and MoJ pages: https://www.whatdotheyknow.com/body/list/court_records_note
