### ISSUE TITLE
Tidy up test authorities and their requests

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#999]
We have 8 test authorities 

https://www.whatdotheyknow.com/body/list/test_authority

and one has some 708 [junk] requests

Can we delete them? 

In particular can we delete the one with the URL "mysociety" which has the potential for confusion?

Related note from email discussion:

>we do have a special tag (“test”) to exclude [bodies] from statistics.

 https://github.com/mysociety/alaveteli/blob/e024bba8/app/models/public_body.rb#L694-L696

A test body is sometimes useful, perhaps we could restrict ourselves to one?

**Comment by MattK1234** [comment]
I've been bold and got rid of a couple of test authorities that had no/one request(s).

I'm guessing someone else has blitzed some too as I can't find one with 708 requests.

If we're happy with cutting them back (I don't know what others may use them for) I'm happy to blitz all the old requests and delete down to one authority.

I'd also propose tagging any remaining test authorities `defunct` when not being used for testing, so they don't show up in the batch picker etc.

If we find we need more that one for a specific reason we can always create more.
